In [1]:
import os
import json
from glob import glob
from pathlib import Path
from urllib.parse import urlparse

import httpx
from tqdm import tqdm
import pandas as pd
from dotenv import load_dotenv
from huggingface_hub import login
from datasets import Dataset, load_dataset


ROOT_DIR = Path("../").resolve()
DATA_DIR = ROOT_DIR / "data"

/home/octoopt/workspace/projects/personal/data_enrichment/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def init_login():
    load_dotenv()
    login(os.getenv("HUGGINGFACE_TOKEN"))
    print("Login successful")

In [3]:
def download_image(image_url, save_path, timeout=10):
    """
    Download an image from a URL and save it to the specified path using httpx.

    Args:
        image_url (str): URL of the image to download
        save_path (str): Local path where to save the image (including filename)
        timeout (int): Request timeout in seconds

    Returns:
        bool: True if download successful, False otherwise
    """
    try:
        with httpx.Client() as client:
            response = client.get(image_url, timeout=timeout)
            response.raise_for_status()  # Raise an exception for bad status codes

            # Create directory if it doesn't exist
            os.makedirs(os.path.dirname(save_path), exist_ok=True)

            # Write the image to file
            with open(save_path, "wb") as file:
                file.write(response.content)

        print(f"✓ Downloaded: {save_path}")
        return True

    except httpx.RequestError as e:
        print(f"✗ Failed to download {image_url}: {e}")
        return False
    except Exception as e:
        print(f"✗ Error saving image: {e}")
        return False


def read_json(file_path):
    """Read and return data from a JSON file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"✗ File not found: {file_path}")
        return None
    except json.JSONDecodeError as e:
        print(f"✗ Invalid JSON in {file_path}: {e}")
        return None


def write_json(data, file_path, indent=4):
    """Write data to a JSON file."""
    try:
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=indent, ensure_ascii=False)
        print(f"✓ Written JSON to: {file_path}")
        return True
    except Exception as e:
        print(f"✗ Error writing JSON: {e}")
        return False

## Old days

In [4]:
DATASET_DIR = DATA_DIR / "raw" / "wikipedia_famous_people" / "famous_people.json"

In [9]:
ds = pd.read_json(str(DATASET_DIR))
ds.head()

,name,url,summary,image_url,categories,timestamp
0,Sacheus !Gonteb,https://en.wikipedia.org/wiki/Sacheus_!Gonteb,Rear Admiral Sacheus Randy !Gonteb is a Namibi...,NaN,"[Articles with short description, Living peopl...",2025-08-02 04:53:49.485904
1,1.Cuz,https://en.wikipedia.org/wiki/1.Cuz,"Abas Abdikarim Bakar, better known as 1.Cuz (b...",NaN,"[1997 births, 21st-century male rappers, Artic...",2025-08-02 04:53:51.707057
2,1da Banton,https://en.wikipedia.org/wiki/1da_Banton,"Godson Ominibie Epelle, professionally known a...",NaN,"[1994 births, 21st-century Nigerian musicians,...",2025-08-02 04:53:54.208175
3,1nonly,https://en.wikipedia.org/wiki/1nonly,"Nathan Scott Fuller (born April 6, 2004), bett...",NaN,"[2004 births, 21st-century American male rappe...",2025-08-02 04:53:56.621336
4,1ucid,https://en.wikipedia.org/wiki/1ucid,"Kwadwo Bedihene, known professionally as 1ucid...",NaN,"[20th-century births, Afrobeats musicians, All...",2025-08-02 04:53:59.252879

In [10]:
ds = ds.drop(columns=["image_url"])
ds.head()

,name,url,summary,categories,timestamp
0,Sacheus !Gonteb,https://en.wikipedia.org/wiki/Sacheus_!Gonteb,Rear Admiral Sacheus Randy !Gonteb is a Namibi...,"[Articles with short description, Living peopl...",2025-08-02 04:53:49.485904
1,1.Cuz,https://en.wikipedia.org/wiki/1.Cuz,"Abas Abdikarim Bakar, better known as 1.Cuz (b...","[1997 births, 21st-century male rappers, Artic...",2025-08-02 04:53:51.707057
2,1da Banton,https://en.wikipedia.org/wiki/1da_Banton,"Godson Ominibie Epelle, professionally known a...","[1994 births, 21st-century Nigerian musicians,...",2025-08-02 04:53:54.208175
3,1nonly,https://en.wikipedia.org/wiki/1nonly,"Nathan Scott Fuller (born April 6, 2004), bett...","[2004 births, 21st-century American male rappe...",2025-08-02 04:53:56.621336
4,1ucid,https://en.wikipedia.org/wiki/1ucid,"Kwadwo Bedihene, known professionally as 1ucid...","[20th-century births, Afrobeats musicians, All...",2025-08-02 04:53:59.252879

In [12]:
hf_ds = Dataset.from_pandas(df=ds)
hf_ds

Dataset({
    features: ['name', 'url', 'summary', 'categories', 'timestamp'],
    num_rows: 1300
})

In [14]:
data_id = "minhleduc/wiki_famous_person_00"

hf_ds.push_to_hub(data_id, commit_message="Initial commit")

Creating parquet from Arrow format: 100%|██████████| 2/2 [00:00<00:00, 92.34ba/s]
Uploading the dataset shards: 100%|██████████| 1/1 [00:03<00:00,  3.07s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/minhleduc/wiki_famous_person_00/commit/1fd688c7abaa1f6cbf506a834c2a75cbacca7549', commit_message='Initial commit', commit_description='', oid='1fd688c7abaa1f6cbf506a834c2a75cbacca7549', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/minhleduc/wiki_famous_person_00', endpoint='https://huggingface.co', repo_type='dataset', repo_id='minhleduc/wiki_famous_person_00'), pr_revision=None, pr_num=None)

## 02.10.2025

In [6]:
datafile = str(DATA_DIR / "german" / "german_artist_detail.json")
json_data = read_json(datafile)

In [12]:
count = 0

for data in json_data:
    image_url = data["image_urls"]
    if not image_url:
        continue
    image_url = image_url[0]
    name = data["title"].replace(" ", "_")
    download_image(image_url, f"images/{name}.jpg")

✓ Downloaded: images/Heinrich_Aldegrever.jpg
✓ Downloaded: images/Elisabeth_von_Adlerflycht.jpg
✓ Downloaded: images/Albrecht_Altdorfer.jpg
✓ Downloaded: images/Jean_Arp.jpg
✓ Downloaded: images/Asam_brothers.jpg
✓ Downloaded: images/Cosmas_Damian_Asam.jpg
✓ Downloaded: images/Egid_Quirin_Asam.jpg
✓ Downloaded: images/Isidor_Ascheim.jpg
✓ Downloaded: images/Jim_Avignon.jpg
✓ Downloaded: images/Johannes_Baader.jpg
✓ Downloaded: images/Caroline_Bardua.jpg
✓ Downloaded: images/Johann_Wolfgang_Baumgartner.jpg
✓ Downloaded: images/Barthel_Beham.jpg
✓ Downloaded: images/Hans_Bellmer.jpg
✓ Downloaded: images/Ella_Bergmann-Michel.jpg
✓ Downloaded: images/Joseph_Beuys.jpg
✓ Downloaded: images/Anna_and_Bernhard_Blume.jpg
✓ Downloaded: images/Bärbel_Bohley.jpg
✓ Downloaded: images/Eberhard_Bosslet.jpg
✓ Downloaded: images/Erwin_Bowien.jpg
✓ Downloaded: images/Pola_Brändle.jpg
✓ Downloaded: images/Jörg_Breu_the_Elder.jpg
✓ Downloaded: images/Jörg_Breu_the_Younger.jpg
✓ Downloaded: images/Hans_Burgkmair.jpg
✓ Downloaded: images/Niclas_Castello.jpg
✓ Downloaded: images/Dorothea_Chandelle.jpg
✓ Downloaded: images/Johann_Joseph_Christian.jpg
✓ Downloaded: images/Charles_Crodel.jpg
✓ Downloaded: images/Paul_Eduard_Crodel.jpg
✓ Downloaded: images/Wilm_Dedeke.jpg
✓ Downloaded: images/Johann_Melchior_Dinglinger.jpg
✓ Downloaded: images/Louise_Droste-Roggemann.jpg
✓ Downloaded: images/Albrecht_Dürer.jpg
✓ Downloaded: images/Otto_Eckmann.jpg
✓ Downloaded: images/Erwin_Eisch.jpg
✓ Downloaded: images/Knut_Ekwall.jpg
✓ Downloaded: images/Max_Ernst.jpg
✓ Downloaded: images/Lyonel_Feininger.jpg
✓ Downloaded: images/Johann_Michael_Feuchtmayer_the_Elder.jpg
✓ Downloaded: images/Franz_Xaver_Feuchtmayer_the_Younger.jpg
✓ Downloaded: images/Franz_Joseph_Feuchtmayer.jpg
✓ Downloaded: images/Franz_Xaver_Feuchtmayer.jpg
✓ Downloaded: images/Johann_Michael_Feuchtmayer.jpg
✓ Downloaded: images/Joseph_Anton_Feuchtmayer.jpg
✓ Downloaded: images/Karl_von_Fischer.jpg
✓ Downloaded: images/Ferdinand_Wolfgang_Flachenecker.jpg
✓ Downloaded: images/Elsa_von_Freytag-Loringhoven.jpg
✓ Downloaded: images/Johnny_Friedlaender.jpg
✓ Downloaded: images/Caspar_David_Friedrich.jpg
✓ Downloaded: images/David_Füleki.jpg
✓ Downloaded: images/Wolfgang_Ganter.jpg
✓ Downloaded: images/Heinrich_Gätke.jpg
✓ Downloaded: images/Isa_Genzken.jpg
✓ Downloaded: images/Mathias_Goeritz.jpg
✓ Downloaded: images/Ekkeland_Götze.jpg
✓ Downloaded: images/Henry_Gowa.jpg
✓ Downloaded: images/Carl_Grossberg.jpg
✓ Downloaded: images/Matthias_Grünewald.jpg
✓ Downloaded: images/Ignaz_Günther.jpg
✓ Downloaded: images/Matthäus_Günther.jpg
✓ Downloaded: images/Andreas_Gursky.jpg
✓ Downloaded: images/Hans_Haacke.jpg
✓ Downloaded: images/Alfred_23_Harth.jpg
✓ Downloaded: images/Kati_Heck.jpg
✓ Downloaded: images/Wilhelm_Heine.jpg
✓ Downloaded: images/Bettina_Heinen-Ayech.jpg
✓ Downloaded: images/Carola_Helbing-Erben.jpg
✓ Downloaded: images/Amalia_von_Helvig.jpg
✓ Downloaded: images/Augustin_Hirschvogel.jpg
✓ Downloaded: images/Hannah_Höch.jpg
✓ Downloaded: images/Heinrich_Hoerle.jpg
✓ Downloaded: images/Hans_Holbein_the_Elder.jpg
✓ Downloaded: images/Ottmar_Hörl.jpg
✓ Downloaded: images/Rebecca_Horn.jpg
✓ Downloaded: images/Johann_Erdmann_Hummel.jpg
✓ Downloaded: images/Maria_Innocentia_Hummel.jpg
✓ Downloaded: images/Otto_Hupp.jpg
✓ Downloaded: images/Jaan_Patterson.jpg
✓ Downloaded: images/Janosch.jpg
✓ Downloaded: images/Horst_Janssen.jpg
✓ Downloaded: images/Wolfgang_Joop.jpg
✓ Downloaded: images/Johann_Joachim_Kändler.jpg
✓ Downloaded: images/Leo_Kahn.jpg
✓ Downloaded: images/Johanna_Keimeyer.jpg
✓ Downloaded: images/Hans_Kemmer.jpg
✓ Downloaded: images/George_Kenner.jpg
✓ Downloaded: images/Georg_Friedrich_Kersting.jpg
✓ Downloaded: images/Ludwig_Kieninger.jpg
✓ Downloaded: images/Martin_Kippenberger.jpg
✓ Downloaded: images/Paul_Klee.jpg
✓ Downloaded: images/Leo_von_Klenze.jpg
✓ Downloaded: images/Mario_Klingemann.jpg
✓ Downloaded: images/Käthe_Kollwitz.jpg
✓ Downloaded: images/Thomas_Köner.jpg
✓ Downloaded: images/Rudolf_Kortokraks.jpg
✓ Downloaded: images/Gerhard_von_Kügelgen.jpg
✓ Downloaded: images/Diether_Kunerth.jpg
✓ Downloaded: images/Rainer_Maria_Latzke.jpg
✓ Downloaded: images/Heinrich_Leutemann.jpg
✓ Downloaded: images/Max_Liebermann.jpg
✓ Downloaded: images/Elfriede_Lohse-Wächtler.jpg
✓ Downloaded: images/Lore_Lorentz.jpg
✓ Downloaded: images/Markus_Lüpertz.jpg
✓ Downloaded: images/Bernd_Luz.jpg
✓ Downloaded: images/Walter_Lenck.jpg
✓ Downloaded: images/August_Macke.jpg
✓ Downloaded: images/Eduard_Magnus.jpg
✓ Downloaded: images/Franz_Marc.jpg
✓ Downloaded: images/Leo_Marchutz.jpg
✓ Downloaded: images/Master_of_the_Housebook.jpg
✓ Downloaded: images/Master_L._Cz..jpg
✓ Downloaded: images/Petra_Mattheis.jpg
✓ Downloaded: images/Christoph_Meckel.jpg
✓ Downloaded: images/Ada_Mee.jpg
✓ Downloaded: images/Johann_Peter_Melchior.jpg
✓ Downloaded: images/Adolph_Menzel.jpg
✓ Downloaded: images/Gerhard_Mevissen.jpg
✓ Downloaded: images/Alice_Michaelis.jpg
✓ Downloaded: images/Paula_Modersohn-Becker.jpg
✓ Downloaded: images/Manfred_Mohr.jpg
✓ Downloaded: images/Georg_Mühlberg.jpg
✓ Downloaded: images/Wolfgang_Müller.jpg
✓ Downloaded: images/Gabriele_Münter.jpg
✓ Downloaded: images/Georg_Nees.jpg
✓ Downloaded: images/Renee_Nele.jpg
✓ Downloaded: images/Gert_Neuhaus.jpg
✓ Downloaded: images/Natias_Neutert.jpg
✓ Downloaded: images/Markus_Oehlen.jpg
✓ Downloaded: images/Karl_Oenike.jpg
✓ Downloaded: images/Méret_Oppenheim.jpg
✓ Downloaded: images/Louise_Pagenkopf.jpg
✓ Downloaded: images/Otto_Pankok.jpg
✓ Downloaded: images/Bruno_Paul.jpg
✓ Downloaded: images/Paul_Eddie_Pfisterer.jpg
✓ Downloaded: images/Otto_Piene.jpg
✓ Downloaded: images/Friedrich_Preller.jpg
✓ Downloaded: images/Paul_Preuning.jpg
✓ Downloaded: images/Karin_Putsch-Grassi.jpg
✓ Downloaded: images/Neo_Rauch.jpg
✓ Downloaded: images/Margaretha_Reichardt.jpg
✓ Downloaded: images/Mirko_Reisser_(DAIM).jpg
✓ Downloaded: images/Alfred_Rethel.jpg
✓ Downloaded: images/Ottilie_Reylaender.jpg
✓ Downloaded: images/Gerhard_Richter.jpg
✓ Downloaded: images/Henry_James_Richter.jpg
✓ Downloaded: images/Hans_Richter.jpg
✓ Downloaded: images/Tilman_Riemenschneider.jpg
✓ Downloaded: images/Dieter_Roth.jpg
✓ Downloaded: images/August_Sander.jpg
✓ Downloaded: images/Hanns_Scharff.jpg
✓ Downloaded: images/Caroline_Friederike_von_Schlözer.jpg
✓ Downloaded: images/Walter_Schönenbröcher.jpg
✓ Downloaded: images/Adolf_Schreyer.jpg
✓ Downloaded: images/Simon_Schubert.jpg
✓ Downloaded: images/Thomas_Schütte.jpg
✓ Downloaded: images/Simon_Schwartz_(artist).jpg
✓ Downloaded: images/Kurt_Schwitters.jpg
✓ Downloaded: images/Franz_Wilhelm_Seiwert.jpg
✓ Downloaded: images/Zuzanna_Skiba.jpg
✓ Downloaded: images/Conrad_von_Soest.jpg
✓ Downloaded: images/Virgil_Solis.jpg
✓ Downloaded: images/Franz_Joseph_Spiegler.jpg
✓ Downloaded: images/Bodo_Sperling.jpg
✓ Downloaded: images/Birgit_Stauch.jpg
✓ Downloaded: images/Johannes_Stenrat.jpg
✓ Downloaded: images/Veit_Stoss.jpg
✓ Downloaded: images/Johann_Baptist_Straub.jpg
✓ Downloaded: images/Gunta_Stölzl.jpg
✓ Downloaded: images/Peter_Eduard_Stroehling.jpg
✓ Downloaded: images/Ruben_Talberg.jpg
✓ Downloaded: images/Elsa_Thiemann.jpg
✓ Downloaded: images/Elisabeth_Treskow.jpg
✓ Downloaded: images/Rosemarie_Trockel.jpg
✓ Downloaded: images/Ulay.jpg
✓ Downloaded: images/van_Ray.jpg
✓ Downloaded: images/Various_&_Gould.jpg
✓ Downloaded: images/Markus_Vater.jpg
✓ Downloaded: images/Peter_Vischer_the_Elder.jpg
✓ Downloaded: images/Wolf_Vostell.jpg
✓ Downloaded: images/Carl_Wagner_(painter).jpg
✓ Downloaded: images/Grete_Waldau.jpg
✓ Downloaded: images/Johann_Jakob_Walther.jpg
✓ Downloaded: images/Karl_Walther.jpg
✓ Downloaded: images/Petrus_Wandrey.jpg
✓ Downloaded: images/Karl_Josef_Weinmair.jpg
✓ Downloaded: images/Victor_Weisz.jpg
✓ Downloaded: images/Ralf_Winkler.jpg
✓ Downloaded: images/Adolf_Wissel.jpg
✓ Downloaded: images/Henry_Otto_Wix.jpg
✓ Downloaded: images/Gert_Heinrich_Wollheim.jpg
✓ Downloaded: images/Paul_Wunderlich.jpg
✓ Downloaded: images/Barbara_Yelin.jpg
✓ Downloaded: images/Gabriel_Zehender.jpg
✓ Downloaded: images/Ernst_Zehle.jpg
✓ Downloaded: images/Adolf_Ziegler.jpg
✓ Downloaded: images/Johann_Baptist_Zimmermann.jpg
✓ Downloaded: images/Albania.jpg
✓ Downloaded: images/Armenia.jpg
✓ Downloaded: images/Denmark.jpg
✓ Downloaded: images/Georgia.jpg
✓ Downloaded: images/Hungary.jpg
✓ Downloaded: images/Montenegro.jpg
✓ Downloaded: images/Russia.jpg
✓ Downloaded: images/Serbia.jpg
✓ Downloaded: images/Slovakia.jpg
✓ Downloaded: images/Switzerland.jpg
✓ Downloaded: images/United_Kingdom.jpg
✓ Downloaded: images/Faroe_Islands.jpg
✓ Downloaded: images/Gibraltar.jpg
✓ Downloaded: images/Jersey.jpg

In [5]:
# datafile = str(DATA_DIR / "german" / "politicians")
datafile = str(DATA_DIR / "wiki_other_nations")
datapaths = glob(datafile + "/**.json")
datapaths

['/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_002.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_003.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_001.json']

In [6]:
politician_profiles = []

for path in datapaths:
    json_data = read_json(file_path=path)
    politician_profiles += json_data


len(politician_profiles)

6167

In [7]:
politician_profiles[10]

{'title': 'Lauri Ylönen',
 'url': 'https://en.wikipedia.org/wiki/Lauri_Yl%C3%B6nen',
 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/The_Rasmus_-_2025250_125352_2025-09-07_ZDF-Fernsehgarten_-_Sven_-_5DS_R_-_0115_-_5DSR3551_%28cropped%3B_Lauri_Yl%C3%B6nen%29.jpg/250px-The_Rasmus_-_2025250_125352_2025-09-07_ZDF-Fernsehgarten_-_Sven_-_5DS_R_-_0115_-_5DSR3551_%28cropped%3B_Lauri_Yl%C3%B6nen%29.jpg',
 'summary': 'Lauri Johannes Ylönen (born 23 April 1979) is a Finnish singer-songwriter, best known as the co-founder and frontman of the Finnish alternative rock band The Rasmus .',
 'infobox': {'Born': '( 1979-04-23 ) 23 April 1979 (age\xa046) Helsinki , Finland',
  'Occupation': 'Singer/songwriter',
  'Instrument(s)': 'Vocals , guitar , piano',
  'Labels': 'Playground Music Universal Music ( Finland )',
  'Website': 'amanda.fm'}}

In [9]:
write_json(data=politician_profiles, 
file_path=DATA_DIR / "wiki_other_nations" / "other_country_singer.json")

✓ Written JSON to: /home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer.json

True

In [11]:
count = 0

save_dir = str(DATA_DIR / "images" / "other_nation_wiki")

for idx in tqdm(range(len(politician_profiles))):
    data = politician_profiles[idx]
    image_url = data["image_url"]
    if not image_url:
        continue
    name = data["title"].replace(" ", "_")
    local_path = f"{save_dir}/{name}.jpg"
    data['local_path'] = local_path
    download_image(image_url, local_path)

  0%|          | 2/6167 [00:00<43:59,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Democratic_Republic_of_the_Congo.jpg

  0%|          | 4/6167 [00:01<28:15,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Cuba.jpg

  0%|          | 5/6167 [00:01<27:27,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Netherlands.jpg

  0%|          | 7/6167 [00:01<21:14,  4.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Zida.jpg

  0%|          | 9/6167 [00:02<19:28,  5.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Felix_Zenger.jpg

  0%|          | 10/6167 [00:03<46:38,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/A._W._Yrjänä.jpg

  0%|          | 11/6167 [00:03<43:19,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lauri_Ylönen.jpg

  0%|          | 12/6167 [00:04<43:18,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kirsi_Ylijoki.jpg

  0%|          | 16/6167 [00:04<22:43,  4.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Windows95man.jpg

  0%|          | 17/6167 [00:06<57:19,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arttu_Wiskari.jpg

  0%|          | 18/6167 [00:06<52:38,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toni_Wirtanen.jpg

  0%|          | 19/6167 [00:07<1:00:57,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tapio_Wilska.jpg

  0%|          | 20/6167 [00:09<1:14:52,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pepe_Willberg.jpg

  0%|          | 21/6167 [00:09<1:19:10,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jenny_Wilhelms.jpg

  0%|          | 22/6167 [00:10<1:04:06,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jann_Wilde.jpg

  0%|          | 23/6167 [00:10<1:07:18,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jani_Wickholm.jpg

  0%|          | 24/6167 [00:11<1:09:18,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kristiina_Wheeler.jpg

  0%|          | 25/6167 [00:13<1:51:51,  1.09s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Theodor_Weissman.jpg

  0%|          | 27/6167 [00:14<1:24:59,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martti_Wallén.jpg

  0%|          | 29/6167 [00:15<1:00:59,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mirel_Wagner.jpg

  0%|          | 30/6167 [00:15<1:00:53,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leif_Wager.jpg

  1%|          | 31/6167 [00:16<1:02:18,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Voutilainen.jpg

  1%|          | 33/6167 [00:17<50:51,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emppu_Vuorinen.jpg

  1%|          | 35/6167 [00:17<47:00,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Veltto_Virtanen.jpg

  1%|          | 36/6167 [00:18<50:46,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jukka_Virtanen.jpg

  1%|          | 37/6167 [00:19<57:18,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olavi_Virta.jpg

  1%|          | 39/6167 [00:19<46:22,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maija_Vilkkumaa.jpg

  1%|          | 40/6167 [00:20<46:01,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erika_Vikman.jpg

  1%|          | 41/6167 [00:20<43:51,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pihla_Viitala.jpg

  1%|          | 42/6167 [00:21<51:51,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaarle_Viikate.jpg

  1%|          | 43/6167 [00:21<45:52,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paula_Vesala.jpg

  1%|          | 44/6167 [00:22<48:50,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ailamari_Vehviläinen.jpg

  1%|          | 45/6167 [00:22<42:25,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jenni_Vartiainen.jpg

  1%|          | 46/6167 [00:23<45:44,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saija_Varjus.jpg

  1%|          | 47/6167 [00:23<56:53,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mato_Valtonen.jpg

  1%|          | 48/6167 [00:24<1:00:52,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ville_Valo.jpg

  1%|          | 49/6167 [00:25<1:00:01,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jontte_Valosaari.jpg

  1%|          | 50/6167 [00:26<1:07:49,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Niko_Valkeapää.jpg

  1%|          | 51/6167 [00:26<57:56,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nils-Aslak_Valkeapää.jpg

  1%|          | 52/6167 [00:27<1:11:23,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juha_"Watt"_Vainio.jpg

  1%|          | 53/6167 [00:28<1:16:51,  1.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olavi_Uusivirta.jpg

  1%|          | 54/6167 [00:28<1:08:56,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Uniikki.jpg

  1%|          | 55/6167 [00:29<1:11:34,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lauri_Tähkä.jpg

  1%|          | 56/6167 [00:30<1:06:17,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/H._Olliver_Twisted.jpg

  1%|          | 57/6167 [00:30<1:03:18,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ex_Tuuttiz.jpg

  1%|          | 58/6167 [00:31<1:12:41,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tarja_Turunen.jpg

  1%|          | 61/6167 [00:32<45:49,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tuomo.jpg

  1%|          | 62/6167 [00:32<47:31,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johanna_Tukiainen.jpg

  1%|          | 63/6167 [00:33<56:12,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antti_Tuisku.jpg

  1%|          | 65/6167 [00:33<41:18,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Timo_Tolkki.jpg

  1%|          | 66/6167 [00:34<45:46,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jean_Theslöf.jpg

  1%|          | 67/6167 [00:35<51:27,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henry_Theel.jpg

  1%|          | 68/6167 [00:36<1:01:35,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suvi_Teräsniska.jpg

  1%|          | 69/6167 [00:36<1:05:04,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jonna_Tervomaa.jpg

  1%|          | 70/6167 [00:37<1:08:52,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irma_Tervani.jpg

  1%|          | 71/6167 [00:38<1:25:45,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vera_Telenius.jpg

  1%|          | 72/6167 [00:39<1:29:22,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liisa_Tavi.jpg

  1%|          | 73/6167 [00:40<1:19:57,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Tauriainen.jpg

  1%|          | 75/6167 [00:41<59:08,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kari_Tapio.jpg

  1%|          | 76/6167 [00:41<1:03:49,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juha_Tapio.jpg

  1%|▏         | 78/6167 [00:42<56:36,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/J._Alfred_Tanner.jpg

  1%|▏         | 79/6167 [00:44<1:28:06,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martti_Talvela.jpg

  1%|▏         | 81/6167 [00:45<1:08:20,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Taiska.jpg

  1%|▏         | 82/6167 [00:46<1:06:35,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reijo_Taipale.jpg

  1%|▏         | 83/6167 [00:46<1:02:25,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Annikki_Tähti.jpg

  1%|▏         | 84/6167 [00:47<1:04:16,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jussi_Sydänmaa.jpg

  1%|▏         | 85/6167 [00:48<1:07:44,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Astrid_Swan.jpg

  1%|▏         | 86/6167 [00:48<1:11:21,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meiju_Suvas.jpg

  1%|▏         | 87/6167 [00:49<1:10:43,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martti_Suosalo.jpg

  1%|▏         | 88/6167 [00:50<1:16:53,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gösta_Sundqvist.jpg

  1%|▏         | 89/6167 [00:50<1:10:05,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pekka_Streng.jpg

  1%|▏         | 90/6167 [00:51<1:06:57,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stig.jpg

  1%|▏         | 92/6167 [00:52<54:51,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Steen1.jpg

  2%|▏         | 93/6167 [00:52<53:11,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carola_Standertskjöld.jpg

  2%|▏         | 95/6167 [00:53<42:18,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ville_Sorvali.jpg

  2%|▏         | 96/6167 [00:53<46:21,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Topi_Sorsakoski.jpg

  2%|▏         | 97/6167 [00:54<49:53,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Riki_Sorsa.jpg

  2%|▏         | 98/6167 [00:55<53:07,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rauli_"Badding"_Somerjoki.jpg

  2%|▏         | 99/6167 [00:55<50:44,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyllikki_Solanterä.jpg

  2%|▏         | 100/6167 [00:55<43:53,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sinikka_Sokka.jpg

  2%|▏         | 101/6167 [00:56<40:47,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cristal_Snow.jpg

  2%|▏         | 102/6167 [00:57<1:00:00,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Axl_Smith.jpg

  2%|▏         | 103/6167 [00:58<1:28:41,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raimo_Sirkiä.jpg

  2%|▏         | 105/6167 [00:59<1:00:20,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Sippola.jpg

  2%|▏         | 106/6167 [01:00<1:09:15,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seija_Simola.jpg

  2%|▏         | 107/6167 [01:00<1:08:02,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heikki_Silvennoinen.jpg

  2%|▏         | 108/6167 [01:01<59:37,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jari_Sillanpää.jpg

  2%|▏         | 109/6167 [01:02<1:02:50,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elina_Siirala.jpg

  2%|▏         | 111/6167 [01:02<50:42,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Krista_Siegfrids.jpg

  2%|▏         | 112/6167 [01:03<52:01,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shatraug.jpg

  2%|▏         | 113/6167 [01:03<53:33,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sexmane.jpg

  2%|▏         | 114/6167 [01:05<1:13:00,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pete_Seppälä.jpg

  2%|▏         | 117/6167 [01:05<42:26,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johanna_von_Schoultz.jpg

  2%|▏         | 119/6167 [01:06<41:02,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sipe_Santapukki.jpg

  2%|▏         | 120/6167 [01:07<47:21,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandhja.jpg

  2%|▏         | 122/6167 [01:07<46:44,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyösti_Salokorpi.jpg

  2%|▏         | 123/6167 [01:08<49:05,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hiski_Salomaa.jpg

  2%|▏         | 124/6167 [01:09<49:25,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simo_Salminen.jpg

  2%|▏         | 125/6167 [01:09<51:01,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matti_Salminen.jpg

  2%|▏         | 126/6167 [01:11<1:14:37,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tuomo_Saikkonen.jpg

  2%|▏         | 127/6167 [01:11<1:04:47,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arja_Saijonmaa.jpg

  2%|▏         | 129/6167 [01:12<50:02,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anneli_Saaristo.jpg

  2%|▏         | 130/6167 [01:12<52:14,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martti_Saarinen.jpg

  2%|▏         | 131/6167 [01:13<52:24,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wimme_Saari.jpg

  2%|▏         | 132/6167 [01:14<1:04:25,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sami_Saari.jpg

  2%|▏         | 133/6167 [01:14<1:05:05,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hannes_Saari.jpg

  2%|▏         | 134/6167 [01:15<1:00:15,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Saaresto.jpg

  2%|▏         | 135/6167 [01:16<1:10:15,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruudolf.jpg

  2%|▏         | 136/6167 [01:16<1:13:21,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kauko_Röyhkä.jpg

  2%|▏         | 137/6167 [01:17<1:09:50,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jope_Ruonansuu.jpg

  2%|▏         | 139/6167 [01:18<1:01:27,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marion_Rung.jpg

  2%|▏         | 140/6167 [01:19<1:03:13,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vicky_Rosti.jpg

  2%|▏         | 142/6167 [01:20<51:32,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ronya.jpg

  2%|▏         | 144/6167 [01:21<1:05:15,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sebastian_Rejman.jpg

  2%|▏         | 145/6167 [01:23<1:27:04,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Redrama.jpg

  2%|▏         | 146/6167 [01:24<1:29:18,  1.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jay_Ray.jpg

  2%|▏         | 147/6167 [01:26<1:47:56,  1.08s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pia_Ravenna.jpg

  2%|▏         | 148/6167 [01:26<1:34:14,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Timo_Rautiainen.jpg

  2%|▏         | 149/6167 [01:27<1:24:33,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aulikki_Rautawaara.jpg

  2%|▏         | 150/6167 [01:27<1:10:04,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tapio_Rautavaara.jpg

  2%|▏         | 151/6167 [01:28<1:13:13,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mari_Rantasila.jpg

  2%|▏         | 152/6167 [01:29<1:13:59,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pasi_Rantanen.jpg

  2%|▏         | 154/6167 [01:29<55:21,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antti_Railio.jpg

  3%|▎         | 155/6167 [01:30<58:22,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raappana.jpg

  3%|▎         | 156/6167 [01:32<1:46:17,  1.06s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pyhimys.jpg

  3%|▎         | 157/6167 [01:34<2:03:57,  1.24s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Puu.jpg

  3%|▎         | 158/6167 [01:36<2:18:04,  1.38s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Samuli_Putro.jpg

  3%|▎         | 159/6167 [01:36<1:56:54,  1.17s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomi_Putaansuu.jpg

  3%|▎         | 160/6167 [01:37<1:39:52,  1.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Portion_Boys.jpg

  3%|▎         | 162/6167 [01:38<1:17:17,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaija_Pohjola.jpg

  3%|▎         | 165/6167 [01:39<49:23,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ulla_Pirttijärvi-Länsman.jpg

  3%|▎         | 167/6167 [01:39<45:11,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lea_Piltti.jpg

  3%|▎         | 168/6167 [01:40<51:26,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaani_Peuhu.jpg

  3%|▎         | 169/6167 [01:41<59:38,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pirkka-Pekka_Petelius.jpg

  3%|▎         | 170/6167 [01:42<1:04:49,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maukka_Perusjätkä.jpg

  3%|▎         | 172/6167 [01:42<44:38,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matti_Pellonpää.jpg

  3%|▎         | 174/6167 [01:43<38:04,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leena_Peisa.jpg

  3%|▎         | 175/6167 [01:44<57:25,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kari_Peitsamo.jpg

  3%|▎         | 176/6167 [01:45<1:05:48,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Päivi_Paunu.jpg

  3%|▎         | 178/6167 [01:46<54:36,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pete_Parkkonen.jpg

  3%|▎         | 180/6167 [01:46<45:31,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paperi_T.jpg

  3%|▎         | 181/6167 [01:47<45:10,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tauno_Palo.jpg

  3%|▎         | 183/6167 [01:48<42:38,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paleface.jpg

  3%|▎         | 184/6167 [01:49<56:58,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanna_Pakarinen.jpg

  3%|▎         | 185/6167 [01:49<58:02,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esa_Pakarinen.jpg

  3%|▎         | 187/6167 [01:50<40:17,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robin_Packalen.jpg

  3%|▎         | 189/6167 [01:50<34:27,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lilli_Paasikivi.jpg

  3%|▎         | 190/6167 [01:51<38:04,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jules_Näveri.jpg

  3%|▎         | 191/6167 [01:51<46:18,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Närhi.jpg

  3%|▎         | 192/6167 [01:52<47:05,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ann-Christine_Nyström.jpg

  3%|▎         | 193/6167 [01:52<42:15,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camilla_Nylund.jpg

  3%|▎         | 194/6167 [01:53<43:09,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Petri_Nygård.jpg

  3%|▎         | 195/6167 [01:53<38:18,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matti_Nykänen.jpg

  3%|▎         | 196/6167 [01:53<45:08,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Harri_Nuutinen.jpg

  3%|▎         | 197/6167 [01:54<46:08,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tuomari_Nurmio.jpg

  3%|▎         | 199/6167 [01:55<39:28,  2.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anne_Nurmi.jpg

  3%|▎         | 201/6167 [01:55<37:01,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/M._A._Numminen.jpg

  3%|▎         | 202/6167 [01:56<43:16,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Siiri_Nordin.jpg

  3%|▎         | 203/6167 [01:56<43:58,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reino_Nordin.jpg

  3%|▎         | 204/6167 [01:57<47:31,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nopsajalka.jpg

  3%|▎         | 206/6167 [01:57<37:24,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pertti_Neumann.jpg

  3%|▎         | 208/6167 [01:59<48:35,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jasmin_Mäntylä.jpg

  3%|▎         | 210/6167 [01:59<36:24,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jari_Mäenpää.jpg

  3%|▎         | 211/6167 [02:00<42:50,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lasse_Mårtenson.jpg

  3%|▎         | 212/6167 [02:00<49:10,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pate_Mustajärvi.jpg

  3%|▎         | 213/6167 [02:01<50:52,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Musta_Barbaari.jpg

  3%|▎         | 214/6167 [02:02<56:10,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Muska.jpg

  3%|▎         | 215/6167 [02:02<49:06,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michael_Monroe.jpg

  4%|▎         | 216/6167 [02:03<53:43,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milana_Misic.jpg

  4%|▎         | 217/6167 [02:03<51:54,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pelle_Miljoona.jpg

  4%|▎         | 218/6167 [02:04<54:12,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matthau_Mikojan.jpg

  4%|▎         | 220/6167 [02:04<46:12,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juha_Metsäperä.jpg

  4%|▎         | 221/6167 [02:05<51:27,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olivia_Merilahti.jpg

  4%|▎         | 222/6167 [02:06<54:36,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patrik_Mennander.jpg

  4%|▎         | 223/6167 [02:06<49:14,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Melleri.jpg

  4%|▎         | 224/6167 [02:07<1:03:47,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emilie_Mechelin.jpg

  4%|▎         | 225/6167 [02:08<1:08:12,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andy_McCoy.jpg

  4%|▎         | 226/6167 [02:09<1:04:46,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pauliina_May.jpg

  4%|▎         | 227/6167 [02:10<1:23:11,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karita_Mattila.jpg

  4%|▎         | 228/6167 [02:12<2:02:23,  1.24s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anne_Mattila.jpg

  4%|▎         | 229/6167 [02:13<1:57:29,  1.19s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matti_ja_Teppo.jpg

  4%|▎         | 231/6167 [02:14<1:22:57,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jarkko_Martikainen.jpg

  4%|▍         | 232/6167 [02:15<1:22:21,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariska.jpg

  4%|▍         | 234/6167 [02:16<1:20:12,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eeki_Mantere_(aka._Viktor_Kalborrek).jpg

  4%|▍         | 235/6167 [02:17<1:18:05,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pirkko_Mannola.jpg

  4%|▍         | 236/6167 [02:18<1:13:57,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Georg_Malmstén.jpg

  4%|▍         | 237/6167 [02:18<1:10:56,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eugen_Malmstén.jpg

  4%|▍         | 240/6167 [02:19<39:07,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Malmivaara.jpg

  4%|▍         | 241/6167 [02:19<45:50,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pave_Maijanen.jpg

  4%|▍         | 243/6167 [02:20<40:09,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maarit.jpg

  4%|▍         | 244/6167 [02:21<44:58,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tommi_Läntinen.jpg

  4%|▍         | 245/6167 [02:21<53:10,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hildá_Länsman.jpg

  4%|▍         | 246/6167 [02:22<55:36,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erja_Lyytinen.jpg

  4%|▍         | 248/6167 [02:23<44:55,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Luttinen.jpg

  4%|▍         | 249/6167 [02:23<48:33,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaija_Lustila.jpg

  4%|▍         | 250/6167 [02:24<50:18,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mira_Luoti.jpg

  4%|▍         | 251/6167 [02:25<1:02:52,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amadeus_Lundberg.jpg

  4%|▍         | 252/6167 [02:25<1:01:36,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Lund.jpg

  4%|▍         | 253/6167 [02:27<1:18:29,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alma_Lund.jpg

  4%|▍         | 254/6167 [02:28<1:20:08,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaakko_Löytty.jpg

  4%|▍         | 255/6167 [02:28<1:12:56,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesa-Matti_Loiri.jpg

  4%|▍         | 256/6167 [02:29<1:10:49,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jyrki_Linnankivi.jpg

  4%|▍         | 257/6167 [02:30<1:15:34,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalle_Lindroth.jpg

  4%|▍         | 258/6167 [02:30<1:16:55,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Petri_Lindroos.jpg

  4%|▍         | 259/6167 [02:31<1:15:17,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Lindroos.jpg

  4%|▍         | 260/6167 [02:32<1:13:05,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lill_Lindfors.jpg

  4%|▍         | 261/6167 [02:32<1:00:30,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olli_Lindholm.jpg

  4%|▍         | 262/6167 [02:34<1:26:08,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dave_Lindholm.jpg

  4%|▍         | 263/6167 [02:34<1:21:40,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helge_Lindberg.jpg

  4%|▍         | 264/6167 [02:35<1:16:40,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mathias_Lillmåns.jpg

  4%|▍         | 265/6167 [02:36<1:12:19,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mats_Lillhannus.jpg

  4%|▍         | 266/6167 [02:36<1:11:18,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tommi_Liimatta.jpg

  4%|▍         | 267/6167 [02:38<1:21:44,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juice_Leskinen.jpg

  4%|▍         | 268/6167 [02:38<1:17:56,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Päivi_Lepistö.jpg

  4%|▍         | 269/6167 [02:39<1:08:53,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikko_Leppilampi.jpg

  4%|▍         | 270/6167 [02:40<1:23:50,  1.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JP_Leppäluoto.jpg

  4%|▍         | 271/6167 [02:42<1:49:16,  1.11s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rosa_Lemberg.jpg

  4%|▍         | 272/6167 [02:42<1:40:44,  1.03s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ville_Leinonen.jpg

  4%|▍         | 275/6167 [02:43<57:38,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matti_Lehtinen.jpg

  4%|▍         | 276/6167 [02:44<57:10,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Walfrid_Lehto.jpg

  4%|▍         | 277/6167 [02:45<1:01:35,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Veikko_Lavi.jpg

  5%|▍         | 278/6167 [02:48<2:09:30,  1.32s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lea_Laven.jpg

  5%|▍         | 279/6167 [02:50<2:25:07,  1.48s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lau_Nau.jpg

  5%|▍         | 282/6167 [02:51<1:25:23,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olli-Pekka_Laine.jpg

  5%|▍         | 283/6167 [02:51<1:19:10,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ville_Laihiala.jpg

  5%|▍         | 284/6167 [02:52<1:09:54,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexi_Laiho.jpg

  5%|▍         | 285/6167 [02:52<1:08:40,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaija_Kärkinen.jpg

  5%|▍         | 286/6167 [02:54<1:38:48,  1.01s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Käärijä.jpg

  5%|▍         | 288/6167 [02:55<1:09:15,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikko_Kuustonen.jpg

  5%|▍         | 289/6167 [02:56<1:12:00,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mauno_Kuusisto.jpg

  5%|▍         | 290/6167 [02:57<1:16:18,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heikki_Kuula.jpg

  5%|▍         | 292/6167 [02:58<1:03:39,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alma_Kuula.jpg

  5%|▍         | 293/6167 [02:58<1:06:44,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanni_Kurkisuo.jpg

  5%|▍         | 294/6167 [02:59<1:13:12,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johanna_Kurkela.jpg

  5%|▍         | 295/6167 [03:00<1:07:18,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakari_Kuosmanen.jpg

  5%|▍         | 296/6167 [03:00<56:03,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jukka_Kuoppamäki.jpg

  5%|▍         | 297/6167 [03:01<1:01:46,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mira_Kunnasluoto.jpg

  5%|▍         | 302/6167 [03:02<29:09,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tom_Krause.jpg

  5%|▍         | 303/6167 [03:02<33:15,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Birgit_Kronström.jpg

  5%|▍         | 304/6167 [03:02<33:12,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pasi_Koskinen.jpg

  5%|▍         | 305/6167 [03:03<38:37,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Timo_Kotipelto.jpg

  5%|▍         | 307/6167 [03:04<34:55,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juho_Koskelo.jpg

  5%|▍         | 308/6167 [03:04<34:25,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arja_Koriseva.jpg

  5%|▌         | 309/6167 [03:05<38:26,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaisa_Korhonen.jpg

  5%|▌         | 310/6167 [03:06<56:10,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaija_Koo.jpg

  5%|▌         | 311/6167 [03:06<58:06,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anu_Komsi.jpg

  5%|▌         | 312/6167 [03:07<1:00:51,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Terhi_Kokkonen.jpg

  5%|▌         | 314/6167 [03:08<45:21,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pekka_Kokko.jpg

  5%|▌         | 316/6167 [03:08<39:22,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paula_Koivuniemi.jpg

  5%|▌         | 317/6167 [03:09<49:16,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Brita_Koivunen.jpg

  5%|▌         | 318/6167 [03:10<52:44,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ari_Koivunen.jpg

  5%|▌         | 319/6167 [03:10<54:39,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viktor_Klimenko.jpg

  5%|▌         | 320/6167 [03:11<1:06:49,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Litku_Klemetti.jpg

  5%|▌         | 321/6167 [03:12<1:06:48,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kirka.jpg

  5%|▌         | 322/6167 [03:13<1:04:42,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laila_Kinnunen.jpg

  5%|▌         | 323/6167 [03:13<1:08:04,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tuure_Kilpeläinen.jpg

  5%|▌         | 324/6167 [03:15<1:24:04,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hilkka_Kinnunen.jpg

  5%|▌         | 325/6167 [03:16<1:34:53,  1.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kikka.jpg

  5%|▌         | 326/6167 [03:17<1:35:48,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anssi_Kela.jpg

  5%|▌         | 327/6167 [03:18<1:33:24,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leo_Kauppi.jpg

  5%|▌         | 329/6167 [03:18<1:02:33,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katri_Helena.jpg

  5%|▌         | 330/6167 [03:19<1:06:13,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kasmir.jpg

  5%|▌         | 331/6167 [03:20<1:04:12,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karri_Koira.jpg

  5%|▌         | 333/6167 [03:20<43:00,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pernilla_Karlsson.jpg

  5%|▌         | 334/6167 [03:21<46:41,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/J._Karjalainen.jpg

  5%|▌         | 335/6167 [03:21<41:28,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Kares.jpg

  5%|▌         | 336/6167 [03:22<48:27,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tapani_Kansa.jpg

  5%|▌         | 337/6167 [03:22<52:58,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kana.jpg

  5%|▌         | 339/6167 [03:23<39:33,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karoliina_Kallio.jpg

  6%|▌         | 340/6167 [03:23<45:09,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ile_Kallio.jpg

  6%|▌         | 341/6167 [03:24<53:00,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Kakko.jpg

  6%|▌         | 343/6167 [03:25<46:03,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Järvinen.jpg

  6%|▌         | 344/6167 [03:25<45:15,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Järvinen.jpg

  6%|▌         | 346/6167 [03:26<48:02,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maikki_Järnefelt.jpg

  6%|▌         | 348/6167 [03:28<51:55,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pasi_Jääskeläinen.jpg

  6%|▌         | 351/6167 [03:28<39:19,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juno.jpg

  6%|▌         | 352/6167 [03:29<43:06,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erkki_Junkkarinen.jpg

  6%|▌         | 354/6167 [03:30<39:30,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jukka_Poika.jpg

  6%|▌         | 355/6167 [03:30<46:15,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juju.jpg

  6%|▌         | 356/6167 [03:31<57:04,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jonsu.jpg

  6%|▌         | 357/6167 [03:32<54:57,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesa_"Vesku"_Jokinen.jpg

  6%|▌         | 359/6167 [03:33<48:19,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jippu.jpg

  6%|▌         | 362/6167 [03:34<38:03,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jannika_B.jpg

  6%|▌         | 363/6167 [03:34<47:17,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janna.jpg

  6%|▌         | 364/6167 [03:36<58:23,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janita.jpg

  6%|▌         | 367/6167 [03:36<41:26,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iso_H.jpg

  6%|▌         | 368/6167 [03:37<45:03,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Islaja.jpg

  6%|▌         | 369/6167 [03:37<45:58,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irina.jpg

  6%|▌         | 371/6167 [03:38<41:30,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elias_Hämäläinen.jpg

  6%|▌         | 372/6167 [03:39<48:18,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antony_Hämäläinen.jpg

  6%|▌         | 373/6167 [03:40<54:26,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jouni_Hynynen.jpg

  6%|▌         | 374/6167 [03:41<1:03:56,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jorma_Hynninen.jpg

  6%|▌         | 377/6167 [03:41<34:53,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maarit_Hurmerinta.jpg

  6%|▌         | 378/6167 [03:41<34:07,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vuokko_Hovatta.jpg

  6%|▌         | 380/6167 [03:43<51:35,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Hirsma.jpg

  6%|▌         | 381/6167 [03:44<57:57,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tea_Hiilloste.jpg

  6%|▌         | 382/6167 [03:44<57:50,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hiili_Hiilesmaa.jpg

  6%|▌         | 384/6167 [03:45<52:26,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Hietala.jpg

  6%|▌         | 385/6167 [03:46<58:48,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikko_Herranen.jpg

  6%|▋         | 386/6167 [03:47<1:03:03,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim_Herold.jpg

  6%|▋         | 387/6167 [03:48<1:07:44,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Barbara_Helsingius.jpg

  6%|▋         | 388/6167 [03:48<1:03:06,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reino_Helismaa.jpg

  6%|▋         | 389/6167 [03:50<1:21:47,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heikki_Hela.jpg

  6%|▋         | 390/6167 [03:50<1:16:57,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pekka_Heino.jpg

  6%|▋         | 391/6167 [03:52<1:32:54,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olga_Heikkala.jpg

  6%|▋         | 392/6167 [03:52<1:26:16,  1.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hector.jpg

  6%|▋         | 393/6167 [03:53<1:18:04,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Costello_Hautamäki.jpg

  6%|▋         | 394/6167 [03:54<1:29:50,  1.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juha_Harju.jpg

  6%|▋         | 395/6167 [03:55<1:23:36,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Hanski.jpg

  6%|▋         | 396/6167 [03:57<1:51:33,  1.16s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pauli_Hanhiniemi.jpg

  6%|▋         | 399/6167 [03:57<1:01:48,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joel_Hallikainen.jpg

  6%|▋         | 400/6167 [03:58<59:08,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jussi_Hakulinen.jpg

  7%|▋         | 403/6167 [03:59<42:44,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Hagelstam.jpg

  7%|▋         | 404/6167 [03:59<41:08,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Samu_Haber.jpg

  7%|▋         | 405/6167 [04:00<49:35,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Susanna_Haavisto.jpg

  7%|▋         | 406/6167 [04:02<1:13:44,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katherine_Haataja.jpg

  7%|▋         | 407/6167 [04:02<1:03:54,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kreeta_Haapasalo.jpg

  7%|▋         | 409/6167 [04:03<52:07,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monica_Groop.jpg

  7%|▋         | 410/6167 [04:03<56:00,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eino_Grön.jpg

  7%|▋         | 411/6167 [04:04<1:03:14,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanna_Granfelt.jpg

  7%|▋         | 412/6167 [04:05<1:04:46,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irwin_Goodman.jpg

  7%|▋         | 413/6167 [04:06<1:04:35,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gettomasa.jpg

  7%|▋         | 415/6167 [04:06<51:26,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikael_Gabriel.jpg

  7%|▋         | 417/6167 [04:07<42:07,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Freeman.jpg

  7%|▋         | 418/6167 [04:08<49:58,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fredi.jpg

  7%|▋         | 419/6167 [04:08<54:05,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frederik.jpg

  7%|▋         | 420/6167 [04:09<1:05:08,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elisa_Frandin.jpg

  7%|▋         | 422/6167 [04:10<46:53,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Forsberg.jpg

  7%|▋         | 423/6167 [04:11<53:38,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elin_Fohström.jpg

  7%|▋         | 424/6167 [04:12<1:04:11,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alma_Fohström.jpg

  7%|▋         | 425/6167 [04:13<1:12:55,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim_Floor.jpg

  7%|▋         | 427/6167 [04:14<1:16:05,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Evelina.jpg

  7%|▋         | 429/6167 [04:25<3:50:25,  2.41s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Anna_Eriksson_in_2018_%28cropped%29.jpg/250px-Anna_Eriksson_in_2018_%28cropped%29.jpg: _ssl.c:983: The handshake operation timed out

  7%|▋         | 430/6167 [04:35<6:26:48,  4.05s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Erin_Anttila.JPG/250px-Erin_Anttila.JPG: [Errno 101] Network is unreachable

  7%|▋         | 431/6167 [04:45<8:40:44,  5.45s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Emma_Engdahl%2C_rollportr%C3%A4tt_-_SMV_-_H2_191.tif/lossy-page1-190px-Emma_Engdahl%2C_rollportr%C3%A4tt_-_SMV_-_H2_191.tif.jpg: [Errno 101] Network is unreachable

  7%|▋         | 432/6167 [04:55<10:31:12,  6.60s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Emmifinnish.jpg/250px-Emmifinnish.jpg: [Errno 101] Network is unreachable

  7%|▋         | 433/6167 [05:05<11:58:04,  7.51s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Kike_Elomaa_Vihreill%C3%A4_Niityill%C3%A4.jpg/250px-Kike_Elomaa_Vihreill%C3%A4_Niityill%C3%A4.jpg: [Errno 101] Network is unreachable

  7%|▋         | 434/6167 [05:15<13:04:56,  8.21s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Isac_Elliot_-_YleXPop_2016_1_%28cropped%29.jpg/250px-Isac_Elliot_-_YleXPop_2016_1_%28cropped%29.jpg: [Errno 101] Network is unreachable

  7%|▋         | 435/6167 [05:25<13:54:04,  8.73s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Elastinen.JPG/250px-Elastinen.JPG: [Errno 101] Network is unreachable

  7%|▋         | 436/6167 [05:35<14:30:26,  9.11s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ida_Ekman_1900s_to_1910s.jpg/250px-Ida_Ekman_1900s_to_1910s.jpg: [Errno 101] Network is unreachable

  7%|▋         | 438/6167 [05:45<11:34:57,  7.28s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Samuli-Edelmann-2019-2.jpg/250px-Samuli-Edelmann-2019-2.jpg: [Errno 101] Network is unreachable

  7%|▋         | 439/6167 [05:55<12:39:15,  7.95s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Bomfunk_MC%E2%80%99s_Allas_8.jpg/250px-Bomfunk_MC%E2%80%99s_Allas_8.jpg: [Errno 101] Network is unreachable

  7%|▋         | 440/6167 [06:05<13:31:17,  8.50s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Diandra_Flores_C_IMG_5380.JPG/250px-Diandra_Flores_C_IMG_5380.JPG: [Errno 101] Network is unreachable

  7%|▋         | 441/6167 [06:15<14:11:31,  8.92s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Johannadebreczeni6.JPG/250px-Johannadebreczeni6.JPG: [Errno 101] Network is unreachable

  7%|▋         | 442/6167 [06:25<14:41:42,  9.24s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Danny_in_Pori_2008.JPG/250px-Danny_in_Pori_2008.JPG: [Errno 101] Network is unreachable

  7%|▋         | 444/6167 [06:35<11:44:12,  7.38s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Cyan_Kicks.jpg/250px-Cyan_Kicks.jpg: [Errno 101] Network is unreachable

  7%|▋         | 445/6167 [06:46<12:45:25,  8.03s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/JimiConstantine.jpg/250px-JimiConstantine.jpg: [Errno 101] Network is unreachable

  7%|▋         | 447/6167 [06:56<10:49:10,  6.81s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Kaj_Chydenius.jpg/250px-Kaj_Chydenius.jpg: [Errno 101] Network is unreachable

  7%|▋         | 449/6167 [07:06<9:46:45,  6.16s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Chisu_-_Ilosaarirock_2010_2.jpg/250px-Chisu_-_Ilosaarirock_2010_2.jpg: [Errno 101] Network is unreachable

  7%|▋         | 450/6167 [07:16<11:04:16,  6.97s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Cheek_-_Ilosaarirock_2016_-_16_%28cropped%29.jpg/250px-Cheek_-_Ilosaarirock_2016_-_16_%28cropped%29.jpg: [Errno 101] Network is unreachable

  7%|▋         | 453/6167 [07:26<8:21:20,  5.26s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Kim_Brown_1966_Renegades.jpg/250px-Kim_Brown_1966_Renegades.jpg: [Errno 101] Network is unreachable

  7%|▋         | 454/6167 [07:36<9:45:08,  6.15s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/ME_EMME_VAIKENE_023_Rasismia_ja_fasismia_vastaan_%2853165159338%29.jpg/250px-ME_EMME_VAIKENE_023_Rasismia_ja_fasismia_vastaan_%2853165159338%29.jpg: [Errno 101] Network is unreachable

  7%|▋         | 455/6167 [07:46<11:02:13,  6.96s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Br%C3%A4di_%26_Kasmir_-_YleXPop_2017_-_01.jpg/250px-Br%C3%A4di_%26_Kasmir_-_YleXPop_2017_-_01.jpg: [Errno 101] Network is unreachable

  7%|▋         | 456/6167 [07:56<12:09:35,  7.67s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Kristiina_Brask.JPG/250px-Kristiina_Brask.JPG: [Errno 101] Network is unreachable

  7%|▋         | 457/6167 [08:06<13:05:56,  8.26s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Borg-kim-1965.jpg/250px-Borg-kim-1965.jpg: [Errno 101] Network is unreachable

  7%|▋         | 458/6167 [08:16<13:50:27,  8.73s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Demilich_Party.San_Metal_Open_Air_2017_08.jpg/250px-Demilich_Party.San_Metal_Open_Air_2017_08.jpg: [Errno 101] Network is unreachable

  7%|▋         | 459/6167 [08:26<14:24:39,  9.09s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Tuure_Boelius_Helsinki_Pride_2024_02_%28cropped%29.jpg/250px-Tuure_Boelius_Helsinki_Pride_2024_02_%28cropped%29.jpg: [Errno 101] Network is unreachable

  8%|▊         | 465/6167 [08:36<6:12:07,  3.92s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Benjamin_Peltonen%2C_2020_%28cropped%29.png/250px-Benjamin_Peltonen%2C_2020_%28cropped%29.png: [Errno 101] Network is unreachable

  8%|▊         | 466/6167 [08:46<7:35:31,  4.79s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Singer-songwriter_Rita_Behm_live_on_stage_at_Ruisrock_2022.png/250px-Singer-songwriter_Rita_Behm_live_on_stage_at_Ruisrock_2022.png: [Errno 101] Network is unreachable

  8%|▊         | 467/6167 [08:56<9:00:50,  5.69s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ida_Basilier.jpg/250px-Ida_Basilier.jpg: [Errno 101] Network is unreachable

  8%|▊         | 468/6167 [09:07<10:21:28,  6.54s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Mara_Balls.jpg/250px-Mara_Balls.jpg: [Errno 101] Network is unreachable

  8%|▊         | 470/6167 [09:17<9:29:47,  6.00s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/L%C3%A4j%C3%A4_%C3%84ij%C3%A4l%C3%A4.jpg/250px-L%C3%A4j%C3%A4_%C3%84ij%C3%A4l%C3%A4.jpg: [Errno 101] Network is unreachable

  8%|▊         | 471/6167 [09:27<10:47:59,  6.83s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Aste6.jpg/250px-Aste6.jpg: [Errno 101] Network is unreachable

  8%|▊         | 472/6167 [09:37<11:57:27,  7.56s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Kita_%C3%A0_Anvers_en_octobre_2006.jpg/250px-Kita_%C3%A0_Anvers_en_octobre_2006.jpg: [Errno 101] Network is unreachable

  8%|▊         | 473/6167 [09:47<12:55:24,  8.17s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Monica_Aspelund_1987.jpg/330px-Monica_Aspelund_1987.jpg: [Errno 101] Network is unreachable

  8%|▊         | 474/6167 [09:57<13:41:54,  8.66s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Asa_Pori_Jazzeilla_2015.jpg/250px-Asa_Pori_Jazzeilla_2015.jpg: [Errno 101] Network is unreachable

  8%|▊         | 475/6167 [10:07<14:18:25,  9.05s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Ami_Aspelund_%282023%29_-_2.jpg/330px-Ami_Aspelund_%282023%29_-_2.jpg: [Errno 101] Network is unreachable

  8%|▊         | 476/6167 [10:17<14:45:24,  9.33s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Koop_Arponen.JPG/250px-Koop_Arponen.JPG: [Errno 101] Network is unreachable

  8%|▊         | 477/6167 [10:27<15:04:29,  9.54s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Markku_Aro_191.JPG/250px-Markku_Aro_191.JPG: [Errno 101] Network is unreachable

  8%|▊         | 478/6167 [10:37<15:18:54,  9.69s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mokoma_MTR_20110619_13.jpg/250px-Mokoma_MTR_20110619_13.jpg: [Errno 101] Network is unreachable

  8%|▊         | 479/6167 [10:47<15:28:38,  9.80s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Nikke_Ankara_-_YleXPop_2016_2.jpg/250px-Nikke_Ankara_-_YleXPop_2016_2.jpg: [Errno 101] Network is unreachable

  8%|▊         | 480/6167 [10:57<15:36:08,  9.88s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Alfons-Almi.jpg/250px-Alfons-Almi.jpg: [Errno 101] Network is unreachable

  8%|▊         | 481/6167 [11:07<15:40:48,  9.93s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Alma_-_2018082191458_2018-03-23_Radio_Regenbogen_Award_2018_-_Sven_-_1D_X_MK_II_-_0406_-_AK8I0137.jpg/250px-Alma_-_2018082191458_2018-03-23_Radio_Regenbogen_Award_2018_-_Sven_-_1D_X_MK_II_-_0406_-_AK8I0137.jpg: [Errno 101] Network is unreachable

  8%|▊         | 482/6167 [11:17<15:44:10,  9.96s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Nikolai_Alho.jpg/250px-Nikolai_Alho.jpg: [Errno 101] Network is unreachable

  8%|▊         | 483/6167 [11:27<15:46:11,  9.99s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Mikko_alatalo.jpg/250px-Mikko_alatalo.jpg: [Errno 101] Network is unreachable

  8%|▊         | 484/6167 [11:37<15:48:33, 10.01s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ismo_Alanko.jpg/250px-Ismo_Alanko.jpg: [Errno 101] Network is unreachable

  8%|▊         | 485/6167 [11:48<15:50:04, 10.03s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Ilkka_Alanko_-_Ilosaarirock_2011.jpg/250px-Ilkka_Alanko_-_Ilosaarirock_2011.jpg: [Errno 101] Network is unreachable

  8%|▊         | 487/6167 [11:58<12:11:23,  7.73s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Jukka_Ahti_ja_Katri_Lammi.jpg/250px-Jukka_Ahti_ja_Katri_Lammi.jpg: [Errno 101] Network is unreachable

  8%|▊         | 488/6167 [12:08<13:06:32,  8.31s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Ter%C3%A4sbetoni_032008_Ahola_03.jpg/250px-Ter%C3%A4sbetoni_032008_Ahola_03.jpg: [Errno 101] Network is unreachable

  8%|▊         | 489/6167 [12:18<13:49:58,  8.77s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Susan_Aho_07.jpg/250px-Susan_Aho_07.jpg: [Errno 101] Network is unreachable

  8%|▊         | 490/6167 [12:28<14:23:05,  9.12s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Alexandra-Ahnger.jpg/250px-Alexandra-Ahnger.jpg: [Errno 101] Network is unreachable

  8%|▊         | 491/6167 [12:38<14:48:51,  9.40s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pepe_Ahlqvist.jpg/250px-Pepe_Ahlqvist.jpg: [Errno 101] Network is unreachable

  8%|▊         | 492/6167 [12:48<15:07:22,  9.59s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Emmy_achte.jpg/250px-Emmy_achte.jpg: [Errno 101] Network is unreachable

  8%|▊         | 493/6167 [12:58<15:19:29,  9.72s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/AAckt%C3%A9_1900s_%28cropped%29.jpg/250px-AAckt%C3%A9_1900s_%28cropped%29.jpg: [Errno 101] Network is unreachable

  8%|▊         | 494/6167 [13:08<15:29:03,  9.83s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Anna_Abreu_I9073_C.JPG/250px-Anna_Abreu_I9073_C.JPG: [Errno 101] Network is unreachable

  8%|▊         | 495/6167 [13:18<15:35:51,  9.90s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Armi_Aavikko.jpg/250px-Armi_Aavikko.jpg: [Errno 101] Network is unreachable

  8%|▊         | 496/6167 [13:28<15:40:29,  9.95s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Jonne_Aaron_Lappeenrannan_Y%C3%B6t_2013_2.jpg/250px-Jonne_Aaron_Lappeenrannan_Y%C3%B6t_2013_2.jpg: [Errno 101] Network is unreachable

  8%|▊         | 497/6167 [13:38<15:43:46,  9.99s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Agit_Prop_1974.jpg/250px-Agit_Prop_1974.jpg: [Errno 101] Network is unreachable

  8%|▊         | 499/6167 [13:48<12:08:44,  7.71s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Saara_Aalto_%282%29_20180508_EuroVisionary_%28cropped%29.jpg/250px-Saara_Aalto_%282%29_20180508_EuroVisionary_%28cropped%29.jpg: [Errno 101] Network is unreachable

  8%|▊         | 501/6167 [13:59<10:28:11,  6.65s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Charice_06-19-16.jpg/250px-Charice_06-19-16.jpg: [Errno 101] Network is unreachable

  8%|▊         | 507/6167 [14:09<5:32:11,  3.52s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Yael_Yuzon_and_Sponge_Cola.jpg/250px-Yael_Yuzon_and_Sponge_Cola.jpg: [Errno 101] Network is unreachable

  8%|▊         | 508/6167 [14:19<6:52:36,  4.37s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Lauren_Young.jpg/250px-Lauren_Young.jpg: [Errno 101] Network is unreachable

  8%|▊         | 514/6167 [14:29<4:38:03,  2.95s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/en/f/ff/Victor-Wood.jpg: [Errno 101] Network is unreachable

  8%|▊         | 517/6167 [14:39<4:48:18,  3.06s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Jillian_Ward_2025.jpg/250px-Jillian_Ward_2025.jpg: [Errno 101] Network is unreachable

  8%|▊         | 519/6167 [14:49<5:26:49,  3.47s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/JonalynVirayfearless1.jpg/250px-JonalynVirayfearless1.jpg: [Errno 101] Network is unreachable

  8%|▊         | 520/6167 [14:59<6:46:40,  4.32s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cris_Villonco_as_Ophelia.jpg/250px-Cris_Villonco_as_Ophelia.jpg: [Errno 101] Network is unreachable

  8%|▊         | 523/6167 [15:09<6:14:17,  3.98s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Buboy_Villar_-_2021_%28cropped%29.jpg/250px-Buboy_Villar_-_2021_%28cropped%29.jpg: [Errno 101] Network is unreachable

  9%|▊         | 528/6167 [15:19<4:49:17,  3.08s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ms._Cebu_Emmanuelle_Vera_in_Basey%2C_Leyte_%282023%29.jpg/250px-Ms._Cebu_Emmanuelle_Vera_in_Basey%2C_Leyte_%282023%29.jpg: [Errno 101] Network is unreachable

  9%|▊         | 529/6167 [15:29<6:05:04,  3.89s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Lilian_Velez_Filipina_Actor.jpg/250px-Lilian_Velez_Filipina_Actor.jpg: [Errno 101] Network is unreachable

  9%|▊         | 530/6167 [15:39<7:27:37,  4.76s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Camile_Velasco.jpg/250px-Camile_Velasco.jpg: [Errno 101] Network is unreachable

  9%|▊         | 531/6167 [15:49<8:51:46,  5.66s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/RVA_in_2010_%28cropped%29.jpg/250px-RVA_in_2010_%28cropped%29.jpg: [Errno 101] Network is unreachable

  9%|▊         | 532/6167 [15:59<10:12:07,  6.52s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Katrina_Velarde_-_2023.png/250px-Katrina_Velarde_-_2023.png: [Errno 101] Network is unreachable

  9%|▊         | 533/6167 [16:09<11:24:47,  7.29s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/en/f/f4/JULIE_VEGA_PIC.jpg: [Errno 101] Network is unreachable

  9%|▊         | 536/6167 [16:20<8:26:11,  5.39s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Volts.jpg/250px-Volts.jpg: [Errno 101] Network is unreachable

  9%|▊         | 537/6167 [16:30<9:47:30,  6.26s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Rey-valera.jpg/250px-Rey-valera.jpg: [Errno 101] Network is unreachable

  9%|▊         | 538/6167 [16:40<11:02:18,  7.06s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Bpvalenzuelasatchmivinylday2015.jpg/250px-Bpvalenzuelasatchmivinylday2015.jpg: [Errno 101] Network is unreachable

  9%|▉         | 540/6167 [16:50<9:50:47,  6.30s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Gary_Valenciano_in_Toronto_2014_02.jpg/250px-Gary_Valenciano_in_Toronto_2014_02.jpg: [Errno 101] Network is unreachable

  9%|▉         | 546/6167 [17:00<5:23:10,  3.45s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Bitoy_in_eatbulaga.jpg/250px-Bitoy_in_eatbulaga.jpg: [Errno 101] Network is unreachable

  9%|▉         | 547/6167 [17:10<6:42:36,  4.30s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Mocha_Uson_2017.jpg/250px-Mocha_Uson_2017.jpg: [Errno 101] Network is unreachable

  9%|▉         | 548/6167 [17:20<8:06:09,  5.19s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Unique_Salonga_at_LSGH_2024-04-13.jpg/250px-Unique_Salonga_at_LSGH_2024-04-13.jpg: [Errno 101] Network is unreachable

  9%|▉         | 551/6167 [17:30<6:57:48,  4.46s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Green_Bones_actor_Dennis_Trillo12.jpg/250px-Green_Bones_actor_Dennis_Trillo12.jpg: [Errno 101] Network is unreachable

  9%|▉         | 553/6167 [17:40<7:12:22,  4.62s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Athena_High_School_Musical_Onstage_as_Sharpay_Evans_2.JPG/250px-Athena_High_School_Musical_Onstage_as_Sharpay_Evans_2.JPG: [Errno 101] Network is unreachable

  9%|▉         | 559/6167 [17:50<4:43:05,  3.03s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Antoinette_Taus_BoxSing_Challenge.jpg/250px-Antoinette_Taus_BoxSing_Challenge.jpg: [Errno 101] Network is unreachable

  9%|▉         | 561/6167 [18:00<5:21:14,  3.44s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/KZ_Tandingan_at_Pagibang_Damara_Festival_2025_%28cropped%29.jpg/250px-KZ_Tandingan_at_Pagibang_Damara_Festival_2025_%28cropped%29.jpg: [Errno 101] Network is unreachable

  9%|▉         | 563/6167 [18:10<5:54:41,  3.80s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Zack_Tabudlo.png/250px-Zack_Tabudlo.png: [Errno 101] Network is unreachable

  9%|▉         | 564/6167 [18:20<7:15:49,  4.67s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/MaxineSyjuco-Portrait.jpg/250px-MaxineSyjuco-Portrait.jpg: [Errno 101] Network is unreachable

  9%|▉         | 565/6167 [18:30<8:39:33,  5.56s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Max-surban.png/250px-Max-surban.png: [Errno 101] Network is unreachable

  9%|▉         | 567/6167 [18:40<8:23:40,  5.40s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Marco_Sison.jpg/250px-Marco_Sison.jpg: [Errno 101] Network is unreachable

  9%|▉         | 570/6167 [18:51<7:06:10,  4.57s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Pepe_Smith_%282008%29.jpg/250px-Pepe_Smith_%282008%29.jpg: [Errno 101] Network is unreachable

  9%|▉         | 573/6167 [19:01<6:24:10,  4.12s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Armida_Siguion-Reyna_National_Artist_award_protest_at_CCP.jpg/250px-Armida_Siguion-Reyna_National_Artist_award_protest_at_CCP.jpg: [Errno 101] Network is unreachable

  9%|▉         | 575/6167 [19:11<6:45:53,  4.36s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sheena_Catacutan_in_September_2025.jpg/250px-Sheena_Catacutan_in_September_2025.jpg: [Errno 101] Network is unreachable

  9%|▉         | 577/6167 [19:21<7:02:59,  4.54s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/JapsSergio.jpg/330px-JapsSergio.jpg: [Errno 101] Network is unreachable

  9%|▉         | 578/6167 [19:31<8:26:28,  5.44s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Aiza_Seguerra_portrait.jpg/250px-Aiza_Seguerra_portrait.jpg: [Errno 101] Network is unreachable

  9%|▉         | 581/6167 [19:41<7:06:32,  4.58s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Rep._Vilma_Santos-Recto_%2818th_Congress_PH%29.jpg/250px-Rep._Vilma_Santos-Recto_%2818th_Congress_PH%29.jpg: [Errno 101] Network is unreachable

  9%|▉         | 582/6167 [19:51<8:29:56,  5.48s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Judy_Ann_Santos_%282008%29.jpg/250px-Judy_Ann_Santos_%282008%29.jpg: [Errno 101] Network is unreachable

  9%|▉         | 584/6167 [20:01<8:16:13,  5.33s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Erik_Santos_-_Chicago_Concert_2008.jpg/250px-Erik_Santos_-_Chicago_Concert_2008.jpg: [Errno 101] Network is unreachable

  9%|▉         | 585/6167 [20:11<9:37:35,  6.21s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Aicelle_Santos_Isang_Himala_5.jpg/250px-Aicelle_Santos_Isang_Himala_5.jpg: [Errno 101] Network is unreachable

 10%|▉         | 586/6167 [20:21<10:52:42,  7.02s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Walang_tulugan_18th_year_anniversary_2014-05-08_03-34.jpg/250px-Walang_tulugan_18th_year_anniversary_2014-05-08_03-34.jpg: [Errno 101] Network is unreachable

 10%|▉         | 588/6167 [20:31<9:43:36,  6.28s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Jess_Santiago_%2870%27s_Bistro%29.jpg/250px-Jess_Santiago_%2870%27s_Bistro%29.jpg: [Errno 101] Network is unreachable

 10%|▉         | 591/6167 [20:41<7:42:13,  4.97s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Sharlene_San_Pedro_on_iWant_ASAP_4.jpg/250px-Sharlene_San_Pedro_on_iWant_ASAP_4.jpg: [Errno 101] Network is unreachable

 10%|▉         | 592/6167 [20:49<8:23:15,  5.42s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julie_Anne_San_Jose.jpg

 10%|▉         | 597/6167 [20:49<3:46:44,  2.44s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Salvador.jpg

 10%|▉         | 598/6167 [20:49<3:19:09,  2.15s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janella_Salvador.jpg

 10%|▉         | 600/6167 [20:50<2:26:44,  1.58s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lea_Salonga.jpg

 10%|▉         | 604/6167 [20:50<1:28:00,  1.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nur-Ana_Sahidulla.jpg

 10%|▉         | 605/6167 [20:51<1:20:24,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michael_Sager.jpg

 10%|▉         | 607/6167 [20:51<1:04:46,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karl_Roy.jpg

 10%|▉         | 608/6167 [20:51<57:27,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wilbert_Ross.jpg

 10%|▉         | 610/6167 [20:52<42:27,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jericho_Rosales.jpg

 10%|▉         | 611/6167 [20:52<45:26,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anthony_Rosaldo.jpg

 10%|▉         | 613/6167 [20:53<33:51,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olivia_Rodrigo.jpg

 10%|█         | 617/6167 [20:53<19:59,  4.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jak_Roberto.jpg

 10%|█         | 619/6167 [20:53<17:56,  5.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marian_Rivera.jpg

 10%|█         | 620/6167 [20:54<23:14,  3.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jamie_Rivera.jpg

 10%|█         | 621/6167 [20:54<24:18,  3.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ariel_Rivera.jpg

 10%|█         | 629/6167 [20:54<10:41,  8.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alden_Richards.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willie_Revillame.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/James_Reid.jpg

 10%|█         | 631/6167 [20:55<13:34,  6.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sheryn_Regis.jpg

 10%|█         | 632/6167 [20:55<14:55,  6.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/April_Boy_Regino.jpg

 10%|█         | 633/6167 [20:56<24:36,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sunday_Reantaso.jpg

 10%|█         | 636/6167 [20:56<17:28,  5.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elizabeth_Ramsey.jpg

 10%|█         | 638/6167 [20:56<15:42,  5.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Regine_Velasquez.jpg

 10%|█         | 639/6167 [20:57<17:10,  5.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khalil_Ramos.jpg

 10%|█         | 640/6167 [20:57<20:38,  4.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sue_Ramirez.jpg

 10%|█         | 641/6167 [20:57<21:48,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maris_Racal.jpg

 10%|█         | 645/6167 [20:58<13:22,  6.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angeline_Quinto.jpg

 11%|█         | 648/6167 [20:58<11:08,  8.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rico_J._Puno.jpg

 11%|█         | 649/6167 [20:58<13:30,  6.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yassi_Pressman.jpg

 11%|█         | 650/6167 [20:59<20:25,  4.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chickoy_Pura.jpg

 11%|█         | 651/6167 [20:59<23:30,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Richard_Poon.jpg

 11%|█         | 652/6167 [21:00<25:28,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marcelito_Pomoy.jpg

 11%|█         | 653/6167 [21:00<25:26,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pokwang.jpg

 11%|█         | 654/6167 [21:00<25:21,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lovi_Poe.jpg

 11%|█         | 656/6167 [21:00<19:24,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arnel_Pineda.jpg

 11%|█         | 658/6167 [21:01<17:00,  5.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eddie_Peregrina.jpg

 11%|█         | 659/6167 [21:01<18:27,  4.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heaven_Peralejo.jpg

 11%|█         | 660/6167 [21:01<20:15,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rica_Peralejo.jpg

 11%|█         | 663/6167 [21:01<14:39,  6.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jim_Paredes.jpg

 11%|█         | 664/6167 [21:02<20:36,  4.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Piolo_Pascual.jpg

 11%|█         | 666/6167 [21:02<17:48,  5.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sonny_Parsons.jpg

 11%|█         | 669/6167 [21:03<13:38,  6.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Imelda_Papin.jpg

 11%|█         | 673/6167 [21:03<10:03,  9.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Donny_Pangilinan.jpg

 11%|█         | 674/6167 [21:03<12:46,  7.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jett_Pangan.jpg

 11%|█         | 678/6167 [21:03<09:53,  9.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariel_Pamintuan.jpg

 11%|█         | 679/6167 [21:04<12:00,  7.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zsa_Zsa_Padilla.jpg

 11%|█         | 680/6167 [21:05<28:52,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kylie_Padilla.jpg

 11%|█         | 681/6167 [21:06<36:47,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniel_Padilla.jpg

 11%|█         | 682/6167 [21:06<41:47,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manny_Pacquiao.jpg

 11%|█         | 683/6167 [21:07<37:51,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Pablo.jpg

 11%|█         | 684/6167 [21:08<1:03:41,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pablo.jpg

 11%|█         | 688/6167 [21:09<43:24,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daryl_Ong.jpg

 11%|█         | 692/6167 [21:11<38:31,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miles_Ocampo.jpg

 11%|█         | 693/6167 [21:11<37:23,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diether_Ocampo.jpg

 11%|█▏        | 696/6167 [21:11<26:24,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Grace_Nono.jpg

 11%|█▏        | 697/6167 [21:12<31:20,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nityalila.jpg

 11%|█▏        | 698/6167 [21:12<31:58,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina.jpg

 11%|█▏        | 699/6167 [21:13<30:20,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robin_Nievera.jpg

 11%|█▏        | 700/6167 [21:13<29:16,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martin_Nievera.jpg

 11%|█▏        | 702/6167 [21:14<32:14,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bert_Nievera.jpg

 11%|█▏        | 705/6167 [21:15<36:23,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vhong_Navarro.jpg

 11%|█▏        | 706/6167 [21:17<52:40,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sitti_Navarro.jpg

 11%|█▏        | 708/6167 [21:17<40:55,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leah_Navarro.jpg

 11%|█▏        | 709/6167 [21:19<1:04:15,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rodel_Naval.jpg

 12%|█▏        | 711/6167 [21:19<50:08,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikko_Natividad.jpg

 12%|█▏        | 715/6167 [21:20<33:57,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kitchie_Nadal.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arci_Muñoz.jpg

 12%|█▏        | 721/6167 [21:21<17:12,  5.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Morissette.jpg

 12%|█▏        | 723/6167 [21:21<18:50,  4.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akira_Morishita.jpg

 12%|█▏        | 724/6167 [21:22<22:07,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ena_Mori.jpg

 12%|█▏        | 725/6167 [21:22<22:44,  3.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tillie_Moreno.jpg

 12%|█▏        | 726/6167 [21:23<29:03,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Moran.jpg

 12%|█▏        | 727/6167 [21:23<38:15,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vina_Morales.jpg

 12%|█▏        | 729/6167 [21:24<32:59,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seann_Miley_Moore.jpg

 12%|█▏        | 732/6167 [21:25<34:07,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cesar_Montano.jpg

 12%|█▏        | 735/6167 [21:26<28:47,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lani_Misalucha.jpg

 12%|█▏        | 736/6167 [21:27<36:51,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/G3_Misa.jpg

 12%|█▏        | 737/6167 [21:27<35:40,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kelvin_Miranda.jpg

 12%|█▏        | 738/6167 [21:27<34:05,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chito_Miranda.jpg

 12%|█▏        | 739/6167 [21:28<32:03,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ara_Mina.jpg

 12%|█▏        | 741/6167 [21:28<24:57,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aubrey_Miles.jpg

 12%|█▏        | 743/6167 [21:29<34:11,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sam_Milby.jpg

 12%|█▏        | 744/6167 [21:29<32:34,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikha.jpg

 12%|█▏        | 746/6167 [21:30<25:48,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jennylyn_Mercado.jpg

 12%|█▏        | 747/6167 [21:31<45:42,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maine_Mendoza.jpg

 12%|█▏        | 750/6167 [21:32<33:02,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luke_Mejares.jpg

 12%|█▏        | 752/6167 [21:32<31:57,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bailey_May.jpg

 12%|█▏        | 753/6167 [21:33<44:41,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maxie.jpg

 12%|█▏        | 759/6167 [21:34<23:35,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/OJ_Mariano.jpg

 12%|█▏        | 760/6167 [21:35<25:32,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jan_Marini.jpg

 12%|█▏        | 762/6167 [21:35<26:50,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mau_Marcelo.jpg

 12%|█▏        | 768/6167 [21:36<18:14,  4.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miko_Manguba.jpg

 12%|█▏        | 769/6167 [21:36<19:46,  4.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bamboo_Manalac.jpg

 12%|█▏        | 770/6167 [21:37<21:11,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ramiele_Malubay.jpg

 13%|█▎        | 771/6167 [21:37<21:39,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maloi.jpg

 13%|█▎        | 772/6167 [21:38<29:13,  3.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maki.jpg

 13%|█▎        | 774/6167 [21:38<22:42,  3.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mahal.jpg

 13%|█▎        | 775/6167 [21:38<23:30,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jolina_Magdangal.jpg

 13%|█▎        | 776/6167 [21:38<24:56,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francis_Magalona.jpg

 13%|█▎        | 778/6167 [21:39<24:07,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elmo_Magalona.jpg

 13%|█▎        | 779/6167 [21:39<24:57,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jed_Madela.jpg

 13%|█▎        | 781/6167 [21:40<21:19,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nadine_Lustre.jpg

 13%|█▎        | 782/6167 [21:40<26:32,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Champ_Lui_Pio.jpg

 13%|█▎        | 783/6167 [21:41<34:31,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maloy_Lozanes.jpg

 13%|█▎        | 787/6167 [21:41<22:36,  3.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JoAnne_Lorenzana.jpg

 13%|█▎        | 789/6167 [21:42<19:22,  4.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Xian_Lim.jpg

 13%|█▎        | 792/6167 [21:42<17:24,  5.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ralph_Joseph_Lim.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ronnie_Liang.jpg

 13%|█▎        | 793/6167 [21:43<22:00,  4.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lilet.jpg

 13%|█▎        | 794/6167 [21:43<30:01,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celeste_Legaspi.jpg

 13%|█▎        | 795/6167 [21:44<34:43,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kuh_Ledesma.jpg

 13%|█▎        | 796/6167 [21:44<31:52,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kris_Lawrence.jpg

 13%|█▎        | 801/6167 [21:45<20:23,  4.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reese_Lansangan.jpg

 13%|█▎        | 802/6167 [21:45<24:13,  3.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davey_Langit.jpg

 13%|█▎        | 805/6167 [21:46<18:40,  4.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sylvia_La_Torre.jpg

 13%|█▎        | 807/6167 [21:46<16:20,  5.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ranz_Kyle.jpg

 13%|█▎        | 808/6167 [21:47<25:35,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyla.jpg

 13%|█▎        | 809/6167 [21:47<26:30,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yasmien_Kurdi.jpg

 13%|█▎        | 813/6167 [21:48<16:40,  5.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karylle.jpg

 13%|█▎        | 814/6167 [21:48<21:28,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lala_Karmela.jpg

 13%|█▎        | 816/6167 [21:49<24:36,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JV_Kapunan.jpg

 13%|█▎        | 817/6167 [21:49<24:50,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Clinton_Kane.jpg

 13%|█▎        | 818/6167 [21:50<32:44,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kakie.jpg

 13%|█▎        | 819/6167 [21:50<31:29,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Justin.jpg

 13%|█▎        | 820/6167 [21:50<29:02,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Júnior.jpg

 13%|█▎        | 823/6167 [21:51<24:11,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JJ.jpg

 13%|█▎        | 826/6167 [21:51<18:35,  4.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jhoanna.jpg

 13%|█▎        | 827/6167 [21:52<24:35,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anthony_Jennings.jpg

 13%|█▎        | 828/6167 [21:52<25:57,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaya.jpg

 13%|█▎        | 829/6167 [21:53<37:01,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patricia_Javier.jpg

 14%|█▎        | 840/6167 [21:54<12:32,  7.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexa_Ilacad.jpg

 14%|█▎        | 841/6167 [21:55<18:51,  4.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Isabel_Granada.jpg

 14%|█▎        | 842/6167 [21:56<25:04,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arnell_Ignacio.jpg

 14%|█▎        | 843/6167 [21:56<25:47,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruby_Ibarra.jpg

 14%|█▎        | 844/6167 [21:56<29:19,  3.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kai_Honasan.jpg

 14%|█▎        | 845/6167 [21:57<27:35,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Honcho.jpg

 14%|█▍        | 850/6167 [21:57<14:46,  6.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janine_Gutierrez.jpg

 14%|█▍        | 851/6167 [21:58<29:42,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gabrielle_Gutierrez.jpg

 14%|█▍        | 854/6167 [21:59<21:49,  4.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Matteo_Guidicelli.jpg

 14%|█▍        | 855/6167 [21:59<25:30,  3.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sela_Guia.jpg

 14%|█▍        | 859/6167 [21:59<16:04,  5.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yamyam_Gucong.jpg

 14%|█▍        | 860/6167 [22:00<16:39,  5.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Isabel_Granada.jpg

 14%|█▍        | 861/6167 [22:00<22:45,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Catriona_Gray.jpg

 14%|█▍        | 863/6167 [22:01<20:20,  4.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alodia_Gosiengfiao.jpg

 14%|█▍        | 865/6167 [22:02<26:52,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enya_Gonzalez.jpg

 14%|█▍        | 869/6167 [22:02<16:29,  5.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toni_Gonzaga.jpg

 14%|█▍        | 871/6167 [22:02<15:31,  5.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Gonzaga.jpg

 14%|█▍        | 873/6167 [22:03<20:22,  4.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rachelle_Ann_Go.jpg

 14%|█▍        | 876/6167 [22:03<18:40,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/King_Girado.jpg

 14%|█▍        | 877/6167 [22:04<24:39,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikki_Gil.jpg

 14%|█▍        | 878/6167 [22:05<35:43,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enrique_Gil.jpg

 14%|█▍        | 882/6167 [22:05<22:00,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sarah_Geronimo.jpg

 14%|█▍        | 883/6167 [22:06<27:26,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ylona_Garcia.jpg

 14%|█▍        | 884/6167 [22:06<28:02,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maricris_Garcia.jpg

 14%|█▍        | 885/6167 [22:07<30:50,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jamir_Garcia.jpg

 14%|█▍        | 886/6167 [22:07<30:04,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gabbi_Garcia.jpg

 14%|█▍        | 887/6167 [22:08<30:28,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vice_Ganda.jpg

 14%|█▍        | 888/6167 [22:08<29:10,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lyca_Gairanod.jpg

 14%|█▍        | 890/6167 [22:09<30:15,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Susan_Fuentes.jpg

 14%|█▍        | 891/6167 [22:09<37:45,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Flow_G.jpg

 14%|█▍        | 892/6167 [22:10<45:34,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jovita_Fuentes.jpg

 14%|█▍        | 893/6167 [22:11<47:28,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rose_Fostanes.jpg

 14%|█▍        | 894/6167 [22:12<1:02:43,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gerphil_Flores.jpg

 15%|█▍        | 896/6167 [22:13<50:16,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Susan_Fernandez.jpg

 15%|█▍        | 897/6167 [22:14<1:01:57,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pops_Fernandez.jpg

 15%|█▍        | 898/6167 [22:15<1:14:23,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juris_Fernandez.jpg

 15%|█▍        | 903/6167 [22:15<29:38,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Felip.jpg

 15%|█▍        | 904/6167 [22:16<35:46,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Fegi.jpg

 15%|█▍        | 905/6167 [22:17<40:40,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seth_Fedelin.jpg

 15%|█▍        | 910/6167 [22:17<20:31,  4.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heart_Evangelista.jpg

 15%|█▍        | 911/6167 [22:18<24:09,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lyka_Estrella.jpg

 15%|█▍        | 914/6167 [22:18<21:23,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Abel_Estanislao.jpg

 15%|█▍        | 915/6167 [22:19<30:11,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gretchen_Espina.jpg

 15%|█▍        | 917/6167 [22:19<25:49,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darren_Espanto.jpg

 15%|█▍        | 919/6167 [22:20<22:11,  3.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vivoree_Esclito.jpg

 15%|█▍        | 920/6167 [22:20<22:47,  3.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bituin_Escalante.jpg

 15%|█▍        | 922/6167 [22:21<26:02,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gabby_Eigenmann.jpg

 15%|█▍        | 923/6167 [22:21<25:49,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maymay_Entrata.jpg

 15%|█▍        | 924/6167 [22:21<27:36,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrew_E..jpg

 15%|█▌        | 926/6167 [22:22<20:45,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyle_Echarri.jpg

 15%|█▌        | 929/6167 [22:22<19:06,  4.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elaine_Duran.jpg

 15%|█▌        | 931/6167 [22:23<17:05,  5.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mich_Dulce.jpg

 15%|█▌        | 932/6167 [22:23<19:02,  4.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dulce.jpg

 15%|█▌        | 938/6167 [22:23<12:09,  7.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ney_Dimaculangan.jpg

 15%|█▌        | 939/6167 [22:24<18:09,  4.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celia_Díaz_Laurel.jpg

 15%|█▌        | 940/6167 [22:24<19:36,  4.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francine_Diaz.jpg

 15%|█▌        | 943/6167 [22:26<33:33,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enchong_Dee.jpg

 15%|█▌        | 944/6167 [22:27<35:41,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai-Ai_delas_Alas.jpg

 15%|█▌        | 946/6167 [22:27<29:51,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moira_Dela_Torre.jpg

 15%|█▌        | 948/6167 [22:28<25:14,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Atang_de_la_Rama.jpg

 15%|█▌        | 951/6167 [22:28<22:48,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Claire_de_la_Fuente.jpg

 15%|█▌        | 952/6167 [22:29<33:02,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katy_de_la_Cruz.jpg

 16%|█▌        | 956/6167 [22:30<20:28,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JC_de_Vera.jpg

 16%|█▌        | 959/6167 [22:31<29:25,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joey_de_Leon.jpg

 16%|█▌        | 961/6167 [22:32<25:43,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gigi_de_Lana.jpg

 16%|█▌        | 962/6167 [22:32<25:51,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dominic_Roque.jpg

 16%|█▌        | 964/6167 [22:33<30:59,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JM_de_Guzman.jpg

 16%|█▌        | 965/6167 [22:33<30:38,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jex_de_Castro.jpg

 16%|█▌        | 966/6167 [22:35<48:50,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karina_Constantino_David.jpg

 16%|█▌        | 967/6167 [22:35<44:04,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Glaiza_de_Castro.jpg

 16%|█▌        | 968/6167 [22:35<44:37,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dingdong_Dantes.jpg

 16%|█▌        | 971/6167 [22:36<30:00,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johnoy_Danao.jpg

 16%|█▌        | 972/6167 [22:36<31:36,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fides_Cuyugan-Asensio.jpg

 16%|█▌        | 975/6167 [22:37<20:05,  4.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anne_Curtis.jpg

 16%|█▌        | 976/6167 [22:37<21:03,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sharon_Cuneta.jpg

 16%|█▌        | 978/6167 [22:37<22:09,  3.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josh_Cullen.jpg

 16%|█▌        | 981/6167 [22:38<15:50,  5.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tirso_Cruz_III.jpg

 16%|█▌        | 985/6167 [22:38<14:08,  6.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Israel_Cruz.jpg

 16%|█▌        | 986/6167 [22:38<14:39,  5.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Geneva_Cruz.jpg

 16%|█▌        | 987/6167 [22:40<39:05,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Garry_Cruz.jpg

 16%|█▌        | 989/6167 [22:41<31:19,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Billy_Crawford.jpg

 16%|█▌        | 991/6167 [22:41<24:56,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pilita_Corrales.jpg

 16%|█▌        | 993/6167 [22:41<20:38,  4.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yeng_Constantino.jpg

 16%|█▌        | 994/6167 [22:42<22:30,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joao_Constancia.jpg

 16%|█▌        | 995/6167 [22:43<45:51,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sam_Concepcion.jpg

 16%|█▌        | 996/6167 [22:44<42:10,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/KC_Concepcion.jpg

 16%|█▌        | 997/6167 [22:45<53:57,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gabby_Concepcion.jpg

 16%|█▌        | 998/6167 [22:45<53:37,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noel_Comia_Jr..jpg

 16%|█▌        | 999/6167 [22:46<1:09:31,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Colet.jpg

 16%|█▌        | 1001/6167 [22:48<1:03:19,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Skusta_Clee.jpg

 16%|█▋        | 1003/6167 [22:48<44:26,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julia_Clarete.jpg

 16%|█▋        | 1004/6167 [22:49<48:05,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Charmaine_Clamor.jpg

 16%|█▋        | 1005/6167 [22:49<44:03,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kean_Cipriano.jpg

 16%|█▋        | 1006/6167 [22:50<51:27,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kriesha_Chu.jpg

 16%|█▋        | 1008/6167 [22:50<37:22,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim_Chiu.jpg

 16%|█▋        | 1011/6167 [22:51<24:17,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chanty.jpg

 16%|█▋        | 1012/6167 [22:51<25:43,  3.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jose_Mari_Chan.jpg

 16%|█▋        | 1014/6167 [22:52<27:44,  3.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chris_Cayzer.jpg

 16%|█▋        | 1015/6167 [22:52<26:36,  3.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Castro.jpg

 16%|█▋        | 1016/6167 [22:52<25:41,  3.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ryan_Cayabyab.jpg

 17%|█▋        | 1020/6167 [22:53<18:55,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Carpena.jpg

 17%|█▋        | 1021/6167 [22:53<19:07,  4.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lolita_Carbon.jpg

 17%|█▋        | 1026/6167 [22:54<14:31,  5.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jiggly_Caliente.jpg

 17%|█▋        | 1029/6167 [22:55<16:57,  5.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manuel_Kabajar_Cabase.jpg

 17%|█▋        | 1030/6167 [22:55<18:10,  4.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noel_Cabangon.jpg

 17%|█▋        | 1031/6167 [22:57<48:24,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Federico_Caballero.jpg

 17%|█▋        | 1032/6167 [22:58<44:20,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marcus_Cabais.jpg

 17%|█▋        | 1033/6167 [22:58<41:10,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bruno_Mars.jpg

 17%|█▋        | 1034/6167 [22:58<36:59,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikey_Bustos.jpg

 17%|█▋        | 1036/6167 [22:59<33:13,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vincent_Bueno.jpg

 17%|█▋        | 1037/6167 [22:59<33:34,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ely_Buendia.jpg

 17%|█▋        | 1039/6167 [23:00<24:22,  3.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea_Brillantes.jpg

 17%|█▋        | 1041/6167 [23:01<29:13,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lou_Bonnevie.jpg

 17%|█▋        | 1042/6167 [23:01<27:58,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/AC_Bonifacio.jpg

 17%|█▋        | 1043/6167 [23:01<26:05,  3.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jimmy_Bondoc.jpg

 17%|█▋        | 1045/6167 [23:01<20:58,  4.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rico_Blanco.jpg

 17%|█▋        | 1046/6167 [23:02<28:02,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Blakdyak.jpg

 17%|█▋        | 1048/6167 [23:02<21:45,  3.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bea_Binene.jpg

 17%|█▋        | 1050/6167 [23:03<23:42,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kathryn_Bernardo.jpg

 17%|█▋        | 1051/6167 [23:03<28:50,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janine_Berdin.jpg

 17%|█▋        | 1053/6167 [23:04<24:37,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zild_Benitez.jpg

 17%|█▋        | 1055/6167 [23:04<22:37,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Clara_Benin.jpg

 17%|█▋        | 1058/6167 [23:05<21:33,  3.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sheena_Belarmino.jpg

 17%|█▋        | 1059/6167 [23:05<22:38,  3.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beabadoobee.jpg

 17%|█▋        | 1061/6167 [23:06<20:15,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christian_Bautista.jpg

 17%|█▋        | 1062/6167 [23:06<26:06,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joe_Bataan.jpg

 17%|█▋        | 1063/6167 [23:07<31:31,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bea_Alonzo.jpg

 17%|█▋        | 1066/6167 [23:07<20:39,  4.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lougee_Basabas.jpg

 17%|█▋        | 1069/6167 [23:08<19:44,  4.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bayang_Barrios.jpg

 17%|█▋        | 1070/6167 [23:08<20:15,  4.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edward_Barber.jpg

 17%|█▋        | 1072/6167 [23:09<22:53,  3.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ace_Banzuelo.jpg

 17%|█▋        | 1075/6167 [23:09<17:07,  4.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jovit_Baldivino.jpg

 18%|█▊        | 1080/6167 [23:10<14:43,  5.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joey_Ayala.jpg

 18%|█▊        | 1081/6167 [23:11<20:39,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulo_Avelino.jpg

 18%|█▊        | 1083/6167 [23:11<19:38,  4.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nora_Aunor.jpg

 18%|█▊        | 1087/6167 [23:11<14:47,  5.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicole_Laurel_Asensio.jpg

 18%|█▊        | 1089/6167 [23:12<14:19,  5.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Junji_Arias.jpg

 18%|█▊        | 1090/6167 [23:13<28:40,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Aragon.jpg

 18%|█▊        | 1092/6167 [23:13<24:57,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlo_Aquino.jpg

 18%|█▊        | 1093/6167 [23:14<26:05,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/apl.de.ap.jpg

 18%|█▊        | 1094/6167 [23:14<29:34,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nico_Antonio.jpg

 18%|█▊        | 1105/6167 [23:15<09:58,  8.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Barbie_Almalbis.jpg

 18%|█▊        | 1106/6167 [23:15<14:00,  6.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christine_Allado.jpg

 18%|█▊        | 1107/6167 [23:16<15:46,  5.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ken_Alfonso.jpg

 18%|█▊        | 1109/6167 [23:16<17:52,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rachel_Alejandro.jpg

 18%|█▊        | 1110/6167 [23:17<18:39,  4.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nino_Alejandro.jpg

 18%|█▊        | 1111/6167 [23:17<25:32,  3.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hajji_Alejandro.jpg

 18%|█▊        | 1112/6167 [23:18<25:15,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ogie_Alcasid.jpg

 18%|█▊        | 1113/6167 [23:18<32:03,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leila_Alcasid.jpg

 18%|█▊        | 1114/6167 [23:19<29:13,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyline_Alcantara.jpg

 18%|█▊        | 1116/6167 [23:19<22:53,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayaka_Akimoto.jpg

 18%|█▊        | 1117/6167 [23:20<38:37,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aiah.jpg

 18%|█▊        | 1118/6167 [23:21<44:42,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Freddie_Aguilar.jpg

 18%|█▊        | 1122/6167 [23:21<21:47,  3.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bayani_Agbayani.jpg

 18%|█▊        | 1124/6167 [23:21<18:50,  4.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marcus_Adoro.jpg

 18%|█▊        | 1125/6167 [23:22<23:45,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adie.jpg

 18%|█▊        | 1126/6167 [23:22<25:00,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Migo_Adecer.jpg

 18%|█▊        | 1128/6167 [23:22<20:47,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aljur_Abrenica.jpg

 18%|█▊        | 1129/6167 [23:24<47:17,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Abra.jpg

 18%|█▊        | 1130/6167 [23:25<42:38,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marc_Abaya.jpg

 18%|█▊        | 1131/6167 [23:25<38:28,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dong_Abay.jpg

 18%|█▊        | 1133/6167 [23:26<33:57,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ziggi_Recado.jpg

 18%|█▊        | 1134/6167 [23:26<32:15,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zangeres_Zonder_Naam.jpg

 18%|█▊        | 1135/6167 [23:27<40:43,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yvonne_Keeley.jpg

 18%|█▊        | 1136/6167 [23:28<54:24,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Youp_van_'t_Hek.jpg

 18%|█▊        | 1137/6167 [23:29<59:18,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Xander_de_Buisonjé.jpg

 18%|█▊        | 1139/6167 [23:31<1:13:43,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wouter_Hamel.jpg

 18%|█▊        | 1140/6167 [23:31<1:08:44,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wolter_Kroes.jpg

 19%|█▊        | 1141/6167 [23:32<1:02:36,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wim_de_Bie.jpg

 19%|█▊        | 1142/6167 [23:32<51:54,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wim_Sonneveld.jpg

 19%|█▊        | 1143/6167 [23:34<1:21:51,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wim_Kan.jpg

 19%|█▊        | 1144/6167 [23:35<1:17:34,  1.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wim_Hogenkamp.jpg

 19%|█▊        | 1145/6167 [23:36<1:08:51,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wilma_Landkroon.jpg

 19%|█▊        | 1146/6167 [23:36<1:10:27,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wilma_Driessen.jpg

 19%|█▊        | 1147/6167 [23:37<1:05:54,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willy_Walden.jpg

 19%|█▊        | 1148/6167 [23:39<1:38:16,  1.17s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willy_Alberti.jpg

 19%|█▊        | 1149/6167 [23:40<1:22:30,  1.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willem_Duyn.jpg

 19%|█▊        | 1150/6167 [23:40<1:12:59,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willemijn_Verkaik.jpg

 19%|█▊        | 1151/6167 [23:41<1:10:08,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willeke_Alberti.jpg

 19%|█▊        | 1153/6167 [23:42<1:04:03,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wesley_Klein.jpg

 19%|█▊        | 1154/6167 [23:44<1:21:36,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wieteke_van_Dort.jpg

 19%|█▊        | 1155/6167 [23:45<1:13:16,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wende.jpg

 19%|█▊        | 1156/6167 [23:45<1:10:49,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Waylon.jpg

 19%|█▉        | 1157/6167 [23:47<1:16:08,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wally_Tax.jpg

 19%|█▉        | 1158/6167 [23:47<1:09:33,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/WOW!.jpg

 19%|█▉        | 1159/6167 [23:48<1:13:19,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/VanVelzen.jpg

 19%|█▉        | 1161/6167 [23:50<1:16:51,  1.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Trudy_van_den_Berg.jpg

 19%|█▉        | 1162/6167 [23:51<1:18:09,  1.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Trijntje_Oosterhuis.jpg

 19%|█▉        | 1163/6167 [23:52<1:08:35,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Treble.jpg

 19%|█▉        | 1164/6167 [23:53<1:16:46,  1.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toon_Hermans.jpg

 19%|█▉        | 1165/6167 [23:54<1:33:43,  1.12s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tom_Manders.jpg

 19%|█▉        | 1166/6167 [23:55<1:22:30,  1.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tol_Hansse.jpg

 19%|█▉        | 1167/6167 [23:56<1:21:15,  1.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tim_Knol.jpg

 19%|█▉        | 1168/6167 [23:57<1:16:56,  1.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tim_Douwsma.jpg

 19%|█▉        | 1169/6167 [23:58<1:23:12,  1.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thérèse_Steinmetz.jpg

 19%|█▉        | 1170/6167 [23:59<1:12:58,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thé_Lau.jpg

 19%|█▉        | 1171/6167 [23:59<1:10:28,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thomas_Berge.jpg

 19%|█▉        | 1172/6167 [24:00<1:06:57,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thomas_Azier.jpg

 19%|█▉        | 1173/6167 [24:00<55:17,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thijs_van_Leer.jpg

 19%|█▉        | 1175/6167 [24:01<35:36,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Star_Sisters.jpg

 19%|█▉        | 1176/6167 [24:01<32:45,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Shorts.jpg

 19%|█▉        | 1178/6167 [24:02<36:22,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teddy_Scholten.jpg

 19%|█▉        | 1179/6167 [24:03<43:38,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tatjana_Šimić.jpg

 19%|█▉        | 1180/6167 [24:03<44:09,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tante_Leen.jpg

 19%|█▉        | 1181/6167 [24:04<44:12,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tania_de_Jong.jpg

 19%|█▉        | 1182/6167 [24:05<54:21,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Hoekwater.jpg

 19%|█▉        | 1183/6167 [24:05<44:29,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Taco.jpg

 19%|█▉        | 1185/6167 [24:05<29:57,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sylvia_Kristel.jpg

 19%|█▉        | 1186/6167 [24:06<37:40,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Svenja_van_Beek.jpg

 19%|█▉        | 1188/6167 [24:07<38:52,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stevie_Ann.jpg

 19%|█▉        | 1189/6167 [24:08<42:57,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stella_Maessen.jpg

 19%|█▉        | 1190/6167 [24:08<45:25,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stef_Bos.jpg

 19%|█▉        | 1192/6167 [24:09<36:16,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sita.jpg

 19%|█▉        | 1193/6167 [24:09<37:23,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simone_Simons.jpg

 19%|█▉        | 1194/6167 [24:11<1:03:00,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simone_Kleinsma.jpg

 19%|█▉        | 1195/6167 [24:12<59:06,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simone_Angel.jpg

 19%|█▉        | 1196/6167 [24:12<54:49,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simon_Keizer.jpg

 19%|█▉        | 1197/6167 [24:13<54:31,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Signe_Tollefsen.jpg

 19%|█▉        | 1198/6167 [24:13<44:50,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sieneke.jpg

 19%|█▉        | 1199/6167 [24:14<47:57,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shirley.jpg

 19%|█▉        | 1200/6167 [24:14<47:45,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sharon_den_Adel.jpg

 19%|█▉        | 1201/6167 [24:16<1:11:45,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sharon_Kovacs.jpg

 19%|█▉        | 1202/6167 [24:17<1:06:53,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sharon_Kips.jpg

 20%|█▉        | 1203/6167 [24:17<1:01:08,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sharon_Doorson.jpg

 20%|█▉        | 1206/6167 [24:18<35:15,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanne_Hans.jpg

 20%|█▉        | 1207/6167 [24:18<36:44,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandra_van_Nieuwland.jpg

 20%|█▉        | 1208/6167 [24:19<38:33,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandra_Reemer.jpg

 20%|█▉        | 1209/6167 [24:19<42:22,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sander_Jan_Klerk.jpg

 20%|█▉        | 1210/6167 [24:20<41:40,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sander_Gommans.jpg

 20%|█▉        | 1211/6167 [24:20<40:58,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sabrina_Starke.jpg

 20%|█▉        | 1212/6167 [24:21<50:28,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sabine_Uitslag.jpg

 20%|█▉        | 1213/6167 [24:22<43:01,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruud_Schaap.jpg

 20%|█▉        | 1214/6167 [24:23<1:11:51,  1.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruth_Jacott.jpg

 20%|█▉        | 1215/6167 [24:24<1:13:16,  1.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rudi_Carrell.jpg

 20%|█▉        | 1216/6167 [24:25<1:00:07,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rosy_Pereira.jpg

 20%|█▉        | 1217/6167 [24:26<1:21:06,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rood_Adeo.jpg

 20%|█▉        | 1218/6167 [24:27<1:15:20,  1.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ronald_van_Prooijen.jpg

 20%|█▉        | 1219/6167 [24:27<1:04:31,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ron_Link.jpg

 20%|█▉        | 1220/6167 [24:28<1:01:24,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romy_Haag.jpg

 20%|█▉        | 1221/6167 [24:29<1:01:19,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rolinha_Kross.jpg

 20%|█▉        | 1222/6167 [24:29<55:34,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roger_Peterson.jpg

 20%|█▉        | 1223/6167 [24:30<55:06,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rochelle_Perts.jpg

 20%|█▉        | 1224/6167 [24:30<45:58,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robert_Westerholt.jpg

 20%|█▉        | 1225/6167 [24:31<49:09,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robert_Long.jpg

 20%|█▉        | 1226/6167 [24:31<45:00,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robert_Holl.jpg

 20%|█▉        | 1227/6167 [24:32<56:36,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robbie_van_Leeuwen.jpg

 20%|█▉        | 1228/6167 [24:33<52:41,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rob_de_Nijs.jpg

 20%|█▉        | 1229/6167 [24:34<56:23,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Reys.jpg

 20%|█▉        | 1230/6167 [24:34<57:05,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rijk_de_Gooyer.jpg

 20%|█▉        | 1231/6167 [24:35<1:04:47,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ria_Valk.jpg

 20%|█▉        | 1233/6167 [24:36<39:50,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ria_Brieffies.jpg

 20%|██        | 1234/6167 [24:37<47:00,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/René_Shuman.jpg

 20%|██        | 1236/6167 [24:37<37:48,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/René_Froger.jpg

 20%|██        | 1237/6167 [24:38<35:06,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ray_Slijngaard.jpg

 20%|██        | 1238/6167 [24:38<38:06,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rania_Zeriri.jpg

 20%|██        | 1239/6167 [24:39<40:40,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ramses_Shaffy.jpg

 20%|██        | 1240/6167 [24:40<53:35,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raffaëla_Paton.jpg

 20%|██        | 1241/6167 [24:40<53:50,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ralf_Mackenbach.jpg

 20%|██        | 1242/6167 [24:41<56:50,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rachèl_Louise.jpg

 20%|██        | 1243/6167 [24:42<1:05:49,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rachel_Traets.jpg

 20%|██        | 1244/6167 [24:44<1:19:31,  1.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rachel_Kramer.jpg

 20%|██        | 1245/6167 [24:44<1:04:33,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Princess_Christina_of_the_Netherlands.jpg

 20%|██        | 1246/6167 [24:45<1:03:27,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Polle_Eduard.jpg

 20%|██        | 1247/6167 [24:45<1:00:48,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Piet_Veerman.jpg

 20%|██        | 1248/6167 [24:47<1:13:29,  1.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Piet_Römer.jpg

 20%|██        | 1249/6167 [24:47<59:58,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pierre_Kartner.jpg

 20%|██        | 1250/6167 [24:47<50:26,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Piet_Muijselaar.jpg

 20%|██        | 1251/6167 [24:48<42:34,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pia_Douwes.jpg

 20%|██        | 1252/6167 [24:48<44:19,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Phatt_(Ricardo_Burgrust).jpg

 20%|██        | 1254/6167 [24:49<34:21,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Van_Wood.jpg

 20%|██        | 1256/6167 [24:50<32:46,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Blanker.jpg

 20%|██        | 1258/6167 [24:50<31:27,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paul_de_Leeuw.jpg

 20%|██        | 1259/6167 [24:51<30:33,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patty_Brard.jpg

 20%|██        | 1261/6167 [24:51<27:15,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patrick_Mameli.jpg

 20%|██        | 1262/6167 [24:52<41:03,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patricia_Paay.jpg

 20%|██        | 1264/6167 [24:53<33:47,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oscar_Benton.jpg

 21%|██        | 1266/6167 [24:54<35:30,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olivier_Heim.jpg

 21%|██        | 1267/6167 [24:54<40:21,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/O'G3NE.jpg

 21%|██        | 1268/6167 [24:55<43:08,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oedo_Kuipers.jpg

 21%|██        | 1269/6167 [24:56<43:52,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nynke_Laverman.jpg

 21%|██        | 1270/6167 [24:56<42:46,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ntjam_Rosie.jpg

 21%|██        | 1271/6167 [24:57<43:58,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikki_Kerkhof.jpg

 21%|██        | 1272/6167 [24:57<44:29,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nightporter.jpg

 21%|██        | 1273/6167 [24:58<45:12,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nielson.jpg

 21%|██        | 1274/6167 [24:59<48:53,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Niels_Geusebroek.jpg

 21%|██        | 1277/6167 [24:59<30:23,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nick_Schilder.jpg

 21%|██        | 1278/6167 [25:00<40:52,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nick_&_Simon.jpg

 21%|██        | 1279/6167 [25:01<47:20,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nathalie_Makoma.jpg

 21%|██        | 1282/6167 [25:02<35:53,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nancy_Coolen.jpg

 21%|██        | 1283/6167 [25:02<33:43,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monique_Smit.jpg

 21%|██        | 1284/6167 [25:03<35:08,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monica_Verschoor.jpg

 21%|██        | 1285/6167 [25:04<42:31,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mirjam_Timmer.jpg

 21%|██        | 1286/6167 [25:04<46:51,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milly_Scott.jpg

 21%|██        | 1287/6167 [25:05<46:32,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miggy.jpg

 21%|██        | 1288/6167 [25:05<39:33,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michelle_Courtens.jpg

 21%|██        | 1289/6167 [25:05<36:32,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maywood.jpg

 21%|██        | 1290/6167 [25:06<43:04,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Lavelle.jpg

 21%|██        | 1291/6167 [25:07<47:06,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Hakvoort.jpg

 21%|██        | 1292/6167 [25:07<47:48,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Max_van_Egmond.jpg

 21%|██        | 1293/6167 [25:08<48:11,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Max_Werner.jpg

 21%|██        | 1294/6167 [25:09<45:04,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maurice_de_Jong.jpg

 21%|██        | 1295/6167 [25:09<48:00,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Max_Blokzijl.jpg

 21%|██        | 1297/6167 [25:10<37:06,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mathilde_Santing.jpg

 21%|██        | 1298/6167 [25:10<41:44,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martine_van_Loon.jpg

 21%|██        | 1299/6167 [25:11<43:08,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martin_van_Drunen.jpg

 21%|██        | 1300/6167 [25:12<47:48,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martin_Porter.jpg

 21%|██        | 1301/6167 [25:12<45:32,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marlayne.jpg

 21%|██        | 1302/6167 [25:13<40:43,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mark_Ritsema.jpg

 21%|██        | 1303/6167 [25:13<37:12,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mark_Jansen.jpg

 21%|██        | 1304/6167 [25:13<33:25,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marius_van_Altena.jpg

 21%|██        | 1305/6167 [25:14<42:21,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariska_Veres.jpg

 21%|██        | 1306/6167 [25:15<46:12,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marike_Jager.jpg

 21%|██        | 1307/6167 [25:15<40:09,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marike_Groot.jpg

 21%|██        | 1309/6167 [25:16<35:34,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maribelle.jpg

 21%|██▏       | 1311/6167 [25:17<33:19,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Francisca_Bia.jpg

 21%|██▏       | 1312/6167 [25:17<36:32,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marga_Scheide.jpg

 21%|██▏       | 1313/6167 [25:18<36:14,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marco_Borsato.jpg

 21%|██▏       | 1314/6167 [25:18<33:13,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marcha.jpg

 21%|██▏       | 1316/6167 [25:18<27:29,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manke_Nelis.jpg

 21%|██▏       | 1317/6167 [25:20<54:23,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manda_Ophuis.jpg

 21%|██▏       | 1318/6167 [25:21<54:09,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maitri.jpg

 21%|██▏       | 1319/6167 [25:21<52:32,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/MainStreet.jpg

 21%|██▏       | 1320/6167 [25:22<55:02,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mai_Tai.jpg

 21%|██▏       | 1321/6167 [25:23<54:25,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maggie_MacNeal.jpg

 21%|██▏       | 1322/6167 [25:24<54:12,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maartje_Offers.jpg

 21%|██▏       | 1323/6167 [25:24<58:43,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maarten_van_Roozendaal.jpg

 21%|██▏       | 1324/6167 [25:25<54:45,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maarten_Heijmans.jpg

 22%|██▏       | 1327/6167 [25:25<31:35,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luv'.jpg

 22%|██▏       | 1328/6167 [25:26<29:48,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Loïs_Lane.jpg

 22%|██▏       | 1329/6167 [25:27<37:28,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Louis_Davids.jpg

 22%|██▏       | 1330/6167 [25:27<42:35,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lou_Bandy.jpg

 22%|██▏       | 1331/6167 [25:28<43:29,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Loona.jpg

 22%|██▏       | 1333/6167 [25:30<58:45,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lisa_Hordijk.jpg

 22%|██▏       | 1334/6167 [25:30<57:36,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linda_Williams.jpg

 22%|██▏       | 1335/6167 [25:31<55:48,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linda_Wagenmakers.jpg

 22%|██▏       | 1336/6167 [25:33<1:16:10,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linda_Estelle.jpg

 22%|██▏       | 1337/6167 [25:33<1:06:04,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lils_Mackintosh.jpg

 22%|██▏       | 1338/6167 [25:34<59:06,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liesbeth_List.jpg

 22%|██▏       | 1339/6167 [25:34<53:34,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lia_Dorana.jpg

 22%|██▏       | 1340/6167 [25:35<50:44,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lexington_Bridge.jpg

 22%|██▏       | 1341/6167 [25:35<51:39,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lex_van_Delden.jpg

 22%|██▏       | 1342/6167 [25:37<1:18:30,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lex_Goudsmit.jpg

 22%|██▏       | 1343/6167 [25:38<1:07:27,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leonie_Meijer.jpg

 22%|██▏       | 1344/6167 [25:38<1:02:07,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leoni_Jansen.jpg

 22%|██▏       | 1345/6167 [25:39<57:18,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leo_Fuld.jpg

 22%|██▏       | 1346/6167 [25:40<1:05:45,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lenny_Kuhr.jpg

 22%|██▏       | 1349/6167 [25:42<52:38,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lee_Towers.jpg

 22%|██▏       | 1351/6167 [25:43<58:51,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Jansen.jpg

 22%|██▏       | 1352/6167 [25:44<55:24,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Fygi.jpg

 22%|██▏       | 1353/6167 [25:45<55:53,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lana_Wolf.jpg

 22%|██▏       | 1354/6167 [25:45<52:44,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kizzy.jpg

 22%|██▏       | 1355/6167 [25:46<51:58,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kimm_Hekker.jpg

 22%|██▏       | 1356/6167 [25:46<50:15,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim-Lian.jpg

 22%|██▏       | 1357/6167 [25:48<1:11:18,  1.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim_Hoorweg.jpg

 22%|██▏       | 1358/6167 [25:49<1:12:07,  1.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Keren_Ann.jpg

 22%|██▏       | 1359/6167 [25:49<1:04:31,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenny_B.jpg

 22%|██▏       | 1360/6167 [25:50<1:02:13,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katja_Schuurman.jpg

 22%|██▏       | 1361/6167 [25:51<56:44,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karin_Bloemen.jpg

 22%|██▏       | 1363/6167 [25:51<35:30,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/K3.jpg

 22%|██▏       | 1364/6167 [25:52<47:33,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Justine_Pelmelay.jpg

 22%|██▏       | 1365/6167 [25:52<41:00,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julia_van_Bergen.jpg

 22%|██▏       | 1366/6167 [25:53<47:34,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julia_Culp.jpg

 22%|██▏       | 1369/6167 [25:54<29:58,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Hoebee.jpg

 22%|██▏       | 1370/6167 [25:54<30:14,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josje_Huisman.jpg

 22%|██▏       | 1371/6167 [25:55<37:03,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jos_Brink.jpg

 22%|██▏       | 1372/6167 [25:55<32:39,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jordy_van_Loon.jpg

 22%|██▏       | 1373/6167 [25:55<30:02,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joost_Klein.jpg

 22%|██▏       | 1374/6167 [25:56<42:05,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joost_Prinsen.jpg

 22%|██▏       | 1375/6167 [25:57<44:52,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johnny_Jordaan.jpg

 22%|██▏       | 1376/6167 [25:58<52:59,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johnny_&_Jones.jpg

 22%|██▏       | 1379/6167 [25:59<47:14,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johan_Messchaert.jpg

 22%|██▏       | 1380/6167 [26:01<1:04:19,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johannes_Heesters.jpg

 22%|██▏       | 1381/6167 [26:02<1:17:15,  1.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joan_Franka.jpg

 22%|██▏       | 1382/6167 [26:03<1:16:39,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jim_Bakkum.jpg

 22%|██▏       | 1383/6167 [26:05<1:19:21,  1.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jetty_Paerl.jpg

 22%|██▏       | 1384/6167 [26:05<1:15:11,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jeronimo_van_Ballegoijen.jpg

 22%|██▏       | 1385/6167 [26:06<1:10:07,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jett_Rebel.jpg

 22%|██▏       | 1386/6167 [26:07<1:04:06,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jeroen_van_der_Boom.jpg

 23%|██▎       | 1388/6167 [26:07<47:20,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jerney_Kaagman.jpg

 23%|██▎       | 1389/6167 [26:08<55:00,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jenny_Arean.jpg

 23%|██▎       | 1390/6167 [26:09<54:49,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelka_van_Houten.jpg

 23%|██▎       | 1391/6167 [26:10<52:46,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janine_Kitzen.jpg

 23%|██▎       | 1393/6167 [26:10<36:08,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jan_Smit.jpg

 23%|██▎       | 1394/6167 [26:10<37:42,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jan_Rot.jpg

 23%|██▎       | 1395/6167 [26:11<45:29,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jan_Mesdag.jpg

 23%|██▎       | 1396/6167 [26:12<51:43,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jan_Keizer.jpg

 23%|██▎       | 1397/6167 [26:13<49:12,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jamai_Loman.jpg

 23%|██▎       | 1398/6167 [26:13<42:07,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Urlus.jpg

 23%|██▎       | 1399/6167 [26:14<1:00:02,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacqueline_Govaert.jpg

 23%|██▎       | 1400/6167 [26:15<54:34,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jack_Poels.jpg

 23%|██▎       | 1401/6167 [26:16<1:03:56,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jack_Jersey.jpg

 23%|██▎       | 1402/6167 [26:17<1:08:40,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Izaline_Calister.jpg

 23%|██▎       | 1403/6167 [26:17<58:04,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaap_Reesema.jpg

 23%|██▎       | 1404/6167 [26:18<1:03:28,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iris_Kroes.jpg

 23%|██▎       | 1405/6167 [26:19<1:03:09,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irene_Moors.jpg

 23%|██▎       | 1406/6167 [26:19<49:04,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irene_Jansen.jpg

 23%|██▎       | 1407/6167 [26:20<40:24,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Imran_Khan.jpg

 23%|██▎       | 1408/6167 [26:20<40:03,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilse_Huizinga.jpg

 23%|██▎       | 1409/6167 [26:20<33:42,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilse_DeLange.jpg

 23%|██▎       | 1411/6167 [26:21<38:53,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Huug_Kok.jpg

 23%|██▎       | 1412/6167 [26:22<41:58,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Humphrey_Campbell.jpg

 23%|██▎       | 1413/6167 [26:23<45:26,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hind_Laroussi.jpg

 23%|██▎       | 1414/6167 [26:24<48:27,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hilbrand_Nawijn.jpg

 23%|██▎       | 1415/6167 [26:24<53:07,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hetty_Blok.jpg

 23%|██▎       | 1416/6167 [26:25<55:52,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hessel.jpg

 23%|██▎       | 1417/6167 [26:26<54:10,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Herman_van_Veen.jpg

 23%|██▎       | 1419/6167 [26:26<42:18,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Herman_Brood.jpg

 23%|██▎       | 1420/6167 [26:27<46:11,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Herman_Brock_Jr..jpg

 23%|██▎       | 1421/6167 [26:28<45:53,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henri_van_Zanten.jpg

 23%|██▎       | 1422/6167 [26:29<49:40,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henri_Sattler.jpg

 23%|██▎       | 1423/6167 [26:29<49:11,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henri_Albers.jpg

 23%|██▎       | 1424/6167 [26:31<1:14:24,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henny_Vrienten.jpg

 23%|██▎       | 1425/6167 [26:32<1:09:21,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henkie.jpg

 23%|██▎       | 1426/6167 [26:32<1:04:58,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henk_Wijngaard.jpg

 23%|██▎       | 1427/6167 [26:33<1:00:46,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henk_Westbroek.jpg

 23%|██▎       | 1428/6167 [26:34<57:25,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Henk_Poort.jpg

 23%|██▎       | 1429/6167 [26:35<1:04:12,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heintje_Simons.jpg

 23%|██▎       | 1430/6167 [26:35<58:15,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heddy_Lester.jpg

 23%|██▎       | 1431/6167 [26:36<56:27,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hearts_of_Soul.jpg

 23%|██▎       | 1433/6167 [26:36<41:46,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Harry_Muskee.jpg

 23%|██▎       | 1434/6167 [26:37<45:41,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Alagic.jpg

 23%|██▎       | 1435/6167 [26:38<57:34,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Guusje_Nederhorst.jpg

 23%|██▎       | 1436/6167 [26:40<1:09:33,  1.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Guus_Meeuwis.jpg

 23%|██▎       | 1437/6167 [26:41<1:14:50,  1.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gré_Brouwenstijn.jpg

 23%|██▎       | 1438/6167 [26:41<1:08:13,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greetje_Kauffeld.jpg

 23%|██▎       | 1439/6167 [26:42<1:01:43,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gordon_Heuckeroth.jpg

 23%|██▎       | 1440/6167 [26:43<1:02:23,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Glennis_Grace.jpg

 23%|██▎       | 1441/6167 [26:44<1:11:09,  1.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Getty_Kaspers.jpg

 23%|██▎       | 1442/6167 [26:44<58:07,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gerard_Joling.jpg

 23%|██▎       | 1443/6167 [26:45<52:55,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gerard_Cox.jpg

 23%|██▎       | 1444/6167 [26:45<49:40,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Georgina_Verbaan.jpg

 23%|██▎       | 1446/6167 [26:46<35:04,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Kooymans.jpg

 23%|██▎       | 1447/6167 [26:46<39:15,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Baker.jpg

 23%|██▎       | 1448/6167 [26:47<44:08,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/G.W._Sok.jpg

 23%|██▎       | 1449/6167 [26:48<44:35,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frizzle_Sizzle.jpg

 24%|██▎       | 1450/6167 [26:48<39:42,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frisz.jpg

 24%|██▎       | 1451/6167 [26:50<1:10:48,  1.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Freek_de_Jonge.jpg

 24%|██▎       | 1452/6167 [26:50<57:30,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frederik_van_Pallandt.jpg

 24%|██▎       | 1453/6167 [26:51<55:09,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fred_Wiegman.jpg

 24%|██▎       | 1454/6167 [26:53<1:17:01,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frans_Duijts.jpg

 24%|██▎       | 1455/6167 [26:53<1:07:29,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frans_Bauer.jpg

 24%|██▎       | 1456/6167 [26:54<1:02:56,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frank_Boeijen.jpg

 24%|██▎       | 1458/6167 [26:55<46:30,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francien_van_Tuinen.jpg

 24%|██▎       | 1459/6167 [26:55<41:48,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Forrest.jpg

 24%|██▎       | 1460/6167 [26:56<43:07,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Floortje_Smit.jpg

 24%|██▎       | 1461/6167 [26:56<44:56,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Floor_Jansen.jpg

 24%|██▎       | 1462/6167 [26:57<44:52,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ewout_Genemans.jpg

 24%|██▎       | 1463/6167 [26:58<50:31,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eva-Maria_Westbroek.jpg

 24%|██▎       | 1464/6167 [26:58<42:41,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eva_Simons.jpg

 24%|██▍       | 1466/6167 [26:58<32:14,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esmée_Denters.jpg

 24%|██▍       | 1467/6167 [26:59<36:28,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esther_Hart.jpg

 24%|██▍       | 1468/6167 [27:00<40:37,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erna_Spoorenberg.jpg

 24%|██▍       | 1469/6167 [27:00<34:14,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erik_Hulzebosch.jpg

 24%|██▍       | 1470/6167 [27:00<36:09,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eric_Corton.jpg

 24%|██▍       | 1471/6167 [27:01<38:16,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emil_Landman.jpg

 24%|██▍       | 1472/6167 [27:02<40:29,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emma_Kok.jpg

 24%|██▍       | 1474/6167 [27:02<27:22,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elly_Ameling.jpg

 24%|██▍       | 1475/6167 [27:03<52:12,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ellen_ten_Damme.jpg

 24%|██▍       | 1476/6167 [27:05<1:04:29,  1.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/EliZe.jpg

 24%|██▍       | 1477/6167 [27:06<1:06:27,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eefje_de_Visser.jpg

 24%|██▍       | 1479/6167 [27:06<47:24,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edward_Reekers.jpg

 24%|██▍       | 1480/6167 [27:07<42:05,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edsilia_Rombley.jpg

 24%|██▍       | 1481/6167 [27:07<49:43,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ede_Staal.jpg

 24%|██▍       | 1482/6167 [27:08<52:19,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eddy_Christiani.jpg

 24%|██▍       | 1483/6167 [27:09<1:01:33,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/E-Life.jpg

 24%|██▍       | 1484/6167 [27:10<55:15,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Duncan_Laurence.jpg

 24%|██▍       | 1485/6167 [27:10<51:39,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Drs._P.jpg

 24%|██▍       | 1486/6167 [27:11<51:25,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dries_Roelvink.jpg

 24%|██▍       | 1487/6167 [27:11<45:23,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dries_Holten.jpg

 24%|██▍       | 1489/6167 [27:13<56:31,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Douwe_Bob.jpg

 24%|██▍       | 1490/6167 [27:14<48:20,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dotan_Harpenau.jpg

 24%|██▍       | 1491/6167 [27:15<1:14:15,  1.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dorona_Alberti.jpg

 24%|██▍       | 1492/6167 [27:16<1:12:06,  1.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dolly_Dots.jpg

 24%|██▍       | 1493/6167 [27:17<1:04:14,  1.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dolf_Brouwers.jpg

 24%|██▍       | 1494/6167 [27:17<57:41,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Do.jpg

 24%|██▍       | 1495/6167 [27:18<55:12,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dinand_Woesthoff.jpg

 24%|██▍       | 1496/6167 [27:20<1:24:10,  1.08s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dick_Rienstra.jpg

 24%|██▍       | 1497/6167 [27:21<1:18:31,  1.01s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dick_Annegarn.jpg

 24%|██▍       | 1498/6167 [27:21<1:08:03,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dianne_van_Giersbergen.jpg

 24%|██▍       | 1500/6167 [27:22<49:51,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Devriès_family.jpg

 24%|██▍       | 1501/6167 [27:23<53:22,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Denise_Jannah.jpg

 24%|██▍       | 1502/6167 [27:24<53:27,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Debbie.jpg

 24%|██▍       | 1503/6167 [27:24<51:44,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dean_Saunders.jpg

 24%|██▍       | 1505/6167 [27:25<34:13,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/David_Alexandre_Winter.jpg

 24%|██▍       | 1506/6167 [27:25<31:39,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dave.jpg

 24%|██▍       | 1507/6167 [27:26<48:33,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danny_de_Munk.jpg

 24%|██▍       | 1508/6167 [27:27<57:31,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniël_Sahuleka.jpg

 24%|██▍       | 1509/6167 [27:30<1:39:30,  1.28s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daisy_Dee.jpg

 24%|██▍       | 1510/6167 [27:31<1:25:11,  1.10s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cristina_Deutekom.jpg

 25%|██▍       | 1511/6167 [27:31<1:19:23,  1.02s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Corry_Brokken.jpg

 25%|██▍       | 1512/6167 [27:32<1:04:31,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cornélie_van_Zanten.jpg

 25%|██▍       | 1513/6167 [27:32<59:47,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cornelis_Vreeswijk.jpg

 25%|██▍       | 1515/6167 [27:33<43:13,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Conny_Vandenbos.jpg

 25%|██▍       | 1516/6167 [27:34<53:48,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Conny_Stuart.jpg

 25%|██▍       | 1517/6167 [27:35<53:10,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coen_van_Vrijberghe_de_Coningh.jpg

 25%|██▍       | 1518/6167 [27:35<54:08,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Co_Verdaas.jpg

 25%|██▍       | 1519/6167 [27:36<50:48,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Close_II_You.jpg

 25%|██▍       | 1520/6167 [27:37<48:47,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christel_Adelaar.jpg

 25%|██▍       | 1521/6167 [27:37<48:38,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Charlotte_Wessels.jpg

 25%|██▍       | 1522/6167 [27:39<1:11:39,  1.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Charlotte_Margiono.jpg

 25%|██▍       | 1524/6167 [27:39<50:01,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chantal_Janzen.jpg

 25%|██▍       | 1525/6167 [27:40<43:15,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Centerfold.jpg

 25%|██▍       | 1526/6167 [27:42<1:08:10,  1.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celine_Cairo.jpg

 25%|██▍       | 1527/6167 [27:42<1:01:00,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cees_Veerman.jpg

 25%|██▍       | 1528/6167 [27:43<59:04,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Caught_in_the_Act.jpg

 25%|██▍       | 1530/6167 [27:43<42:30,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carola_Smit.jpg

 25%|██▍       | 1531/6167 [27:44<38:46,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Caro_Emerald.jpg

 25%|██▍       | 1532/6167 [27:45<45:20,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carina_Lemoine.jpg

 25%|██▍       | 1533/6167 [27:45<48:33,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anita_Doth.jpg

 25%|██▍       | 1534/6167 [27:46<40:55,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anneke_Grönloh.jpg

 25%|██▍       | 1535/6167 [27:46<35:14,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andy_Tielman.jpg

 25%|██▍       | 1536/6167 [27:46<30:58,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angela_Groothuizen.jpg

 25%|██▍       | 1537/6167 [27:48<54:30,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ann_Burton.jpg

 25%|██▍       | 1538/6167 [27:48<43:53,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anita_Meyer.jpg

 25%|██▍       | 1539/6167 [27:48<42:55,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/André_van_Duin.jpg

 25%|██▍       | 1540/6167 [27:49<40:47,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/André_Manuel.jpg

 25%|██▍       | 1541/6167 [27:49<39:53,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/André_Hazes.jpg

 25%|██▌       | 1542/6167 [27:50<40:17,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amira_Willighagen.jpg

 25%|██▌       | 1545/6167 [27:51<29:40,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albert_West.jpg

 25%|██▌       | 1546/6167 [27:51<31:05,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aaltje_Noordewier-Reddingius.jpg

 25%|██▌       | 1547/6167 [27:52<34:41,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aafje_Heynis.jpg

 25%|██▌       | 1552/6167 [27:52<15:30,  4.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yusa.jpg

 25%|██▌       | 1553/6167 [27:53<30:51,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alberto_Villalón.jpg

 25%|██▌       | 1554/6167 [27:54<31:59,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mayra_Verónica.jpg

 25%|██▌       | 1555/6167 [27:54<33:09,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dominica_Verges.jpg

 25%|██▌       | 1556/6167 [27:55<34:07,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/María_Teresa_Vera.jpg

 25%|██▌       | 1557/6167 [27:56<54:44,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lis_Vega.jpg

 25%|██▌       | 1558/6167 [27:57<52:07,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_Varela.jpg

 25%|██▌       | 1559/6167 [27:58<50:35,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miguelito_Valdés.jpg

 25%|██▌       | 1560/6167 [27:58<46:30,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Merceditas_Valdés.jpg

 25%|██▌       | 1561/6167 [27:59<45:52,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Trio_Matamoros.jpg

 25%|██▌       | 1562/6167 [28:00<50:57,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malú_Trevejo.jpg

 25%|██▌       | 1563/6167 [28:00<49:00,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Torres.jpg

 25%|██▌       | 1564/6167 [28:01<46:34,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leoni_Torres.jpg

 25%|██▌       | 1565/6167 [28:01<44:31,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chanel_Terrero.jpg

 25%|██▌       | 1566/6167 [28:03<1:02:34,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Compay_Segundo.jpg

 25%|██▌       | 1568/6167 [28:03<45:29,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jon_Secada.jpg

 25%|██▌       | 1569/6167 [28:04<43:13,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ñico_Saquito.jpg

 25%|██▌       | 1570/6167 [28:04<42:21,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Sandunga.jpg

 25%|██▌       | 1571/6167 [28:05<38:46,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pepe_Sánchez.jpg

 25%|██▌       | 1572/6167 [28:05<37:54,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rosendo_Ruiz.jpg

 26%|██▌       | 1573/6167 [28:06<38:37,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rey_Ruiz.jpg

 26%|██▌       | 1575/6167 [28:06<29:56,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yotuel_Romero.jpg

 26%|██▌       | 1576/6167 [28:08<49:18,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvio_Rodríguez.jpg

 26%|██▌       | 1577/6167 [28:08<46:00,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aldo_Rodríguez.jpg

 26%|██▌       | 1578/6167 [28:09<45:33,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raquel_Rodrigo.jpg

 26%|██▌       | 1579/6167 [28:10<54:48,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Panchito_Riset.jpg

 26%|██▌       | 1583/6167 [28:10<29:48,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Evelin_Ramón.jpg

 26%|██▌       | 1586/6167 [28:11<24:06,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adonis_Puentes.jpg

 26%|██▌       | 1587/6167 [28:13<40:33,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_Puebla.jpg

 26%|██▌       | 1590/6167 [28:13<29:15,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diamela_del_Pozo.jpg

 26%|██▌       | 1591/6167 [28:13<28:14,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Omara_Portuondo.jpg

 26%|██▌       | 1598/6167 [28:14<13:25,  5.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bola_de_Nieve.jpg

 26%|██▌       | 1600/6167 [28:14<14:41,  5.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benny_Moré.jpg

 26%|██▌       | 1602/6167 [28:15<15:47,  4.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Montaner.jpg

 26%|██▌       | 1605/6167 [28:15<13:38,  5.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pablo_Milanés.jpg

 26%|██▌       | 1606/6167 [28:16<16:50,  4.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haydée_Milanés.jpg

 26%|██▌       | 1608/6167 [28:16<17:46,  4.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Addys_Mercedes.jpg

 26%|██▌       | 1610/6167 [28:17<18:45,  4.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Margarita_Martínez-Casado.jpg

 26%|██▌       | 1613/6167 [28:17<15:12,  4.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Martínez.jpg

 26%|██▌       | 1615/6167 [28:18<16:24,  4.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Machito.jpg

 26%|██▌       | 1616/6167 [28:18<21:17,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antonio_Machín.jpg

 26%|██▌       | 1617/6167 [28:19<24:47,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/La_Lupe.jpg

 26%|██▌       | 1618/6167 [28:20<30:41,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pedro_Lugo.jpg

 26%|██▋       | 1619/6167 [28:20<33:30,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucrecia.jpg

 26%|██▋       | 1623/6167 [28:22<34:14,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Margarita_Lecuona.jpg

 26%|██▋       | 1625/6167 [28:23<32:21,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rolando_Laserie.jpg

 26%|██▋       | 1626/6167 [28:23<34:13,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kumar.jpg

 26%|██▋       | 1627/6167 [28:24<39:02,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Israel_Kantor.jpg

 26%|██▋       | 1632/6167 [28:25<22:51,  3.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liuba_María_Hevia.jpg

 26%|██▋       | 1633/6167 [28:25<25:15,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chalía_Herrera.jpg

 27%|██▋       | 1635/6167 [28:27<31:14,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heradel.jpg

 27%|██▋       | 1637/6167 [28:27<30:28,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diego_Gutiérrez.jpg

 27%|██▋       | 1641/6167 [28:28<25:34,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bienvenido_Granda.jpg

 27%|██▋       | 1642/6167 [28:29<29:20,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Graciela.jpg

 27%|██▋       | 1645/6167 [28:29<21:24,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celina_González.jpg

 27%|██▋       | 1646/6167 [28:30<24:26,  3.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_González_Gómez.jpg

 27%|██▋       | 1648/6167 [28:30<23:18,  3.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Osmani_García.jpg

 27%|██▋       | 1651/6167 [28:31<21:31,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sindo_Garay.jpg

 27%|██▋       | 1653/6167 [28:33<33:19,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rosita_Fornés.jpg

 27%|██▋       | 1654/6167 [28:33<34:13,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Fonseca.jpg

 27%|██▋       | 1655/6167 [28:36<1:01:56,  1.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulito_FG.jpg

 27%|██▋       | 1656/6167 [28:36<53:35,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ibrahim_Ferrer.jpg

 27%|██▋       | 1658/6167 [28:37<40:23,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucio_Fernandez.jpg

 27%|██▋       | 1661/6167 [28:37<27:11,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Santiago_Feliú.jpg

 27%|██▋       | 1665/6167 [28:37<17:46,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria_Estefan.jpg

 27%|██▋       | 1666/6167 [28:38<20:49,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Glenda_del_E.jpg

 27%|██▋       | 1668/6167 [28:39<23:53,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Barbarito_Díez.jpg

 27%|██▋       | 1671/6167 [28:39<20:10,  3.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Cuba.jpg

 27%|██▋       | 1672/6167 [28:40<20:10,  3.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celia_Cruz.jpg

 27%|██▋       | 1673/6167 [28:40<24:13,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manuel_Corona.jpg

 27%|██▋       | 1674/6167 [28:41<29:35,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jorge_Cordero.jpg

 27%|██▋       | 1676/6167 [28:41<25:45,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adolfo_Colombo.jpg

 27%|██▋       | 1678/6167 [28:42<23:02,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Willy_Chirino.jpg

 27%|██▋       | 1679/6167 [28:43<31:14,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francisco_Céspedes.jpg

 27%|██▋       | 1680/6167 [28:44<43:22,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Espiridiona_Cenda.jpg

 27%|██▋       | 1681/6167 [28:44<42:31,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teté_Caturla.jpg

 27%|██▋       | 1682/6167 [28:45<38:38,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Isabella_Castillo.jpg

 27%|██▋       | 1683/6167 [28:46<46:07,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cascarita.jpg

 27%|██▋       | 1685/6167 [28:46<38:38,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yilian_Cañizares.jpg

 27%|██▋       | 1690/6167 [28:47<21:23,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malena_Burke.jpg

 27%|██▋       | 1691/6167 [28:48<32:05,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lena_Burke.jpg

 27%|██▋       | 1692/6167 [28:49<37:55,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Burke.jpg

 27%|██▋       | 1694/6167 [28:50<31:11,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julio_Brito.jpg

 27%|██▋       | 1695/6167 [28:51<36:22,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alfredo_Brito.jpg

 28%|██▊       | 1696/6167 [28:51<42:39,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esther_Borja.jpg

 28%|██▊       | 1697/6167 [28:52<38:14,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/La_Dame_Blanche.jpg

 28%|██▊       | 1699/6167 [28:52<33:47,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patricio_Ballagas.jpg

 28%|██▊       | 1700/6167 [28:54<54:13,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Don_Marino_Barreto_Jr..jpg

 28%|██▊       | 1702/6167 [28:55<45:03,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daymé_Arocena.jpg

 28%|██▊       | 1703/6167 [28:56<45:23,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eduardo_Antonio.jpg

 28%|██▊       | 1705/6167 [28:58<57:25,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulina_Álvarez.jpg

 28%|██▊       | 1706/6167 [28:58<49:03,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pacho_Alonso.jpg

 28%|██▊       | 1707/6167 [28:58<46:03,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Xiomara_Alfaro.jpg

 28%|██▊       | 1708/6167 [28:59<42:42,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liset_Alea.jpg

 28%|██▊       | 1709/6167 [29:00<44:20,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexander_Abreu.jpg

 28%|██▊       | 1711/6167 [29:00<39:03,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Outline.jpg

 28%|██▊       | 1712/6167 [29:01<38:43,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Interlace.jpg

 28%|██▊       | 1713/6167 [29:01<33:34,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Names.jpg

 28%|██▊       | 1714/6167 [29:02<36:13,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Decorations.jpg

 28%|██▊       | 1715/6167 [29:03<42:22,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Crown.jpg

 28%|██▊       | 1716/6167 [29:03<41:15,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Costume.jpg

 28%|██▊       | 1717/6167 [29:03<36:28,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coat_of_arms.jpg

 28%|██▊       | 1718/6167 [29:04<36:01,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Checkerboard.jpg

 28%|██▊       | 1719/6167 [29:05<44:58,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anthem.jpg

 28%|██▊       | 1720/6167 [29:05<43:46,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Theatre.jpg

 28%|██▊       | 1724/6167 [29:06<25:34,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/1970s.jpg

 28%|██▊       | 1726/6167 [29:07<28:37,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Television.jpg

 28%|██▊       | 1727/6167 [29:08<29:52,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sport.jpg

 28%|██▊       | 1729/6167 [29:09<33:42,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music.jpg

 28%|██▊       | 1730/6167 [29:09<31:04,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Literature.jpg

 28%|██▊       | 1732/6167 [29:09<23:45,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatian_language.jpg

 28%|██▊       | 1733/6167 [29:10<24:04,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wine.jpg

 28%|██▊       | 1734/6167 [29:10<23:40,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cuisine.jpg

 28%|██▊       | 1736/6167 [29:10<21:51,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cinema.jpg

 28%|██▊       | 1737/6167 [29:11<27:19,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Art.jpg

 28%|██▊       | 1738/6167 [29:12<30:16,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Architecture.jpg

 28%|██▊       | 1739/6167 [29:12<35:39,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Women.jpg

 28%|██▊       | 1740/6167 [29:13<33:18,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Religion.jpg

 28%|██▊       | 1741/6167 [29:14<57:10,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Languages.jpg

 28%|██▊       | 1742/6167 [29:15<54:27,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Healthcare.jpg

 28%|██▊       | 1743/6167 [29:16<52:55,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Genetics.jpg

 28%|██▊       | 1744/6167 [29:16<50:06,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Education.jpg

 28%|██▊       | 1745/6167 [29:17<49:43,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Demographics.jpg

 28%|██▊       | 1746/6167 [29:17<40:50,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croats.jpg

 28%|██▊       | 1747/6167 [29:18<43:36,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Transport.jpg

 28%|██▊       | 1748/6167 [29:18<45:38,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tourism.jpg

 28%|██▊       | 1750/6167 [29:19<33:33,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stock_Exchange.jpg

 28%|██▊       | 1752/6167 [29:19<24:59,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_euro.jpg

 28%|██▊       | 1753/6167 [29:20<24:42,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/National_Bank.jpg

 28%|██▊       | 1754/6167 [29:20<30:58,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/History_of_currency.jpg

 28%|██▊       | 1755/6167 [29:21<36:40,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Industry.jpg

 28%|██▊       | 1756/6167 [29:22<37:28,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Energy.jpg

 28%|██▊       | 1757/6167 [29:22<37:11,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Brands.jpg

 29%|██▊       | 1758/6167 [29:23<38:54,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Security_and_intelligence.jpg

 29%|██▊       | 1759/6167 [29:23<34:44,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Foreign_relations.jpg

 29%|██▊       | 1760/6167 [29:23<30:50,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elections.jpg

 29%|██▊       | 1761/6167 [29:24<27:01,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Speaker.jpg

 29%|██▊       | 1762/6167 [29:24<26:41,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Parliament.jpg

 29%|██▊       | 1763/6167 [29:25<42:39,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chief_of_the_General_Staff.jpg

 29%|██▊       | 1764/6167 [29:26<48:19,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/General_Staff.jpg

 29%|██▊       | 1765/6167 [29:27<49:08,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Military.jpg

 29%|██▊       | 1766/6167 [29:27<50:55,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Law_enforcement.jpg

 29%|██▊       | 1767/6167 [29:28<43:27,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/LGBTQ.jpg

 29%|██▊       | 1769/6167 [29:28<28:26,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Prime_Minister.jpg

 29%|██▊       | 1770/6167 [29:28<31:06,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Government.jpg

 29%|██▊       | 1771/6167 [29:29<28:02,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/President.jpg

 29%|██▊       | 1772/6167 [29:30<42:41,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Constitution.jpg

 29%|██▊       | 1773/6167 [29:30<43:51,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Administrative_divisions.jpg

 29%|██▉       | 1774/6167 [29:31<37:32,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Topography.jpg

 29%|██▉       | 1775/6167 [29:31<34:43,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Climate.jpg

 29%|██▉       | 1776/6167 [29:31<30:59,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/European_Union.jpg

 29%|██▉       | 1777/6167 [29:32<34:16,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/NATO.jpg

 29%|██▉       | 1778/6167 [29:32<29:20,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia_since_1995.jpg

 29%|██▉       | 1779/6167 [29:33<26:33,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/War_of_Independence.jpg

 29%|██▉       | 1780/6167 [29:33<25:25,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Independence.jpg

 29%|██▉       | 1781/6167 [29:33<28:34,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Socialist_Republic.jpg

 29%|██▉       | 1782/6167 [29:34<27:10,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/'Independent_State'.jpg

 29%|██▉       | 1783/6167 [29:34<26:18,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/World_War_II.jpg

 29%|██▉       | 1785/6167 [29:35<24:49,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Banovina.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kingdom_of_Yugoslavia.jpg

 29%|██▉       | 1786/6167 [29:35<24:18,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/World_War_I.jpg

 29%|██▉       | 1787/6167 [29:35<23:08,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Austrio-Hungarian_kingdom.jpg

 29%|██▉       | 1788/6167 [29:36<29:22,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Illyrian_Provinces.jpg

 29%|██▉       | 1789/6167 [29:36<26:52,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Habsburg_kingdom.jpg

 29%|██▉       | 1790/6167 [29:37<29:21,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Republic_of_Ragusa.jpg

 29%|██▉       | 1791/6167 [29:37<28:09,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Venetian_Dalmatia.jpg

 29%|██▉       | 1792/6167 [29:38<30:25,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Personal_union_with_Hungary.jpg

 29%|██▉       | 1794/6167 [29:38<21:57,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ban_of_Croatia.jpg

 29%|██▉       | 1795/6167 [29:38<21:06,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Medieval_kingdom.jpg

 29%|██▉       | 1796/6167 [29:39<28:08,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanalites.jpg

 29%|██▉       | 1797/6167 [29:40<39:16,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Travunia.jpg

 29%|██▉       | 1798/6167 [29:40<37:33,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zachlumia.jpg

 29%|██▉       | 1799/6167 [29:41<34:07,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Narentines.jpg

 29%|██▉       | 1800/6167 [29:41<41:07,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Red_Croatia.jpg

 29%|██▉       | 1801/6167 [29:42<43:54,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lower_Pannonia.jpg

 29%|██▉       | 1802/6167 [29:43<46:22,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dalmatian_city-states.jpg

 29%|██▉       | 1803/6167 [29:43<44:27,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Medieval_duchy.jpg

 29%|██▉       | 1804/6167 [29:44<43:14,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/White_Croatia.jpg

 29%|██▉       | 1805/6167 [29:44<36:45,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/White_Croats.jpg

 29%|██▉       | 1806/6167 [29:44<31:16,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Origins_of_Croats.jpg

 29%|██▉       | 1807/6167 [29:45<42:40,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Prehistoric.jpg

 29%|██▉       | 1808/6167 [29:46<44:29,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Šašić.jpg

 29%|██▉       | 1809/6167 [29:46<38:17,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Samardžić.jpg

 29%|██▉       | 1810/6167 [29:47<34:04,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Joksimović.jpg

 29%|██▉       | 1811/6167 [29:47<31:05,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Bebek.jpg

 29%|██▉       | 1813/6167 [29:47<22:31,  3.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šemsa_Suljaković.jpg

 29%|██▉       | 1815/6167 [29:48<22:17,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šaban_Šaulić.jpg

 29%|██▉       | 1818/6167 [29:49<18:45,  3.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zoran_Lesendrić.jpg

 29%|██▉       | 1819/6167 [29:49<27:12,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zdravko_Čolić.jpg

 30%|██▉       | 1820/6167 [29:51<37:47,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaim_Imamović.jpg

 30%|██▉       | 1821/6167 [29:52<47:39,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yiannis_Parios.jpg

 30%|██▉       | 1822/6167 [29:52<45:53,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlado_Georgiev.jpg

 30%|██▉       | 1823/6167 [29:53<47:20,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viki.jpg

 30%|██▉       | 1824/6167 [29:55<1:11:02,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesna_Zmijanac.jpg

 30%|██▉       | 1826/6167 [29:55<47:54,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vasilis_Karras.jpg

 30%|██▉       | 1827/6167 [29:56<41:01,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toše_Proeski.jpg

 30%|██▉       | 1828/6167 [29:57<53:57,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tonči_Huljić.jpg

 30%|██▉       | 1829/6167 [29:57<49:26,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Cetinski.jpg

 30%|██▉       | 1830/6167 [29:58<40:09,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toma_Zdravković.jpg

 30%|██▉       | 1831/6167 [29:58<38:52,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tifa.jpg

 30%|██▉       | 1832/6167 [29:59<45:53,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tijana_Dapčević.jpg

 30%|██▉       | 1833/6167 [30:00<46:29,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tereza_Kesovija.jpg

 30%|██▉       | 1834/6167 [30:00<51:26,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Savić.jpg

 30%|██▉       | 1835/6167 [30:01<48:06,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Ribič.jpg

 30%|██▉       | 1836/6167 [30:01<40:04,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Todevska.jpg

 30%|██▉       | 1838/6167 [30:02<31:00,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stoja.jpg

 30%|██▉       | 1839/6167 [30:02<30:31,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofi_Marinova.jpg

 30%|██▉       | 1840/6167 [30:03<39:00,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Snežana_Đurišić.jpg

 30%|██▉       | 1841/6167 [30:04<34:51,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slađana_Milošević.jpg

 30%|██▉       | 1843/6167 [30:04<31:27,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvana_Armenulić.jpg

 30%|██▉       | 1844/6167 [30:05<29:09,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina.jpg

 30%|██▉       | 1845/6167 [30:05<31:26,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sertab_Erener.jpg

 30%|██▉       | 1846/6167 [30:06<30:58,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergej_Ćetković.jpg

 30%|██▉       | 1847/6167 [30:06<35:57,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serdar_Ortaç.jpg

 30%|██▉       | 1848/6167 [30:07<38:19,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Bajrami.jpg

 30%|██▉       | 1849/6167 [30:07<36:32,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seka_Aleksić.jpg

 30%|██▉       | 1850/6167 [30:08<36:01,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sejo_Sexon.jpg

 30%|███       | 1851/6167 [30:08<35:38,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sead_Lipovača.jpg

 30%|███       | 1852/6167 [30:09<35:23,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Matić.jpg

 30%|███       | 1853/6167 [30:11<1:05:48,  1.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Lošić.jpg

 30%|███       | 1854/6167 [30:12<1:05:17,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Kovačević.jpg

 30%|███       | 1855/6167 [30:12<1:00:44,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Jo.jpg

 30%|███       | 1856/6167 [30:13<53:47,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Vučić.jpg

 30%|███       | 1857/6167 [30:13<45:51,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakis_Rouvas.jpg

 30%|███       | 1858/6167 [30:14<1:01:21,  1.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Safet_Isović.jpg

 30%|███       | 1859/6167 [30:15<55:41,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Ora.jpg

 30%|███       | 1860/6167 [30:16<1:09:23,  1.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rayna.jpg

 30%|███       | 1862/6167 [30:17<46:39,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rambo_Amadeus.jpg

 30%|███       | 1863/6167 [30:18<45:48,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preslava.jpg

 30%|███       | 1864/6167 [30:18<45:14,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Živković_Tozovac.jpg

 30%|███       | 1865/6167 [30:19<42:39,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Gojković-Cune.jpg

 30%|███       | 1866/6167 [30:20<47:06,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Poli_Genova.jpg

 30%|███       | 1867/6167 [30:20<45:10,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paola.jpg

 30%|███       | 1869/6167 [30:21<39:14,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Dragojević.jpg

 30%|███       | 1870/6167 [30:22<40:48,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nora_Istrefi.jpg

 30%|███       | 1871/6167 [30:22<43:58,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noizy.jpg

 30%|███       | 1873/6167 [30:23<31:11,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Badrić.jpg

 30%|███       | 1874/6167 [30:23<32:16,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikos_Vertis.jpg

 30%|███       | 1876/6167 [30:24<31:20,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikola_Rokvić.jpg

 30%|███       | 1877/6167 [30:25<39:17,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nexhmije_Pagarusha.jpg

 30%|███       | 1878/6167 [30:26<40:38,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nevena_Božović.jpg

 30%|███       | 1879/6167 [30:26<44:53,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neno_Belan.jpg

 30%|███       | 1880/6167 [30:27<42:46,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nele_Karajlić.jpg

 31%|███       | 1882/6167 [30:27<30:23,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neda_Ukraden.jpg

 31%|███       | 1883/6167 [30:28<27:57,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nataša_Bekvalac.jpg

 31%|███       | 1884/6167 [30:28<32:33,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natasa_Theodoridou.jpg

 31%|███       | 1885/6167 [30:29<39:08,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Topčagić.jpg

 31%|███       | 1886/6167 [30:30<40:00,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Mamula.jpg

 31%|███       | 1890/6167 [30:30<21:09,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miša_Aleksić.jpg

 31%|███       | 1892/6167 [30:31<26:25,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Ilić.jpg

 31%|███       | 1895/6167 [30:32<19:20,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mile_Kitić.jpg

 31%|███       | 1896/6167 [30:32<24:40,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milan_Stanković.jpg

 31%|███       | 1898/6167 [30:34<28:59,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Merima_Njegomir.jpg

 31%|███       | 1900/6167 [30:34<25:31,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Berović.jpg

 31%|███       | 1901/6167 [30:35<30:52,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Šuput.jpg

 31%|███       | 1902/6167 [30:35<32:35,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Massimo_Savić.jpg

 31%|███       | 1903/6167 [30:37<45:52,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marta_Savić.jpg

 31%|███       | 1904/6167 [30:37<43:28,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Kon.jpg

 31%|███       | 1905/6167 [30:38<44:35,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marinella.jpg

 31%|███       | 1906/6167 [30:38<37:29,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marija_Šerifović.jpg

 31%|███       | 1907/6167 [30:39<39:59,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Elena_Kyriakou.jpg

 31%|███       | 1908/6167 [30:39<42:28,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malina.jpg

 31%|███       | 1910/6167 [30:40<32:22,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Magnifico.jpg

 31%|███       | 1911/6167 [30:41<34:48,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luke_Black.jpg

 31%|███       | 1913/6167 [30:41<30:58,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Lukić.jpg

 31%|███       | 1914/6167 [30:42<31:07,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Brena.jpg

 31%|███       | 1915/6167 [30:42<31:00,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lefteris_Pantazis.jpg

 31%|███       | 1916/6167 [30:43<34:03,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kornelije_Kovač.jpg

 31%|███       | 1918/6167 [30:43<29:36,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Konstrakta.jpg

 31%|███       | 1919/6167 [30:44<27:47,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Knez.jpg

 31%|███       | 1921/6167 [30:44<26:02,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kićo_Slabinac.jpg

 31%|███       | 1922/6167 [30:45<25:07,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenan_Doğulu.jpg

 31%|███       | 1923/6167 [30:45<30:52,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Monteno.jpg

 31%|███       | 1924/6167 [30:46<28:59,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katy_Garbi.jpg

 31%|███       | 1925/6167 [30:46<30:00,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karolina_Gočeva.jpg

 31%|███       | 1926/6167 [30:46<26:32,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamelia.jpg

 31%|███       | 1927/6167 [30:47<34:36,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalomira.jpg

 31%|███▏      | 1928/6167 [30:48<38:58,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaliopi.jpg

 31%|███▏      | 1929/6167 [30:49<40:21,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurica_Pađen.jpg

 31%|███▏      | 1931/6167 [30:49<36:51,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josipa_Lisac.jpg

 31%|███▏      | 1932/6167 [30:50<38:00,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Tomašević.jpg

 31%|███▏      | 1933/6167 [30:51<47:06,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Rozga.jpg

 31%|███▏      | 1934/6167 [30:52<47:15,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Karleuša.jpg

 31%|███▏      | 1936/6167 [30:52<34:50,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Houdek.jpg

 31%|███▏      | 1937/6167 [30:53<31:22,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Pogorelić.jpg

 31%|███▏      | 1938/6167 [30:53<33:21,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivi_Adamou.jpg

 31%|███▏      | 1940/6167 [30:55<47:44,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Zajc.jpg

 31%|███▏      | 1941/6167 [30:56<45:59,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inva_Mula.jpg

 31%|███▏      | 1942/6167 [30:56<40:15,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inna.jpg

 32%|███▏      | 1943/6167 [30:57<39:31,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Radić.jpg

 32%|███▏      | 1944/6167 [30:57<37:19,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Levak.jpg

 32%|███▏      | 1945/6167 [30:58<40:37,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilira.jpg

 32%|███▏      | 1946/6167 [30:58<38:44,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hurricane.jpg

 32%|███▏      | 1947/6167 [30:59<44:50,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Himzo_Polovina.jpg

 32%|███▏      | 1948/6167 [30:59<39:04,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helena_Paparizou.jpg

 32%|███▏      | 1949/6167 [31:00<37:39,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hasiba_Agić.jpg

 32%|███▏      | 1950/6167 [31:00<36:54,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Džinović.jpg

 32%|███▏      | 1951/6167 [31:01<32:06,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hari_Varešanović.jpg

 32%|███▏      | 1952/6167 [31:01<39:41,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halid_Bešlić.jpg

 32%|███▏      | 1953/6167 [31:02<34:26,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hadise.jpg

 32%|███▏      | 1954/6167 [31:02<36:05,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gru.jpg

 32%|███▏      | 1955/6167 [31:03<31:10,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Bregović.jpg

 32%|███▏      | 1956/6167 [31:03<34:07,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goca_Tržan.jpg

 32%|███▏      | 1957/6167 [31:04<37:48,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria.jpg

 32%|███▏      | 1958/6167 [31:04<39:32,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gibonni.jpg

 32%|███▏      | 1959/6167 [31:05<44:47,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gergana.jpg

 32%|███▏      | 1960/6167 [31:06<44:44,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Dalaras.jpg

 32%|███▏      | 1962/6167 [31:07<35:53,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Galena.jpg

 32%|███▏      | 1965/6167 [31:07<26:43,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fiki.jpg

 32%|███▏      | 1966/6167 [31:08<26:19,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esma_Redžepova.jpg

 32%|███▏      | 1967/6167 [31:08<25:39,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Era_Istrefi.jpg

 32%|███▏      | 1968/6167 [31:09<27:18,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emina_Jahović.jpg

 32%|███▏      | 1969/6167 [31:09<33:56,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emanuela.jpg

 32%|███▏      | 1970/6167 [31:10<37:42,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvir_Laković_Laka.jpg

 32%|███▏      | 1971/6167 [31:10<34:05,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvana_Gjata.jpg

 32%|███▏      | 1972/6167 [31:11<34:32,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elhaida_Dani.jpg

 32%|███▏      | 1973/6167 [31:11<31:10,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleni_Foureira.jpg

 32%|███▏      | 1974/6167 [31:12<33:04,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Risteska.jpg

 32%|███▏      | 1975/6167 [31:12<33:47,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleftheria_Eleftheriou.jpg

 32%|███▏      | 1976/6167 [31:13<34:34,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Maajka.jpg

 32%|███▏      | 1977/6167 [31:13<36:20,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Džej_Ramadanovski.jpg

 32%|███▏      | 1978/6167 [31:14<37:56,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Đorđe_Balašević.jpg

 32%|███▏      | 1980/6167 [31:14<25:39,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dua_Lipa.jpg

 32%|███▏      | 1981/6167 [31:15<23:37,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragana_Mirković.jpg

 32%|███▏      | 1982/6167 [31:16<50:21,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragan_Kojić_Keba.jpg

 32%|███▏      | 1984/6167 [31:17<38:17,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doris_Dragović.jpg

 32%|███▏      | 1985/6167 [31:17<34:14,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Merlin.jpg

 32%|███▏      | 1986/6167 [31:18<38:44,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Dvornik.jpg

 32%|███▏      | 1987/6167 [31:18<35:25,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Despina_Vandi.jpg

 32%|███▏      | 1989/6167 [31:19<27:25,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deen.jpg

 32%|███▏      | 1990/6167 [31:20<33:18,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davorin_Popović.jpg

 32%|███▏      | 1991/6167 [31:21<51:35,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darko_Rundek.jpg

 32%|███▏      | 1993/6167 [31:22<39:03,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danijela_Martinović.jpg

 32%|███▏      | 1995/6167 [31:22<31:38,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dafina_Zeqiri.jpg

 32%|███▏      | 1996/6167 [31:23<32:36,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dado_Topić.jpg

 32%|███▏      | 1999/6167 [31:23<22:29,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coby.jpg

 32%|███▏      | 2000/6167 [31:26<48:06,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ceca.jpg

 32%|███▏      | 2001/6167 [31:26<48:46,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Capital_T.jpg

 32%|███▏      | 2004/6167 [31:27<32:03,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Novković.jpg

 33%|███▎      | 2006/6167 [31:27<25:25,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bora_Đorđević.jpg

 33%|███▎      | 2007/6167 [31:28<29:20,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boban_Rajović.jpg

 33%|███▎      | 2008/6167 [31:29<36:29,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bleona.jpg

 33%|███▎      | 2009/6167 [31:29<32:59,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebi_Dol.jpg

 33%|███▎      | 2010/6167 [31:30<29:46,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebe_Rexha.jpg

 33%|███▎      | 2011/6167 [31:30<32:11,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beba_Selimović.jpg

 33%|███▎      | 2012/6167 [31:30<29:17,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bajaga.jpg

 33%|███▎      | 2013/6167 [31:31<28:44,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azis.jpg

 33%|███▎      | 2014/6167 [31:31<28:34,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Avni_Mula.jpg

 33%|███▎      | 2015/6167 [31:32<33:24,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurela_Gaçe.jpg

 33%|███▎      | 2016/6167 [31:33<46:07,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arsen_Dedić.jpg

 33%|███▎      | 2017/6167 [31:34<51:49,  1.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ardian_Bujupi.jpg

 33%|███▎      | 2020/6167 [31:35<31:30,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Vissi.jpg

 33%|███▎      | 2021/6167 [31:35<36:45,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Odobescu.jpg

 33%|███▎      | 2022/6167 [31:36<37:16,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea.jpg

 33%|███▎      | 2023/6167 [31:36<37:15,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bănică.jpg

 33%|███▎      | 2025/6167 [31:37<32:13,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Kokić.jpg

 33%|███▎      | 2028/6167 [31:38<22:16,  3.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Stan.jpg

 33%|███▎      | 2029/6167 [31:38<22:48,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleksandra_Prijović.jpg

 33%|███▎      | 2030/6167 [31:38<23:03,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Islamović.jpg

 33%|███▎      | 2031/6167 [31:39<27:49,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alban_Skënderaj.jpg

 33%|███▎      | 2033/6167 [31:40<28:16,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Rahimovski.jpg

 33%|███▎      | 2035/6167 [31:41<25:41,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Sînă.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aco_Pejović.jpg

 33%|███▎      | 2036/6167 [31:41<29:40,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aca_Lukas.jpg

 33%|███▎      | 2037/6167 [31:42<32:05,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 33%|███▎      | 2039/6167 [31:43<38:47,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 33%|███▎      | 2040/6167 [31:44<39:32,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 33%|███▎      | 2041/6167 [31:45<43:30,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 33%|███▎      | 2042/6167 [31:45<36:59,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zeybek.jpg

 33%|███▎      | 2044/6167 [31:45<27:48,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oro_(eagle_dance).jpg

 33%|███▎      | 2045/6167 [31:45<24:32,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karsilamas.jpg

 33%|███▎      | 2046/6167 [31:46<28:52,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Čoček.jpg

 33%|███▎      | 2049/6167 [31:47<22:34,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsamiko.jpg

 33%|███▎      | 2050/6167 [31:48<29:03,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamzara.jpg

 33%|███▎      | 2051/6167 [31:48<31:04,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sousta.jpg

 33%|███▎      | 2052/6167 [31:48<28:18,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sirtaki.jpg

 33%|███▎      | 2053/6167 [31:49<36:46,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syrtos.jpg

 33%|███▎      | 2055/6167 [31:50<25:05,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kolo.jpg

 33%|███▎      | 2056/6167 [31:50<24:51,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kochari.jpg

 33%|███▎      | 2057/6167 [31:51<28:01,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khigga.jpg

 33%|███▎      | 2060/6167 [31:51<21:07,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hora.jpg

 34%|███▎      | 2066/6167 [31:52<12:07,  5.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 34%|███▎      | 2067/6167 [31:52<15:03,  4.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenia.jpg

 34%|███▎      | 2068/6167 [31:53<16:22,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serbia.jpg

 34%|███▎      | 2069/6167 [31:53<20:07,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romania.jpg

 34%|███▎      | 2070/6167 [31:54<28:46,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/North_Macedonia.jpg

 34%|███▎      | 2071/6167 [31:55<30:38,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegro.jpg

 34%|███▎      | 2072/6167 [31:55<35:02,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moldova.jpg

 34%|███▎      | 2074/6167 [31:56<28:56,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 34%|███▎      | 2075/6167 [31:56<28:12,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 34%|███▎      | 2076/6167 [31:57<29:20,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cyprus.jpg

 34%|███▎      | 2077/6167 [31:57<27:40,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 34%|███▎      | 2078/6167 [31:57<24:59,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 34%|███▎      | 2079/6167 [31:58<25:02,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnia_and_Herzegovina.jpg

 34%|███▎      | 2081/6167 [31:59<39:51,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 34%|███▍      | 2082/6167 [32:00<40:54,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albania.jpg

 34%|███▍      | 2083/6167 [32:01<37:46,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yugoslav_pop.jpg

 34%|███▍      | 2086/6167 [32:01<28:05,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ganga_music.jpg

 34%|███▍      | 2088/6167 [32:02<25:48,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_brass.jpg

 34%|███▍      | 2092/6167 [32:02<16:51,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani_music.jpg

 34%|███▍      | 2093/6167 [32:03<18:15,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rebetiko.jpg

 34%|███▍      | 2094/6167 [32:04<34:46,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nisiotika.jpg

 34%|███▍      | 2095/6167 [32:05<38:04,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turbo-folk.jpg

 34%|███▍      | 2097/6167 [32:06<32:19,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manele.jpg

 34%|███▍      | 2098/6167 [32:06<33:53,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laïko.jpg

 34%|███▍      | 2100/6167 [32:07<27:30,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk-pop.jpg

 34%|███▍      | 2101/6167 [32:07<25:43,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkish.jpg

 34%|███▍      | 2102/6167 [32:08<24:20,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenian.jpg

 34%|███▍      | 2104/6167 [32:08<17:53,  3.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romanian.jpg

 34%|███▍      | 2105/6167 [32:08<18:43,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani.jpg

 34%|███▍      | 2106/6167 [32:08<17:44,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegrin.jpg

 34%|███▍      | 2107/6167 [32:09<17:18,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Macedonian.jpg

 34%|███▍      | 2108/6167 [32:09<18:45,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greek.jpg

 34%|███▍      | 2109/6167 [32:09<19:08,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatian.jpg

 34%|███▍      | 2110/6167 [32:11<39:28,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgarian.jpg

 34%|███▍      | 2111/6167 [32:11<33:10,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnian.jpg

 34%|███▍      | 2112/6167 [32:11<28:58,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albanian.jpg

 34%|███▍      | 2113/6167 [32:11<27:31,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk.jpg

 34%|███▍      | 2120/6167 [32:12<12:24,  5.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davor_Zovko.jpg

 34%|███▍      | 2123/6167 [32:13<12:00,  5.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vice_Vukov.jpg

 34%|███▍      | 2125/6167 [32:13<14:25,  4.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina_Vučković.jpg

 34%|███▍      | 2126/6167 [32:14<16:24,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Siniša_Vuco.jpg

 35%|███▍      | 2129/6167 [32:14<14:03,  4.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Vitasović.jpg

 35%|███▍      | 2130/6167 [32:15<19:29,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eric_Vidović.jpg

 35%|███▍      | 2132/6167 [32:16<19:31,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vanna.jpg

 35%|███▍      | 2133/6167 [32:16<24:08,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Damir_Urban.jpg

 35%|███▍      | 2134/6167 [32:17<24:29,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neda_Ukraden.jpg

 35%|███▍      | 2136/6167 [32:17<18:35,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dado_Topić.jpg

 35%|███▍      | 2139/6167 [32:17<13:40,  4.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Tolja.jpg

 35%|███▍      | 2140/6167 [32:18<18:22,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tajči.jpg

 35%|███▍      | 2141/6167 [32:19<27:08,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Radojka_Šverko.jpg

 35%|███▍      | 2142/6167 [32:19<31:59,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea_Šušnjara.jpg

 35%|███▍      | 2143/6167 [32:20<29:46,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Šuput.jpg

 35%|███▍      | 2144/6167 [32:21<37:01,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Štok.jpg

 35%|███▍      | 2145/6167 [32:22<58:59,  1.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antonija_Šola.jpg

 35%|███▍      | 2146/6167 [32:23<54:20,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lana_Škrgatić.jpg

 35%|███▍      | 2147/6167 [32:24<48:43,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Škoro.jpg

 35%|███▍      | 2152/6167 [32:24<21:57,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kićo_Slabinac.jpg

 35%|███▍      | 2153/6167 [32:25<21:20,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina.jpg

 35%|███▍      | 2155/6167 [32:25<18:50,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Massimo_Savić.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Renata_Sabljak.jpg

 35%|███▍      | 2156/6167 [32:26<29:48,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Rozga.jpg

 35%|███▌      | 2160/6167 [32:27<18:09,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Robić.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivana_Radovniković.jpg

 35%|███▌      | 2166/6167 [32:27<12:23,  5.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Perković.jpg

 35%|███▌      | 2168/6167 [32:28<14:45,  4.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marina_Perazić.jpg

 35%|███▌      | 2169/6167 [32:29<17:35,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zlatko_Pejaković.jpg

 35%|███▌      | 2170/6167 [32:29<20:11,  3.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurica_Pađen.jpg

 35%|███▌      | 2171/6167 [32:30<25:28,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Obrovac.jpg

 35%|███▌      | 2173/6167 [32:31<23:51,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Novković.jpg

 35%|███▌      | 2175/6167 [32:31<21:49,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gabi_Novak.jpg

 35%|███▌      | 2177/6167 [32:32<23:07,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ljiljana_Nikolovska.jpg

 35%|███▌      | 2179/6167 [32:32<21:47,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Navojec.jpg

 35%|███▌      | 2184/6167 [32:33<14:28,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Igor_Milić.jpg

 35%|███▌      | 2186/6167 [32:35<24:39,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandra_Mihanovich.jpg

 35%|███▌      | 2188/6167 [32:35<22:52,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amira_Medunjanin.jpg

 35%|███▌      | 2189/6167 [32:36<24:36,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanya_Mateyas.jpg

 36%|███▌      | 2190/6167 [32:36<22:59,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danijela_Martinović.jpg

 36%|███▌      | 2191/6167 [32:37<27:58,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandy_Marton.jpg

 36%|███▌      | 2194/6167 [32:37<19:35,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martina_Majerle.jpg

 36%|███▌      | 2196/6167 [32:37<16:07,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lorde.jpg

 36%|███▌      | 2197/6167 [32:38<19:54,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Radoslav_Lorković.jpg

 36%|███▌      | 2198/6167 [32:38<19:08,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josipa_Lisac.jpg

 36%|███▌      | 2199/6167 [32:39<18:14,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Levak.jpg

 36%|███▌      | 2200/6167 [32:39<23:53,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frano_Lasić.jpg

 36%|███▌      | 2201/6167 [32:41<45:43,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/La_Lana.jpg

 36%|███▌      | 2202/6167 [32:41<42:19,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Kutlić.jpg

 36%|███▌      | 2203/6167 [32:42<50:07,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karin_Kuljanić.jpg

 36%|███▌      | 2205/6167 [32:43<35:31,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Kraljić.jpg

 36%|███▌      | 2206/6167 [32:43<35:19,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zdenka_Kovačiček.jpg

 36%|███▌      | 2209/6167 [32:44<25:58,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zorica_Kondža.jpg

 36%|███▌      | 2210/6167 [32:46<44:43,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adam_Končić.jpg

 36%|███▌      | 2211/6167 [32:46<39:13,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emilija_Kokić.jpg

 36%|███▌      | 2213/6167 [32:47<28:05,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daria_Kinzer.jpg

 36%|███▌      | 2215/6167 [32:48<28:31,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Karan.jpg

 36%|███▌      | 2216/6167 [32:48<34:55,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ibrica_Jusić.jpg

 36%|███▌      | 2217/6167 [32:49<31:38,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eni_Jurišić.jpg

 36%|███▌      | 2219/6167 [32:49<25:36,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Jelusick.jpg

 36%|███▌      | 2223/6167 [32:49<14:25,  4.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Houdek.jpg

 36%|███▌      | 2225/6167 [32:50<16:48,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bobby_Grubic.jpg

 36%|███▌      | 2226/6167 [32:51<20:59,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Grše.jpg

 36%|███▌      | 2232/6167 [32:51<10:06,  6.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davor_Gobac.jpg

 36%|███▌      | 2234/6167 [32:51<09:53,  6.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zlatan_Stipišić_Gibonni.jpg

 36%|███▋      | 2236/6167 [32:52<10:00,  6.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Dvornik.jpg

 36%|███▋      | 2238/6167 [32:52<12:04,  5.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davor_Dretar.jpg

 36%|███▋      | 2239/6167 [32:53<13:13,  4.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doris_Dragović.jpg

 36%|███▋      | 2240/6167 [32:53<14:37,  4.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Dragojević.jpg

 36%|███▋      | 2242/6167 [32:53<13:44,  4.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Doležal.jpg

 36%|███▋      | 2245/6167 [32:55<24:07,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mia_Dimšić.jpg

 36%|███▋      | 2247/6167 [32:56<22:20,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arsen_Dedić.jpg

 36%|███▋      | 2250/6167 [32:56<18:31,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zrinka_Cvitešić.jpg

 37%|███▋      | 2252/6167 [32:57<18:14,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Igor_Cukrov.jpg

 37%|███▋      | 2253/6167 [32:57<20:31,  3.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Branko_Črnac_Tusta.jpg

 37%|███▋      | 2255/6167 [32:58<22:11,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Cetinski.jpg

 37%|███▋      | 2258/6167 [32:58<17:44,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Max_Emanuel_Cenčić.jpg

 37%|███▋      | 2260/6167 [32:59<19:31,  3.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joško_Čagalj_Jole.jpg

 37%|███▋      | 2261/6167 [33:00<23:55,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mate_Bulić.jpg

 37%|███▋      | 2265/6167 [33:00<14:10,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michael_Bublé.jpg

 37%|███▋      | 2269/6167 [33:01<13:11,  4.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Van_Bod.jpg

 37%|███▋      | 2270/6167 [33:02<18:49,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roko_Blažević.jpg

 37%|███▋      | 2271/6167 [33:02<22:46,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Claudia_Beni.jpg

 37%|███▋      | 2272/6167 [33:03<22:36,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neno_Belan.jpg

 37%|███▋      | 2273/6167 [33:04<28:16,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Bebić.jpg

 37%|███▋      | 2274/6167 [33:04<25:52,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Bebek.jpg

 37%|███▋      | 2275/6167 [33:04<27:22,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Franka_Batelić.jpg

 37%|███▋      | 2276/6167 [33:05<29:28,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lidija_Bajuk.jpg

 37%|███▋      | 2278/6167 [33:05<20:46,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Badrić.jpg

 37%|███▋      | 2279/6167 [33:06<23:26,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lidija_Bačić.jpg

 37%|███▋      | 2281/6167 [33:06<24:43,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Antić.jpg

 37%|███▋      | 2282/6167 [33:07<26:57,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Baby_Lasagna.jpg

 37%|███▋      | 2285/6167 [33:09<32:05,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Werrason.jpg

 37%|███▋      | 2286/6167 [33:09<31:45,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Papa_Wemba.jpg

 37%|███▋      | 2287/6167 [33:09<28:31,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alicios_Theluji.jpg

 37%|███▋      | 2288/6167 [33:10<34:05,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tabu_Ley_Rochereau.jpg

 37%|███▋      | 2291/6167 [33:11<22:32,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Koffi_Olomide.jpg

 37%|███▋      | 2292/6167 [33:11<24:09,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nyboma_Mwan'dido_(Nyboma).jpg

 37%|███▋      | 2293/6167 [33:12<28:12,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dena_Mwana.jpg

 37%|███▋      | 2294/6167 [33:13<33:11,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tshala_Muana.jpg

 37%|███▋      | 2296/6167 [33:14<35:35,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohombi.jpg

 37%|███▋      | 2297/6167 [33:14<34:34,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moise_Mbiye.jpg

 37%|███▋      | 2298/6167 [33:15<33:42,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jessy_Matador.jpg

 37%|███▋      | 2304/6167 [33:15<12:49,  5.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Abeti_Masikini.jpg

 37%|███▋      | 2305/6167 [33:15<13:47,  4.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nathalie_Makoma.jpg

 37%|███▋      | 2308/6167 [33:16<13:24,  4.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vicky_Longomba.jpg

 37%|███▋      | 2309/6167 [33:16<14:10,  4.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/N'Yoka_Longo.jpg

 37%|███▋      | 2310/6167 [33:17<16:42,  3.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Awilo_Longomba.jpg

 37%|███▋      | 2312/6167 [33:17<16:33,  3.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wendo_Kolosoy.jpg

 38%|███▊      | 2314/6167 [33:18<17:16,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaysha.jpg

 38%|███▊      | 2315/6167 [33:20<36:29,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lokua_Kanza.jpg

 38%|███▊      | 2318/6167 [33:20<24:39,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucie_Eyenga.jpg

 38%|███▊      | 2319/6167 [33:23<48:27,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cindy_Le_Coeur.jpg

 38%|███▊      | 2322/6167 [33:23<33:39,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Céline_Banza.jpg

 38%|███▊      | 2324/6167 [33:24<27:07,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cor_Akim.jpg

 38%|███▊      | 2327/6167 [33:24<20:31,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coat_of_arms.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Flag.jpg

 38%|███▊      | 2328/6167 [33:25<23:59,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cinema.jpg

 38%|███▊      | 2330/6167 [33:26<26:37,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Radio.jpg

 38%|███▊      | 2331/6167 [33:26<28:01,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anneke_van_Giersbergen.jpg

 38%|███▊      | 2332/6167 [33:27<30:17,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anneliese_van_der_Pol.jpg

 38%|███▊      | 2334/6167 [33:28<30:38,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Annie_Palmen.jpg

 38%|███▊      | 2335/6167 [33:28<27:23,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anny_Schilder.jpg

 38%|███▊      | 2336/6167 [33:29<35:42,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anouchka_van_Miltenburg.jpg

 38%|███▊      | 2337/6167 [33:30<35:55,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anouk.jpg

 38%|███▊      | 2338/6167 [33:30<35:22,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anton_Sistermans.jpg

 38%|███▊      | 2339/6167 [33:31<38:36,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anton_van_Rooy.jpg

 38%|███▊      | 2340/6167 [33:31<33:10,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antonie_Kamerling.jpg

 38%|███▊      | 2341/6167 [33:31<28:33,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arjen_Anthony_Lucassen.jpg

 38%|███▊      | 2342/6167 [33:32<33:18,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Armand.jpg

 38%|███▊      | 2345/6167 [33:33<20:10,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Barry_Hay.jpg

 38%|███▊      | 2348/6167 [33:33<15:45,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bastiaan_Ragas.jpg

 38%|███▊      | 2349/6167 [33:34<26:13,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bearforce_1.jpg

 38%|███▊      | 2351/6167 [33:35<24:10,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ben_Cramer.jpg

 38%|███▊      | 2352/6167 [33:35<25:33,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ben_Saunders.jpg

 38%|███▊      | 2353/6167 [33:36<33:46,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benny_Neyman.jpg

 38%|███▊      | 2354/6167 [33:37<35:14,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bernadette.jpg

 38%|███▊      | 2356/6167 [33:38<28:25,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bertha_Frensel_Wegener.jpg

 38%|███▊      | 2357/6167 [33:38<32:40,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bertolf_Lentink.jpg

 38%|███▊      | 2358/6167 [33:39<34:03,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bill_van_Dijk.jpg

 38%|███▊      | 2359/6167 [33:40<39:15,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Birgit_Schuurman.jpg

 38%|███▊      | 2360/6167 [33:41<44:43,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Blaudzun.jpg

 38%|███▊      | 2361/6167 [33:42<54:35,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bojoura.jpg

 38%|███▊      | 2362/6167 [33:43<53:08,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bonnie_St._Claire.jpg

 38%|███▊      | 2363/6167 [33:43<46:30,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boudewijn_de_Groot.jpg

 38%|███▊      | 2364/6167 [33:44<41:31,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Titulaer.jpg

 38%|███▊      | 2365/6167 [33:45<43:49,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/CB_Milton.jpg

 38%|███▊      | 2366/6167 [33:45<42:25,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cab_Kaye.jpg

 38%|███▊      | 2367/6167 [33:46<36:21,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Candy_Dulfer.jpg

 38%|███▊      | 2368/6167 [33:46<34:33,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carice_van_Houten.jpg

 38%|███▊      | 2369/6167 [33:46<30:07,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sarah_Geronimo.jpg

 38%|███▊      | 2372/6167 [33:47<16:05,  3.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maricel_Soriano.jpg

 38%|███▊      | 2374/6167 [33:47<14:14,  4.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gian_Sotto.jpg

 39%|███▊      | 2375/6167 [33:47<15:25,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tito_Sotto.jpg

 39%|███▊      | 2377/6167 [33:48<13:46,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vic_Sotto.jpg

 39%|███▊      | 2378/6167 [33:48<14:49,  4.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/J._Rey_Soul.jpg

 39%|███▊      | 2379/6167 [33:50<37:35,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stacey.jpg

 39%|███▊      | 2380/6167 [33:50<34:55,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stell.jpg

 39%|███▊      | 2382/6167 [33:50<24:46,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Indonesia.jpg

 39%|███▊      | 2383/6167 [33:51<25:10,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Iran.jpg

 39%|███▊      | 2387/6167 [33:51<13:26,  4.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Malaysia.jpg

 39%|███▊      | 2388/6167 [33:52<15:18,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Mexico.jpg

 39%|███▊      | 2389/6167 [33:52<18:01,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yahir_Othon.jpg

 39%|███▉      | 2390/6167 [33:52<17:48,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vicente_Fernández.jpg

 39%|███▉      | 2391/6167 [33:53<23:20,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Valentin_Elizalde.jpg

 39%|███▉      | 2393/6167 [33:54<27:02,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tito_Guízar.jpg

 39%|███▉      | 2394/6167 [33:54<27:31,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergio_Vega.jpg

 39%|███▉      | 2395/6167 [33:55<32:09,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergio_Gómez.jpg

 39%|███▉      | 2396/6167 [33:56<32:48,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saul_Hernández.jpg

 39%|███▉      | 2397/6167 [33:56<36:36,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Samo.jpg

 39%|███▉      | 2398/6167 [33:58<50:24,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Salvador_Flores_Rivera.jpg

 39%|███▉      | 2399/6167 [33:58<41:51,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Tapia.jpg

 39%|███▉      | 2400/6167 [33:59<38:00,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Gomez_Bolaños.jpg

 39%|███▉      | 2401/6167 [33:59<35:47,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Cantoral.jpg

 39%|███▉      | 2403/6167 [34:00<28:28,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reyli.jpg

 39%|███▉      | 2405/6167 [34:00<22:53,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Regulo_Caro.jpg

 39%|███▉      | 2406/6167 [34:00<21:30,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ramón_Ayala.jpg

 39%|███▉      | 2408/6167 [34:01<18:40,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peso_Pluma.jpg

 39%|███▉      | 2409/6167 [34:01<20:53,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pedro_Fernández.jpg

 39%|███▉      | 2410/6167 [34:02<21:03,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pepe_Aguilar.jpg

 39%|███▉      | 2411/6167 [34:02<19:46,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pedro_Infante.jpg

 39%|███▉      | 2412/6167 [34:03<27:33,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pablo_Montero.jpg

 39%|███▉      | 2413/6167 [34:03<32:01,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Óscar_Chávez.jpg

 39%|███▉      | 2414/6167 [34:04<30:31,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miguel_Aceves_Mejía.jpg

 39%|███▉      | 2415/6167 [34:04<26:50,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marco_Antonio_Solís.jpg

 39%|███▉      | 2417/6167 [34:05<27:20,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lupillo_Rivera.jpg

 39%|███▉      | 2419/6167 [34:05<20:47,  3.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luis_Miguel.jpg

 39%|███▉      | 2420/6167 [34:06<23:01,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luis_Coronel.jpg

 39%|███▉      | 2422/6167 [34:07<26:27,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leonardo_Aguilar.jpg

 39%|███▉      | 2424/6167 [34:08<24:47,  2.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalimba.jpg

 39%|███▉      | 2426/6167 [34:08<24:00,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julión_Álvarez.jpg

 39%|███▉      | 2429/6167 [34:09<18:23,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juan_Gabriel.jpg

 39%|███▉      | 2430/6167 [34:09<21:18,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Manuel_Figueroa.jpg

 39%|███▉      | 2431/6167 [34:10<26:51,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Mojica.jpg

 39%|███▉      | 2432/6167 [34:11<32:38,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_José.jpg

 39%|███▉      | 2434/6167 [34:12<31:27,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Ángel_Espinoza.jpg

 39%|███▉      | 2435/6167 [34:13<32:42,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Alfredo_Jiménez.jpg

 40%|███▉      | 2436/6167 [34:13<33:45,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jorge_Negrete.jpg

 40%|███▉      | 2440/6167 [34:14<15:56,  3.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joan_Sebastian.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jean_Duverger.jpg

 40%|███▉      | 2441/6167 [34:14<20:02,  3.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Javier_Solís.jpg

 40%|███▉      | 2442/6167 [34:15<25:38,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaime_Camil.jpg

 40%|███▉      | 2445/6167 [34:16<22:20,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Germán_Valdés.jpg

 40%|███▉      | 2447/6167 [34:16<19:40,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gerardo_Ortíz.jpg

 40%|███▉      | 2448/6167 [34:17<22:38,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gualberto_Castro.jpg

 40%|███▉      | 2449/6167 [34:17<23:29,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Frankie_J.jpg

 40%|███▉      | 2450/6167 [34:18<31:35,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francisco_Gabilondo_Soler.jpg

 40%|███▉      | 2451/6167 [34:19<34:04,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fher_Olvera.jpg

 40%|███▉      | 2452/6167 [34:20<35:54,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_de_la_Mora.jpg

 40%|███▉      | 2453/6167 [34:21<42:20,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_Delgadillo.jpg

 40%|███▉      | 2454/6167 [34:21<44:10,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eulalio_González.jpg

 40%|███▉      | 2455/6167 [34:23<56:50,  1.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erik_Rubin.jpg

 40%|███▉      | 2456/6167 [34:23<49:38,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Espinoza_Paz.jpg

 40%|███▉      | 2457/6167 [34:25<1:07:35,  1.09s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enrique_Guzmán.jpg

 40%|███▉      | 2458/6167 [34:26<55:17,  1.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emmanuel.jpg

 40%|███▉      | 2459/6167 [34:27<58:03,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/El_Potro_de_Sinaloa.jpg

 40%|███▉      | 2460/6167 [34:27<52:12,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/El_Chapo_de_Sinaloa.jpg

 40%|████      | 2467/6167 [34:28<17:50,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cuco_Sánchez.jpg

 40%|████      | 2468/6167 [34:29<20:24,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christopher_Uckerman.jpg

 40%|████      | 2469/6167 [34:29<19:36,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christian_Nodal.jpg

 40%|████      | 2470/6167 [34:29<22:16,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chico_Che.jpg

 40%|████      | 2471/6167 [34:30<24:45,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chetes.jpg

 40%|████      | 2472/6167 [34:30<23:18,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chalino_Sánchez.jpg

 40%|████      | 2473/6167 [34:30<21:25,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cristian_Castro.jpg

 40%|████      | 2475/6167 [34:31<17:11,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/César_Costa.jpg

 40%|████      | 2476/6167 [34:31<20:16,  3.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cepillín.jpg

 40%|████      | 2477/6167 [34:32<20:06,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celso_Piña.jpg

 40%|████      | 2478/6167 [34:32<19:21,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_Santana.jpg

 40%|████      | 2479/6167 [34:33<32:49,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Caloncho.jpg

 40%|████      | 2480/6167 [34:34<36:09,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bobby_Larios.jpg

 40%|████      | 2482/6167 [34:34<27:44,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benny_Ibarra.jpg

 40%|████      | 2483/6167 [34:36<44:38,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benito_Castro.jpg

 40%|████      | 2484/6167 [34:37<42:18,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Baby_Bash.jpg

 40%|████      | 2485/6167 [34:37<35:50,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Armando_Manzanero.jpg

 40%|████      | 2487/6167 [34:38<30:33,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antonio_Aguilar.jpg

 40%|████      | 2489/6167 [34:38<27:00,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alfonso_Herrera.jpg

 40%|████      | 2490/6167 [34:39<29:51,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexander_Acha.jpg

 40%|████      | 2491/6167 [34:40<32:27,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Álex_Lora.jpg

 40%|████      | 2492/6167 [34:40<34:38,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arturo_Meza.jpg

 40%|████      | 2493/6167 [34:41<39:06,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ariel_Camacho.jpg

 40%|████      | 2494/6167 [34:41<33:46,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleks_Syntek.jpg

 40%|████      | 2496/6167 [34:42<25:08,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alejandro_Fernández.jpg

 41%|████      | 2499/6167 [34:42<17:09,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Agustín_Lara.jpg

 41%|████      | 2500/6167 [34:43<22:29,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuridia.jpg

 41%|████      | 2501/6167 [34:45<38:20,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuri.jpg

 41%|████      | 2504/6167 [34:46<37:13,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ximena_Sariñana.jpg

 41%|████      | 2505/6167 [34:47<38:53,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Oxor.jpg

 41%|████      | 2506/6167 [34:48<34:23,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selena.jpg

 41%|████      | 2507/6167 [34:48<33:44,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sasha_Sokol.jpg

 41%|████      | 2508/6167 [34:48<30:23,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Ramirez.jpg

 41%|████      | 2510/6167 [34:49<25:30,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Verónica_Castro.jpg

 41%|████      | 2511/6167 [34:49<23:20,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Thalía.jpg

 41%|████      | 2512/6167 [34:50<26:13,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tehua.jpg

 41%|████      | 2513/6167 [34:51<32:49,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tatiana.jpg

 41%|████      | 2514/6167 [34:51<27:48,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tania_Libertad.jpg

 41%|████      | 2515/6167 [34:51<27:28,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pilar_Montenegro.jpg

 41%|████      | 2516/6167 [34:52<34:08,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paty_Cantú.jpg

 41%|████      | 2517/6167 [34:52<29:54,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulina_Rubio.jpg

 41%|████      | 2519/6167 [34:53<20:12,  3.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Patricia_Manterola.jpg

 41%|████      | 2520/6167 [34:53<22:54,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paquita_la_del_Barrio.jpg

 41%|████      | 2521/6167 [34:54<24:30,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Niurka_Marcos.jpg

 41%|████      | 2522/6167 [34:55<32:46,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ninel_Conde.jpg

 41%|████      | 2523/6167 [34:55<32:13,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nati_Cano.jpg

 41%|████      | 2524/6167 [34:55<27:34,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natalia_Lafourcade.jpg

 41%|████      | 2525/6167 [34:56<30:38,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mon_Laferte.jpg

 41%|████      | 2527/6167 [34:57<30:05,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maribel_Guardia.jpg

 41%|████      | 2528/6167 [34:57<28:38,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariana_Seoane.jpg

 41%|████      | 2529/6167 [34:58<29:20,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariana_Levy.jpg

 41%|████      | 2530/6167 [34:59<37:33,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariana_Garza.jpg

 41%|████      | 2531/6167 [34:59<32:30,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/María_Victoria.jpg

 41%|████      | 2532/6167 [35:00<33:26,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/María_de_Lourdes.jpg

 41%|████      | 2533/6167 [35:00<32:51,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/María_José.jpg

 41%|████      | 2535/6167 [35:02<35:31,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marcela_Bovio.jpg

 41%|████      | 2536/6167 [35:02<36:17,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maite_Perroni.jpg

 41%|████      | 2537/6167 [35:05<1:03:17,  1.05s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lupita_D'Alessio.jpg

 41%|████      | 2538/6167 [35:05<54:53,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucha_Villa.jpg

 41%|████      | 2539/6167 [35:06<51:16,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lynda_Thomas.jpg

 41%|████      | 2540/6167 [35:07<48:05,  1.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucha_Reyes.jpg

 41%|████      | 2541/6167 [35:07<45:29,  1.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucía_Méndez.jpg

 41%|████      | 2542/6167 [35:08<44:41,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucero.jpg

 41%|████      | 2543/6167 [35:08<40:54,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lorena_Herrera.jpg

 41%|████▏     | 2544/6167 [35:10<51:18,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lola_Beltrán.jpg

 41%|████▏     | 2545/6167 [35:10<41:36,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Litzy.jpg

 41%|████▏     | 2547/6167 [35:10<29:22,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lila_Downs.jpg

 41%|████▏     | 2548/6167 [35:11<32:19,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lety_López.jpg

 41%|████▏     | 2549/6167 [35:12<38:00,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/La_Prieta_Linda.jpg

 41%|████▏     | 2550/6167 [35:13<40:17,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Zapata.jpg

 41%|████▏     | 2551/6167 [35:14<42:31,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kim_Loaiza.jpg

 41%|████▏     | 2552/6167 [35:16<1:10:52,  1.18s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenia_OS.jpg

 41%|████▏     | 2553/6167 [35:16<57:46,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karol_Sevilla.jpg

 41%|████▏     | 2554/6167 [35:17<47:15,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jenni_Rivera.jpg

 41%|████▏     | 2555/6167 [35:17<42:12,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julieta_Venegas.jpg

 41%|████▏     | 2556/6167 [35:18<40:41,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Itatí_Cantoral.jpg

 41%|████▏     | 2557/6167 [35:19<40:02,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irma_Serrano.jpg

 41%|████▏     | 2558/6167 [35:19<36:35,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irma_Dorantes.jpg

 41%|████▏     | 2559/6167 [35:20<36:04,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irán_Castillo.jpg

 42%|████▏     | 2560/6167 [35:20<33:59,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanna_Nicole.jpg

 42%|████▏     | 2561/6167 [35:21<33:37,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Guadalupe_Pineda.jpg

 42%|████▏     | 2563/6167 [35:21<27:12,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria_Trevi.jpg

 42%|████▏     | 2564/6167 [35:22<24:53,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Flor_Silvestre.jpg

 42%|████▏     | 2565/6167 [35:22<22:53,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fey.jpg

 42%|████▏     | 2566/6167 [35:22<26:34,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eugenia_León.jpg

 42%|████▏     | 2567/6167 [35:23<31:00,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ely_Guerra.jpg

 42%|████▏     | 2568/6167 [35:23<26:39,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eiza_González.jpg

 42%|████▏     | 2569/6167 [35:24<34:32,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edith_Márquez.jpg

 42%|████▏     | 2570/6167 [35:25<33:00,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dulce_María.jpg

 42%|████▏     | 2572/6167 [35:27<43:03,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Denisse_Guerrero.jpg

 42%|████▏     | 2573/6167 [35:27<41:52,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniela_Romo.jpg

 42%|████▏     | 2574/6167 [35:28<39:52,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniela_Luján.jpg

 42%|████▏     | 2575/6167 [35:28<33:07,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniela_Castro.jpg

 42%|████▏     | 2576/6167 [35:29<30:58,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danna_Paola.jpg

 42%|████▏     | 2578/6167 [35:29<27:31,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cynthia_Rodríguez.jpg

 42%|████▏     | 2579/6167 [35:30<27:24,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Consuelo_Velázquez.jpg

 42%|████▏     | 2580/6167 [35:30<29:37,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Concha_Michel.jpg

 42%|████▏     | 2581/6167 [35:31<29:31,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiquis_Rivera.jpg

 42%|████▏     | 2582/6167 [35:31<30:29,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chayito_Valdez.jpg

 42%|████▏     | 2583/6167 [35:32<26:49,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chavela_Vargas.jpg

 42%|████▏     | 2584/6167 [35:32<24:39,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celia_Cruz.jpg

 42%|████▏     | 2585/6167 [35:32<22:08,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carla_Morrison.jpg

 42%|████▏     | 2586/6167 [35:33<23:23,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camila_Cabello.jpg

 42%|████▏     | 2587/6167 [35:33<21:25,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camila_Sodi.jpg

 42%|████▏     | 2588/6167 [35:34<24:18,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Blanca_Estela_Pavón.jpg

 42%|████▏     | 2589/6167 [35:34<21:49,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bibi_Gaytán.jpg

 42%|████▏     | 2590/6167 [35:35<43:38,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bianca_Marroquín.jpg

 42%|████▏     | 2591/6167 [35:36<39:57,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Betsy_Pecanins.jpg

 42%|████▏     | 2592/6167 [35:36<32:22,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Belinda_Peregrín.jpg

 42%|████▏     | 2593/6167 [35:37<34:18,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beatriz_Adriana.jpg

 42%|████▏     | 2594/6167 [35:37<33:54,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ashley_Grace.jpg

 42%|████▏     | 2595/6167 [35:38<34:08,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aracely_Arámbula.jpg

 42%|████▏     | 2596/6167 [35:38<28:49,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angélica_Vale.jpg

 42%|████▏     | 2597/6167 [35:39<25:07,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angélica_Rivera.jpg

 42%|████▏     | 2598/6167 [35:39<23:47,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angélica_María.jpg

 42%|████▏     | 2599/6167 [35:39<27:36,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angélica_Aragón.jpg

 42%|████▏     | 2600/6167 [35:40<23:53,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ángela_Aguilar.jpg

 42%|████▏     | 2601/6167 [35:40<25:51,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anahí.jpg

 42%|████▏     | 2602/6167 [35:41<26:21,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Victoria.jpg

 42%|████▏     | 2603/6167 [35:41<28:37,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Gabriel.jpg

 42%|████▏     | 2604/6167 [35:42<30:37,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Bárbara.jpg

 42%|████▏     | 2605/6167 [35:42<31:31,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amparo_Ochoa.jpg

 42%|████▏     | 2606/6167 [35:43<32:18,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amanda_Miguel.jpg

 42%|████▏     | 2607/6167 [35:44<39:03,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amalia_Mendoza.jpg

 42%|████▏     | 2608/6167 [35:44<37:02,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ally_Brooke.jpg

 42%|████▏     | 2609/6167 [35:45<35:09,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alix_Bauer.jpg

 42%|████▏     | 2610/6167 [35:46<36:26,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alicia_Villarreal.jpg

 42%|████▏     | 2611/6167 [35:46<36:31,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alessandra_Rosaldo.jpg

 42%|████▏     | 2612/6167 [35:47<30:08,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alejandra_Guzmán.jpg

 42%|████▏     | 2613/6167 [35:47<34:19,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleida_Núñez.jpg

 42%|████▏     | 2615/6167 [35:48<28:50,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aida_Cuevas.jpg

 42%|████▏     | 2616/6167 [35:48<25:11,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ziana_Zain.jpg

 42%|████▏     | 2618/6167 [35:49<22:05,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zee_Avi.jpg

 42%|████▏     | 2620/6167 [35:49<16:53,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuna.jpg

 43%|████▎     | 2622/6167 [35:49<14:11,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wany_Hasrita.jpg

 43%|████▎     | 2623/6167 [35:50<15:06,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wani_Kayrie.jpg

 43%|████▎     | 2625/6167 [35:50<12:22,  4.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Victor_Wong.jpg

 43%|████▎     | 2626/6167 [35:50<13:13,  4.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tiz_Zaqyah.jpg

 43%|████▎     | 2627/6167 [35:51<13:22,  4.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suki_Low.jpg

 43%|████▎     | 2628/6167 [35:51<15:02,  3.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sudirman_Arshad.jpg

 43%|████▎     | 2630/6167 [35:51<12:22,  4.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stacy.jpg

 43%|████▎     | 2632/6167 [35:52<14:30,  4.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Siti_Nurhaliza.jpg

 43%|████▎     | 2633/6167 [35:52<15:04,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Soo_Wincci.jpg

 43%|████▎     | 2634/6167 [35:53<17:40,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shila_Amzah.jpg

 43%|████▎     | 2636/6167 [35:53<13:49,  4.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sheila_Majid.jpg

 43%|████▎     | 2641/6167 [35:53<08:51,  6.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shah_Indrawan_Ismail.jpg

 43%|████▎     | 2642/6167 [35:54<11:45,  5.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sean_Ghazi.jpg

 43%|████▎     | 2643/6167 [35:55<26:15,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sarimah_Ibrahim.jpg

 43%|████▎     | 2644/6167 [35:56<23:40,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandra_Dianne.jpg

 43%|████▎     | 2645/6167 [35:56<21:52,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Salmah_Ismail.jpg

 43%|████▎     | 2646/6167 [35:56<20:10,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rynn_Lim.jpg

 43%|████▎     | 2651/6167 [35:56<09:22,  6.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Remy_Ishak.jpg

 43%|████▎     | 2660/6167 [35:57<05:36, 10.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Penny_Tai.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noh_Salleh.jpg

 43%|████▎     | 2662/6167 [35:58<10:23,  5.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noraniza_Idris.jpg

 43%|████▎     | 2663/6167 [35:58<11:06,  5.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ning_Baizura.jpg

 43%|████▎     | 2669/6167 [36:00<13:08,  4.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohd_Taufik_Nordin.jpg

 43%|████▎     | 2671/6167 [36:00<12:29,  4.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michael_Wong.jpg

 43%|████▎     | 2673/6167 [36:01<11:29,  5.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meeia_Foo.jpg

 43%|████▎     | 2674/6167 [36:01<12:52,  4.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Karin.jpg

 43%|████▎     | 2675/6167 [36:02<18:36,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mawi.jpg

 43%|████▎     | 2677/6167 [36:02<15:16,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marsha_Milan_Londoh.jpg

 44%|████▎     | 2685/6167 [36:02<07:09,  8.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jess_Lee.jpg

 44%|████▎     | 2688/6167 [36:03<09:02,  6.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jamal_Abdillah.jpg

 44%|████▎     | 2689/6167 [36:04<10:13,  5.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jaclyn_Victor.jpg

 44%|████▎     | 2692/6167 [36:04<08:42,  6.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Imee_Ooi.jpg

 44%|████▎     | 2693/6167 [36:04<11:52,  4.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hunny_Madu.jpg

 44%|████▎     | 2694/6167 [36:05<15:21,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hannah_Tan.jpg

 44%|████▎     | 2696/6167 [36:05<13:22,  4.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hafiz_Suip.jpg

 44%|████▎     | 2698/6167 [36:06<11:19,  5.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gary_Chaw.jpg

 44%|████▍     | 2699/6167 [36:06<13:04,  4.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fattah_Amin.jpg

 44%|████▍     | 2700/6167 [36:06<14:09,  4.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Freya_Lim.jpg

 44%|████▍     | 2701/6167 [36:07<17:05,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francissca_Peter.jpg

 44%|████▍     | 2702/6167 [36:07<17:40,  3.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fish_Leong.jpg

 44%|████▍     | 2706/6167 [36:07<09:40,  5.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Faizal_Tahir.jpg

 44%|████▍     | 2710/6167 [36:08<08:28,  6.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eric_Moo.jpg

 44%|████▍     | 2711/6167 [36:08<09:46,  5.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erra_Fazira.jpg

 44%|████▍     | 2712/6167 [36:09<13:03,  4.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ella.jpg

 44%|████▍     | 2714/6167 [36:09<11:21,  5.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dayang_Nurfaizah.jpg

 44%|████▍     | 2720/6167 [36:09<07:37,  7.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camelia.jpg

 44%|████▍     | 2722/6167 [36:10<10:33,  5.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bell_Yu_Tian.jpg

 44%|████▍     | 2723/6167 [36:11<13:04,  4.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amira_Othman.jpg

 44%|████▍     | 2724/6167 [36:11<13:14,  4.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aznil_Nawawi.jpg

 44%|████▍     | 2727/6167 [36:11<10:25,  5.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayda_Jebat.jpg

 44%|████▍     | 2728/6167 [36:11<11:04,  5.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Awie.jpg

 44%|████▍     | 2729/6167 [36:12<14:52,  3.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ash_Nair.jpg

 44%|████▍     | 2730/6167 [36:13<20:40,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Armando_Chin_Yong.jpg

 44%|████▍     | 2732/6167 [36:13<18:48,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anuar_Zain.jpg

 44%|████▍     | 2734/6167 [36:14<14:45,  3.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angelica_Lee.jpg

 44%|████▍     | 2735/6167 [36:14<14:36,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amy_Mastura.jpg

 44%|████▍     | 2737/6167 [36:14<11:53,  4.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Altimet.jpg

 44%|████▍     | 2738/6167 [36:14<13:16,  4.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alif_Satar.jpg

 44%|████▍     | 2739/6167 [36:15<16:06,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aizat_Amdan.jpg

 44%|████▍     | 2740/6167 [36:15<16:31,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aiman_Hakim_Ridza.jpg

 44%|████▍     | 2742/6167 [36:15<12:57,  4.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ah_Niu.jpg

 44%|████▍     | 2744/6167 [36:16<10:54,  5.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Afdlin_Shauki.jpg

 45%|████▍     | 2748/6167 [36:16<10:46,  5.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ieva_Zasimauskaitė.jpg

 45%|████▍     | 2749/6167 [36:17<14:28,  3.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Lithuania.jpg

 45%|████▍     | 2751/6167 [36:18<17:22,  3.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Žalvarinis.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ovidijus_Vyšniauskas.jpg

 45%|████▍     | 2752/6167 [36:18<19:29,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurijus_Veklenko.jpg

 45%|████▍     | 2753/6167 [36:19<20:50,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lena_Valaitis.jpg

 45%|████▍     | 2754/6167 [36:21<40:15,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Violeta_Urmana.jpg

 45%|████▍     | 2757/6167 [36:21<24:40,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stano.jpg

 45%|████▍     | 2758/6167 [36:22<25:00,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sasha_Son.jpg

 45%|████▍     | 2760/6167 [36:22<20:48,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aistė_Smilgevičiūtė.jpg

 45%|████▍     | 2761/6167 [36:23<24:32,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/SKAMP.jpg

 45%|████▍     | 2763/6167 [36:24<25:16,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurga_Šeduikytė.jpg

 45%|████▍     | 2766/6167 [36:24<18:09,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Evelina_Sašenko.jpg

 45%|████▍     | 2768/6167 [36:24<14:33,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Roop.jpg

 45%|████▍     | 2769/6167 [36:25<20:29,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mindaugas_Rojus.jpg

 45%|████▍     | 2770/6167 [36:27<30:56,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Violeta_Riaubiškytė-Tarasovienė.jpg

 45%|████▍     | 2772/6167 [36:27<26:30,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stasys_Povilaitis.jpg

 45%|████▍     | 2773/6167 [36:28<26:41,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aistė_Pilvelytė.jpg

 45%|████▍     | 2774/6167 [36:28<27:34,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrius_Pojavis.jpg

 45%|████▍     | 2775/6167 [36:30<48:54,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kipras_Petrauskas.jpg

 45%|████▌     | 2776/6167 [36:31<43:36,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alina_Orlova.jpg

 45%|████▌     | 2777/6167 [36:31<39:29,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ieva_Narkutė.jpg

 45%|████▌     | 2778/6167 [36:32<35:51,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Virgilijus_Noreika.jpg

 45%|████▌     | 2779/6167 [36:32<34:58,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vilija_Matačiūnaitė.jpg

 45%|████▌     | 2781/6167 [36:33<25:22,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Donny_Montell.jpg

 45%|████▌     | 2782/6167 [36:33<28:49,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jeronimas_Milius.jpg

 45%|████▌     | 2783/6167 [36:34<29:51,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marijonas_Mikutavičius.jpg

 45%|████▌     | 2784/6167 [36:34<25:56,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vilija_Matačiūnaitė.jpg

 45%|████▌     | 2785/6167 [36:35<32:56,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mia.jpg

 45%|████▌     | 2787/6167 [36:36<25:17,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrius_Mamontovas.jpg

 45%|████▌     | 2788/6167 [36:36<27:01,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arnoldas_Lukošius.jpg

 45%|████▌     | 2789/6167 [36:37<31:55,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monika_Liu.jpg

 45%|████▌     | 2790/6167 [36:39<47:43,  1.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monika_Linkytė.jpg

 45%|████▌     | 2791/6167 [36:40<45:29,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linas_and_Simona.jpg

 45%|████▌     | 2792/6167 [36:40<40:47,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nechama_Lifshitz.jpg

 45%|████▌     | 2793/6167 [36:41<39:24,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Judita_Leitaitė.jpg

 45%|████▌     | 2795/6167 [36:43<48:38,  1.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vytautas_Kernagis.jpg

 45%|████▌     | 2798/6167 [36:43<29:58,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katarsis.jpg

 45%|████▌     | 2799/6167 [36:45<40:25,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eglė_Jurgaitytė.jpg

 45%|████▌     | 2800/6167 [36:45<38:12,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vytautas_Juozapaitis.jpg

 45%|████▌     | 2802/6167 [36:46<29:22,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jarosekas_Quartet.jpg

 45%|████▌     | 2803/6167 [36:47<34:50,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Justinas_Jarutis.jpg

 45%|████▌     | 2804/6167 [36:48<35:52,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severija_Janušauskaitė.jpg

 45%|████▌     | 2805/6167 [36:48<34:52,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mantas_Jankavičius.jpg

 46%|████▌     | 2806/6167 [36:49<32:28,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inga_Jankauskaitė.jpg

 46%|████▌     | 2807/6167 [36:49<31:01,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Justina_Gringytė.jpg

 46%|████▌     | 2808/6167 [36:50<34:36,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/InCulto.jpg

 46%|████▌     | 2809/6167 [36:51<35:38,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Asmik_Grigorian.jpg

 46%|████▌     | 2810/6167 [36:51<34:16,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/GJan.jpg

 46%|████▌     | 2811/6167 [36:52<36:02,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/GiedRé.jpg

 46%|████▌     | 2812/6167 [36:52<35:14,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vaida_Genytė.jpg

 46%|████▌     | 2813/6167 [36:53<34:09,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fusedmarc.jpg

 46%|████▌     | 2814/6167 [36:54<41:50,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danielius_Dolskis.jpg

 46%|████▌     | 2817/6167 [36:55<25:59,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vaidas_Baumila.jpg

 46%|████▌     | 2818/6167 [36:57<42:27,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvester_Belt.jpg

 46%|████▌     | 2819/6167 [36:58<42:51,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vytautas_Babravičius.jpg

 46%|████▌     | 2821/6167 [37:09<2:29:42,  2.68s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Nijol%C4%97.jpg/200px-Nijol%C4%97.jpg: The read operation timed out

 46%|████▌     | 2822/6167 [37:19<4:00:57,  4.32s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/4fun_Eurovision_2007.jpg/250px-4fun_Eurovision_2007.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2823/6167 [37:29<5:18:01,  5.71s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/MagniHermosaBeach5-13-07.jpg/250px-MagniHermosaBeach5-13-07.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2824/6167 [37:39<6:20:08,  6.82s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ageir_Trausti.jpg/250px-Ageir_Trausti.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2825/6167 [37:49<7:08:03,  7.68s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/Vilhj%C3%A1lmur_Vilhj%C3%A1lmsson_portrait.jpg/250px-Vilhj%C3%A1lmur_Vilhj%C3%A1lmsson_portrait.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2827/6167 [37:59<6:03:35,  6.53s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Emiliana_Torrini_02.jpg/250px-Emiliana_Torrini_02.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2828/6167 [38:09<6:50:02,  7.37s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ageir_Trausti.jpg/250px-Ageir_Trausti.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2829/6167 [38:19<7:27:52,  8.05s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Svala_%28singer%29_Red_Carpet4_Kyiv2_2017.jpg/250px-Svala_%28singer%29_Red_Carpet4_Kyiv2_2017.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2830/6167 [38:29<7:57:32,  8.59s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Soley2.jpg/250px-Soley2.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2831/6167 [38:39<8:20:13,  9.00s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/ESC2016_-_Iceland_Meet_%26_Greet_03.jpg/250px-ESC2016_-_Iceland_Meet_%26_Greet_03.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2834/6167 [38:49<5:30:27,  5.95s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Pascal_Pinon_in_2009_in_the_Nordic_House%2C_Reykjav%C3%ADk.jpg/250px-Pascal_Pinon_in_2009_in_the_Nordic_House%2C_Reykjav%C3%ADk.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2835/6167 [38:59<6:16:54,  6.79s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Prins_Polo.jpg/330px-Prins_Polo.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2836/6167 [39:10<6:58:00,  7.53s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/BlueCarpet2018-052-Iceland2-EuroVisionary.jpg/250px-BlueCarpet2018-052-Iceland2-EuroVisionary.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2837/6167 [39:20<7:32:03,  8.15s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/PaulOscar-ScalaLondon-20080425-closeup.jpg/250px-PaulOscar-ScalaLondon-20080425-closeup.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2838/6167 [39:30<7:59:44,  8.65s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Mugison.jpg/250px-Mugison.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2839/6167 [39:40<8:20:57,  9.03s/it]

✗ Failed to download https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bubbi_Morthens_%28285001430%29.jpg/250px-Bubbi_Morthens_%28285001430%29.jpg: [Errno 101] Network is unreachable

 46%|████▌     | 2840/6167 [39:40<6:05:27,  6.59s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laufey.jpg

 46%|████▌     | 2841/6167 [39:41<4:29:57,  4.87s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Megas.jpg

 46%|████▌     | 2842/6167 [39:41<3:16:37,  3.55s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Low_Roar.jpg

 46%|████▌     | 2844/6167 [39:41<1:56:09,  2.10s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Júníus_Meyvant.jpg

 46%|████▌     | 2845/6167 [39:42<1:31:44,  1.66s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lay_Low.jpg

 46%|████▌     | 2846/6167 [39:43<1:19:20,  1.43s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jónsi.jpg

 46%|████▌     | 2847/6167 [39:43<1:06:21,  1.20s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jófríður_Ákadóttir.jpg

 46%|████▌     | 2848/6167 [39:44<59:33,  1.08s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Högni_Egilsson.jpg

 46%|████▌     | 2849/6167 [39:45<52:39,  1.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jón_Jónsson.jpg

 46%|████▌     | 2850/6167 [39:45<41:22,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hilmar_Örn_Hilmarsson.jpg

 46%|████▌     | 2851/6167 [39:45<36:36,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hafdís_Huld.jpg

 46%|████▋     | 2853/6167 [39:46<25:49,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eyþór_Ingi_Gunnlaugsson.jpg

 46%|████▋     | 2854/6167 [39:46<25:46,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ragnheiður_Gröndal.jpg

 46%|████▋     | 2855/6167 [39:47<25:55,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jóhanna_Guðrún.jpg

 46%|████▋     | 2856/6167 [39:47<27:28,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emmsjé_Gauti.jpg

 46%|████▋     | 2858/6167 [39:49<34:51,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eivør.jpg

 46%|████▋     | 2859/6167 [39:50<45:15,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Friðrik_Dór.jpg

 46%|████▋     | 2860/6167 [39:51<42:20,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daði_Freyr.jpg

 46%|████▋     | 2862/6167 [39:52<32:53,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Björk.jpg

 46%|████▋     | 2863/6167 [39:52<29:00,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hera_Björk.jpg

 46%|████▋     | 2864/6167 [39:53<31:59,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ragnar_Bjarnason.jpg

 46%|████▋     | 2865/6167 [39:53<31:02,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ásgeir.jpg

 46%|████▋     | 2866/6167 [39:54<35:00,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arnór_Dan_Arnarson.jpg

 46%|████▋     | 2867/6167 [39:55<48:29,  1.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ólöf_Arnalds.jpg

 47%|████▋     | 2868/6167 [39:56<38:46,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ólafur_Arnalds.jpg

 47%|████▋     | 2870/6167 [39:56<24:39,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Line_Music.jpg

 47%|████▋     | 2871/6167 [39:57<29:45,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oricon_Music_Store.jpg

 47%|████▋     | 2872/6167 [39:57<26:51,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/E-Onkyo_music.jpg

 47%|████▋     | 2873/6167 [39:58<29:26,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dwango.jp.jpg

 47%|████▋     | 2874/6167 [39:58<29:42,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mora.jpg

 47%|████▋     | 2875/6167 [39:59<26:31,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/RecoChoku.jpg

 47%|████▋     | 2876/6167 [39:59<29:10,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/LISMO.jpg

 47%|████▋     | 2877/6167 [40:00<29:20,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/KKBox.jpg

 47%|████▋     | 2878/6167 [40:01<29:42,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Spotify.jpg

 47%|████▋     | 2879/6167 [40:01<29:42,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Apple_Music.jpg

 47%|████▋     | 2880/6167 [40:02<30:18,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amazon_Music.jpg

 47%|████▋     | 2881/6167 [40:02<26:27,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Google_Play_Music.jpg

 47%|████▋     | 2882/6167 [40:02<22:35,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/iTunes_Store.jpg

 47%|████▋     | 2900/6167 [40:03<03:24, 15.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/2010.jpg

 47%|████▋     | 2911/6167 [40:04<04:55, 11.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teichiku_Entertainment.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pony_Canyon.jpg

 47%|████▋     | 2913/6167 [40:05<07:27,  7.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Warner_Music_Group.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Victor_Entertainment.jpg

 47%|████▋     | 2915/6167 [40:06<11:21,  4.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Being_Inc..jpg

 47%|████▋     | 2916/6167 [40:07<12:55,  4.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/J_Storm.jpg

 47%|████▋     | 2918/6167 [40:07<12:46,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Universal_Music_Japan.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/King_Record_Co..jpg

 47%|████▋     | 2919/6167 [40:08<13:08,  4.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sony_Music_Entertainment_Japan.jpg

 47%|████▋     | 2920/6167 [40:08<13:14,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Avex_Group.jpg

 47%|████▋     | 2925/6167 [40:08<07:09,  7.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Combined_Albums_Chart.jpg

 47%|████▋     | 2927/6167 [40:09<08:03,  6.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Combined_Singles_Chart.jpg

 47%|████▋     | 2929/6167 [40:10<13:14,  4.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Southern_Islands.jpg

 48%|████▊     | 2931/6167 [40:10<14:30,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ainu_music.jpg

 48%|████▊     | 2934/6167 [40:11<10:32,  5.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vocaloid_music.jpg

 48%|████▊     | 2935/6167 [40:11<14:44,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Visual_kei.jpg

 48%|████▊     | 2937/6167 [40:12<20:02,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akishibu-kei.jpg

 48%|████▊     | 2938/6167 [40:13<19:33,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shibuya-kei.jpg

 48%|████▊     | 2939/6167 [40:13<22:40,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Onkyokei.jpg

 48%|████▊     | 2940/6167 [40:14<21:25,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kawaii_metal.jpg

 48%|████▊     | 2943/6167 [40:14<13:39,  3.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Grime.jpg

 48%|████▊     | 2945/6167 [40:15<15:13,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Juliana’s_techno.jpg

 48%|████▊     | 2947/6167 [40:15<14:25,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Italo_Disco.jpg

 48%|████▊     | 2948/6167 [40:16<15:18,  3.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Visual_kei.jpg

 48%|████▊     | 2950/6167 [40:16<12:06,  4.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Synth-pop.jpg

 48%|████▊     | 2953/6167 [40:17<16:24,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noise_rock.jpg

 48%|████▊     | 2954/6167 [40:18<18:47,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noise.jpg

 48%|████▊     | 2955/6167 [40:18<19:04,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Metal.jpg

 48%|████▊     | 2956/6167 [40:19<22:12,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hip_hop.jpg

 48%|████▊     | 2958/6167 [40:20<26:43,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eurobeat.jpg

 48%|████▊     | 2959/6167 [40:20<24:03,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Electropop.jpg

 48%|████▊     | 2961/6167 [40:21<24:13,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Electro.jpg

 48%|████▊     | 2962/6167 [40:21<22:34,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiptune.jpg

 48%|████▊     | 2963/6167 [40:22<23:35,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/City_pop.jpg

 48%|████▊     | 2964/6167 [40:22<21:57,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anime_song.jpg

 48%|████▊     | 2965/6167 [40:23<25:03,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rock.jpg

 48%|████▊     | 2966/6167 [40:23<23:46,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/J-pop.jpg

 48%|████▊     | 2967/6167 [40:24<22:15,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Image_song.jpg

 48%|████▊     | 2969/6167 [40:24<19:31,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ryūkōka.jpg

 48%|████▊     | 2974/6167 [40:25<09:38,  5.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enzetsuka/Enka.jpg

 48%|████▊     | 2975/6167 [40:25<12:45,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Komori-uta_(lullaby).jpg

 48%|████▊     | 2976/6167 [40:26<17:04,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rōkyoku.jpg

 48%|████▊     | 2977/6167 [40:27<22:11,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nagauta.jpg

 48%|████▊     | 2978/6167 [40:27<26:36,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Min'yō.jpg

 48%|████▊     | 2981/6167 [40:28<21:52,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gigaku.jpg

 48%|████▊     | 2982/6167 [40:30<34:42,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gagaku.jpg

 48%|████▊     | 2983/6167 [40:30<31:49,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danmono.jpg

 48%|████▊     | 2984/6167 [40:31<27:19,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dainichido_Bugaku.jpg

 48%|████▊     | 2986/6167 [40:32<25:47,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bugaku.jpg

 48%|████▊     | 2988/6167 [40:32<21:49,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaq.jpg

 49%|████▊     | 2994/6167 [40:32<10:28,  5.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Izumi_Yukimura.jpg

 49%|████▊     | 2996/6167 [40:33<10:27,  5.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saori_Yuki.jpg

 49%|████▊     | 3000/6167 [40:34<09:58,  5.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui.jpg

 49%|████▊     | 3004/6167 [40:34<10:11,  5.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hitomi_Yoshizawa.jpg

 49%|████▉     | 3010/6167 [40:35<06:47,  7.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Soyoka_Yoshida.jpg

 49%|████▉     | 3012/6167 [40:35<07:13,  7.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Yokoyama.jpg

 49%|████▉     | 3015/6167 [40:35<07:32,  6.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toko_Yasuda.jpg

 49%|████▉     | 3018/6167 [40:36<07:06,  7.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Yashiro.jpg

 49%|████▉     | 3021/6167 [40:36<06:52,  7.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hiromi_Yanagihara.jpg

 49%|████▉     | 3023/6167 [40:36<06:58,  7.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomohisa_Yamashita.jpg

 49%|████▉     | 3025/6167 [40:37<08:02,  6.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linda_Yamamoto.jpg

 49%|████▉     | 3027/6167 [40:37<08:02,  6.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoshiko_Yamaguchi.jpg

 49%|████▉     | 3029/6167 [40:38<12:49,  4.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yu_Yamada.jpg

 49%|████▉     | 3030/6167 [40:38<12:57,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ryosuke_Yamada.jpg

 49%|████▉     | 3033/6167 [40:39<09:31,  5.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maimi_Yajima.jpg

 49%|████▉     | 3035/6167 [40:39<08:37,  6.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mari_Yaguchi.jpg

 49%|████▉     | 3037/6167 [40:39<09:16,  5.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nako_Yabuki.jpg

 49%|████▉     | 3040/6167 [40:40<08:47,  5.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chon_Wolson.jpg

 49%|████▉     | 3043/6167 [40:40<07:28,  6.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mayu_Watanabe.jpg

 49%|████▉     | 3045/6167 [40:40<07:42,  6.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hamako_Watanabe.jpg

 49%|████▉     | 3046/6167 [40:41<10:21,  5.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Misato_Watanabe.jpg

 49%|████▉     | 3047/6167 [40:41<12:54,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanon_Wakeshima.jpg

 49%|████▉     | 3048/6167 [40:42<16:18,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomiko_Van.jpg

 50%|████▉     | 3054/6167 [40:43<09:02,  5.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miyoshi_Umeki.jpg

 50%|████▉     | 3055/6167 [40:43<10:05,  5.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Misako_Uno.jpg

 50%|████▉     | 3056/6167 [40:43<10:34,  4.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hikaru_Utada.jpg

 50%|████▉     | 3058/6167 [40:43<09:49,  5.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aya_Ueto.jpg

 50%|████▉     | 3061/6167 [40:44<08:38,  5.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kana_Uemura.jpg

 50%|████▉     | 3062/6167 [40:44<10:08,  5.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Takako_Uehara.jpg

 50%|████▉     | 3068/6167 [40:45<05:40,  9.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ua.jpg

 50%|████▉     | 3073/6167 [40:45<04:29, 11.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Momoko_Tsugunaga.jpg

 50%|████▉     | 3075/6167 [40:45<05:05, 10.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Tsuchiya.jpg

 50%|████▉     | 3077/6167 [40:46<07:06,  7.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Toyosaki.jpg

 50%|████▉     | 3078/6167 [40:46<08:36,  5.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nao_Tōyama.jpg

 50%|████▉     | 3081/6167 [40:46<07:07,  7.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kazuki_Tomokawa.jpg

 50%|████▉     | 3082/6167 [40:48<16:49,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruka_Tomatsu.jpg

 50%|█████     | 3084/6167 [40:48<15:22,  3.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamaki_Tokuyama.jpg

 50%|█████     | 3086/6167 [40:49<14:05,  3.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sora_Tokui.jpg

 50%|█████     | 3087/6167 [40:49<16:24,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ami_Tokito.jpg

 50%|█████     | 3090/6167 [40:50<14:36,  3.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Todd.jpg

 50%|█████     | 3098/6167 [40:50<06:47,  7.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meru_Tashima.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masashi_Tashiro.jpg

 50%|█████     | 3100/6167 [40:51<11:38,  4.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tarako.jpg

 50%|█████     | 3101/6167 [40:52<12:09,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tao_Tsuchiya.jpg

 50%|█████     | 3102/6167 [40:53<15:45,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nana_Tanimura.jpg

 50%|█████     | 3103/6167 [40:53<18:03,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shinji_Tanimura.jpg

 50%|█████     | 3106/6167 [40:54<15:00,  3.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoshiko_Tanaka.jpg

 50%|█████     | 3108/6167 [40:54<15:12,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reina_Tanaka.jpg

 50%|█████     | 3109/6167 [40:55<14:53,  3.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukari_Tamura.jpg

 50%|█████     | 3111/6167 [40:55<13:08,  3.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eriko_Tamura.jpg

 50%|█████     | 3113/6167 [40:55<10:45,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nami_Tamaki.jpg

 50%|█████     | 3114/6167 [40:55<11:20,  4.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shiori_Tamai.jpg

 51%|█████     | 3115/6167 [40:56<11:31,  4.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nanako_Takushi.jpg

 51%|█████     | 3116/6167 [40:56<13:10,  3.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariya_Takeuchi.jpg

 51%|█████     | 3117/6167 [40:57<17:46,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miori_Takimoto.jpg

 51%|█████     | 3118/6167 [40:57<17:13,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tetsuya_Takeda.jpg

 51%|█████     | 3119/6167 [40:58<31:03,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akane_Takayanagi.jpg

 51%|█████     | 3127/6167 [40:59<09:10,  5.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Takajo.jpg

 51%|█████     | 3128/6167 [40:59<10:11,  4.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukihiro_Takahashi.jpg

 51%|█████     | 3130/6167 [41:00<13:15,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoko_Takahashi.jpg

 51%|█████     | 3131/6167 [41:00<13:20,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minami_Takahashi.jpg

 51%|█████     | 3135/6167 [41:00<08:34,  5.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Takahashi.jpg

 51%|█████     | 3136/6167 [41:01<09:21,  5.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reni_Takagi.jpg

 51%|█████     | 3139/6167 [41:01<08:40,  5.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayahi_Takagaki.jpg

 51%|█████     | 3140/6167 [41:02<13:00,  3.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sachi_Tainaka.jpg

 51%|█████     | 3143/6167 [41:02<10:30,  4.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syuri.jpg

 51%|█████     | 3152/6167 [41:03<05:15,  9.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ami_Suzuki.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Airi_Suzuki.jpg

 51%|█████     | 3154/6167 [41:03<06:59,  7.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fuku_Suzuki.jpg

 51%|█████     | 3158/6167 [41:04<08:55,  5.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Risako_Sugaya.jpg

 51%|█████     | 3160/6167 [41:05<10:17,  4.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maasa_Sudo.jpg

 51%|█████▏    | 3162/6167 [41:05<09:45,  5.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masaki_Suda.jpg

 51%|█████▏    | 3164/6167 [41:06<09:11,  5.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Suda.jpg

 51%|█████▏    | 3169/6167 [41:07<12:31,  3.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Machiko_Soga.jpg

 51%|█████▏    | 3170/6167 [41:08<15:54,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shanti_Snyder.jpg

 51%|█████▏    | 3174/6167 [41:08<10:52,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kavka_Shishido.jpg

 52%|█████▏    | 3180/6167 [41:09<07:15,  6.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ryoko_Shinohara.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomoe_Shinohara.jpg

 52%|█████▏    | 3182/6167 [41:10<10:25,  4.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariko_Shinoda.jpg

 52%|█████▏    | 3185/6167 [41:10<09:03,  5.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikuni_Shimokawa.jpg

 52%|█████▏    | 3186/6167 [41:10<09:27,  5.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saki_Shimizu.jpg

 52%|█████▏    | 3187/6167 [41:11<10:00,  4.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruka_Shimazaki.jpg

 52%|█████▏    | 3188/6167 [41:11<10:22,  4.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hitomi_Shimatani.jpg

 52%|█████▏    | 3190/6167 [41:11<09:19,  5.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiyoko_Shimakura.jpg

 52%|█████▏    | 3194/6167 [41:11<06:25,  7.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saki_Shimizu.jpg

 52%|█████▏    | 3195/6167 [41:12<08:48,  5.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariko_Shiga.jpg

 52%|█████▏    | 3198/6167 [41:12<09:17,  5.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jun_Shibata.jpg

 52%|█████▏    | 3200/6167 [41:13<09:39,  5.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kō_Shibasaki.jpg

 52%|█████▏    | 3202/6167 [41:13<09:28,  5.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ringo_Sheena.jpg

 52%|█████▏    | 3206/6167 [41:14<07:07,  6.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eiko_Segawa.jpg

 52%|█████▏    | 3207/6167 [41:14<08:02,  6.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayuri.jpg

 52%|█████▏    | 3208/6167 [41:14<09:29,  5.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Riho_Sayashi.jpg

 52%|█████▏    | 3212/6167 [41:15<07:11,  6.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Megumi_Satsu.jpg

 52%|█████▏    | 3215/6167 [41:15<06:39,  7.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sumire_Satō.jpg

 52%|█████▏    | 3217/6167 [41:15<07:18,  6.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masaki_Sato.jpg

 52%|█████▏    | 3218/6167 [41:16<10:14,  4.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiyako_Sato.jpg

 52%|█████▏    | 3222/6167 [41:16<07:07,  6.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rikako_Sasaki.jpg

 52%|█████▏    | 3223/6167 [41:17<09:21,  5.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rino_Sashihara.jpg

 52%|█████▏    | 3224/6167 [41:18<22:40,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikoi_Sasaki.jpg

 52%|█████▏    | 3225/6167 [41:19<20:50,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayaka_Sasaki.jpg

 52%|█████▏    | 3226/6167 [41:19<18:59,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mary_Sara.jpg

 52%|█████▏    | 3229/6167 [41:19<11:38,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Makoto_Sakurada.jpg

 52%|█████▏    | 3233/6167 [41:19<07:39,  6.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miu_Sakamoto.jpg

 52%|█████▏    | 3234/6167 [41:20<09:09,  5.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maaya_Sakamoto.jpg

 52%|█████▏    | 3235/6167 [41:20<11:30,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyu_Sakamoto.jpg

 52%|█████▏    | 3237/6167 [41:21<09:53,  4.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ikue_Sakakibara.jpg

 53%|█████▎    | 3239/6167 [41:21<10:36,  4.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noriko_Sakai.jpg

 53%|█████▎    | 3241/6167 [41:21<10:20,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Izumi_Sakai.jpg

 53%|█████▎    | 3245/6167 [41:22<07:05,  6.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hideki_Saijo.jpg

 53%|█████▎    | 3252/6167 [41:22<04:04, 11.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reona.jpg

 53%|█████▎    | 3258/6167 [41:22<03:18, 14.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pinko_Izumi.jpg

 53%|█████▎    | 3260/6167 [41:23<05:21,  9.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pile.jpg

 53%|█████▎    | 3268/6167 [41:23<03:38, 13.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuko_Oshima.jpg

 53%|█████▎    | 3272/6167 [41:23<03:29, 13.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lisa_Ono.jpg

 53%|█████▎    | 3274/6167 [41:24<05:05,  9.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fumiko_Orikasa.jpg

 53%|█████▎    | 3276/6167 [41:24<05:28,  8.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Judy_Ongg.jpg

 53%|█████▎    | 3278/6167 [41:25<05:40,  8.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Makoto_Okunaka.jpg

 53%|█████▎    | 3280/6167 [41:25<05:31,  8.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masami_Okui.jpg

 53%|█████▎    | 3281/6167 [41:25<09:13,  5.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanako_Oku.jpg

 53%|█████▎    | 3287/6167 [41:26<05:42,  8.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chisato_Okai.jpg

 53%|█████▎    | 3289/6167 [41:26<06:17,  7.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukiko_Okada.jpg

 53%|█████▎    | 3291/6167 [41:27<08:53,  5.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robin_Shoko_Okada.jpg

 53%|█████▎    | 3295/6167 [41:28<08:01,  5.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yumi_Ohka.jpg

 54%|█████▎    | 3300/6167 [41:28<05:59,  7.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nozomi_Ōhashi.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Ogura.jpg

 54%|█████▎    | 3305/6167 [41:28<04:56,  9.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakura_Oda.jpg

 54%|█████▎    | 3307/6167 [41:30<12:35,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kazuha_Oda.jpg

 54%|█████▎    | 3309/6167 [41:30<11:21,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rena_Nōnen.jpg

 54%|█████▎    | 3310/6167 [41:31<13:03,  3.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Nonaka.jpg

 54%|█████▎    | 3313/6167 [41:31<10:48,  4.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yojiro_Noda.jpg

 54%|█████▍    | 3316/6167 [41:32<08:51,  5.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikiho_Niwa.jpg

 54%|█████▍    | 3318/6167 [41:32<08:11,  5.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariya_Nishiuchi.jpg

 54%|█████▍    | 3321/6167 [41:32<07:49,  6.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Riki_Nishimura.jpg

 54%|█████▍    | 3322/6167 [41:33<12:27,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kana_Nishino.jpg

 54%|█████▍    | 3325/6167 [41:34<11:18,  4.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haru_Nemuri.jpg

 54%|█████▍    | 3326/6167 [41:35<13:57,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Risa_Niigaki.jpg

 54%|█████▍    | 3327/6167 [41:35<13:44,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miyabi_Natsuyaki.jpg

 54%|█████▍    | 3328/6167 [41:35<17:17,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rimi_Natsukawa.jpg

 54%|█████▍    | 3336/6167 [41:36<06:20,  7.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miho_Nakayama.jpg

 54%|█████▍    | 3338/6167 [41:36<06:20,  7.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Nakashima.jpg

 54%|█████▍    | 3340/6167 [41:37<07:46,  6.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aya_Nakano.jpg

 54%|█████▍    | 3343/6167 [41:38<10:07,  4.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ataru_Nakamura.jpg

 54%|█████▍    | 3344/6167 [41:38<10:48,  4.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suzuka_Nakamoto.jpg

 54%|█████▍    | 3345/6167 [41:38<11:00,  4.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akina_Nakamori.jpg

 54%|█████▍    | 3346/6167 [41:38<11:42,  4.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukie_Nakama.jpg

 54%|█████▍    | 3347/6167 [41:39<12:08,  3.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuto_Nakajima.jpg

 54%|█████▍    | 3348/6167 [41:39<12:37,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saki_Nakajima.jpg

 54%|█████▍    | 3351/6167 [41:39<08:43,  5.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Megumi_Nakajima.jpg

 54%|█████▍    | 3352/6167 [41:40<12:31,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuta_Nakamoto.jpg

 54%|█████▍    | 3354/6167 [41:41<13:32,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shoko_Nakagawa.jpg

 54%|█████▍    | 3356/6167 [41:41<10:57,  4.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yōko_Nagayama.jpg

 54%|█████▍    | 3359/6167 [41:41<08:05,  5.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mina_Myōi.jpg

 55%|█████▍    | 3367/6167 [41:43<08:08,  5.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayaka_Miyoshi.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Taichi_Mukai.jpg

 55%|█████▍    | 3370/6167 [41:43<08:12,  5.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chisato_Moritaka.jpg

 55%|█████▍    | 3376/6167 [41:44<05:41,  8.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Momoe_Mori.jpg

 55%|█████▍    | 3378/6167 [41:44<06:41,  6.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanako_Momota.jpg

 55%|█████▍    | 3380/6167 [41:45<08:19,  5.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yūko_Mizutani.jpg

 55%|█████▍    | 3381/6167 [41:45<11:52,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaori_Mochida.jpg

 55%|█████▍    | 3382/6167 [41:46<12:15,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Mizuno.jpg

 55%|█████▍    | 3384/6167 [41:46<11:03,  4.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nana_Mizuki.jpg

 55%|█████▍    | 3385/6167 [41:46<11:01,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alisa_Mizuki.jpg

 55%|█████▍    | 3386/6167 [41:47<11:47,  3.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mai_Mizuhashi.jpg

 55%|█████▍    | 3390/6167 [41:48<10:28,  4.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sae_Miyazawa.jpg

 55%|█████▍    | 3391/6167 [41:48<10:56,  4.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakura_Miyawaki.jpg

 55%|█████▌    | 3392/6167 [41:48<11:05,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miho_Miyazaki.jpg

 55%|█████▌    | 3393/6167 [41:49<12:54,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reina_Miyauchi.jpg

 55%|█████▌    | 3395/6167 [41:49<11:13,  4.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanako_Miyamoto.jpg

 55%|█████▌    | 3397/6167 [41:49<09:40,  4.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Harumi_Miyako.jpg

 55%|█████▌    | 3398/6167 [41:50<11:25,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukari_Miyake.jpg

 55%|█████▌    | 3401/6167 [41:50<08:09,  5.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miwa.jpg

 55%|█████▌    | 3402/6167 [41:50<09:21,  4.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamaki_Miura.jpg

 55%|█████▌    | 3404/6167 [41:50<08:14,  5.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hikari_Mitsushima.jpg

 55%|█████▌    | 3408/6167 [41:52<12:09,  3.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aika_Mitsui.jpg

 55%|█████▌    | 3409/6167 [41:52<12:32,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miki_Matsubara.jpg

 55%|█████▌    | 3413/6167 [41:52<08:19,  5.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hibari_Misora.jpg

 55%|█████▌    | 3414/6167 [41:53<11:38,  3.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daichi_Miura.jpg

 55%|█████▌    | 3416/6167 [41:54<10:47,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Misia.jpg

 55%|█████▌    | 3417/6167 [41:54<11:08,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Misato.jpg

 56%|█████▌    | 3425/6167 [41:54<05:33,  8.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minami_Minegishi.jpg

 56%|█████▌    | 3426/6167 [41:55<07:56,  5.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sana_Minatozaki.jpg

 56%|█████▌    | 3427/6167 [41:56<10:30,  4.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoko_Minamino.jpg

 56%|█████▌    | 3430/6167 [41:56<09:51,  4.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Kobayashi.jpg

 56%|█████▌    | 3431/6167 [41:56<10:11,  4.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suzuko_Mimori.jpg

 56%|█████▌    | 3433/6167 [41:57<09:29,  4.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mihiro.jpg

 56%|█████▌    | 3434/6167 [41:57<10:14,  4.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Junko_Mihara.jpg

 56%|█████▌    | 3437/6167 [41:57<08:07,  5.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayumi_Michishige.jpg

 56%|█████▌    | 3438/6167 [41:58<10:40,  4.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emi_Meyer.jpg

 56%|█████▌    | 3440/6167 [41:58<09:21,  4.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Melody.jpg

 56%|█████▌    | 3441/6167 [41:58<09:39,  4.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mell.jpg

 56%|█████▌    | 3442/6167 [41:59<09:57,  4.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/May'n.jpg

 56%|█████▌    | 3443/6167 [41:59<13:29,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meg.jpg

 56%|█████▌    | 3444/6167 [41:59<13:18,  3.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/May_J..jpg

 56%|█████▌    | 3446/6167 [42:00<10:18,  4.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yumi_Matsuzawa.jpg

 56%|█████▌    | 3447/6167 [42:00<10:25,  4.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiharu_Matsuyama.jpg

 56%|█████▌    | 3450/6167 [42:00<07:37,  5.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aya_Matsuura.jpg

 56%|█████▌    | 3454/6167 [42:01<05:58,  7.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rica_Matsumoto.jpg

 56%|█████▌    | 3456/6167 [42:01<06:46,  6.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sumako_Matsui.jpg

 56%|█████▌    | 3457/6167 [42:02<13:54,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakiko_Matsui.jpg

 56%|█████▌    | 3458/6167 [42:03<15:01,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rena_Matsui.jpg

 56%|█████▌    | 3459/6167 [42:03<14:41,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurina_Matsui.jpg

 56%|█████▌    | 3462/6167 [42:03<09:38,  4.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ritsuko_Matsuda.jpg

 56%|█████▌    | 3463/6167 [42:04<10:06,  4.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miki_Matsubara.jpg

 56%|█████▋    | 3473/6167 [42:04<03:38, 12.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maon_Kurosaki.jpg

 56%|█████▋    | 3477/6167 [42:04<04:39,  9.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Makino.jpg

 56%|█████▋    | 3481/6167 [42:05<05:45,  7.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Atsuko_Maeda.jpg

 57%|█████▋    | 3486/6167 [42:05<04:44,  9.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olivia_Lufkin.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liyuu.jpg

 57%|█████▋    | 3488/6167 [42:06<07:04,  6.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/LiSA.jpg

 57%|█████▋    | 3489/6167 [42:07<07:50,  5.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lisa.jpg

 57%|█████▋    | 3490/6167 [42:07<09:56,  4.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lili.jpg

 57%|█████▋    | 3491/6167 [42:08<12:12,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linlin.jpg

 57%|█████▋    | 3492/6167 [42:08<14:34,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lia.jpg

 57%|█████▋    | 3493/6167 [42:09<16:01,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Junjun.jpg

 57%|█████▋    | 3494/6167 [42:10<23:36,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leyona.jpg

 57%|█████▋    | 3497/6167 [42:10<14:15,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lecca.jpg

 57%|█████▋    | 3498/6167 [42:10<14:01,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyary_Pamyu_Pamyu.jpg

 57%|█████▋    | 3500/6167 [42:11<13:41,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kylee.jpg

 57%|█████▋    | 3507/6167 [42:12<07:35,  5.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiaki_Kuriyama.jpg

 57%|█████▋    | 3508/6167 [42:13<13:36,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minami_Kuribayashi.jpg

 57%|█████▋    | 3510/6167 [42:14<13:07,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mai_Kuraki.jpg

 57%|█████▋    | 3511/6167 [42:14<12:53,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Asuka_Kuramochi.jpg

 57%|█████▋    | 3514/6167 [42:15<12:26,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yurina_Kumai.jpg

 57%|█████▋    | 3515/6167 [42:15<12:45,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yurina_Kumai.jpg

 57%|█████▋    | 3518/6167 [42:15<09:12,  4.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruka_Kudō.jpg

 57%|█████▋    | 3526/6167 [42:16<04:52,  9.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katsutaro_Kouta.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kotringo.jpg

 57%|█████▋    | 3528/6167 [42:16<07:09,  6.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kotoko.jpg

 57%|█████▋    | 3529/6167 [42:17<09:15,  4.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minako_Kotobuki.jpg

 57%|█████▋    | 3530/6167 [42:18<10:58,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ami_Koshimizu.jpg

 57%|█████▋    | 3534/6167 [42:18<07:19,  5.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manami_Konishi.jpg

 57%|█████▋    | 3536/6167 [42:18<06:53,  6.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mikako_Komatsu.jpg

 57%|█████▋    | 3539/6167 [42:18<06:03,  7.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruna_Kojima.jpg

 57%|█████▋    | 3540/6167 [42:19<06:37,  6.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kokia.jpg

 57%|█████▋    | 3541/6167 [42:19<07:49,  5.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyōko_Koizumi.jpg

 57%|█████▋    | 3542/6167 [42:20<13:18,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruka_Kohara.jpg

 57%|█████▋    | 3543/6167 [42:20<15:11,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kumi_Koda.jpg

 57%|█████▋    | 3545/6167 [42:21<14:22,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sachiko_Kobayashi.jpg

 58%|█████▊    | 3549/6167 [42:21<09:13,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Izumi_Kitta.jpg

 58%|█████▊    | 3551/6167 [42:22<10:01,  4.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kie_Kitano.jpg

 58%|█████▊    | 3552/6167 [42:22<10:38,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eri_Kitamura.jpg

 58%|█████▊    | 3554/6167 [42:22<09:20,  4.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saburō_Kitajima.jpg

 58%|█████▊    | 3555/6167 [42:24<18:42,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rie_Kitahara.jpg

 58%|█████▊    | 3556/6167 [42:25<21:45,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nana_Kitade.jpg

 58%|█████▊    | 3558/6167 [42:25<19:32,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukina_Kinoshita.jpg

 58%|█████▊    | 3560/6167 [42:26<14:54,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaela_Kimura.jpg

 58%|█████▊    | 3561/6167 [42:26<15:50,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoshino_Kimura.jpg

 58%|█████▊    | 3564/6167 [42:26<10:26,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moa_Kikuchi.jpg

 58%|█████▊    | 3565/6167 [42:27<12:30,  3.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/You_Kikkawa.jpg

 58%|█████▊    | 3569/6167 [42:27<08:58,  4.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kazu_Makino.jpg

 58%|█████▊    | 3570/6167 [42:28<09:53,  4.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fujii_Kaze.jpg

 58%|█████▊    | 3573/6167 [42:28<07:27,  5.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Kawashima.jpg

 58%|█████▊    | 3574/6167 [42:29<10:03,  4.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marina_Kawano.jpg

 58%|█████▊    | 3576/6167 [42:29<11:34,  3.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaori_Kawamura.jpg

 58%|█████▊    | 3578/6167 [42:29<09:59,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mieko_Kawakami.jpg

 58%|█████▊    | 3580/6167 [42:30<08:38,  4.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kazumi_Kawai.jpg

 58%|█████▊    | 3583/6167 [42:30<06:40,  6.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rena_Kato.jpg

 58%|█████▊    | 3585/6167 [42:30<06:17,  6.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mami_Kawada.jpg

 58%|█████▊    | 3590/6167 [42:31<05:07,  8.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tokiko_Kato.jpg

 58%|█████▊    | 3592/6167 [42:31<05:23,  7.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miliyah_Kato.jpg

 58%|█████▊    | 3593/6167 [42:32<10:38,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kazuhiko_Katō.jpg

 58%|█████▊    | 3597/6167 [42:33<09:54,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuki_Kashiwagi.jpg

 58%|█████▊    | 3601/6167 [42:33<08:29,  5.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomomi_Kasai.jpg

 58%|█████▊    | 3603/6167 [42:34<08:28,  5.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shizuko_Kasagi.jpg

 58%|█████▊    | 3605/6167 [42:34<07:47,  5.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoko_Kanno.jpg

 58%|█████▊    | 3606/6167 [42:35<09:16,  4.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miho_Kanno.jpg

 58%|█████▊    | 3607/6167 [42:35<09:25,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayaka_Kanda.jpg

 59%|█████▊    | 3608/6167 [42:35<12:24,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mika_Kanai.jpg

 59%|█████▊    | 3610/6167 [42:36<09:55,  4.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mone_Kamishiraishi.jpg

 59%|█████▊    | 3611/6167 [42:36<10:07,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eri_Kamei.jpg

 59%|█████▊    | 3616/6167 [42:36<05:24,  7.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Kago.jpg

 59%|█████▊    | 3617/6167 [42:36<06:12,  6.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jun_Matsumoto.jpg

 59%|█████▉    | 3625/6167 [42:37<04:03, 10.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karen_Iwata.jpg

 59%|█████▉    | 3629/6167 [42:37<04:27,  9.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Junko_Iwao.jpg

 59%|█████▉    | 3631/6167 [42:38<05:18,  7.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yukiko_Iwai.jpg

 59%|█████▉    | 3632/6167 [42:39<08:32,  4.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Itsuki.jpg

 59%|█████▉    | 3633/6167 [42:39<09:29,  4.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/ITSUKA.jpg

 59%|█████▉    | 3634/6167 [42:39<10:07,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hiroshi_Itsuki.jpg

 59%|█████▉    | 3635/6167 [42:40<11:40,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuna_Ito.jpg

 59%|█████▉    | 3639/6167 [42:40<07:38,  5.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanako_Itō.jpg

 59%|█████▉    | 3640/6167 [42:40<08:35,  4.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanae_Itō.jpg

 59%|█████▉    | 3641/6167 [42:41<09:20,  4.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomomi_Itano.jpg

 59%|█████▉    | 3644/6167 [42:42<09:58,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maiha_Ishimura.jpg

 59%|█████▉    | 3645/6167 [42:42<11:09,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Satoko_Ishimine.jpg

 59%|█████▉    | 3646/6167 [42:42<11:48,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayuri_Ishikawa.jpg

 59%|█████▉    | 3647/6167 [42:43<16:07,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiaki_Ishikawa.jpg

 59%|█████▉    | 3648/6167 [42:44<19:38,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rika_Ishikawa.jpg

 59%|█████▉    | 3650/6167 [42:44<17:42,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Takeo_Ishii.jpg

 59%|█████▉    | 3651/6167 [42:45<17:35,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aya_Ishiguro.jpg

 59%|█████▉    | 3652/6167 [42:46<21:08,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoko_Ishida.jpg

 59%|█████▉    | 3654/6167 [42:46<14:55,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hikari_Ishida.jpg

 59%|█████▉    | 3656/6167 [42:47<14:15,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayumi_Ishida_(Morning_Musume_member).jpg

 59%|█████▉    | 3657/6167 [42:47<13:47,  3.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayumi_Ishida_(actress).jpg

 59%|█████▉    | 3659/6167 [42:47<10:39,  3.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Iriyama.jpg

 59%|█████▉    | 3663/6167 [42:47<06:44,  6.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kikuko_Inoue.jpg

 59%|█████▉    | 3664/6167 [42:48<07:25,  5.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azumi_Inoue.jpg

 59%|█████▉    | 3669/6167 [42:48<04:35,  9.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eriko_Imai.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Asami_Imai.jpg

 60%|█████▉    | 3671/6167 [42:49<07:08,  5.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erina_Ikuta.jpg

 60%|█████▉    | 3672/6167 [42:49<07:52,  5.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akiko_Ikuina.jpg

 60%|█████▉    | 3673/6167 [42:49<08:24,  4.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Riyoko_Ikeda.jpg

 60%|█████▉    | 3674/6167 [42:50<09:41,  4.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rina_Ikoma.jpg

 60%|█████▉    | 3677/6167 [42:50<09:34,  4.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruna_Iikubo.jpg

 60%|█████▉    | 3678/6167 [42:51<09:48,  4.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mari_Iijima.jpg

 60%|█████▉    | 3681/6167 [42:51<07:15,  5.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ichimaru.jpg

 60%|█████▉    | 3684/6167 [42:51<06:10,  6.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruyo_Ichikawa.jpg

 60%|█████▉    | 3687/6167 [42:51<05:30,  7.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Taro_Ichihara.jpg

 60%|█████▉    | 3689/6167 [42:52<05:52,  7.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hyde.jpg

 60%|█████▉    | 3691/6167 [42:52<06:10,  6.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gen_Hoshino.jpg

 60%|█████▉    | 3695/6167 [42:52<04:29,  9.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Horie.jpg

 60%|█████▉    | 3697/6167 [42:53<06:00,  6.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Risa_Honma.jpg

 60%|█████▉    | 3698/6167 [42:54<10:04,  4.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minako_Honda.jpg

 60%|█████▉    | 3700/6167 [42:54<09:13,  4.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hitomi_Honda.jpg

 60%|██████    | 3704/6167 [42:55<09:50,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mieko_Hirota.jpg

 60%|██████    | 3705/6167 [42:55<10:01,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ryōko_Hirosue.jpg

 60%|██████    | 3707/6167 [42:56<11:33,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aya_Hirano.jpg

 60%|██████    | 3709/6167 [42:56<09:42,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Momo_Hirai.jpg

 60%|██████    | 3710/6167 [42:57<10:08,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayaka_Hirahara.jpg

 60%|██████    | 3717/6167 [42:57<05:00,  8.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noriko_Hidaka.jpg

 60%|██████    | 3725/6167 [42:57<03:11, 12.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saori_Hayami.jpg

 60%|██████    | 3727/6167 [42:58<03:40, 11.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akari_Hayami.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miho_Hatori.jpg

 60%|██████    | 3729/6167 [42:59<06:59,  5.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masato_Hayakawa.jpg

 60%|██████    | 3730/6167 [42:59<07:45,  5.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sawako_Hata.jpg

 61%|██████    | 3733/6167 [42:59<06:39,  6.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kanna_Hashimoto.jpg

 61%|██████    | 3735/6167 [43:00<06:28,  6.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aina_Hashimoto.jpg

 61%|██████    | 3737/6167 [43:00<06:28,  6.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Hashimoto.jpg

 61%|██████    | 3738/6167 [43:00<08:24,  4.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luna_Haruna.jpg

 61%|██████    | 3743/6167 [43:01<05:17,  7.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kana_Hanazawa.jpg

 61%|██████    | 3744/6167 [43:02<08:26,  4.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanayo.jpg

 61%|██████    | 3745/6167 [43:02<08:54,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Megumi_Han.jpg

 61%|██████    | 3746/6167 [43:02<11:10,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayumi_Hamasaki.jpg

 61%|██████    | 3750/6167 [43:03<07:08,  5.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chitose_Hajime.jpg

 61%|██████    | 3751/6167 [43:03<07:49,  5.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mai_Hagiwara.jpg

 61%|██████    | 3752/6167 [43:03<08:05,  4.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halca.jpg

 61%|██████    | 3754/6167 [43:03<06:46,  5.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuki_Goto.jpg

 61%|██████    | 3756/6167 [43:04<06:03,  6.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maki_Goto.jpg

 61%|██████    | 3757/6167 [43:04<07:28,  5.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kumiko_Goto.jpg

 61%|██████    | 3760/6167 [43:04<05:49,  6.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akiko_Futaba.jpg

 61%|██████    | 3763/6167 [43:06<10:19,  3.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mizuki_Fukumura.jpg

 61%|██████    | 3765/6167 [43:06<09:00,  4.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miho_Fukuhara.jpg

 61%|██████    | 3768/6167 [43:06<07:43,  5.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Taeko_Fukao.jpg

 61%|██████    | 3769/6167 [43:07<09:14,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kyoko_Fukada.jpg

 61%|██████    | 3770/6167 [43:07<09:34,  4.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ichirō_Fujiyama.jpg

 61%|██████    | 3771/6167 [43:07<11:02,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoshie_Fujiwara.jpg

 61%|██████    | 3775/6167 [43:08<07:03,  5.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miki_Fujimoto.jpg

 61%|██████    | 3776/6167 [43:09<11:53,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lena_Fujii.jpg

 61%|██████    | 3777/6167 [43:09<11:49,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kano_Fujihira.jpg

 61%|██████▏   | 3778/6167 [43:09<12:04,  3.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karen_Fujii.jpg

 61%|██████▏   | 3779/6167 [43:10<11:27,  3.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Keiko_Fuji.jpg

 61%|██████▏   | 3785/6167 [43:10<05:17,  7.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chiemi_Eri.jpg

 61%|██████▏   | 3787/6167 [43:11<07:14,  5.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emi_Maria.jpg

 61%|██████▏   | 3788/6167 [43:11<08:04,  4.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Enako.jpg

 61%|██████▏   | 3789/6167 [43:11<08:50,  4.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elisa.jpg

 61%|██████▏   | 3790/6167 [43:11<09:40,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dean_Fujioka.jpg

 62%|██████▏   | 3793/6167 [43:12<07:03,  5.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leah_Dizon.jpg

 62%|██████▏   | 3795/6167 [43:12<06:24,  6.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Crystal_Kay.jpg

 62%|██████▏   | 3796/6167 [43:13<09:17,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coppé.jpg

 62%|██████▏   | 3797/6167 [43:13<14:03,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cocco.jpg

 62%|██████▏   | 3800/6167 [43:14<09:01,  4.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuri_Chinen.jpg

 62%|██████▏   | 3801/6167 [43:14<10:39,  3.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minori_Chihara.jpg

 62%|██████▏   | 3808/6167 [43:14<04:54,  8.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chara.jpg

 62%|██████▏   | 3811/6167 [43:15<04:28,  8.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bonnie_Pink.jpg

 62%|██████▏   | 3813/6167 [43:15<06:18,  6.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bird.jpg

 62%|██████▏   | 3814/6167 [43:16<07:39,  5.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beni.jpg

 62%|██████▏   | 3819/6167 [43:16<05:04,  7.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haruka_Ayase.jpg

 62%|██████▏   | 3823/6167 [43:16<04:32,  8.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayaka.jpg

 62%|██████▏   | 3826/6167 [43:17<04:44,  8.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Asca.jpg

 62%|██████▏   | 3827/6167 [43:17<05:16,  7.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noriko_Awaya.jpg

 62%|██████▏   | 3829/6167 [43:17<05:41,  6.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kana_Asumi.jpg

 62%|██████▏   | 3830/6167 [43:18<07:00,  5.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natsuko_Aso.jpg

 62%|██████▏   | 3831/6167 [43:18<08:04,  4.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mana_Ashida.jpg

 62%|██████▏   | 3836/6167 [43:19<05:05,  7.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuma_Asami.jpg

 62%|██████▏   | 3837/6167 [43:20<10:09,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maki_Asakawa.jpg

 62%|██████▏   | 3840/6167 [43:20<07:24,  5.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miyoko_Asada.jpg

 62%|██████▏   | 3841/6167 [43:20<09:54,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Momoka_Ariyasu.jpg

 62%|██████▏   | 3842/6167 [43:21<09:58,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsugumi_Aritomo.jpg

 62%|██████▏   | 3845/6167 [43:21<09:32,  4.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aramary.jpg

 62%|██████▏   | 3849/6167 [43:22<06:25,  6.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yui_Aragaki.jpg

 62%|██████▏   | 3854/6167 [43:22<04:37,  8.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sola_Aoi.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Aoki.jpg

 63%|██████▎   | 3856/6167 [43:25<14:17,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mina_Aoe.jpg

 63%|██████▎   | 3857/6167 [43:25<13:50,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anza.jpg

 63%|██████▎   | 3858/6167 [43:25<13:06,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anri.jpg

 63%|██████▎   | 3865/6167 [43:26<06:03,  6.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Namie_Amuro.jpg

 63%|██████▎   | 3872/6167 [43:26<04:08,  9.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akino.jpg

 63%|██████▎   | 3874/6167 [43:26<04:18,  8.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sayaka_Akimoto.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Masafumi_Akikawa.jpg

 63%|██████▎   | 3876/6167 [43:28<10:21,  3.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angela_Aki.jpg

 63%|██████▎   | 3883/6167 [43:29<06:37,  5.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/AiRI.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rina_Aiuchi.jpg

 63%|██████▎   | 3885/6167 [43:29<06:58,  5.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aina_the_End.jpg

 63%|██████▎   | 3886/6167 [43:29<07:05,  5.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aimi.jpg

 63%|██████▎   | 3888/6167 [43:30<07:32,  5.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aimer.jpg

 63%|██████▎   | 3890/6167 [43:30<07:11,  5.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuzuki_Aikawa.jpg

 63%|██████▎   | 3891/6167 [43:31<09:58,  3.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nanase_Aikawa.jpg

 63%|██████▎   | 3892/6167 [43:31<10:08,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai_Shinozaki.jpg

 63%|██████▎   | 3895/6167 [43:31<07:08,  5.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ai.jpg

 63%|██████▎   | 3897/6167 [43:32<07:03,  5.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ado.jpg

 63%|██████▎   | 3898/6167 [43:32<07:55,  4.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yumi_Adachi.jpg

 63%|██████▎   | 3900/6167 [43:32<06:54,  5.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natsumi_Abe.jpg

 63%|██████▎   | 3904/6167 [43:33<06:07,  6.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pari_Zanganeh.jpg

 63%|██████▎   | 3905/6167 [43:33<08:46,  4.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davood_Younesi.jpg

 63%|██████▎   | 3906/6167 [43:34<09:12,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohsen_Yeganeh.jpg

 63%|██████▎   | 3907/6167 [43:35<13:54,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reza_Yazdani.jpg

 63%|██████▎   | 3908/6167 [43:35<15:35,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mehdi_Yarrahi.jpg

 63%|██████▎   | 3909/6167 [43:36<15:02,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viguen.jpg

 63%|██████▎   | 3910/6167 [43:36<15:07,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kourosh_Yaghmaei.jpg

 63%|██████▎   | 3911/6167 [43:37<17:48,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yas.jpg

 63%|██████▎   | 3912/6167 [43:37<22:02,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monir_Vakili.jpg

 63%|██████▎   | 3914/6167 [43:38<18:24,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amir_Tataloo.jpg

 63%|██████▎   | 3915/6167 [43:39<19:43,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alireza_Talischi.jpg

 63%|██████▎   | 3916/6167 [43:39<21:01,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Homayoun_Shajarian.jpg

 64%|██████▎   | 3917/6167 [43:40<23:34,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reza_Sadeghi.jpg

 64%|██████▎   | 3918/6167 [43:41<20:29,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toomaj_Salehi.jpg

 64%|██████▎   | 3919/6167 [43:42<27:31,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Siavash_Shams.jpg

 64%|██████▎   | 3920/6167 [43:43<28:32,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Salome_MC.jpg

 64%|██████▎   | 3921/6167 [43:43<25:35,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shahram_Shabpareh.jpg

 64%|██████▎   | 3922/6167 [43:44<25:26,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shakila.jpg

 64%|██████▎   | 3923/6167 [43:44<24:41,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sattar.jpg

 64%|██████▎   | 3924/6167 [43:45<25:28,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ezzat_Rouhbakhsh.jpg

 64%|██████▎   | 3925/6167 [43:46<25:38,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Reza_Rooygari.jpg

 64%|██████▎   | 3927/6167 [43:47<20:33,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Behzad_Ranjbaran.jpg

 64%|██████▎   | 3930/6167 [43:47<15:03,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pooran.jpg

 64%|██████▎   | 3931/6167 [43:48<16:30,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kian_Pourtorab.jpg

 64%|██████▍   | 3932/6167 [43:49<18:16,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Morteza_Pashaei.jpg

 64%|██████▍   | 3933/6167 [43:50<21:22,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Giti_Pashaei.jpg

 64%|██████▍   | 3934/6167 [43:50<22:59,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khatereh_Parvaneh.jpg

 64%|██████▍   | 3935/6167 [43:51<22:39,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Parisa.jpg

 64%|██████▍   | 3936/6167 [43:52<24:08,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ali_Pahlavan.jpg

 64%|██████▍   | 3937/6167 [43:52<23:22,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anousha_Nazari.jpg

 64%|██████▍   | 3938/6167 [43:53<24:12,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shahin_Najafi.jpg

 64%|██████▍   | 3939/6167 [43:53<23:00,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bijan_Mortazavi.jpg

 64%|██████▍   | 3940/6167 [43:54<21:31,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohammad_Motamedi.jpg

 64%|██████▍   | 3941/6167 [43:54<20:54,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Morteza.jpg

 64%|██████▍   | 3942/6167 [43:55<19:09,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohammad_Reza_Shajarian.jpg

 64%|██████▍   | 3943/6167 [43:56<21:00,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moein.jpg

 64%|██████▍   | 3944/6167 [43:56<17:41,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Farhad_Mehrad.jpg

 64%|██████▍   | 3945/6167 [43:56<17:03,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mahasti.jpg

 64%|██████▍   | 3946/6167 [43:57<20:14,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mansour.jpg

 64%|██████▍   | 3947/6167 [43:57<17:50,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mahsa_Vahdat.jpg

 64%|██████▍   | 3948/6167 [43:58<21:38,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ali_Lohrasbi.jpg

 64%|██████▍   | 3949/6167 [43:58<18:26,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Soroush_Lashkary.jpg

 64%|██████▍   | 3950/6167 [43:59<16:13,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laleh.jpg

 64%|██████▍   | 3951/6167 [43:59<19:24,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shahrum_Kashani.jpg

 64%|██████▍   | 3953/6167 [44:00<15:00,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sirvan_Khosravi.jpg

 64%|██████▍   | 3955/6167 [44:01<13:54,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bijan_Kamkar.jpg

 64%|██████▍   | 3956/6167 [44:01<15:44,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mozhdah_Jamalzadah.jpg

 64%|██████▍   | 3957/6167 [44:02<16:34,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Babak_Jahanbakhsh.jpg

 64%|██████▍   | 3958/6167 [44:04<28:42,  1.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iraj_Rahmanpour.jpg

 64%|██████▍   | 3959/6167 [44:04<29:29,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iraj.jpg

 64%|██████▍   | 3960/6167 [44:05<26:38,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shervin_Hajipour.jpg

 64%|██████▍   | 3961/6167 [44:06<26:56,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hassan_Zirak.jpg

 64%|██████▍   | 3962/6167 [44:06<22:20,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hayedeh.jpg

 64%|██████▍   | 3963/6167 [44:06<18:37,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Habib.jpg

 64%|██████▍   | 3964/6167 [44:07<18:08,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shusha_Guppy.jpg

 64%|██████▍   | 3965/6167 [44:07<20:56,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Googoosh.jpg

 64%|██████▍   | 3966/6167 [44:08<24:37,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alireza_Ghorbani.jpg

 64%|██████▍   | 3967/6167 [44:09<23:06,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Siavash_Ghomayshi.jpg

 64%|██████▍   | 3968/6167 [44:09<19:45,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leila_Forouhar.jpg

 64%|██████▍   | 3969/6167 [44:10<21:09,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohammad_Esfahani.jpg

 64%|██████▍   | 3970/6167 [44:10<18:24,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Farzad_Farzin.jpg

 64%|██████▍   | 3971/6167 [44:11<18:50,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elaheh.jpg

 64%|██████▍   | 3972/6167 [44:12<23:19,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Erfan.jpg

 64%|██████▍   | 3973/6167 [44:13<25:49,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ali_Reza_Eftekhari.jpg

 64%|██████▍   | 3974/6167 [44:13<27:01,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohsen_Ebrahimzadeh.jpg

 64%|██████▍   | 3975/6167 [44:14<21:53,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ebi.jpg

 64%|██████▍   | 3976/6167 [44:14<23:00,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Donya_Dadrasan.jpg

 64%|██████▍   | 3977/6167 [44:16<36:56,  1.01s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dariush.jpg

 65%|██████▍   | 3979/6167 [44:17<26:47,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mohsen_Chavoshi.jpg

 65%|██████▍   | 3980/6167 [44:18<26:50,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sima_Bina.jpg

 65%|██████▍   | 3982/6167 [44:18<20:21,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Abdi_Behravanfar.jpg

 65%|██████▍   | 3983/6167 [44:19<19:41,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Barbad.jpg

 65%|██████▍   | 3984/6167 [44:20<21:05,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gholam_Hossein_Banan.jpg

 65%|██████▍   | 3985/6167 [44:20<21:03,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bahram.jpg

 65%|██████▍   | 3986/6167 [44:20<17:43,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davood_Azad.jpg

 65%|██████▍   | 3987/6167 [44:22<24:28,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benyamin_Bahadori.jpg

 65%|██████▍   | 3988/6167 [44:22<24:31,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azad.jpg

 65%|██████▍   | 3989/6167 [44:23<23:33,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Faramarz_Assef.jpg

 65%|██████▍   | 3990/6167 [44:24<27:04,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Faramarz_Aslani.jpg

 65%|██████▍   | 3991/6167 [44:25<32:40,  1.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amir_Hossein_Arman.jpg

 65%|██████▍   | 3992/6167 [44:25<25:59,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arash.jpg

 65%|██████▍   | 3993/6167 [44:26<26:00,  1.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andy.jpg

 65%|██████▍   | 3994/6167 [44:27<25:50,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ehsan_Khajeh_Amiri.jpg

 65%|██████▍   | 3996/6167 [44:27<18:07,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azam_Ali.jpg

 65%|██████▍   | 3997/6167 [44:28<19:17,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Majid_Akhshabi.jpg

 65%|██████▍   | 3998/6167 [44:28<16:42,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sahar_Ajdamsani.jpg

 65%|██████▍   | 3999/6167 [44:29<17:57,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nematollah_Aghasi.jpg

 65%|██████▍   | 4000/6167 [44:29<17:57,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Morteza_Ahmadi.jpg

 65%|██████▍   | 4001/6167 [44:30<18:50,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nazanin_Afshin-Jam.jpg

 65%|██████▍   | 4003/6167 [44:30<14:19,  2.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ali_Abdolmaleki.jpg

 65%|██████▍   | 4006/6167 [44:32<15:51,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaveh_Afagh.jpg

 65%|██████▍   | 4007/6167 [44:32<14:27,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yura_Yunita.jpg

 65%|██████▍   | 4008/6167 [44:33<18:03,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuni_Shara.jpg

 65%|██████▌   | 4009/6167 [44:34<20:27,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Waljinah.jpg

 65%|██████▌   | 4010/6167 [44:34<18:07,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wafda_Saifan.jpg

 65%|██████▌   | 4012/6167 [44:34<13:27,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vidi_Aldiano.jpg

 65%|██████▌   | 4013/6167 [44:35<12:19,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tulus.jpg

 65%|██████▌   | 4014/6167 [44:35<12:00,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Titiek_Puspa.jpg

 65%|██████▌   | 4015/6167 [44:36<16:19,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miss_World_1983.jpg

 65%|██████▌   | 4016/6167 [44:36<16:22,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Titi_DJ.jpg

 65%|██████▌   | 4018/6167 [44:37<15:18,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indonesian_Idol.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Terryana_Fatiah.jpg

 65%|██████▌   | 4019/6167 [44:38<19:04,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tiara_Andini.jpg

 65%|██████▌   | 4020/6167 [44:38<18:32,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tantowi_Yahya.jpg

 65%|██████▌   | 4021/6167 [44:39<15:59,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syahrini.jpg

 65%|██████▌   | 4023/6167 [44:39<11:08,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/New_Wave.jpg

 65%|██████▌   | 4024/6167 [44:39<12:18,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sherina_Munaf.jpg

 65%|██████▌   | 4025/6167 [44:40<11:54,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sandhy_Sondoro.jpg

 65%|██████▌   | 4026/6167 [44:40<11:38,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rich_Brian.jpg

 65%|██████▌   | 4027/6167 [44:40<11:10,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raisa_Andriana.jpg

 65%|██████▌   | 4028/6167 [44:41<14:34,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruth_Sahanaya.jpg

 65%|██████▌   | 4029/6167 [44:41<13:30,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rossa.jpg

 65%|██████▌   | 4030/6167 [44:42<13:08,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sule.jpg

 65%|██████▌   | 4031/6167 [44:42<11:47,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rizky_Febian.jpg

 65%|██████▌   | 4032/6167 [44:43<22:43,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indonesian_Idol.jpg

 65%|██████▌   | 4034/6167 [44:44<14:48,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rhoma_Irama.jpg

 65%|██████▌   | 4036/6167 [44:44<10:39,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rainych.jpg

 65%|██████▌   | 4038/6167 [44:44<10:22,  3.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pane_Irma.jpg

 65%|██████▌   | 4039/6167 [44:45<14:19,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pinkan_Mambo.jpg

 66%|██████▌   | 4040/6167 [44:45<13:23,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Once.jpg

 66%|██████▌   | 4043/6167 [44:47<14:06,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Niki.jpg

 66%|██████▌   | 4045/6167 [44:47<11:05,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nike_Ardilla.jpg

 66%|██████▌   | 4046/6167 [44:47<12:27,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Naura_Ayu.jpg

 66%|██████▌   | 4047/6167 [44:48<12:40,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nafa_Urbach.jpg

 66%|██████▌   | 4048/6167 [44:48<14:00,  2.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mahalini_Raharja.jpg

 66%|██████▌   | 4050/6167 [44:49<10:37,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mimi_Mariani.jpg

 66%|██████▌   | 4051/6167 [44:49<11:14,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indonesian_Idol.jpg

 66%|██████▌   | 4052/6167 [44:49<10:39,  3.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mulan_Jameela.jpg

 66%|██████▌   | 4054/6167 [44:50<08:36,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Melly_Goeslaw.jpg

 66%|██████▌   | 4055/6167 [44:50<12:14,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Melky_Goeslaw.jpg

 66%|██████▌   | 4057/6167 [44:51<09:19,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maudy_Ayunda.jpg

 66%|██████▌   | 4058/6167 [44:51<09:26,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lilis_Suryani.jpg

 66%|██████▌   | 4059/6167 [44:51<09:31,  3.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lyodra_Ginting.jpg

 66%|██████▌   | 4060/6167 [44:52<13:49,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julia_Perez.jpg

 66%|██████▌   | 4062/6167 [44:52<09:59,  3.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jockie_Soerjoprajogo.jpg

 66%|██████▌   | 4063/6167 [44:52<09:57,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iwan_Fals.jpg

 66%|██████▌   | 4064/6167 [44:53<09:51,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Isyana_Sarasvati.jpg

 66%|██████▌   | 4065/6167 [44:53<09:36,  3.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iwa_K.jpg

 66%|██████▌   | 4067/6167 [44:53<07:25,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dangdut.jpg

 66%|██████▌   | 4068/6167 [44:54<08:46,  3.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inul_Daratista.jpg

 66%|██████▌   | 4070/6167 [44:54<07:10,  4.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indra_Lesmana.jpg

 66%|██████▌   | 4072/6167 [44:55<08:15,  4.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Harry_Roesli.jpg

 66%|██████▌   | 4073/6167 [44:56<15:50,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gombloh.jpg

 66%|██████▌   | 4074/6167 [44:56<14:12,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gita_Gutawa.jpg

 66%|██████▌   | 4075/6167 [44:56<13:05,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Glenn_Fredly.jpg

 66%|██████▌   | 4076/6167 [44:57<15:05,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Freya_Jayawardana.jpg

 66%|██████▌   | 4078/6167 [44:57<10:52,  3.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fariz_RM.jpg

 66%|██████▌   | 4079/6167 [44:58<12:27,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/X_Factor_Indonesia.jpg

 66%|██████▌   | 4080/6167 [44:59<21:32,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fatin_Shidqia.jpg

 66%|██████▌   | 4082/6167 [45:00<17:14,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eros_Djarot.jpg

 66%|██████▌   | 4084/6167 [45:00<12:40,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ebiet_G_Ade.jpg

 66%|██████▌   | 4085/6167 [45:00<12:09,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Didi_Kempot.jpg

 66%|██████▋   | 4086/6167 [45:01<14:25,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dewi_Sandra.jpg

 66%|██████▋   | 4088/6167 [45:01<11:01,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dewi_Persik.jpg

 66%|██████▋   | 4089/6167 [45:02<11:37,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dewi_Lestari.jpg

 66%|██████▋   | 4090/6167 [45:02<11:48,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indonesian_Idol.jpg

 66%|██████▋   | 4091/6167 [45:03<16:42,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Citra_Scholastika.jpg

 66%|██████▋   | 4093/6167 [45:03<13:08,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cinta_Laura.jpg

 66%|██████▋   | 4094/6167 [45:04<14:30,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chrisye.jpg

 66%|██████▋   | 4095/6167 [45:04<13:09,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camelia_Malik.jpg

 66%|██████▋   | 4096/6167 [45:05<12:51,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bunga_Citra_Lestari.jpg

 66%|██████▋   | 4098/6167 [45:06<17:51,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Brian_Imanuel.jpg

 66%|██████▋   | 4099/6167 [45:06<15:46,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Benyamin_Sueb.jpg

 66%|██████▋   | 4100/6167 [45:07<18:32,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ayu_Ting_Ting.jpg

 66%|██████▋   | 4101/6167 [45:07<16:17,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dewa_19.jpg

 67%|██████▋   | 4102/6167 [45:08<14:11,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ari_Lasso.jpg

 67%|██████▋   | 4103/6167 [45:08<15:24,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anggun.jpg

 67%|██████▋   | 4105/6167 [45:09<11:03,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ahmad_Dhani.jpg

 67%|██████▋   | 4106/6167 [45:09<10:40,  3.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ahmad_Albar.jpg

 67%|██████▋   | 4107/6167 [45:09<10:34,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Acha_Septriasa.jpg

 67%|██████▋   | 4108/6167 [45:10<12:35,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Afgan.jpg

 67%|██████▋   | 4110/6167 [45:10<09:24,  3.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Agnez_Mo.jpg

 67%|██████▋   | 4112/6167 [45:12<18:08,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rohit_John_Chhetri.jpg

 67%|██████▋   | 4113/6167 [45:13<19:43,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Babina_Bhattarai.jpg

 67%|██████▋   | 4114/6167 [45:13<20:43,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Visan_Yonjan.jpg

 67%|██████▋   | 4115/6167 [45:14<18:01,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Madeira.jpg

 67%|██████▋   | 4116/6167 [45:14<16:05,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/A_Portuguesa.jpg

 67%|██████▋   | 4117/6167 [45:14<15:01,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Šašić.jpg

 67%|██████▋   | 4118/6167 [45:15<13:44,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Samardžić.jpg

 67%|██████▋   | 4119/6167 [45:15<14:10,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Joksimović.jpg

 67%|██████▋   | 4120/6167 [45:15<12:16,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Bebek.jpg

 67%|██████▋   | 4122/6167 [45:15<08:54,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šemsa_Suljaković.jpg

 67%|██████▋   | 4124/6167 [45:16<09:35,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šaban_Šaulić.jpg

 67%|██████▋   | 4127/6167 [45:16<06:42,  5.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zoran_Lesendrić.jpg

 67%|██████▋   | 4128/6167 [45:18<15:32,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaim_Imamović.jpg

 67%|██████▋   | 4129/6167 [45:18<14:33,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zdravko_Čolić.jpg

 67%|██████▋   | 4130/6167 [45:19<14:10,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yiannis_Parios.jpg

 67%|██████▋   | 4131/6167 [45:19<12:58,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlado_Georgiev.jpg

 67%|██████▋   | 4132/6167 [45:19<12:43,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viki.jpg

 67%|██████▋   | 4133/6167 [45:20<12:20,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesna_Zmijanac.jpg

 67%|██████▋   | 4135/6167 [45:21<12:55,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vasilis_Karras.jpg

 67%|██████▋   | 4136/6167 [45:21<12:35,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toše_Proeski.jpg

 67%|██████▋   | 4137/6167 [45:21<11:27,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Cetinski.jpg

 67%|██████▋   | 4138/6167 [45:21<10:26,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tonči_Huljić.jpg

 67%|██████▋   | 4139/6167 [45:22<09:41,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toma_Zdravković.jpg

 67%|██████▋   | 4140/6167 [45:22<09:36,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tifa.jpg

 67%|██████▋   | 4141/6167 [45:22<09:18,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tijana_Dapčević.jpg

 67%|██████▋   | 4142/6167 [45:22<09:05,  3.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tereza_Kesovija.jpg

 67%|██████▋   | 4143/6167 [45:23<09:20,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Ribič.jpg

 67%|██████▋   | 4144/6167 [45:23<09:59,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Savić.jpg

 67%|██████▋   | 4145/6167 [45:23<09:58,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Todevska.jpg

 67%|██████▋   | 4147/6167 [45:24<07:27,  4.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stoja.jpg

 67%|██████▋   | 4148/6167 [45:24<08:11,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofi_Marinova.jpg

 67%|██████▋   | 4149/6167 [45:25<19:49,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Snežana_Đurišić.jpg

 67%|██████▋   | 4150/6167 [45:26<17:23,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slađana_Milošević.jpg

 67%|██████▋   | 4152/6167 [45:26<12:27,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvana_Armenulić.jpg

 67%|██████▋   | 4153/6167 [45:27<12:43,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina.jpg

 67%|██████▋   | 4154/6167 [45:28<22:07,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sertab_Erener.jpg

 67%|██████▋   | 4155/6167 [45:28<18:54,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergej_Ćetković.jpg

 67%|██████▋   | 4156/6167 [45:29<16:22,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serdar_Ortaç.jpg

 67%|██████▋   | 4157/6167 [45:29<14:31,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Bajrami.jpg

 67%|██████▋   | 4158/6167 [45:29<12:40,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seka_Aleksić.jpg

 67%|██████▋   | 4159/6167 [45:29<12:06,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sejo_Sexon.jpg

 67%|██████▋   | 4160/6167 [45:30<11:22,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sead_Lipovača.jpg

 67%|██████▋   | 4161/6167 [45:30<10:27,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Matić.jpg

 67%|██████▋   | 4162/6167 [45:30<11:45,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Lošić.jpg

 68%|██████▊   | 4163/6167 [45:31<14:22,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Kovačević.jpg

 68%|██████▊   | 4164/6167 [45:31<12:28,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Jo.jpg

 68%|██████▊   | 4165/6167 [45:32<11:32,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Vučić.jpg

 68%|██████▊   | 4166/6167 [45:32<10:41,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Safet_Isović.jpg

 68%|██████▊   | 4167/6167 [45:32<10:32,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Ora.jpg

 68%|██████▊   | 4168/6167 [45:33<20:55,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rayna.jpg

 68%|██████▊   | 4169/6167 [45:34<16:57,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakis_Rouvas.jpg

 68%|██████▊   | 4170/6167 [45:34<14:32,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rambo_Amadeus.jpg

 68%|██████▊   | 4172/6167 [45:35<17:46,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preslava.jpg

 68%|██████▊   | 4173/6167 [45:36<15:25,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Živković_Tozovac.jpg

 68%|██████▊   | 4174/6167 [45:36<14:35,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Gojković-Cune.jpg

 68%|██████▊   | 4175/6167 [45:36<13:57,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Poli_Genova.jpg

 68%|██████▊   | 4176/6167 [45:37<16:04,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paola.jpg

 68%|██████▊   | 4178/6167 [45:37<11:02,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Dragojević.jpg

 68%|██████▊   | 4179/6167 [45:38<11:34,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nora_Istrefi.jpg

 68%|██████▊   | 4180/6167 [45:38<11:03,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noizy.jpg

 68%|██████▊   | 4182/6167 [45:38<09:02,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Badrić.jpg

 68%|██████▊   | 4183/6167 [45:39<09:08,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikos_Vertis.jpg

 68%|██████▊   | 4185/6167 [45:39<08:14,  4.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikola_Rokvić.jpg

 68%|██████▊   | 4186/6167 [45:39<09:11,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nexhmije_Pagarusha.jpg

 68%|██████▊   | 4187/6167 [45:40<09:37,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neno_Belan.jpg

 68%|██████▊   | 4188/6167 [45:40<09:13,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nevena_Božović.jpg

 68%|██████▊   | 4189/6167 [45:40<09:21,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nele_Karajlić.jpg

 68%|██████▊   | 4191/6167 [45:41<07:33,  4.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neda_Ukraden.jpg

 68%|██████▊   | 4192/6167 [45:41<08:00,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nataša_Bekvalac.jpg

 68%|██████▊   | 4193/6167 [45:41<07:54,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natasa_Theodoridou.jpg

 68%|██████▊   | 4194/6167 [45:41<09:06,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Topčagić.jpg

 68%|██████▊   | 4195/6167 [45:42<08:57,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Mamula.jpg

 68%|██████▊   | 4199/6167 [45:42<05:03,  6.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miša_Aleksić.jpg

 68%|██████▊   | 4201/6167 [45:42<05:04,  6.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Ilić.jpg

 68%|██████▊   | 4204/6167 [45:43<04:09,  7.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mile_Kitić.jpg

 68%|██████▊   | 4205/6167 [45:43<06:29,  5.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milan_Stanković.jpg

 68%|██████▊   | 4207/6167 [45:43<05:53,  5.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Merima_Njegomir.jpg

 68%|██████▊   | 4209/6167 [45:44<06:24,  5.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Berović.jpg

 68%|██████▊   | 4210/6167 [45:44<07:40,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Šuput.jpg

 68%|██████▊   | 4211/6167 [45:45<07:45,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Massimo_Savić.jpg

 68%|██████▊   | 4212/6167 [45:45<07:32,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marta_Savić.jpg

 68%|██████▊   | 4213/6167 [45:46<16:46,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Kon.jpg

 68%|██████▊   | 4214/6167 [45:46<14:57,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marinella.jpg

 68%|██████▊   | 4215/6167 [45:47<14:20,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marija_Šerifović.jpg

 68%|██████▊   | 4216/6167 [45:47<12:53,  2.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malina.jpg

 68%|██████▊   | 4219/6167 [45:48<07:52,  4.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Elena_Kyriakou.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Magnifico.jpg

 68%|██████▊   | 4220/6167 [45:48<08:36,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luke_Black.jpg

 68%|██████▊   | 4222/6167 [45:48<07:20,  4.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Brena.jpg

 68%|██████▊   | 4223/6167 [45:49<07:28,  4.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Lukić.jpg

 68%|██████▊   | 4224/6167 [45:49<07:52,  4.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lefteris_Pantazis.jpg

 69%|██████▊   | 4225/6167 [45:49<08:19,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kornelije_Kovač.jpg

 69%|██████▊   | 4227/6167 [45:49<06:33,  4.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Konstrakta.jpg

 69%|██████▊   | 4228/6167 [45:50<08:28,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Knez.jpg

 69%|██████▊   | 4230/6167 [45:50<06:57,  4.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kićo_Slabinac.jpg

 69%|██████▊   | 4231/6167 [45:50<07:45,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenan_Doğulu.jpg

 69%|██████▊   | 4232/6167 [45:51<08:02,  4.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Monteno.jpg

 69%|██████▊   | 4233/6167 [45:51<07:46,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katy_Garbi.jpg

 69%|██████▊   | 4234/6167 [45:51<08:14,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamelia.jpg

 69%|██████▊   | 4235/6167 [45:52<08:48,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalomira.jpg

 69%|██████▊   | 4236/6167 [45:52<08:39,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karolina_Gočeva.jpg

 69%|██████▊   | 4237/6167 [45:53<13:01,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaliopi.jpg

 69%|██████▊   | 4238/6167 [45:53<11:50,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurica_Pađen.jpg

 69%|██████▉   | 4240/6167 [45:53<08:43,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josipa_Lisac.jpg

 69%|██████▉   | 4241/6167 [45:53<09:07,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Tomašević.jpg

 69%|██████▉   | 4242/6167 [45:54<09:20,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Karleuša.jpg

 69%|██████▉   | 4244/6167 [45:54<08:33,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Rozga.jpg

 69%|██████▉   | 4245/6167 [45:56<16:52,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Pogorelić.jpg

 69%|██████▉   | 4246/6167 [45:56<15:20,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Houdek.jpg

 69%|██████▉   | 4248/6167 [45:56<10:52,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivi_Adamou.jpg

 69%|██████▉   | 4249/6167 [45:57<10:21,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Zajc.jpg

 69%|██████▉   | 4250/6167 [45:57<09:53,  3.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inva_Mula.jpg

 69%|██████▉   | 4251/6167 [45:57<10:00,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inna.jpg

 69%|██████▉   | 4252/6167 [45:57<09:17,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Radić.jpg

 69%|██████▉   | 4253/6167 [45:58<08:55,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Levak.jpg

 69%|██████▉   | 4254/6167 [45:58<09:14,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilira.jpg

 69%|██████▉   | 4255/6167 [45:58<08:30,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hurricane.jpg

 69%|██████▉   | 4256/6167 [45:59<18:18,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Himzo_Polovina.jpg

 69%|██████▉   | 4257/6167 [46:00<15:47,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helena_Paparizou.jpg

 69%|██████▉   | 4258/6167 [46:00<13:52,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hasiba_Agić.jpg

 69%|██████▉   | 4259/6167 [46:00<12:50,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Džinović.jpg

 69%|██████▉   | 4260/6167 [46:01<11:22,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hari_Varešanović.jpg

 69%|██████▉   | 4261/6167 [46:01<10:21,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halid_Bešlić.jpg

 69%|██████▉   | 4262/6167 [46:01<09:48,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hadise.jpg

 69%|██████▉   | 4263/6167 [46:02<12:57,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Bregović.jpg

 69%|██████▉   | 4264/6167 [46:02<11:23,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gru.jpg

 69%|██████▉   | 4265/6167 [46:03<14:41,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goca_Tržan.jpg

 69%|██████▉   | 4266/6167 [46:03<12:42,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria.jpg

 69%|██████▉   | 4267/6167 [46:04<20:45,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gibonni.jpg

 69%|██████▉   | 4268/6167 [46:05<17:01,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gergana.jpg

 69%|██████▉   | 4269/6167 [46:05<17:41,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Dalaras.jpg

 69%|██████▉   | 4271/6167 [46:05<12:15,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Galena.jpg

 69%|██████▉   | 4274/6167 [46:06<08:21,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fiki.jpg

 69%|██████▉   | 4275/6167 [46:06<08:20,  3.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Era_Istrefi.jpg

 69%|██████▉   | 4276/6167 [46:06<08:27,  3.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esma_Redžepova.jpg

 69%|██████▉   | 4277/6167 [46:07<08:45,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emina_Jahović.jpg

 69%|██████▉   | 4278/6167 [46:08<12:38,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emanuela.jpg

 69%|██████▉   | 4279/6167 [46:08<11:37,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvir_Laković_Laka.jpg

 69%|██████▉   | 4280/6167 [46:08<11:12,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elhaida_Dani.jpg

 69%|██████▉   | 4281/6167 [46:08<10:52,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvana_Gjata.jpg

 69%|██████▉   | 4282/6167 [46:09<10:17,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Risteska.jpg

 69%|██████▉   | 4283/6167 [46:09<13:49,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleni_Foureira.jpg

 69%|██████▉   | 4284/6167 [46:10<12:53,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Maajka.jpg

 69%|██████▉   | 4285/6167 [46:10<11:34,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleftheria_Eleftheriou.jpg

 69%|██████▉   | 4286/6167 [46:10<10:48,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Džej_Ramadanovski.jpg

 70%|██████▉   | 4287/6167 [46:11<11:06,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Đorđe_Balašević.jpg

 70%|██████▉   | 4289/6167 [46:11<07:58,  3.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dua_Lipa.jpg

 70%|██████▉   | 4290/6167 [46:11<08:10,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragana_Mirković.jpg

 70%|██████▉   | 4291/6167 [46:12<08:31,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragan_Kojić_Keba.jpg

 70%|██████▉   | 4293/6167 [46:12<06:53,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doris_Dragović.jpg

 70%|██████▉   | 4294/6167 [46:12<07:11,  4.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Merlin.jpg

 70%|██████▉   | 4295/6167 [46:12<07:14,  4.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Dvornik.jpg

 70%|██████▉   | 4296/6167 [46:13<07:19,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Despina_Vandi.jpg

 70%|██████▉   | 4298/6167 [46:13<06:08,  5.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deen.jpg

 70%|██████▉   | 4299/6167 [46:13<06:54,  4.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davorin_Popović.jpg

 70%|██████▉   | 4300/6167 [46:14<08:04,  3.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darko_Rundek.jpg

 70%|██████▉   | 4302/6167 [46:14<06:34,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danijela_Martinović.jpg

 70%|██████▉   | 4305/6167 [46:14<05:50,  5.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dado_Topić.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dafina_Zeqiri.jpg

 70%|██████▉   | 4308/6167 [46:15<04:34,  6.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coby.jpg

 70%|██████▉   | 4309/6167 [46:15<05:19,  5.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ceca.jpg

 70%|██████▉   | 4310/6167 [46:15<06:50,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Capital_T.jpg

 70%|██████▉   | 4313/6167 [46:16<05:00,  6.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Novković.jpg

 70%|██████▉   | 4315/6167 [46:16<05:16,  5.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bora_Đorđević.jpg

 70%|██████▉   | 4316/6167 [46:16<06:09,  5.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boban_Rajović.jpg

 70%|███████   | 4317/6167 [46:17<06:40,  4.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebi_Dol.jpg

 70%|███████   | 4318/6167 [46:17<08:13,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bleona.jpg

 70%|███████   | 4319/6167 [46:18<09:19,  3.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebe_Rexha.jpg

 70%|███████   | 4320/6167 [46:18<08:58,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beba_Selimović.jpg

 70%|███████   | 4321/6167 [46:18<08:53,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bajaga.jpg

 70%|███████   | 4323/6167 [46:19<08:27,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azis.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Avni_Mula.jpg

 70%|███████   | 4324/6167 [46:19<09:05,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurela_Gaçe.jpg

 70%|███████   | 4325/6167 [46:19<10:21,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arsen_Dedić.jpg

 70%|███████   | 4326/6167 [46:20<13:28,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ardian_Bujupi.jpg

 70%|███████   | 4329/6167 [46:20<07:34,  4.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Vissi.jpg

 70%|███████   | 4330/6167 [46:21<08:04,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Odobescu.jpg

 70%|███████   | 4331/6167 [46:21<08:21,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea.jpg

 70%|███████   | 4333/6167 [46:21<06:49,  4.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bănică.jpg

 70%|███████   | 4334/6167 [46:22<07:00,  4.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Kokić.jpg

 70%|███████   | 4337/6167 [46:23<10:14,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Stan.jpg

 70%|███████   | 4338/6167 [46:23<09:40,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Islamović.jpg

 70%|███████   | 4339/6167 [46:24<10:31,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleksandra_Prijović.jpg

 70%|███████   | 4340/6167 [46:24<09:50,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alban_Skënderaj.jpg

 70%|███████   | 4342/6167 [46:24<07:19,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Rahimovski.jpg

 70%|███████   | 4343/6167 [46:24<07:46,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Sînă.jpg

 70%|███████   | 4345/6167 [46:25<07:48,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aca_Lukas.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aco_Pejović.jpg

 70%|███████   | 4346/6167 [46:25<08:51,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 70%|███████   | 4347/6167 [46:26<09:01,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 71%|███████   | 4349/6167 [46:26<07:11,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 71%|███████   | 4350/6167 [46:26<07:17,  4.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 71%|███████   | 4351/6167 [46:26<07:29,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zeybek.jpg

 71%|███████   | 4353/6167 [46:27<06:00,  5.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oro_(eagle_dance).jpg

 71%|███████   | 4354/6167 [46:27<06:12,  4.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karsilamas.jpg

 71%|███████   | 4355/6167 [46:27<06:33,  4.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Čoček.jpg

 71%|███████   | 4358/6167 [46:28<04:53,  6.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsamiko.jpg

 71%|███████   | 4359/6167 [46:28<05:23,  5.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamzara.jpg

 71%|███████   | 4360/6167 [46:28<06:32,  4.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sousta.jpg

 71%|███████   | 4361/6167 [46:28<07:16,  4.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sirtaki.jpg

 71%|███████   | 4362/6167 [46:29<07:21,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syrtos.jpg

 71%|███████   | 4364/6167 [46:29<06:07,  4.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kolo.jpg

 71%|███████   | 4365/6167 [46:30<08:47,  3.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kochari.jpg

 71%|███████   | 4366/6167 [46:30<08:40,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khigga.jpg

 71%|███████   | 4369/6167 [46:30<05:33,  5.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hora.jpg

 71%|███████   | 4370/6167 [46:30<06:22,  4.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Šašić.jpg

 71%|███████   | 4371/6167 [46:31<06:41,  4.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Samardžić.jpg

 71%|███████   | 4373/6167 [46:31<06:50,  4.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Joksimović.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Bebek.jpg

 71%|███████   | 4375/6167 [46:31<05:37,  5.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šemsa_Suljaković.jpg

 71%|███████   | 4377/6167 [46:32<05:08,  5.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šaban_Šaulić.jpg

 71%|███████   | 4380/6167 [46:32<03:55,  7.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zoran_Lesendrić.jpg

 71%|███████   | 4381/6167 [46:32<04:39,  6.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zdravko_Čolić.jpg

 71%|███████   | 4382/6167 [46:33<08:45,  3.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaim_Imamović.jpg

 71%|███████   | 4383/6167 [46:34<09:54,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yiannis_Parios.jpg

 71%|███████   | 4384/6167 [46:34<09:53,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlado_Georgiev.jpg

 71%|███████   | 4385/6167 [46:34<09:24,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viki.jpg

 71%|███████   | 4386/6167 [46:34<08:56,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesna_Zmijanac.jpg

 71%|███████   | 4388/6167 [46:35<06:31,  4.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vasilis_Karras.jpg

 71%|███████   | 4389/6167 [46:35<09:49,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toše_Proeski.jpg

 71%|███████   | 4390/6167 [46:36<12:46,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tonči_Huljić.jpg

 71%|███████   | 4391/6167 [46:36<11:42,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Cetinski.jpg

 71%|███████   | 4392/6167 [46:37<10:15,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toma_Zdravković.jpg

 71%|███████   | 4393/6167 [46:37<09:57,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tifa.jpg

 71%|███████▏  | 4394/6167 [46:37<09:11,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tijana_Dapčević.jpg

 71%|███████▏  | 4395/6167 [46:37<08:39,  3.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tereza_Kesovija.jpg

 71%|███████▏  | 4396/6167 [46:38<08:31,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Savić.jpg

 71%|███████▏  | 4397/6167 [46:38<07:55,  3.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Ribič.jpg

 71%|███████▏  | 4398/6167 [46:38<07:58,  3.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Todevska.jpg

 71%|███████▏  | 4400/6167 [46:38<06:13,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stoja.jpg

 71%|███████▏  | 4401/6167 [46:39<06:56,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofi_Marinova.jpg

 71%|███████▏  | 4402/6167 [46:39<08:25,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Snežana_Đurišić.jpg

 71%|███████▏  | 4403/6167 [46:40<08:36,  3.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slađana_Milošević.jpg

 71%|███████▏  | 4409/6167 [46:40<03:32,  8.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 72%|███████▏  | 4410/6167 [46:40<04:39,  6.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenia.jpg

 72%|███████▏  | 4411/6167 [46:41<05:42,  5.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serbia.jpg

 72%|███████▏  | 4412/6167 [46:41<06:36,  4.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romania.jpg

 72%|███████▏  | 4413/6167 [46:41<07:11,  4.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/North_Macedonia.jpg

 72%|███████▏  | 4414/6167 [46:41<06:56,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegro.jpg

 72%|███████▏  | 4415/6167 [46:42<07:11,  4.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moldova.jpg

 72%|███████▏  | 4417/6167 [46:42<08:37,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 72%|███████▏  | 4418/6167 [46:43<08:20,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 72%|███████▏  | 4419/6167 [46:43<08:11,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cyprus.jpg

 72%|███████▏  | 4420/6167 [46:43<08:27,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 72%|███████▏  | 4421/6167 [46:44<08:03,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 72%|███████▏  | 4422/6167 [46:44<10:59,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnia_and_Herzegovina.jpg

 72%|███████▏  | 4424/6167 [46:44<07:45,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 72%|███████▏  | 4425/6167 [46:45<07:57,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albania.jpg

 72%|███████▏  | 4426/6167 [46:45<07:50,  3.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yugoslav_pop.jpg

 72%|███████▏  | 4429/6167 [46:45<05:11,  5.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ganga_music.jpg

 72%|███████▏  | 4431/6167 [46:46<04:59,  5.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_brass.jpg

 72%|███████▏  | 4435/6167 [46:46<03:29,  8.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani_music.jpg

 72%|███████▏  | 4436/6167 [46:46<04:04,  7.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rebetiko.jpg

 72%|███████▏  | 4437/6167 [46:46<04:52,  5.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nisiotika.jpg

 72%|███████▏  | 4438/6167 [46:47<05:22,  5.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turbo-folk.jpg

 72%|███████▏  | 4440/6167 [46:47<05:06,  5.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manele.jpg

 72%|███████▏  | 4442/6167 [46:47<05:16,  5.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvana_Armenulić.jpg

 72%|███████▏  | 4443/6167 [46:48<05:42,  5.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina.jpg

 72%|███████▏  | 4444/6167 [46:48<06:22,  4.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sertab_Erener.jpg

 72%|███████▏  | 4445/6167 [46:48<06:29,  4.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergej_Ćetković.jpg

 72%|███████▏  | 4446/6167 [46:48<06:43,  4.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serdar_Ortaç.jpg

 72%|███████▏  | 4447/6167 [46:49<07:06,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Bajrami.jpg

 72%|███████▏  | 4448/6167 [46:49<07:10,  3.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seka_Aleksić.jpg

 72%|███████▏  | 4449/6167 [46:50<10:53,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sejo_Sexon.jpg

 72%|███████▏  | 4450/6167 [46:50<10:33,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sead_Lipovača.jpg

 72%|███████▏  | 4451/6167 [46:50<09:45,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Matić.jpg

 72%|███████▏  | 4452/6167 [46:51<10:07,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Lošić.jpg

 72%|███████▏  | 4453/6167 [46:51<10:05,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Kovačević.jpg

 72%|███████▏  | 4454/6167 [46:51<09:57,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Jo.jpg

 72%|███████▏  | 4455/6167 [46:52<09:05,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Vučić.jpg

 72%|███████▏  | 4456/6167 [46:52<08:54,  3.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakis_Rouvas.jpg

 72%|███████▏  | 4457/6167 [46:52<08:20,  3.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Safet_Isović.jpg

 72%|███████▏  | 4458/6167 [46:53<10:27,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Ora.jpg

 72%|███████▏  | 4459/6167 [46:53<10:17,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rayna.jpg

 72%|███████▏  | 4461/6167 [46:53<07:54,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rambo_Amadeus.jpg

 72%|███████▏  | 4462/6167 [46:55<14:11,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preslava.jpg

 72%|███████▏  | 4463/6167 [46:55<14:57,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Živković_Tozovac.jpg

 72%|███████▏  | 4464/6167 [46:57<20:57,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Gojković-Cune.jpg

 72%|███████▏  | 4465/6167 [46:57<17:13,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Poli_Genova.jpg

 72%|███████▏  | 4466/6167 [46:57<15:06,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paola.jpg

 72%|███████▏  | 4468/6167 [46:57<10:21,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Dragojević.jpg

 72%|███████▏  | 4469/6167 [46:58<10:32,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nora_Istrefi.jpg

 72%|███████▏  | 4470/6167 [46:58<10:17,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noizy.jpg

 73%|███████▎  | 4472/6167 [47:00<14:42,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Badrić.jpg

 73%|███████▎  | 4473/6167 [47:00<13:48,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikos_Vertis.jpg

 73%|███████▎  | 4475/6167 [47:00<10:26,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikola_Rokvić.jpg

 73%|███████▎  | 4476/6167 [47:01<10:15,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nexhmije_Pagarusha.jpg

 73%|███████▎  | 4477/6167 [47:01<09:44,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nevena_Božović.jpg

 73%|███████▎  | 4478/6167 [47:01<09:12,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neno_Belan.jpg

 73%|███████▎  | 4479/6167 [47:02<08:27,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nele_Karajlić.jpg

 73%|███████▎  | 4480/6167 [47:02<08:17,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laïko.jpg

 73%|███████▎  | 4482/6167 [47:02<07:17,  3.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk-pop.jpg

 73%|███████▎  | 4483/6167 [47:03<11:21,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkish.jpg

 73%|███████▎  | 4484/6167 [47:03<10:40,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenian.jpg

 73%|███████▎  | 4486/6167 [47:04<07:43,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romanian.jpg

 73%|███████▎  | 4487/6167 [47:04<08:18,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani.jpg

 73%|███████▎  | 4488/6167 [47:04<07:43,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegrin.jpg

 73%|███████▎  | 4489/6167 [47:05<08:01,  3.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Macedonian.jpg

 73%|███████▎  | 4490/6167 [47:06<18:55,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greek.jpg

 73%|███████▎  | 4491/6167 [47:07<17:07,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatian.jpg

 73%|███████▎  | 4492/6167 [47:07<14:41,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgarian.jpg

 73%|███████▎  | 4493/6167 [47:07<12:31,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnian.jpg

 73%|███████▎  | 4494/6167 [47:08<13:28,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albanian.jpg

 73%|███████▎  | 4495/6167 [47:08<12:42,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk.jpg

 73%|███████▎  | 4500/6167 [47:09<05:26,  5.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Slovenia.jpg

 73%|███████▎  | 4501/6167 [47:09<06:53,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mia_Žnidarič.jpg

 73%|███████▎  | 4502/6167 [47:10<11:59,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nika_Zorjan.jpg

 73%|███████▎  | 4503/6167 [47:11<13:21,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irena_Yebuah_Tiran.jpg

 73%|███████▎  | 4504/6167 [47:12<14:57,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fanchette_Verhunc.jpg

 73%|███████▎  | 4507/6167 [47:12<10:44,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darja_Švajger.jpg

 73%|███████▎  | 4508/6167 [47:13<11:25,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adi_Smolar.jpg

 73%|███████▎  | 4509/6167 [47:13<11:45,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karmen_Stavec.jpg

 73%|███████▎  | 4510/6167 [47:14<13:53,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Soklič.jpg

 73%|███████▎  | 4511/6167 [47:15<14:17,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Klemen_Slakonja.jpg

 73%|███████▎  | 4512/6167 [47:15<14:19,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lea_Sirk.jpg

 73%|███████▎  | 4513/6167 [47:16<15:29,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Majda_Sepe.jpg

 73%|███████▎  | 4514/6167 [47:16<13:21,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anja_Rupel.jpg

 73%|███████▎  | 4516/6167 [47:17<09:15,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Ribič.jpg

 73%|███████▎  | 4517/6167 [47:17<11:03,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vili_Resnik.jpg

 73%|███████▎  | 4518/6167 [47:18<11:59,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Regina.jpg

 73%|███████▎  | 4520/6167 [47:18<08:38,  3.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raiven.jpg

 73%|███████▎  | 4521/6167 [47:18<08:45,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neda_Ukraden.jpg

 73%|███████▎  | 4522/6167 [47:19<08:28,  3.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nataša_Bekvalac.jpg

 73%|███████▎  | 4523/6167 [47:19<07:57,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natasa_Theodoridou.jpg

 73%|███████▎  | 4524/6167 [47:19<09:22,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Topčagić.jpg

 73%|███████▎  | 4525/6167 [47:20<09:19,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Mamula.jpg

 73%|███████▎  | 4529/6167 [47:20<04:48,  5.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miša_Aleksić.jpg

 73%|███████▎  | 4531/6167 [47:20<04:20,  6.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Ilić.jpg

 74%|███████▎  | 4534/6167 [47:20<03:33,  7.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mile_Kitić.jpg

 74%|███████▎  | 4535/6167 [47:21<04:18,  6.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milan_Stanković.jpg

 74%|███████▎  | 4537/6167 [47:21<04:03,  6.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Merima_Njegomir.jpg

 74%|███████▎  | 4539/6167 [47:22<04:38,  5.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Berović.jpg

 74%|███████▎  | 4540/6167 [47:22<05:14,  5.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Šuput.jpg

 74%|███████▎  | 4541/6167 [47:23<09:37,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Massimo_Savić.jpg

 74%|███████▎  | 4542/6167 [47:23<08:48,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marta_Savić.jpg

 74%|███████▎  | 4543/6167 [47:23<08:41,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Kon.jpg

 74%|███████▎  | 4544/6167 [47:24<08:13,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marinella.jpg

 74%|███████▎  | 4545/6167 [47:24<07:49,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marija_Šerifović.jpg

 74%|███████▎  | 4546/6167 [47:24<07:28,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Elena_Kyriakou.jpg

 74%|███████▎  | 4547/6167 [47:24<07:29,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malina.jpg

 74%|███████▍  | 4549/6167 [47:25<05:41,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Magnifico.jpg

 74%|███████▍  | 4550/6167 [47:25<05:59,  4.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luke_Black.jpg

 74%|███████▍  | 4552/6167 [47:25<05:13,  5.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Lukić.jpg

 74%|███████▍  | 4553/6167 [47:26<06:18,  4.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Brena.jpg

 74%|███████▍  | 4554/6167 [47:26<08:04,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lefteris_Pantazis.jpg

 74%|███████▍  | 4555/6167 [47:27<10:22,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Pušlar.jpg

 74%|███████▍  | 4557/6167 [47:27<09:12,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zoran_Predin.jpg

 74%|███████▍  | 4558/6167 [47:28<11:11,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oto_Pestner.jpg

 74%|███████▍  | 4559/6167 [47:28<12:00,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tomaž_Pengov.jpg

 74%|███████▍  | 4560/6167 [47:29<12:16,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neisha.jpg

 74%|███████▍  | 4561/6167 [47:30<14:03,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iztok_Mlakar.jpg

 74%|███████▍  | 4562/6167 [47:30<15:48,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Omar_Naber.jpg

 74%|███████▍  | 4563/6167 [47:31<18:23,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/ManuElla.jpg

 74%|███████▍  | 4564/6167 [47:33<24:14,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hannah_Mancini.jpg

 74%|███████▍  | 4565/6167 [47:33<19:19,  1.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Magnifico.jpg

 74%|███████▍  | 4566/6167 [47:33<16:09,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Martina_Majerle.jpg

 74%|███████▍  | 4567/6167 [47:34<16:53,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Lovšin.jpg

 74%|███████▍  | 4569/6167 [47:35<12:43,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lara-B.jpg

 74%|███████▍  | 4571/6167 [47:36<13:35,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlado_Kreslin.jpg

 74%|███████▍  | 4573/6167 [47:37<12:23,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tinkara_Kovač.jpg

 74%|███████▍  | 4575/6167 [47:37<09:25,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Keuc.jpg

 74%|███████▍  | 4577/6167 [47:38<10:56,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/July_Jones.jpg

 74%|███████▍  | 4579/6167 [47:39<10:48,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Grohar.jpg

 74%|███████▍  | 4580/6167 [47:39<12:41,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Grohar.jpg

 74%|███████▍  | 4581/6167 [47:40<14:52,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alenka_Gotar.jpg

 74%|███████▍  | 4582/6167 [47:41<17:54,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alenka_Godec.jpg

 74%|███████▍  | 4583/6167 [47:43<21:23,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jarmila_Gerbič.jpg

 74%|███████▍  | 4585/6167 [47:43<15:10,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neca_Falk.jpg

 74%|███████▍  | 4587/6167 [47:43<10:48,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kornelije_Kovač.jpg

 74%|███████▍  | 4588/6167 [47:44<12:24,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ben_Dolic.jpg

 74%|███████▍  | 4589/6167 [47:45<13:27,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rebeka_Dremelj.jpg

 74%|███████▍  | 4591/6167 [47:45<09:20,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Konstrakta.jpg

 74%|███████▍  | 4592/6167 [47:45<09:32,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Knez.jpg

 74%|███████▍  | 4594/6167 [47:46<07:20,  3.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kićo_Slabinac.jpg

 75%|███████▍  | 4595/6167 [47:46<07:33,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenan_Doğulu.jpg

 75%|███████▍  | 4596/6167 [47:46<08:02,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Monteno.jpg

 75%|███████▍  | 4597/6167 [47:47<08:35,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katy_Garbi.jpg

 75%|███████▍  | 4598/6167 [47:47<08:24,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karolina_Gočeva.jpg

 75%|███████▍  | 4599/6167 [47:48<10:32,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamelia.jpg

 75%|███████▍  | 4600/6167 [47:48<09:40,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalomira.jpg

 75%|███████▍  | 4601/6167 [47:48<09:06,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaliopi.jpg

 75%|███████▍  | 4602/6167 [47:49<09:26,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurica_Pađen.jpg

 75%|███████▍  | 4604/6167 [47:49<07:08,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josipa_Lisac.jpg

 75%|███████▍  | 4605/6167 [47:49<06:51,  3.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Tomašević.jpg

 75%|███████▍  | 4606/6167 [47:50<10:31,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Rozga.jpg

 75%|███████▍  | 4607/6167 [47:50<10:32,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Karleuša.jpg

 75%|███████▍  | 4609/6167 [47:51<07:35,  3.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Houdek.jpg

 75%|███████▍  | 4610/6167 [47:51<07:35,  3.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Pogorelić.jpg

 75%|███████▍  | 4613/6167 [47:51<05:27,  4.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivi_Adamou.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Zajc.jpg

 75%|███████▍  | 4614/6167 [47:52<06:09,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inva_Mula.jpg

 75%|███████▍  | 4615/6167 [47:53<09:08,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inna.jpg

 75%|███████▍  | 4616/6167 [47:53<08:38,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Radić.jpg

 75%|███████▍  | 4617/6167 [47:53<08:02,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Levak.jpg

 75%|███████▍  | 4618/6167 [47:53<08:26,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilira.jpg

 75%|███████▍  | 4619/6167 [47:54<07:49,  3.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hurricane.jpg

 75%|███████▍  | 4620/6167 [47:54<10:29,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Himzo_Polovina.jpg

 75%|███████▍  | 4621/6167 [47:55<09:51,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helena_Paparizou.jpg

 75%|███████▍  | 4622/6167 [47:55<09:11,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hasiba_Agić.jpg

 75%|███████▍  | 4623/6167 [47:56<17:25,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Džinović.jpg

 75%|███████▍  | 4624/6167 [47:57<14:38,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hari_Varešanović.jpg

 75%|███████▍  | 4625/6167 [47:57<12:02,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halid_Bešlić.jpg

 75%|███████▌  | 4626/6167 [47:57<10:49,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hadise.jpg

 75%|███████▌  | 4627/6167 [47:58<10:08,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gru.jpg

 75%|███████▌  | 4628/6167 [47:58<10:42,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anžej_Dežan.jpg

 75%|███████▌  | 4629/6167 [47:59<12:18,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nuša_Derenda.jpg

 75%|███████▌  | 4630/6167 [47:59<13:08,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eva_Boto.jpg

 75%|███████▌  | 4631/6167 [48:00<15:34,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sabina_Cvilak.jpg

 75%|███████▌  | 4632/6167 [48:01<16:02,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Janez_Bončina.jpg

 75%|███████▌  | 4633/6167 [48:02<21:55,  1.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julij_Betetto.jpg

 75%|███████▌  | 4635/6167 [48:03<14:53,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Urška_Arlič_Gololičič.jpg

 75%|███████▌  | 4637/6167 [48:03<12:12,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alya.jpg

 75%|███████▌  | 4638/6167 [48:04<13:18,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cvetka_Ahlin.jpg

 75%|███████▌  | 4640/6167 [48:04<09:22,  2.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Bregović.jpg

 75%|███████▌  | 4641/6167 [48:05<08:43,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goca_Tržan.jpg

 75%|███████▌  | 4642/6167 [48:05<08:27,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria.jpg

 75%|███████▌  | 4643/6167 [48:05<08:37,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gibonni.jpg

 75%|███████▌  | 4644/6167 [48:05<07:58,  3.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gergana.jpg

 75%|███████▌  | 4645/6167 [48:06<08:06,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Dalaras.jpg

 75%|███████▌  | 4647/6167 [48:06<06:28,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Galena.jpg

 75%|███████▌  | 4650/6167 [48:06<04:57,  5.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fiki.jpg

 75%|███████▌  | 4651/6167 [48:07<05:31,  4.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esma_Redžepova.jpg

 75%|███████▌  | 4652/6167 [48:07<08:02,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Era_Istrefi.jpg

 75%|███████▌  | 4653/6167 [48:08<07:45,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emina_Jahović.jpg

 75%|███████▌  | 4654/6167 [48:08<10:04,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emanuela.jpg

 75%|███████▌  | 4655/6167 [48:09<09:20,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvir_Laković_Laka.jpg

 75%|███████▌  | 4656/6167 [48:09<08:57,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvana_Gjata.jpg

 76%|███████▌  | 4657/6167 [48:09<08:16,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elhaida_Dani.jpg

 76%|███████▌  | 4658/6167 [48:10<07:52,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleni_Foureira.jpg

 76%|███████▌  | 4659/6167 [48:10<07:12,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Risteska.jpg

 76%|███████▌  | 4660/6167 [48:10<07:25,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleftheria_Eleftheriou.jpg

 76%|███████▌  | 4661/6167 [48:10<07:05,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Maajka.jpg

 76%|███████▌  | 4662/6167 [48:11<08:06,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Džej_Ramadanovski.jpg

 76%|███████▌  | 4663/6167 [48:11<08:38,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Đorđe_Balašević.jpg

 76%|███████▌  | 4665/6167 [48:12<08:27,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dua_Lipa.jpg

 76%|███████▌  | 4666/6167 [48:12<08:39,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragana_Mirković.jpg

 76%|███████▌  | 4667/6167 [48:13<08:31,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragan_Kojić_Keba.jpg

 76%|███████▌  | 4669/6167 [48:13<06:07,  4.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doris_Dragović.jpg

 76%|███████▌  | 4670/6167 [48:13<06:35,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Merlin.jpg

 76%|███████▌  | 4671/6167 [48:13<06:30,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Dvornik.jpg

 76%|███████▌  | 4672/6167 [48:14<06:41,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Despina_Vandi.jpg

 76%|███████▌  | 4674/6167 [48:14<05:05,  4.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deen.jpg

 76%|███████▌  | 4675/6167 [48:14<05:31,  4.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davorin_Popović.jpg

 76%|███████▌  | 4676/6167 [48:16<13:22,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darko_Rundek.jpg

 76%|███████▌  | 4678/6167 [48:16<09:06,  2.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danijela_Martinović.jpg

 76%|███████▌  | 4680/6167 [48:16<06:56,  3.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dafina_Zeqiri.jpg

 76%|███████▌  | 4681/6167 [48:16<06:47,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dado_Topić.jpg

 76%|███████▌  | 4684/6167 [48:17<04:36,  5.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coby.jpg

 76%|███████▌  | 4685/6167 [48:17<04:54,  5.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ceca.jpg

 76%|███████▌  | 4686/6167 [48:17<06:34,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Capital_T.jpg

 76%|███████▌  | 4689/6167 [48:18<05:16,  4.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Novković.jpg

 76%|███████▌  | 4691/6167 [48:18<05:06,  4.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bora_Đorđević.jpg

 76%|███████▌  | 4692/6167 [48:19<05:17,  4.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boban_Rajović.jpg

 76%|███████▌  | 4693/6167 [48:19<06:40,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bleona.jpg

 76%|███████▌  | 4694/6167 [48:19<07:02,  3.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebi_Dol.jpg

 76%|███████▌  | 4695/6167 [48:20<06:56,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebe_Rexha.jpg

 76%|███████▌  | 4696/6167 [48:20<06:53,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beba_Selimović.jpg

 76%|███████▌  | 4697/6167 [48:20<06:41,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bajaga.jpg

 76%|███████▌  | 4698/6167 [48:21<07:18,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azis.jpg

 76%|███████▌  | 4699/6167 [48:21<07:44,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Avni_Mula.jpg

 76%|███████▌  | 4700/6167 [48:21<07:43,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurela_Gaçe.jpg

 76%|███████▌  | 4701/6167 [48:22<08:34,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arsen_Dedić.jpg

 76%|███████▌  | 4702/6167 [48:22<09:28,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ardian_Bujupi.jpg

 76%|███████▋  | 4705/6167 [48:23<06:47,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Vissi.jpg

 76%|███████▋  | 4706/6167 [48:24<09:59,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Odobescu.jpg

 76%|███████▋  | 4707/6167 [48:24<09:21,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea.jpg

 76%|███████▋  | 4708/6167 [48:24<08:45,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bănică.jpg

 76%|███████▋  | 4710/6167 [48:24<06:19,  3.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Kokić.jpg

 76%|███████▋  | 4713/6167 [48:25<04:43,  5.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Stan.jpg

 76%|███████▋  | 4714/6167 [48:25<06:02,  4.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleksandra_Prijović.jpg

 76%|███████▋  | 4715/6167 [48:26<06:11,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Islamović.jpg

 76%|███████▋  | 4716/6167 [48:26<05:59,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alban_Skënderaj.jpg

 77%|███████▋  | 4718/6167 [48:26<04:40,  5.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Rahimovski.jpg

 77%|███████▋  | 4720/6167 [48:27<05:06,  4.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Sînă.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aco_Pejović.jpg

 77%|███████▋  | 4721/6167 [48:27<05:45,  4.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aca_Lukas.jpg

 77%|███████▋  | 4722/6167 [48:27<06:21,  3.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 77%|███████▋  | 4724/6167 [48:27<04:55,  4.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 77%|███████▋  | 4725/6167 [48:28<05:52,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 77%|███████▋  | 4726/6167 [48:28<05:53,  4.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 77%|███████▋  | 4727/6167 [48:30<14:56,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zeybek.jpg

 77%|███████▋  | 4730/6167 [48:30<08:35,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oro_(eagle_dance).jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karsilamas.jpg

 77%|███████▋  | 4731/6167 [48:31<08:21,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Čoček.jpg

 77%|███████▋  | 4734/6167 [48:31<05:27,  4.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsamiko.jpg

 77%|███████▋  | 4735/6167 [48:31<05:38,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamzara.jpg

 77%|███████▋  | 4736/6167 [48:31<05:42,  4.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sousta.jpg

 77%|███████▋  | 4737/6167 [48:32<07:52,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sirtaki.jpg

 77%|███████▋  | 4738/6167 [48:32<07:35,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syrtos.jpg

 77%|███████▋  | 4740/6167 [48:33<05:52,  4.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kolo.jpg

 77%|███████▋  | 4741/6167 [48:33<06:45,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kochari.jpg

 77%|███████▋  | 4742/6167 [48:33<06:35,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khigga.jpg

 77%|███████▋  | 4745/6167 [48:34<04:23,  5.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hora.jpg

 77%|███████▋  | 4751/6167 [48:34<02:16, 10.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenia.jpg

 77%|███████▋  | 4753/6167 [48:36<06:23,  3.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serbia.jpg

 77%|███████▋  | 4754/6167 [48:36<06:32,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romania.jpg

 77%|███████▋  | 4756/6167 [48:36<06:25,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/North_Macedonia.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegro.jpg

 77%|███████▋  | 4757/6167 [48:37<06:27,  3.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moldova.jpg

 77%|███████▋  | 4759/6167 [48:37<05:38,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 77%|███████▋  | 4760/6167 [48:37<05:31,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 77%|███████▋  | 4761/6167 [48:38<05:37,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cyprus.jpg

 77%|███████▋  | 4762/6167 [48:38<05:43,  4.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 77%|███████▋  | 4763/6167 [48:38<05:45,  4.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 77%|███████▋  | 4764/6167 [48:38<06:24,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnia_and_Herzegovina.jpg

 77%|███████▋  | 4766/6167 [48:39<05:09,  4.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 77%|███████▋  | 4767/6167 [48:39<05:46,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albania.jpg

 77%|███████▋  | 4768/6167 [48:40<07:35,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yugoslav_pop.jpg

 77%|███████▋  | 4771/6167 [48:40<04:55,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ganga_music.jpg

 77%|███████▋  | 4773/6167 [48:40<04:12,  5.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_brass.jpg

 77%|███████▋  | 4777/6167 [48:40<03:00,  7.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani_music.jpg

 77%|███████▋  | 4778/6167 [48:41<03:55,  5.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rebetiko.jpg

 77%|███████▋  | 4779/6167 [48:41<04:31,  5.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nisiotika.jpg

 78%|███████▊  | 4780/6167 [48:41<04:45,  4.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turbo-folk.jpg

 78%|███████▊  | 4782/6167 [48:42<04:06,  5.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manele.jpg

 78%|███████▊  | 4783/6167 [48:42<04:29,  5.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laïko.jpg

 78%|███████▊  | 4785/6167 [48:42<04:41,  4.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk-pop.jpg

 78%|███████▊  | 4786/6167 [48:43<05:15,  4.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkish.jpg

 78%|███████▊  | 4787/6167 [48:43<05:31,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenian.jpg

 78%|███████▊  | 4789/6167 [48:43<04:22,  5.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romanian.jpg

 78%|███████▊  | 4790/6167 [48:44<05:26,  4.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani.jpg

 78%|███████▊  | 4791/6167 [48:44<05:27,  4.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegrin.jpg

 78%|███████▊  | 4792/6167 [48:44<05:58,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Macedonian.jpg

 78%|███████▊  | 4793/6167 [48:44<06:23,  3.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greek.jpg

 78%|███████▊  | 4794/6167 [48:45<06:22,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatian.jpg

 78%|███████▊  | 4795/6167 [48:45<06:08,  3.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgarian.jpg

 78%|███████▊  | 4796/6167 [48:45<06:21,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnian.jpg

 78%|███████▊  | 4797/6167 [48:46<06:29,  3.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albanian.jpg

 78%|███████▊  | 4798/6167 [48:46<06:24,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk.jpg

 78%|███████▊  | 4803/6167 [48:46<02:53,  7.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music_of_Romania.jpg

 78%|███████▊  | 4804/6167 [48:47<05:11,  4.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Virginia_Zeani.jpg

 78%|███████▊  | 4807/6167 [48:47<04:28,  5.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ellie_White.jpg

 78%|███████▊  | 4808/6167 [48:48<06:15,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Xonia.jpg

 78%|███████▊  | 4809/6167 [48:49<08:03,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Voltaj.jpg

 78%|███████▊  | 4812/6167 [48:49<06:29,  3.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Veronika.jpg

 78%|███████▊  | 4813/6167 [48:50<08:05,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Vicoveanca.jpg

 78%|███████▊  | 4816/6167 [48:50<05:31,  4.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aura_Urziceanu.jpg

 78%|███████▊  | 4817/6167 [48:51<06:51,  3.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viorica_Ursuleac.jpg

 78%|███████▊  | 4818/6167 [48:52<08:32,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrei_Ursu.jpg

 78%|███████▊  | 4820/6167 [48:52<08:00,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aura_Twarowska.jpg

 78%|███████▊  | 4822/6167 [48:53<08:05,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mihai_Traistariu.jpg

 78%|███████▊  | 4823/6167 [48:53<08:17,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Todomondo.jpg

 78%|███████▊  | 4824/6167 [48:54<09:46,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Theodorini.jpg

 78%|███████▊  | 4826/6167 [48:55<08:42,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Tănase.jpg

 78%|███████▊  | 4827/6167 [48:55<09:28,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cleopatra_Stratan.jpg

 78%|███████▊  | 4828/6167 [48:56<10:27,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tataee.jpg

 78%|███████▊  | 4830/6167 [48:57<10:24,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Stoica.jpg

 78%|███████▊  | 4833/6167 [48:57<07:49,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Stan.jpg

 78%|███████▊  | 4835/6167 [48:58<08:26,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dan_Spătaru.jpg

 78%|███████▊  | 4836/6167 [48:59<10:14,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alina_Sorescu.jpg

 78%|███████▊  | 4838/6167 [49:00<10:00,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Victor_Socaciu.jpg

 78%|███████▊  | 4839/6167 [49:00<09:31,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Sînă.jpg

 78%|███████▊  | 4840/6167 [49:01<10:41,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Smiley.jpg

 79%|███████▊  | 4842/6167 [49:02<11:24,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angela_Similea.jpg

 79%|███████▊  | 4843/6167 [49:04<15:11,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carmen_Şerban.jpg

 79%|███████▊  | 4844/6167 [49:04<15:18,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vasile_Șeicaru.jpg

 79%|███████▊  | 4845/6167 [49:05<15:19,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paula_Seling.jpg

 79%|███████▊  | 4846/6167 [49:05<14:03,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Joseph_Schmidt.jpg

 79%|███████▊  | 4847/6167 [49:06<14:14,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teodora_Sava.jpg

 79%|███████▊  | 4848/6167 [49:07<14:51,  1.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ileana_Sărăroiu.jpg

 79%|███████▊  | 4850/6167 [49:08<11:55,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florin_Salam.jpg

 79%|███████▊  | 4851/6167 [49:08<13:25,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florian_Rus.jpg

 79%|███████▊  | 4853/6167 [49:09<10:41,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roxen.jpg

 79%|███████▊  | 4854/6167 [49:10<12:34,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stella_Roman.jpg

 79%|███████▊  | 4855/6167 [49:11<13:18,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florin_Ristei.jpg

 79%|███████▊  | 4856/6167 [49:11<13:12,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irina_Rimes.jpg

 79%|███████▉  | 4859/6167 [49:12<08:18,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adela_Popescu.jpg

 79%|███████▉  | 4860/6167 [49:13<13:46,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ștefan_Pop.jpg

 79%|███████▉  | 4863/6167 [49:14<09:29,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florian_Pittiș.jpg

 79%|███████▉  | 4864/6167 [49:15<10:25,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gică_Petrescu.jpg

 79%|███████▉  | 4865/6167 [49:15<11:26,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Petean.jpg

 79%|███████▉  | 4866/6167 [49:17<14:23,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ester_Peony.jpg

 79%|███████▉  | 4868/6167 [49:17<11:25,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Claudia_Pavel.jpg

 79%|███████▉  | 4869/6167 [49:18<13:08,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Margareta_Pâslaru.jpg

 79%|███████▉  | 4870/6167 [49:19<14:04,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ioan_Gyuri_Pascu.jpg

 79%|███████▉  | 4871/6167 [49:20<15:03,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cristina_Pasaroiu.jpg

 79%|███████▉  | 4872/6167 [49:20<14:14,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anca_Parghel.jpg

 79%|███████▉  | 4874/6167 [49:21<10:44,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Parazitii.jpg

 79%|███████▉  | 4875/6167 [49:22<11:58,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kadriye_Nurmambet.jpg

 79%|███████▉  | 4878/6167 [49:22<08:29,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariana_Nicolesco.jpg

 79%|███████▉  | 4879/6167 [49:23<10:41,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nico.jpg

 79%|███████▉  | 4881/6167 [49:24<09:32,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Naomy.jpg

 79%|███████▉  | 4882/6167 [49:24<08:59,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dana_Nălbaru.jpg

 79%|███████▉  | 4885/6167 [49:24<05:42,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Motans.jpg

 79%|███████▉  | 4886/6167 [49:25<07:06,  3.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Moșuc.jpg

 79%|███████▉  | 4887/6167 [49:26<09:33,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jean_Moscopol.jpg

 79%|███████▉  | 4890/6167 [49:27<07:36,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angela_Moldovan.jpg

 79%|███████▉  | 4891/6167 [49:28<10:42,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marius_Moga.jpg

 79%|███████▉  | 4893/6167 [49:28<08:44,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlad_Miriţă.jpg

 79%|███████▉  | 4894/6167 [49:29<09:44,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nelly_Miricioiu.jpg

 79%|███████▉  | 4895/6167 [49:31<16:27,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Minune.jpg

 79%|███████▉  | 4896/6167 [49:32<15:39,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Minelli.jpg

 79%|███████▉  | 4897/6167 [49:32<14:39,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ada_Milea.jpg

 79%|███████▉  | 4899/6167 [49:33<11:10,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Mica.jpg

 79%|███████▉  | 4900/6167 [49:33<11:50,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Irina_Măruță.jpg

 79%|███████▉  | 4902/6167 [49:34<08:15,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edward_Maya.jpg

 80%|███████▉  | 4903/6167 [49:34<09:02,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Delia_Matache.jpg

 80%|███████▉  | 4906/6167 [49:35<07:22,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yolanda_Marculescu.jpg

 80%|███████▉  | 4907/6167 [49:36<08:17,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mădălina_Manole.jpg

 80%|███████▉  | 4908/6167 [49:37<12:49,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mandinga.jpg

 80%|███████▉  | 4911/6167 [49:38<09:17,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Irina_Loghin.jpg

 80%|███████▉  | 4912/6167 [49:39<12:33,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Lesko.jpg

 80%|███████▉  | 4917/6167 [49:40<08:28,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dalma_Kovács.jpg

 80%|███████▉  | 4918/6167 [49:41<08:57,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Atilla_Kiss_B..jpg

 80%|███████▉  | 4919/6167 [49:42<09:45,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamelia.jpg

 80%|███████▉  | 4920/6167 [49:42<09:41,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vika_Jigulina.jpg

 80%|███████▉  | 4922/6167 [49:43<08:49,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Ivaniţchi.jpg

 80%|███████▉  | 4923/6167 [49:44<11:10,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leo_Iorga.jpg

 80%|███████▉  | 4925/6167 [49:44<09:20,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dan_Iordăchescu.jpg

 80%|███████▉  | 4927/6167 [49:45<09:21,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Costi_Ioniță.jpg

 80%|███████▉  | 4928/6167 [49:46<08:42,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inna.jpg

 80%|███████▉  | 4929/6167 [49:46<08:59,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indiggo.jpg

 80%|███████▉  | 4930/6167 [49:47<10:57,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emeric_Imre.jpg

 80%|████████  | 4934/6167 [49:47<06:05,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Narcis_Iustin_Ianău.jpg

 80%|████████  | 4935/6167 [49:48<06:49,  3.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Humans.jpg

 80%|████████  | 4936/6167 [49:48<07:28,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antonia_Iacobescu.jpg

 80%|████████  | 4937/6167 [49:49<09:14,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ștefan_Hrușcă.jpg

 80%|████████  | 4938/6167 [49:50<10:45,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandrina_Hristov.jpg

 80%|████████  | 4939/6167 [49:51<11:16,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Károly_Horváth.jpg

 80%|████████  | 4940/6167 [49:51<09:48,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Holy_Molly.jpg

 80%|████████  | 4941/6167 [49:51<09:46,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hotel_FM.jpg

 80%|████████  | 4942/6167 [49:52<10:41,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ioan_Holender.jpg

 80%|████████  | 4943/6167 [49:52<09:13,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hi-Q.jpg

 80%|████████  | 4945/6167 [49:53<07:12,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Heaven.jpg

 80%|████████  | 4947/6167 [49:53<06:46,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rona_Hartner.jpg

 80%|████████  | 4949/6167 [49:54<05:45,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haiducii.jpg

 80%|████████  | 4950/6167 [49:55<08:01,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicolae_Guță.jpg

 80%|████████  | 4951/6167 [49:55<10:19,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Traian_Grozăvescu.jpg

 80%|████████  | 4952/6167 [49:56<11:15,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Loredana_Groza.jpg

 80%|████████  | 4955/6167 [49:56<06:38,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Angela_Gheorghiu.jpg

 80%|████████  | 4956/6167 [49:57<07:07,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tudor_Gheorghe.jpg

 80%|████████  | 4957/6167 [49:57<07:13,  2.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Gheorghe.jpg

 80%|████████  | 4958/6167 [49:58<06:44,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christina_Grimmie.jpg

 80%|████████  | 4959/6167 [49:58<06:25,  3.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamara_Ghedi.jpg

 80%|████████  | 4961/6167 [49:59<07:10,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrei_Găluț.jpg

 80%|████████  | 4963/6167 [50:00<08:11,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florin_Salam_.jpg

 80%|████████  | 4964/6167 [50:00<08:34,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/G_Girls.jpg

 81%|████████  | 4965/6167 [50:01<09:10,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Forescu.jpg

 81%|████████  | 4967/6167 [50:01<07:32,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Killa_Fonic.jpg

 81%|████████  | 4969/6167 [50:02<07:29,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alex_Florea.jpg

 81%|████████  | 4972/6167 [50:03<06:43,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alina_Eremia.jpg

 81%|████████  | 4974/6167 [50:04<08:06,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emaa.jpg

 81%|████████  | 4975/6167 [50:04<07:31,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dida_Drăgan.jpg

 81%|████████  | 4977/6167 [50:05<07:40,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ion_Dolănescu.jpg

 81%|████████  | 4978/6167 [50:05<07:18,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gil_Dobrică.jpg

 81%|████████  | 4979/6167 [50:06<06:52,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diana_V.jpg

 81%|████████  | 4980/6167 [50:06<08:28,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Annamari_Dancs.jpg

 81%|████████  | 4981/6167 [50:07<09:21,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hariclea_Darclée.jpg

 81%|████████  | 4984/6167 [50:08<07:02,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bogdan_Curta.jpg

 81%|████████  | 4988/6167 [50:08<05:30,  3.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viorica_Cortez.jpg

 81%|████████  | 4990/6167 [50:10<07:39,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Corina.jpg

 81%|████████  | 4991/6167 [50:11<10:10,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Connect-R.jpg

 81%|████████  | 4992/6167 [50:12<11:27,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sorin_Coliban.jpg

 81%|████████  | 4993/6167 [50:13<11:30,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sabina_Cojocar.jpg

 81%|████████  | 4996/6167 [50:13<07:52,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tudor_Chirilă.jpg

 81%|████████  | 4997/6167 [50:14<08:14,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Corina_Chiriac.jpg

 81%|████████  | 4998/6167 [50:14<09:36,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Florin_Chilian.jpg

 81%|████████  | 4999/6167 [50:15<11:57,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicole_Cherry.jpg

 81%|████████  | 5000/6167 [50:16<12:11,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/The_Cheeky_Girls.jpg

 81%|████████  | 5001/6167 [50:17<13:37,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Cernei.jpg

 81%|████████  | 5002/6167 [50:18<14:29,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cezar.jpg

 81%|████████  | 5003/6167 [50:18<13:47,  1.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ovidiu_Cernăuţeanu.jpg

 81%|████████  | 5004/6167 [50:19<12:36,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Cebotari.jpg

 81%|████████  | 5006/6167 [50:19<09:02,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carla's_Dreams.jpg

 81%|████████  | 5008/6167 [50:20<08:21,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Costel_Busuioc.jpg

 81%|████████  | 5009/6167 [50:21<09:30,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roxana_Briban.jpg

 81%|████████  | 5010/6167 [50:22<11:25,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicolae_Bretan.jpg

 81%|████████▏ | 5012/6167 [50:22<09:16,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Horia_Brenciu.jpg

 81%|████████▏ | 5017/6167 [50:23<05:03,  3.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dan_Bittman.jpg

 81%|████████▏ | 5020/6167 [50:24<06:05,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ducu_Bertzi.jpg

 81%|████████▏ | 5021/6167 [50:25<07:07,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bere_Gratis.jpg

 81%|████████▏ | 5022/6167 [50:26<07:43,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mircea_Baniciu.jpg

 81%|████████▏ | 5023/6167 [50:26<09:21,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ramona_Badescu.jpg

 81%|████████▏ | 5025/6167 [50:27<08:02,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Agatha_Bârsescu.jpg

 82%|████████▏ | 5027/6167 [50:28<07:52,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ștefan_Bănică,_Sr..jpg

 82%|████████▏ | 5028/6167 [50:28<08:26,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ștefan_Bănică,_Jr..jpg

 82%|████████▏ | 5029/6167 [50:29<07:46,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bănică.jpg

 82%|████████▏ | 5030/6167 [50:29<09:12,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bălan.jpg

 82%|████████▏ | 5031/6167 [50:30<10:20,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilinca_Băcilă.jpg

 82%|████████▏ | 5032/6167 [50:31<10:37,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kristaq_Antoniu.jpg

 82%|████████▏ | 5035/6167 [50:31<07:01,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Giulia_Anghelescu.jpg

 82%|████████▏ | 5036/6167 [50:32<08:42,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Monica_Anghel.jpg

 82%|████████▏ | 5037/6167 [50:33<09:01,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luminiţa_Anghel.jpg

 82%|████████▏ | 5038/6167 [50:33<10:14,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Theodor_Andrei.jpg

 82%|████████▏ | 5039/6167 [50:36<18:01,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurelian_Andreescu.jpg

 82%|████████▏ | 5040/6167 [50:36<17:00,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andra.jpg

 82%|████████▏ | 5041/6167 [50:37<15:41,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/AMI.jpg

 82%|████████▏ | 5042/6167 [50:38<15:09,  1.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Radu_Almășan.jpg

 82%|████████▏ | 5044/6167 [50:39<12:43,  1.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicoleta_Alexandru.jpg

 82%|████████▏ | 5045/6167 [50:40<13:23,  1.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Akcent.jpg

 82%|████████▏ | 5046/6167 [50:40<12:23,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandru_Agache.jpg

 82%|████████▏ | 5047/6167 [50:41<13:03,  1.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adena.jpg

 82%|████████▏ | 5048/6167 [50:42<12:46,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anda_Adam.jpg

 82%|████████▏ | 5049/6167 [50:42<13:42,  1.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Olivia_Addams.jpg

 82%|████████▏ | 5052/6167 [50:43<08:24,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/RUC.jpg

 82%|████████▏ | 5053/6167 [50:44<08:50,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rádio_Comercial.jpg

 82%|████████▏ | 5055/6167 [50:44<07:58,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/RFM.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/MTV_Portugal.jpg

 82%|████████▏ | 5056/6167 [50:45<09:54,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mega_FM.jpg

 82%|████████▏ | 5057/6167 [50:46<10:17,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/M80.jpg

 82%|████████▏ | 5058/6167 [50:46<08:32,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Blitz.jpg

 82%|████████▏ | 5059/6167 [50:47<08:34,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Antena_3.jpg

 82%|████████▏ | 5060/6167 [50:47<09:13,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vilar_de_Mouros.jpg

 82%|████████▏ | 5062/6167 [50:48<07:40,  2.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/_Sudoeste.jpg

 82%|████████▏ | 5063/6167 [50:48<08:05,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Super_Bock_Super_Rock.jpg

 82%|████████▏ | 5064/6167 [50:49<09:22,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/_Rock_in_Rio_Lisboa.jpg

 82%|████████▏ | 5065/6167 [50:50<11:40,  1.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paredes_de_Coura.jpg

 82%|████████▏ | 5066/6167 [50:51<13:55,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/NOS_Alive.jpg

 82%|████████▏ | 5067/6167 [50:52<13:41,  1.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Festival_Músicas_do_Mundo.jpg

 82%|████████▏ | 5068/6167 [50:53<14:40,  1.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalorama.jpg

 82%|████████▏ | 5069/6167 [50:53<14:09,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boom.jpg

 82%|████████▏ | 5071/6167 [50:54<10:38,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pimba.jpg

 82%|████████▏ | 5072/6167 [50:55<09:51,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hip_hop.jpg

 82%|████████▏ | 5073/6167 [50:55<10:53,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk.jpg

 82%|████████▏ | 5074/6167 [50:56<09:17,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fado.jpg

 82%|████████▏ | 5075/6167 [50:56<09:42,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Desgarrada.jpg

 82%|████████▏ | 5076/6167 [50:57<08:33,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Classical.jpg

 82%|████████▏ | 5077/6167 [50:57<09:17,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cante_Alentejano.jpg

 82%|████████▏ | 5078/6167 [50:58<10:04,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/sapo.pt.jpg

 82%|████████▏ | 5079/6167 [50:58<08:18,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/O_Globo.jpg

 82%|████████▏ | 5080/6167 [50:58<06:58,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diário_de_Notícias.jpg

 82%|████████▏ | 5081/6167 [50:59<08:20,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zeca_Afonso.jpg

 82%|████████▏ | 5083/6167 [51:00<07:27,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yolanda_Soares.jpg

 82%|████████▏ | 5084/6167 [51:00<08:05,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wet_Bed_Gang.jpg

 82%|████████▏ | 5085/6167 [51:01<07:39,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/WAY_45_(Rafael_Leão).jpg

 82%|████████▏ | 5086/6167 [51:01<08:22,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vitorino.jpg

 82%|████████▏ | 5087/6167 [51:02<09:24,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vânia_Fernandes.jpg

 83%|████████▎ | 5088/6167 [51:02<09:58,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Valete.jpg

 83%|████████▎ | 5089/6167 [51:03<09:53,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Carreira.jpg

 83%|████████▎ | 5090/6167 [51:04<11:33,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tonicha.jpg

 83%|████████▎ | 5092/6167 [51:04<08:46,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tito_Schipa_Jr..jpg

 83%|████████▎ | 5093/6167 [51:05<09:47,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tiago_Bettencourt.jpg

 83%|████████▎ | 5094/6167 [51:06<09:58,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teresinha_Landeiro.jpg

 83%|████████▎ | 5096/6167 [51:06<08:37,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Teresa_Salgueiro.jpg

 83%|████████▎ | 5097/6167 [51:07<10:24,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suzy.jpg

 83%|████████▎ | 5098/6167 [51:08<10:28,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suspiria_Franklyn.jpg

 83%|████████▎ | 5099/6167 [51:09<10:33,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Susana_Gaspar.jpg

 83%|████████▎ | 5101/6167 [51:09<07:00,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Vitória.jpg

 83%|████████▎ | 5103/6167 [51:10<06:41,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofia_Hoffmann.jpg

 83%|████████▎ | 5106/6167 [51:10<04:54,  3.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slimmy.jpg

 83%|████████▎ | 5108/6167 [51:12<09:01,  1.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Simone_de_Oliveira.jpg

 83%|████████▎ | 5109/6167 [51:13<09:13,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sérgio_Godinho.jpg

 83%|████████▎ | 5111/6167 [51:13<08:10,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Correia.jpg

 83%|████████▎ | 5112/6167 [51:14<09:08,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Tavares.jpg

 83%|████████▎ | 5113/6167 [51:15<10:34,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Braga_Simões.jpg

 83%|████████▎ | 5114/6167 [51:16<11:03,  1.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sam_the_Kid.jpg

 83%|████████▎ | 5115/6167 [51:17<13:17,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Salvador_Sobral.jpg

 83%|████████▎ | 5116/6167 [51:17<10:55,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sabrina.jpg

 83%|████████▎ | 5117/6167 [51:18<11:03,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rui_Veloso.jpg

 83%|████████▎ | 5120/6167 [51:18<05:46,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rui_Bandeira.jpg

 83%|████████▎ | 5122/6167 [51:19<05:50,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rosinha.jpg

 83%|████████▎ | 5123/6167 [51:19<07:09,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Roberto_Leal.jpg

 83%|████████▎ | 5124/6167 [51:20<08:43,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Redshoes.jpg

 83%|████████▎ | 5125/6167 [51:21<09:33,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Damásio.jpg

 83%|████████▎ | 5126/6167 [51:23<14:05,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Guerra.jpg

 83%|████████▎ | 5127/6167 [51:25<20:36,  1.19s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Richie_Campbell.jpg

 83%|████████▎ | 5128/6167 [51:26<18:13,  1.05s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Regina_Pacini.jpg

 83%|████████▎ | 5129/6167 [51:26<16:42,  1.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raquel_Tavares.jpg

 83%|████████▎ | 5131/6167 [51:27<11:49,  1.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raquel_Camarinha.jpg

 83%|████████▎ | 5132/6167 [51:28<11:33,  1.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Quim_Barreiros.jpg

 83%|████████▎ | 5135/6167 [51:28<08:03,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Piruka.jpg

 83%|████████▎ | 5136/6167 [51:29<09:42,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pilar_Homem_de_Melo.jpg

 83%|████████▎ | 5138/6167 [51:30<08:07,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pedro_Luís_Neves.jpg

 83%|████████▎ | 5139/6167 [51:31<10:23,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pedro_Abrunhosa.jpg

 83%|████████▎ | 5143/6167 [51:32<06:35,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulo_de_Carvalho.jpg

 83%|████████▎ | 5144/6167 [51:32<07:02,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paulo_Brissos.jpg

 83%|████████▎ | 5149/6167 [51:33<04:37,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paco_Bandeira.jpg

 84%|████████▎ | 5151/6167 [51:34<04:46,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Sean.jpg

 84%|████████▎ | 5152/6167 [51:35<06:20,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nuno_Roque.jpg

 84%|████████▎ | 5153/6167 [51:35<06:24,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nuno_Bettencourt.jpg

 84%|████████▎ | 5154/6167 [51:36<07:12,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nuno_Resende.jpg

 84%|████████▎ | 5159/6167 [51:36<03:36,  4.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nelly_Furtado.jpg

 84%|████████▎ | 5163/6167 [51:37<02:58,  5.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mishlawi.jpg

 84%|████████▎ | 5164/6167 [51:37<03:41,  4.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mimicat.jpg

 84%|████████▍ | 5165/6167 [51:38<05:04,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milú.jpg

 84%|████████▍ | 5166/6167 [51:39<08:41,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miguel_Guedes.jpg

 84%|████████▍ | 5168/6167 [51:40<06:37,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mickael_Carreira.jpg

 84%|████████▍ | 5170/6167 [51:40<06:18,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maximiano_de_Sousa.jpg

 84%|████████▍ | 5171/6167 [51:41<07:52,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maurizio_Bensaude.jpg

 84%|████████▍ | 5172/6167 [51:42<07:11,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marta_Dias.jpg

 84%|████████▍ | 5173/6167 [51:42<06:32,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariza.jpg

 84%|████████▍ | 5174/6167 [51:43<08:23,  1.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maro.jpg

 84%|████████▍ | 5175/6167 [51:44<10:08,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marisa_Liz.jpg

 84%|████████▍ | 5177/6167 [51:44<08:58,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Teresa_de_Noronha.jpg

 84%|████████▍ | 5178/6167 [51:45<07:42,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marie_Myriam.jpg

 84%|████████▍ | 5179/6167 [51:45<08:52,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Severa-Onofriana.jpg

 84%|████████▍ | 5180/6167 [51:46<09:27,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_José_Valério.jpg

 84%|████████▍ | 5181/6167 [51:47<09:12,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_João.jpg

 84%|████████▍ | 5183/6167 [51:47<07:38,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_do_Carmo.jpg

 84%|████████▍ | 5187/6167 [51:48<04:32,  3.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Márcio_Cunha.jpg

 84%|████████▍ | 5190/6167 [51:48<03:49,  4.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manuela_Bravo.jpg

 84%|████████▍ | 5191/6167 [51:49<04:40,  3.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manuela_Azevedo.jpg

 84%|████████▍ | 5193/6167 [51:50<05:08,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malvina_Garrigues.jpg

 84%|████████▍ | 5196/6167 [51:52<07:27,  2.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Madalena_Iglésias.jpg

 84%|████████▍ | 5198/6167 [51:52<06:52,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lura.jpg

 84%|████████▍ | 5199/6167 [51:53<07:38,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lula_Pena.jpg

 84%|████████▍ | 5200/6167 [51:55<10:31,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luísa_Todi.jpg

 84%|████████▍ | 5201/6167 [51:55<09:05,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luísa_Sobral.jpg

 84%|████████▍ | 5204/6167 [51:55<06:23,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luís_Gil_Bettencourt.jpg

 84%|████████▍ | 5205/6167 [51:56<07:50,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucília_do_Carmo.jpg

 84%|████████▍ | 5206/6167 [51:57<08:23,  1.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luciana_Abreu.jpg

 84%|████████▍ | 5207/6167 [51:57<07:27,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lúcia_Moniz.jpg

 84%|████████▍ | 5208/6167 [51:58<07:25,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lucenzo.jpg

 84%|████████▍ | 5211/6167 [51:58<05:18,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lizzy's_Husband.jpg

 85%|████████▍ | 5212/6167 [51:59<06:20,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Linda_de_Suza.jpg

 85%|████████▍ | 5213/6167 [52:00<07:22,  2.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Leonor_Andrade.jpg

 85%|████████▍ | 5214/6167 [52:01<08:46,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lata_Gouveia.jpg

 85%|████████▍ | 5215/6167 [52:01<08:47,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lena_d'Água.jpg

 85%|████████▍ | 5216/6167 [52:02<08:57,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katia_Guerreiro.jpg

 85%|████████▍ | 5218/6167 [52:02<07:47,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/JP_Simões.jpg

 85%|████████▍ | 5219/6167 [52:03<08:28,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Pinhal.jpg

 85%|████████▍ | 5220/6167 [52:04<08:44,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Mário_Branco.jpg

 85%|████████▍ | 5221/6167 [52:04<08:46,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Cid.jpg

 85%|████████▍ | 5222/6167 [52:05<09:31,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/José_Carlos_Xavier.jpg

 85%|████████▍ | 5223/6167 [52:07<14:33,  1.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jorge_Palma.jpg

 85%|████████▍ | 5224/6167 [52:08<15:22,  1.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jorge_Chaminé.jpg

 85%|████████▍ | 5233/6167 [52:09<04:14,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Isaura.jpg

 85%|████████▍ | 5234/6167 [52:10<05:24,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iolanda.jpg

 85%|████████▍ | 5236/6167 [52:10<05:05,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inês_Herédia.jpg

 85%|████████▍ | 5237/6167 [52:11<06:12,  2.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/IAMDDB.jpg

 85%|████████▍ | 5238/6167 [52:12<07:35,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hermínia_Silva.jpg

 85%|████████▍ | 5239/6167 [52:13<08:27,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Herman_José.jpg

 85%|████████▍ | 5241/6167 [52:13<07:01,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helder_Moutinho.jpg

 85%|████████▌ | 5243/6167 [52:14<06:01,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gisela_João.jpg

 85%|████████▌ | 5245/6167 [52:14<04:48,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/General_D.jpg

 85%|████████▌ | 5246/6167 [52:15<05:41,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/G-Amado.jpg

 85%|████████▌ | 5247/6167 [52:15<06:54,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Francisco_D'Andrade.jpg

 85%|████████▌ | 5250/6167 [52:16<05:16,  2.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Filipa_Azevedo.jpg

 85%|████████▌ | 5251/6167 [52:17<06:07,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_Tordo.jpg

 85%|████████▌ | 5252/6167 [52:17<06:33,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_Ribeiro.jpg

 85%|████████▌ | 5253/6167 [52:18<08:19,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_Maurício.jpg

 85%|████████▌ | 5255/6167 [52:19<06:47,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fernando_Daniel.jpg

 85%|████████▌ | 5256/6167 [52:20<07:34,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fausto_Bordalo_Dias.jpg

 85%|████████▌ | 5257/6167 [52:21<10:40,  1.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Evelina_Pereira.jpg

 85%|████████▌ | 5259/6167 [52:21<07:52,  1.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ercília_Costa.jpg

 85%|████████▌ | 5260/6167 [52:22<09:47,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elisabete_Matos.jpg

 85%|████████▌ | 5261/6167 [52:23<09:22,  1.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elisa_Silva.jpg

 85%|████████▌ | 5263/6167 [52:23<06:41,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dulce_Pontes.jpg

 85%|████████▌ | 5266/6167 [52:24<04:59,  3.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diogo_Piçarra.jpg

 85%|████████▌ | 5267/6167 [52:25<06:12,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_D'Santiago.jpg

 85%|████████▌ | 5268/6167 [52:26<07:25,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Diana_Piedade.jpg

 86%|████████▌ | 5273/6167 [52:26<04:03,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/David_Fonseca.jpg

 86%|████████▌ | 5274/6167 [52:27<05:36,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/David_Carreira.jpg

 86%|████████▌ | 5275/6167 [52:27<05:24,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniela_Varela.jpg

 86%|████████▌ | 5276/6167 [52:28<06:31,  2.28it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cristina_Branco.jpg

 86%|████████▌ | 5278/6167 [52:29<05:42,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Corina_Freire.jpg

 86%|████████▌ | 5279/6167 [52:29<06:17,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Conan_Osiris.jpg

 86%|████████▌ | 5280/6167 [52:30<07:10,  2.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Claudisabel.jpg

 86%|████████▌ | 5281/6167 [52:31<08:11,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cláudia_Pascoal.jpg

 86%|████████▌ | 5282/6167 [52:31<08:12,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Clara_D'Ovar.jpg

 86%|████████▌ | 5283/6167 [52:32<08:51,  1.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Celeste_Rodrigues.jpg

 86%|████████▌ | 5285/6167 [52:33<07:51,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Catarina_Miranda.jpg

 86%|████████▌ | 5286/6167 [52:34<08:44,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carolina_Deslandes.jpg

 86%|████████▌ | 5287/6167 [52:35<12:16,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carminho.jpg

 86%|████████▌ | 5289/6167 [52:36<08:33,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carmen_Souza.jpg

 86%|████████▌ | 5290/6167 [52:36<07:34,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carmen_Miranda.jpg

 86%|████████▌ | 5293/6167 [52:37<05:17,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_Nóbrega.jpg

 86%|████████▌ | 5294/6167 [52:37<05:39,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_Mendes.jpg

 86%|████████▌ | 5295/6167 [52:38<07:09,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Carlos_do_Carmo.jpg

 86%|████████▌ | 5297/6167 [52:39<07:14,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Capicua.jpg

 86%|████████▌ | 5299/6167 [52:40<06:06,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Camané.jpg

 86%|████████▌ | 5300/6167 [52:42<10:52,  1.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boss_AC.jpg

 86%|████████▌ | 5301/6167 [52:43<11:01,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Blaya.jpg

 86%|████████▌ | 5305/6167 [52:43<06:05,  2.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bárbara_Tinoco.jpg

 86%|████████▌ | 5307/6167 [52:44<05:59,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurea.jpg

 86%|████████▌ | 5309/6167 [52:45<05:38,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Argentina_Santos.jpg

 86%|████████▌ | 5310/6167 [52:45<06:22,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/April_Ivy.jpg

 86%|████████▌ | 5311/6167 [52:46<06:58,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/António_Zambujo.jpg

 86%|████████▌ | 5312/6167 [52:47<07:41,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/António_Variações.jpg

 86%|████████▌ | 5315/6167 [52:47<05:30,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/António_D'Andrade.jpg

 86%|████████▌ | 5316/6167 [52:48<05:51,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/António_Calvário.jpg

 86%|████████▌ | 5318/6167 [52:50<08:16,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anita_Guerreiro.jpg

 86%|████████▋ | 5320/6167 [52:50<06:54,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/André_Sardet.jpg

 86%|████████▋ | 5321/6167 [52:51<06:22,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anabela.jpg

 86%|████████▋ | 5322/6167 [52:51<06:58,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Moura.jpg

 86%|████████▋ | 5323/6167 [52:52<08:02,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Malhoa.jpg

 86%|████████▋ | 5324/6167 [52:53<09:01,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Free.jpg

 86%|████████▋ | 5325/6167 [52:54<09:39,  1.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_da_Silva.jpg

 86%|████████▋ | 5326/6167 [52:54<08:12,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amélia_Muge.jpg

 86%|████████▋ | 5327/6167 [52:55<07:36,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amália_Rodrigues.jpg

 86%|████████▋ | 5328/6167 [52:55<07:34,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alfredo_Marceneiro.jpg

 86%|████████▋ | 5330/6167 [52:56<06:31,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alberto_Ribeiro.jpg

 86%|████████▋ | 5333/6167 [52:57<06:47,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adriano_Correia_de_Oliveira.jpg

 86%|████████▋ | 5334/6167 [52:58<07:52,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adolfo_Luxúria_Canibal.jpg

 87%|████████▋ | 5337/6167 [53:00<07:32,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Navneet_Aditya_Waiba.jpg

 87%|████████▋ | 5338/6167 [53:00<07:24,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sajjan_Raj_Vaidya.jpg

 87%|████████▋ | 5339/6167 [53:01<07:45,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Robin_Tamang.jpg

 87%|████████▋ | 5344/6167 [53:02<03:58,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dharmaraj_Thapa.jpg

 87%|████████▋ | 5345/6167 [53:02<04:39,  2.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arun_Thapa.jpg

 87%|████████▋ | 5346/6167 [53:02<04:27,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Phiroj_Shyangden.jpg

 87%|████████▋ | 5347/6167 [53:03<05:14,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Abhaya_Subba.jpg

 87%|████████▋ | 5349/6167 [53:03<04:19,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sushma_Shrestha.jpg

 87%|████████▋ | 5350/6167 [53:04<05:10,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seturam_Shrestha.jpg

 87%|████████▋ | 5354/6167 [53:05<03:28,  3.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deep_Shrestha.jpg

 87%|████████▋ | 5355/6167 [53:06<06:30,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Shiva_Shankar.jpg

 87%|████████▋ | 5357/6167 [53:07<05:33,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arjun_Sapkota.jpg

 87%|████████▋ | 5358/6167 [53:07<05:50,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nima_Rumba.jpg

 87%|████████▋ | 5359/6167 [53:08<06:21,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sashi_Rawal.jpg

 87%|████████▋ | 5360/6167 [53:08<06:12,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gyanu_Rana.jpg

 87%|████████▋ | 5364/6167 [53:09<03:58,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rajesh_Payal_Rai.jpg

 87%|████████▋ | 5366/6167 [53:10<03:59,  3.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bartika_Eam_Rai.jpg

 87%|████████▋ | 5367/6167 [53:10<04:08,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Pradhan.jpg

 87%|████████▋ | 5368/6167 [53:11<04:58,  2.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Prem_Dhoj_Pradhan.jpg

 87%|████████▋ | 5370/6167 [53:11<04:04,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sugam_Pokharel.jpg

 87%|████████▋ | 5372/6167 [53:11<03:17,  4.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anju_Panta.jpg

 87%|████████▋ | 5376/6167 [53:12<02:32,  5.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kunti_Moktan.jpg

 87%|████████▋ | 5378/6167 [53:12<02:20,  5.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bishnu_Majhi.jpg

 87%|████████▋ | 5379/6167 [53:14<05:48,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Muna_Thapa_Magar.jpg

 87%|████████▋ | 5380/6167 [53:14<05:40,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raju_Lama.jpg

 87%|████████▋ | 5381/6167 [53:15<06:25,  2.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamal_Khatri.jpg

 87%|████████▋ | 5382/6167 [53:17<10:48,  1.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pramod_Kharel.jpg

 87%|████████▋ | 5383/6167 [53:18<10:02,  1.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ram_Prasad_Khanal.jpg

 87%|████████▋ | 5391/6167 [53:18<03:00,  4.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Narayan_Gopal.jpg

 87%|████████▋ | 5393/6167 [53:19<03:18,  3.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mausami_Gurung.jpg

 87%|████████▋ | 5396/6167 [53:19<03:20,  3.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khem_Raj_Gurung.jpg

 88%|████████▊ | 5399/6167 [53:20<02:58,  4.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Atithi_Gautam_K._C.jpg

 88%|████████▊ | 5400/6167 [53:21<03:43,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amrit_Gurung.jpg

 88%|████████▊ | 5401/6167 [53:22<05:00,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Amber_Gurung.jpg

 88%|████████▊ | 5402/6167 [53:23<07:50,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sunita_Dulal.jpg

 88%|████████▊ | 5403/6167 [53:24<07:05,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ani_Choying_Dolma.jpg

 88%|████████▊ | 5404/6167 [53:24<07:01,  1.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tara_Devi.jpg

 88%|████████▊ | 5406/6167 [53:25<06:16,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karna_Das.jpg

 88%|████████▊ | 5407/6167 [53:25<06:18,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nalina_Chitrakar.jpg

 88%|████████▊ | 5411/6167 [53:26<03:43,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tika_Bhandari.jpg

 88%|████████▊ | 5417/6167 [53:27<02:26,  5.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Wajiha_Rastagar.jpg

 88%|████████▊ | 5420/6167 [53:27<02:21,  5.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Outline.jpg

 88%|████████▊ | 5421/6167 [53:28<03:18,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yol_Aularong.jpg

 88%|████████▊ | 5423/6167 [53:29<03:25,  3.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nawal_El_Zoghbi.jpg

 88%|████████▊ | 5424/6167 [53:29<04:11,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coburn_Pharr.jpg

 88%|████████▊ | 5427/6167 [53:30<03:31,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jeanne_Dusseau.jpg

 88%|████████▊ | 5428/6167 [53:31<06:00,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/VannDa.jpg

 88%|████████▊ | 5434/6167 [53:32<03:08,  3.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/So_Savoeun.jpg

 88%|████████▊ | 5435/6167 [53:32<03:16,  3.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sinn_Sisamouth.jpg

 88%|████████▊ | 5436/6167 [53:34<05:42,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ros_Serey_Sothea.jpg

 88%|████████▊ | 5437/6167 [53:34<05:17,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preap_Sovath.jpg

 88%|████████▊ | 5438/6167 [53:35<05:44,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pou_Vannary.jpg

 88%|████████▊ | 5439/6167 [53:36<06:15,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pisith_Pilika.jpg

 88%|████████▊ | 5440/6167 [53:36<05:46,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pich_Sophea.jpg

 88%|████████▊ | 5441/6167 [53:37<07:56,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pen_Ron.jpg

 88%|████████▊ | 5442/6167 [53:38<07:48,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meas_Samon.jpg

 88%|████████▊ | 5443/6167 [53:38<07:38,  1.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meas_Soksophea.jpg

 88%|████████▊ | 5444/6167 [53:39<06:20,  1.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mao_Sareth.jpg

 88%|████████▊ | 5445/6167 [53:39<06:52,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Liev_Tuk.jpg

 88%|████████▊ | 5446/6167 [53:40<06:00,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laura_Mam.jpg

 88%|████████▊ | 5453/6167 [53:40<02:18,  5.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chhom_Nimol.jpg

 88%|████████▊ | 5456/6167 [53:41<02:12,  5.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bonny_B..jpg

 88%|████████▊ | 5457/6167 [53:41<02:15,  5.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aok_Sokunkanha.jpg

 89%|████████▊ | 5459/6167 [53:41<02:06,  5.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adda_Angel.jpg

 89%|████████▊ | 5460/6167 [53:42<03:47,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sports.jpg

 89%|████████▊ | 5462/6167 [53:43<03:06,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Music.jpg

 89%|████████▊ | 5463/6167 [53:43<03:49,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Language.jpg

 89%|████████▊ | 5464/6167 [53:44<05:15,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Literature.jpg

 89%|████████▊ | 5465/6167 [53:44<04:53,  2.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dances.jpg

 89%|████████▊ | 5467/6167 [53:45<04:27,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/wine.jpg

 89%|████████▊ | 5468/6167 [53:46<05:58,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cuisine.jpg

 89%|████████▊ | 5469/6167 [53:46<05:19,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coat_of_arms.jpg

 89%|████████▊ | 5470/6167 [53:47<05:19,  2.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cinema.jpg

 89%|████████▊ | 5472/6167 [53:47<04:28,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Religion.jpg

 89%|████████▊ | 5473/6167 [53:48<04:59,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Demographics.jpg

 89%|████████▉ | 5474/6167 [53:49<05:37,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/People.jpg

 89%|████████▉ | 5475/6167 [53:49<05:44,  2.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Languages.jpg

 89%|████████▉ | 5476/6167 [53:51<08:42,  1.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Health.jpg

 89%|████████▉ | 5477/6167 [53:52<10:53,  1.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Education.jpg

 89%|████████▉ | 5478/6167 [53:53<09:49,  1.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Crime.jpg

 89%|████████▉ | 5479/6167 [53:53<08:51,  1.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Transport.jpg

 89%|████████▉ | 5480/6167 [53:54<07:39,  1.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rail.jpg

 89%|████████▉ | 5481/6167 [53:54<06:08,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tourism.jpg

 89%|████████▉ | 5482/6167 [53:54<06:26,  1.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stock_Exchange.jpg

 89%|████████▉ | 5483/6167 [53:55<05:25,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Science_and_technology.jpg

 89%|████████▉ | 5484/6167 [53:56<07:06,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/National_bank.jpg

 89%|████████▉ | 5485/6167 [53:56<07:17,  1.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lev_.jpg

 89%|████████▉ | 5486/6167 [53:57<07:04,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Industry.jpg

 89%|████████▉ | 5487/6167 [53:58<07:24,  1.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Energy.jpg

 89%|████████▉ | 5488/6167 [53:58<06:07,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Economic_statistics.jpg

 89%|████████▉ | 5490/6167 [53:58<04:20,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Prime_Minister.jpg

 89%|████████▉ | 5491/6167 [53:59<04:14,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/President.jpg

 89%|████████▉ | 5492/6167 [53:59<05:21,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chairperson.jpg

 89%|████████▉ | 5493/6167 [54:00<06:22,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/National_Assembly.jpg

 89%|████████▉ | 5494/6167 [54:01<06:36,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chief_of_the_Defence.jpg

 89%|████████▉ | 5495/6167 [54:01<05:54,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Armed_Forces.jpg

 89%|████████▉ | 5496/6167 [54:02<06:29,  1.72it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/enforcement.jpg

 89%|████████▉ | 5498/6167 [54:02<04:21,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/LGBT.jpg

 89%|████████▉ | 5500/6167 [54:03<03:44,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Government.jpg

 89%|████████▉ | 5501/6167 [54:03<04:18,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Foreign_relations.jpg

 89%|████████▉ | 5502/6167 [54:04<05:18,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elections.jpg

 89%|████████▉ | 5503/6167 [54:05<06:04,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Constitution.jpg

 89%|████████▉ | 5504/6167 [54:05<05:17,  2.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sredna_Gora.jpg

 89%|████████▉ | 5505/6167 [54:06<06:18,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rhodope_Mountains.jpg

 89%|████████▉ | 5506/6167 [54:07<06:18,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rila.jpg

 89%|████████▉ | 5507/6167 [54:07<06:25,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Pirin.jpg

 89%|████████▉ | 5508/6167 [54:08<06:24,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Provinces.jpg

 89%|████████▉ | 5509/6167 [54:08<06:21,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Black_Sea_coast.jpg

 89%|████████▉ | 5510/6167 [54:09<06:26,  1.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_Peninsula.jpg

 89%|████████▉ | 5511/6167 [54:10<08:37,  1.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_Mountains.jpg

 89%|████████▉ | 5512/6167 [54:11<08:05,  1.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria_since_1990.jpg

 89%|████████▉ | 5513/6167 [54:11<06:21,  1.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/People's_Republic.jpg

 89%|████████▉ | 5514/6167 [54:11<05:35,  1.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/War_II.jpg

 89%|████████▉ | 5515/6167 [54:12<06:11,  1.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/War_I.jpg

 89%|████████▉ | 5517/6167 [54:13<05:03,  2.14it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/3rd_Tsardom.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Principality.jpg

 89%|████████▉ | 5518/6167 [54:13<04:41,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ottoman_period.jpg

 89%|████████▉ | 5519/6167 [54:14<04:00,  2.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Second_Bulgarian_Empire.jpg

 90%|████████▉ | 5520/6167 [54:14<04:42,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/First_Bulgarian_Empire.jpg

 90%|████████▉ | 5521/6167 [54:15<05:10,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Old_Great_Bulgaria.jpg

 90%|████████▉ | 5522/6167 [54:15<05:07,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Odrysian_kingdom.jpg

 90%|████████▉ | 5523/6167 [54:16<04:45,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Šašić.jpg

 90%|████████▉ | 5524/6167 [54:16<04:22,  2.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Samardžić.jpg

 90%|████████▉ | 5525/6167 [54:16<03:43,  2.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Bebek.jpg

 90%|████████▉ | 5526/6167 [54:16<03:47,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Željko_Joksimović.jpg

 90%|████████▉ | 5528/6167 [54:17<02:37,  4.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šemsa_Suljaković.jpg

 90%|████████▉ | 5531/6167 [54:17<02:13,  4.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šaban_Šaulić.jpg

 90%|████████▉ | 5533/6167 [54:18<02:41,  3.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zoran_Lesendrić.jpg

 90%|████████▉ | 5534/6167 [54:18<02:46,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zdravko_Čolić.jpg

 90%|████████▉ | 5535/6167 [54:19<02:50,  3.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaim_Imamović.jpg

 90%|████████▉ | 5536/6167 [54:19<03:05,  3.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yiannis_Parios.jpg

 90%|████████▉ | 5537/6167 [54:19<03:09,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vlado_Georgiev.jpg

 90%|████████▉ | 5538/6167 [54:19<03:05,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Viki.jpg

 90%|████████▉ | 5539/6167 [54:20<03:05,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesna_Zmijanac.jpg

 90%|████████▉ | 5541/6167 [54:21<04:50,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vasilis_Karras.jpg

 90%|████████▉ | 5542/6167 [54:22<05:04,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toše_Proeski.jpg

 90%|████████▉ | 5543/6167 [54:22<05:22,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tonči_Huljić.jpg

 90%|████████▉ | 5544/6167 [54:23<05:40,  1.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tony_Cetinski.jpg

 90%|████████▉ | 5545/6167 [54:23<04:52,  2.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toma_Zdravković.jpg

 90%|████████▉ | 5546/6167 [54:23<04:12,  2.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tifa.jpg

 90%|████████▉ | 5547/6167 [54:24<03:46,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tijana_Dapčević.jpg

 90%|████████▉ | 5548/6167 [54:24<03:28,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tereza_Kesovija.jpg

 90%|████████▉ | 5549/6167 [54:24<03:37,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Savić.jpg

 90%|████████▉ | 5550/6167 [54:25<03:22,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tanja_Ribič.jpg

 90%|█████████ | 5551/6167 [54:25<03:22,  3.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamara_Todevska.jpg

 90%|█████████ | 5553/6167 [54:25<02:37,  3.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofi_Marinova.jpg

 90%|█████████ | 5554/6167 [54:26<02:57,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stoja.jpg

 90%|█████████ | 5555/6167 [54:27<06:16,  1.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Snežana_Đurišić.jpg

 90%|█████████ | 5556/6167 [54:28<05:27,  1.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slađana_Milošević.jpg

 90%|█████████ | 5558/6167 [54:28<03:37,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvana_Armenulić.jpg

 90%|█████████ | 5559/6167 [54:28<03:35,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Severina.jpg

 90%|█████████ | 5560/6167 [54:29<03:38,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sergej_Ćetković.jpg

 90%|█████████ | 5561/6167 [54:29<04:40,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sertab_Erener.jpg

 90%|█████████ | 5562/6167 [54:30<04:11,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serdar_Ortaç.jpg

 90%|█████████ | 5563/6167 [54:30<03:54,  2.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seka_Aleksić.jpg

 90%|█████████ | 5564/6167 [54:30<03:52,  2.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Bajrami.jpg

 90%|█████████ | 5565/6167 [54:31<03:42,  2.71it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sead_Lipovača.jpg

 90%|█████████ | 5566/6167 [54:31<03:22,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sejo_Sexon.jpg

 90%|█████████ | 5567/6167 [54:31<03:09,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Matić.jpg

 90%|█████████ | 5568/6167 [54:32<03:32,  2.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Lošić.jpg

 90%|█████████ | 5569/6167 [54:32<03:54,  2.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Saša_Kovačević.jpg

 90%|█████████ | 5570/6167 [54:32<03:36,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sara_Jo.jpg

 90%|█████████ | 5571/6167 [54:33<03:27,  2.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sanja_Vučić.jpg

 90%|█████████ | 5572/6167 [54:33<03:28,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sakis_Rouvas.jpg

 90%|█████████ | 5573/6167 [54:33<03:28,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Safet_Isović.jpg

 90%|█████████ | 5574/6167 [54:34<04:42,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rita_Ora.jpg

 90%|█████████ | 5575/6167 [54:34<04:11,  2.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rayna.jpg

 90%|█████████ | 5577/6167 [54:36<05:29,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rambo_Amadeus.jpg

 90%|█████████ | 5578/6167 [54:36<04:38,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preslava.jpg

 90%|█████████ | 5579/6167 [54:36<04:10,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Živković_Tozovac.jpg

 90%|█████████ | 5580/6167 [54:37<03:41,  2.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Predrag_Gojković-Cune.jpg

 90%|█████████ | 5581/6167 [54:37<03:31,  2.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Poli_Genova.jpg

 91%|█████████ | 5582/6167 [54:37<03:20,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Paola.jpg

 91%|█████████ | 5584/6167 [54:38<02:32,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oliver_Dragojević.jpg

 91%|█████████ | 5585/6167 [54:38<02:44,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nora_Istrefi.jpg

 91%|█████████ | 5586/6167 [54:39<03:59,  2.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Noizy.jpg

 91%|█████████ | 5588/6167 [54:39<02:58,  3.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikos_Vertis.jpg

 91%|█████████ | 5589/6167 [54:39<02:56,  3.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nina_Badrić.jpg

 91%|█████████ | 5591/6167 [54:40<02:33,  3.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nikola_Rokvić.jpg

 91%|█████████ | 5592/6167 [54:40<02:35,  3.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nexhmije_Pagarusha.jpg

 91%|█████████ | 5593/6167 [54:40<02:56,  3.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neno_Belan.jpg

 91%|█████████ | 5594/6167 [54:41<02:58,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nevena_Božović.jpg

 91%|█████████ | 5595/6167 [54:41<02:50,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nele_Karajlić.jpg

 91%|█████████ | 5597/6167 [54:41<02:22,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neda_Ukraden.jpg

 91%|█████████ | 5598/6167 [54:42<02:39,  3.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nataša_Bekvalac.jpg

 91%|█████████ | 5599/6167 [54:42<02:40,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Natasa_Theodoridou.jpg

 91%|█████████ | 5600/6167 [54:43<03:04,  3.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Topčagić.jpg

 91%|█████████ | 5601/6167 [54:43<03:09,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nada_Mamula.jpg

 91%|█████████ | 5605/6167 [54:43<01:38,  5.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miša_Aleksić.jpg

 91%|█████████ | 5607/6167 [54:43<01:28,  6.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Ilić.jpg

 91%|█████████ | 5610/6167 [54:44<01:20,  6.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mile_Kitić.jpg

 91%|█████████ | 5611/6167 [54:44<01:32,  5.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milan_Stanković.jpg

 91%|█████████ | 5613/6167 [54:44<01:23,  6.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Merima_Njegomir.jpg

 91%|█████████ | 5615/6167 [54:45<01:39,  5.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maya_Berović.jpg

 91%|█████████ | 5616/6167 [54:45<01:48,  5.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maja_Šuput.jpg

 91%|█████████ | 5617/6167 [54:45<01:57,  4.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marta_Savić.jpg

 91%|█████████ | 5618/6167 [54:46<01:59,  4.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Massimo_Savić.jpg

 91%|█████████ | 5619/6167 [54:46<02:06,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marko_Kon.jpg

 91%|█████████ | 5620/6167 [54:46<02:30,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marinella.jpg

 91%|█████████ | 5621/6167 [54:47<03:53,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marija_Šerifović.jpg

 91%|█████████ | 5622/6167 [54:47<03:38,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Malina.jpg

 91%|█████████ | 5623/6167 [54:48<04:22,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Elena_Kyriakou.jpg

 91%|█████████ | 5625/6167 [54:48<02:49,  3.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Magnifico.jpg

 91%|█████████ | 5627/6167 [54:49<02:15,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Luke_Black.jpg

 91%|█████████▏| 5628/6167 [54:49<02:15,  3.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Lukić.jpg

 91%|█████████▏| 5629/6167 [54:50<04:32,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Brena.jpg

 91%|█████████▏| 5630/6167 [54:50<04:01,  2.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lefteris_Pantazis.jpg

 91%|█████████▏| 5631/6167 [54:51<03:39,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kornelije_Kovač.jpg

 91%|█████████▏| 5633/6167 [54:51<02:37,  3.39it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Konstrakta.jpg

 91%|█████████▏| 5634/6167 [54:52<04:50,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Knez.jpg

 91%|█████████▏| 5636/6167 [54:53<03:17,  2.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kićo_Slabinac.jpg

 91%|█████████▏| 5637/6167 [54:53<02:58,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kenan_Doğulu.jpg

 91%|█████████▏| 5638/6167 [54:53<02:49,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Monteno.jpg

 91%|█████████▏| 5639/6167 [54:54<02:55,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karolina_Gočeva.jpg

 91%|█████████▏| 5640/6167 [54:54<02:43,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamelia.jpg

 91%|█████████▏| 5641/6167 [54:54<02:45,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Katy_Garbi.jpg

 91%|█████████▏| 5642/6167 [54:54<02:35,  3.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kaliopi.jpg

 92%|█████████▏| 5643/6167 [54:55<02:37,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kalomira.jpg

 92%|█████████▏| 5644/6167 [54:55<02:28,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jurica_Pađen.jpg

 92%|█████████▏| 5646/6167 [54:55<01:53,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Josipa_Lisac.jpg

 92%|█████████▏| 5647/6167 [54:55<02:00,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Tomašević.jpg

 92%|█████████▏| 5648/6167 [54:56<03:25,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Rozga.jpg

 92%|█████████▏| 5650/6167 [54:57<02:32,  3.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacques_Houdek.jpg

 92%|█████████▏| 5651/6167 [54:57<02:35,  3.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jelena_Karleuša.jpg

 92%|█████████▏| 5652/6167 [54:57<02:37,  3.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Pogorelić.jpg

 92%|█████████▏| 5654/6167 [54:58<01:57,  4.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Zajc.jpg

 92%|█████████▏| 5655/6167 [54:58<02:13,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivi_Adamou.jpg

 92%|█████████▏| 5656/6167 [54:59<03:15,  2.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inva_Mula.jpg

 92%|█████████▏| 5657/6167 [54:59<03:03,  2.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Inna.jpg

 92%|█████████▏| 5658/6167 [54:59<02:59,  2.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Radić.jpg

 92%|█████████▏| 5659/6167 [55:00<02:49,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Indira_Levak.jpg

 92%|█████████▏| 5660/6167 [55:00<02:59,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ilira.jpg

 92%|█████████▏| 5661/6167 [55:00<02:40,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hurricane.jpg

 92%|█████████▏| 5662/6167 [55:01<03:03,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Himzo_Polovina.jpg

 92%|█████████▏| 5663/6167 [55:01<02:58,  2.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Helena_Paparizou.jpg

 92%|█████████▏| 5664/6167 [55:01<02:43,  3.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hasiba_Agić.jpg

 92%|█████████▏| 5665/6167 [55:01<02:28,  3.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Džinović.jpg

 92%|█████████▏| 5666/6167 [55:02<02:33,  3.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hari_Varešanović.jpg

 92%|█████████▏| 5667/6167 [55:02<02:29,  3.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halid_Bešlić.jpg

 92%|█████████▏| 5668/6167 [55:02<02:25,  3.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hadise.jpg

 92%|█████████▏| 5669/6167 [55:03<02:22,  3.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goran_Bregović.jpg

 92%|█████████▏| 5670/6167 [55:03<02:21,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Goca_Tržan.jpg

 92%|█████████▏| 5671/6167 [55:03<02:14,  3.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gru.jpg

 92%|█████████▏| 5672/6167 [55:04<03:46,  2.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria.jpg

 92%|█████████▏| 5673/6167 [55:04<03:16,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gibonni.jpg

 92%|█████████▏| 5674/6167 [55:06<05:42,  1.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/George_Dalaras.jpg

 92%|█████████▏| 5675/6167 [55:06<04:33,  1.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gergana.jpg

 92%|█████████▏| 5678/6167 [55:06<02:36,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Galena.jpg

 92%|█████████▏| 5679/6167 [55:07<02:47,  2.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fiki.jpg

 92%|█████████▏| 5681/6167 [55:07<02:14,  3.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Esma_Redžepova.jpg

 92%|█████████▏| 5682/6167 [55:07<02:20,  3.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Era_Istrefi.jpg

 92%|█████████▏| 5683/6167 [55:08<02:31,  3.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emanuela.jpg

 92%|█████████▏| 5684/6167 [55:08<02:40,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emina_Jahović.jpg

 92%|█████████▏| 5685/6167 [55:09<02:40,  3.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvir_Laković_Laka.jpg

 92%|█████████▏| 5686/6167 [55:09<02:49,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvana_Gjata.jpg

 92%|█████████▏| 5687/6167 [55:09<02:38,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleni_Foureira.jpg

 92%|█████████▏| 5688/6167 [55:10<02:32,  3.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elhaida_Dani.jpg

 92%|█████████▏| 5689/6167 [55:10<02:20,  3.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elena_Risteska.jpg

 92%|█████████▏| 5690/6167 [55:10<02:13,  3.57it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eleftheria_Eleftheriou.jpg

 92%|█████████▏| 5691/6167 [55:10<02:09,  3.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Maajka.jpg

 92%|█████████▏| 5692/6167 [55:11<02:29,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Džej_Ramadanovski.jpg

 92%|█████████▏| 5693/6167 [55:11<02:32,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Đorđe_Balašević.jpg

 92%|█████████▏| 5695/6167 [55:11<01:49,  4.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dua_Lipa.jpg

 92%|█████████▏| 5696/6167 [55:12<01:57,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragan_Kojić_Keba.jpg

 92%|█████████▏| 5697/6167 [55:12<02:01,  3.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dragana_Mirković.jpg

 92%|█████████▏| 5699/6167 [55:12<01:36,  4.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doris_Dragović.jpg

 92%|█████████▏| 5700/6167 [55:13<02:16,  3.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Merlin.jpg

 92%|█████████▏| 5701/6167 [55:13<02:29,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Dvornik.jpg

 92%|█████████▏| 5702/6167 [55:13<02:22,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Despina_Vandi.jpg

 92%|█████████▏| 5704/6167 [55:14<01:47,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Davorin_Popović.jpg

 93%|█████████▎| 5705/6167 [55:14<01:46,  4.35it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deen.jpg

 93%|█████████▎| 5707/6167 [55:14<02:01,  3.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darko_Rundek.jpg

 93%|█████████▎| 5711/6167 [55:15<01:14,  6.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danijela_Martinović.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dafina_Zeqiri.jpg

 93%|█████████▎| 5712/6167 [55:15<01:16,  5.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dado_Topić.jpg

 93%|█████████▎| 5714/6167 [55:15<01:18,  5.77it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Coby.jpg

 93%|█████████▎| 5715/6167 [55:16<01:50,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Capital_T.jpg

 93%|█████████▎| 5716/6167 [55:16<01:53,  3.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ceca.jpg

 93%|█████████▎| 5719/6167 [55:17<01:21,  5.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Novković.jpg

 93%|█████████▎| 5721/6167 [55:17<01:16,  5.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bora_Đorđević.jpg

 93%|█████████▎| 5722/6167 [55:17<01:21,  5.46it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boban_Rajović.jpg

 93%|█████████▎| 5723/6167 [55:18<01:47,  4.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bleona.jpg

 93%|█████████▎| 5724/6167 [55:18<01:54,  3.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebi_Dol.jpg

 93%|█████████▎| 5725/6167 [55:18<01:55,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bebe_Rexha.jpg

 93%|█████████▎| 5726/6167 [55:18<01:54,  3.87it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beba_Selimović.jpg

 93%|█████████▎| 5727/6167 [55:19<02:18,  3.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azis.jpg

 93%|█████████▎| 5728/6167 [55:19<02:18,  3.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bajaga.jpg

 93%|█████████▎| 5729/6167 [55:20<02:21,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Avni_Mula.jpg

 93%|█████████▎| 5730/6167 [55:20<02:20,  3.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aurela_Gaçe.jpg

 93%|█████████▎| 5731/6167 [55:20<02:47,  2.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ardian_Bujupi.jpg

 93%|█████████▎| 5732/6167 [55:21<02:59,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Arsen_Dedić.jpg

 93%|█████████▎| 5735/6167 [55:21<01:43,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Odobescu.jpg

 93%|█████████▎| 5736/6167 [55:21<01:47,  4.01it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anna_Vissi.jpg

 93%|█████████▎| 5737/6167 [55:22<01:47,  4.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea.jpg

 93%|█████████▎| 5739/6167 [55:22<01:33,  4.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andreea_Bănică.jpg

 93%|█████████▎| 5740/6167 [55:23<02:23,  2.97it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ana_Kokić.jpg

 93%|█████████▎| 5743/6167 [55:23<01:30,  4.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandra_Stan.jpg

 93%|█████████▎| 5744/6167 [55:23<01:39,  4.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aleksandra_Prijović.jpg

 93%|█████████▎| 5745/6167 [55:24<01:44,  4.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Islamović.jpg

 93%|█████████▎| 5746/6167 [55:24<01:46,  3.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alban_Skënderaj.jpg

 93%|█████████▎| 5748/6167 [55:24<01:25,  4.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aki_Rahimovski.jpg

 93%|█████████▎| 5750/6167 [55:25<01:28,  4.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Adrian_Sînă.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aco_Pejović.jpg

 93%|█████████▎| 5751/6167 [55:25<01:44,  4.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aca_Lukas.jpg

 93%|█████████▎| 5752/6167 [55:26<02:37,  2.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 93%|█████████▎| 5754/6167 [55:26<01:52,  3.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 93%|█████████▎| 5755/6167 [55:26<02:06,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 93%|█████████▎| 5756/6167 [55:27<02:15,  3.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 93%|█████████▎| 5757/6167 [55:27<02:13,  3.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zeybek.jpg

 93%|█████████▎| 5759/6167 [55:27<01:38,  4.13it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Oro_(eagle_dance).jpg

 93%|█████████▎| 5760/6167 [55:28<01:38,  4.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Karsilamas.jpg

 93%|█████████▎| 5761/6167 [55:28<01:35,  4.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Čoček.jpg

 93%|█████████▎| 5764/6167 [55:28<01:09,  5.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsamiko.jpg

 93%|█████████▎| 5765/6167 [55:29<01:26,  4.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tamzara.jpg

 93%|█████████▎| 5766/6167 [55:29<01:32,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sousta.jpg

 94%|█████████▎| 5767/6167 [55:30<02:11,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sirtaki.jpg

 94%|█████████▎| 5768/6167 [55:30<02:11,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Syrtos.jpg

 94%|█████████▎| 5770/6167 [55:30<01:36,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kolo.jpg

 94%|█████████▎| 5771/6167 [55:32<03:33,  1.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kochari.jpg

 94%|█████████▎| 5772/6167 [55:32<03:07,  2.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khigga.jpg

 94%|█████████▎| 5775/6167 [55:33<02:13,  2.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hora.jpg

 94%|█████████▎| 5781/6167 [55:33<01:04,  5.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkey.jpg

 94%|█████████▍| 5782/6167 [55:33<01:08,  5.61it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenia.jpg

 94%|█████████▍| 5783/6167 [55:34<01:46,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Serbia.jpg

 94%|█████████▍| 5784/6167 [55:34<01:48,  3.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romania.jpg

 94%|█████████▍| 5786/6167 [55:36<02:42,  2.34it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/North_Macedonia.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegro.jpg

 94%|█████████▍| 5787/6167 [55:36<02:27,  2.58it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Moldova.jpg

 94%|█████████▍| 5789/6167 [55:36<01:49,  3.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greece.jpg

 94%|█████████▍| 5790/6167 [55:37<01:46,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 94%|█████████▍| 5791/6167 [55:37<01:47,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cyprus.jpg

 94%|█████████▍| 5792/6167 [55:37<01:42,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgaria.jpg

 94%|█████████▍| 5793/6167 [55:38<01:56,  3.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatia.jpg

 94%|█████████▍| 5794/6167 [55:38<02:01,  3.06it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnia_and_Herzegovina.jpg

 94%|█████████▍| 5796/6167 [55:38<01:40,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/performers.jpg

 94%|█████████▍| 5797/6167 [55:39<01:44,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yugoslav_pop.jpg

 94%|█████████▍| 5798/6167 [55:39<01:44,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albania.jpg

 94%|█████████▍| 5801/6167 [55:39<01:12,  5.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ganga_music.jpg

 94%|█████████▍| 5803/6167 [55:40<01:08,  5.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Balkan_brass.jpg

 94%|█████████▍| 5807/6167 [55:40<00:50,  7.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani_music.jpg

 94%|█████████▍| 5808/6167 [55:40<00:55,  6.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nisiotika.jpg

 94%|█████████▍| 5809/6167 [55:41<01:01,  5.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turbo-folk.jpg

 94%|█████████▍| 5810/6167 [55:41<01:12,  4.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rebetiko.jpg

 94%|█████████▍| 5812/6167 [55:41<01:05,  5.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Manele.jpg

 94%|█████████▍| 5813/6167 [55:41<01:08,  5.17it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Laïko.jpg

 94%|█████████▍| 5815/6167 [55:42<01:15,  4.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk-pop.jpg

 94%|█████████▍| 5816/6167 [55:42<01:24,  4.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Turkish.jpg

 94%|█████████▍| 5817/6167 [55:42<01:26,  4.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Slovenian.jpg

 94%|█████████▍| 5819/6167 [55:43<01:08,  5.11it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romanian.jpg

 94%|█████████▍| 5820/6167 [55:44<02:08,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Romani.jpg

 94%|█████████▍| 5821/6167 [55:44<01:55,  2.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Montenegrin.jpg

 94%|█████████▍| 5822/6167 [55:44<01:47,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Macedonian.jpg

 94%|█████████▍| 5823/6167 [55:44<01:46,  3.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Greek.jpg

 94%|█████████▍| 5824/6167 [55:45<01:44,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Croatian.jpg

 94%|█████████▍| 5825/6167 [55:45<01:44,  3.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bulgarian.jpg

 94%|█████████▍| 5826/6167 [55:45<01:46,  3.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bosnian.jpg

 94%|█████████▍| 5827/6167 [55:46<02:32,  2.24it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Folk.jpg

 95%|█████████▍| 5828/6167 [55:47<02:20,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Albanian.jpg

 95%|█████████▍| 5834/6167 [55:47<01:00,  5.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/doi.jpg

 95%|█████████▍| 5836/6167 [55:48<01:05,  5.04it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Grove_Music_Online.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/doi.jpg

 95%|█████████▍| 5837/6167 [55:48<01:14,  4.43it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Grove_Music_Online.jpg

 95%|█████████▍| 5840/6167 [55:48<01:09,  4.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yuri_Boukoff.jpg

 95%|█████████▍| 5841/6167 [55:49<01:34,  3.45it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yordanka_Hristova.jpg

 95%|█████████▍| 5842/6167 [55:49<01:38,  3.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yoan_Kukuzel.jpg

 95%|█████████▍| 5843/6167 [55:51<02:43,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Yildiz_Ibrahimova.jpg

 95%|█████████▍| 5844/6167 [55:51<02:51,  1.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vladimir_Stoyanov.jpg

 95%|█████████▍| 5846/6167 [55:52<02:21,  2.27it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Victoria_Georgieva.jpg

 95%|█████████▍| 5847/6167 [55:53<02:38,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesselina_Kasarova.jpg

 95%|█████████▍| 5848/6167 [55:54<04:22,  1.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vesko_Eschkenazy.jpg

 95%|█████████▍| 5850/6167 [55:55<03:07,  1.69it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ventsislav_Yankov.jpg

 95%|█████████▍| 5851/6167 [55:56<03:25,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vassil_Naidenov.jpg

 95%|█████████▍| 5853/6167 [55:56<02:42,  1.94it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vanya_Shtereva.jpg

 95%|█████████▍| 5854/6167 [55:57<02:50,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Vanya_Kostova.jpg

 95%|█████████▍| 5855/6167 [55:58<02:49,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Valya_Balkanska.jpg

 95%|█████████▌| 5859/6167 [55:59<01:51,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tsvetelina.jpg

 95%|█████████▌| 5860/6167 [55:59<02:16,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toni_Storaro.jpg

 95%|█████████▌| 5861/6167 [56:00<02:24,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Toma_Zdravkov.jpg

 95%|█████████▌| 5862/6167 [56:01<02:44,  1.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Todor_Kolev.jpg

 95%|█████████▌| 5863/6167 [56:02<03:01,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Todor_Kobakov.jpg

 95%|█████████▌| 5864/6167 [56:02<03:09,  1.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Tita.jpg

 95%|█████████▌| 5865/6167 [56:03<03:03,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Theodosii_Spassov.jpg

 95%|█████████▌| 5867/6167 [56:04<03:18,  1.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Svetla_Vassileva.jpg

 95%|█████████▌| 5869/6167 [56:05<02:34,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Svetla_Protich.jpg

 95%|█████████▌| 5870/6167 [56:06<02:57,  1.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Suzanitta.jpg

 95%|█████████▌| 5872/6167 [56:06<02:07,  2.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stefan_Valdobrev.jpg

 95%|█████████▌| 5873/6167 [56:06<01:58,  2.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Stefan_Dimitrov.jpg

 95%|█████████▌| 5875/6167 [56:07<01:30,  3.22it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sofi_Marinova.jpg

 95%|█████████▌| 5876/6167 [56:07<02:00,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sonya_Yoncheva.jpg

 95%|█████████▌| 5880/6167 [56:09<01:55,  2.47it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ruslan_Maynov.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rumyana.jpg

 95%|█████████▌| 5883/6167 [56:10<01:36,  2.95it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raina_Kabaivanska.jpg

 95%|█████████▌| 5884/6167 [56:11<01:50,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raffi_Boghosyan.jpg

 95%|█████████▌| 5885/6167 [56:11<01:42,  2.76it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Raffaele_Arié.jpg

 95%|█████████▌| 5886/6167 [56:12<02:06,  2.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Radka_Toneff.jpg

 95%|█████████▌| 5888/6167 [56:12<01:30,  3.09it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Preslava.jpg

 95%|█████████▌| 5889/6167 [56:12<01:30,  3.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Poli_Genova.jpg

 96%|█████████▌| 5890/6167 [56:13<01:58,  2.33it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Petko_Staynov.jpg

 96%|█████████▌| 5891/6167 [56:13<02:11,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Petia.jpg

 96%|█████████▌| 5892/6167 [56:14<02:19,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Baykov.jpg

 96%|█████████▌| 5893/6167 [56:15<02:32,  1.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Penka_Toromanova.jpg

 96%|█████████▌| 5895/6167 [56:15<02:03,  2.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Orlin_Goranov.jpg

 96%|█████████▌| 5898/6167 [56:16<01:11,  3.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nicola_Ghiuselev.jpg

 96%|█████████▌| 5900/6167 [56:16<01:25,  3.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Neva_Krysteva.jpg

 96%|█████████▌| 5902/6167 [56:17<01:20,  3.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nayden_Todorov.jpg

 96%|█████████▌| 5906/6167 [56:18<01:03,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miroslav_Kostadinov.jpg

 96%|█████████▌| 5907/6167 [56:18<01:22,  3.15it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mira_Aroyo.jpg

 96%|█████████▌| 5908/6167 [56:19<01:42,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mimi_Balkanska.jpg

 96%|█████████▌| 5909/6167 [56:20<02:16,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milko_Kalaidjiev.jpg

 96%|█████████▌| 5911/6167 [56:21<01:54,  2.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milena_Slavova.jpg

 96%|█████████▌| 5912/6167 [56:21<01:57,  2.16it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Milen_E._Ivanov.jpg

 96%|█████████▌| 5915/6167 [56:22<01:28,  2.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mila_Robert.jpg

 96%|█████████▌| 5916/6167 [56:23<02:03,  2.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mihaela_Fileva.jpg

 96%|█████████▌| 5917/6167 [56:24<02:09,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michail_Svetlev.jpg

 96%|█████████▌| 5918/6167 [56:25<02:17,  1.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Michail_Belchev.jpg

 96%|█████████▌| 5920/6167 [56:25<02:02,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marius_Kurkinski.jpg

 96%|█████████▌| 5922/6167 [56:26<01:41,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mariana_Popova.jpg

 96%|█████████▌| 5923/6167 [56:27<02:12,  1.84it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Mitzeva.jpg

 96%|█████████▌| 5924/6167 [56:28<03:05,  1.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Ilieva.jpg

 96%|█████████▌| 5925/6167 [56:30<04:03,  1.01s/it]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Maria_Christova.jpg

 96%|█████████▌| 5929/6167 [56:31<01:58,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lyudmila_Radkova.jpg

 96%|█████████▌| 5930/6167 [56:32<02:33,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lyubka_Rondova.jpg

 96%|█████████▌| 5931/6167 [56:33<02:31,  1.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ludmilla_Diakovska.jpg

 96%|█████████▌| 5932/6167 [56:33<02:32,  1.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lubo_Kirov.jpg

 96%|█████████▌| 5933/6167 [56:34<02:24,  1.62it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ljuba_Welitsch.jpg

 96%|█████████▌| 5934/6167 [56:35<02:33,  1.52it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lili_Ivanova.jpg

 96%|█████████▋| 5938/6167 [56:36<01:30,  2.53it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kristian_Kostov.jpg

 96%|█████████▋| 5939/6167 [56:36<01:36,  2.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Krisia_Todorova.jpg

 96%|█████████▋| 5943/6167 [56:37<01:06,  3.36it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kiril_Manolov.jpg

 96%|█████████▋| 5944/6167 [56:38<01:21,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kiril_Marichkov.jpg

 96%|█████████▋| 5945/6167 [56:38<01:38,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kamen_Tchanev.jpg

 96%|█████████▋| 5948/6167 [56:39<01:16,  2.85it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Julia_Tsenova.jpg

 96%|█████████▋| 5949/6167 [56:40<01:20,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jacob_Soulliere.jpg

 96%|█████████▋| 5951/6167 [56:40<01:19,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivo_Papazov.jpg

 97%|█████████▋| 5952/6167 [56:41<01:32,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivana.jpg

 97%|█████████▋| 5953/6167 [56:42<01:44,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ivan_Yanakov.jpg

 97%|█████████▋| 5956/6167 [56:42<01:12,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iliya_Argirov.jpg

 97%|█████████▋| 5957/6167 [56:43<01:11,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gloria.jpg

 97%|█████████▋| 5959/6167 [56:43<00:54,  3.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gergana.jpg

 97%|█████████▋| 5960/6167 [56:43<01:08,  3.03it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Georgi_Minchev.jpg

 97%|█████████▋| 5961/6167 [56:44<01:25,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Georgi_Belev.jpg

 97%|█████████▋| 5963/6167 [56:45<01:19,  2.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Gena_Dimitrova.jpg

 97%|█████████▋| 5964/6167 [56:45<01:20,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Galena.jpg

 97%|█████████▋| 5965/6167 [56:46<01:22,  2.44it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fiki.jpg

 97%|█████████▋| 5967/6167 [56:46<01:16,  2.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emil_Dimitrov.jpg

 97%|█████████▋| 5968/6167 [56:47<01:22,  2.42it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emanuela.jpg

 97%|█████████▋| 5969/6167 [56:47<01:27,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elitsa_Todorova.jpg

 97%|█████████▋| 5971/6167 [56:48<01:14,  2.63it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dzhena.jpg

 97%|█████████▋| 5972/6167 [56:49<01:24,  2.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dzhina_Stoeva.jpg

 97%|█████████▋| 5973/6167 [56:51<02:42,  1.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Doni.jpg

 97%|█████████▋| 5975/6167 [56:51<01:56,  1.64it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deyan_Nedelchev.jpg

 97%|█████████▋| 5979/6167 [56:52<01:07,  2.80it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Darina_Takova.jpg

 97%|█████████▋| 5980/6167 [56:53<01:22,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Danny_Levan.jpg

 97%|█████████▋| 5981/6167 [56:53<01:32,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Daniela_Radkova.jpg

 97%|█████████▋| 5983/6167 [56:54<01:21,  2.26it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Christina_Morfova.jpg

 97%|█████████▋| 5985/6167 [56:55<01:15,  2.41it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ciguli.jpg

 97%|█████████▋| 5986/6167 [56:56<01:31,  1.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Komitov.jpg

 97%|█████████▋| 5989/6167 [56:57<01:17,  2.30it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boris_Christoff.jpg

 97%|█████████▋| 5990/6167 [56:57<01:23,  2.12it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Boiko_Zvetanov.jpg

 97%|█████████▋| 5991/6167 [56:58<01:23,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bogdana_Karadocheva.jpg

 97%|█████████▋| 5992/6167 [56:59<01:28,  1.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Biser_Kirov.jpg

 97%|█████████▋| 5994/6167 [56:59<01:23,  2.08it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Bedros_Kirkorov.jpg

 97%|█████████▋| 5996/6167 [57:00<01:08,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Azis.jpg

 97%|█████████▋| 5997/6167 [57:01<01:15,  2.25it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Armand_Tokatyan.jpg

 97%|█████████▋| 5998/6167 [57:01<01:24,  2.00it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aron_Aronov.jpg

 97%|█████████▋| 6002/6167 [57:02<00:49,  3.31it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anelia.jpg

 97%|█████████▋| 6004/6167 [57:03<01:04,  2.51it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Andrea.jpg

 97%|█████████▋| 6006/6167 [57:04<01:00,  2.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alisia.jpg

 97%|█████████▋| 6007/6167 [57:05<01:22,  1.93it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexis_Weissenberg.jpg

 97%|█████████▋| 6009/6167 [57:06<01:15,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexandrina_Miltcheva.jpg

 97%|█████████▋| 6011/6167 [57:07<01:16,  2.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alek_Sandar.jpg

 98%|█████████▊| 6015/6167 [57:09<01:15,  2.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Mulahalilović.jpg

 98%|█████████▊| 6019/6167 [57:09<00:48,  3.05it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šemsa_Suljaković.jpg

 98%|█████████▊| 6020/6167 [57:10<00:53,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šako_Polumenta.jpg

 98%|█████████▊| 6021/6167 [57:10<00:50,  2.86it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Šaban_Šaulić.jpg

 98%|█████████▊| 6026/6167 [57:11<00:33,  4.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Malovčić.jpg

 98%|█████████▊| 6028/6167 [57:11<00:29,  4.66it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Haris_Džinović.jpg

 98%|█████████▊| 6030/6167 [57:11<00:27,  4.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Halid_Bešlić.jpg

 98%|█████████▊| 6036/6167 [57:12<00:21,  6.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zekerijah_Đezić.jpg

 98%|█████████▊| 6037/6167 [57:13<00:30,  4.32it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zehra_Deović.jpg

 98%|█████████▊| 6038/6167 [57:14<00:47,  2.70it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zaim_Imamović.jpg

 98%|█████████▊| 6039/6167 [57:15<00:53,  2.38it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Umihana_Čuvidina.jpg

 98%|█████████▊| 6040/6167 [57:15<00:50,  2.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Silvana_Armenulić.jpg

 98%|█████████▊| 6041/6167 [57:15<00:45,  2.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Safet_Isović.jpg

 98%|█████████▊| 6043/6167 [57:16<00:42,  2.90it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Meho_Puzić.jpg

 98%|█████████▊| 6044/6167 [57:16<00:42,  2.92it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Himzo_Polovina.jpg

 98%|█████████▊| 6046/6167 [57:17<00:34,  3.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hanka_Paldum.jpg

 98%|█████████▊| 6048/6167 [57:17<00:34,  3.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dina_Bajraktarević.jpg

 98%|█████████▊| 6049/6167 [57:18<00:39,  2.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Damir_Imamović.jpg

 98%|█████████▊| 6050/6167 [57:18<00:38,  3.02it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beba_Selimović.jpg

 98%|█████████▊| 6051/6167 [57:18<00:42,  2.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jala_Brat.jpg

 98%|█████████▊| 6053/6167 [57:19<00:31,  3.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Edo_Maajka.jpg

 98%|█████████▊| 6056/6167 [57:19<00:20,  5.49it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Sead_Lipovača.jpg

 98%|█████████▊| 6057/6167 [57:19<00:22,  4.81it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Hari_Varešanović.jpg

 98%|█████████▊| 6058/6167 [57:20<00:23,  4.55it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elvir_Laković_Laka.jpg

 98%|█████████▊| 6059/6167 [57:22<01:05,  1.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Cem_Adrian.jpg

 98%|█████████▊| 6060/6167 [57:23<01:26,  1.23it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alen_Islamović.jpg

 98%|█████████▊| 6061/6167 [57:23<01:17,  1.37it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Branko_Đurić.jpg

 98%|█████████▊| 6062/6167 [57:25<01:35,  1.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Zuzi_Zu.jpg

 98%|█████████▊| 6065/6167 [57:25<00:49,  2.07it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Selma_Bajrami.jpg

 98%|█████████▊| 6066/6167 [57:25<00:44,  2.29it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Seka_Aleksić.jpg

 98%|█████████▊| 6070/6167 [57:26<00:27,  3.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Peter_Nalitch.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Nino_Pršeš.jpg

 98%|█████████▊| 6071/6167 [57:26<00:26,  3.65it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Marija_Šerifović.jpg

 98%|█████████▊| 6074/6167 [57:27<00:18,  4.99it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Lepa_Brena.jpg

 99%|█████████▊| 6076/6167 [57:27<00:19,  4.67it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Kemal_Monteno.jpg
✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Fazla.jpg

 99%|█████████▊| 6077/6167 [57:27<00:20,  4.40it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Emina_Jahović.jpg

 99%|█████████▊| 6079/6167 [57:28<00:21,  4.18it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Eldin_Huseinbegović.jpg

 99%|█████████▊| 6080/6167 [57:28<00:22,  3.83it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dženy.jpg

 99%|█████████▊| 6081/6167 [57:29<00:22,  3.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Merlin.jpg

 99%|█████████▊| 6082/6167 [57:29<00:28,  2.98it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Donna_Ares.jpg

 99%|█████████▊| 6084/6167 [57:29<00:21,  3.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Deen.jpg

 99%|█████████▊| 6086/6167 [57:30<00:22,  3.60it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dalal_Midhat-Talakić.jpg

 99%|█████████▉| 6090/6167 [57:31<00:18,  4.19it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Anabela_Atijas.jpg

 99%|█████████▉| 6092/6167 [57:32<00:19,  3.82it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aida_Čorbadžić.jpg

 99%|█████████▉| 6093/6167 [57:33<00:29,  2.54it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Jasmin_Bašić.jpg

 99%|█████████▉| 6095/6167 [57:35<00:41,  1.74it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ismet_Alajbegović_Šerbo.jpg

 99%|█████████▉| 6096/6167 [57:36<00:59,  1.20it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dino_Zonić.jpg

 99%|█████████▉| 6098/6167 [57:37<00:41,  1.68it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Alexander_von_Zemlinsky.jpg

 99%|█████████▉| 6099/6167 [57:37<00:39,  1.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Chris_Rolle.jpg

 99%|█████████▉| 6101/6167 [57:38<00:31,  2.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rexy_Rolle.jpg

 99%|█████████▉| 6102/6167 [57:39<00:34,  1.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Johnny_Kemp.jpg

 99%|█████████▉| 6103/6167 [57:39<00:36,  1.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Iris_Stryx.jpg

 99%|█████████▉| 6110/6167 [57:40<00:13,  4.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Brettina.jpg

 99%|█████████▉| 6112/6167 [57:41<00:15,  3.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ubaidullah_Jan.jpg

 99%|█████████▉| 6122/6167 [57:41<00:05,  7.88it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Rukhshana.jpg

 99%|█████████▉| 6134/6167 [57:42<00:02, 11.89it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Naghma.jpg

100%|█████████▉| 6139/6167 [57:42<00:02, 10.21it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Miri_Maftun.jpg

100%|█████████▉| 6143/6167 [57:43<00:02, 10.91it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Mozhdah_Jamalzadah.jpg

100%|█████████▉| 6146/6167 [57:43<00:02,  9.48it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Khyal_Muhammad.jpg

100%|█████████▉| 6150/6167 [57:44<00:01,  9.73it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Farid_Zaland.jpg

100%|█████████▉| 6152/6167 [57:44<00:01,  7.50it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Farhad_Darya.jpg

100%|█████████▉| 6153/6167 [57:44<00:02,  6.75it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Elaha_Soroor.jpg

100%|█████████▉| 6154/6167 [57:45<00:02,  4.96it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ehsan_Aman.jpg

100%|█████████▉| 6155/6167 [57:45<00:02,  4.56it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Dawood_Sarkhosh.jpg

100%|█████████▉| 6157/6167 [57:46<00:02,  3.79it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Beltoon.jpg

100%|█████████▉| 6164/6167 [57:47<00:00,  6.59it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Aryana_Sayeed.jpg

100%|█████████▉| 6165/6167 [57:48<00:00,  4.10it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ahmad_Zahir.jpg

100%|██████████| 6167/6167 [57:48<00:00,  1.78it/s]

✓ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/other_nation_wiki/Ahmad_Wali.jpg