In [1]:
import os
import json
from glob import glob
from pathlib import Path
from urllib.parse import urlparse

import httpx
from tqdm import tqdm
import pandas as pd
from dotenv import load_dotenv
from huggingface_hub import login
from datasets import Dataset, load_dataset


ROOT_DIR = Path("../").resolve()
DATA_DIR = ROOT_DIR / "data"

/home/octoopt/workspace/projects/personal/data_enrichment/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def init_login():
    load_dotenv()
    login(os.getenv("HUGGINGFACE_TOKEN"))
    print("Login successful")

In [ ]:
import os
import httpx
import random

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/121.0",
]

def download_image(image_url, save_path, timeout=10):
    """
    Download an image from a URL and save it to the specified path using httpx.
    """
    # try:
    headers = {
        "User-Agent": random.choice(USER_AGENTS),
        "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive",
    }

    with httpx.Client(follow_redirects=True) as client:
        response = client.get(image_url, headers=headers, timeout=timeout)
        response.raise_for_status()  # raise error if 403/404 etc.

        # Create directory if needed
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

        with open(save_path, "wb") as f:
            f.write(response.content)

    return True

    # except httpx.HTTPStatusError as e:
    #     print(f"❌ HTTP error {e.response.status_code} for {image_url}")
    # except Exception as e:
    #     print(f"❌ Failed to download {image_url}: {e}")

    return False


def read_json(file_path):
    """Read and return data from a JSON file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"✗ File not found: {file_path}")
        return None
    except json.JSONDecodeError as e:
        print(f"✗ Invalid JSON in {file_path}: {e}")
        return None


def write_json(data, file_path, indent=4):
    """Write data to a JSON file."""
    try:
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=indent, ensure_ascii=False)
        print(f"✓ Written JSON to: {file_path}")
        return True
    except Exception as e:
        print(f"✗ Error writing JSON: {e}")
        return False

## Old days

In [8]:
DATASET_DIR = DATA_DIR / "wiki_thai_people_artist.json"

In [9]:
ds = pd.read_json(str(DATASET_DIR))
ds.head()

,profile_url,name,gender,image_url,metadata,description
0,https://en.wikipedia.org/wiki/4Eve,,,https://upload.wikimedia.org/wikipedia/commons...,"{'Origin': 'Bangkok, Thailand', 'Genres': 'T-p...",is a Thai girl group formed in 2020. The group...
1,https://en.wikipedia.org/wiki/Four-Mod,,,https://upload.wikimedia.org/wikipedia/commons...,"{'Origin': 'Bangkok , Thailand', 'Genres': 'Po...",(โฟร์-มด) was a duo which formed in 2005. Th...
2,https://en.wikipedia.org/wiki/Fonthip_Watchara...,Fonthip Watcharatrakul,,https://upload.wikimedia.org/wikipedia/commons...,"{'Born': '( 1990-07-19 ) July 19, 1990 (age 35...","( : ,"
3,https://en.wikipedia.org/wiki/Florence_Faivre,Florence Faivre,,https://upload.wikimedia.org/wikipedia/commons...,{'Born': 'Florence Vanida Faivre ( 1983-06-08 ...,( :
4,https://en.wikipedia.org/wiki/Sarocha_Chankimha,Sarocha Chankimha,,https://upload.wikimedia.org/wikipedia/commons...,{'Born': 'Sarocha Chankimha ( 1998-08-08 ) 8 A...,( :

In [10]:
ds = ds.drop(columns=["image_url"])
ds.head()

,name,url,summary,categories,timestamp
0,Sacheus !Gonteb,https://en.wikipedia.org/wiki/Sacheus_!Gonteb,Rear Admiral Sacheus Randy !Gonteb is a Namibi...,"[Articles with short description, Living peopl...",2025-08-02 04:53:49.485904
1,1.Cuz,https://en.wikipedia.org/wiki/1.Cuz,"Abas Abdikarim Bakar, better known as 1.Cuz (b...","[1997 births, 21st-century male rappers, Artic...",2025-08-02 04:53:51.707057
2,1da Banton,https://en.wikipedia.org/wiki/1da_Banton,"Godson Ominibie Epelle, professionally known a...","[1994 births, 21st-century Nigerian musicians,...",2025-08-02 04:53:54.208175
3,1nonly,https://en.wikipedia.org/wiki/1nonly,"Nathan Scott Fuller (born April 6, 2004), bett...","[2004 births, 21st-century American male rappe...",2025-08-02 04:53:56.621336
4,1ucid,https://en.wikipedia.org/wiki/1ucid,"Kwadwo Bedihene, known professionally as 1ucid...","[20th-century births, Afrobeats musicians, All...",2025-08-02 04:53:59.252879

In [12]:
hf_ds = Dataset.from_pandas(df=ds)
hf_ds

Dataset({
    features: ['name', 'url', 'summary', 'categories', 'timestamp'],
    num_rows: 1300
})

In [14]:
data_id = "minhleduc/wiki_famous_person_00"

hf_ds.push_to_hub(data_id, commit_message="Initial commit")

Creating parquet from Arrow format: 100%|██████████| 2/2 [00:00<00:00, 92.34ba/s]
Uploading the dataset shards: 100%|██████████| 1/1 [00:03<00:00,  3.07s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/minhleduc/wiki_famous_person_00/commit/1fd688c7abaa1f6cbf506a834c2a75cbacca7549', commit_message='Initial commit', commit_description='', oid='1fd688c7abaa1f6cbf506a834c2a75cbacca7549', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/minhleduc/wiki_famous_person_00', endpoint='https://huggingface.co', repo_type='dataset', repo_id='minhleduc/wiki_famous_person_00'), pr_revision=None, pr_num=None)

## 02.10.2025

In [ ]:
datafile = str(DATA_DIR / "raw" / "22102025" / ".json")
json_data = read_json(datafile)

In [5]:
# datafile = str(DATA_DIR / "german" / "politicians")
datafile = str(DATA_DIR / "wiki_other_nations")
datapaths = glob(datafile + "/**.json")
datapaths

['/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_002.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_003.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/wiki_other_nations/other_country_singer_001.json']

In [6]:
politician_profiles = []

for path in datapaths:
    json_data = read_json(file_path=path)
    politician_profiles += json_data


len(politician_profiles)

6167

In [7]:
politician_profiles[10]

{'title': 'Lauri Ylönen',
 'url': 'https://en.wikipedia.org/wiki/Lauri_Yl%C3%B6nen',
 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/The_Rasmus_-_2025250_125352_2025-09-07_ZDF-Fernsehgarten_-_Sven_-_5DS_R_-_0115_-_5DSR3551_%28cropped%3B_Lauri_Yl%C3%B6nen%29.jpg/250px-The_Rasmus_-_2025250_125352_2025-09-07_ZDF-Fernsehgarten_-_Sven_-_5DS_R_-_0115_-_5DSR3551_%28cropped%3B_Lauri_Yl%C3%B6nen%29.jpg',
 'summary': 'Lauri Johannes Ylönen (born 23 April 1979) is a Finnish singer-songwriter, best known as the co-founder and frontman of the Finnish alternative rock band The Rasmus .',
 'infobox': {'Born': '( 1979-04-23 ) 23 April 1979 (age\xa046) Helsinki , Finland',
  'Occupation': 'Singer/songwriter',
  'Instrument(s)': 'Vocals , guitar , piano',
  'Labels': 'Playground Music Universal Music ( Finland )',
  'Website': 'amanda.fm'}}

In [4]:
write_json(data=politician_profiles, 
file_path=DATA_DIR / "wiki_other_nations" / "other_country_singer.json")

NameError: name 'politician_profiles' is not defined

In [6]:
count = 0

save_dir = str(DATA_DIR / "images" / "other_nation_wiki")

for idx in tqdm(range(len(politician_profiles))):
    data = politician_profiles[idx]
    image_url = data["image_url"]
    if not image_url:
        continue
    name = data["title"].replace(" ", "_")
    local_path = f"{save_dir}/{name}.jpg"
    data['local_path'] = local_path
    download_image(image_url, local_path)

NameError: name 'politician_profiles' is not defined

In [26]:
filepath = str(DATA_DIR / "raw" / "22102025")
datapaths = glob(filepath + "/onthisday*.json")
datapaths

['/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_people_001.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_gen_lost.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_genalpha.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_genx.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_gen_silent.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_genz.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_genbabyboomer.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/raw/22102025/onthisday_gen_millenials.json']

In [19]:
def _get_name_from_url(image_url: str):
    image_name = image_url.split("/")[-1]
    name = image_name.split("-")[: -1]
    return " ".join(name).strip().title()



_get_name_from_url(image_url="https://www.thefamouspeople.com/profiles/thumbs/annette-lu-1.jpg")

'Annette Lu'

In [27]:
final_profiles = []

for filepath in datapaths:
    profiles = read_json(file_path=filepath)

    for profile in profiles:
        data = {}
        image_url = profile.get('image_url', '')
        if not image_url: 
            print(f"Image URL is missing for profile: {profile}")
            continue

        profile_name = profile.get('name', '')
        if not profile_name:
            profile_name = _get_name_from_url(image_url=image_url)
        profile_name = profile_name.title()

        data['name'] = profile_name
        data['mainType'] = profile.get('mainType', '')
        data['dateOfBirth'] =profile.get('dateOfBirth', '')
        data['homePlace'] =profile.get('homePlace', '')
        data['workPlace'] = profile.get('workPlace', '')

        # description = '\n\n'.join([profile.get('about', ''), profile.get('beforeFame', ''), profile.get('trivia', '')])
        description = profile.get('about', '')
        gender = profile.get('gender', '')

        if not gender: 
            if "He" in description:
                gender = "Male"
            elif "She" in description:
                gender = "Female"
            else:
                gender = ""

        data['gender'] = gender


        data['image_url'] = profile.get('image_url', '')
        data['profile_url'] =profile.get('profile_url', '')

        metadata = {
            "sunSign": profile.get('sunSign', ''),  
            'description': description
        }
        data['metadata'] = metadata
        final_profiles.append(data)

len(final_profiles)

Image URL is missing for profile: {'profile_url': '', 'name': '', 'mainType': '', 'image_url': '', 'homePlace': '', 'gender': '', 'dateOfBirth': '', 'nationality': '', 'about': ''}

3592

In [ ]:
# final_profiles = []
# DATASET_DIR = DATA_DIR / "thailand_profiles.json"
# profiles = read_json(file_path=str(DATASET_DIR))

# for profile in profiles:
#     data = {}
#     profile_name = profile.get('name', '').title()
#     image_url = profile.get('image_url', '')
#     metadata = profile.get('metadata', {})
#     if not profile_name:
#         image_name = image_url.split('/')[-1].split('.')[0]
#         image_name_components = image_name.split('-')[:-1]
#         profile_name = ' '.join(image_name_components).title()
#     data['name'] = profile_name
#     data['mainType'] = metadata.get('Occupations', '')
#     data['dateOfBirth'] =metadata.get('Born', '')
#     data['homePlace'] =metadata.get('Labels', '')
#     data['workPlace'] = metadata.get('workPlace', 'Thailand')
#     data['gender'] =profile.get('gender', '')


#     data['image_url'] = profile.get('image_url', '')
#     data['profile_url'] =profile.get('profile_url', '')
#     data['metadata'] = metadata

#     final_profiles.append(data)

# len(final_profiles)

200

In [30]:
filepath = str(DATA_DIR)
datapaths = glob(filepath + "/20252210*.json")
datapaths

['/home/octoopt/workspace/projects/personal/data_enrichment/data/20252210_001_fmppl_bf.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/20252210_003_fmppl_bf.json',
 '/home/octoopt/workspace/projects/personal/data_enrichment/data/20252210_002_fmppl_bf.json']

In [31]:
merged_profiles = []

for filepath in datapaths:
    profiles = read_json(filepath)
    merged_profiles += profiles

len(merged_profiles)

8920

In [ ]:
write_json(
    data=final_profiles, 
    # data=merged_profiles, 
        file_path='../data/20252210_mrgdprf_bf.json', 
)

✓ Written JSON to: ../data/20252210_mrgdprf_bf.json

True

In [40]:
final_profiles = read_json(file_path=str(DATA_DIR / "20252210_mrgdprf_bf.json"))

len(final_profiles)

8920

In [41]:
"""
Only get profile that get image
"""

usable_profiles = []
save_dir = str(DATA_DIR / "images" / "20252210_mrgdprf")


for idx in tqdm(range(len(final_profiles))):
    try:
        profile = final_profiles[idx]
        image_url = profile['image_url']
        img_name = profile["name"].replace(" ", "_")
        local_path = f"{save_dir}/{img_name}.jpg"
        profile['local_path'] = local_path
        is_success = download_image(image_url, local_path)
        if is_success:
            usable_profiles.append(profile)

    except Exception as e:
        print(e)
        continue

  0%|          | 1/8920 [00:01<2:53:44,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charli_Damelio.jpg

  0%|          | 2/8920 [00:01<1:42:51,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khabane_Lame.jpg

  0%|          | 3/8920 [00:02<1:58:18,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kio_Cyr.jpg

  0%|          | 4/8920 [00:04<3:30:01,  1.41s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kanan_Hunt.jpg

  0%|          | 5/8920 [00:05<3:02:50,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bella_Poarch_101462.jpg

  0%|          | 6/8920 [00:06<2:15:46,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dixie_Damelio.jpg

  0%|          | 7/8920 [00:07<3:00:20,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Bartolozzi.jpg

  0%|          | 8/8920 [00:08<2:17:43,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Magusara.jpg

  0%|          | 9/8920 [00:08<2:00:14,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooke_Monk_75031.jpg

  0%|          | 10/8920 [00:09<2:04:16,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Swagboyq.jpg

  0%|          | 11/8920 [00:10<2:14:22,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oneya_Johnson.jpg

  0%|          | 12/8920 [00:10<1:45:40,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Williams.jpg

  0%|          | 13/8920 [00:11<1:26:50,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Qgriggs.jpg

  0%|          | 14/8920 [00:12<1:41:58,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kbreeezo.jpg

  0%|          | 15/8920 [00:14<2:44:10,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Victor_Mackie.jpg

  0%|          | 16/8920 [00:15<2:49:30,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Reeves.jpg

  0%|          | 17/8920 [00:18<4:12:58,  1.70s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nic_Kaufmann.jpg

  0%|          | 18/8920 [00:23<6:38:44,  2.69s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sora_Simmons_120389.jpg

  0%|          | 19/8920 [00:25<6:14:34,  2.52s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhong.jpg

  0%|          | 20/8920 [00:30<8:11:07,  3.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahmad_Najya.jpg

  0%|          | 21/8920 [00:32<6:45:53,  2.74s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paradiisedd.jpg

  0%|          | 22/8920 [00:32<4:56:58,  2.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Anastasio.jpg

  0%|          | 23/8920 [00:32<3:40:05,  1.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaayyyaaaa.jpg

  0%|          | 24/8920 [00:33<3:08:15,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dom_Brack_75386.jpg

  0%|          | 25/8920 [00:34<3:11:16,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liane_Valenzuela.jpg

  0%|          | 26/8920 [00:35<3:05:12,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jayden_Bartels.jpg

  0%|          | 27/8920 [00:37<3:36:42,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessya_Farrugia.jpg

  0%|          | 28/8920 [00:42<5:37:31,  2.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sharan_Jones.jpg

  0%|          | 29/8920 [00:45<6:43:22,  2.72s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabrina_Quesada.jpg

  0%|          | 30/8920 [00:46<5:18:32,  2.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dtay.jpg

  0%|          | 31/8920 [00:49<5:46:19,  2.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Austin.jpg

  0%|          | 32/8920 [00:50<4:44:55,  1.92s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prettyluhhazel_74586.jpg

  0%|          | 33/8920 [00:51<4:22:44,  1.77s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grant_Marshall.jpg

  0%|          | 34/8920 [00:52<3:22:17,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Derkslurp.jpg

  0%|          | 35/8920 [00:53<3:07:55,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariano_Castano.jpg

  0%|          | 36/8920 [00:53<2:32:59,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chase_Hudson.jpg

  0%|          | 37/8920 [00:58<5:37:54,  2.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Boo.jpg

  0%|          | 38/8920 [01:00<4:42:43,  1.91s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Levinhotho.jpg

  0%|          | 39/8920 [01:02<5:06:01,  2.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_French.jpg

  0%|          | 40/8920 [01:02<3:50:03,  1.55s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Devyn_Winkler.jpg

  0%|          | 41/8920 [01:04<4:07:12,  1.67s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/C_Cessarr_74920.jpg

  0%|          | 42/8920 [01:06<4:24:52,  1.79s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luke_Singletary.jpg

  0%|          | 43/8920 [01:07<3:24:26,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Mendelsohn.jpg

  0%|          | 44/8920 [01:07<2:53:13,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejandro_Rosario.jpg

  1%|          | 45/8920 [01:08<2:39:20,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Boulet_Viau.jpg

  1%|          | 46/8920 [01:09<2:21:25,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milo_Winter_63202.jpg

  1%|          | 47/8920 [01:10<2:29:18,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jada_Gomillion_75284.jpg

  1%|          | 48/8920 [01:10<1:56:43,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trvp_Andre.jpg

  1%|          | 49/8920 [01:11<2:06:20,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dayshawn_Wilson.jpg

  1%|          | 50/8920 [01:13<2:34:57,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellie_Zeiler.jpg

  1%|          | 51/8920 [01:15<3:03:53,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatyanah_Bass.jpg

  1%|          | 52/8920 [01:15<2:43:53,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juztjosh.jpg

  1%|          | 53/8920 [01:16<2:13:44,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madiit.jpg

  1%|          | 54/8920 [01:16<1:59:55,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Kim.jpg

  1%|          | 55/8920 [01:18<2:46:53,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Poppy_Mead.jpg

  1%|          | 56/8920 [01:19<2:34:17,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peyton_Jord.jpg

  1%|          | 57/8920 [01:19<2:01:01,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jslutty.jpg

  1%|          | 58/8920 [01:20<1:40:33,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Devron_Harris.jpg

  1%|          | 59/8920 [01:20<1:28:59,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Halle_Pitman.jpg

  1%|          | 60/8920 [01:22<2:04:03,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Riley_Hubatka.jpg

  1%|          | 61/8920 [01:23<2:47:11,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yazan_Diab.jpg

  1%|          | 62/8920 [01:25<3:08:33,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Camila.jpg

  1%|          | 63/8920 [01:25<2:25:31,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cherry_Hunt_75501.jpg

  1%|          | 64/8920 [01:27<2:41:23,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alantae_Nicholas.jpg

  1%|          | 65/8920 [01:27<2:24:29,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kat_Stickler.jpg

  1%|          | 66/8920 [01:29<2:34:11,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ross_Smith.jpg

  1%|          | 67/8920 [01:29<2:01:31,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benji_Xavier_118987.jpg

  1%|          | 68/8920 [01:29<1:48:26,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erica_Ha.jpg

  1%|          | 69/8920 [01:30<1:26:01,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Trusty.jpg

  1%|          | 70/8920 [01:31<1:57:39,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lexi_Hidalgo.jpg

  1%|          | 71/8920 [01:32<1:58:54,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryce_Buse.jpg

  1%|          | 72/8920 [01:33<2:40:06,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Labelle.jpg

  1%|          | 73/8920 [01:34<2:16:52,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sydney_Morgan.jpg

  1%|          | 74/8920 [01:35<2:14:25,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willywonkatiktok.jpg

  1%|          | 75/8920 [01:37<2:46:33,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Silk_61806.jpg

  1%|          | 76/8920 [01:37<2:32:53,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricky_Flores.jpg

  1%|          | 77/8920 [01:38<1:58:30,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amare_Frost.jpg

  1%|          | 78/8920 [01:38<1:52:08,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Worldwidekayy.jpg

  1%|          | 79/8920 [01:40<2:19:05,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katelyn_Elizabeth.jpg

  1%|          | 80/8920 [01:41<2:48:29,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jada_Wesley.jpg

  1%|          | 81/8920 [01:42<2:21:34,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gardian_Hasani.jpg

  1%|          | 82/8920 [01:42<1:55:43,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheri_Easterling.jpg

  1%|          | 83/8920 [01:43<1:53:21,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dalaija_Monet.jpg

  1%|          | 84/8920 [01:44<1:47:16,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Owen_Holt_120968.jpg

  1%|          | 85/8920 [01:44<1:47:34,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bene_Schulz.jpg

  1%|          | 86/8920 [01:45<1:44:35,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Olsen.jpg

  1%|          | 87/8920 [01:45<1:24:19,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Barnett.jpg

  1%|          | 88/8920 [01:45<1:11:33,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Challan_Trishann.jpg

  1%|          | 89/8920 [01:46<1:02:54,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loren_Gray_Beech.jpg

  1%|          | 90/8920 [01:47<1:19:37,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Wright.jpg

  1%|          | 91/8920 [01:47<1:07:55,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liana_Jade_Brooker.jpg

  1%|          | 92/8920 [01:47<57:20,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colie_1.jpg

  1%|          | 93/8920 [01:48<1:09:12,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_Prieto.jpg

  1%|          | 94/8920 [01:48<1:19:47,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaylie_Leas.jpg

  1%|          | 95/8920 [01:49<1:23:55,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mishka_Silva.jpg

  1%|          | 96/8920 [01:49<1:13:09,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zeddywill.jpg

  1%|          | 97/8920 [01:50<1:22:36,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Montanez.jpg

  1%|          | 98/8920 [01:51<1:54:39,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brody_Dempsey.jpg

  1%|          | 99/8920 [01:53<2:19:38,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Brooks_Mcallister_120292.jpg

  1%|          | 100/8920 [01:54<2:25:09,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maximo_Rivano.jpg

  1%|          | 101/8920 [01:55<2:50:29,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xqc.jpg

  1%|          | 102/8920 [01:57<2:54:44,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loserfruit.jpg

  1%|          | 103/8920 [01:57<2:14:19,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Quackityhq.jpg

  1%|          | 104/8920 [02:00<4:03:17,  1.66s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Kolcheff.jpg

  1%|          | 105/8920 [02:01<3:00:43,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nihachu.jpg

  1%|          | 106/8920 [02:02<2:55:27,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aimsey.jpg

  1%|          | 107/8920 [02:05<4:45:30,  1.94s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxggs.jpg

  1%|          | 108/8920 [02:08<5:18:24,  2.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sykkuno.jpg

  1%|          | 109/8920 [02:08<3:54:48,  1.60s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jinnytty.jpg

  1%|          | 110/8920 [02:10<4:08:29,  1.69s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queenmico.jpg

  1%|          | 111/8920 [02:11<3:12:32,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hachubby.jpg

  1%|▏         | 112/8920 [02:13<3:44:12,  1.53s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tubbo.jpg

  1%|▏         | 113/8920 [02:13<3:10:01,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ranboolive.jpg

  1%|▏         | 114/8920 [02:14<2:27:42,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Punz.jpg

  1%|▏         | 115/8920 [02:15<2:46:20,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Jacobs.jpg

  1%|▏         | 116/8920 [02:16<2:30:21,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Awesamdude.jpg

  1%|▏         | 117/8920 [02:16<1:59:44,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Philza.jpg

  1%|▏         | 118/8920 [02:17<1:49:02,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hasan_Piker.jpg

  1%|▏         | 119/8920 [02:18<2:11:46,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Captain_Puffy.jpg

  1%|▏         | 120/8920 [02:18<1:45:17,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Badboyhalo.jpg

  1%|▏         | 121/8920 [02:19<1:30:59,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justaminx.jpg

  1%|▏         | 122/8920 [02:21<2:25:39,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Itsfundy.jpg

  1%|▏         | 123/8920 [02:21<2:05:26,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Foolish_Gamers.jpg

  1%|▏         | 124/8920 [02:21<1:38:26,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tinakitten.jpg

  1%|▏         | 125/8920 [02:22<1:40:02,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Badlinu_112112.jpg

  1%|▏         | 126/8920 [02:23<1:37:48,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brookeab.jpg

  1%|▏         | 127/8920 [02:23<1:21:15,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai_Cenat.jpg

  1%|▏         | 128/8920 [02:25<2:11:36,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Darling.jpg

  1%|▏         | 129/8920 [02:28<4:06:48,  1.68s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kingani.jpg

  1%|▏         | 130/8920 [02:29<3:32:21,  1.45s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Piso4_150876.jpg

  1%|▏         | 131/8920 [02:31<3:37:54,  1.49s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iziprime_154548.jpg

  1%|▏         | 132/8920 [02:32<3:03:48,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brucedropemoff.jpg

  1%|▏         | 133/8920 [02:34<4:18:31,  1.77s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cinna_155212.jpg

  2%|▏         | 134/8920 [02:35<3:30:45,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mongraal.jpg

  2%|▏         | 135/8920 [02:38<4:31:05,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buddha_144106.jpg

  2%|▏         | 136/8920 [02:39<3:50:08,  1.57s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peacelovecaitlin_150664.jpg

  2%|▏         | 137/8920 [02:40<3:22:39,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aria_Saki_143894.jpg

  2%|▏         | 138/8920 [02:41<3:10:59,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jellybean_155328.jpg

  2%|▏         | 139/8920 [02:42<2:55:49,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lotsofbunnies_143319.jpg

  2%|▏         | 140/8920 [02:44<3:44:48,  1.54s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucky_Chamu_152534.jpg

  2%|▏         | 141/8920 [02:45<3:07:51,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lurn_152648.jpg

  2%|▏         | 142/8920 [02:45<2:36:27,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Runthefutmarket_155351.jpg

  2%|▏         | 143/8920 [02:48<3:41:18,  1.51s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baronvongamez_153128.jpg

  2%|▏         | 144/8920 [02:48<2:46:14,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 145/8920 [02:49<2:41:38,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jojothamofo_155960.jpg

  2%|▏         | 146/8920 [02:51<2:51:07,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Parkenharbor_144380.jpg

  2%|▏         | 147/8920 [02:51<2:16:36,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kruzadar_151402.jpg

  2%|▏         | 148/8920 [02:53<2:58:23,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macaiyla_148477.jpg

  2%|▏         | 149/8920 [02:56<4:23:14,  1.80s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 150/8920 [02:57<3:34:25,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vgumiho_154616.jpg

  2%|▏         | 151/8920 [02:57<3:01:23,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asianjeff_152771.jpg

  2%|▏         | 152/8920 [03:01<4:56:06,  2.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Manifold_145961.jpg

  2%|▏         | 153/8920 [03:02<3:40:38,  1.51s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Esfandtv_152155.jpg

  2%|▏         | 154/8920 [03:03<3:33:08,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shelby_Renae_143394.jpg

  2%|▏         | 155/8920 [03:04<2:55:26,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Velvetiscake_154585.jpg

  2%|▏         | 156/8920 [03:04<2:33:21,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonii_143416.jpg

  2%|▏         | 157/8920 [03:05<2:14:23,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Highkeyhateme_145440.jpg

  2%|▏         | 158/8920 [03:06<2:19:27,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katerino_150869.jpg

  2%|▏         | 159/8920 [03:10<4:34:31,  1.88s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wintrrz_155085.jpg

  2%|▏         | 160/8920 [03:11<4:08:37,  1.70s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beasttrollmc_156305.jpg

  2%|▏         | 161/8920 [03:13<4:29:40,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenz_151207.jpg

  2%|▏         | 162/8920 [03:14<3:35:54,  1.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pokelawls_143684.jpg

  2%|▏         | 163/8920 [03:15<2:58:47,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Poobear_147690.jpg

  2%|▏         | 164/8920 [03:16<3:06:45,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jawsh_155149.jpg

  2%|▏         | 165/8920 [03:17<2:54:27,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Koji_Revenge_144750.jpg

  2%|▏         | 166/8920 [03:19<3:37:32,  1.49s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 167/8920 [03:20<2:44:14,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 168/8920 [03:20<2:25:18,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mitch_Jones_154640.jpg

  2%|▏         | 169/8920 [03:21<1:58:53,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 170/8920 [03:21<1:58:48,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 171/8920 [03:22<2:06:09,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bbjess_156304.jpg

  2%|▏         | 172/8920 [03:24<2:29:39,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthonyz_152300.jpg

  2%|▏         | 173/8920 [03:24<2:08:13,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Triciaisabirdy_154244.jpg

  2%|▏         | 174/8920 [03:25<2:11:02,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scarra_150391.jpg

  2%|▏         | 175/8920 [03:26<2:16:20,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/39Daph_143625.jpg

  2%|▏         | 176/8920 [03:28<2:35:35,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dinglederper_150697.jpg

  2%|▏         | 177/8920 [03:29<2:45:06,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dantes_144374.jpg

  2%|▏         | 178/8920 [03:30<2:26:56,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 179/8920 [03:31<2:18:37,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baghera_Jones_146411.jpg

  2%|▏         | 180/8920 [03:34<4:24:59,  1.82s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Ly_155589.jpg

  2%|▏         | 181/8920 [03:36<3:58:21,  1.64s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boze_153713.jpg

  2%|▏         | 182/8920 [03:40<6:08:34,  2.53s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karq_143666.jpg

  2%|▏         | 183/8920 [03:41<4:31:36,  1.87s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  2%|▏         | 184/8920 [03:43<4:39:43,  1.92s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greekgodx_145278.jpg

  2%|▏         | 185/8920 [03:43<3:42:08,  1.53s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ohnepixel_146817.jpg

  2%|▏         | 186/8920 [03:44<3:11:11,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonnaay_145939.jpg

  2%|▏         | 187/8920 [03:46<3:47:22,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Prezoh_144383.jpg

  2%|▏         | 188/8920 [03:47<3:06:44,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aarava_144582.jpg

  2%|▏         | 189/8920 [03:47<2:20:15,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danyell_Lanza_155907.jpg

  2%|▏         | 190/8920 [03:49<2:50:57,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billzo_145298.jpg

  2%|▏         | 191/8920 [03:49<2:10:39,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blushi_153572.jpg

  2%|▏         | 192/8920 [03:49<1:56:39,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Fosco_155319.jpg

  2%|▏         | 193/8920 [03:50<1:50:33,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baschin_148491.jpg

  2%|▏         | 194/8920 [03:51<1:44:03,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Goch_155570.jpg

  2%|▏         | 195/8920 [03:52<1:56:21,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Polom_147792.jpg

  2%|▏         | 196/8920 [03:52<1:51:41,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_W_Clark_150192.jpg

  2%|▏         | 197/8920 [03:53<1:49:26,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noahwplays_155620.jpg

  2%|▏         | 198/8920 [03:53<1:26:09,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/.jpg

  2%|▏         | 199/8920 [03:55<1:53:22,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Notaestheticallyhannah_153657.jpg

  2%|▏         | 200/8920 [03:57<3:12:40,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Strawbys_153109.jpg

  2%|▏         | 201/8920 [03:58<2:29:38,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zach_Reed_Clayton.jpg

  2%|▏         | 202/8920 [03:58<2:17:17,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Seavey.jpg

  2%|▏         | 203/8920 [04:00<2:47:38,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Weston_Koury.jpg

  2%|▏         | 204/8920 [04:04<5:00:39,  2.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christine_Rowland.jpg

  2%|▏         | 205/8920 [04:07<5:30:06,  2.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hunter_Rowland.jpg

  2%|▏         | 206/8920 [04:07<4:03:12,  1.67s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jodie_Frampton_145887.jpg

  2%|▏         | 207/8920 [04:07<3:01:56,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristian_Oliveras.jpg

  2%|▏         | 208/8920 [04:08<2:19:50,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gotdamnzo_40894.jpg

  2%|▏         | 209/8920 [04:08<1:50:10,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gio2Saucy.jpg

  2%|▏         | 210/8920 [04:09<2:06:18,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Stone.jpg

  2%|▏         | 211/8920 [04:10<2:21:25,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonas_Bridges.jpg

  2%|▏         | 212/8920 [04:12<2:36:44,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Devin_Corwin.jpg

  2%|▏         | 213/8920 [04:13<2:31:09,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robby_Epicsauce.jpg

  2%|▏         | 214/8920 [04:14<2:49:22,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Derek_Couture_156087.jpg

  2%|▏         | 215/8920 [04:15<2:30:52,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Juarez_155982.jpg

  2%|▏         | 216/8920 [04:16<2:45:09,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Poulos_150953.jpg

  2%|▏         | 217/8920 [04:18<3:25:51,  1.42s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jared_Ryan_Tousley_148048.jpg

  2%|▏         | 218/8920 [04:23<5:57:18,  2.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Triston_Tyler_147936.jpg

  2%|▏         | 219/8920 [04:36<13:41:18,  5.66s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/logan-morris-147673-1.jpg: The read operation timed out

  2%|▏         | 220/8920 [05:06<31:23:11, 12.99s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/caleb-bielski-147065-1.jpg: timed out

  2%|▏         | 221/8920 [05:37<43:51:54, 18.15s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/cody-ryle-146651-1.jpg: timed out

  2%|▏         | 222/8920 [06:07<52:30:05, 21.73s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/christian-winters-1.jpg: timed out

  2%|▎         | 223/8920 [06:37<58:33:31, 24.24s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/sam-collins-1.jpg: timed out

  3%|▎         | 224/8920 [07:07<62:47:59, 26.00s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/conner-dennis-1.jpg: timed out

  3%|▎         | 225/8920 [07:37<65:45:06, 27.22s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/kayce-brewer-1.jpg: timed out

  3%|▎         | 226/8920 [08:07<67:48:20, 28.08s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/lee-hinchcliffe-1.jpg: timed out

  3%|▎         | 227/8920 [08:37<69:14:21, 28.67s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/mikey-barone-1.jpg: timed out

  3%|▎         | 228/8920 [09:07<70:16:21, 29.11s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/wesley-tucker.jpg: timed out

  3%|▎         | 229/8920 [09:37<70:58:19, 29.40s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/james-neese-1.jpg: timed out

  3%|▎         | 230/8920 [10:07<71:27:38, 29.60s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/karlee-steel-1.jpg: timed out

  3%|▎         | 231/8920 [10:38<72:10:22, 29.90s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/dillon-juarez-1.jpg: timed out

  3%|▎         | 232/8920 [11:08<72:17:52, 29.96s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/madeline-phillips-1.jpg: timed out

  3%|▎         | 233/8920 [11:38<72:22:07, 29.99s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/christian-burns-1.jpg: timed out

  3%|▎         | 234/8920 [12:08<72:25:23, 30.02s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/mateo-haack-131906-1.jpg: timed out

  3%|▎         | 235/8920 [12:38<72:28:39, 30.04s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/mathias-dahl-moslund-132412-1.jpg: timed out

  3%|▎         | 236/8920 [13:08<72:29:09, 30.05s/it]

❌ Failed to download https://www.thefamouspeople.com/images/no_image.jpg.webp: timed out

  3%|▎         | 237/8920 [13:38<72:29:44, 30.06s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/tayler-holder-1.jpg: timed out

  3%|▎         | 238/8920 [14:09<72:30:42, 30.07s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/zach-king-1.jpg: timed out

  3%|▎         | 239/8920 [14:39<72:30:16, 30.07s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/thomas-sanders-1.jpg: timed out

  3%|▎         | 240/8920 [15:09<72:29:55, 30.07s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/jay-versace-1.jpg: timed out

  3%|▎         | 241/8920 [15:39<72:33:29, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/darren-black-1.jpg: timed out

  3%|▎         | 242/8920 [16:09<72:33:09, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/kenny-knox-1.jpg: timed out

  3%|▎         | 243/8920 [16:39<72:32:34, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/darius-benson-1.jpg: timed out

  3%|▎         | 244/8920 [17:09<72:31:00, 30.09s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/hardstop-lucas-1.jpg: timed out

  3%|▎         | 245/8920 [17:39<72:29:23, 30.08s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/brandon-calvillo-1.jpg: timed out

  3%|▎         | 246/8920 [18:09<72:28:32, 30.08s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/evan-breen-1.jpg: timed out

  3%|▎         | 247/8920 [18:39<72:28:59, 30.09s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/andres-b-1.jpg: timed out

  3%|▎         | 248/8920 [19:09<72:28:05, 30.08s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/brent-rivera-1.jpg: timed out

  3%|▎         | 249/8920 [19:40<72:28:19, 30.09s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/rudy-mancuso-1.jpg: timed out

  3%|▎         | 250/8920 [20:10<72:27:37, 30.09s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/chloe-woodard-1.jpg: timed out

  3%|▎         | 251/8920 [20:40<72:50:14, 30.25s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/nik-keswani-1.jpg: timed out

  3%|▎         | 252/8920 [21:10<72:42:24, 30.20s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/liane-valenzuela-1.jpg: timed out

  3%|▎         | 253/8920 [21:40<72:37:06, 30.16s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/noel-miller-1.jpg: timed out

  3%|▎         | 254/8920 [22:10<72:33:53, 30.14s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/marlon-webb-1.jpg: timed out

  3%|▎         | 255/8920 [22:41<72:29:56, 30.12s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/quenlin-blackwell-1.jpg: timed out

  3%|▎         | 256/8920 [23:11<72:27:58, 30.11s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/corey-scherer-1.jpg: timed out

  3%|▎         | 257/8920 [23:41<72:25:58, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/scotty-sire-1.jpg: timed out

  3%|▎         | 258/8920 [24:11<72:24:35, 30.09s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/desmond-english-7.jpg: timed out

  3%|▎         | 259/8920 [24:41<72:45:39, 30.24s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/aaron-doh-1.jpg: timed out

  3%|▎         | 260/8920 [25:11<72:38:56, 30.20s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/melvin-gregg-1.jpg: timed out

  3%|▎         | 261/8920 [25:42<72:35:33, 30.18s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/jojoe-1.jpg: timed out

  3%|▎         | 262/8920 [26:12<72:30:56, 30.15s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/gotdamnzo-40894-1.jpg: timed out

  3%|▎         | 263/8920 [26:42<72:27:19, 30.13s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/grayson-bailey-dolan-1.jpg: timed out

  3%|▎         | 264/8920 [27:12<72:24:57, 30.12s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/brittany-furlan-1.jpg: timed out

  3%|▎         | 265/8920 [27:42<72:23:38, 30.11s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/kurtis-conner-1.jpg: timed out

  3%|▎         | 266/8920 [28:12<72:21:35, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/tina-woods-1.jpg: timed out

  3%|▎         | 267/8920 [28:42<72:20:26, 30.10s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/louis-giordano-1.jpg: timed out

  3%|▎         | 268/8920 [28:45<52:21:36, 21.79s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Conte.jpg

  3%|▎         | 269/8920 [28:47<38:37:26, 16.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rickey_Thompson.jpg

  3%|▎         | 270/8920 [28:48<27:52:58, 11.60s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Mendez.jpg

  3%|▎         | 271/8920 [28:50<20:31:28,  8.54s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khayman_Burton.jpg

  3%|▎         | 272/8920 [28:51<15:24:25,  6.41s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Itsbambii.jpg

  3%|▎         | 273/8920 [28:52<11:33:54,  4.81s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Braden_Carpenter.jpg

  3%|▎         | 274/8920 [28:54<9:23:30,  3.91s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Poookieboo_143299.jpg

  3%|▎         | 275/8920 [28:55<7:06:27,  2.96s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cody_Johns.jpg

  3%|▎         | 276/8920 [28:56<5:57:40,  2.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caleb_Hurst_150063.jpg

  3%|▎         | 277/8920 [28:57<4:26:55,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kronismusic_151400.jpg

  3%|▎         | 278/8920 [28:58<4:14:00,  1.76s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

  3%|▎         | 279/8920 [29:01<4:46:19,  1.99s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evancredible_143383.jpg

  3%|▎         | 280/8920 [29:04<5:26:21,  2.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adnan_Mansoor_144624.jpg

  3%|▎         | 281/8920 [29:04<4:00:04,  1.67s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sydney_Adams.jpg

  3%|▎         | 282/8920 [29:05<3:36:13,  1.50s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trench.jpg

  3%|▎         | 283/8920 [29:06<3:16:55,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shady_Srour.jpg

  3%|▎         | 284/8920 [29:07<3:09:20,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ethan_Kennicott.jpg

  3%|▎         | 285/8920 [29:08<2:29:52,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terrance_Jones.jpg

  3%|▎         | 286/8920 [29:08<1:55:15,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/666Chainz.jpg

  3%|▎         | 287/8920 [29:09<2:16:56,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Holly_H.jpg

  3%|▎         | 288/8920 [29:10<2:29:27,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tate_Mcrae.jpg

  3%|▎         | 289/8920 [29:13<3:35:24,  1.50s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tayvion_Power.jpg

  3%|▎         | 290/8920 [29:14<3:03:45,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahogany_Cheyenne_Gordy.jpg

  3%|▎         | 291/8920 [29:15<2:51:59,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haley_Bieniewicz_153559.jpg

  3%|▎         | 292/8920 [29:16<2:59:25,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Perkins.jpg

  3%|▎         | 293/8920 [29:17<2:54:52,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeffrey_Marsh_149418.jpg

  3%|▎         | 294/8920 [29:18<2:28:50,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Sherman.jpg

  3%|▎         | 295/8920 [29:19<2:14:59,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Akridge.jpg

  3%|▎         | 296/8920 [29:19<2:00:26,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Ramos.jpg

  3%|▎         | 297/8920 [29:20<2:13:29,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will_Gittens.jpg

  3%|▎         | 298/8920 [29:23<3:15:01,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Devin_Hayes.jpg

  3%|▎         | 299/8920 [29:24<3:18:07,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Ramírez.jpg

  3%|▎         | 300/8920 [29:25<2:54:03,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jazmine_Hood.jpg

  3%|▎         | 301/8920 [29:26<2:26:05,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malak_Watson.jpg

  3%|▎         | 302/8920 [29:26<1:53:25,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carter_Reynolds.jpg

  3%|▎         | 303/8920 [29:28<2:49:36,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Wilkinson.jpg

  3%|▎         | 304/8920 [29:29<2:53:48,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Holtti.jpg

  3%|▎         | 305/8920 [29:30<2:30:26,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucas_Dobre.jpg

  3%|▎         | 306/8920 [29:31<2:16:08,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Dail.jpg

  3%|▎         | 307/8920 [29:31<1:57:16,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Urie.jpg

  3%|▎         | 308/8920 [29:32<1:50:00,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucas_Ovalle.jpg

  3%|▎         | 309/8920 [29:32<1:46:31,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hayes_Grier.jpg

  3%|▎         | 310/8920 [29:33<1:53:33,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Purpdrank.jpg

  3%|▎         | 311/8920 [29:34<2:03:12,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Vanessa.jpg

  3%|▎         | 312/8920 [29:35<1:48:19,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Golbach.jpg

  4%|▎         | 313/8920 [29:36<2:00:57,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Taylor.jpg

  4%|▎         | 314/8920 [29:38<2:35:40,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demetrius_Harmon.jpg

  4%|▎         | 315/8920 [29:38<2:18:57,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Jr.jpg

  4%|▎         | 316/8920 [29:39<2:04:26,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curtis_Lepore.jpg

  4%|▎         | 317/8920 [29:39<1:40:50,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesse_Taylor_Ridgway.jpg

  4%|▎         | 318/8920 [29:42<3:01:53,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mr_Monkey.jpg

  4%|▎         | 319/8920 [29:42<2:29:55,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jovani_Jara.jpg

  4%|▎         | 320/8920 [29:43<1:57:50,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Summerella.jpg

  4%|▎         | 321/8920 [29:43<1:36:23,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Collins.jpg

  4%|▎         | 322/8920 [29:44<1:49:11,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arantza_Fahnbulleh.jpg

  4%|▎         | 323/8920 [29:44<1:39:07,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noah_Riley.jpg

  4%|▎         | 324/8920 [29:46<2:01:26,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mighty_Neicy.jpg

  4%|▎         | 325/8920 [29:46<1:50:32,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heath_Hussar.jpg

  4%|▎         | 326/8920 [29:47<1:54:40,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elton_Castee.jpg

  4%|▎         | 327/8920 [29:48<2:06:12,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Rojas.jpg

  4%|▎         | 328/8920 [29:52<4:12:12,  1.76s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerome_Jarre.jpg

  4%|▎         | 329/8920 [29:53<3:26:37,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Issa_Christopher_Tweimeh.jpg

  4%|▎         | 330/8920 [29:54<3:01:49,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justice_Carradine.jpg

  4%|▎         | 331/8920 [29:54<2:19:04,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adin_Kolansky.jpg

  4%|▎         | 332/8920 [29:57<3:33:02,  1.49s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Skunky.jpg

  4%|▎         | 333/8920 [29:58<3:43:51,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davine_Nesbitt.jpg

  4%|▎         | 334/8920 [30:01<4:19:35,  1.81s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wesley.jpg

  4%|▍         | 335/8920 [30:01<3:28:31,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackson_Brazier.jpg

  4%|▍         | 336/8920 [30:02<3:04:55,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Reilly.jpg

  4%|▍         | 337/8920 [30:03<2:26:20,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Michael_Caniff.jpg

  4%|▍         | 338/8920 [30:03<2:12:10,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yi_Sun_Sin.jpg

  4%|▍         | 339/8920 [30:04<1:43:43,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuna_Kim.jpg

  4%|▍         | 340/8920 [30:04<1:22:31,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yeon-Koung.jpg

  4%|▍         | 341/8920 [30:04<1:08:28,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/An_Se-Young.jpg

  4%|▍         | 342/8920 [30:04<1:01:49,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pak_Se-Ri.jpg

  4%|▍         | 343/8920 [30:05<58:14,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Wan-Ho.jpg

  4%|▍         | 344/8920 [30:05<51:39,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Dae-Hoon.jpg

  4%|▍         | 345/8920 [30:05<49:47,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ki_Bo-Bae.jpg

  4%|▍         | 346/8920 [30:06<48:00,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ku_Bon-Chan.jpg

  4%|▍         | 347/8920 [30:06<47:11,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Yong-Dae.jpg

  4%|▍         | 348/8920 [30:07<1:00:25,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bang_Soo-Hyun.jpg

  4%|▍         | 349/8920 [30:07<1:10:46,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Sung-Bin.jpg

  4%|▍         | 350/8920 [30:07<1:01:20,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Im_Dong-Hyun.jpg

  4%|▍         | 351/8920 [30:08<1:12:29,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Woo-Jin.jpg

  4%|▍         | 352/8920 [30:09<1:23:31,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryu_Seung-Min.jpg

  4%|▍         | 353/8920 [30:09<1:17:57,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jin_Jong-Oh.jpg

  4%|▍         | 354/8920 [30:10<1:26:52,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/In-Kyung_Kim.jpg

  4%|▍         | 355/8920 [30:12<2:38:51,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yun-Ja.jpg

  4%|▍         | 356/8920 [30:13<2:31:08,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ban_Ki-Moon.jpg

  4%|▍         | 357/8920 [30:14<1:58:40,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kang_Chae-Young.jpg

  4%|▍         | 358/8920 [30:14<1:33:04,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Taek-Soo.jpg

  4%|▍         | 359/8920 [30:14<1:19:38,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/An_San.jpg

  4%|▍         | 360/8920 [30:16<1:51:39,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Hyeon-Ju.jpg

  4%|▍         | 361/8920 [30:16<1:36:26,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoon_Kyung-Shin.jpg

  4%|▍         | 362/8920 [30:16<1:21:16,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Kyung-Wook.jpg

  4%|▍         | 363/8920 [30:17<1:06:51,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inbee_Park.jpg

  4%|▍         | 364/8920 [30:17<59:50,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Joo-Bong.jpg

  4%|▍         | 365/8920 [30:17<52:25,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hwang_Sun-Ai.jpg

  4%|▍         | 366/8920 [30:18<1:32:40,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Sang-Hwa.jpg

  4%|▍         | 367/8920 [30:19<1:14:36,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Hye-Jin.jpg

  4%|▍         | 368/8920 [30:21<2:21:07,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Jin-Hyek.jpg

  4%|▍         | 369/8920 [30:21<1:51:40,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Je-Deok.jpg

  4%|▍         | 370/8920 [30:21<1:32:21,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Jong-Hyun.jpg

  4%|▍         | 371/8920 [30:22<1:21:08,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Mi-Sun.jpg

  4%|▍         | 372/8920 [30:22<1:09:13,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Soo-Nyung.jpg

  4%|▍         | 373/8920 [30:23<1:43:39,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Sei-Young.jpg

  4%|▍         | 374/8920 [30:24<1:36:55,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiyai_Shin.jpg

  4%|▍         | 375/8920 [30:24<1:16:37,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyo-Joo.jpg

  4%|▍         | 376/8920 [30:25<1:20:08,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Min-Hee.jpg

  4%|▍         | 377/8920 [30:25<1:07:23,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mo_Tae-Bum.jpg

  4%|▍         | 378/8920 [30:25<59:51,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Na-Yeon.jpg

  4%|▍         | 379/8920 [30:26<1:10:04,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Jun.jpg

  4%|▍         | 380/8920 [30:26<59:35,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Min-Ho.jpg

  4%|▍         | 381/8920 [30:28<1:49:55,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyeon-Woo.jpg

  4%|▍         | 382/8920 [30:28<1:29:46,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jae-Bum.jpg

  4%|▍         | 383/8920 [30:28<1:12:00,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Bong-Ju.jpg

  4%|▍         | 384/8920 [30:29<1:38:16,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Seung-Yun.jpg

  4%|▍         | 385/8920 [30:31<2:04:29,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hwang_Kyung-Seon.jpg

  4%|▍         | 386/8920 [30:31<1:37:06,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Dae-Sung.jpg

  4%|▍         | 387/8920 [30:31<1:21:47,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cha_Dong-Min.jpg

  4%|▍         | 388/8920 [30:34<2:54:19,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Sang-Eun.jpg

  4%|▍         | 389/8920 [30:34<2:16:43,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sa_Jae-Hyouk.jpg

  4%|▍         | 390/8920 [30:35<2:17:46,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeon_Ki-Young.jpg

  4%|▍         | 391/8920 [30:36<2:01:57,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Mi-Jin.jpg

  4%|▍         | 392/8920 [30:36<1:39:54,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Ok-Hee.jpg

  4%|▍         | 393/8920 [30:37<1:22:49,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryu_Ji-Hye.jpg

  4%|▍         | 394/8920 [30:37<1:08:28,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Kyung-Mo.jpg

  4%|▍         | 395/8920 [30:37<1:11:58,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Chul-Seung.jpg

  4%|▍         | 396/8920 [30:38<1:00:23,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cho_Min-Sun.jpg

  4%|▍         | 397/8920 [30:38<1:09:28,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hwang_Young-Cho.jpg

  4%|▍         | 398/8920 [30:39<59:08,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Kyung-Ah.jpg

  4%|▍         | 399/8920 [30:39<1:02:40,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jo-Sun.jpg

  4%|▍         | 400/8920 [30:40<1:09:28,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yang_Young-Ja.jpg

  4%|▍         | 401/8920 [30:40<1:17:42,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Kyong-Hun.jpg

  5%|▍         | 402/8920 [30:41<1:31:39,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joo_Hyun-Jung.jpg

  5%|▍         | 403/8920 [30:42<1:20:11,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_Hyang-Soon.jpg

  5%|▍         | 404/8920 [30:42<1:10:19,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Eun-Kyung.jpg

  5%|▍         | 405/8920 [30:43<1:42:22,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kang_Jae-Won.jpg

  5%|▍         | 406/8920 [30:44<1:46:10,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Yong-Ho.jpg

  5%|▍         | 407/8920 [30:44<1:25:57,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cho_Youn-Jeong.jpg

  5%|▍         | 408/8920 [30:44<1:11:39,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Nam-Soon.jpg

  5%|▍         | 409/8920 [30:45<1:14:57,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Sung-Soo.jpg

  5%|▍         | 410/8920 [30:46<1:27:20,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Chang-Hwan.jpg

  5%|▍         | 411/8920 [30:46<1:14:19,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Bo-Ram.jpg

  5%|▍         | 412/8920 [30:46<1:03:06,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Kyo-Moon.jpg

  5%|▍         | 413/8920 [30:47<53:59,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Young-Sook.jpg

  5%|▍         | 414/8920 [30:47<48:38,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Hee-Kyung.jpg

  5%|▍         | 415/8920 [30:47<43:34,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyun-Mee.jpg

  5%|▍         | 416/8920 [30:48<1:00:47,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoon_Hye-Young.jpg

  5%|▍         | 417/8920 [30:48<54:08,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chun_In-Soo.jpg

  5%|▍         | 418/8920 [30:49<1:31:29,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Jae-Hun.jpg

  5%|▍         | 419/8920 [30:50<1:45:38,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Han-Sup.jpg

  5%|▍         | 420/8920 [30:51<1:46:36,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Sung-Jin.jpg

  5%|▍         | 421/8920 [30:52<2:10:54,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Sung-Hyun.jpg

  5%|▍         | 422/8920 [30:53<1:41:00,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jungkook.jpg

  5%|▍         | 423/8920 [30:54<2:23:04,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Taehyung.jpg

  5%|▍         | 424/8920 [30:55<2:08:29,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rap_Monster.jpg

  5%|▍         | 425/8920 [30:55<1:39:55,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roseanne_Park.jpg

  5%|▍         | 426/8920 [30:56<1:40:07,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Song_Joong_Ki.jpg

  5%|▍         | 427/8920 [30:57<1:36:08,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimin.jpg

  5%|▍         | 428/8920 [30:57<1:17:38,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Jongsuk.jpg

  5%|▍         | 429/8920 [30:58<1:23:10,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Seok_Jin.jpg

  5%|▍         | 430/8920 [30:58<1:10:01,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Seo_Joon.jpg

  5%|▍         | 431/8920 [30:59<1:44:11,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji_Chang_Wook.jpg

  5%|▍         | 432/8920 [31:00<1:44:44,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suga.jpg

  5%|▍         | 433/8920 [31:01<2:08:41,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cha_Eun_Woo.jpg

  5%|▍         | 434/8920 [31:01<1:41:18,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iu.jpg

  5%|▍         | 435/8920 [31:03<2:00:35,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Heung-Min.jpg

  5%|▍         | 436/8920 [31:03<1:47:20,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Shin_Hye.jpg

  5%|▍         | 437/8920 [31:03<1:27:40,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hyun_Bin.jpg

  5%|▍         | 438/8920 [31:04<1:15:27,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Na.jpg

  5%|▍         | 439/8920 [31:05<1:27:55,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kang_Min_Hyuk.jpg

  5%|▍         | 440/8920 [31:07<2:43:43,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yiruma.jpg

  5%|▍         | 441/8920 [31:08<2:46:33,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sungha_Jung.jpg

  5%|▍         | 442/8920 [31:10<3:10:15,  1.35s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Hun_Gon.jpg

  5%|▍         | 443/8920 [31:12<3:23:58,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peggy_Gou.jpg

  5%|▍         | 444/8920 [31:13<3:01:23,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Jong-Hoon.jpg

  5%|▍         | 445/8920 [31:14<3:15:35,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isang_Yun.jpg

  5%|▌         | 446/8920 [31:16<3:21:19,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han-Na_Chang.jpg

  5%|▌         | 447/8920 [31:18<3:59:43,  1.70s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Cheol-Woong.jpg

  5%|▌         | 448/8920 [31:19<3:43:29,  1.58s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jungkook.jpg

  5%|▌         | 449/8920 [31:20<3:06:47,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Taehyung.jpg

  5%|▌         | 450/8920 [31:20<2:23:24,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rap_Monster.jpg

  5%|▌         | 451/8920 [31:21<2:11:06,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roseanne_Park.jpg

  5%|▌         | 452/8920 [31:21<1:41:13,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimin.jpg

  5%|▌         | 453/8920 [31:22<1:22:09,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Seok_Jin.jpg

  5%|▌         | 454/8920 [31:23<1:46:06,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iu.jpg

  5%|▌         | 455/8920 [31:23<1:25:14,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suga.jpg

  5%|▌         | 456/8920 [31:23<1:14:37,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cha_Eun_Woo.jpg

  5%|▌         | 457/8920 [31:24<1:13:36,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J_Hope.jpg

  5%|▌         | 458/8920 [31:24<1:17:54,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jong_Hyun.jpg

  5%|▌         | 459/8920 [31:25<1:04:08,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Hyung_Sik.jpg

  5%|▌         | 460/8920 [31:25<1:08:59,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Chanyeol.jpg

  5%|▌         | 461/8920 [31:26<1:38:57,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/G_Dragon.jpg

  5%|▌         | 462/8920 [31:27<1:33:09,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Do_Kyung_Soo.jpg

  5%|▌         | 463/8920 [31:30<2:52:23,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai.jpg

  5%|▌         | 464/8920 [31:30<2:11:30,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Jae_Sang.jpg

  5%|▌         | 465/8920 [31:31<2:20:42,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyuna.jpg

  5%|▌         | 466/8920 [31:32<2:01:02,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suho.jpg

  5%|▌         | 467/8920 [31:33<2:26:29,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Tae_Min.jpg

  5%|▌         | 468/8920 [31:33<1:58:12,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nancy.jpg

  5%|▌         | 469/8920 [31:34<2:05:25,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cl.jpg

  5%|▌         | 470/8920 [31:35<1:53:03,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_In_Guk.jpg

  5%|▌         | 471/8920 [31:36<1:43:50,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Jung.jpg

  5%|▌         | 472/8920 [31:37<2:06:40,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hirai_Momo.jpg

  5%|▌         | 473/8920 [31:38<2:25:31,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeon_So-Mi.jpg

  5%|▌         | 474/8920 [31:39<2:26:14,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Krystal_Jung.jpg

  5%|▌         | 475/8920 [31:40<2:20:54,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rain.jpg

  5%|▌         | 476/8920 [31:41<2:07:52,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nayeon.jpg

  5%|▌         | 477/8920 [31:43<3:05:34,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/L.jpg

  5%|▌         | 478/8920 [31:43<2:22:26,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeongyeon.jpg

  5%|▌         | 479/8920 [31:44<2:21:32,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ailee.jpg

  5%|▌         | 480/8920 [31:45<2:00:13,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Park.jpg

  5%|▌         | 481/8920 [31:46<2:01:36,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Si_Won.jpg

  5%|▌         | 482/8920 [31:46<1:50:42,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung_Yong_Hwa.jpg

  5%|▌         | 483/8920 [31:47<1:39:22,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Im_Yoon_Ah.jpg

  5%|▌         | 484/8920 [31:48<1:37:40,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Onew.jpg

  5%|▌         | 485/8920 [31:48<1:19:31,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leeteuk.jpg

  5%|▌         | 486/8920 [31:48<1:19:39,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baekhyun.jpg

  5%|▌         | 487/8920 [31:49<1:29:45,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Min_Ho.jpg

  5%|▌         | 488/8920 [31:50<1:16:51,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Tae_Yeon.jpg

  5%|▌         | 489/8920 [31:50<1:05:11,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boa.jpg

  5%|▌         | 490/8920 [31:50<1:11:55,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunmi.jpg

  6%|▌         | 491/8920 [31:51<1:20:38,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_Kang_Joon.jpg

  6%|▌         | 492/8920 [31:52<1:39:23,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung_Joon_Young.jpg

  6%|▌         | 493/8920 [31:54<2:16:28,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Song_Ji_Eun.jpg

  6%|▌         | 494/8920 [31:54<1:54:42,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T.O.P.jpg

  6%|▌         | 495/8920 [31:56<2:49:00,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jb.jpg

  6%|▌         | 496/8920 [31:57<2:19:58,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Joon.jpg

  6%|▌         | 497/8920 [31:59<2:50:38,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T_O_P_Rapper.jpg

  6%|▌         | 498/8920 [31:59<2:22:08,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hong_Jin_Young.jpg

  6%|▌         | 499/8920 [32:00<2:11:05,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Key.jpg

  6%|▌         | 500/8920 [32:01<2:07:19,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joon_Park.jpg

  6%|▌         | 501/8920 [32:02<2:28:23,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiffany_Hwang.jpg

  6%|▌         | 502/8920 [32:04<2:48:21,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunny.jpg

  6%|▌         | 503/8920 [32:04<2:28:20,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Jin_Young.jpg

  6%|▌         | 504/8920 [32:05<2:10:55,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baek_Ji_Young.jpg

  6%|▌         | 505/8920 [32:07<2:54:18,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Ji-Yeon.jpg

  6%|▌         | 506/8920 [32:07<2:14:33,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Gi_Kwang.jpg

  6%|▌         | 507/8920 [32:10<3:15:54,  1.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roy_Kim.jpg

  6%|▌         | 508/8920 [32:10<2:44:54,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Ji_Min.jpg

  6%|▌         | 509/8920 [32:11<2:23:30,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_Taiji.jpg

  6%|▌         | 510/8920 [32:13<2:42:39,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Dominic.jpg

  6%|▌         | 511/8920 [32:14<2:54:13,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jae_Joong.jpg

  6%|▌         | 512/8920 [32:14<2:23:30,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Dong_Hae.jpg

  6%|▌         | 513/8920 [32:16<2:25:36,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wendy.jpg

  6%|▌         | 514/8920 [32:17<2:24:28,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han_Seung_Yeon.jpg

  6%|▌         | 515/8920 [32:17<2:12:05,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Won_Ho.jpg

  6%|▌         | 516/8920 [32:18<1:53:29,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Cho_Rong.jpg

  6%|▌         | 517/8920 [32:18<1:45:19,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahn_Heeyeon.jpg

  6%|▌         | 518/8920 [32:21<2:44:09,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soyou.jpg

  6%|▌         | 519/8920 [32:21<2:16:27,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yesung.jpg

  6%|▌         | 520/8920 [32:22<2:12:49,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Im_Si_Wan.jpg

  6%|▌         | 521/8920 [32:23<2:17:09,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yugyeom.jpg

  6%|▌         | 522/8920 [32:23<1:45:43,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joshua_Hong.jpg

  6%|▌         | 523/8920 [32:24<1:26:42,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Song_Joong_Ki.jpg

  6%|▌         | 524/8920 [32:24<1:14:08,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Jongsuk.jpg

  6%|▌         | 525/8920 [32:24<1:13:51,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Seo_Joon.jpg

  6%|▌         | 526/8920 [32:25<1:11:14,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji_Chang_Wook.jpg

  6%|▌         | 527/8920 [32:25<1:04:41,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hyun_Bin.jpg

  6%|▌         | 528/8920 [32:25<55:03,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Shin_Hye.jpg

  6%|▌         | 529/8920 [32:26<1:17:38,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gong_Yoo.jpg

  6%|▌         | 530/8920 [32:28<1:42:27,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Ye_Jin.jpg

  6%|▌         | 531/8920 [32:28<1:23:57,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nam_Joo_Hyuk.jpg

  6%|▌         | 532/8920 [32:28<1:08:23,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Soo_Hyun.jpg

  6%|▌         | 533/8920 [32:28<1:01:50,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bae_Suzy.jpg

  6%|▌         | 534/8920 [32:29<1:25:00,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Bo-Gum.jpg

  6%|▌         | 535/8920 [32:30<1:23:43,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Dong_Wook.jpg

  6%|▌         | 536/8920 [32:33<3:11:13,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jun_Ji_Hyun.jpg

  6%|▌         | 537/8920 [32:34<2:54:12,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Woo_Bin.jpg

  6%|▌         | 538/8920 [32:34<2:15:38,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_So_Hyun.jpg

  6%|▌         | 539/8920 [32:35<1:47:56,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Min_Young.jpg

  6%|▌         | 540/8920 [32:36<2:07:06,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Joon_Gi.jpg

  6%|▌         | 541/8920 [32:36<1:40:11,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yoo_Jung.jpg

  6%|▌         | 542/8920 [32:38<2:13:48,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyun_Joong.jpg

  6%|▌         | 543/8920 [32:38<1:58:53,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Go_Eun.jpg

  6%|▌         | 544/8920 [32:39<1:53:18,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Song_Ji_Hyo.jpg

  6%|▌         | 545/8920 [32:39<1:38:10,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han_Hyo_Joo.jpg

  6%|▌         | 546/8920 [32:41<2:15:00,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Sung_Kyung.jpg

  6%|▌         | 547/8920 [32:41<1:45:28,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Bo_Young.jpg

  6%|▌         | 548/8920 [32:42<1:23:31,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Bum.jpg

  6%|▌         | 549/8920 [32:42<1:23:20,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung_So_Min.jpg

  6%|▌         | 550/8920 [32:43<1:27:58,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Min_Ho.jpg

  6%|▌         | 551/8920 [32:44<1:28:00,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ha_Ji_Won.jpg

  6%|▌         | 552/8920 [32:44<1:39:21,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Hae_Jin.jpg

  6%|▌         | 553/8920 [32:45<1:35:06,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Tae_Hee.jpg

  6%|▌         | 554/8920 [32:46<1:30:15,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_In_Na.jpg

  6%|▌         | 555/8920 [32:46<1:26:39,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji_Sung.jpg

  6%|▌         | 556/8920 [32:48<2:19:47,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Cho.jpg

  6%|▌         | 557/8920 [32:49<2:07:49,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Kwang_Soo.jpg

  6%|▋         | 558/8920 [32:49<1:57:15,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung_Il_Woo.jpg

  6%|▋         | 559/8920 [32:50<1:43:06,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sung_Hoon.jpg

  6%|▋         | 560/8920 [32:51<2:08:16,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Min_A.jpg

  6%|▋         | 561/8920 [32:52<1:42:35,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/So_Ji_Sub.jpg

  6%|▋         | 562/8920 [32:52<1:39:58,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Tae_Ri.jpg

  6%|▋         | 563/8920 [32:53<1:52:22,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Seung_Ho.jpg

  6%|▋         | 564/8920 [32:54<1:42:09,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Hyuk.jpg

  6%|▋         | 565/8920 [32:54<1:36:57,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Se_Kyung.jpg

  6%|▋         | 566/8920 [32:55<1:17:27,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bong_Joon_Ho.jpg

  6%|▋         | 567/8920 [32:55<1:19:27,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ma_Dong-Seok.jpg

  6%|▋         | 568/8920 [32:56<1:20:50,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahn_Jae_Hyun.jpg

  6%|▋         | 569/8920 [32:56<1:18:04,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kang_Ha_Neul.jpg

  6%|▋         | 570/8920 [32:59<2:24:16,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Yeon_Seo.jpg

  6%|▋         | 571/8920 [32:59<1:53:37,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xiumin.jpg

  6%|▋         | 572/8920 [33:00<1:56:07,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Yeon-Seok.jpg

  6%|▋         | 573/8920 [33:01<1:55:15,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_Hyun_Jin.jpg

  6%|▋         | 574/8920 [33:03<3:18:09,  1.42s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeo_Jin_Goo.jpg

  6%|▋         | 575/8920 [33:04<2:29:00,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Song_Hye_Kyo.jpg

  6%|▋         | 576/8920 [33:04<2:08:23,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gong_Hyo_Jin.jpg

  6%|▋         | 577/8920 [33:04<1:42:34,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seohyun.jpg

  6%|▋         | 578/8920 [33:05<1:26:02,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Chae_Won.jpg

  6%|▋         | 579/8920 [33:05<1:27:28,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji_Soo.jpg

  7%|▋         | 580/8920 [33:06<1:37:06,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yook_Sung_Jae.jpg

  7%|▋         | 581/8920 [33:07<1:28:43,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Ah_In.jpg

  7%|▋         | 582/8920 [33:08<1:38:21,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Jae_Suk.jpg

  7%|▋         | 583/8920 [33:08<1:20:38,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Bo_Young.jpg

  7%|▋         | 584/8920 [33:09<1:38:47,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Keun_Suk.jpg

  7%|▋         | 585/8920 [33:10<1:40:36,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_So_Eun.jpg

  7%|▋         | 586/8920 [33:11<2:18:38,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hwang_Jung_Eum.jpg

  7%|▋         | 587/8920 [33:12<1:57:28,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joo_Won.jpg

  7%|▋         | 588/8920 [33:13<2:18:37,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Tae_Joon.jpg

  7%|▋         | 589/8920 [33:15<2:51:44,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Woo-Shik.jpg

  7%|▋         | 590/8920 [33:16<2:53:09,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoon_Eun_Hye.jpg

  7%|▋         | 591/8920 [33:18<3:18:18,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han_Ji_Min.jpg

  7%|▋         | 592/8920 [33:18<2:32:05,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_So_Yeon.jpg

  7%|▋         | 593/8920 [33:19<2:13:34,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoon_Kyun_Sang.jpg

  7%|▋         | 594/8920 [33:19<1:46:13,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bae_Doona.jpg

  7%|▋         | 595/8920 [33:20<1:57:32,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeon_Woo_Jin.jpg

  7%|▋         | 596/8920 [33:21<2:00:14,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Se_Young.jpg

  7%|▋         | 597/8920 [33:22<2:10:37,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Jin_Wook.jpg

  7%|▋         | 598/8920 [33:23<1:44:02,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Jae_In.jpg

  7%|▋         | 599/8920 [33:23<1:24:56,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yi_Sun_Sin.jpg

  7%|▋         | 600/8920 [33:23<1:16:09,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Syngman_Rhee.jpg

  7%|▋         | 601/8920 [33:24<1:18:06,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Dae.jpg

  7%|▋         | 602/8920 [33:24<1:03:38,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Chung_Hee.jpg

  7%|▋         | 603/8920 [33:25<1:19:57,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Young-Sam.jpg

  7%|▋         | 604/8920 [33:26<1:13:13,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Myung-Bak.jpg

  7%|▋         | 605/8920 [33:26<1:05:54,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Hong_Hi.jpg

  7%|▋         | 606/8920 [33:26<56:25,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roh_Tae-Woo.jpg

  7%|▋         | 607/8920 [33:27<58:37,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Won-Soon.jpg

  7%|▋         | 608/8920 [33:28<1:40:20,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Gu.jpg

  7%|▋         | 609/8920 [33:28<1:22:09,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roh_Moo-Hyun.jpg

  7%|▋         | 610/8920 [33:29<1:25:04,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eul-Dong_Kim.jpg

  7%|▋         | 611/8920 [33:30<1:24:50,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Posun.jpg

  7%|▋         | 612/8920 [33:30<1:10:46,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Geun_Hye.jpg

  7%|▋         | 613/8920 [33:30<1:14:20,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahn_Cheol-Soo.jpg

  7%|▋         | 614/8920 [33:31<1:28:12,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Mong-Koo.jpg

  7%|▋         | 615/8920 [33:32<1:33:40,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chun_Doo-Hwan.jpg

  7%|▋         | 616/8920 [33:33<1:43:40,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Du-Han.jpg

  7%|▋         | 617/8920 [33:34<1:40:13,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeong_Dojeon.jpg

  7%|▋         | 618/8920 [33:34<1:42:03,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Mong-Joon.jpg

  7%|▋         | 619/8920 [33:35<1:21:50,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Chi-Ho.jpg

  7%|▋         | 620/8920 [33:35<1:23:02,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Kyu-Hah.jpg

  7%|▋         | 621/8920 [33:36<1:21:43,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Myon.jpg

  7%|▋         | 622/8920 [33:38<2:21:47,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Kyu-Sik.jpg

  7%|▋         | 623/8920 [33:38<1:49:41,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeong_Seung-Hwa.jpg

  7%|▋         | 624/8920 [33:39<1:55:27,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choe_Deok-Sin.jpg

  7%|▋         | 625/8920 [33:40<1:38:08,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Cha-Su.jpg

  7%|▋         | 626/8920 [33:40<1:35:39,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Seong-Su.jpg

  7%|▋         | 627/8920 [33:41<1:26:32,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lim_O-Kyeong.jpg

  7%|▋         | 628/8920 [33:41<1:25:41,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Ki-Chol.jpg

  7%|▋         | 629/8920 [33:42<1:38:09,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Il-Kwon.jpg

  7%|▋         | 630/8920 [33:42<1:19:56,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bae_Yong_Joon.jpg

  7%|▋         | 631/8920 [33:43<1:14:24,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Kun-Hee.jpg

  7%|▋         | 632/8920 [33:43<1:04:27,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Ju_Yung.jpg

  7%|▋         | 633/8920 [33:44<1:22:13,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Yoo_Ri.jpg

  7%|▋         | 634/8920 [33:44<1:10:18,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahn_Cheol-Soo.jpg

  7%|▋         | 635/8920 [33:45<1:14:29,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Kyuk-Ho.jpg

  7%|▋         | 636/8920 [33:45<1:03:26,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Mong-Hun.jpg

  7%|▋         | 637/8920 [33:46<1:26:13,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Woo-Jung.jpg

  7%|▋         | 638/8920 [33:47<1:39:45,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sang_Yoon.jpg

  7%|▋         | 639/8920 [33:48<1:56:41,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Dong-Bin.jpg

  7%|▋         | 640/8920 [33:49<1:43:35,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Se_Yung.jpg

  7%|▋         | 641/8920 [33:49<1:27:23,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Heung-Min.jpg

  7%|▋         | 642/8920 [33:50<1:44:51,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Ji-Sung.jpg

  7%|▋         | 643/8920 [33:51<1:25:44,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hines_Ward.jpg

  7%|▋         | 644/8920 [33:52<1:40:40,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Younghoe_Koo.jpg

  7%|▋         | 645/8920 [33:52<1:40:26,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ki_Sung-Yueng.jpg

  7%|▋         | 646/8920 [33:53<1:22:21,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dong_Hyun_Kim.jpg

  7%|▋         | 647/8920 [33:53<1:23:23,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yeon-Koung.jpg

  7%|▋         | 648/8920 [33:55<1:52:02,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin-Soo_Choo.jpg

  7%|▋         | 649/8920 [33:55<1:29:28,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/An_Se-Young.jpg

  7%|▋         | 650/8920 [33:55<1:22:11,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Koo_Ja-Cheol.jpg

  7%|▋         | 651/8920 [33:56<1:36:01,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Hong-Man.jpg

  7%|▋         | 652/8920 [33:57<1:31:09,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pak_Se-Ri.jpg

  7%|▋         | 653/8920 [33:57<1:15:18,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Yong-Dae.jpg

  7%|▋         | 654/8920 [33:58<1:35:52,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji-Man_Choi.jpg

  7%|▋         | 655/8920 [33:59<1:36:15,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_In-Bee.jpg

  7%|▋         | 656/8920 [34:00<1:38:55,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Chung-Yong.jpg

  7%|▋         | 657/8920 [34:00<1:44:55,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chan_Ho_Park.jpg

  7%|▋         | 658/8920 [34:01<1:21:53,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Chu-Young.jpg

  7%|▋         | 659/8920 [34:01<1:17:35,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chung_Hyeon.jpg

  7%|▋         | 660/8920 [34:01<1:06:24,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Dae-Hoon.jpg

  7%|▋         | 661/8920 [34:02<1:16:09,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ji_Dong-Won.jpg

  7%|▋         | 662/8920 [34:04<2:13:29,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung-Ho_Kang.jpg

  7%|▋         | 663/8920 [34:04<1:42:19,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Sung-Bin.jpg

  7%|▋         | 664/8920 [34:05<1:38:46,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Byung-Hyun_Kim.jpg

  7%|▋         | 665/8920 [34:05<1:21:21,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Woo-Jin.jpg

  7%|▋         | 666/8920 [34:06<1:20:42,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hyun-Jin_Ryu.jpg

  7%|▋         | 667/8920 [34:07<1:51:19,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Wan-Ho.jpg

  7%|▋         | 668/8920 [34:08<2:04:21,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Yo-Han.jpg

  8%|▊         | 669/8920 [34:09<1:54:28,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_So-Hee.jpg

  8%|▊         | 670/8920 [34:10<1:49:41,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kwang-Hyun_Kim.jpg

  8%|▊         | 671/8920 [34:10<1:25:41,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuna_Kim.jpg

  8%|▊         | 672/8920 [34:11<1:24:36,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Yeon-Jae.jpg

  8%|▊         | 673/8920 [34:11<1:28:48,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sung_Ji-Hyun.jpg

  8%|▊         | 674/8920 [34:12<1:24:46,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Sang-Uk.jpg

  8%|▊         | 675/8920 [34:12<1:27:32,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chae_Yoo-Jung.jpg

  8%|▊         | 676/8920 [34:13<1:13:46,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yang_Hyo-Jin.jpg

  8%|▊         | 677/8920 [34:13<1:19:52,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Hyun-Il.jpg

  8%|▊         | 678/8920 [34:14<1:20:25,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Sang-Young.jpg

  8%|▊         | 679/8920 [34:14<1:07:56,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ki_Bo-Bae.jpg

  8%|▊         | 680/8920 [34:16<1:51:55,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hwang_Chul-Soon.jpg

  8%|▊         | 681/8920 [34:17<1:55:45,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seo_Seung-Jae.jpg

  8%|▊         | 682/8920 [34:18<2:06:04,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jung-Hwan.jpg

  8%|▊         | 683/8920 [34:19<1:55:26,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ku_Bon-Chan.jpg

  8%|▊         | 684/8920 [34:19<1:41:59,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ko_Sung-Hyun.jpg

  8%|▊         | 685/8920 [34:20<1:40:54,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bang_Soo-Hyun.jpg

  8%|▊         | 686/8920 [34:20<1:27:29,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Joo-Bong.jpg

  8%|▊         | 687/8920 [34:21<1:41:24,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Dong_Gook.jpg

  8%|▊         | 688/8920 [34:22<1:48:29,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hong_Myung-Bo.jpg

  8%|▊         | 689/8920 [34:23<1:45:34,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Ji-Yeon.jpg

  8%|▊         | 690/8920 [34:24<1:43:24,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Seung-Chan.jpg

  8%|▊         | 691/8920 [34:24<1:35:28,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Duk-Koo.jpg

  8%|▊         | 692/8920 [34:25<1:34:18,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jung_Kyung-Eun.jpg

  8%|▊         | 693/8920 [34:25<1:15:25,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cho_Eun-Jung.jpg

  8%|▊         | 694/8920 [34:25<1:02:50,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Hye-Jin.jpg

  8%|▊         | 695/8920 [34:26<1:17:16,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Sang-Su.jpg

  8%|▊         | 696/8920 [34:26<1:06:04,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Yeon-Seong.jpg

  8%|▊         | 697/8920 [34:27<1:11:31,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gu_Bon-Gil.jpg

  8%|▊         | 698/8920 [34:27<1:01:44,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oh_Jin-Hyek.jpg

  8%|▊         | 699/8920 [34:27<53:01,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Im_Dong-Hyun.jpg

  8%|▊         | 700/8920 [34:29<1:44:43,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jong_Tae-Se.jpg

  8%|▊         | 701/8920 [34:30<1:36:20,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Sung-Min.jpg

  8%|▊         | 702/8920 [34:31<1:49:05,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Ahn.jpg

  8%|▊         | 703/8920 [34:32<1:55:41,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Gi-Jung.jpg

  8%|▊         | 704/8920 [34:33<2:18:39,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jang_Mi-Ran.jpg

  8%|▊         | 705/8920 [34:33<1:50:45,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Mi-Sun.jpg

  8%|▊         | 706/8920 [34:34<2:02:57,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Dong-Moon.jpg

  8%|▊         | 707/8920 [34:35<2:06:11,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Byung-Chul.jpg

  8%|▊         | 708/8920 [34:36<1:38:17,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Taek-Soo.jpg

  8%|▊         | 709/8920 [34:37<1:55:14,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_So-Yeong.jpg

  8%|▊         | 710/8920 [34:37<1:45:01,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Min-Soo.jpg

  8%|▊         | 711/8920 [34:38<1:25:09,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jin_Jong-Oh.jpg

  8%|▊         | 712/8920 [34:38<1:26:33,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shin_Baek-Cheol.jpg

  8%|▊         | 713/8920 [34:40<2:07:42,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Sa-Rang.jpg

  8%|▊         | 714/8920 [34:41<2:15:46,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hyeon-Jun.jpg

  8%|▊         | 715/8920 [34:42<2:01:22,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Hyo-Jung.jpg

  8%|▊         | 716/8920 [34:42<1:34:15,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Big_Marvel.jpg

  8%|▊         | 717/8920 [34:42<1:17:43,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Soo.jpg

  8%|▊         | 718/8920 [34:43<1:07:19,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zach_Choi.jpg

  8%|▊         | 719/8920 [34:43<1:14:57,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabrina_Azhar.jpg

  8%|▊         | 720/8920 [34:44<1:12:58,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nalu_Santana.jpg

  8%|▊         | 721/8920 [34:44<1:16:42,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Miso.jpg

  8%|▊         | 722/8920 [34:47<2:40:46,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erna_Limdaugh.jpg

  8%|▊         | 723/8920 [34:48<2:15:21,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daria_Eo.jpg

  8%|▊         | 724/8920 [34:49<2:17:34,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pooh_In_Korea.jpg

  8%|▊         | 725/8920 [34:50<2:14:19,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ppomo.jpg

  8%|▊         | 726/8920 [34:51<2:42:21,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minjun_Kim.jpg

  8%|▊         | 727/8920 [34:52<2:14:39,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tzuyang.jpg

  8%|▊         | 728/8920 [34:53<2:16:00,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bonggil.jpg

  8%|▊         | 729/8920 [34:53<2:02:32,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gwon_Sang-Yun.jpg

  8%|▊         | 730/8920 [34:55<2:22:16,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ae_Jeong.jpg

  8%|▊         | 731/8920 [34:55<2:04:49,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/_Narcissism_9.jpg

  8%|▊         | 732/8920 [34:57<2:32:09,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freezia.jpg

  8%|▊         | 733/8920 [35:00<3:33:33,  1.57s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaeyeol_Asmr.jpg

  8%|▊         | 734/8920 [35:00<2:53:54,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xx_Narci24.jpg

  8%|▊         | 735/8920 [35:01<2:22:24,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Kim.jpg

  8%|▊         | 736/8920 [35:02<2:35:06,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Kim.jpg

  8%|▊         | 737/8920 [35:03<2:13:42,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raon_Lee.jpg

  8%|▊         | 738/8920 [35:03<1:56:38,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ssinnim.jpg

  8%|▊         | 739/8920 [35:03<1:30:44,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Asmr.jpg

  8%|▊         | 740/8920 [35:05<1:50:58,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bendeen.jpg

  8%|▊         | 741/8920 [35:06<2:19:29,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gongsam_Table.jpg

  8%|▊         | 742/8920 [35:07<2:01:03,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sio_Asmr.jpg

  8%|▊         | 743/8920 [35:09<2:55:24,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eat_With_Boki.jpg

  8%|▊         | 744/8920 [35:10<2:28:34,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sohyun_Moon.jpg

  8%|▊         | 745/8920 [35:11<2:27:46,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sulgi_Yang.jpg

  8%|▊         | 746/8920 [35:11<2:12:42,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Latte_Asmr.jpg

  8%|▊         | 747/8920 [35:12<2:13:50,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ssoyoung.jpg

  8%|▊         | 748/8920 [35:13<1:59:05,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Rhee.jpg

  8%|▊         | 749/8920 [35:14<2:01:54,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jinwoo.jpg

  8%|▊         | 750/8920 [35:15<2:10:21,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Makrye.jpg

  8%|▊         | 751/8920 [35:16<2:13:05,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaykayes_128742.jpg

  8%|▊         | 752/8920 [35:17<2:19:17,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenn_Im.jpg

  8%|▊         | 753/8920 [35:17<1:47:05,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/V_Nguyn_Gip.jpg

  8%|▊         | 754/8920 [35:18<1:28:43,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Quang_Liêm.jpg

  8%|▊         | 755/8920 [35:18<1:13:30,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hồ_Văn_Ý.jpg

  8%|▊         | 756/8920 [35:18<1:01:29,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ho_Chi_Minh.jpg

  8%|▊         | 757/8920 [35:20<1:35:41,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Trang.jpg

  8%|▊         | 758/8920 [35:20<1:18:31,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Veronica_Ngo.jpg

  9%|▊         | 759/8920 [35:20<1:18:05,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Le_Duan.jpg

  9%|▊         | 760/8920 [35:21<1:10:42,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Tri_Nguyen.jpg

  9%|▊         | 761/8920 [35:21<1:15:22,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngo_Bao_Chau.jpg

  9%|▊         | 762/8920 [35:22<1:04:26,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gia_Long.jpg

  9%|▊         | 763/8920 [35:22<55:27,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madame_Nhu.jpg

  9%|▊         | 764/8920 [35:23<1:13:17,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lady_Trieu.jpg

  9%|▊         | 765/8920 [35:24<1:55:06,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Le_Duc_Tho.jpg

  9%|▊         | 766/8920 [35:25<1:32:34,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Hung_Dao.jpg

  9%|▊         | 767/8920 [35:25<1:16:41,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Lợi.jpg

  9%|▊         | 768/8920 [35:25<1:04:22,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thich_Quang_Duc.jpg

  9%|▊         | 769/8920 [35:26<1:10:06,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bao_Dai.jpg

  9%|▊         | 770/8920 [35:27<1:14:59,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Yersin.jpg

  9%|▊         | 771/8920 [35:27<1:03:31,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Ut.jpg

  9%|▊         | 772/8920 [35:27<1:08:53,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pham_Van_Dong.jpg

  9%|▊         | 773/8920 [35:28<1:00:28,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phi_Nhung.jpg

  9%|▊         | 774/8920 [35:28<1:05:27,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thich_Nhat_Hanh.jpg

  9%|▊         | 775/8920 [35:28<55:42,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linh_Dan_Pham.jpg

  9%|▊         | 776/8920 [35:29<49:08,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janet_Nguyen.jpg

  9%|▊         | 777/8920 [35:30<1:22:46,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minh_Mang.jpg

  9%|▊         | 778/8920 [35:32<2:21:29,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Boi_Chau.jpg

  9%|▊         | 779/8920 [35:33<2:04:14,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tấn_Dũng.jpg

  9%|▊         | 780/8920 [35:33<1:36:11,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacqueline_Nguyen.jpg

  9%|▉         | 781/8920 [35:34<1:39:12,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trưng_Trắc.jpg

  9%|▉         | 782/8920 [35:36<2:54:29,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phạm_Tuân.jpg

  9%|▉         | 783/8920 [35:37<2:32:22,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kieu_Chinh.jpg

  9%|▉         | 784/8920 [35:38<2:42:03,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Thu_Le.jpg

  9%|▉         | 785/8920 [35:39<2:07:31,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mai_Lan.jpg

  9%|▉         | 786/8920 [35:39<1:40:38,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tan_Le.jpg

  9%|▉         | 787/8920 [35:39<1:21:03,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leyna_Nguyen.jpg

  9%|▉         | 788/8920 [35:40<1:31:08,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tu_Duc.jpg

  9%|▉         | 789/8920 [35:41<1:47:12,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tôn_Đức_Thắng.jpg

  9%|▉         | 790/8920 [35:42<1:43:28,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trinh_T._Minh-Ha.jpg

  9%|▉         | 791/8920 [35:42<1:38:41,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khoa_Do.jpg

  9%|▉         | 792/8920 [35:44<2:02:37,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hung_Huynh.jpg

  9%|▉         | 793/8920 [35:44<1:48:14,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Du.jpg

  9%|▉         | 794/8920 [35:45<2:04:06,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Truong_Tan_Sang.jpg

  9%|▉         | 795/8920 [35:46<1:40:27,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoang_Xuan_Vinh.jpg

  9%|▉         | 796/8920 [35:46<1:21:48,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trish_Thuy_Trang.jpg

  9%|▉         | 797/8920 [35:47<1:19:56,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Huu_Tho.jpg

  9%|▉         | 798/8920 [35:47<1:07:19,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Anh_Hung.jpg

  9%|▉         | 799/8920 [35:48<1:48:47,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngô_Quyền.jpg

  9%|▉         | 800/8920 [35:49<1:48:41,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tiến_Minh.jpg

  9%|▉         | 801/8920 [35:51<2:07:02,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duy_Tân.jpg

  9%|▉         | 802/8920 [35:52<2:38:53,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Delpy.jpg

  9%|▉         | 803/8920 [35:52<2:00:43,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/To_Huu.jpg

  9%|▉         | 804/8920 [35:53<2:04:49,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thành_Thái.jpg

  9%|▉         | 805/8920 [35:55<2:13:05,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hàm_Nghi.jpg

  9%|▉         | 806/8920 [35:55<1:44:38,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ly_Thuong_Kiet.jpg

  9%|▉         | 807/8920 [35:55<1:23:45,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vy_Qwaint.jpg

  9%|▉         | 808/8920 [35:58<2:37:03,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trưng_Sisters.jpg

  9%|▉         | 809/8920 [35:58<2:01:26,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vo_Chi_Cong.jpg

  9%|▉         | 810/8920 [35:58<1:48:49,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Ireland.jpg

  9%|▉         | 811/8920 [35:59<1:46:06,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Nguyen.jpg

  9%|▉         | 812/8920 [36:00<1:27:21,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Thanh_Gian.jpg

  9%|▉         | 813/8920 [36:01<1:47:18,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pax_Thien_Jolie_Pitt.jpg

  9%|▉         | 814/8920 [36:01<1:26:34,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Truong.jpg

  9%|▉         | 815/8920 [36:02<1:55:45,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anh_Dao_Traxel.jpg

  9%|▉         | 816/8920 [36:03<1:47:45,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephane_Gauger.jpg

  9%|▉         | 817/8920 [36:04<2:09:16,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Văn_Thuận.jpg

  9%|▉         | 818/8920 [36:05<1:41:17,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Ngọc_Nguyên_Nhung.jpg

  9%|▉         | 819/8920 [36:05<1:35:34,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngo_Dinh_Diem.jpg

  9%|▉         | 820/8920 [36:05<1:16:01,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Văn_Tiến_Dũng.jpg

  9%|▉         | 821/8920 [36:06<1:03:39,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Van_Tan.jpg

  9%|▉         | 822/8920 [36:06<52:58,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Van_Thieu.jpg

  9%|▉         | 823/8920 [36:07<1:04:46,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Cao_Ky.jpg

  9%|▉         | 824/8920 [36:07<56:20,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Van_Tra.jpg

  9%|▉         | 825/8920 [36:07<1:06:55,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Haberkorn.jpg

  9%|▉         | 826/8920 [36:08<1:25:12,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Ngoc_Loan.jpg

  9%|▉         | 827/8920 [36:09<1:11:21,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Phan.jpg

  9%|▉         | 828/8920 [36:09<1:01:39,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dinh_Bo_Linh.jpg

  9%|▉         | 829/8920 [36:10<1:21:50,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ocean_Vuong.jpg

  9%|▉         | 830/8920 [36:10<1:06:44,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huynh_Phu_So.jpg

  9%|▉         | 831/8920 [36:11<1:00:44,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Chau_Trinh.jpg

  9%|▉         | 832/8920 [36:11<51:24,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duong_Van_Minh.jpg

  9%|▉         | 833/8920 [36:11<48:43,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Dinh_Phung.jpg

  9%|▉         | 834/8920 [36:11<48:00,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bebe_Pham.jpg

  9%|▉         | 835/8920 [36:12<43:59,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cuong_De.jpg

  9%|▉         | 836/8920 [36:13<1:09:52,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Truong_Chinh.jpg

  9%|▉         | 837/8920 [36:13<1:01:47,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tri_Phương.jpg

  9%|▉         | 838/8920 [36:14<1:09:55,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viet_D._Dinh.jpg

  9%|▉         | 839/8920 [36:14<1:01:16,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Khanh.jpg

  9%|▉         | 840/8920 [36:14<54:53,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/De_Tham.jpg

  9%|▉         | 841/8920 [36:15<1:19:05,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Văn_Linh.jpg

  9%|▉         | 842/8920 [36:16<1:09:31,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Đỗ_Tuấn_Đức.jpg

  9%|▉         | 843/8920 [36:16<1:20:01,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Van_Thinh.jpg

  9%|▉         | 844/8920 [36:19<2:47:43,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khúc_Thừa_Dụ.jpg

  9%|▉         | 845/8920 [36:20<2:26:14,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ieng_Sary.jpg

  9%|▉         | 846/8920 [36:21<2:25:53,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Phúc_Tần.jpg

  9%|▉         | 847/8920 [36:22<2:19:11,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Ardizzone.jpg

 10%|▉         | 848/8920 [36:23<2:04:05,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Khoi.jpg

 10%|▉         | 849/8920 [36:24<2:08:44,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Mai.jpg

 10%|▉         | 850/8920 [36:25<2:15:10,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Đèo_Văn_Trị.jpg

 10%|▉         | 851/8920 [36:25<1:44:08,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khai_Dinh.jpg

 10%|▉         | 852/8920 [36:25<1:22:17,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Ngoc_Chau.jpg

 10%|▉         | 853/8920 [36:26<1:22:08,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/V_Nguyn_Gip.jpg

 10%|▉         | 854/8920 [36:26<1:07:12,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ho_Chi_Minh.jpg

 10%|▉         | 855/8920 [36:26<58:21,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cung_Le.jpg

 10%|▉         | 856/8920 [36:26<49:06,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thich_Quang_Duc.jpg

 10%|▉         | 857/8920 [36:27<44:08,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Le_Duan.jpg

 10%|▉         | 858/8920 [36:28<1:19:38,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bao_Dai.jpg

 10%|▉         | 859/8920 [36:28<1:06:55,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Le_Duc_Tho.jpg

 10%|▉         | 860/8920 [36:28<58:47,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Tri_Nguyen.jpg

 10%|▉         | 861/8920 [36:30<1:47:35,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gia_Long.jpg

 10%|▉         | 862/8920 [36:31<2:09:36,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngo_Bao_Chau.jpg

 10%|▉         | 863/8920 [36:32<1:54:43,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Ut.jpg

 10%|▉         | 864/8920 [36:32<1:29:02,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Lợi.jpg

 10%|▉         | 865/8920 [36:34<1:55:40,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Hung_Dao.jpg

 10%|▉         | 866/8920 [36:34<1:33:40,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pham_Van_Dong.jpg

 10%|▉         | 867/8920 [36:34<1:17:31,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Yersin.jpg

 10%|▉         | 868/8920 [36:34<1:03:28,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minh_Mang.jpg

 10%|▉         | 869/8920 [36:35<58:25,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hung_Huynh.jpg

 10%|▉         | 870/8920 [36:35<52:15,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tấn_Dũng.jpg

 10%|▉         | 871/8920 [36:36<1:03:53,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Anh_Hung.jpg

 10%|▉         | 872/8920 [36:36<57:16,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tôn_Đức_Thắng.jpg

 10%|▉         | 873/8920 [36:37<1:08:33,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Văn_Tiến_Dũng.jpg

 10%|▉         | 874/8920 [36:37<57:42,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Van_Thieu.jpg

 10%|▉         | 875/8920 [36:37<52:14,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phan_Boi_Chau.jpg

 10%|▉         | 876/8920 [36:38<48:02,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Truong_Tan_Sang.jpg

 10%|▉         | 877/8920 [36:38<44:57,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngo_Dinh_Diem.jpg

 10%|▉         | 878/8920 [36:38<51:37,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Haberkorn.jpg

 10%|▉         | 879/8920 [36:39<45:51,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thich_Nhat_Hanh.jpg

 10%|▉         | 880/8920 [36:39<56:38,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Cao_Ky.jpg

 10%|▉         | 881/8920 [36:41<1:32:23,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Ngoc_Loan.jpg

 10%|▉         | 882/8920 [36:41<1:17:36,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tu_Duc.jpg

 10%|▉         | 883/8920 [36:41<1:05:46,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phạm_Tuân.jpg

 10%|▉         | 884/8920 [36:42<1:12:45,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Phan.jpg

 10%|▉         | 885/8920 [36:42<1:02:56,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Quang_Liêm.jpg

 10%|▉         | 886/8920 [36:43<1:36:55,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ocean_Vuong.jpg

 10%|▉         | 887/8920 [36:44<1:28:01,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Van_Tra.jpg

 10%|▉         | 888/8920 [36:44<1:17:48,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duong_Van_Minh.jpg

 10%|▉         | 889/8920 [36:45<1:06:36,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Truong_Chinh.jpg

 10%|▉         | 890/8920 [36:45<58:12,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khoa_Do.jpg

 10%|▉         | 891/8920 [36:46<1:06:56,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Huu_Tho.jpg

 10%|█         | 892/8920 [36:47<1:41:44,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duy_Tân.jpg

 10%|█         | 893/8920 [36:47<1:20:46,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoang_Xuan_Vinh.jpg

 10%|█         | 894/8920 [36:48<1:24:32,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ngô_Quyền.jpg

 10%|█         | 895/8920 [36:48<1:10:38,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Khanh.jpg

 10%|█         | 896/8920 [36:48<1:01:34,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Du.jpg

 10%|█         | 897/8920 [36:50<1:34:41,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ieng_Sary.jpg

 10%|█         | 898/8920 [36:50<1:32:32,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tiến_Minh.jpg

 10%|█         | 899/8920 [36:51<1:16:53,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thành_Thái.jpg

 10%|█         | 900/8920 [36:51<1:17:49,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Văn_Linh.jpg

 10%|█         | 901/8920 [36:52<1:02:59,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hàm_Nghi.jpg

 10%|█         | 902/8920 [36:52<1:06:29,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viet_D._Dinh.jpg

 10%|█         | 903/8920 [36:52<56:07,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Trang.jpg

 10%|█         | 904/8920 [36:53<1:04:25,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Veronica_Ngo.jpg

 10%|█         | 905/8920 [36:53<58:29,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madame_Nhu.jpg

 10%|█         | 906/8920 [36:54<49:20,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lady_Trieu.jpg

 10%|█         | 907/8920 [36:54<44:02,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linh_Dan_Pham.jpg

 10%|█         | 908/8920 [36:54<40:07,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phi_Nhung.jpg

 10%|█         | 909/8920 [36:54<39:13,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacqueline_Nguyen.jpg

 10%|█         | 910/8920 [36:55<53:41,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janet_Nguyen.jpg

 10%|█         | 911/8920 [36:55<52:16,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Thu_Le.jpg

 10%|█         | 912/8920 [36:56<47:31,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kieu_Chinh.jpg

 10%|█         | 913/8920 [36:56<44:03,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leyna_Nguyen.jpg

 10%|█         | 914/8920 [36:56<42:58,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mai_Lan.jpg

 10%|█         | 915/8920 [36:56<41:56,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trinh_T._Minh-Ha.jpg

 10%|█         | 916/8920 [36:58<1:21:30,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trưng_Sisters.jpg

 10%|█         | 917/8920 [36:59<1:55:05,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tan_Le.jpg

 10%|█         | 918/8920 [36:59<1:32:02,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trưng_Trắc.jpg

 10%|█         | 919/8920 [37:00<1:37:24,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bebe_Pham.jpg

 10%|█         | 920/8920 [37:01<1:20:28,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trish_Thuy_Trang.jpg

 10%|█         | 921/8920 [37:01<1:08:09,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anh_Dao_Traxel.jpg

 10%|█         | 922/8920 [37:01<56:12,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vy_Qwaint.jpg

 10%|█         | 923/8920 [37:01<47:43,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Ngọc_Nguyên_Nhung.jpg

 10%|█         | 924/8920 [37:02<44:34,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tien_Nguyen.jpg

 10%|█         | 925/8920 [37:02<43:42,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mai_Van_Trang.jpg

 10%|█         | 926/8920 [37:03<56:05,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linh_Miu.jpg

 10%|█         | 927/8920 [37:03<1:07:51,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Quynh_Thi.jpg

 10%|█         | 928/8920 [37:04<58:22,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anh_Thu_Mai.jpg

 10%|█         | 929/8920 [37:04<50:28,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Nhu_Le.jpg

 10%|█         | 930/8920 [37:06<1:47:01,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han_Hang.jpg

 10%|█         | 931/8920 [37:06<1:26:12,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Li.Ilii.jpg

 10%|█         | 932/8920 [37:06<1:12:07,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bui_Chau.jpg

 10%|█         | 933/8920 [37:07<1:28:30,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jun_Wu.jpg

 10%|█         | 934/8920 [37:08<1:51:58,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunnie_Miller.jpg

 10%|█         | 935/8920 [37:09<1:28:55,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoang_Kim_Ngan.jpg

 10%|█         | 936/8920 [37:09<1:13:44,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Parisa_Official.jpg

 11%|█         | 937/8920 [37:09<1:01:35,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huynh_Nhat_Hoa.jpg

 11%|█         | 938/8920 [37:09<54:34,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuha_Cao.jpg

 11%|█         | 939/8920 [37:10<1:02:02,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Vi.jpg

 11%|█         | 940/8920 [37:10<56:38,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Myha_Luong.jpg

 11%|█         | 941/8920 [37:11<1:20:04,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ann_Asmr.jpg

 11%|█         | 942/8920 [37:13<1:41:55,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Do_Linh_Chi.jpg

 11%|█         | 943/8920 [37:14<2:00:59,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khanh_Van.jpg

 11%|█         | 944/8920 [37:14<1:36:33,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bbysimmii.jpg

 11%|█         | 945/8920 [37:14<1:17:34,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thanh_Phuog.jpg

 11%|█         | 946/8920 [37:15<1:02:27,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lykio_Lalaschool.jpg

 11%|█         | 947/8920 [37:15<53:00,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linh_Nhi.jpg

 11%|█         | 948/8920 [37:15<46:05,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lacey_Bibi.jpg

 11%|█         | 949/8920 [37:15<40:38,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mai_Ngọc.jpg

 11%|█         | 950/8920 [37:15<39:58,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Choi_Minah.jpg

 11%|█         | 951/8920 [37:16<52:40,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kieuchang.02.jpg

 11%|█         | 952/8920 [37:17<1:31:26,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyen_Thi_Hoai_Thuong.jpg

 11%|█         | 953/8920 [37:18<1:16:39,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoang_Xuan_Vinh.jpg

 11%|█         | 954/8920 [37:18<1:04:06,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nguyễn_Tiến_Minh.jpg

 11%|█         | 955/8920 [37:18<53:49,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Quang_Liêm.jpg

 11%|█         | 956/8920 [37:19<51:11,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Nguyen.jpg

 11%|█         | 957/8920 [37:19<45:46,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lê_Ngọc_Nguyên_Nhung.jpg

 11%|█         | 958/8920 [37:20<1:21:39,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Truong.jpg

 11%|█         | 959/8920 [37:20<1:10:27,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Đỗ_Tuấn_Đức.jpg

 11%|█         | 960/8920 [37:21<1:00:26,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoang_Thanh_Trang.jpg

 11%|█         | 961/8920 [37:21<1:10:23,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hồ_Văn_Ý.jpg

 11%|█         | 962/8920 [37:22<1:14:49,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Trang.jpg

 11%|█         | 963/8920 [37:22<1:03:26,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Veronica_Ngo.jpg

 11%|█         | 964/8920 [37:23<56:36,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Tri_Nguyen.jpg

 11%|█         | 965/8920 [37:23<57:29,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linh_Dan_Pham.jpg

 11%|█         | 966/8920 [37:23<54:30,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Haberkorn.jpg

 11%|█         | 967/8920 [37:24<49:02,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trinh_T._Minh-Ha.jpg

 11%|█         | 968/8920 [37:24<44:43,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Thu_Le.jpg

 11%|█         | 969/8920 [37:24<40:28,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tran_Anh_Hung.jpg

 11%|█         | 970/8920 [37:25<38:28,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kieu_Chinh.jpg

 11%|█         | 971/8920 [37:25<39:20,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khoa_Do.jpg

 11%|█         | 972/8920 [37:25<38:41,  3.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Delpy.jpg

 11%|█         | 973/8920 [37:25<35:41,  3.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Phan.jpg

 11%|█         | 974/8920 [37:26<36:02,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephane_Gauger.jpg

 11%|█         | 975/8920 [37:26<38:13,  3.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khabib_Nurmagomedov.jpg

 11%|█         | 976/8920 [37:26<37:57,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Lenin.jpg

 11%|█         | 977/8920 [37:28<1:47:53,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_The_Great.jpg

 11%|█         | 978/8920 [37:29<1:29:33,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Sharapova.jpg

 11%|█         | 979/8920 [37:29<1:31:29,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leo_Tolstoy.jpg

 11%|█         | 980/8920 [37:30<1:16:05,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Ilyich_Tchaikovsky.jpg

 11%|█         | 981/8920 [37:31<2:00:53,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Gorbachev.jpg

 11%|█         | 982/8920 [37:32<2:04:32,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_The_Great.jpg

 11%|█         | 983/8920 [37:34<2:21:50,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Shayk.jpg

 11%|█         | 984/8920 [37:34<2:05:45,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ovechkin.jpg

 11%|█         | 985/8920 [37:35<1:50:42,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Chekhov.jpg

 11%|█         | 986/8920 [37:35<1:28:30,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Dostoevsky.jpg

 11%|█         | 987/8920 [37:36<1:13:15,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Kasparov.jpg

 11%|█         | 988/8920 [37:36<1:03:09,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Mendeleev.jpg

 11%|█         | 989/8920 [37:36<54:42,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Pushkin.jpg

 11%|█         | 990/8920 [37:36<48:22,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Yashin.jpg

 11%|█         | 991/8920 [37:37<44:30,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Rachmaninoff.jpg

 11%|█         | 992/8920 [37:37<53:39,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wassily_Kandinsky.jpg

 11%|█         | 993/8920 [37:37<49:46,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Nureyev.jpg

 11%|█         | 994/8920 [37:38<46:33,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Isayevich_Solzhenitsyn.jpg

 11%|█         | 995/8920 [37:38<56:40,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ii_Of_Russia.jpg

 11%|█         | 996/8920 [37:39<1:03:46,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Zhukov.jpg

 11%|█         | 997/8920 [37:39<59:13,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fedor_Emelianenko.jpg

 11%|█         | 998/8920 [37:40<1:05:42,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_The_Terrible.jpg

 11%|█         | 999/8920 [37:40<57:58,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Stravinsky.jpg

 11%|█         | 1000/8920 [37:41<1:05:01,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigori_Perelman.jpg

 11%|█         | 1001/8920 [37:41<58:05,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tarkovsky.jpg

 11%|█         | 1002/8920 [37:42<57:33,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Kropotkin.jpg

 11%|█         | 1003/8920 [37:42<54:17,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Pavlova.jpg

 11%|█▏        | 1004/8920 [37:42<47:15,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgenia_Medvedeva.jpg

 11%|█▏        | 1005/8920 [37:43<49:40,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Karpov.jpg

 11%|█▏        | 1006/8920 [37:43<59:54,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Kvyat.jpg

 11%|█▏        | 1007/8920 [37:44<51:39,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Gorky.jpg

 11%|█▏        | 1008/8920 [37:45<1:26:35,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Zagitova.jpg

 11%|█▏        | 1009/8920 [37:45<1:12:10,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kazimir_Malevich.jpg

 11%|█▏        | 1010/8920 [37:45<1:01:39,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vaslav_Nijinsky.jpg

 11%|█▏        | 1011/8920 [37:46<53:28,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Netrebko.jpg

 11%|█▏        | 1012/8920 [37:46<48:41,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Eisenstein.jpg

 11%|█▏        | 1013/8920 [37:46<51:28,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Isinbayeva.jpg

 11%|█▏        | 1014/8920 [37:47<1:16:56,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Grinkov.jpg

 11%|█▏        | 1015/8920 [37:48<1:18:02,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nataliya_Kuznetsova.jpg

 11%|█▏        | 1016/8920 [37:48<1:03:29,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Nepomniachtchi.jpg

 11%|█▏        | 1017/8920 [37:49<55:36,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Alekhine.jpg

 11%|█▏        | 1018/8920 [37:49<49:54,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Vodianova_35828.jpg

 11%|█▏        | 1019/8920 [37:49<43:33,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Spassky.jpg

 11%|█▏        | 1020/8920 [37:52<2:22:39,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Lipnitskaya.jpg

 11%|█▏        | 1021/8920 [37:52<1:51:21,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Politkovskaya.jpg

 11%|█▏        | 1022/8920 [37:52<1:29:32,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Gordeeva.jpg

 11%|█▏        | 1023/8920 [37:54<2:03:56,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galina_Ulanova.jpg

 11%|█▏        | 1024/8920 [37:54<1:39:24,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Alekseyev.jpg

 11%|█▏        | 1025/8920 [37:55<1:22:59,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Diaghilev.jpg

 12%|█▏        | 1026/8920 [37:56<1:50:06,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Kabaeva.jpg

 12%|█▏        | 1027/8920 [37:56<1:27:41,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgeny_Kissin.jpg

 12%|█▏        | 1028/8920 [37:57<1:18:19,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maya_Plisetskaya.jpg

 12%|█▏        | 1029/8920 [37:57<1:06:47,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sviatoslav_Richter.jpg

 12%|█▏        | 1030/8920 [37:57<59:26,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Zakharova.jpg

 12%|█▏        | 1031/8920 [37:58<52:05,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizaveta_Tuktamysheva.jpg

 12%|█▏        | 1032/8920 [37:59<1:44:05,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petr_Yan.jpg

 12%|█▏        | 1033/8920 [38:00<1:24:46,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Ashkenazy.jpg

 12%|█▏        | 1034/8920 [38:00<1:21:47,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Fedorov.jpg

 12%|█▏        | 1035/8920 [38:00<1:08:39,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Kramnik.jpg

 12%|█▏        | 1036/8920 [38:01<59:02,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_K._Zworykin.jpg

 12%|█▏        | 1037/8920 [38:01<49:47,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgeni_Plushenko.jpg

 12%|█▏        | 1038/8920 [38:01<46:05,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Kosteniuk.jpg

 12%|█▏        | 1039/8920 [38:01<43:05,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Smyslov.jpg

 12%|█▏        | 1040/8920 [38:02<40:59,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Lobachevsky.jpg

 12%|█▏        | 1041/8920 [38:02<41:51,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Grischuk.jpg

 12%|█▏        | 1042/8920 [38:02<40:36,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Glukhovsky.jpg

 12%|█▏        | 1043/8920 [38:03<39:23,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michel_Fokine.jpg

 12%|█▏        | 1044/8920 [38:03<39:19,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Trifonov.jpg

 12%|█▏        | 1045/8920 [38:04<51:46,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galina_Vishnevskaya.jpg

 12%|█▏        | 1046/8920 [38:04<50:31,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Nemov.jpg

 12%|█▏        | 1047/8920 [38:04<44:16,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irena_Szewińska.jpg

 12%|█▏        | 1048/8920 [38:04<42:22,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludmilla_Tourischeva.jpg

 12%|█▏        | 1049/8920 [38:05<39:11,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Bure.jpg

 12%|█▏        | 1050/8920 [38:05<38:54,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislav_Artemiev.jpg

 12%|█▏        | 1051/8920 [38:06<1:20:31,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Popov.jpg

 12%|█▏        | 1052/8920 [38:07<1:08:23,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Makarova.jpg

 12%|█▏        | 1053/8920 [38:07<59:38,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emil_Gilels.jpg

 12%|█▏        | 1054/8920 [38:08<1:05:14,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Dobromyslova.jpg

 12%|█▏        | 1055/8920 [38:08<55:59,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ostrovsky.jpg

 12%|█▏        | 1056/8920 [38:08<48:14,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Osipova.jpg

 12%|█▏        | 1057/8920 [38:08<50:13,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Mravinsky.jpg

 12%|█▏        | 1058/8920 [38:09<1:06:42,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Esipenko.jpg

 12%|█▏        | 1059/8920 [38:10<56:26,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Radionova.jpg

 12%|█▏        | 1060/8920 [38:10<50:14,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artem_Vakhitov.jpg

 12%|█▏        | 1061/8920 [38:11<1:03:49,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buvaisar_Saitiev.jpg

 12%|█▏        | 1062/8920 [38:11<54:02,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Ponomarenko.jpg

 12%|█▏        | 1063/8920 [38:11<48:15,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Shushunova.jpg

 12%|█▏        | 1064/8920 [38:11<43:47,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Vishneva.jpg

 12%|█▏        | 1065/8920 [38:12<41:37,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Winogradsky.jpg

 12%|█▏        | 1066/8920 [38:12<40:00,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/El_Lissitzky.jpg

 12%|█▏        | 1067/8920 [38:12<38:27,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yekaterina_Gamova.jpg

 12%|█▏        | 1068/8920 [38:13<1:10:29,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Saitiev.jpg

 12%|█▏        | 1069/8920 [38:14<1:02:11,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Zamolodchikova.jpg

 12%|█▏        | 1070/8920 [38:15<1:33:46,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Trankov.jpg

 12%|█▏        | 1071/8920 [38:15<1:15:54,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirill_Alekseenko.jpg

 12%|█▏        | 1072/8920 [38:15<1:04:13,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Salnikov.jpg

 12%|█▏        | 1073/8920 [38:16<55:15,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Talant_Dujshebaev.jpg

 12%|█▏        | 1074/8920 [38:19<2:42:51,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Vlasov.jpg

 12%|█▏        | 1075/8920 [38:19<2:06:10,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khabib_Nurmagomedov.jpg

 12%|█▏        | 1076/8920 [38:19<1:41:24,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Lenin.jpg

 12%|█▏        | 1077/8920 [38:20<1:35:52,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Gorbachev.jpg

 12%|█▏        | 1078/8920 [38:21<1:58:12,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leo_Tolstoy.jpg

 12%|█▏        | 1079/8920 [38:22<1:55:56,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Brin.jpg

 12%|█▏        | 1080/8920 [38:22<1:31:55,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_The_Great.jpg

 12%|█▏        | 1081/8920 [38:24<1:57:09,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ovechkin.jpg

 12%|█▏        | 1083/8920 [38:24<1:11:41,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Ilyich_Tchaikovsky.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Kasparov.jpg

 12%|█▏        | 1084/8920 [38:25<1:03:54,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Dostoevsky.jpg

 12%|█▏        | 1085/8920 [38:25<1:00:56,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fedor_Emelianenko.jpg

 12%|█▏        | 1086/8920 [38:26<1:23:58,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Chekhov.jpg

 12%|█▏        | 1087/8920 [38:27<1:45:34,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_The_Terrible.jpg

 12%|█▏        | 1088/8920 [38:29<2:18:28,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ii_Of_Russia.jpg

 12%|█▏        | 1089/8920 [38:29<1:48:56,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Mendeleev.jpg

 12%|█▏        | 1090/8920 [38:30<1:26:57,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Zhukov.jpg

 12%|█▏        | 1091/8920 [38:30<1:10:11,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wassily_Kandinsky.jpg

 12%|█▏        | 1092/8920 [38:30<1:12:29,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Putin.jpg

 12%|█▏        | 1093/8920 [38:32<2:06:54,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Isayevich_Solzhenitsyn.jpg

 12%|█▏        | 1094/8920 [38:33<1:37:57,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Rachmaninoff.jpg

 12%|█▏        | 1095/8920 [38:33<1:16:57,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Pushkin.jpg

 12%|█▏        | 1096/8920 [38:33<1:03:02,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Nureyev.jpg

 12%|█▏        | 1097/8920 [38:33<53:57,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Ii.jpg

 12%|█▏        | 1098/8920 [38:33<46:59,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Yashin.jpg

 12%|█▏        | 1099/8920 [38:34<51:17,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Gagarin.jpg

 12%|█▏        | 1100/8920 [38:34<46:44,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Trotsky.jpg

 12%|█▏        | 1101/8920 [38:35<47:59,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Stravinsky.jpg

 12%|█▏        | 1102/8920 [38:35<41:57,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Abramovich.jpg

 12%|█▏        | 1103/8920 [38:35<38:39,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Pavlov.jpg

 12%|█▏        | 1104/8920 [38:36<1:03:03,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tarkovsky.jpg

 12%|█▏        | 1105/8920 [38:37<1:20:15,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aziz.jpg

 12%|█▏        | 1106/8920 [38:37<1:07:18,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigori_Perelman.jpg

 12%|█▏        | 1107/8920 [38:37<55:40,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Yeltsin.jpg

 12%|█▏        | 1108/8920 [38:38<46:56,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Navalny.jpg

 12%|█▏        | 1109/8920 [38:38<42:47,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Vygotsky.jpg

 12%|█▏        | 1110/8920 [38:38<44:15,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Kvyat.jpg

 12%|█▏        | 1111/8920 [38:39<53:11,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Komarov.jpg

 12%|█▏        | 1112/8920 [38:39<49:45,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_I_Of_Russia.jpg

 12%|█▏        | 1113/8920 [38:40<1:28:10,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Karpov.jpg

 12%|█▏        | 1114/8920 [38:43<2:41:35,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Shostakovich.jpg

 12%|█▎        | 1115/8920 [38:43<2:02:39,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Eisenstein.jpg

 13%|█▎        | 1116/8920 [38:45<2:32:14,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Kropotkin.jpg

 13%|█▎        | 1117/8920 [38:46<2:12:03,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Iii_Of_Russia.jpg

 13%|█▎        | 1118/8920 [38:46<1:43:07,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Gorky.jpg

 13%|█▎        | 1119/8920 [38:46<1:25:50,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Kalashnikov.jpg

 13%|█▎        | 1120/8920 [38:47<1:38:06,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Stalin.jpg

 13%|█▎        | 1121/8920 [38:48<1:56:31,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Medvedev.jpg

 13%|█▎        | 1122/8920 [38:49<1:41:03,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitalik_Buterin.jpg

 13%|█▎        | 1123/8920 [38:49<1:29:00,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Nikolaevich_Tsarevich_Of_Russia.jpg

 13%|█▎        | 1124/8920 [38:50<1:15:03,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Dyatlov.jpg

 13%|█▎        | 1125/8920 [38:50<1:13:03,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Gorbachev.jpg

 13%|█▎        | 1126/8920 [38:51<1:03:29,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Lenin.jpg

 13%|█▎        | 1127/8920 [38:51<1:06:36,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Zhukov.jpg

 13%|█▎        | 1128/8920 [38:52<1:11:18,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasili_Arkhipov.jpg

 13%|█▎        | 1129/8920 [38:52<1:02:40,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Putina.jpg

 13%|█▎        | 1130/8920 [38:52<54:41,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Lavrov.jpg

 13%|█▎        | 1131/8920 [38:54<1:36:11,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Suvorov.jpg

 13%|█▎        | 1132/8920 [38:54<1:25:21,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Nemtsov.jpg

 13%|█▎        | 1133/8920 [38:55<1:23:13,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Kerensky.jpg

 13%|█▎        | 1134/8920 [38:55<1:08:30,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Putin.jpg

 13%|█▎        | 1135/8920 [38:56<1:11:38,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadezhda_Konstantinovna_Krupskaya.jpg

 13%|█▎        | 1136/8920 [38:57<1:30:01,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Bulganin.jpg

 13%|█▎        | 1137/8920 [38:57<1:13:32,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Kalinin.jpg

 13%|█▎        | 1138/8920 [38:58<1:14:39,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Lvov.jpg

 13%|█▎        | 1139/8920 [38:58<1:04:32,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Andropov.jpg

 13%|█▎        | 1140/8920 [38:58<59:29,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Medvedev_13350.jpg

 13%|█▎        | 1141/8920 [38:59<1:07:18,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Malenkov.jpg

 13%|█▎        | 1142/8920 [39:00<1:06:21,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Bagration.jpg

 13%|█▎        | 1143/8920 [39:00<1:20:53,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julius_Martov.jpg

 13%|█▎        | 1144/8920 [39:01<1:20:13,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Frunze.jpg

 13%|█▎        | 1145/8920 [39:02<1:38:05,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Michael_Nikolaevich_Of_Russia.jpg

 13%|█▎        | 1146/8920 [39:03<1:48:15,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Orlov.jpg

 13%|█▎        | 1147/8920 [39:04<1:55:23,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Stolypin.jpg

 13%|█▎        | 1148/8920 [39:05<1:42:59,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Nicholas_Nikolaevich_Of_Russia.jpg

 13%|█▎        | 1149/8920 [39:05<1:23:05,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Yeltsin.jpg

 13%|█▎        | 1150/8920 [39:08<2:38:25,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Von_Ungern-Sternberg.jpg

 13%|█▎        | 1151/8920 [39:08<2:16:36,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Yazov.jpg

 13%|█▎        | 1152/8920 [39:09<2:15:35,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Kosygin.jpg

 13%|█▎        | 1153/8920 [39:11<2:58:13,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fabian_Gottlieb_Von_Bellingshausen.jpg

 13%|█▎        | 1154/8920 [39:12<2:40:44,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Gromyko.jpg

 13%|█▎        | 1155/8920 [39:13<2:19:58,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Kaspersky.jpg

 13%|█▎        | 1156/8920 [39:14<1:56:42,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Abakumov.jpg

 13%|█▎        | 1157/8920 [39:14<1:48:40,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Andrei_Vladimirovich_Of_Russia.jpg

 13%|█▎        | 1158/8920 [39:15<1:56:03,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Silayev.jpg

 13%|█▎        | 1159/8920 [39:16<1:43:01,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Witte.jpg

 13%|█▎        | 1160/8920 [39:18<2:17:50,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Sobyanin.jpg

 13%|█▎        | 1161/8920 [39:18<2:01:20,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Raskova.jpg

 13%|█▎        | 1162/8920 [39:19<1:51:46,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislav_Surkov.jpg

 13%|█▎        | 1163/8920 [39:19<1:29:22,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyubov_Sobol.jpg

 13%|█▎        | 1164/8920 [39:20<1:30:52,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Konstantin_Pavlovich_Of_Russia.jpg

 13%|█▎        | 1165/8920 [39:21<1:27:27,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Nechayev.jpg

 13%|█▎        | 1166/8920 [39:21<1:21:03,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirsan_Ilyumzhinov.jpg

 13%|█▎        | 1167/8920 [39:22<1:38:21,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Sudoplatov.jpg

 13%|█▎        | 1168/8920 [39:23<1:29:37,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Yudenich.jpg

 13%|█▎        | 1169/8920 [39:23<1:17:38,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Grudinin.jpg

 13%|█▎        | 1170/8920 [39:24<1:24:40,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lavr_Kornilov.jpg

 13%|█▎        | 1171/8920 [39:24<1:18:36,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Sechin.jpg

 13%|█▎        | 1172/8920 [39:25<1:20:31,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Milyukov.jpg

 13%|█▎        | 1173/8920 [39:26<1:22:22,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasili_Iii_Of_Russia.jpg

 13%|█▎        | 1174/8920 [39:26<1:23:24,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Grigoryevich_Orlov.jpg

 13%|█▎        | 1175/8920 [39:27<1:42:02,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Michael_Mikhailovich_Of_Russia.jpg

 13%|█▎        | 1176/8920 [39:28<1:35:32,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Alexandrovich,_Tsesarevich_Of_Russia.jpg

 13%|█▎        | 1177/8920 [39:29<1:24:05,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Govorov.jpg

 13%|█▎        | 1178/8920 [39:30<1:40:44,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Zhirinovsky.jpg

 13%|█▎        | 1179/8920 [39:30<1:31:36,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Rogozin.jpg

 13%|█▎        | 1180/8920 [39:30<1:13:25,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yemelyan_Pugachev.jpg

 13%|█▎        | 1181/8920 [39:31<1:16:13,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyril_Vladimirovich,_Grand_Duke_Of_Russia.jpg

 13%|█▎        | 1182/8920 [39:32<1:13:42,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Sergei_Mikhailovich_Of_Russia.jpg

 13%|█▎        | 1183/8920 [39:33<1:38:48,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Ryzhkov.jpg

 13%|█▎        | 1184/8920 [39:34<1:44:50,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Litvinov.jpg

 13%|█▎        | 1185/8920 [39:34<1:40:53,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sulim_Yamadayev.jpg

 13%|█▎        | 1186/8920 [39:35<1:21:36,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Rykov.jpg

 13%|█▎        | 1187/8920 [39:36<1:41:43,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Feodor_I_Of_Russia.jpg

 13%|█▎        | 1188/8920 [39:37<1:50:49,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Kasyanov.jpg

 13%|█▎        | 1189/8920 [39:38<1:58:41,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imam_Shamil.jpg

 13%|█▎        | 1190/8920 [39:39<2:05:05,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Naryshkin.jpg

 13%|█▎        | 1191/8920 [39:39<1:40:39,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Primakov.jpg

 13%|█▎        | 1192/8920 [39:40<1:19:36,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Kamenev.jpg

 13%|█▎        | 1193/8920 [39:40<1:21:30,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Chernenko.jpg

 13%|█▎        | 1194/8920 [39:41<1:07:43,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vyacheslav_Molotov.jpg

 13%|█▎        | 1195/8920 [39:41<55:50,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Trotsky.jpg

 13%|█▎        | 1196/8920 [39:42<1:35:09,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Alekseyevna_Of_Russia.jpg

 13%|█▎        | 1197/8920 [39:42<1:16:43,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Stalin.jpg

 13%|█▎        | 1198/8920 [39:43<1:18:31,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khertek_Anchimaa-Toka.jpg

 13%|█▎        | 1199/8920 [39:45<1:53:17,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Blyukher.jpg

 13%|█▎        | 1200/8920 [39:45<1:31:39,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leo_Tolstoy.jpg

 13%|█▎        | 1201/8920 [39:46<1:51:30,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Chekhov.jpg

 13%|█▎        | 1202/8920 [39:46<1:29:15,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Dostoevsky.jpg

 13%|█▎        | 1203/8920 [39:47<1:12:15,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Pushkin.jpg

 13%|█▎        | 1204/8920 [39:47<59:55,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Nabokov.jpg

 14%|█▎        | 1205/8920 [39:48<1:04:58,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Isayevich_Solzhenitsyn.jpg

 14%|█▎        | 1206/8920 [39:48<1:11:33,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Pasternak.jpg

 14%|█▎        | 1207/8920 [39:50<1:42:17,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Gorky.jpg

 14%|█▎        | 1208/8920 [39:50<1:44:22,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Bulgakov.jpg

 14%|█▎        | 1209/8920 [39:51<1:48:37,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Mayakovsky.jpg

 14%|█▎        | 1210/8920 [39:52<1:36:22,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Turgenev.jpg

 14%|█▎        | 1211/8920 [39:52<1:27:24,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Akhmatova.jpg

 14%|█▎        | 1212/8920 [39:53<1:35:52,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Lermontov.jpg

 14%|█▎        | 1213/8920 [39:54<1:49:05,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Yesenin.jpg

 14%|█▎        | 1214/8920 [39:55<1:35:50,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Limonov.jpg

 14%|█▎        | 1215/8920 [39:55<1:28:20,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Brodsky.jpg

 14%|█▎        | 1216/8920 [39:56<1:21:17,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Strugatsky.jpg

 14%|█▎        | 1217/8920 [39:56<1:09:18,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Bunin.jpg

 14%|█▎        | 1218/8920 [39:57<59:10,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Glukhovsky.jpg

 14%|█▎        | 1219/8920 [39:57<1:03:53,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Berkman.jpg

 14%|█▎        | 1220/8920 [39:59<1:49:52,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Pelevin.jpg

 14%|█▎        | 1221/8920 [39:59<1:40:32,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Blok.jpg

 14%|█▎        | 1222/8920 [40:01<1:56:40,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Ehrenburg.jpg

 14%|█▎        | 1223/8920 [40:01<1:47:21,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaac_Babel.jpg

 14%|█▎        | 1224/8920 [40:02<1:25:14,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Bukovsky.jpg

 14%|█▎        | 1225/8920 [40:02<1:27:48,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arkady_Strugatsky.jpg

 14%|█▎        | 1226/8920 [40:03<1:26:49,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Leskov.jpg

 14%|█▍        | 1227/8920 [40:04<1:22:45,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksey_Konstantinovich_Tolstoy.jpg

 14%|█▍        | 1228/8920 [40:04<1:06:17,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Herzen.jpg

 14%|█▍        | 1229/8920 [40:04<1:13:23,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyubov_Dostoevskaya.jpg

 14%|█▍        | 1230/8920 [40:06<1:38:41,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varlam_Shalamov.jpg

 14%|█▍        | 1231/8920 [40:07<1:44:34,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Goncharov.jpg

 14%|█▍        | 1232/8920 [40:07<1:44:44,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maya_Deren.jpg

 14%|█▍        | 1233/8920 [40:08<1:52:31,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Tolstaya.jpg

 14%|█▍        | 1234/8920 [40:09<1:52:18,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Constance_Garnett.jpg

 14%|█▍        | 1235/8920 [40:11<2:13:42,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Dovlatov.jpg

 14%|█▍        | 1236/8920 [40:12<2:12:43,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Pushkina.jpg

 14%|█▍        | 1237/8920 [40:12<1:56:33,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Osip_Mandelstam.jpg

 14%|█▍        | 1238/8920 [40:13<1:29:57,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Shklovsky.jpg

 14%|█▍        | 1239/8920 [40:13<1:28:57,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Yevtushenko.jpg

 14%|█▍        | 1240/8920 [40:14<1:43:58,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helena_Roerich.jpg

 14%|█▍        | 1241/8920 [40:15<1:46:48,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Akunin.jpg

 14%|█▍        | 1242/8920 [40:16<1:54:01,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Tsvetaeva.jpg

 14%|█▍        | 1243/8920 [40:17<1:53:19,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grand_Duke_Constantine_Constantinovich_Of_Russia.jpg

 14%|█▍        | 1244/8920 [40:18<1:42:51,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Nekrasov.jpg

 14%|█▍        | 1245/8920 [40:18<1:22:35,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ostrovsky.jpg

 14%|█▍        | 1246/8920 [40:20<2:04:52,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Bashlachev.jpg

 14%|█▍        | 1247/8920 [40:20<1:47:40,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgenia_Ginzburg.jpg

 14%|█▍        | 1248/8920 [40:21<1:56:50,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Grossman.jpg

 14%|█▍        | 1249/8920 [40:22<2:01:02,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Sholokhov.jpg

 14%|█▍        | 1250/8920 [40:24<2:13:58,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Krylov.jpg

 14%|█▍        | 1251/8920 [40:25<2:10:51,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Dostoevskaya.jpg

 14%|█▍        | 1252/8920 [40:25<1:55:01,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Dimitri_Romanov.jpg

 14%|█▍        | 1253/8920 [40:26<1:42:22,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Suvorov.jpg

 14%|█▍        | 1254/8920 [40:26<1:30:56,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leo_Tolstoy_Bibliography.jpg

 14%|█▍        | 1255/8920 [40:27<1:30:03,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bodrov.jpg

 14%|█▍        | 1256/8920 [40:28<1:25:54,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Tyutchev.jpg

 14%|█▍        | 1257/8920 [40:28<1:31:35,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Zhukovsky.jpg

 14%|█▍        | 1258/8920 [40:30<1:45:15,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Saltykov-Shchedrin.jpg

 14%|█▍        | 1259/8920 [40:30<1:48:06,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Ustinova.jpg

 14%|█▍        | 1260/8920 [40:32<2:11:28,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Larina.jpg

 14%|█▍        | 1261/8920 [40:33<2:01:23,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Lukyanenko.jpg

 14%|█▍        | 1262/8920 [40:33<1:50:25,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arseny_Tarkovsky.jpg

 14%|█▍        | 1263/8920 [40:34<1:56:29,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vera_Zasulich.jpg

 14%|█▍        | 1264/8920 [40:35<1:46:42,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandr_Griboyedov.jpg

 14%|█▍        | 1265/8920 [40:36<1:38:38,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Merezhkovsky.jpg

 14%|█▍        | 1266/8920 [40:36<1:26:44,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Platonov.jpg

 14%|█▍        | 1267/8920 [40:37<1:39:45,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Kharms.jpg

 14%|█▍        | 1268/8920 [40:38<1:50:49,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Velimir_Khlebnikov.jpg

 14%|█▍        | 1269/8920 [40:39<2:00:44,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Gogol.jpg

 14%|█▍        | 1270/8920 [40:40<1:50:45,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Gumilyov.jpg

 14%|█▍        | 1271/8920 [40:40<1:29:31,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Chernyshevsky.jpg

 14%|█▍        | 1272/8920 [40:42<1:50:33,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lou_Andreas-Salomé.jpg

 14%|█▍        | 1273/8920 [40:42<1:39:03,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Durant.jpg

 14%|█▍        | 1274/8920 [40:43<1:50:03,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eldar_Ryazanov.jpg

 14%|█▍        | 1275/8920 [40:44<1:29:07,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Kropotkin.jpg

 14%|█▍        | 1276/8920 [40:44<1:21:09,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helena_Blavatsky.jpg

 14%|█▍        | 1277/8920 [40:44<1:11:55,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Vygotsky.jpg

 14%|█▍        | 1278/8920 [40:45<58:56,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Gurdjieff.jpg

 14%|█▍        | 1279/8920 [40:46<1:14:54,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Bakhtin.jpg

 14%|█▍        | 1280/8920 [40:46<1:15:54,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Bakunin.jpg

 14%|█▍        | 1281/8920 [40:46<1:02:03,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pitirim_Sorokin.jpg

 14%|█▍        | 1282/8920 [40:47<1:21:31,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Élie_Metchnikoff.jpg

 14%|█▍        | 1283/8920 [40:48<1:21:14,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Blok.jpg

 14%|█▍        | 1284/8920 [40:49<1:35:18,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Berdyaev.jpg

 14%|█▍        | 1285/8920 [40:50<1:32:33,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Solovyov.jpg

 14%|█▍        | 1286/8920 [40:50<1:25:44,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Shestov.jpg

 14%|█▍        | 1287/8920 [40:51<1:44:46,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Luria.jpg

 14%|█▍        | 1288/8920 [40:52<1:26:50,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Herzen.jpg

 14%|█▍        | 1289/8920 [40:54<2:21:11,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/P._D._Ouspensky.jpg

 14%|█▍        | 1290/8920 [40:55<2:05:15,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kantorovich.jpg

 14%|█▍        | 1291/8920 [40:55<1:51:55,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Jakobson.jpg

 14%|█▍        | 1292/8920 [40:56<1:39:58,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Oparin.jpg

 14%|█▍        | 1293/8920 [40:57<1:41:08,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wolf_Messing.jpg

 15%|█▍        | 1294/8920 [40:58<1:45:55,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Propp.jpg

 15%|█▍        | 1295/8920 [40:59<1:55:04,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Fyodorovich_Fyodorov.jpg

 15%|█▍        | 1296/8920 [40:59<1:38:15,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Dent_Cantacuzene_Spiransky-Grant.jpg

 15%|█▍        | 1297/8920 [41:00<1:32:03,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bluma_Zeigarnik.jpg

 15%|█▍        | 1298/8920 [41:00<1:15:05,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Alexeyeva.jpg

 15%|█▍        | 1299/8920 [41:00<1:10:10,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wolfgang_Köhler.jpg

 15%|█▍        | 1300/8920 [41:01<1:11:39,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Przhevalsky.jpg

 15%|█▍        | 1301/8920 [41:02<1:13:38,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Bekhterev.jpg

 15%|█▍        | 1302/8920 [41:02<1:10:57,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexey_Miller.jpg

 15%|█▍        | 1303/8920 [41:03<1:15:11,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wassily_Leontief.jpg

 15%|█▍        | 1304/8920 [41:03<1:13:50,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksei_Losev.jpg

 15%|█▍        | 1305/8920 [41:04<1:15:04,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvira_Nabiullina.jpg

 15%|█▍        | 1306/8920 [41:04<1:12:44,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Chernyshevsky.jpg

 15%|█▍        | 1307/8920 [41:05<1:04:33,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Durant.jpg

 15%|█▍        | 1308/8920 [41:05<54:44,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Navalnaya.jpg

 15%|█▍        | 1309/8920 [41:06<1:06:07,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Tyutchev.jpg

 15%|█▍        | 1310/8920 [41:07<1:22:13,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Smirnov.jpg

 15%|█▍        | 1311/8920 [41:07<1:20:54,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Dokuchaev.jpg

 15%|█▍        | 1312/8920 [41:08<1:31:58,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Dugin.jpg

 15%|█▍        | 1313/8920 [41:09<1:29:24,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Kondratiev.jpg

 15%|█▍        | 1314/8920 [41:09<1:12:46,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Platonov.jpg

 15%|█▍        | 1315/8920 [41:10<1:15:55,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bulgakov.jpg

 15%|█▍        | 1316/8920 [41:11<1:39:33,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Nikitich_Mitrokhin.jpg

 15%|█▍        | 1317/8920 [41:11<1:20:41,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yegor_Gaidar.jpg

 15%|█▍        | 1318/8920 [41:12<1:16:46,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Aven.jpg

 15%|█▍        | 1319/8920 [41:12<1:03:13,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helena_Roerich.jpg

 15%|█▍        | 1320/8920 [41:13<1:25:29,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Rostovtzeff.jpg

 15%|█▍        | 1321/8920 [41:14<1:34:43,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Dubnow.jpg

 15%|█▍        | 1322/8920 [41:15<1:25:42,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Karamzin.jpg

 15%|█▍        | 1323/8920 [41:16<1:38:56,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Zinoviev.jpg

 15%|█▍        | 1324/8920 [41:17<2:03:37,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Kudrin.jpg

 15%|█▍        | 1325/8920 [41:18<2:05:30,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Trubetzkoy.jpg

 15%|█▍        | 1326/8920 [41:19<2:06:44,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Leontiev.jpg

 15%|█▍        | 1327/8920 [41:20<1:48:10,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Ansoff.jpg

 15%|█▍        | 1328/8920 [41:20<1:26:37,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Baratynsky.jpg

 15%|█▍        | 1329/8920 [41:21<1:24:35,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Volkogonov.jpg

 15%|█▍        | 1330/8920 [41:21<1:17:28,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Chaadayev.jpg

 15%|█▍        | 1331/8920 [41:22<1:30:20,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgi_Plekhanov.jpg

 15%|█▍        | 1332/8920 [41:23<1:21:00,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Mikhaylovich_Gerasimov.jpg

 15%|█▍        | 1333/8920 [41:23<1:20:14,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksey_Khomyakov.jpg

 15%|█▍        | 1334/8920 [41:24<1:32:36,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Florensky.jpg

 15%|█▍        | 1335/8920 [41:25<1:43:39,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Yakovlevich_Danilevsky.jpg

 15%|█▍        | 1336/8920 [41:26<1:34:27,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Amalrik.jpg

 15%|█▍        | 1337/8920 [41:26<1:32:25,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Rozanov.jpg

 15%|█▌        | 1338/8920 [41:29<2:28:27,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Klyuchevsky.jpg

 15%|█▌        | 1339/8920 [41:30<2:22:47,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Koyré.jpg

 15%|█▌        | 1340/8920 [41:30<1:51:23,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgenia_Albats.jpg

 15%|█▌        | 1341/8920 [41:31<1:42:58,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Tatishchev.jpg

 15%|█▌        | 1342/8920 [41:31<1:38:02,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Knorozov.jpg

 15%|█▌        | 1343/8920 [41:32<1:46:56,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Likhachov.jpg

 15%|█▌        | 1344/8920 [41:33<1:23:45,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vyacheslav_Ivanov.jpg

 15%|█▌        | 1345/8920 [41:34<1:36:18,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Dubyanskiy.jpg

 15%|█▌        | 1346/8920 [41:34<1:42:18,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Onufriyevich_Lossky.jpg

 15%|█▌        | 1347/8920 [41:35<1:34:46,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henri_Troyat.jpg

 15%|█▌        | 1348/8920 [41:37<2:12:44,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Miklouho-Maclay.jpg

 15%|█▌        | 1349/8920 [41:37<1:57:39,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antiochus_Kantemir.jpg

 15%|█▌        | 1350/8920 [41:38<1:33:44,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Ilyich_Tchaikovsky.jpg

 15%|█▌        | 1351/8920 [41:39<1:42:46,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Rachmaninoff.jpg

 15%|█▌        | 1352/8920 [41:39<1:20:25,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Shostakovich.jpg

 15%|█▌        | 1353/8920 [41:39<1:06:25,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Stravinsky.jpg

 15%|█▌        | 1354/8920 [41:40<1:10:49,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Rimsky.jpg

 15%|█▌        | 1355/8920 [41:41<1:35:36,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zedd.jpg

 15%|█▌        | 1356/8920 [41:43<2:03:07,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Modest_Mussorgsky.jpg

 15%|█▌        | 1357/8920 [41:43<1:47:24,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Borodin.jpg

 15%|█▌        | 1358/8920 [41:44<2:03:40,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mstislav_Rostropovich.jpg

 15%|█▌        | 1359/8920 [41:45<1:51:31,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgeny_Kissin.jpg

 15%|█▌        | 1360/8920 [41:46<1:37:28,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jascha_Heifetz.jpg

 15%|█▌        | 1361/8920 [41:46<1:25:17,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sviatoslav_Richter.jpg

 15%|█▌        | 1362/8920 [41:47<1:17:07,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Kraviz.jpg

 15%|█▌        | 1363/8920 [41:49<2:32:43,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Glinka.jpg

 15%|█▌        | 1364/8920 [41:50<2:29:43,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Schnittke.jpg

 15%|█▌        | 1365/8920 [41:51<2:20:52,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Rubinstein.jpg

 15%|█▌        | 1366/8920 [41:52<1:56:37,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Ashkenazy.jpg

 15%|█▌        | 1367/8920 [41:52<1:31:26,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Trifonov.jpg

 15%|█▌        | 1368/8920 [41:54<2:23:34,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Glazunov.jpg

 15%|█▌        | 1369/8920 [41:55<2:22:31,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mily_Balakirev.jpg

 15%|█▌        | 1370/8920 [41:57<2:42:15,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexey_Vorobyov.jpg

 15%|█▌        | 1371/8920 [41:58<2:42:35,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cesar_Cui.jpg

 15%|█▌        | 1372/8920 [42:00<3:16:56,  1.57s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Gradsky.jpg

 15%|█▌        | 1373/8920 [42:01<2:43:33,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Stepanov.jpg

 15%|█▌        | 1374/8920 [42:02<2:31:56,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirill_Petrenko.jpg

 15%|█▌        | 1375/8920 [42:03<2:10:37,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofia_Gubaidulina.jpg

 15%|█▌        | 1376/8920 [42:03<1:51:15,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktoria_Mullova.jpg

 15%|█▌        | 1377/8920 [42:04<1:38:40,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Petrenko.jpg

 15%|█▌        | 1378/8920 [42:04<1:28:30,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Vengerov.jpg

 15%|█▌        | 1379/8920 [42:05<1:26:55,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denis_Matsuev.jpg

 15%|█▌        | 1380/8920 [42:06<1:37:40,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Sokolov.jpg

 15%|█▌        | 1381/8920 [42:06<1:19:52,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emil_Gilels.jpg

 15%|█▌        | 1382/8920 [42:07<1:29:11,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Yudina.jpg

 16%|█▌        | 1383/8920 [42:09<2:28:59,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Bashlachev.jpg

 16%|█▌        | 1384/8920 [42:10<2:18:39,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonya_Belousova.jpg

 16%|█▌        | 1385/8920 [42:11<2:00:07,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reinhold_Glière.jpg

 16%|█▌        | 1386/8920 [42:11<1:45:26,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Grebenshchikov.jpg

 16%|█▌        | 1387/8920 [42:13<2:05:43,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Scheps.jpg

 16%|█▌        | 1388/8920 [42:13<1:49:22,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Rubinstein.jpg

 16%|█▌        | 1389/8920 [42:14<1:54:44,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Scriabin.jpg

 16%|█▌        | 1390/8920 [42:15<1:43:37,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadezhda_Tolokonnikova.jpg

 16%|█▌        | 1391/8920 [42:16<1:51:09,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Kalinnikov.jpg

 16%|█▌        | 1392/8920 [42:17<1:46:34,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glukoza.jpg

 16%|█▌        | 1393/8920 [42:18<2:01:10,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valery_Gergiev.jpg

 16%|█▌        | 1394/8920 [42:19<1:43:48,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Vasilyevich_Alexandrov.jpg

 16%|█▌        | 1395/8920 [42:19<1:35:50,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Pletnev.jpg

 16%|█▌        | 1396/8920 [42:20<1:20:55,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Arkhipova.jpg

 16%|█▌        | 1397/8920 [42:21<1:40:34,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Nikolayeva.jpg

 16%|█▌        | 1398/8920 [42:21<1:22:51,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Mravinsky.jpg

 16%|█▌        | 1399/8920 [42:22<1:22:07,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Sviridov.jpg

 16%|█▌        | 1400/8920 [42:22<1:24:19,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valery_Khalilov.jpg

 16%|█▌        | 1401/8920 [42:24<1:49:05,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Jurowski.jpg

 16%|█▌        | 1402/8920 [42:24<1:39:23,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galina_Ustvolskaya.jpg

 16%|█▌        | 1403/8920 [42:25<1:18:23,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Kasparyan.jpg

 16%|█▌        | 1404/8920 [42:25<1:15:02,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Serge_Koussevitzky.jpg

 16%|█▌        | 1405/8920 [42:27<1:54:04,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Medtner.jpg

 16%|█▌        | 1406/8920 [42:27<1:37:43,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Siloti.jpg

 16%|█▌        | 1407/8920 [42:28<1:32:45,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Markevitch.jpg

 16%|█▌        | 1408/8920 [42:28<1:16:17,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bulat_Okudzhava.jpg

 16%|█▌        | 1409/8920 [42:29<1:15:17,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Gazmanov.jpg

 16%|█▌        | 1410/8920 [42:30<1:32:29,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Lyadov.jpg

 16%|█▌        | 1411/8920 [42:31<1:36:33,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Taneyev.jpg

 16%|█▌        | 1412/8920 [42:31<1:29:34,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Nikolayev.jpg

 16%|█▌        | 1413/8920 [42:33<2:21:17,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hans_Pfitzner.jpg

 16%|█▌        | 1414/8920 [42:35<2:34:53,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Martynov.jpg

 16%|█▌        | 1415/8920 [42:35<2:09:19,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Roldugin.jpg

 16%|█▌        | 1416/8920 [42:36<1:50:36,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Arensky.jpg

 16%|█▌        | 1417/8920 [42:37<1:39:28,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Lyapunov.jpg

 16%|█▌        | 1418/8920 [42:37<1:29:51,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Tcherepnin.jpg

 16%|█▌        | 1419/8920 [42:38<1:29:02,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vernon_Duke.jpg

 16%|█▌        | 1420/8920 [42:39<1:40:25,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Artemyev.jpg

 16%|█▌        | 1421/8920 [42:39<1:18:45,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Svetlanov.jpg

 16%|█▌        | 1422/8920 [42:40<1:23:12,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Karpova.jpg

 16%|█▌        | 1423/8920 [42:41<1:36:51,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Dargomyzhsky.jpg

 16%|█▌        | 1425/8920 [42:42<1:10:54,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Dyachenko.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khabib_Nurmagomedov.jpg

 16%|█▌        | 1426/8920 [42:42<1:04:35,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Sharapova.jpg

 16%|█▌        | 1427/8920 [42:43<1:07:41,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kamila_Valieva.jpg

 16%|█▌        | 1428/8920 [42:43<59:12,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Kasparov.jpg

 16%|█▌        | 1429/8920 [42:44<1:05:20,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Shcherbakova.jpg

 16%|█▌        | 1430/8920 [42:44<1:09:13,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Grinkov.jpg

 16%|█▌        | 1431/8920 [42:45<1:05:05,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alena_Kostornaia.jpg

 16%|█▌        | 1432/8920 [42:45<1:01:12,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Yashin.jpg

 16%|█▌        | 1433/8920 [42:45<55:27,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Spassky.jpg

 16%|█▌        | 1434/8920 [42:46<1:02:22,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Alekhine.jpg

 16%|█▌        | 1435/8920 [42:46<52:08,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Lipnitskaya.jpg

 16%|█▌        | 1436/8920 [42:47<57:25,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nataliya_Kuznetsova.jpg

 16%|█▌        | 1437/8920 [42:48<1:15:54,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Trusova.jpg

 16%|█▌        | 1438/8920 [42:50<2:09:49,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgeni_Malkin.jpg

 16%|█▌        | 1439/8920 [42:50<1:41:11,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ovechkin.jpg

 16%|█▌        | 1440/8920 [42:51<1:38:27,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tigran_Petrosian.jpg

 16%|█▌        | 1441/8920 [42:51<1:22:12,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Kabaeva.jpg

 16%|█▌        | 1442/8920 [42:53<1:59:12,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Makarova.jpg

 16%|█▌        | 1443/8920 [42:53<1:36:26,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Nepomniachtchi.jpg

 16%|█▌        | 1444/8920 [42:54<1:30:46,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Kirilenko.jpg

 16%|█▌        | 1445/8920 [42:54<1:13:48,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Kramnik.jpg

 16%|█▌        | 1446/8920 [42:55<1:26:12,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vadim_Nemkov.jpg

 16%|█▌        | 1447/8920 [42:56<1:24:25,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Vesnina.jpg

 16%|█▌        | 1448/8920 [42:56<1:18:23,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daria_Kasatkina.jpg

 16%|█▌        | 1449/8920 [42:56<1:03:30,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Karpov.jpg

 16%|█▋        | 1450/8920 [42:57<1:04:54,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Fedorov.jpg

 16%|█▋        | 1451/8920 [42:58<1:36:27,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonina_Krivoshapka.jpg

 16%|█▋        | 1452/8920 [43:00<2:01:08,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Kournikova.jpg

 16%|█▋        | 1453/8920 [43:00<1:43:36,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Kharitonov.jpg

 16%|█▋        | 1454/8920 [43:01<1:53:01,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Pogrebnyak.jpg

 16%|█▋        | 1455/8920 [43:03<2:24:00,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilia_Kulik.jpg

 16%|█▋        | 1456/8920 [43:04<2:28:34,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darya_Klishina.jpg

 16%|█▋        | 1457/8920 [43:06<2:26:10,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktoria_Komova.jpg

 16%|█▋        | 1458/8920 [43:06<1:53:56,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Gordeeva.jpg

 16%|█▋        | 1459/8920 [43:06<1:44:03,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Žydrūnas_Ilgauskas.jpg

 16%|█▋        | 1460/8920 [43:07<1:34:01,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Mamun.jpg

 16%|█▋        | 1461/8920 [43:08<1:24:44,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelina_Melnikova.jpg

 16%|█▋        | 1462/8920 [43:08<1:11:08,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Arshavin.jpg

 16%|█▋        | 1463/8920 [43:08<1:08:19,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rustam_Khabilov.jpg

 16%|█▋        | 1464/8920 [43:09<1:12:53,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirill_Kaprizov.jpg

 16%|█▋        | 1465/8920 [43:10<1:10:00,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Sotskova.jpg

 16%|█▋        | 1466/8920 [43:10<59:47,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Alekseyev.jpg

 16%|█▋        | 1467/8920 [43:11<1:29:19,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Grischuk.jpg

 16%|█▋        | 1468/8920 [43:12<1:24:28,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Kirilenko.jpg

 16%|█▋        | 1469/8920 [43:14<2:17:17,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Sinitsina.jpg

 16%|█▋        | 1470/8920 [43:15<2:12:51,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Potapova.jpg

 16%|█▋        | 1471/8920 [43:16<2:22:02,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Radulov.jpg

 17%|█▋        | 1472/8920 [43:17<1:57:18,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dina_Averina.jpg

 17%|█▋        | 1473/8920 [43:17<1:46:15,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Semyon_Varlamov.jpg

 17%|█▋        | 1474/8920 [43:18<1:42:54,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Smyslov.jpg

 17%|█▋        | 1475/8920 [43:18<1:23:20,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Kosteniuk.jpg

 17%|█▋        | 1476/8920 [43:19<1:34:41,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arina_Averina.jpg

 17%|█▋        | 1477/8920 [43:20<1:29:00,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Ilinykh.jpg

 17%|█▋        | 1478/8920 [43:21<2:01:27,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rinat_Dasayev.jpg

 17%|█▋        | 1479/8920 [43:22<1:33:25,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Ignashevich.jpg

 17%|█▋        | 1480/8920 [43:23<2:01:11,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Kalinskaya.jpg

 17%|█▋        | 1481/8920 [43:24<1:52:01,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Zhirkov.jpg

 17%|█▋        | 1482/8920 [43:25<2:04:08,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Korchnoi.jpg

 17%|█▋        | 1483/8920 [43:26<1:53:31,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dinara_Safina.jpg

 17%|█▋        | 1484/8920 [43:26<1:30:00,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Ponomarenko.jpg

 17%|█▋        | 1485/8920 [43:27<1:29:10,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislav_Tretiak.jpg

 17%|█▋        | 1486/8920 [43:28<1:25:52,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Rudenko.jpg

 17%|█▋        | 1487/8920 [43:28<1:21:40,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Moldavsky.jpg

 17%|█▋        | 1488/8920 [43:29<1:17:40,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Krutov.jpg

 17%|█▋        | 1489/8920 [43:29<1:18:27,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Isinbayeva.jpg

 17%|█▋        | 1490/8920 [43:29<1:02:40,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Popov.jpg

 17%|█▋        | 1491/8920 [43:30<1:07:03,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludmilla_Tourischeva.jpg

 17%|█▋        | 1492/8920 [43:31<1:23:02,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bobrovsky.jpg

 17%|█▋        | 1493/8920 [43:32<1:48:07,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislava_Urazova.jpg

 17%|█▋        | 1494/8920 [43:33<1:38:26,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Askar_Askarov.jpg

 17%|█▋        | 1495/8920 [43:34<1:31:47,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magomed_Ismailov.jpg

 17%|█▋        | 1496/8920 [43:34<1:25:00,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandra_Soldatova.jpg

 17%|█▋        | 1497/8920 [43:35<1:39:32,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Aliev.jpg

 17%|█▋        | 1498/8920 [43:36<1:20:02,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Nemov.jpg

 17%|█▋        | 1499/8920 [43:36<1:14:26,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanislav_Cherchesov.jpg

 17%|█▋        | 1500/8920 [43:36<1:03:28,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pitirim_Sorokin.jpg

 17%|█▋        | 1501/8920 [43:37<53:17,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Bukovsky.jpg

 17%|█▋        | 1502/8920 [43:38<1:39:37,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Alexeyeva.jpg

 17%|█▋        | 1503/8920 [43:40<2:01:42,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petr_Pavlensky.jpg

 17%|█▋        | 1504/8920 [43:41<2:20:19,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stenka_Razin.jpg

 17%|█▋        | 1505/8920 [43:43<2:29:20,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Estemirova.jpg

 17%|█▋        | 1506/8920 [43:43<1:53:47,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Parvus.jpg

 17%|█▋        | 1507/8920 [43:43<1:29:26,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Bonner.jpg

 17%|█▋        | 1508/8920 [43:44<1:25:23,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeriya_Novodvorskaya.jpg

 17%|█▋        | 1509/8920 [43:44<1:18:43,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Gorbanevskaya.jpg

 17%|█▋        | 1510/8920 [43:46<1:51:55,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Mitroshina.jpg

 17%|█▋        | 1511/8920 [43:47<2:13:25,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Martsinkevich.jpg

 17%|█▋        | 1512/8920 [43:48<1:56:06,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zara.jpg

 17%|█▋        | 1513/8920 [43:49<1:48:23,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ginzburg.jpg

 17%|█▋        | 1514/8920 [43:49<1:49:23,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Khakamada.jpg

 17%|█▋        | 1515/8920 [43:51<2:15:23,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fanny_Lewald.jpg

 17%|█▋        | 1516/8920 [43:51<1:44:02,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Lvovich_Kazembek.jpg

 17%|█▋        | 1517/8920 [43:52<1:22:19,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Baryshnikov.jpg

 17%|█▋        | 1518/8920 [43:52<1:07:44,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Pavlova.jpg

 17%|█▋        | 1519/8920 [43:52<57:38,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Nureyev.jpg

 17%|█▋        | 1520/8920 [43:53<1:17:00,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artem_Chigvintsev.jpg

 17%|█▋        | 1521/8920 [43:53<1:04:59,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galina_Ulanova.jpg

 17%|█▋        | 1522/8920 [43:54<55:19,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Khokhlova.jpg

 17%|█▋        | 1523/8920 [43:54<1:05:06,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Rihanoff.jpg

 17%|█▋        | 1524/8920 [43:55<1:06:22,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Zakharova.jpg

 17%|█▋        | 1525/8920 [43:56<1:26:18,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mathilde_Kschessinska.jpg

 17%|█▋        | 1526/8920 [43:57<1:36:15,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pati_Behrs.jpg

 17%|█▋        | 1527/8920 [43:57<1:18:53,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maya_Plisetskaya.jpg

 17%|█▋        | 1528/8920 [43:58<1:17:47,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pasha_Kovalev_14628.jpg

 17%|█▋        | 1529/8920 [43:58<1:02:46,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Zagoruychenko.jpg

 17%|█▋        | 1530/8920 [43:59<1:05:56,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lydia_Lopokova.jpg

 17%|█▋        | 1531/8920 [43:59<57:34,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Khoreva.jpg

 17%|█▋        | 1532/8920 [43:59<49:27,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Makarova.jpg

 17%|█▋        | 1533/8920 [44:01<1:23:07,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Ilinykh.jpg

 17%|█▋        | 1534/8920 [44:01<1:19:52,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamara_Toumanova.jpg

 17%|█▋        | 1535/8920 [44:02<1:06:52,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Davis.jpg

 17%|█▋        | 1536/8920 [44:02<56:41,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michel_Fokine.jpg

 17%|█▋        | 1537/8920 [44:02<1:04:02,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Sinitsina.jpg

 17%|█▋        | 1538/8920 [44:03<1:03:48,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Léonide_Massine.jpg

 17%|█▋        | 1539/8920 [44:04<1:24:14,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Vlasova.jpg

 17%|█▋        | 1540/8920 [44:05<1:48:04,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Ponomarenko.jpg

 17%|█▋        | 1541/8920 [44:07<2:11:34,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Bukin.jpg

 17%|█▋        | 1542/8920 [44:08<2:12:09,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Volochkova.jpg

 17%|█▋        | 1543/8920 [44:08<1:50:23,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Anissina.jpg

 17%|█▋        | 1544/8920 [44:11<2:41:46,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ulyana_Lopatkina.jpg

 17%|█▋        | 1545/8920 [44:11<2:02:44,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Osipova.jpg

 17%|█▋        | 1546/8920 [44:12<1:56:59,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vaslav_Nijinsky.jpg

 17%|█▋        | 1547/8920 [44:12<1:44:04,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Katsalapov.jpg

 17%|█▋        | 1548/8920 [44:14<2:09:00,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Navka.jpg

 17%|█▋        | 1549/8920 [44:15<1:54:49,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ida_Rubinstein.jpg

 17%|█▋        | 1550/8920 [44:15<1:42:57,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Baronova.jpg

 17%|█▋        | 1551/8920 [44:16<1:34:40,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agrippina_Vaganova.jpg

 17%|█▋        | 1552/8920 [44:16<1:19:08,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Vishneva.jpg

 17%|█▋        | 1553/8920 [44:17<1:43:03,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Godunov.jpg

 17%|█▋        | 1554/8920 [44:18<1:30:53,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katya_Jones.jpg

 17%|█▋        | 1555/8920 [44:20<2:16:59,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofya_Skya.jpg

 17%|█▋        | 1556/8920 [44:21<2:04:19,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Danilova.jpg

 17%|█▋        | 1557/8920 [44:22<2:04:42,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Somova.jpg

 17%|█▋        | 1558/8920 [44:22<1:49:59,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Polunin.jpg

 17%|█▋        | 1559/8920 [44:23<1:52:31,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Vasiliev.jpg

 17%|█▋        | 1560/8920 [44:24<1:55:18,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Pushkin.jpg

 18%|█▊        | 1561/8920 [44:25<1:59:30,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Simkin.jpg

 18%|█▊        | 1562/8920 [44:26<1:56:03,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Maximova.jpg

 18%|█▊        | 1563/8920 [44:27<2:00:08,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Zhulin.jpg

 18%|█▊        | 1564/8920 [44:28<2:00:11,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kseniya_Ryabinkina.jpg

 18%|█▊        | 1565/8920 [44:29<2:00:24,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Ivanov.jpg

 18%|█▊        | 1566/8920 [44:30<1:58:19,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oksana_Grishuk.jpg

 18%|█▊        | 1567/8920 [44:32<2:43:02,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgenia_Obraztsova.jpg

 18%|█▊        | 1568/8920 [44:33<2:24:22,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Ratmansky.jpg

 18%|█▊        | 1569/8920 [44:34<2:01:38,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamara_Karsavina.jpg

 18%|█▊        | 1570/8920 [44:34<1:43:31,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Balanchine.jpg

 18%|█▊        | 1571/8920 [44:35<1:33:38,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamara_Geva.jpg

 18%|█▊        | 1572/8920 [44:36<1:31:53,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Moiseyev.jpg

 18%|█▊        | 1573/8920 [44:37<1:37:17,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Dudinskaya.jpg

 18%|█▊        | 1574/8920 [44:38<2:08:58,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Stepanova.jpg

 18%|█▊        | 1575/8920 [44:39<1:53:02,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Preobrajenska.jpg

 18%|█▊        | 1576/8920 [44:39<1:39:28,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Lepeshinskaya.jpg

 18%|█▊        | 1577/8920 [44:40<1:36:08,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Grinenko.jpg

 18%|█▊        | 1578/8920 [44:41<1:43:08,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fedor_Andreev.jpg

 18%|█▊        | 1579/8920 [44:41<1:22:45,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yury_Grigorovich.jpg

 18%|█▊        | 1580/8920 [44:42<1:32:18,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Vasiliev.jpg

 18%|█▊        | 1581/8920 [44:43<1:48:29,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Bessmertnova.jpg

 18%|█▊        | 1582/8920 [44:44<1:41:32,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Drobiazko.jpg

 18%|█▊        | 1583/8920 [44:45<1:27:02,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Semyonova.jpg

 18%|█▊        | 1584/8920 [44:45<1:22:34,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Kaptsova.jpg

 18%|█▊        | 1585/8920 [44:46<1:17:46,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vadim_Muntagirov.jpg

 18%|█▊        | 1586/8920 [44:46<1:12:35,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sulamith_Messerer.jpg

 18%|█▊        | 1587/8920 [44:47<1:08:23,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizaveta_Khudaiberdieva.jpg

 18%|█▊        | 1588/8920 [44:48<1:24:15,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Lomonosova.jpg

 18%|█▊        | 1589/8920 [44:48<1:21:21,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Morozov.jpg

 18%|█▊        | 1590/8920 [44:49<1:17:34,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Alexeyevich_Gorsky.jpg

 18%|█▊        | 1591/8920 [44:49<1:05:06,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Shchelkanova.jpg

 18%|█▊        | 1592/8920 [44:49<54:55,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Pavlov.jpg

 18%|█▊        | 1593/8920 [44:50<47:52,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Demikhov.jpg

 18%|█▊        | 1594/8920 [44:50<58:18,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Rogozov.jpg

 18%|█▊        | 1595/8920 [44:51<49:36,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Alliluyev.jpg

 18%|█▊        | 1596/8920 [44:52<1:22:09,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabina_Spielrein.jpg

 18%|█▊        | 1597/8920 [44:53<1:21:49,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Bogdanov.jpg

 18%|█▊        | 1598/8920 [44:53<1:06:44,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Luria.jpg

 18%|█▊        | 1599/8920 [44:55<1:50:25,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Bekhterev.jpg

 18%|█▊        | 1600/8920 [44:55<1:43:26,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bluma_Zeigarnik.jpg

 18%|█▊        | 1601/8920 [44:56<1:34:36,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doctor_Mike.jpg

 18%|█▊        | 1602/8920 [44:57<2:03:43,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Yegorov.jpg

 18%|█▊        | 1603/8920 [44:58<1:49:46,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svyatoslav_Fyodorov.jpg

 18%|█▊        | 1604/8920 [44:59<2:01:37,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Pirogov.jpg

 18%|█▊        | 1605/8920 [45:00<1:46:11,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caesar_Korolenko.jpg

 18%|█▊        | 1606/8920 [45:00<1:23:08,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeniy_Chazov.jpg

 18%|█▊        | 1607/8920 [45:01<1:31:57,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Rosenbaum.jpg

 18%|█▊        | 1608/8920 [45:01<1:14:39,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Mendeleev.jpg

 18%|█▊        | 1609/8920 [45:02<1:02:28,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonhard_Euler.jpg

 18%|█▊        | 1610/8920 [45:02<53:16,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigori_Perelman.jpg

 18%|█▊        | 1611/8920 [45:03<1:09:17,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georg_Cantor.jpg

 18%|█▊        | 1612/8920 [45:03<1:09:44,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Landau.jpg

 18%|█▊        | 1613/8920 [45:04<1:14:46,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Sakharov.jpg

 18%|█▊        | 1614/8920 [45:05<1:12:31,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Lomonosov.jpg

 18%|█▊        | 1615/8920 [45:05<1:01:15,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Tsiolkovsky.jpg

 18%|█▊        | 1616/8920 [45:05<53:03,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Gamow.jpg

 18%|█▊        | 1617/8920 [45:05<46:40,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Mikhailovich_Prokudin-Gorskii.jpg

 18%|█▊        | 1618/8920 [45:06<53:48,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoli_Bugorski.jpg

 18%|█▊        | 1619/8920 [45:08<1:36:33,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Stepanovich_Popov.jpg

 18%|█▊        | 1620/8920 [45:08<1:17:31,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Prigogine.jpg

 18%|█▊        | 1621/8920 [45:09<1:17:58,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexey_Pazhitnov.jpg

 18%|█▊        | 1622/8920 [45:09<1:05:41,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Lobachevsky.jpg

 18%|█▊        | 1623/8920 [45:09<55:52,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Élie_Metchnikoff.jpg

 18%|█▊        | 1624/8920 [45:10<1:00:02,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Kurchatov.jpg

 18%|█▊        | 1625/8920 [45:10<52:26,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitalik_Buterin.jpg

 18%|█▊        | 1626/8920 [45:11<1:17:41,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theodosius_Dobzhansky.jpg

 18%|█▊        | 1627/8920 [45:11<1:05:18,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Kapitsa.jpg

 18%|█▊        | 1628/8920 [45:12<1:02:59,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Friedmann.jpg

 18%|█▊        | 1629/8920 [45:12<52:07,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhores_Ivanovich_Alferov.jpg

 18%|█▊        | 1630/8920 [45:13<56:20,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Markov.jpg

 18%|█▊        | 1631/8920 [45:14<1:21:22,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Vernadsky.jpg

 18%|█▊        | 1632/8920 [45:15<1:23:58,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Lyapunov.jpg

 18%|█▊        | 1633/8920 [45:17<2:13:20,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Ivanovsky.jpg

 18%|█▊        | 1634/8920 [45:17<1:43:41,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kantorovich.jpg

 18%|█▊        | 1635/8920 [45:18<1:39:48,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trofim_Lysenko.jpg

 18%|█▊        | 1636/8920 [45:19<1:57:05,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Kolmogorov_8769.jpg

 18%|█▊        | 1637/8920 [45:19<1:43:32,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Vavilov.jpg

 18%|█▊        | 1638/8920 [45:20<1:20:40,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Oparin.jpg

 18%|█▊        | 1639/8920 [45:20<1:19:55,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Leonidovich_Gromov.jpg

 18%|█▊        | 1640/8920 [45:21<1:06:46,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Tamm.jpg

 18%|█▊        | 1641/8920 [45:22<1:32:06,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Cherenkov.jpg

 18%|█▊        | 1642/8920 [45:23<1:37:36,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pafnuty_Chebyshev.jpg

 18%|█▊        | 1643/8920 [45:24<1:45:11,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Voevodsky.jpg

 18%|█▊        | 1644/8920 [45:24<1:32:39,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Oganessian.jpg

 18%|█▊        | 1645/8920 [45:25<1:42:06,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Novoselov.jpg

 18%|█▊        | 1646/8920 [45:26<1:35:35,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitaly_Ginzburg.jpg

 18%|█▊        | 1647/8920 [45:27<1:47:58,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Israel_Gelfand.jpg

 18%|█▊        | 1648/8920 [45:28<1:48:47,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Goldbach.jpg

 18%|█▊        | 1649/8920 [45:29<1:42:25,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Kontsevich.jpg

 18%|█▊        | 1650/8920 [45:29<1:35:54,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Khachiyan.jpg

 19%|█▊        | 1651/8920 [45:30<1:16:30,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Winogradsky.jpg

 19%|█▊        | 1652/8920 [45:30<1:10:56,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johann_Euler.jpg

 19%|█▊        | 1653/8920 [45:30<58:39,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Dokuchaev.jpg

 19%|█▊        | 1654/8920 [45:32<1:19:42,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Frenkel.jpg

 19%|█▊        | 1655/8920 [45:32<1:08:36,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Basov.jpg

 19%|█▊        | 1656/8920 [45:33<1:27:21,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Stepanov.jpg

 19%|█▊        | 1657/8920 [45:33<1:10:27,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanislav_Smirnov.jpg

 19%|█▊        | 1658/8920 [45:34<1:06:20,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Abrikosov.jpg

 19%|█▊        | 1659/8920 [45:34<58:23,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yury_Luzhkov.jpg

 19%|█▊        | 1660/8920 [45:35<1:16:48,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petr_Mitrichev.jpg

 19%|█▊        | 1661/8920 [45:36<1:16:12,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Otto_Struve.jpg

 19%|█▊        | 1662/8920 [45:36<1:13:43,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Arnold.jpg

 19%|█▊        | 1663/8920 [45:37<1:34:15,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Margulis.jpg

 19%|█▊        | 1664/8920 [45:38<1:31:55,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Shukhov.jpg

 19%|█▊        | 1665/8920 [45:39<1:24:51,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Okounkov.jpg

 19%|█▊        | 1666/8920 [45:39<1:22:15,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Fock.jpg

 19%|█▊        | 1667/8920 [45:40<1:07:43,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Ansoff.jpg

 19%|█▊        | 1668/8920 [45:40<55:41,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulii_Khariton.jpg

 19%|█▊        | 1669/8920 [45:40<1:03:17,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Drinfeld.jpg

 19%|█▊        | 1670/8920 [45:42<1:42:57,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rashid_Sunyaev.jpg

 19%|█▊        | 1671/8920 [45:42<1:20:27,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Florensky.jpg

 19%|█▊        | 1672/8920 [45:43<1:19:25,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stepan_Makarov.jpg

 19%|█▉        | 1673/8920 [45:44<1:26:41,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Zhukovsky.jpg

 19%|█▉        | 1674/8920 [45:45<1:36:52,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Salye.jpg

 19%|█▉        | 1675/8920 [45:46<1:42:34,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Friedrich_Georg_Wilhelm_Von_Struve.jpg

 19%|█▉        | 1676/8920 [45:47<1:44:01,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Timofeevich_Fomenko.jpg

 19%|█▉        | 1677/8920 [45:47<1:34:58,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Otto_Schmidt.jpg

 19%|█▉        | 1678/8920 [45:48<1:26:16,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Vasilyevich_Markovnikov.jpg

 19%|█▉        | 1679/8920 [45:49<1:55:55,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Efim_Isaakovich_Zelmanov.jpg

 19%|█▉        | 1680/8920 [45:50<1:43:29,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Mishin.jpg

 19%|█▉        | 1681/8920 [45:51<1:45:46,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Sergeevich_Aleksandrov.jpg

 19%|█▉        | 1682/8920 [45:53<2:46:37,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Semyonov.jpg

 19%|█▉        | 1683/8920 [45:54<2:06:03,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Chagall.jpg

 19%|█▉        | 1684/8920 [45:54<1:35:51,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wassily_Kandinsky.jpg

 19%|█▉        | 1685/8920 [45:54<1:15:44,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kazimir_Malevich.jpg

 19%|█▉        | 1686/8920 [45:55<1:29:44,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Repin.jpg

 19%|█▉        | 1687/8920 [45:56<1:21:49,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Aivazovsky.jpg

 19%|█▉        | 1688/8920 [45:57<1:33:01,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Roerich.jpg

 19%|█▉        | 1689/8920 [45:58<1:41:40,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Shishkin.jpg

 19%|█▉        | 1690/8920 [45:58<1:33:10,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Rodchenko.jpg

 19%|█▉        | 1691/8920 [45:59<1:25:45,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Goncharova.jpg

 19%|█▉        | 1692/8920 [46:00<1:27:37,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaac_Levitan.jpg

 19%|█▉        | 1693/8920 [46:00<1:20:43,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Bilibin.jpg

 19%|█▉        | 1694/8920 [46:01<1:28:13,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Serov.jpg

 19%|█▉        | 1695/8920 [46:02<1:21:13,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Vasnetsov.jpg

 19%|█▉        | 1696/8920 [46:03<1:33:19,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Vereshchagin.jpg

 19%|█▉        | 1697/8920 [46:04<1:44:27,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Léon_Bakst.jpg

 19%|█▉        | 1698/8920 [46:05<1:43:59,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Rublev.jpg

 19%|█▉        | 1699/8920 [46:05<1:35:23,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Surikov.jpg

 19%|█▉        | 1700/8920 [46:05<1:18:50,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/El_Lissitzky.jpg

 19%|█▉        | 1701/8920 [46:07<1:33:07,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Perov.jpg

 19%|█▉        | 1702/8920 [46:07<1:38:25,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Makovsky.jpg

 19%|█▉        | 1703/8920 [46:08<1:34:41,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arkhip_Kuindzhi.jpg

 19%|█▉        | 1704/8920 [46:09<1:30:16,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolas_De_Stael.jpg

 19%|█▉        | 1705/8920 [46:09<1:25:09,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Vrubel.jpg

 19%|█▉        | 1706/8920 [46:10<1:20:09,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Kush.jpg

 19%|█▉        | 1707/8920 [46:10<1:04:48,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petr_Pavlensky.jpg

 19%|█▉        | 1708/8920 [46:11<1:19:06,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naum_Gabo.jpg

 19%|█▉        | 1709/8920 [46:12<1:32:14,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Larionov.jpg

 19%|█▉        | 1710/8920 [46:13<1:44:57,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Bryullov.jpg

 19%|█▉        | 1711/8920 [46:14<1:54:17,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexej_Von_Jawlensky.jpg

 19%|█▉        | 1712/8920 [46:15<1:42:09,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Kustodiev.jpg

 19%|█▉        | 1713/8920 [46:15<1:21:21,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Kramskoi.jpg

 19%|█▉        | 1714/8920 [46:17<2:06:28,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelina_Beloff.jpg

 19%|█▉        | 1715/8920 [46:18<2:05:26,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vera_Mukhina.jpg

 19%|█▉        | 1716/8920 [46:19<1:51:34,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Hartmann.jpg

 19%|█▉        | 1717/8920 [46:20<1:40:04,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vissarion.jpg

 19%|█▉        | 1718/8920 [46:20<1:34:08,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marie_Bashkirtseff.jpg

 19%|█▉        | 1719/8920 [46:21<1:43:01,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zurab_Tsereteli.jpg

 19%|█▉        | 1720/8920 [46:22<1:35:43,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandra_Ekster.jpg

 19%|█▉        | 1721/8920 [46:23<1:42:15,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marianne_Von_Werefkin.jpg

 19%|█▉        | 1722/8920 [46:24<1:35:32,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Prokofiev.jpg

 19%|█▉        | 1723/8920 [46:24<1:27:07,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Rozanova.jpg

 19%|█▉        | 1724/8920 [46:25<1:21:13,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varvara_Stepanova.jpg

 19%|█▉        | 1725/8920 [46:26<1:28:54,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Polenov.jpg

 19%|█▉        | 1726/8920 [46:28<2:31:44,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Nesterov.jpg

 19%|█▉        | 1727/8920 [46:29<2:11:53,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Pasternak.jpg

 19%|█▉        | 1728/8920 [46:30<2:00:02,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Andreyevich_Ivanov.jpg

 19%|█▉        | 1729/8920 [46:30<1:34:56,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Mikhaylovich_Gerasimov.jpg

 19%|█▉        | 1730/8920 [46:31<1:39:45,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Tchelitchew.jpg

 19%|█▉        | 1731/8920 [46:31<1:29:58,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kuzma_Petrov-Vodkin.jpg

 19%|█▉        | 1732/8920 [46:32<1:23:14,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolai_Fechin.jpg

 19%|█▉        | 1733/8920 [46:33<1:22:04,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Ge.jpg

 19%|█▉        | 1734/8920 [46:34<1:32:33,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Orest_Kiprensky.jpg

 19%|█▉        | 1735/8920 [46:34<1:25:40,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Volegov.jpg

 19%|█▉        | 1736/8920 [46:36<1:52:15,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksey_Savrasov.jpg

 19%|█▉        | 1737/8920 [46:37<1:53:33,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Korovin.jpg

 19%|█▉        | 1738/8920 [46:37<1:42:17,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franz_Roubaud.jpg

 19%|█▉        | 1739/8920 [46:38<1:41:07,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyubov_Popova.jpg

 20%|█▉        | 1740/8920 [46:39<1:37:43,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Borovikovsky.jpg

 20%|█▉        | 1741/8920 [46:39<1:19:59,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Alexeieff.jpg

 20%|█▉        | 1742/8920 [46:40<1:24:44,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dionisius.jpg

 20%|█▉        | 1743/8920 [46:41<1:32:27,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Prigov.jpg

 20%|█▉        | 1744/8920 [46:42<1:39:38,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Andreyevich_Fedotov.jpg

 20%|█▉        | 1745/8920 [46:43<1:48:13,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Bogdanov-Belsky.jpg

 20%|█▉        | 1746/8920 [46:44<1:39:34,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Benois.jpg

 20%|█▉        | 1747/8920 [46:44<1:30:24,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Konchalovsky.jpg

 20%|█▉        | 1748/8920 [46:46<1:52:28,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Apollinary_Vasnetsov.jpg

 20%|█▉        | 1749/8920 [46:47<1:58:57,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Altman.jpg

 20%|█▉        | 1750/8920 [46:47<1:45:21,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aristarkh_Lentulov.jpg

 20%|█▉        | 1751/8920 [46:47<1:21:12,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Of_Perm.jpg

 20%|█▉        | 1752/8920 [46:49<1:55:09,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Yuon.jpg

 20%|█▉        | 1753/8920 [46:50<1:55:45,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Ushakov.jpg

 20%|█▉        | 1754/8920 [46:51<1:55:46,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Kliun.jpg

 20%|█▉        | 1755/8920 [46:52<1:56:03,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaak_Brodsky.jpg

 20%|█▉        | 1756/8920 [46:53<1:44:19,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Rokotov.jpg

 20%|█▉        | 1757/8920 [46:55<2:25:14,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Somov.jpg

 20%|█▉        | 1758/8920 [46:55<1:52:07,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Kalashnikov.jpg

 20%|█▉        | 1759/8920 [46:55<1:27:23,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_K._Zworykin.jpg

 20%|█▉        | 1760/8920 [46:56<1:21:01,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Theremin.jpg

 20%|█▉        | 1761/8920 [46:56<1:09:03,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Stepanovich_Popov.jpg

 20%|█▉        | 1762/8920 [46:57<1:10:02,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Mikhaylovich_Gerasimov.jpg

 20%|█▉        | 1763/8920 [46:57<58:17,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rashid_Sunyaev.jpg

 20%|█▉        | 1764/8920 [46:57<50:13,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Zhukovsky.jpg

 20%|█▉        | 1765/8920 [46:58<55:35,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Florensky.jpg

 20%|█▉        | 1766/8920 [46:58<47:34,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svyatoslav_Fyodorov.jpg

 20%|█▉        | 1767/8920 [46:59<51:33,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Shpagin.jpg

 20%|█▉        | 1768/8920 [46:59<44:48,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Alexeieff.jpg

 20%|█▉        | 1769/8920 [47:00<1:08:18,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Yablochkov.jpg

 20%|█▉        | 1770/8920 [47:00<1:01:01,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Pirogov.jpg

 20%|█▉        | 1771/8920 [47:02<1:52:58,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Losev.jpg

 20%|█▉        | 1772/8920 [47:04<2:18:31,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Rosing.jpg

 20%|█▉        | 1773/8920 [47:05<2:11:22,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Lebedev.jpg

 20%|█▉        | 1774/8920 [47:05<1:54:36,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yul_Brynner_3242.jpg

 20%|█▉        | 1775/8920 [47:06<1:29:25,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tarkovsky.jpg

 20%|█▉        | 1776/8920 [47:06<1:09:57,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Eisenstein.jpg

 20%|█▉        | 1777/8920 [47:07<1:10:11,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danila_Kozlovsky.jpg

 20%|█▉        | 1778/8920 [47:07<1:06:29,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Stanislavski.jpg

 20%|█▉        | 1779/8920 [47:08<1:13:26,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Khodchenkova_52363.jpg

 20%|█▉        | 1780/8920 [47:08<1:16:30,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Baldry.jpg

 20%|█▉        | 1781/8920 [47:10<1:31:58,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Khabensky.jpg

 20%|█▉        | 1782/8920 [47:11<2:10:03,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyubov_Orlova.jpg

 20%|█▉        | 1783/8920 [47:12<1:51:59,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Mashkov.jpg

 20%|██        | 1784/8920 [47:13<1:53:49,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Mikhalkov.jpg

 20%|██        | 1785/8920 [47:15<2:33:40,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Kolokolnikov.jpg

 20%|██        | 1786/8920 [47:15<1:55:52,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Ustinova.jpg

 20%|██        | 1787/8920 [47:16<1:54:11,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Antonenko.jpg

 20%|██        | 1788/8920 [47:17<1:39:58,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alisa_Freindlich.jpg

 20%|██        | 1789/8920 [47:18<1:48:23,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Petrov.jpg

 20%|██        | 1790/8920 [47:19<1:54:08,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Conway.jpg

 20%|██        | 1791/8920 [47:19<1:40:04,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maryana_Spivak.jpg

 20%|██        | 1792/8920 [47:21<1:53:42,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Klimova.jpg

 20%|██        | 1793/8920 [47:22<2:05:07,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kseniya_Rappoport.jpg

 20%|██        | 1794/8920 [47:23<1:52:07,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Peresild.jpg

 20%|██        | 1795/8920 [47:23<1:43:45,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Lyadova.jpg

 20%|██        | 1796/8920 [47:25<2:12:18,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Ivanova.jpg

 20%|██        | 1797/8920 [47:26<2:12:32,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksei_Serebryakov.jpg

 20%|██        | 1798/8920 [47:27<1:59:28,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pasha_D._Lychnikoff.jpg

 20%|██        | 1799/8920 [47:27<1:42:43,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariya_Lugovaya.jpg

 20%|██        | 1800/8920 [47:29<1:50:13,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liza_Arzamasova.jpg

 20%|██        | 1801/8920 [47:30<2:14:01,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksei_Yevgenyevich_Kravchenko.jpg

 20%|██        | 1802/8920 [47:31<1:51:58,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Konchalovsky.jpg

 20%|██        | 1803/8920 [47:31<1:42:12,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Alfyorova.jpg

 20%|██        | 1804/8920 [47:32<1:51:32,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Nikulin.jpg

 20%|██        | 1805/8920 [47:33<1:37:37,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akim_Tamiroff.jpg

 20%|██        | 1806/8920 [47:34<1:32:23,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Solonitsyn.jpg

 20%|██        | 1807/8920 [47:34<1:13:29,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xenia_Tchoumitcheva.jpg

 20%|██        | 1808/8920 [47:35<1:15:17,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Chekhov.jpg

 20%|██        | 1809/8920 [47:35<1:01:24,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Buzova.jpg

 20%|██        | 1810/8920 [47:36<1:32:35,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Kaidanovsky.jpg

 20%|██        | 1811/8920 [47:36<1:14:54,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yekaterina_Guseva.jpg

 20%|██        | 1812/8920 [47:38<1:30:34,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vyacheslav_Tikhonov.jpg

 20%|██        | 1813/8920 [47:38<1:34:46,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Mirman.jpg

 20%|██        | 1814/8920 [47:39<1:16:28,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Goncharova.jpg

 20%|██        | 1815/8920 [47:40<1:28:51,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nonna_Mordyukova.jpg

 20%|██        | 1816/8920 [47:40<1:24:02,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Kuznetsov.jpg

 20%|██        | 1817/8920 [47:42<1:44:15,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatole_Litvak.jpg

 20%|██        | 1818/8920 [47:43<1:54:51,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Bilibin.jpg

 20%|██        | 1819/8920 [47:43<1:38:12,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Terekhova.jpg

 20%|██        | 1820/8920 [47:44<1:26:00,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktoriya_Isakova.jpg

 20%|██        | 1821/8920 [47:45<1:46:26,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Shklovsky.jpg

 20%|██        | 1822/8920 [47:46<1:30:58,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Priluchny.jpg

 20%|██        | 1823/8920 [47:47<1:38:57,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dziga_Vertov.jpg

 20%|██        | 1824/8920 [47:48<2:08:44,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Boyarsky.jpg

 20%|██        | 1825/8920 [47:49<2:02:44,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Yefremov.jpg

 20%|██        | 1826/8920 [47:51<2:14:32,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bondarchuk.jpg

 20%|██        | 1827/8920 [47:51<2:07:18,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Gorbacheva.jpg

 20%|██        | 1828/8920 [47:53<2:27:15,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Kulagina.jpg

 21%|██        | 1829/8920 [47:54<2:29:45,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamara_Toumanova.jpg

 21%|██        | 1830/8920 [47:56<2:23:25,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Menshikov.jpg

 21%|██        | 1831/8920 [47:56<2:05:18,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bodrov.jpg

 21%|██        | 1832/8920 [47:57<2:00:19,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Poezzhaeva.jpg

 21%|██        | 1833/8920 [47:58<1:46:23,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Savely_Kramarov.jpg

 21%|██        | 1834/8920 [47:58<1:38:01,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olesya_Rulin_14007.jpg

 21%|██        | 1835/8920 [47:59<1:24:17,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Tabakov.jpg

 21%|██        | 1836/8920 [47:59<1:08:22,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Lomonosova.jpg

 21%|██        | 1837/8920 [48:00<1:08:17,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vsevolod_Meyerhold.jpg

 21%|██        | 1838/8920 [48:00<1:07:11,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Kupchenko.jpg

 21%|██        | 1839/8920 [48:01<57:38,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Baronova.jpg

 21%|██        | 1840/8920 [48:01<1:12:57,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktoriya_Agalakova.jpg

 21%|██        | 1841/8920 [48:02<1:09:40,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Abdulov.jpg

 21%|██        | 1842/8920 [48:03<1:25:03,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoli_Papanov.jpg

 21%|██        | 1843/8920 [48:04<1:34:10,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Tsyganov.jpg

 21%|██        | 1844/8920 [48:04<1:14:29,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alla.jpg

 21%|██        | 1845/8920 [48:05<1:34:27,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Leonov.jpg

 21%|██        | 1846/8920 [48:06<1:42:03,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Gaidai.jpg

 21%|██        | 1847/8920 [48:07<1:33:10,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Andrejchenko.jpg

 21%|██        | 1848/8920 [48:09<2:23:31,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Armen_Dzhigarkhanyan.jpg

 21%|██        | 1849/8920 [48:10<1:51:04,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Diamond.jpg

 21%|██        | 1850/8920 [48:10<1:28:56,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liza_Anokhina.jpg

 21%|██        | 1851/8920 [48:10<1:09:50,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Beregova.jpg

 21%|██        | 1852/8920 [48:11<1:04:59,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Bilyalova.jpg

 21%|██        | 1853/8920 [48:11<1:06:33,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kira_Simurina.jpg

 21%|██        | 1854/8920 [48:11<54:40,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1855/8920 [48:12<45:56,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1856/8920 [48:12<40:39,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1857/8920 [48:12<36:38,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1858/8920 [48:12<33:38,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1859/8920 [48:13<30:47,  3.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1860/8920 [48:13<30:17,  3.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1861/8920 [48:13<30:22,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1862/8920 [48:13<28:53,  4.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1863/8920 [48:14<48:34,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 21%|██        | 1864/8920 [48:14<42:42,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasilisa.jpg

 21%|██        | 1865/8920 [48:15<39:45,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nika_Leytink.jpg

 21%|██        | 1866/8920 [48:15<48:35,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanilopa_Tik_149608.jpg

 21%|██        | 1867/8920 [48:15<42:02,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zara_Silver.jpg

 21%|██        | 1868/8920 [48:16<39:44,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/.jpg

 21%|██        | 1869/8920 [48:16<43:08,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iamkatushaa_149602.jpg

 21%|██        | 1870/8920 [48:17<52:19,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasile.jpg

 21%|██        | 1871/8920 [48:18<1:10:58,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milka_Queen_149607.jpg

 21%|██        | 1872/8920 [48:18<57:54,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mekhrona_Sharipova.jpg

 21%|██        | 1873/8920 [48:18<50:09,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sweetfox.jpg

 21%|██        | 1874/8920 [48:19<53:18,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karna.Val.jpg

 21%|██        | 1875/8920 [48:19<49:05,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kat_Longoria_149564.jpg

 21%|██        | 1876/8920 [48:19<41:53,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pokrov90.jpg

 21%|██        | 1877/8920 [48:20<39:53,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alec_Horn.jpg

 21%|██        | 1878/8920 [48:20<36:38,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Radmir_Ozodov.jpg

 21%|██        | 1879/8920 [48:20<33:29,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefan_Taran.jpg

 21%|██        | 1880/8920 [48:21<45:40,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Instasamka_149604.jpg

 21%|██        | 1881/8920 [48:21<54:44,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Endomarfa.jpg

 21%|██        | 1882/8920 [48:22<45:32,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steff_Happy.jpg

 21%|██        | 1883/8920 [48:22<40:34,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Rosh.jpg

 21%|██        | 1884/8920 [48:22<52:38,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cody_Miller_149618.jpg

 21%|██        | 1885/8920 [48:23<44:13,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeria_Voronina.jpg

 21%|██        | 1886/8920 [48:23<52:17,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marya_149598.jpg

 21%|██        | 1887/8920 [48:24<56:09,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennyboiy.jpg

 21%|██        | 1888/8920 [48:24<47:35,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natsya_Monahova.jpg

 21%|██        | 1889/8920 [48:24<41:32,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tanyahereforu.jpg

 21%|██        | 1890/8920 [48:25<37:59,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tasha_S.jpg

 21%|██        | 1891/8920 [48:25<37:20,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xoang_Xa.jpg

 21%|██        | 1892/8920 [48:25<35:27,  3.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tuzelity.jpg

 21%|██        | 1893/8920 [48:26<46:44,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelika_Kruglova.jpg

 21%|██        | 1894/8920 [48:26<49:27,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Slev_Taylor.jpg

 21%|██        | 1895/8920 [48:27<1:05:56,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Maddyson.jpg

 21%|██▏       | 1896/8920 [48:28<1:05:52,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dima_Vodny.jpg

 21%|██▏       | 1897/8920 [48:28<1:11:11,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mimikliffi.jpg

 21%|██▏       | 1898/8920 [48:29<1:18:45,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Gavrilina.jpg

 21%|██▏       | 1899/8920 [48:30<1:31:05,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aren_Zurabyan.jpg

 21%|██▏       | 1900/8920 [48:31<1:39:54,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Johansson.jpg

 21%|██▏       | 1901/8920 [48:32<1:31:41,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anya_Ischuk.jpg

 21%|██▏       | 1902/8920 [48:32<1:23:25,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Bocharov.jpg

 21%|██▏       | 1903/8920 [48:33<1:18:33,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alisha_Kone.jpg

 21%|██▏       | 1904/8920 [48:34<1:29:29,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Renata_Valliulina.jpg

 21%|██▏       | 1905/8920 [48:35<1:32:38,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vlad_Hoshin.jpg

 21%|██▏       | 1906/8920 [48:37<2:04:14,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeria_Tanashevich.jpg

 21%|██▏       | 1907/8920 [48:37<1:48:21,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amina_Mirzoeva.jpg

 21%|██▏       | 1908/8920 [48:39<2:09:22,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danya_Milokhin.jpg

 21%|██▏       | 1909/8920 [48:39<1:52:14,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Egorkaship.jpg

 21%|██▏       | 1910/8920 [48:41<2:10:30,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dasha_Dzhakeli.jpg

 21%|██▏       | 1911/8920 [48:42<1:56:26,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilnur_Khafizov.jpg

 21%|██▏       | 1912/8920 [48:42<1:55:28,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Sorabi.jpg

 21%|██▏       | 1913/8920 [48:43<1:44:07,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rxnexus.jpg

 21%|██▏       | 1914/8920 [48:44<1:50:43,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Belitskaya.jpg

 21%|██▏       | 1915/8920 [48:46<2:16:42,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Kruzin.jpg

 21%|██▏       | 1916/8920 [48:47<2:00:32,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stas_Kolchanov.jpg

 21%|██▏       | 1917/8920 [48:48<2:11:06,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Oleynik.jpg

 22%|██▏       | 1918/8920 [48:49<1:58:39,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mira_Twitch.jpg

 22%|██▏       | 1919/8920 [48:49<1:46:17,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitriy_Shilov.jpg

 22%|██▏       | 1920/8920 [48:50<1:37:45,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristi_Krime.jpg

 22%|██▏       | 1921/8920 [48:51<1:44:23,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Elfie.jpg

 22%|██▏       | 1922/8920 [48:52<1:56:30,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inna_Simakova.jpg

 22%|██▏       | 1923/8920 [48:53<1:38:56,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vlad_Onlad.jpg

 22%|██▏       | 1924/8920 [48:53<1:18:49,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lika_Andreeva.jpg

 22%|██▏       | 1925/8920 [48:53<1:06:55,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katya_Golysheva.jpg

 22%|██▏       | 1926/8920 [48:54<1:09:09,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellen_Sheidlin.jpg

 22%|██▏       | 1927/8920 [48:55<1:10:57,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Goar_Avetisyan.jpg

 22%|██▏       | 1928/8920 [48:55<1:00:43,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1929/8920 [48:55<51:22,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1930/8920 [48:56<1:00:42,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1931/8920 [48:57<1:02:57,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Partizen.jpg

 22%|██▏       | 1932/8920 [48:57<54:26,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Farber.jpg

 22%|██▏       | 1933/8920 [48:57<54:20,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yunona_Kovalenko.jpg

 22%|██▏       | 1934/8920 [48:58<46:05,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milanka_Kudel.jpg

 22%|██▏       | 1935/8920 [48:58<39:46,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yana_Chirkina.jpg

 22%|██▏       | 1936/8920 [48:58<35:42,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Nioly_Pushkareva.jpg

 22%|██▏       | 1937/8920 [48:58<32:38,  3.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jia_Lissa.jpg

 22%|██▏       | 1938/8920 [48:59<46:38,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Delish.jpg

 22%|██▏       | 1939/8920 [49:00<1:04:09,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Shmakova.jpg

 22%|██▏       | 1940/8920 [49:00<1:05:08,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Zueva.jpg

 22%|██▏       | 1941/8920 [49:01<1:07:09,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Katysheva.jpg

 22%|██▏       | 1942/8920 [49:02<1:08:24,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Shpak.jpg

 22%|██▏       | 1943/8920 [49:03<1:39:42,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tuana_Milanova.jpg

 22%|██▏       | 1944/8920 [49:04<1:29:24,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_K..jpg

 22%|██▏       | 1945/8920 [49:05<1:40:09,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sveta_B.jpg

 22%|██▏       | 1946/8920 [49:06<1:53:00,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anella_Miller.jpg

 22%|██▏       | 1947/8920 [49:07<1:56:25,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milana_Khametova.jpg

 22%|██▏       | 1948/8920 [49:07<1:30:41,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naida_Nai.jpg

 22%|██▏       | 1949/8920 [49:08<1:21:01,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasiya_Knyazeva.jpg

 22%|██▏       | 1950/8920 [49:09<1:19:54,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Karmanova.jpg

 22%|██▏       | 1951/8920 [49:10<1:35:14,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hasbulla_Magomedov.jpg

 22%|██▏       | 1952/8920 [49:10<1:29:41,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirogane-Sama.jpg

 22%|██▏       | 1953/8920 [49:12<1:47:06,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Nikitina_Alekseevna.jpg

 22%|██▏       | 1954/8920 [49:12<1:22:07,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kson96.jpg

 22%|██▏       | 1955/8920 [49:12<1:16:23,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sveta_Sanders.jpg

 22%|██▏       | 1956/8920 [49:13<1:01:19,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Bilyalova.jpg

 22%|██▏       | 1957/8920 [49:13<58:32,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Malinovskaya.jpg

 22%|██▏       | 1958/8920 [49:14<1:17:27,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dina_Saeva.jpg

 22%|██▏       | 1959/8920 [49:25<7:23:17,  3.82s/it]

❌ Failed to download https://www.thefamouspeople.com/profiles/thumbs/dasha-taran-1.jpg: _ssl.c:983: The handshake operation timed out

 22%|██▏       | 1960/8920 [49:34<10:26:48,  5.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helga_Lovekaty.jpg

 22%|██▏       | 1961/8920 [49:35<7:41:33,  3.98s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Ivleeva.jpg

 22%|██▏       | 1962/8920 [49:36<6:02:37,  3.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Pavaga.jpg

 22%|██▏       | 1963/8920 [49:37<4:34:52,  2.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lily_Ermak.jpg

 22%|██▏       | 1964/8920 [49:37<3:34:25,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristy_Ren.jpg

 22%|██▏       | 1965/8920 [49:39<3:12:09,  1.66s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_Kross.jpg

 22%|██▏       | 1966/8920 [49:39<2:39:25,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dima_S..jpg

 22%|██▏       | 1967/8920 [49:40<2:11:14,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danya_Bely.jpg

 22%|██▏       | 1968/8920 [49:41<2:14:38,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeri_Sowa.jpg

 22%|██▏       | 1969/8920 [49:41<1:47:19,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mila_Asmr_Mood.jpg

 22%|██▏       | 1970/8920 [49:42<1:33:50,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milana_Melkumova.jpg

 22%|██▏       | 1971/8920 [49:44<2:01:43,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nfkrz.jpg

 22%|██▏       | 1972/8920 [49:44<1:35:17,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taras_Kulakov.jpg

 22%|██▏       | 1973/8920 [49:44<1:26:26,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhong.jpg

 22%|██▏       | 1974/8920 [49:45<1:08:40,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1975/8920 [49:45<57:36,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1976/8920 [49:46<1:07:14,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1977/8920 [49:46<55:44,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1978/8920 [49:46<46:44,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1979/8920 [49:46<41:22,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Chirkin.jpg

 22%|██▏       | 1980/8920 [49:47<36:50,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Galkina.jpg

 22%|██▏       | 1981/8920 [49:48<56:23,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larin.jpg

 22%|██▏       | 1982/8920 [49:48<52:55,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kamil_Kikido.jpg

 22%|██▏       | 1983/8920 [49:50<1:35:13,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dimitri_Petrenko.jpg

 22%|██▏       | 1984/8920 [49:50<1:17:27,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofya_Plotnikova.jpg

 22%|██▏       | 1985/8920 [49:50<1:09:51,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malina_Asmr.jpg

 22%|██▏       | 1986/8920 [49:51<57:00,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taisiya_Chirkina.jpg

 22%|██▏       | 1987/8920 [49:51<50:13,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Mogilko.jpg

 22%|██▏       | 1988/8920 [49:51<44:13,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1989/8920 [49:51<38:11,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moona.jpg

 22%|██▏       | 1990/8920 [49:53<1:07:22,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Westjett_149611.jpg

 22%|██▏       | 1991/8920 [49:53<57:44,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Abroad.jpg

 22%|██▏       | 1992/8920 [49:53<49:33,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Odnovol.jpg

 22%|██▏       | 1993/8920 [49:54<1:10:14,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yaroslav_Kuznetsov_149617.jpg

 22%|██▏       | 1994/8920 [49:54<59:27,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/No_Profile.jpg

 22%|██▏       | 1995/8920 [49:56<1:24:56,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dafuq!?Boom!.jpg

 22%|██▏       | 1996/8920 [49:56<1:23:56,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_Kozyreva.jpg

 22%|██▏       | 1997/8920 [49:57<1:34:12,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viki_Show.jpg

 22%|██▏       | 1998/8920 [49:59<2:02:30,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rima_Alosta.jpg

 22%|██▏       | 1999/8920 [50:00<1:52:50,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Misha_Maksimov.jpg

 22%|██▏       | 2000/8920 [50:01<1:40:38,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jove.jpg

 22%|██▏       | 2001/8920 [50:01<1:35:55,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Basstop.jpg

 22%|██▏       | 2002/8920 [50:01<1:14:44,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Like_Nastya_120212.jpg

 22%|██▏       | 2003/8920 [50:03<1:29:13,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitaly_Zdorovetskiy.jpg

 22%|██▏       | 2004/8920 [50:03<1:10:11,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milana_Coco.jpg

 22%|██▏       | 2005/8920 [50:03<1:04:13,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Gentlewhispering.jpg

 22%|██▏       | 2006/8920 [50:04<56:27,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Beregova.jpg

 22%|██▎       | 2007/8920 [50:04<1:03:35,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Badcomedian.jpg

 23%|██▎       | 2008/8920 [50:05<1:09:38,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Everythingapplepro.jpg

 23%|██▎       | 2009/8920 [50:06<1:22:01,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Vitaly.jpg

 23%|██▎       | 2010/8920 [50:07<1:21:45,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Clapp.jpg

 23%|██▎       | 2011/8920 [50:08<1:45:06,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bella_Devyatkina.jpg

 23%|██▎       | 2012/8920 [50:09<2:01:21,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katya_Adushkina.jpg

 23%|██▎       | 2013/8920 [50:10<1:49:48,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mari_Kruchkova.jpg

 23%|██▎       | 2014/8920 [50:11<1:34:53,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asya_Siam.jpg

 23%|██▎       | 2015/8920 [50:12<1:57:19,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Tropicelle.jpg

 23%|██▎       | 2016/8920 [50:14<2:11:36,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Spilberg.jpg

 23%|██▎       | 2017/8920 [50:14<1:47:58,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dasha_Taran.jpg

 23%|██▎       | 2018/8920 [50:14<1:27:27,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Shayk.jpg

 23%|██▎       | 2019/8920 [50:15<1:15:27,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Luss.jpg

 23%|██▎       | 2020/8920 [50:15<1:01:06,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Pimenova.jpg

 23%|██▎       | 2021/8920 [50:15<52:27,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Vodianova_35828.jpg

 23%|██▎       | 2022/8920 [50:16<56:14,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Vyalitsyna.jpg

 23%|██▎       | 2023/8920 [50:17<1:05:49,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Kvitko.jpg

 23%|██▎       | 2024/8920 [50:18<1:31:07,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Carl_Fabergé.jpg

 23%|██▎       | 2025/8920 [50:19<1:43:41,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Fonda.jpg

 23%|██▎       | 2026/8920 [50:20<1:53:00,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Romanova.jpg

 23%|██▎       | 2027/8920 [50:21<1:33:34,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xenia_Tchoumitcheva.jpg

 23%|██▎       | 2028/8920 [50:22<1:40:21,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugenia_Volodina.jpg

 23%|██▎       | 2029/8920 [50:22<1:33:10,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Glebova.jpg

 23%|██▎       | 2030/8920 [50:23<1:26:07,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zivert.jpg

 23%|██▎       | 2031/8920 [50:23<1:18:09,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alena_Shishkova.jpg

 23%|██▎       | 2032/8920 [50:24<1:07:08,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuliya_Snigir.jpg

 23%|██▎       | 2033/8920 [50:25<1:43:38,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Burn.jpg

 23%|██▎       | 2034/8920 [50:26<1:47:26,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vita_Sidorkina.jpg

 23%|██▎       | 2035/8920 [50:27<1:27:20,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Buzova.jpg

 23%|██▎       | 2036/8920 [50:27<1:11:00,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Goncharova.jpg

 23%|██▎       | 2037/8920 [50:28<1:15:20,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ksenia_Sukhinova.jpg

 23%|██▎       | 2038/8920 [50:28<1:10:46,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khrystyana_Kazakova.jpg

 23%|██▎       | 2039/8920 [50:29<1:26:18,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Pivovarova.jpg

 23%|██▎       | 2040/8920 [50:30<1:09:54,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yekaterina_Lisina.jpg

 23%|██▎       | 2041/8920 [50:31<1:25:25,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masha_Novoselova.jpg

 23%|██▎       | 2042/8920 [50:32<1:36:22,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Voronina.jpg

 23%|██▎       | 2043/8920 [50:33<1:30:09,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Sanko.jpg

 23%|██▎       | 2044/8920 [50:33<1:14:00,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Palina_Rojinski.jpg

 23%|██▎       | 2045/8920 [50:33<1:03:37,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Antonenko.jpg

 23%|██▎       | 2046/8920 [50:34<1:09:25,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Bezrukova.jpg

 23%|██▎       | 2047/8920 [50:35<1:37:49,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Grigorieva.jpg

 23%|██▎       | 2048/8920 [50:36<1:28:39,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sati_Kazanova.jpg

 23%|██▎       | 2049/8920 [50:37<1:25:51,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Sorokko.jpg

 23%|██▎       | 2050/8920 [50:38<1:35:03,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Poly.jpg

 23%|██▎       | 2051/8920 [50:38<1:31:36,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alesia_Raut.jpg

 23%|██▎       | 2052/8920 [50:39<1:24:41,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Sten.jpg

 23%|██▎       | 2053/8920 [50:40<1:34:28,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tania_Russof.jpg

 23%|██▎       | 2054/8920 [50:41<1:31:17,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Pantaeva.jpg

 23%|██▎       | 2055/8920 [50:41<1:13:48,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Gross.jpg

 23%|██▎       | 2056/8920 [50:42<1:12:28,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viki_Odintcova.jpg

 23%|██▎       | 2057/8920 [50:43<1:26:27,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Ivanovskaya.jpg

 23%|██▎       | 2058/8920 [50:44<1:33:52,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agatha_Maksimova.jpg

 23%|██▎       | 2059/8920 [50:46<2:11:31,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Berkova.jpg

 23%|██▎       | 2060/8920 [50:46<1:52:21,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Kahn.jpg

 23%|██▎       | 2061/8920 [50:47<1:58:55,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anya_Monzikova.jpg

 23%|██▎       | 2062/8920 [50:48<1:30:38,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Shubskaya.jpg

 23%|██▎       | 2063/8920 [50:48<1:24:08,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Malova.jpg

 23%|██▎       | 2064/8920 [50:50<2:07:26,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Lloyd.jpg

 23%|██▎       | 2065/8920 [50:52<2:18:13,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gia_Skova.jpg

 23%|██▎       | 2066/8920 [50:52<1:43:49,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Shchapova.jpg

 23%|██▎       | 2067/8920 [50:53<2:03:33,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludmilla_Radchenko.jpg

 23%|██▎       | 2068/8920 [50:56<2:54:10,  1.53s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edelweiss.jpg

 23%|██▎       | 2069/8920 [50:56<2:13:20,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yekaterina_Volkova.jpg

 23%|██▎       | 2070/8920 [50:56<1:41:11,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Navalny.jpg

 23%|██▎       | 2071/8920 [50:57<1:33:32,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Magnitsky.jpg

 23%|██▎       | 2072/8920 [50:58<1:48:39,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyubov_Sobol.jpg

 23%|██▎       | 2073/8920 [51:00<2:01:23,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Poklonskaya.jpg

 23%|██▎       | 2074/8920 [51:00<1:44:48,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathalie_Sarraute.jpg

 23%|██▎       | 2075/8920 [51:01<1:45:56,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Kryuchkov.jpg

 23%|██▎       | 2076/8920 [51:02<1:32:55,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Shuvalov.jpg

 23%|██▎       | 2077/8920 [51:02<1:24:11,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Chicherin.jpg

 23%|██▎       | 2078/8920 [51:03<1:23:20,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Friedrich_Martens.jpg

 23%|██▎       | 2079/8920 [51:09<4:10:55,  2.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Nikolayevich_Durnovo.jpg

 23%|██▎       | 2080/8920 [51:10<3:30:55,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernest_Ametistov.jpg

 23%|██▎       | 2081/8920 [51:13<4:38:43,  2.45s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Tunkin.jpg

 23%|██▎       | 2082/8920 [51:14<3:25:35,  1.80s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Abramovich.jpg

 23%|██▎       | 2083/8920 [51:14<2:34:09,  1.35s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Prokhorov.jpg

 23%|██▎       | 2084/8920 [51:14<1:54:56,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Khodorkovsky.jpg

 23%|██▎       | 2085/8920 [51:15<1:41:06,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dasha_Zhukova.jpg

 23%|██▎       | 2086/8920 [51:16<1:33:56,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evgeny_Lebedev.jpg

 23%|██▎       | 2087/8920 [51:16<1:27:03,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Deripaska.jpg

 23%|██▎       | 2088/8920 [51:17<1:33:36,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Melnichenko.jpg

 23%|██▎       | 2089/8920 [51:18<1:41:18,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Butina.jpg

 23%|██▎       | 2090/8920 [51:19<1:32:21,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alisher_Usmanov.jpg

 23%|██▎       | 2091/8920 [51:20<1:41:56,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miroslava_Duma.jpg

 23%|██▎       | 2092/8920 [51:22<2:05:39,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Vekselberg.jpg

 23%|██▎       | 2093/8920 [51:23<2:04:38,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Milner.jpg

 23%|██▎       | 2094/8920 [51:24<2:03:56,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Rybolovlev.jpg

 23%|██▎       | 2095/8920 [51:24<1:43:51,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arkadiy_Abramovich.jpg

 23%|██▎       | 2096/8920 [51:25<1:46:30,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislav_Doronin.jpg

 24%|██▎       | 2097/8920 [51:25<1:22:30,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Kaspersky.jpg

 24%|██▎       | 2098/8920 [51:26<1:29:49,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Andreev.jpg

 24%|██▎       | 2099/8920 [51:28<1:58:38,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Berezovsky.jpg

 24%|██▎       | 2100/8920 [51:29<1:44:02,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Abramov.jpg

 24%|██▎       | 2101/8920 [51:30<1:58:17,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatyana_Bakalchuk.jpg

 24%|██▎       | 2102/8920 [51:31<1:43:33,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vagit_Alekperov.jpg

 24%|██▎       | 2103/8920 [51:31<1:23:24,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvira_Nabiullina.jpg

 24%|██▎       | 2104/8920 [51:31<1:17:23,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexey_Miller.jpg

 24%|██▎       | 2105/8920 [51:32<1:16:34,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Potanin.jpg

 24%|██▎       | 2106/8920 [51:33<1:34:13,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Mikhelson.jpg

 24%|██▎       | 2107/8920 [51:34<1:18:44,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/German_Khan.jpg

 24%|██▎       | 2108/8920 [51:34<1:16:46,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Chernomyrdin.jpg

 24%|██▎       | 2109/8920 [51:35<1:16:30,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ekaterina_Rybolovleva.jpg

 24%|██▎       | 2110/8920 [51:36<1:17:46,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Lebedev.jpg

 24%|██▎       | 2111/8920 [51:36<1:09:31,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Roldugin.jpg

 24%|██▎       | 2112/8920 [51:37<1:33:07,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Aven.jpg

 24%|██▎       | 2113/8920 [51:38<1:39:57,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Makarov.jpg

 24%|██▎       | 2114/8920 [51:39<1:44:39,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Tretyakov.jpg

 24%|██▎       | 2115/8920 [51:40<1:42:43,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Mazepin.jpg

 24%|██▎       | 2116/8920 [51:41<1:45:03,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aras_Agalarov.jpg

 24%|██▎       | 2117/8920 [51:42<1:32:01,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gustav_Fabergé.jpg

 24%|██▎       | 2118/8920 [51:44<2:13:59,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Gusinsky.jpg

 24%|██▍       | 2119/8920 [51:45<2:18:18,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_Tchelistcheff.jpg

 24%|██▍       | 2120/8920 [51:46<2:12:55,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Kaspersky.jpg

 24%|██▍       | 2121/8920 [51:47<1:59:46,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Farkhad_Akhmedov.jpg

 24%|██▍       | 2122/8920 [51:48<1:54:41,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rem_Vyakhirev.jpg

 24%|██▍       | 2123/8920 [51:49<1:41:12,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Savva_Mamontov.jpg

 24%|██▍       | 2124/8920 [51:49<1:19:38,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Baturina.jpg

 24%|██▍       | 2125/8920 [51:51<1:59:57,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Kay.jpg

 24%|██▍       | 2126/8920 [51:52<2:21:28,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Goga_Ashkenazi.jpg

 24%|██▍       | 2127/8920 [51:54<2:41:51,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Romanovich_Rotenberg.jpg

 24%|██▍       | 2128/8920 [51:55<2:03:00,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Avdeev.jpg

 24%|██▍       | 2129/8920 [51:55<1:45:35,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herman_Gref.jpg

 24%|██▍       | 2130/8920 [51:57<2:21:43,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Telman_Ismailov.jpg

 24%|██▍       | 2131/8920 [51:58<2:12:09,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iskander_Makhmudov.jpg

 24%|██▍       | 2132/8920 [52:00<2:28:08,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Koch.jpg

 24%|██▍       | 2133/8920 [52:00<2:03:23,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Rotenberg.jpg

 24%|██▍       | 2134/8920 [52:01<1:52:08,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Mints.jpg

 24%|██▍       | 2135/8920 [52:02<1:36:10,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Pavlovich_Demidov,_2Nd_Prince_Of_San_Donato.jpg

 24%|██▍       | 2136/8920 [52:03<1:44:50,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Netrebko.jpg

 24%|██▍       | 2137/8920 [52:04<1:48:04,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Tsoi.jpg

 24%|██▍       | 2138/8920 [52:04<1:25:23,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/.jpg

 24%|██▍       | 2139/8920 [52:05<1:23:36,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aida_Garifullina.jpg

 24%|██▍       | 2140/8920 [52:05<1:22:23,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitri_Hvorostovsky.jpg

 24%|██▍       | 2141/8920 [52:06<1:13:06,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lena_Katina.jpg

 24%|██▍       | 2142/8920 [52:06<1:10:10,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Vysotsky.jpg

 24%|██▍       | 2143/8920 [52:08<1:43:39,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Gagarina.jpg

 24%|██▍       | 2144/8920 [52:09<1:38:18,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Regina_Spektor.jpg

 24%|██▍       | 2145/8920 [52:09<1:31:24,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emin_Agalarov.jpg

 24%|██▍       | 2146/8920 [52:11<1:48:32,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Khil.jpg

 24%|██▍       | 2147/8920 [52:11<1:38:28,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zivert.jpg

 24%|██▍       | 2148/8920 [52:12<1:25:01,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katya_Sambuca.jpg

 24%|██▍       | 2149/8920 [52:13<1:38:59,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pelageya.jpg

 24%|██▍       | 2150/8920 [52:14<1:45:40,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dima_Bilan.jpg

 24%|██▍       | 2151/8920 [52:15<1:37:02,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galina_Vishnevskaya.jpg

 24%|██▍       | 2152/8920 [52:18<2:44:09,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Semenovich.jpg

 24%|██▍       | 2153/8920 [52:19<2:34:56,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Baclanova.jpg

 24%|██▍       | 2154/8920 [52:19<2:07:32,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Korolyova.jpg

 24%|██▍       | 2155/8920 [52:20<1:41:31,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oksana.jpg

 24%|██▍       | 2156/8920 [52:20<1:21:40,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexey_Vorobyov.jpg

 24%|██▍       | 2157/8920 [52:21<1:40:00,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nyusha.jpg

 24%|██▍       | 2158/8920 [52:23<1:56:45,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Kotova.jpg

 24%|██▍       | 2159/8920 [52:23<1:44:26,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timati.jpg

 24%|██▍       | 2160/8920 [52:24<1:22:13,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Gradsky.jpg

 24%|██▍       | 2161/8920 [52:24<1:08:48,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glukoza.jpg

 24%|██▍       | 2162/8920 [52:26<1:47:03,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zemfira.jpg

 24%|██▍       | 2163/8920 [52:26<1:32:44,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Nachalova.jpg

 24%|██▍       | 2164/8920 [52:27<1:25:08,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Allegrova.jpg

 24%|██▍       | 2165/8920 [52:27<1:08:46,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Volkova.jpg

 24%|██▍       | 2166/8920 [52:28<1:04:59,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alla_Pugacheva.jpg

 24%|██▍       | 2167/8920 [52:28<1:06:13,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alsou.jpg

 24%|██▍       | 2168/8920 [52:29<1:07:05,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeanna_Friske.jpg

 24%|██▍       | 2169/8920 [52:29<54:12,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Shatunov.jpg

 24%|██▍       | 2170/8920 [52:30<1:00:05,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelina_Danilova.jpg

 24%|██▍       | 2171/8920 [52:31<1:13:02,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Feodor_Chaliapin.jpg

 24%|██▍       | 2172/8920 [52:34<2:55:42,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeriya.jpg

 24%|██▍       | 2173/8920 [52:36<2:41:24,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Vaenga.jpg

 24%|██▍       | 2174/8920 [52:36<2:15:29,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadezhda_Tolokonnikova.jpg

 24%|██▍       | 2175/8920 [52:37<1:51:26,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Talkov.jpg

 24%|██▍       | 2176/8920 [52:37<1:28:47,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sati_Kazanova.jpg

 24%|██▍       | 2177/8920 [52:38<1:36:11,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sevak_Khanagyan.jpg

 24%|██▍       | 2178/8920 [52:39<1:29:51,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Orbakaite.jpg

 24%|██▍       | 2179/8920 [52:39<1:23:32,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Bezrukov.jpg

 24%|██▍       | 2180/8920 [52:40<1:17:36,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Egor_Kreed.jpg

 24%|██▍       | 2181/8920 [52:40<1:05:03,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Gazmanov.jpg

 24%|██▍       | 2182/8920 [52:41<1:21:04,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Fadeev.jpg

 24%|██▍       | 2183/8920 [52:42<1:31:57,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Temnikova.jpg

 24%|██▍       | 2184/8920 [52:43<1:43:30,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Seryabkina.jpg

 24%|██▍       | 2185/8920 [52:44<1:38:21,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Origa.jpg

 25%|██▍       | 2186/8920 [52:44<1:16:25,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Karpova.jpg

 25%|██▍       | 2187/8920 [52:46<1:29:07,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coretti_Arle-Titz.jpg

 25%|██▍       | 2188/8920 [52:46<1:35:20,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Lazarev.jpg

 25%|██▍       | 2189/8920 [52:47<1:27:31,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Peretyatko.jpg

 25%|██▍       | 2190/8920 [52:48<1:33:30,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yekaterina_Guseva.jpg

 25%|██▍       | 2191/8920 [52:49<1:24:49,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maksim.jpg

 25%|██▍       | 2192/8920 [52:50<1:33:13,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Leps.jpg

 25%|██▍       | 2193/8920 [52:51<2:03:53,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktorija_Loba.jpg

 25%|██▍       | 2194/8920 [52:53<2:06:19,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zelim_Bakaev.jpg

 25%|██▍       | 2195/8920 [52:54<2:08:09,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Baskov.jpg

 25%|██▍       | 2196/8920 [52:54<1:45:38,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Shnurov.jpg

 25%|██▍       | 2197/8920 [52:56<2:10:05,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristian_Kostov.jpg

 25%|██▍       | 2198/8920 [52:57<1:55:18,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Lezhneva.jpg

 25%|██▍       | 2199/8920 [52:57<1:44:37,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Mamonov.jpg

 25%|██▍       | 2200/8920 [52:58<1:46:29,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Kobzon.jpg

 25%|██▍       | 2201/8920 [52:59<1:36:17,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Leshchenko.jpg

 25%|██▍       | 2202/8920 [53:00<1:26:29,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Zykina.jpg

 25%|██▍       | 2203/8920 [53:00<1:22:36,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lolita_Milyavskaya.jpg

 25%|██▍       | 2204/8920 [53:01<1:40:35,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natali.jpg

 25%|██▍       | 2205/8920 [53:02<1:32:55,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ildar_Abdrazakov.jpg

 25%|██▍       | 2206/8920 [53:03<1:40:06,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Krug.jpg

 25%|██▍       | 2207/8920 [53:04<1:51:09,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bianka_Singer.jpg

 25%|██▍       | 2208/8920 [53:05<1:36:33,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stas_Piekha.jpg

 25%|██▍       | 2209/8920 [53:05<1:18:42,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Rosenbaum.jpg

 25%|██▍       | 2210/8920 [53:06<1:30:32,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Makarevich.jpg

 25%|██▍       | 2211/8920 [53:08<1:52:40,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Politkovskaya.jpg

 25%|██▍       | 2212/8920 [53:08<1:29:47,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Buzova.jpg

 25%|██▍       | 2213/8920 [53:08<1:12:35,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaac_Babel.jpg

 25%|██▍       | 2214/8920 [53:09<1:01:49,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miroslava_Duma.jpg

 25%|██▍       | 2215/8920 [53:09<55:01,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ksenia_Sukhinova.jpg

 25%|██▍       | 2216/8920 [53:09<47:50,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Korolyova.jpg

 25%|██▍       | 2217/8920 [53:10<46:19,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Dovlatov.jpg

 25%|██▍       | 2218/8920 [53:11<58:06,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Pozner_Jr..jpg

 25%|██▍       | 2219/8920 [53:11<1:03:36,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Bezmenov.jpg

 25%|██▍       | 2220/8920 [53:12<55:12,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Goncharov.jpg

 25%|██▍       | 2221/8920 [53:12<49:33,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Kotova.jpg

 25%|██▍       | 2222/8920 [53:13<56:56,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tina_Kandelaki.jpg

 25%|██▍       | 2223/8920 [53:13<57:46,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varlam_Shalamov.jpg

 25%|██▍       | 2224/8920 [53:14<1:00:04,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Krylov.jpg

 25%|██▍       | 2225/8920 [53:14<1:01:29,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Palina_Rojinski.jpg

 25%|██▍       | 2226/8920 [53:16<1:39:06,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masha_Gessen.jpg

 25%|██▍       | 2227/8920 [53:17<1:39:05,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eldar_Ryazanov.jpg

 25%|██▍       | 2228/8920 [53:18<2:05:09,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Chernyshevsky.jpg

 25%|██▍       | 2229/8920 [53:20<2:22:26,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Sorokko.jpg

 25%|██▌       | 2230/8920 [53:21<2:24:10,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Urgant.jpg

 25%|██▌       | 2231/8920 [53:22<2:03:04,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Nikolayevich_Zadornov.jpg

 25%|██▌       | 2232/8920 [53:23<2:12:27,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Bykov.jpg

 25%|██▌       | 2233/8920 [53:25<2:08:41,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lera_Kudryavtseva.jpg

 25%|██▌       | 2234/8920 [53:26<2:23:39,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Khaldei.jpg

 25%|██▌       | 2235/8920 [53:26<1:49:31,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bulat_Okudzhava.jpg

 25%|██▌       | 2236/8920 [53:28<2:00:02,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yury_Dud.jpg

 25%|██▌       | 2237/8920 [53:30<2:53:26,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kuravlyov.jpg

 25%|██▌       | 2238/8920 [53:31<2:10:28,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalya_Estemirova.jpg

 25%|██▌       | 2239/8920 [53:31<1:53:33,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Nevzorov.jpg

 25%|██▌       | 2240/8920 [53:32<1:39:23,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladislav_Listyev.jpg

 25%|██▌       | 2241/8920 [53:33<1:29:43,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Simonyan.jpg

 25%|██▌       | 2242/8920 [53:33<1:26:45,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zakhar_Prilepin.jpg

 25%|██▌       | 2243/8920 [53:34<1:36:20,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Trebunskaya.jpg

 25%|██▌       | 2244/8920 [53:35<1:29:57,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Korney_Chukovsky.jpg

 25%|██▌       | 2245/8920 [53:35<1:12:53,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Temnikova.jpg

 25%|██▌       | 2246/8920 [53:36<1:15:34,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Gordon.jpg

 25%|██▌       | 2247/8920 [53:36<1:06:49,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Latynina.jpg

 25%|██▌       | 2248/8920 [53:38<1:42:37,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrey_Makarevich.jpg

 25%|██▌       | 2249/8920 [53:39<1:31:05,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Ivinskaya.jpg

 25%|██▌       | 2250/8920 [53:39<1:15:03,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeriya_Novodvorskaya.jpg

 25%|██▌       | 2251/8920 [53:41<1:56:39,  1.05s/it]

❌ HTTP error 404 for https://www.thefamouspeople.com/profiles/thumbs/konstantin-simonov-1.jpg

 25%|██▌       | 2252/8920 [53:42<1:42:01,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Khanga.jpg

 25%|██▌       | 2253/8920 [53:43<1:43:06,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artyom_Borovik.jpg

 25%|██▌       | 2254/8920 [53:43<1:32:39,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Yakubovich.jpg

 25%|██▌       | 2255/8920 [53:44<1:42:53,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Sinyavsky.jpg

 25%|██▌       | 2256/8920 [53:45<1:23:03,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Mitroshina.jpg

 25%|██▌       | 2257/8920 [53:45<1:19:01,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caran_D'Ache.jpg

 25%|██▌       | 2258/8920 [53:48<2:23:42,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Korolenko.jpg

 25%|██▌       | 2259/8920 [53:49<2:02:59,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Dobrolyubov.jpg

 25%|██▌       | 2260/8920 [53:49<1:35:08,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Amalrik.jpg

 25%|██▌       | 2261/8920 [53:50<1:55:37,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Kuprin.jpg

 25%|██▌       | 2262/8920 [53:51<1:46:52,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lydia_Chukovskaya.jpg

 25%|██▌       | 2263/8920 [53:51<1:26:09,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgenia_Albats.jpg

 25%|██▌       | 2264/8920 [53:52<1:32:39,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Dzhigurda.jpg

 25%|██▌       | 2265/8920 [53:54<1:47:31,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Novikov.jpg

 25%|██▌       | 2266/8920 [53:54<1:35:10,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kondraty_Ryleyev.jpg

 25%|██▌       | 2267/8920 [53:55<1:25:07,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Katkov.jpg

 25%|██▌       | 2268/8920 [53:56<1:42:52,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Ginzburg.jpg

 25%|██▌       | 2269/8920 [53:57<1:49:56,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Slavina.jpg

 25%|██▌       | 2270/8920 [53:58<1:24:51,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Khakamada.jpg

 25%|██▌       | 2271/8920 [53:58<1:18:15,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maksim_Averin.jpg

 25%|██▌       | 2272/8920 [53:59<1:13:33,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Maksimov.jpg

 25%|██▌       | 2273/8920 [54:00<1:33:56,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Arbatov.jpg

 25%|██▌       | 2274/8920 [54:00<1:16:35,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Afanasyev.jpg

 26%|██▌       | 2275/8920 [54:00<1:00:22,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kronid_Lyubarsky.jpg

 26%|██▌       | 2276/8920 [54:02<1:21:58,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Lapenko.jpg

 26%|██▌       | 2277/8920 [54:02<1:14:00,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Aliger.jpg

 26%|██▌       | 2278/8920 [54:04<1:57:23,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Potresov.jpg

 26%|██▌       | 2279/8920 [54:05<1:43:59,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Dorenko.jpg

 26%|██▌       | 2280/8920 [54:05<1:31:47,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Afanasyev.jpg

 26%|██▌       | 2281/8920 [54:06<1:22:55,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johann_Voldemar_Jannsen.jpg

 26%|██▌       | 2282/8920 [54:07<1:18:42,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Mikhalkova.jpg

 26%|██▌       | 2283/8920 [54:08<1:29:54,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/D._S._Mirsky.jpg

 26%|██▌       | 2284/8920 [54:09<1:35:53,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Ilf.jpg

 26%|██▌       | 2285/8920 [54:09<1:15:01,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei.jpg

 26%|██▌       | 2286/8920 [54:09<1:00:59,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander.jpg

 26%|██▌       | 2287/8920 [54:10<56:13,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Semion_Mogilevich.jpg

 26%|██▌       | 2288/8920 [54:11<1:20:32,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Bout.jpg

 26%|██▌       | 2289/8920 [54:11<1:15:02,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fanny_Kaplan.jpg

 26%|██▌       | 2290/8920 [54:12<1:03:17,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Gaidamachuk.jpg

 26%|██▌       | 2291/8920 [54:12<1:07:35,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Delvey.jpg

 26%|██▌       | 2292/8920 [54:13<1:23:08,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadir_Salifov.jpg

 26%|██▌       | 2293/8920 [54:14<1:13:57,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonina_Makarova.jpg

 26%|██▌       | 2294/8920 [54:14<1:00:46,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darya_Nikolayevna.jpg

 26%|██▌       | 2295/8920 [54:14<50:43,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Petrova.jpg

 26%|██▌       | 2296/8920 [54:15<1:08:22,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamerlan_Tsarnaev.jpg

 26%|██▌       | 2297/8920 [54:16<1:04:48,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Konstantinovna_Briscorn.jpg

 26%|██▌       | 2299/8920 [54:17<50:39,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dokka_Umarov.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Martsinkevich.jpg

 26%|██▌       | 2300/8920 [54:17<51:58,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shamil_Basayev.jpg

 26%|██▌       | 2301/8920 [54:18<54:52,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Popkov.jpg

 26%|██▌       | 2302/8920 [54:18<1:01:19,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Slivko.jpg

 26%|██▌       | 2303/8920 [54:20<1:19:29,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamara_Samsonova.jpg

 26%|██▌       | 2304/8920 [54:20<1:17:22,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Mavrodi.jpg

 26%|██▌       | 2305/8920 [54:20<1:02:49,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khioniya_Guseva.jpg

 26%|██▌       | 2306/8920 [54:22<1:21:18,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alimzhan_Tokhtakhunov.jpg

 26%|██▌       | 2307/8920 [54:22<1:05:16,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Savinkov.jpg

 26%|██▌       | 2308/8920 [54:22<52:49,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdufatto_Zamanov.jpg

 26%|██▌       | 2309/8920 [54:22<46:48,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Bashlachev.jpg

 26%|██▌       | 2310/8920 [54:23<40:03,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Arkhipova.jpg

 26%|██▌       | 2311/8920 [54:23<37:27,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bulat_Okudzhava.jpg

 26%|██▌       | 2312/8920 [54:23<38:23,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vernon_Duke.jpg

 26%|██▌       | 2313/8920 [54:24<1:05:55,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monetochka.jpg

 26%|██▌       | 2314/8920 [54:25<1:06:03,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Ivanovich_Rozhdestvensky.jpg

 26%|██▌       | 2315/8920 [54:26<1:04:55,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stas_Mikhaylov.jpg

 26%|██▌       | 2316/8920 [54:26<1:07:51,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Meladze.jpg

 26%|██▌       | 2317/8920 [54:27<1:10:52,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_O'Shea.jpg

 26%|██▌       | 2318/8920 [54:27<1:00:45,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nyusha.jpg

 26%|██▌       | 2319/8920 [54:28<1:01:21,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Matvienko.jpg

 26%|██▌       | 2320/8920 [54:28<52:32,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Talkov.jpg

 26%|██▌       | 2321/8920 [54:28<45:19,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zemfira.jpg

 26%|██▌       | 2322/8920 [54:29<40:13,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Vaenga.jpg

 26%|██▌       | 2323/8920 [54:29<37:45,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sevak_Khanagyan.jpg

 26%|██▌       | 2324/8920 [54:30<46:56,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Shatunov.jpg

 26%|██▌       | 2325/8920 [54:30<42:58,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alsou.jpg

 26%|██▌       | 2326/8920 [54:30<42:03,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxim_Fadeev.jpg

 26%|██▌       | 2327/8920 [54:31<55:55,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Orbakaite.jpg

 26%|██▌       | 2328/8920 [54:33<1:29:16,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maksim.jpg

 26%|██▌       | 2329/8920 [54:33<1:13:30,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Mamonov.jpg

 26%|██▌       | 2330/8920 [54:33<1:00:31,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Seryabkina.jpg

 26%|██▌       | 2331/8920 [54:33<51:15,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Rosenbaum.jpg

 26%|██▌       | 2332/8920 [54:34<1:09:17,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Naumenko.jpg

 26%|██▌       | 2333/8920 [54:36<1:42:45,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natali.jpg

 26%|██▌       | 2334/8920 [54:36<1:22:26,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grigory_Leps.jpg

 26%|██▌       | 2335/8920 [54:38<1:35:45,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arkady_Kobyakov.jpg

 26%|██▌       | 2336/8920 [54:38<1:15:55,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yegor_Letov.jpg

 26%|██▌       | 2337/8920 [54:38<1:08:39,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valery_Meladze.jpg

 26%|██▌       | 2338/8920 [54:40<1:39:26,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizaveta_Khripounova.jpg

 26%|██▌       | 2339/8920 [54:42<2:04:18,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Of_Kiev.jpg

 26%|██▌       | 2340/8920 [54:42<1:35:12,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Nevsky.jpg

 26%|██▌       | 2341/8920 [54:42<1:17:19,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patriarch_Alexy_Ii_Of_Moscow.jpg

 26%|██▋       | 2342/8920 [54:43<1:18:15,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Menachem_Mendel_Schneerson.jpg

 26%|██▋       | 2343/8920 [54:43<1:04:38,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zinovia_Dushkova.jpg

 26%|██▋       | 2344/8920 [54:43<52:33,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patriarch_Kirill_I_Of_Moscow.jpg

 26%|██▋       | 2345/8920 [54:44<45:19,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patriarch_Nikon_Of_Moscow.jpg

 26%|██▋       | 2346/8920 [54:44<44:56,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patriarch_Alexy_I_Of_Moscow.jpg

 26%|██▋       | 2347/8920 [54:44<40:41,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergius_Of_Radonezh.jpg

 26%|██▋       | 2348/8920 [54:45<50:28,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Bogolyubsky.jpg

 26%|██▋       | 2349/8920 [54:46<54:22,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macarius,_Metropolitan_Of_Moscow.jpg

 26%|██▋       | 2350/8920 [54:46<1:08:21,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patriarch_Tikhon_Of_Moscow.jpg

 26%|██▋       | 2351/8920 [54:47<1:06:22,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antony_(Khrapovitsky).jpg

 26%|██▋       | 2352/8920 [54:48<1:30:03,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nilus_Of_Sora.jpg

 26%|██▋       | 2353/8920 [54:49<1:22:29,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonah_Of_Moscow.jpg

 26%|██▋       | 2354/8920 [54:50<1:18:46,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naftali_Zvi_Yehuda_Berlin.jpg

 26%|██▋       | 2355/8920 [54:51<1:38:40,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexius,_Metropolitan_Of_Kiev.jpg

 26%|██▋       | 2356/8920 [54:52<1:45:59,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Günzburg.jpg

 26%|██▋       | 2357/8920 [54:53<1:36:05,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gennady_Of_Novgorod.jpg

 26%|██▋       | 2358/8920 [54:54<1:59:20,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macarius_Bulgakov.jpg

 26%|██▋       | 2359/8920 [54:55<1:45:17,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ioann.jpg

 26%|██▋       | 2360/8920 [54:56<1:37:12,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurus_Škurla.jpg

 26%|██▋       | 2361/8920 [54:56<1:17:24,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meyer_Waxman.jpg

 26%|██▋       | 2362/8920 [54:57<1:36:37,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Of_Novgorod.jpg

 26%|██▋       | 2363/8920 [54:58<1:38:04,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theophan_Prokopovich.jpg

 27%|██▋       | 2364/8920 [55:00<1:53:58,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jampel_Lodoy.jpg

 27%|██▋       | 2365/8920 [55:00<1:38:47,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Korolev.jpg

 27%|██▋       | 2366/8920 [55:00<1:16:09,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Dyatlov.jpg

 27%|██▋       | 2367/8920 [55:01<1:02:01,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Kapitsa.jpg

 27%|██▋       | 2368/8920 [55:01<50:12,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_K._Zworykin.jpg

 27%|██▋       | 2369/8920 [55:01<44:05,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Theremin.jpg

 27%|██▋       | 2370/8920 [55:02<1:05:52,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Degtyaryov.jpg

 27%|██▋       | 2371/8920 [55:04<1:59:56,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Glushko.jpg

 27%|██▋       | 2372/8920 [55:05<1:54:02,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Ilyushin.jpg

 27%|██▋       | 2373/8920 [55:06<1:30:47,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Smirnov.jpg

 27%|██▋       | 2374/8920 [55:07<1:32:48,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Kalashnikov.jpg

 27%|██▋       | 2375/8920 [55:08<1:36:45,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tupolev.jpg

 27%|██▋       | 2376/8920 [55:09<2:07:08,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pier_Luigi_Nervi.jpg

 27%|██▋       | 2377/8920 [55:10<1:48:31,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Avdeyev.jpg

 27%|██▋       | 2378/8920 [55:11<1:54:12,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Popovich.jpg

 27%|██▋       | 2379/8920 [55:12<1:38:24,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Zhukovsky.jpg

 27%|██▋       | 2380/8920 [55:12<1:32:20,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Shukhov.jpg

 27%|██▋       | 2381/8920 [55:13<1:38:12,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Tupolev.jpg

 27%|██▋       | 2382/8920 [55:16<2:28:56,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Sergeyevich_Yakovlev.jpg

 27%|██▋       | 2383/8920 [55:17<2:04:59,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Shpagin.jpg

 27%|██▋       | 2384/8920 [55:18<2:10:29,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Yurchikhin.jpg

 27%|██▋       | 2385/8920 [55:18<1:38:28,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Florensky.jpg

 27%|██▋       | 2386/8920 [55:18<1:18:00,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Mishin.jpg

 27%|██▋       | 2387/8920 [55:19<1:20:02,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kerim_Kerimov.jpg

 27%|██▋       | 2388/8920 [55:20<1:16:07,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artem_Mikoyan.jpg

 27%|██▋       | 2389/8920 [55:21<1:23:14,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Fyodorovich_Makarov.jpg

 27%|██▋       | 2390/8920 [55:21<1:19:02,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gennady_Strekalov.jpg

 27%|██▋       | 2391/8920 [55:22<1:04:01,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Yablochkov.jpg

 27%|██▋       | 2392/8920 [55:22<1:05:33,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Chelomey.jpg

 27%|██▋       | 2393/8920 [55:23<1:07:37,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Feoktistov.jpg

 27%|██▋       | 2394/8920 [55:24<1:19:00,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Patsayev.jpg

 27%|██▋       | 2396/8920 [55:25<59:25,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Yangel.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Losev.jpg

 27%|██▋       | 2397/8920 [55:26<1:17:12,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Simonov.jpg

 27%|██▋       | 2398/8920 [55:28<1:53:59,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Mil.jpg

 27%|██▋       | 2399/8920 [55:29<1:56:05,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Ivanovsky.jpg

 27%|██▋       | 2400/8920 [55:30<1:51:13,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Korolev.jpg

 27%|██▋       | 2401/8920 [55:30<1:27:10,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Dyatlov.jpg

 27%|██▋       | 2402/8920 [55:30<1:07:56,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pyotr_Kapitsa.jpg

 27%|██▋       | 2403/8920 [55:32<1:32:05,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_K._Zworykin.jpg

 27%|██▋       | 2404/8920 [55:32<1:34:13,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Theremin.jpg

 27%|██▋       | 2405/8920 [55:33<1:35:27,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Degtyaryov.jpg

 27%|██▋       | 2406/8920 [55:34<1:27:05,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Glushko.jpg

 27%|██▋       | 2407/8920 [55:34<1:09:00,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Ilyushin.jpg

 27%|██▋       | 2408/8920 [55:35<1:08:45,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Smirnov.jpg

 27%|██▋       | 2409/8920 [55:35<1:00:14,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Kalashnikov.jpg

 27%|██▋       | 2410/8920 [55:35<51:17,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tupolev.jpg

 27%|██▋       | 2411/8920 [55:36<56:35,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pier_Luigi_Nervi.jpg

 27%|██▋       | 2412/8920 [55:37<53:27,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Avdeyev.jpg

 27%|██▋       | 2413/8920 [55:37<49:27,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Popovich.jpg

 27%|██▋       | 2414/8920 [55:37<43:35,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Zhukovsky.jpg

 27%|██▋       | 2415/8920 [55:38<53:07,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Shukhov.jpg

 27%|██▋       | 2416/8920 [55:38<45:16,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Tupolev.jpg

 27%|██▋       | 2417/8920 [55:38<41:30,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleksandr_Sergeyevich_Yakovlev.jpg

 27%|██▋       | 2418/8920 [55:39<37:29,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Shpagin.jpg

 27%|██▋       | 2419/8920 [55:39<33:35,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fyodor_Yurchikhin.jpg

 27%|██▋       | 2420/8920 [55:39<33:17,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Florensky.jpg

 27%|██▋       | 2421/8920 [55:40<1:00:15,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasily_Mishin.jpg

 27%|██▋       | 2422/8920 [55:41<51:25,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kerim_Kerimov.jpg

 27%|██▋       | 2423/8920 [55:41<57:52,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artem_Mikoyan.jpg

 27%|██▋       | 2424/8920 [55:42<1:07:08,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Fyodorovich_Makarov.jpg

 27%|██▋       | 2425/8920 [55:43<1:05:53,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gennady_Strekalov.jpg

 27%|██▋       | 2426/8920 [55:43<55:51,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Yablochkov.jpg

 27%|██▋       | 2427/8920 [55:46<2:16:47,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Chelomey.jpg

 27%|██▋       | 2428/8920 [55:46<1:48:05,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Feoktistov.jpg

 27%|██▋       | 2429/8920 [55:47<1:25:45,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Patsayev.jpg

 27%|██▋       | 2430/8920 [55:47<1:19:47,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Yangel.jpg

 27%|██▋       | 2431/8920 [55:49<1:56:35,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Losev.jpg

 27%|██▋       | 2432/8920 [55:49<1:28:53,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Simonov.jpg

 27%|██▋       | 2433/8920 [55:50<1:09:54,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Mil.jpg

 27%|██▋       | 2434/8920 [55:50<56:03,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Ivanovsky.jpg

 27%|██▋       | 2435/8920 [55:51<59:34,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wladimir_Klitschko.jpg

 27%|██▋       | 2436/8920 [55:51<50:17,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasyl_Lomachenko.jpg

 27%|██▋       | 2437/8920 [55:51<56:28,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Prokofiev_351.jpg

 27%|██▋       | 2438/8920 [55:52<50:15,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oksana_Baiul.jpg

 27%|██▋       | 2439/8920 [55:52<44:36,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Bubka.jpg

 27%|██▋       | 2440/8920 [55:52<39:55,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Vovchanchyn.jpg

 27%|██▋       | 2441/8920 [55:53<1:02:48,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Muzychuk.jpg

 27%|██▋       | 2442/8920 [55:54<52:36,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lilia_Podkopayeva.jpg

 27%|██▋       | 2443/8920 [55:54<48:52,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daria_Bilodid.jpg

 27%|██▋       | 2444/8920 [55:54<44:22,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariya_Muzychuk.jpg

 27%|██▋       | 2445/8920 [55:56<1:14:10,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Zhukova.jpg

 27%|██▋       | 2446/8920 [55:57<1:38:00,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Ushenina.jpg

 27%|██▋       | 2447/8920 [55:58<1:26:06,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olha_Kharlan.jpg

 27%|██▋       | 2448/8920 [55:58<1:10:25,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasyl_Ivanchuk.jpg

 27%|██▋       | 2449/8920 [55:58<57:53,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruslan_Ponomariov.jpg

 27%|██▋       | 2450/8920 [55:58<49:11,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Gorokhovskaya.jpg

 27%|██▋       | 2451/8920 [55:59<45:27,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yana_Shemyakina.jpg

 27%|██▋       | 2452/8920 [56:00<53:51,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Lysenko.jpg

 28%|██▊       | 2453/8920 [56:00<47:28,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleg_Blokhin.jpg

 28%|██▊       | 2454/8920 [56:01<1:16:11,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Polunin.jpg

 28%|██▊       | 2455/8920 [56:01<1:02:05,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Chukarin.jpg

 28%|██▊       | 2456/8920 [56:03<1:24:14,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Gutsu.jpg

 28%|██▊       | 2457/8920 [56:03<1:15:50,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kogan.jpg

 28%|██▊       | 2458/8920 [56:03<1:01:23,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kateryna_Lagno.jpg

 28%|██▊       | 2459/8920 [56:04<1:07:07,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anzhelika_Terliuga.jpg

 28%|██▊       | 2460/8920 [56:05<56:45,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Liashchuk.jpg

 28%|██▊       | 2461/8920 [56:06<1:12:46,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Eljanov.jpg

 28%|██▊       | 2462/8920 [56:07<1:25:38,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Ter-Ovanesyan.jpg

 28%|██▊       | 2463/8920 [56:07<1:07:47,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleksiy_Torokhtiy.jpg

 28%|██▊       | 2464/8920 [56:07<53:59,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Volokitin.jpg

 28%|██▊       | 2465/8920 [56:07<48:06,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yana_Klochkova.jpg

 28%|██▊       | 2466/8920 [56:08<45:46,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maksym_Krypak.jpg

 28%|██▊       | 2467/8920 [56:08<41:39,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lenny_Krayzelburg.jpg

 28%|██▊       | 2468/8920 [56:09<48:44,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Zhabotinsky.jpg

 28%|██▊       | 2469/8920 [56:09<55:28,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elbrus_Tedeyev.jpg

 28%|██▊       | 2470/8920 [56:10<1:05:48,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Bocharova.jpg

 28%|██▊       | 2471/8920 [56:10<54:04,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Geria.jpg

 28%|██▊       | 2472/8920 [56:11<46:38,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleksandr_Pyatnytsya.jpg

 28%|██▊       | 2473/8920 [56:11<41:23,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iryna_Merleni.jpg

 28%|██▊       | 2474/8920 [56:12<51:20,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Moiseenko.jpg

 28%|██▊       | 2475/8920 [56:13<1:09:24,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Mankin.jpg

 28%|██▊       | 2476/8920 [56:13<56:00,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Areshchenko.jpg

 28%|██▊       | 2477/8920 [56:14<1:20:31,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zinaida_Turchyna.jpg

 28%|██▊       | 2478/8920 [56:14<1:05:19,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vera_Krepkina.jpg

 28%|██▊       | 2479/8920 [56:15<54:53,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vita_Pavlysh.jpg

 28%|██▊       | 2480/8920 [56:15<48:14,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuriy_Kryvoruchko.jpg

 28%|██▊       | 2482/8920 [56:16<35:58,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zahar_Efimenko.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svetlana_Krachevskaya.jpg

 28%|██▊       | 2483/8920 [56:16<33:54,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Polina_Astakhova.jpg

 28%|██▊       | 2484/8920 [56:16<30:24,  3.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olena_Sadovnycha.jpg

 28%|██▊       | 2485/8920 [56:16<28:00,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nataliya_Burdeyna.jpg

 28%|██▊       | 2486/8920 [56:17<28:41,  3.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kateryna_Serdyuk.jpg

 28%|██▊       | 2487/8920 [56:17<26:42,  4.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleksandr_Yurkov.jpg

 28%|██▊       | 2488/8920 [56:17<29:09,  3.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Volodymyr_Zelenskiy.jpg

 28%|██▊       | 2489/8920 [56:17<27:11,  3.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andriy_Shevchenko.jpg

 28%|██▊       | 2490/8920 [56:19<59:24,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitali_Klitschko.jpg

 28%|██▊       | 2491/8920 [56:20<1:28:59,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kids_Diana_Show_101221.jpg

 28%|██▊       | 2492/8920 [56:22<1:59:48,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleksandr_Usyk.jpg

 28%|██▊       | 2493/8920 [56:22<1:36:02,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olena_Zelenska.jpg

 28%|██▊       | 2494/8920 [56:23<1:19:16,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jan_Koum.jpg

 28%|██▊       | 2495/8920 [56:23<1:20:14,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stepan_Bandera.jpg

 28%|██▊       | 2496/8920 [56:24<1:10:55,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andriy_Yarmolenko.jpg

 28%|██▊       | 2497/8920 [56:24<1:11:33,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_The_Great.jpg

 28%|██▊       | 2498/8920 [56:25<1:12:01,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_B._Mayer.jpg

 28%|██▊       | 2499/8920 [56:26<1:32:17,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Dyatlov.jpg

 28%|██▊       | 2500/8920 [56:28<1:58:58,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taras_Shevchenko.jpg

 28%|██▊       | 2501/8920 [56:29<2:04:26,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nestor_Makhno.jpg

 28%|██▊       | 2502/8920 [56:30<1:47:18,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Berta_Vazquez.jpg

 28%|██▊       | 2503/8920 [56:30<1:24:38,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamala.jpg

 28%|██▊       | 2504/8920 [56:31<1:22:32,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/.jpg

 28%|██▊       | 2505/8920 [56:31<1:04:52,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Verka_Serduchka.jpg

 28%|██▊       | 2506/8920 [56:33<1:27:32,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bohdan_Khmelnytsky.jpg

 28%|██▊       | 2507/8920 [56:33<1:23:47,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yaroslav_The_Wise.jpg

 28%|██▊       | 2508/8920 [56:34<1:08:39,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivanna_Sakhno.jpg

 28%|██▊       | 2510/8920 [56:34<46:12,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denis_Stoff.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophie_Tucker.jpg

 28%|██▊       | 2511/8920 [56:35<1:04:20,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadiya_Bychkova.jpg

 28%|██▊       | 2512/8920 [56:35<54:16,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tina_Karol.jpg

 28%|██▊       | 2513/8920 [56:36<59:55,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oxana_Malaya.jpg

 28%|██▊       | 2514/8920 [56:37<1:24:20,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruslana.jpg

 28%|██▊       | 2515/8920 [56:38<1:24:53,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonia_Delaunay.jpg

 28%|██▊       | 2516/8920 [56:40<1:41:40,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuliya_Levchenko.jpg

 28%|██▊       | 2517/8920 [56:41<1:57:54,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sviatoslav_Mykhailiuk.jpg

 28%|██▊       | 2518/8920 [56:41<1:34:40,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kravchuk.jpg

 28%|██▊       | 2519/8920 [56:42<1:22:35,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yelena_Yemchuk.jpg

 28%|██▊       | 2520/8920 [56:42<1:09:05,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Chmerkovskiy.jpg

 28%|██▊       | 2521/8920 [56:44<1:44:10,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeriy_Lobanovskyi.jpg

 28%|██▊       | 2522/8920 [56:45<1:31:04,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oksana_Lada.jpg

 28%|██▊       | 2523/8920 [56:45<1:30:39,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Ii_Monomakh.jpg

 28%|██▊       | 2524/8920 [56:46<1:28:20,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanisław_I_Leszczyński.jpg

 28%|██▊       | 2525/8920 [56:46<1:12:04,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Zdrok.jpg

 28%|██▊       | 2526/8920 [56:48<1:31:54,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Symon_Petlura.jpg

 28%|██▊       | 2527/8920 [56:48<1:16:32,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Bondarchuk.jpg

 28%|██▊       | 2528/8920 [56:50<1:46:22,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Ehrenburg.jpg

 28%|██▊       | 2529/8920 [56:50<1:21:53,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Mazepa.jpg

 28%|██▊       | 2530/8920 [56:51<1:39:05,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Durytska.jpg

 28%|██▊       | 2531/8920 [56:52<1:17:48,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svyatoslav_Vakarchuk.jpg

 28%|██▊       | 2532/8920 [56:52<1:03:16,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vera_Filatova.jpg

 28%|██▊       | 2533/8920 [56:53<1:26:49,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yaroslava_Mahuchikh.jpg

 28%|██▊       | 2534/8920 [56:53<1:07:57,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatole_Litvak.jpg

 28%|██▊       | 2535/8920 [56:54<1:06:32,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Prokofiev_351.jpg

 28%|██▊       | 2536/8920 [56:54<53:39,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Horowitz.jpg

 28%|██▊       | 2537/8920 [56:55<47:00,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denis_Stoff.jpg

 28%|██▊       | 2538/8920 [56:55<41:00,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Fedorova.jpg

 28%|██▊       | 2539/8920 [56:55<37:39,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svyatoslav_Vakarchuk.jpg

 28%|██▊       | 2540/8920 [56:55<34:35,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Milstein.jpg

 28%|██▊       | 2541/8920 [56:56<31:19,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rezz.jpg

 28%|██▊       | 2542/8920 [56:56<40:29,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Lisitsa.jpg

 29%|██▊       | 2543/8920 [56:56<36:13,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Hajiyeva.jpg

 29%|██▊       | 2544/8920 [56:57<36:19,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mischa_Elman.jpg

 29%|██▊       | 2545/8920 [56:58<1:06:54,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maruv.jpg

 29%|██▊       | 2546/8920 [56:58<54:09,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mykola_Leontovych.jpg

 29%|██▊       | 2547/8920 [56:59<48:56,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monatik.jpg

 29%|██▊       | 2548/8920 [56:59<41:05,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kogan.jpg

 29%|██▊       | 2549/8920 [56:59<37:29,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Krutoy.jpg

 29%|██▊       | 2550/8920 [57:00<1:05:03,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantin_Meladze.jpg

 29%|██▊       | 2551/8920 [57:01<53:02,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Dorn.jpg

 29%|██▊       | 2552/8920 [57:01<44:34,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Kapustin.jpg

 29%|██▊       | 2553/8920 [57:01<49:02,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastia.jpg

 29%|██▊       | 2554/8920 [57:02<41:21,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktoriya_Yermolyeva.jpg

 29%|██▊       | 2555/8920 [57:02<38:18,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Barskih.jpg

 29%|██▊       | 2556/8920 [57:02<37:05,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosina_Lhevinne.jpg

 29%|██▊       | 2557/8920 [57:02<34:37,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleh_Skrypka.jpg

 29%|██▊       | 2558/8920 [57:03<45:51,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benno_Moiseiwitsch.jpg

 29%|██▊       | 2559/8920 [57:04<1:11:57,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emanuel_Feuermann.jpg

 29%|██▊       | 2560/8920 [57:05<1:02:05,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadia_Meiher.jpg

 29%|██▊       | 2561/8920 [57:05<55:14,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shura_Cherkassky.jpg

 29%|██▊       | 2562/8920 [57:05<45:54,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Zaritskaya.jpg

 29%|██▊       | 2563/8920 [57:06<1:01:36,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Siarhei_Mikhalok.jpg

 29%|██▊       | 2564/8920 [57:07<1:03:26,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Prikhodko.jpg

 29%|██▉       | 2565/8920 [57:08<1:20:55,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Heil.jpg

 29%|██▉       | 2566/8920 [57:08<1:07:10,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rada_Lysenko.jpg

 29%|██▉       | 2567/8920 [57:09<1:08:17,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleh_Vynnyk.jpg

 29%|██▉       | 2568/8920 [57:11<1:39:51,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taras_Shevchenko.jpg

 29%|██▉       | 2569/8920 [57:11<1:22:09,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Ehrenburg.jpg

 29%|██▉       | 2570/8920 [57:12<1:14:43,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lesya_Ukrainka.jpg

 29%|██▉       | 2571/8920 [57:12<1:14:47,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Franko.jpg

 29%|██▉       | 2572/8920 [57:13<1:04:48,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Roth.jpg

 29%|██▉       | 2573/8920 [57:13<54:17,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Korolenko.jpg

 29%|██▉       | 2574/8920 [57:14<53:14,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aḥad_HaʿAm.jpg

 29%|██▉       | 2575/8920 [57:14<47:35,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Markiyan_Kamysh.jpg

 29%|██▉       | 2576/8920 [57:14<41:23,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A._D._Gordon.jpg

 29%|██▉       | 2577/8920 [57:14<37:28,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maruv.jpg

 29%|██▉       | 2578/8920 [57:15<43:57,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mykhailo_Kotsiubynsky.jpg

 29%|██▉       | 2579/8920 [57:15<40:26,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Ratushinskaya.jpg

 29%|██▉       | 2580/8920 [57:16<38:46,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Burliuk.jpg

 29%|██▉       | 2581/8920 [57:16<52:46,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Gufeld.jpg

 29%|██▉       | 2582/8920 [57:17<44:11,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saul_Tchernichowsky.jpg

 29%|██▉       | 2583/8920 [57:17<39:41,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ismail_Gasprinski.jpg

 29%|██▉       | 2584/8920 [57:17<35:28,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadia_Meiher.jpg

 29%|██▉       | 2585/8920 [57:17<34:35,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gregor_Von_Rezzori.jpg

 29%|██▉       | 2586/8920 [57:18<48:11,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naphtali_Herz_Imber.jpg

 29%|██▉       | 2587/8920 [57:18<41:18,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Kuznetsov.jpg

 29%|██▉       | 2588/8920 [57:19<38:15,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Kaminsky.jpg

 29%|██▉       | 2589/8920 [57:19<37:21,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Nechuy-Levytsky.jpg

 29%|██▉       | 2590/8920 [57:19<33:18,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Savinkov.jpg

 29%|██▉       | 2591/8920 [57:21<1:13:25,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Kotliarevsky.jpg

 29%|██▉       | 2592/8920 [57:22<1:15:48,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Avrom_Goldfaden.jpg

 29%|██▉       | 2593/8920 [57:22<1:01:50,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demyan_Bedny.jpg

 29%|██▉       | 2594/8920 [57:22<50:57,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Micha_Josef_Berdyczewski.jpg

 29%|██▉       | 2595/8920 [57:22<45:55,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Petrov.jpg

 29%|██▉       | 2596/8920 [57:23<40:37,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Artsybashev.jpg

 29%|██▉       | 2597/8920 [57:23<45:28,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Goldenweiser.jpg

 29%|██▉       | 2598/8920 [57:24<39:30,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaac_Boleslavsky.jpg

 29%|██▉       | 2599/8920 [57:24<52:22,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Bagritsky.jpg

 29%|██▉       | 2600/8920 [57:25<43:03,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moyshe-Leyb_Halpern.jpg

 29%|██▉       | 2601/8920 [57:25<39:05,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Vladimov.jpg

 29%|██▉       | 2602/8920 [57:26<59:22,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michał_Choromański.jpg

 29%|██▉       | 2603/8920 [57:27<1:24:10,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerzy_Toeplitz.jpg

 29%|██▉       | 2604/8920 [57:28<1:21:40,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julian_Stryjkowski.jpg

 29%|██▉       | 2605/8920 [57:28<1:10:32,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Volodymyr_Zelenskiy.jpg

 29%|██▉       | 2606/8920 [57:29<1:03:42,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stepan_Bandera.jpg

 29%|██▉       | 2607/8920 [57:29<53:51,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nestor_Makhno.jpg

 29%|██▉       | 2608/8920 [57:30<54:27,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitali_Klitschko.jpg

 29%|██▉       | 2609/8920 [57:31<1:14:24,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Symon_Petlura.jpg

 29%|██▉       | 2610/8920 [57:31<59:38,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kravchuk.jpg

 29%|██▉       | 2611/8920 [57:32<1:00:47,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Mazepa.jpg

 29%|██▉       | 2612/8920 [57:32<1:03:43,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Svyatoslav_Vakarchuk.jpg

 29%|██▉       | 2613/8920 [57:33<1:08:14,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Levi_Eshkol.jpg

 29%|██▉       | 2614/8920 [57:34<1:04:38,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Tymoshenko.jpg

 29%|██▉       | 2615/8920 [57:35<1:21:41,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Yanukovych.jpg

 29%|██▉       | 2616/8920 [57:35<1:16:29,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petro_Poroshenko.jpg

 29%|██▉       | 2617/8920 [57:36<1:19:26,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Georgyevich_Gorshkov.jpg

 29%|██▉       | 2618/8920 [57:36<1:06:30,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lazar_Kaganovich.jpg

 29%|██▉       | 2619/8920 [57:39<1:52:57,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikheil_Saakashvili.jpg

 29%|██▉       | 2620/8920 [57:39<1:39:57,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Semyon_Timoshenko.jpg

 29%|██▉       | 2621/8920 [57:40<1:23:34,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Slava_Medvedenko.jpg

 29%|██▉       | 2622/8920 [57:41<1:31:38,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Brezhnev.jpg

 29%|██▉       | 2623/8920 [57:41<1:28:18,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Kuchma.jpg

 29%|██▉       | 2624/8920 [57:42<1:31:36,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadiya_Savchenko.jpg

 29%|██▉       | 2625/8920 [57:43<1:35:10,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasyl_Virastyuk.jpg

 29%|██▉       | 2626/8920 [57:44<1:35:07,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rodion_Malinovsky.jpg

 29%|██▉       | 2627/8920 [57:45<1:26:49,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pinhas_Lavon.jpg

 29%|██▉       | 2628/8920 [57:47<1:49:05,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Chebrikov.jpg

 29%|██▉       | 2629/8920 [57:47<1:34:23,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Sokolov.jpg

 29%|██▉       | 2630/8920 [57:48<1:39:32,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Tikhonov.jpg

 29%|██▉       | 2631/8920 [57:49<1:32:08,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeriy_Borzov.jpg

 30%|██▉       | 2632/8920 [57:50<1:35:10,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eka_Zguladze.jpg

 30%|██▉       | 2633/8920 [57:51<1:34:42,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolai_Podgorny.jpg

 30%|██▉       | 2634/8920 [57:51<1:26:25,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A._D._Gordon.jpg

 30%|██▉       | 2635/8920 [57:52<1:21:32,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mykola_Azarov.jpg

 30%|██▉       | 2636/8920 [57:55<2:18:59,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Redl.jpg

 30%|██▉       | 2637/8920 [57:55<1:47:04,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Shevchuk.jpg

 30%|██▉       | 2638/8920 [57:56<1:35:52,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Fyodorovich_Paskevich.jpg

 30%|██▉       | 2639/8920 [57:57<1:39:05,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Nikiforova.jpg

 30%|██▉       | 2640/8920 [57:57<1:28:26,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Sipyagin.jpg

 30%|██▉       | 2641/8920 [57:58<1:19:48,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Stanishev.jpg

 30%|██▉       | 2642/8920 [57:58<1:14:41,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ismail_Gasprinski.jpg

 30%|██▉       | 2643/8920 [57:59<1:10:25,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Pyatakov.jpg

 30%|██▉       | 2644/8920 [57:59<57:42,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuriy_Yekhanurov.jpg

 30%|██▉       | 2645/8920 [58:00<1:01:58,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Ivashko.jpg

 30%|██▉       | 2646/8920 [58:00<52:54,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanislaw_Dulias.jpg

 30%|██▉       | 2647/8920 [58:01<51:45,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vyacheslav_Maksymovich_Chornovil.jpg

 30%|██▉       | 2648/8920 [58:01<44:08,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yisrael_Galili.jpg

 30%|██▉       | 2649/8920 [58:02<1:08:13,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Tolstykh.jpg

 30%|██▉       | 2650/8920 [58:03<1:19:53,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ignacy_Daszyński.jpg

 30%|██▉       | 2651/8920 [58:05<1:39:12,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Zhelyabov.jpg

 30%|██▉       | 2652/8920 [58:05<1:29:27,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Kornukov.jpg

 30%|██▉       | 2653/8920 [58:06<1:16:49,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agenor_Romuald_Gołuchowski.jpg

 30%|██▉       | 2654/8920 [58:06<1:02:33,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Savinkov.jpg

 30%|██▉       | 2655/8920 [58:07<1:11:19,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Bogrov.jpg

 30%|██▉       | 2656/8920 [58:07<1:09:10,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Prikhodko.jpg

 30%|██▉       | 2657/8920 [58:08<1:14:06,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Turanskaya.jpg

 30%|██▉       | 2658/8920 [58:10<1:32:25,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agenor_Maria_Gołuchowski.jpg

 30%|██▉       | 2659/8920 [58:11<1:34:40,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iryna_Farion.jpg

 30%|██▉       | 2660/8920 [58:11<1:29:14,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Maksyuta.jpg

 30%|██▉       | 2661/8920 [58:11<1:09:34,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoliy_Fedorchuk.jpg

 30%|██▉       | 2662/8920 [58:12<57:04,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ang_Lee.jpg

 30%|██▉       | 2663/8920 [58:12<48:16,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tai_Tzu-Ying.jpg

 30%|██▉       | 2664/8920 [58:12<42:04,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cher_Wang.jpg

 30%|██▉       | 2665/8920 [58:12<36:04,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yani_Tseng.jpg

 30%|██▉       | 2666/8920 [58:13<34:00,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chi_Cheng.jpg

 30%|██▉       | 2667/8920 [58:13<33:01,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuang_Chih-Yuan.jpg

 30%|██▉       | 2668/8920 [58:13<32:38,  3.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chao-Tsun_Cheng.jpg

 30%|██▉       | 2669/8920 [58:14<30:57,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tang_Chih-Chun.jpg

 30%|██▉       | 2670/8920 [58:14<30:32,  3.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Mu-Yen.jpg

 30%|██▉       | 2671/8920 [58:16<1:15:41,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deng_Yu-Cheng.jpg

 30%|██▉       | 2672/8920 [58:16<1:01:20,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Shih-Hsin.jpg

 30%|██▉       | 2673/8920 [58:16<51:41,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wei_Chun-Heng.jpg

 30%|██▉       | 2674/8920 [58:17<55:24,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tseng_Li-Cheng.jpg

 30%|██▉       | 2675/8920 [58:17<57:34,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huang_Chih-Hsiung.jpg

 30%|███       | 2676/8920 [58:18<47:59,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Peng-Lung.jpg

 30%|███       | 2677/8920 [58:18<42:42,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huang_Shih-Feng.jpg

 30%|███       | 2678/8920 [58:18<36:26,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liu_Ming-Huang.jpg

 30%|███       | 2679/8920 [58:18<33:03,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Cheng-Pang.jpg

 30%|███       | 2680/8920 [58:19<32:44,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Szu-Yuan.jpg

 30%|███       | 2681/8920 [58:19<41:50,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Lin.jpg

 30%|███       | 2682/8920 [58:21<1:23:35,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shu_Qi.jpg

 30%|███       | 2683/8920 [58:22<1:20:50,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Chen.jpg

 30%|███       | 2684/8920 [58:22<1:05:44,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tsai_Ing_Wen.jpg

 30%|███       | 2685/8920 [58:22<55:41,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chou_Tzu_Yu.jpg

 30%|███       | 2686/8920 [58:23<1:11:43,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Yan.jpg

 30%|███       | 2687/8920 [58:24<1:08:49,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Feng_Jiao.jpg

 30%|███       | 2688/8920 [58:26<1:36:01,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Takeshi_Kaneshiro.jpg

 30%|███       | 2689/8920 [58:26<1:16:22,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Morales.jpg

 30%|███       | 2690/8920 [58:27<1:22:36,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Chao.jpg

 30%|███       | 2691/8920 [58:27<1:04:43,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Chou.jpg

 30%|███       | 2692/8920 [58:27<52:36,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruby_Lin.jpg

 30%|███       | 2693/8920 [58:28<55:48,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Godfrey_Gao.jpg

 30%|███       | 2694/8920 [58:28<55:22,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbie_Hsu.jpg

 30%|███       | 2695/8920 [58:29<57:44,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Quinlivan.jpg

 30%|███       | 2696/8920 [58:30<56:12,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanness_Wu.jpg

 30%|███       | 2697/8920 [58:30<1:07:13,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darren_Chen.jpg

 30%|███       | 2698/8920 [58:31<55:47,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ouyang_Nana.jpg

 30%|███       | 2699/8920 [58:32<1:25:08,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cheng_Yen.jpg

 30%|███       | 2700/8920 [58:33<1:39:16,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ma_Ying_Jeou.jpg

 30%|███       | 2701/8920 [58:34<1:19:47,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Chi-Ling.jpg

 30%|███       | 2702/8920 [58:34<1:17:43,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rainie_Yang.jpg

 30%|███       | 2703/8920 [58:35<1:03:04,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wallace_Huo.jpg

 30%|███       | 2704/8920 [58:35<52:24,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janine_Chang.jpg

 30%|███       | 2705/8920 [58:36<54:27,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Yan.jpg

 30%|███       | 2706/8920 [58:37<1:26:57,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Chen.jpg

 30%|███       | 2707/8920 [58:37<1:08:30,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jolin_Tsai.jpg

 30%|███       | 2708/8920 [58:38<56:49,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Lin.jpg

 30%|███       | 2709/8920 [58:38<58:03,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joey_Wong.jpg

 30%|███       | 2710/8920 [58:39<48:52,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiro_Wang.jpg

 30%|███       | 2711/8920 [58:39<42:39,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jasper_Liu.jpg

 30%|███       | 2712/8920 [58:39<46:15,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiffany_Hsu.jpg

 30%|███       | 2713/8920 [58:40<40:44,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brigitte_Lin.jpg

 30%|███       | 2714/8920 [58:40<35:05,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Chen.jpg

 30%|███       | 2715/8920 [58:40<32:30,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terry_Gou.jpg

 30%|███       | 2716/8920 [58:41<42:25,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ethan_Juan.jpg

 30%|███       | 2717/8920 [58:42<1:02:04,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darren_Wang.jpg

 30%|███       | 2718/8920 [58:42<52:23,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai_Fu_Lee.jpg

 30%|███       | 2719/8920 [58:43<1:15:32,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dee_Hsu.jpg

 30%|███       | 2720/8920 [58:44<1:23:41,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Bolin.jpg

 31%|███       | 2721/8920 [58:45<1:07:47,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivian_Sung.jpg

 31%|███       | 2722/8920 [58:45<1:05:42,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Hsu.jpg

 31%|███       | 2723/8920 [58:46<1:12:31,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A-Lin.jpg

 31%|███       | 2724/8920 [58:47<1:31:05,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Chen.jpg

 31%|███       | 2725/8920 [58:48<1:11:32,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betty_Ting.jpg

 31%|███       | 2726/8920 [58:48<1:05:43,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Peng.jpg

 31%|███       | 2727/8920 [58:49<1:07:50,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morris_Chang.jpg

 31%|███       | 2728/8920 [58:49<55:58,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richie_Jen.jpg

 31%|███       | 2729/8920 [58:49<48:42,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Puff_Kuo.jpg

 31%|███       | 2730/8920 [58:51<1:13:53,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Saram.jpg

 31%|███       | 2731/8920 [58:51<59:07,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Fang-Liang.jpg

 31%|███       | 2732/8920 [58:51<49:59,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Liu.jpg

 31%|███       | 2733/8920 [58:52<45:22,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Chen.jpg

 31%|███       | 2734/8920 [58:52<40:26,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Lin.jpg

 31%|███       | 2735/8920 [58:52<36:33,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bai_Chongxi.jpg

 31%|███       | 2736/8920 [58:53<45:23,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Li.jpg

 31%|███       | 2737/8920 [58:53<39:41,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fong_Fei-Fei.jpg

 31%|███       | 2738/8920 [58:53<37:24,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chan_Hao-Ching.jpg

 31%|███       | 2739/8920 [58:54<34:31,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rene_Liu.jpg

 31%|███       | 2740/8920 [58:54<32:20,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A-Mei.jpg

 31%|███       | 2742/8920 [58:55<33:23,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vicky_Chen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicky_Wu.jpg

 31%|███       | 2743/8920 [58:55<31:04,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lai_Kuan-Lin.jpg

 31%|███       | 2744/8920 [58:56<56:42,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Yi.jpg

 31%|███       | 2745/8920 [58:56<50:28,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Latisha_Chan.jpg

 31%|███       | 2746/8920 [58:57<58:13,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Chen.jpg

 31%|███       | 2747/8920 [58:58<1:02:39,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Yang.jpg

 31%|███       | 2748/8920 [58:58<1:07:09,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hsieh_Su-Wei.jpg

 31%|███       | 2749/8920 [59:01<2:10:54,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lala_Hsu.jpg

 31%|███       | 2750/8920 [59:03<2:27:44,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kuo_Hsing-Chun.jpg

 31%|███       | 2751/8920 [59:03<1:50:45,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chou_Tien-Chen.jpg

 31%|███       | 2752/8920 [59:05<1:57:43,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Lin.jpg

 31%|███       | 2753/8920 [59:05<1:30:38,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanna_Wang.jpg

 31%|███       | 2754/8920 [59:05<1:10:54,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ady_An.jpg

 31%|███       | 2755/8920 [59:05<58:44,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oei_Hui-Lan.jpg

 31%|███       | 2756/8920 [59:06<49:11,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Yu-Sheng.jpg

 31%|███       | 2757/8920 [59:06<44:49,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gingle_Wang.jpg

 31%|███       | 2758/8920 [59:07<1:00:30,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Sheng.jpg

 31%|███       | 2759/8920 [59:07<58:40,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chien-Ming_Wang.jpg

 31%|███       | 2760/8920 [59:08<50:20,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Tseng.jpg

 31%|███       | 2761/8920 [59:08<43:30,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hebe_Tien.jpg

 31%|███       | 2762/8920 [59:08<41:08,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shu_Qi.jpg

 31%|███       | 2763/8920 [59:09<37:22,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tsai_Ing_Wen.jpg

 31%|███       | 2764/8920 [59:09<34:06,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Feng_Jiao.jpg

 31%|███       | 2765/8920 [59:10<1:06:24,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Morales.jpg

 31%|███       | 2766/8920 [59:11<58:10,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chou_Tzu_Yu.jpg

 31%|███       | 2767/8920 [59:12<1:14:50,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tai_Tzu-Ying.jpg

 31%|███       | 2768/8920 [59:12<1:01:51,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Quinlivan.jpg

 31%|███       | 2769/8920 [59:13<1:04:35,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cheng_Yen.jpg

 31%|███       | 2770/8920 [59:14<1:08:02,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruby_Lin.jpg

 31%|███       | 2771/8920 [59:14<1:05:32,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Chen.jpg

 31%|███       | 2773/8920 [59:15<45:00,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Chi-Ling.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rainie_Yang.jpg

 31%|███       | 2774/8920 [59:15<40:38,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbie_Hsu.jpg

 31%|███       | 2775/8920 [59:16<47:36,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jolin_Tsai.jpg

 31%|███       | 2776/8920 [59:16<53:48,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Su.jpg

 31%|███       | 2777/8920 [59:17<54:19,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ouyang_Nana.jpg

 31%|███       | 2778/8920 [59:18<1:12:52,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janine_Chang.jpg

 31%|███       | 2779/8920 [59:19<1:12:28,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Chen.jpg

 31%|███       | 2780/8920 [59:19<58:02,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brigitte_Lin.jpg

 31%|███       | 2781/8920 [59:19<48:29,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiffany_Hsu.jpg

 31%|███       | 2782/8920 [59:19<42:15,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joey_Wong.jpg

 31%|███       | 2783/8920 [59:20<35:55,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Lin.jpg

 31%|███       | 2784/8920 [59:21<56:26,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hsieh_Su-Wei.jpg

 31%|███       | 2785/8920 [59:21<47:17,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivian_Sung.jpg

 31%|███       | 2786/8920 [59:21<39:47,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Chen.jpg

 31%|███       | 2787/8920 [59:21<37:13,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hebe_Tien.jpg

 31%|███▏      | 2788/8920 [59:23<1:03:55,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dee_Hsu.jpg

 31%|███▏      | 2789/8920 [59:23<1:07:46,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Puff_Kuo.jpg

 31%|███▏      | 2790/8920 [59:24<1:04:16,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_Liu.jpg

 31%|███▏      | 2791/8920 [59:26<1:38:10,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A-Lin.jpg

 31%|███▏      | 2792/8920 [59:26<1:16:14,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betty_Ting.jpg

 31%|███▏      | 2793/8920 [59:26<1:10:28,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Chen.jpg

 31%|███▏      | 2794/8920 [59:27<1:07:06,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Teresa_Teng.jpg

 31%|███▏      | 2795/8920 [59:27<56:02,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ady_An.jpg

 31%|███▏      | 2796/8920 [59:28<47:47,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Tseng.jpg

 31%|███▏      | 2797/8920 [59:29<1:05:56,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Mei-Feng.jpg

 31%|███▏      | 2798/8920 [59:29<1:05:16,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivy_Chen.jpg

 31%|███▏      | 2799/8920 [59:30<1:15:02,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivy_Shao.jpg

 31%|███▏      | 2800/8920 [59:30<1:00:03,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Saram.jpg

 31%|███▏      | 2801/8920 [59:31<57:28,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Megan_Lai.jpg

 31%|███▏      | 2802/8920 [59:31<48:30,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Latisha_Chan.jpg

 31%|███▏      | 2803/8920 [59:32<53:27,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Fang-Liang.jpg

 31%|███▏      | 2804/8920 [59:33<1:07:54,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyndi_Wang.jpg

 31%|███▏      | 2805/8920 [59:34<1:17:29,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hsu_Wei-Ning.jpg

 31%|███▏      | 2806/8920 [59:34<1:03:05,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Liu.jpg

 31%|███▏      | 2807/8920 [59:35<1:03:28,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivian_Hsu.jpg

 31%|███▏      | 2808/8920 [59:36<1:17:24,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alyssa_Chia.jpg

 31%|███▏      | 2809/8920 [59:37<1:25:18,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_Kuo.jpg

 32%|███▏      | 2810/8920 [59:38<1:29:31,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Mao.jpg

 32%|███▏      | 2811/8920 [59:40<1:52:39,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Yi.jpg

 32%|███▏      | 2812/8920 [59:40<1:39:12,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chou_Tzu_Yu.jpg

 32%|███▏      | 2813/8920 [59:40<1:18:11,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Chou.jpg

 32%|███▏      | 2814/8920 [59:42<1:31:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jolin_Tsai.jpg

 32%|███▏      | 2815/8920 [59:43<1:31:49,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiro_Wang.jpg

 32%|███▏      | 2816/8920 [59:44<1:43:16,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicky_Wu.jpg

 32%|███▏      | 2817/8920 [59:44<1:30:58,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fei_Yu-Ching.jpg

 32%|███▏      | 2818/8920 [59:45<1:30:51,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Chen.jpg

 32%|███▏      | 2819/8920 [59:47<1:46:49,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A-Lin.jpg

 32%|███▏      | 2820/8920 [59:47<1:22:01,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richie_Jen.jpg

 32%|███▏      | 2821/8920 [59:48<1:14:02,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcus_Chang.jpg

 32%|███▏      | 2822/8920 [59:48<1:13:07,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jam_Hsiao.jpg

 32%|███▏      | 2823/8920 [59:49<59:40,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lai_Kuan-Lin.jpg

 32%|███▏      | 2824/8920 [59:49<50:07,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Tseng.jpg

 32%|███▏      | 2825/8920 [59:49<43:38,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A-Mei.jpg

 32%|███▏      | 2826/8920 [59:50<43:21,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Yi.jpg

 32%|███▏      | 2827/8920 [59:50<48:27,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Chen.jpg

 32%|███▏      | 2828/8920 [59:51<55:53,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hebe_Tien.jpg

 32%|███▏      | 2829/8920 [59:52<1:04:36,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rene_Liu.jpg

 32%|███▏      | 2830/8920 [59:52<56:12,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fong_Fei-Fei.jpg

 32%|███▏      | 2831/8920 [59:52<47:11,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Teresa_Teng.jpg

 32%|███▏      | 2832/8920 [59:53<41:34,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Yi.jpg

 32%|███▏      | 2833/8920 [59:53<36:55,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lala_Hsu.jpg

 32%|███▏      | 2834/8920 [59:53<35:31,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanna_Wang.jpg

 32%|███▏      | 2835/8920 [59:54<43:04,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashin.jpg

 32%|███▏      | 2836/8920 [59:55<56:41,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fanfan.jpg

 32%|███▏      | 2837/8920 [59:58<2:08:05,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kuo_Shu-Yao.jpg

 32%|███▏      | 2838/8920 [59:58<1:44:58,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Yu-Sheng.jpg

 32%|███▏      | 2839/8920 [59:59<1:31:26,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dino_Lee.jpg

 32%|███▏      | 2840/8920 [1:00:01<2:05:39,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bii.jpg

 32%|███▏      | 2841/8920 [1:00:02<2:11:34,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lara_Veronin.jpg

 32%|███▏      | 2842/8920 [1:00:03<1:50:50,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Megan_Lai.jpg

 32%|███▏      | 2843/8920 [1:00:03<1:26:23,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeh_Shuhua.jpg

 32%|███▏      | 2844/8920 [1:00:04<1:32:12,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai_Ko.jpg

 32%|███▏      | 2845/8920 [1:00:05<1:33:02,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Chang.jpg

 32%|███▏      | 2846/8920 [1:00:06<1:34:19,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karena_Lam.jpg

 32%|███▏      | 2847/8920 [1:00:08<2:04:54,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harlem_Yu.jpg

 32%|███▏      | 2848/8920 [1:00:11<2:57:34,  1.75s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calvin_Chen.jpg

 32%|███▏      | 2849/8920 [1:00:12<2:32:19,  1.51s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ming_Dao.jpg

 32%|███▏      | 2850/8920 [1:00:13<2:18:56,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wakin_Chau.jpg

 32%|███▏      | 2851/8920 [1:00:13<1:54:40,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bowie_Tsang.jpg

 32%|███▏      | 2852/8920 [1:00:14<1:35:22,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Lian.jpg

 32%|███▏      | 2853/8920 [1:00:15<1:27:12,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Chou.jpg

 32%|███▏      | 2854/8920 [1:00:15<1:22:51,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Lin.jpg

 32%|███▏      | 2855/8920 [1:00:16<1:16:59,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Crowd_Lu.jpg

 32%|███▏      | 2856/8920 [1:00:18<1:42:22,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lo_Ta-Yu.jpg

 32%|███▏      | 2857/8920 [1:00:19<1:50:14,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_An.jpg

 32%|███▏      | 2858/8920 [1:00:19<1:33:41,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Chang.jpg

 32%|███▏      | 2859/8920 [1:00:20<1:24:13,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_Kuo.jpg

 32%|███▏      | 2860/8920 [1:00:20<1:07:46,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_Kuo.jpg

 32%|███▏      | 2861/8920 [1:00:21<1:03:29,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Show_Lo.jpg

 32%|███▏      | 2862/8920 [1:00:21<59:29,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivian_Hsu.jpg

 32%|███▏      | 2863/8920 [1:00:22<1:00:37,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacky_Wu.jpg

 32%|███▏      | 2864/8920 [1:00:23<1:02:34,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Selina_Jen.jpg

 32%|███▏      | 2865/8920 [1:00:23<1:10:08,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alien_Huang.jpg

 32%|███▏      | 2866/8920 [1:00:24<1:20:04,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elva_Hsiao.jpg

 32%|███▏      | 2867/8920 [1:00:26<1:42:30,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freddy_Lim.jpg

 32%|███▏      | 2868/8920 [1:00:28<2:05:58,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terry_Lin.jpg

 32%|███▏      | 2869/8920 [1:00:29<2:10:00,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chyi_Chin.jpg

 32%|███▏      | 2870/8920 [1:00:30<2:03:28,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huang_An.jpg

 32%|███▏      | 2871/8920 [1:00:31<1:49:12,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Wang.jpg

 32%|███▏      | 2872/8920 [1:00:32<1:32:24,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Chu.jpg

 32%|███▏      | 2873/8920 [1:00:32<1:21:40,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faye.jpg

 32%|███▏      | 2874/8920 [1:00:33<1:34:31,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tia_Lee.jpg

 32%|███▏      | 2875/8920 [1:00:34<1:25:33,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pai_Bing-Bing.jpg

 32%|███▏      | 2876/8920 [1:00:35<1:20:27,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kingone_Wang.jpg

 32%|███▏      | 2877/8920 [1:00:35<1:21:14,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joyce_Chao.jpg

 32%|███▏      | 2878/8920 [1:00:37<1:37:03,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Chen-Yue.jpg

 32%|███▏      | 2879/8920 [1:00:38<1:37:10,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Lee.jpg

 32%|███▏      | 2880/8920 [1:00:38<1:26:44,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Chou.jpg

 32%|███▏      | 2881/8920 [1:00:39<1:21:07,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sibelle_Hu.jpg

 32%|███▏      | 2882/8920 [1:00:39<1:03:37,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anya_Wu.jpg

 32%|███▏      | 2883/8920 [1:00:40<1:00:24,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liu_Wen-Cheng.jpg

 32%|███▏      | 2884/8920 [1:00:40<1:00:48,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvia_Chang.jpg

 32%|███▏      | 2885/8920 [1:00:41<1:01:11,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Wang.jpg

 32%|███▏      | 2886/8920 [1:00:42<1:15:04,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Chiu.jpg

 32%|███▏      | 2887/8920 [1:00:42<1:01:22,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shu_Qi.jpg

 32%|███▏      | 2888/8920 [1:00:44<1:19:51,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ang_Lee.jpg

 32%|███▏      | 2889/8920 [1:00:44<1:03:37,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Takeshi_Kaneshiro.jpg

 32%|███▏      | 2891/8920 [1:00:44<42:34,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Yan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Feng_Jiao.jpg

 32%|███▏      | 2892/8920 [1:00:46<1:10:13,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Godfrey_Gao.jpg

 32%|███▏      | 2893/8920 [1:00:47<1:29:29,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Lin.jpg

 32%|███▏      | 2894/8920 [1:00:47<1:12:20,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Chao.jpg

 32%|███▏      | 2895/8920 [1:00:48<59:04,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanness_Wu.jpg

 32%|███▏      | 2896/8920 [1:00:48<48:46,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wallace_Huo.jpg

 32%|███▏      | 2897/8920 [1:00:48<42:00,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruby_Lin.jpg

 32%|███▏      | 2898/8920 [1:00:49<53:49,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Chen.jpg

 32%|███▎      | 2899/8920 [1:00:49<52:57,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Yan.jpg

 33%|███▎      | 2900/8920 [1:00:50<55:43,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janine_Chang.jpg

 33%|███▎      | 2901/8920 [1:00:50<45:46,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Chi-Ling.jpg

 33%|███▎      | 2902/8920 [1:00:51<39:40,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbie_Hsu.jpg

 33%|███▎      | 2903/8920 [1:00:51<34:45,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rainie_Yang.jpg

 33%|███▎      | 2904/8920 [1:00:51<31:48,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darren_Wang.jpg

 33%|███▎      | 2905/8920 [1:00:51<31:02,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jasper_Liu.jpg

 33%|███▎      | 2906/8920 [1:00:52<40:01,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Peng.jpg

 33%|███▎      | 2907/8920 [1:00:52<36:46,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Chen.jpg

 33%|███▎      | 2908/8920 [1:00:53<1:02:29,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kobe_Tai.jpg

 33%|███▎      | 2909/8920 [1:00:55<1:22:07,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiffany_Hsu.jpg

 33%|███▎      | 2910/8920 [1:00:56<1:34:24,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ethan_Juan.jpg

 33%|███▎      | 2911/8920 [1:00:56<1:14:10,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brigitte_Lin.jpg

 33%|███▎      | 2913/8920 [1:00:57<47:57,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivian_Sung.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Puff_Kuo.jpg

 33%|███▎      | 2914/8920 [1:00:58<1:02:30,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vic_Chou.jpg

 33%|███▎      | 2915/8920 [1:00:59<1:23:59,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joey_Wong.jpg

 33%|███▎      | 2916/8920 [1:00:59<1:05:54,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Bolin.jpg

 33%|███▎      | 2917/8920 [1:01:00<58:55,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Lin.jpg

 33%|███▎      | 2918/8920 [1:01:00<50:25,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Hsu.jpg

 33%|███▎      | 2919/8920 [1:01:01<1:06:34,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Winston_Chao.jpg

 33%|███▎      | 2920/8920 [1:01:01<54:54,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Chen.jpg

 33%|███▎      | 2921/8920 [1:01:02<46:49,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivy_Shao.jpg

 33%|███▎      | 2922/8920 [1:01:02<39:30,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Saram.jpg

 33%|███▎      | 2923/8920 [1:01:02<35:23,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betty_Ting.jpg

 33%|███▎      | 2924/8920 [1:01:02<34:16,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Liu.jpg

 33%|███▎      | 2925/8920 [1:01:03<30:35,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Yi.jpg

 33%|███▎      | 2926/8920 [1:01:03<47:00,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ady_An.jpg

 33%|███▎      | 2927/8920 [1:01:04<41:22,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jam_Hsiao.jpg

 33%|███▎      | 2928/8920 [1:01:05<1:07:14,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Yang.jpg

 33%|███▎      | 2929/8920 [1:01:06<1:16:29,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Wang_Yu.jpg

 33%|███▎      | 2930/8920 [1:01:06<1:03:19,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivy_Chen.jpg

 33%|███▎      | 2931/8920 [1:01:08<1:42:52,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelson_Lee.jpg

 33%|███▎      | 2932/8920 [1:01:09<1:27:16,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Wang.jpg

 33%|███▎      | 2933/8920 [1:01:09<1:20:24,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Tseng.jpg

 33%|███▎      | 2934/8920 [1:01:10<1:05:45,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kuo_Shu-Yao.jpg

 33%|███▎      | 2935/8920 [1:01:11<1:33:15,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fong_Fei-Fei.jpg

 33%|███▎      | 2936/8920 [1:01:12<1:12:36,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vicky_Chen.jpg

 33%|███▎      | 2937/8920 [1:01:13<1:18:47,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tseng_Jing-Hua.jpg

 33%|███▎      | 2938/8920 [1:01:13<1:15:57,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorene_Ren.jpg

 33%|███▎      | 2939/8920 [1:01:14<1:05:37,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunny_Wang.jpg

 33%|███▎      | 2940/8920 [1:01:14<1:03:04,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Sheng.jpg

 33%|███▎      | 2941/8920 [1:01:15<1:12:48,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Lin.jpg

 33%|███▎      | 2942/8920 [1:01:16<1:09:14,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandrine_Pinna.jpg

 33%|███▎      | 2943/8920 [1:01:17<1:15:59,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Yang.jpg

 33%|███▎      | 2944/8920 [1:01:17<1:09:14,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bianca_Bai.jpg

 33%|███▎      | 2945/8920 [1:01:18<1:12:11,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baron_Chen.jpg

 33%|███▎      | 2946/8920 [1:01:18<58:46,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dino_Lee.jpg

 33%|███▎      | 2947/8920 [1:01:19<49:29,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Yi.jpg

 33%|███▎      | 2948/8920 [1:01:19<48:36,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chase_Tang.jpg

 33%|███▎      | 2949/8920 [1:01:20<53:43,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hou_Hsiao-Hsien.jpg

 33%|███▎      | 2950/8920 [1:01:21<1:14:29,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lan_Cheng-Lung.jpg

 33%|███▎      | 2951/8920 [1:01:23<1:47:37,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gingle_Wang.jpg

 33%|███▎      | 2952/8920 [1:01:24<2:03:45,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Philip_Kwok.jpg

 33%|███▎      | 2953/8920 [1:01:26<2:04:43,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blackie_Chen.jpg

 33%|███▎      | 2954/8920 [1:01:26<1:41:48,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wu_Kang-Ren.jpg

 33%|███▎      | 2955/8920 [1:01:26<1:19:36,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ming_Dao.jpg

 33%|███▎      | 2956/8920 [1:01:28<1:34:03,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Chang.jpg

 33%|███▎      | 2957/8920 [1:01:29<1:53:49,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roy_Chiu.jpg

 33%|███▎      | 2958/8920 [1:01:31<2:09:17,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bowie_Tsang.jpg

 33%|███▎      | 2959/8920 [1:01:31<1:39:35,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai_Ko.jpg

 33%|███▎      | 2960/8920 [1:01:32<1:17:37,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Li.jpg

 33%|███▎      | 2961/8920 [1:01:33<1:48:58,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chang_Chen.jpg

 33%|███▎      | 2962/8920 [1:01:35<1:53:06,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tsai_Ing_Wen.jpg

 33%|███▎      | 2963/8920 [1:01:35<1:27:49,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ma_Ying_Jeou.jpg

 33%|███▎      | 2964/8920 [1:01:37<2:11:02,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bai_Chongxi.jpg

 33%|███▎      | 2965/8920 [1:01:38<2:03:03,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hu_Shih.jpg

 33%|███▎      | 2966/8920 [1:01:39<1:42:48,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Shui-Bian.jpg

 33%|███▎      | 2967/8920 [1:01:39<1:18:46,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Mei-Feng.jpg

 33%|███▎      | 2968/8920 [1:01:40<1:17:14,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Teng-Hui.jpg

 33%|███▎      | 2969/8920 [1:01:40<1:09:19,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hsiao_Bi-Khim.jpg

 33%|███▎      | 2970/8920 [1:01:41<1:09:55,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Chu.jpg

 33%|███▎      | 2971/8920 [1:01:42<1:10:28,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annette_Lu.jpg

 33%|███▎      | 2972/8920 [1:01:45<2:16:38,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kao_Chin_Su-Mei.jpg

 33%|███▎      | 2973/8920 [1:01:46<2:06:33,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christine_Chow_Ma.jpg

 33%|███▎      | 2974/8920 [1:01:46<1:45:32,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Siew.jpg

 33%|███▎      | 2975/8920 [1:01:47<1:20:31,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freddy_Lim.jpg

 33%|███▎      | 2976/8920 [1:01:47<1:16:17,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Lin.jpg

 33%|███▎      | 2977/8920 [1:01:48<1:29:04,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tai_Tzu-Ying.jpg

 33%|███▎      | 2978/8920 [1:01:49<1:21:26,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Metchie_Iii.jpg

 33%|███▎      | 2979/8920 [1:01:50<1:22:16,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Latisha_Chan.jpg

 33%|███▎      | 2980/8920 [1:01:51<1:17:36,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chan_Hao-Ching.jpg

 33%|███▎      | 2981/8920 [1:01:51<1:01:43,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chou_Tien-Chen.jpg

 33%|███▎      | 2982/8920 [1:01:51<50:23,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hsieh_Su-Wei.jpg

 33%|███▎      | 2983/8920 [1:01:52<1:10:19,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin_Yun-Ju.jpg

 33%|███▎      | 2985/8920 [1:01:53<44:35,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Lin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kuo_Hsing-Chun.jpg

 33%|███▎      | 2986/8920 [1:01:53<38:24,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Sheng.jpg

 33%|███▎      | 2987/8920 [1:01:53<35:05,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chien-Ming_Wang.jpg

 33%|███▎      | 2988/8920 [1:01:54<43:20,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blackie_Chen.jpg

 34%|███▎      | 2989/8920 [1:01:54<37:47,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Mao.jpg

 34%|███▎      | 2990/8920 [1:01:55<54:52,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pan_Cheng-Tsung.jpg

 34%|███▎      | 2991/8920 [1:01:56<56:33,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Yang.jpg

 34%|███▎      | 2992/8920 [1:01:57<1:03:50,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tseng_Chun-Hsin.jpg

 34%|███▎      | 2993/8920 [1:01:57<1:02:52,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ku_Chin-Shui.jpg

 34%|███▎      | 2994/8920 [1:01:59<1:53:48,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cheng_I-Ching.jpg

 34%|███▎      | 2995/8920 [1:02:00<1:42:02,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Tzu-Wei.jpg

 34%|███▎      | 2996/8920 [1:02:01<1:25:36,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Chi-Lin.jpg

 34%|███▎      | 2997/8920 [1:02:01<1:14:26,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wei-Yin_Chen.jpg

 34%|███▎      | 2998/8920 [1:02:01<58:49,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yen_Hsing-Su.jpg

 34%|███▎      | 2999/8920 [1:02:02<56:07,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lu_Yen-Hsun.jpg

 34%|███▎      | 3000/8920 [1:02:04<1:39:29,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tzu-Wei_Lin.jpg

 34%|███▎      | 3001/8920 [1:02:04<1:25:10,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Hung-Chieh.jpg

 34%|███▎      | 3002/8920 [1:02:05<1:18:16,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yang_Chuan-Kwang.jpg

 34%|███▎      | 3003/8920 [1:02:06<1:13:09,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yani_Tseng.jpg

 34%|███▎      | 3004/8920 [1:02:06<1:06:35,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sze_Yu.jpg

 34%|███▎      | 3005/8920 [1:02:07<1:11:22,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tan_Ya-Ting.jpg

 34%|███▎      | 3006/8920 [1:02:07<56:23,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuang_Chih-Yuan.jpg

 34%|███▎      | 3007/8920 [1:02:08<56:27,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fung_Permadi.jpg

 34%|███▎      | 3008/8920 [1:02:08<48:01,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vom_Ca-Nhum.jpg

 34%|███▎      | 3009/8920 [1:02:09<1:02:32,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cheng_Wen-Hsing.jpg

 34%|███▎      | 3010/8920 [1:02:10<1:06:10,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chi_Cheng.jpg

 34%|███▍      | 3011/8920 [1:02:11<1:06:23,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chao-Tsun_Cheng.jpg

 34%|███▍      | 3012/8920 [1:02:12<1:14:51,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Candie_Kung.jpg

 34%|███▍      | 3013/8920 [1:02:12<1:00:19,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chu_Mu-Yen.jpg

 34%|███▍      | 3014/8920 [1:02:12<50:12,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deng_Yu-Cheng.jpg

 34%|███▍      | 3015/8920 [1:02:14<1:24:49,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tang_Chih-Chun.jpg

 34%|███▍      | 3016/8920 [1:02:14<1:06:20,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Shih-Hsin.jpg

 34%|███▍      | 3018/8920 [1:02:15<44:32,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wei_Chun-Heng.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tseng_Li-Cheng.jpg

 34%|███▍      | 3019/8920 [1:02:15<49:37,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Peng-Lung.jpg

 34%|███▍      | 3020/8920 [1:02:17<1:20:42,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huang_Chih-Hsiung.jpg

 34%|███▍      | 3021/8920 [1:02:17<1:04:18,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huang_Shih-Feng.jpg

 34%|███▍      | 3022/8920 [1:02:17<51:27,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liu_Ming-Huang.jpg

 34%|███▍      | 3023/8920 [1:02:17<44:32,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Cheng-Pang.jpg

 34%|███▍      | 3024/8920 [1:02:18<52:57,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Szu-Yuan.jpg

 34%|███▍      | 3025/8920 [1:02:19<53:56,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franz_Boas.jpg

 34%|███▍      | 3026/8920 [1:02:19<45:02,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/François_Darlan.jpg

 34%|███▍      | 3027/8920 [1:02:19<43:45,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frederick_Catherwood.jpg

 34%|███▍      | 3028/8920 [1:02:20<50:00,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Ruby.jpg

 34%|███▍      | 3029/8920 [1:02:20<44:31,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Henry_Lawrence.jpg

 34%|███▍      | 3030/8920 [1:02:21<59:25,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edwin_Meese.jpg

 34%|███▍      | 3031/8920 [1:02:22<53:37,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Turnbull.jpg

 34%|███▍      | 3032/8920 [1:02:24<1:42:45,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Opel.jpg

 34%|███▍      | 3033/8920 [1:02:24<1:19:09,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spencer_Compton.jpg

 34%|███▍      | 3034/8920 [1:02:24<1:02:18,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Carney.jpg

 34%|███▍      | 3035/8920 [1:02:25<53:47,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_George_Barker.jpg

 34%|███▍      | 3036/8920 [1:02:26<1:17:35,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hudson_Fysh.jpg

 34%|███▍      | 3037/8920 [1:02:26<1:01:29,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Korolev.jpg

 34%|███▍      | 3038/8920 [1:02:27<1:03:02,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Mittelholzer.jpg

 34%|███▍      | 3039/8920 [1:02:27<51:45,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wiley_Post.jpg

 34%|███▍      | 3040/8920 [1:02:28<43:03,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noel_Wien.jpg

 34%|███▍      | 3041/8920 [1:02:29<1:02:58,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francis_Chichester.jpg

 34%|███▍      | 3042/8920 [1:02:29<50:39,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francis_Gary_Powers.jpg

 34%|███▍      | 3043/8920 [1:02:29<46:10,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Mccampbell.jpg

 34%|███▍      | 3044/8920 [1:02:30<41:30,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Bishop.jpg

 34%|███▍      | 3045/8920 [1:02:30<37:49,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeffrey_Hawkins.jpg

 34%|███▍      | 3046/8920 [1:02:30<33:21,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Boeing.jpg

 34%|███▍      | 3047/8920 [1:02:30<30:15,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pappy_Boyington.jpg

 34%|███▍      | 3048/8920 [1:02:31<28:15,  3.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Howard_Hughes.jpg

 34%|███▍      | 3049/8920 [1:02:32<59:21,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_H._Goddard.jpg

 34%|███▍      | 3050/8920 [1:02:32<50:28,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Orville_Wright.jpg

 34%|███▍      | 3051/8920 [1:02:33<45:28,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_E._Byrd.jpg

 34%|███▍      | 3052/8920 [1:02:33<42:17,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Johnson.jpg

 34%|███▍      | 3053/8920 [1:02:35<1:30:26,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Bullard.jpg

 34%|███▍      | 3054/8920 [1:02:36<1:22:29,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Batten.jpg

 34%|███▍      | 3055/8920 [1:02:37<1:45:04,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Popovich.jpg

 34%|███▍      | 3056/8920 [1:02:38<1:22:12,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilbur_Wright.jpg

 34%|███▍      | 3057/8920 [1:02:38<1:05:33,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Claude_Grahame-White.jpg

 34%|███▍      | 3058/8920 [1:02:38<1:02:45,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Doolittle.jpg

 34%|███▍      | 3059/8920 [1:02:39<1:00:22,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Ferguson.jpg

 34%|███▍      | 3060/8920 [1:02:41<1:31:49,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Morrow_Lindbergh.jpg

 34%|███▍      | 3061/8920 [1:02:42<1:42:59,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chesley_Sullenberger.jpg

 34%|███▍      | 3062/8920 [1:02:43<1:39:57,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antoine_De_Saint-Exupéry.jpg

 34%|███▍      | 3063/8920 [1:02:43<1:18:50,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuck_Yeager.jpg

 34%|███▍      | 3064/8920 [1:02:44<1:02:50,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Lindbergh.jpg

 34%|███▍      | 3065/8920 [1:02:44<51:54,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Red_Baron.jpg

 34%|███▍      | 3066/8920 [1:02:45<1:03:59,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henri_Farman.jpg

 34%|███▍      | 3067/8920 [1:02:46<1:22:52,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Fokker.jpg

 34%|███▍      | 3068/8920 [1:02:46<1:06:15,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amelia_Earhart.jpg

 34%|███▍      | 3069/8920 [1:02:47<1:04:09,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheila_Scott.jpg

 34%|███▍      | 3070/8920 [1:02:48<1:17:50,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harriet_Quimby.jpg

 34%|███▍      | 3071/8920 [1:02:48<1:03:04,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guy_Gibson.jpg

 34%|███▍      | 3072/8920 [1:02:49<1:00:49,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Sikorsky.jpg

 34%|███▍      | 3073/8920 [1:02:51<1:44:08,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bessie_Coleman.jpg

 34%|███▍      | 3074/8920 [1:02:51<1:21:10,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Wills_Douglas.jpg

 34%|███▍      | 3075/8920 [1:02:53<1:50:49,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Turner.jpg

 34%|███▍      | 3076/8920 [1:02:55<2:17:59,  1.42s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Chretien.jpg

 34%|███▍      | 3077/8920 [1:02:56<1:54:26,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Abbott.jpg

 35%|███▍      | 3078/8920 [1:02:56<1:26:48,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Bedford_Bennett.jpg

 35%|███▍      | 3079/8920 [1:02:57<1:32:58,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Tupper.jpg

 35%|███▍      | 3080/8920 [1:02:58<1:13:30,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Diefenbaker.jpg

 35%|███▍      | 3081/8920 [1:02:58<58:45,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_St._Laurent.jpg

 35%|███▍      | 3082/8920 [1:02:59<1:27:52,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Meighen.jpg

 35%|███▍      | 3083/8920 [1:03:00<1:09:18,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mackenzie_Bowell.jpg

 35%|███▍      | 3084/8920 [1:03:00<1:03:59,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Mackenzie.jpg

 35%|███▍      | 3085/8920 [1:03:00<51:43,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Thompson.jpg

 35%|███▍      | 3086/8920 [1:03:01<45:51,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Trudeau.jpg

 35%|███▍      | 3087/8920 [1:03:01<49:16,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Borden.jpg

 35%|███▍      | 3088/8920 [1:03:03<1:12:15,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lester_B._Pearson.jpg

 35%|███▍      | 3089/8920 [1:03:03<1:12:08,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mackenzie_King.jpg

 35%|███▍      | 3090/8920 [1:03:04<57:50,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Harper.jpg

 35%|███▍      | 3091/8920 [1:03:05<1:18:57,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Campbell.jpg

 35%|███▍      | 3092/8920 [1:03:05<1:10:51,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Trudeau.jpg

 35%|███▍      | 3093/8920 [1:03:06<1:06:02,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilfrid_Laurier.jpg

 35%|███▍      | 3094/8920 [1:03:07<1:06:22,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Martin.jpg

 35%|███▍      | 3095/8920 [1:03:08<1:17:24,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Clark.jpg

 35%|███▍      | 3096/8920 [1:03:08<1:01:12,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Mulroney.jpg

 35%|███▍      | 3097/8920 [1:03:08<50:02,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_A._Macdonald.jpg

 35%|███▍      | 3098/8920 [1:03:09<41:38,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Augustus_Fitzroy.jpg

 35%|███▍      | 3099/8920 [1:03:09<55:05,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frederick_North.jpg

 35%|███▍      | 3100/8920 [1:03:10<47:18,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Archibald_Primrose.jpg

 35%|███▍      | 3101/8920 [1:03:10<48:32,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Lamb.jpg

 35%|███▍      | 3102/8920 [1:03:11<42:12,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Campbell-Bannerman.jpg

 35%|███▍      | 3103/8920 [1:03:11<38:11,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Russell.jpg

 35%|███▍      | 3104/8920 [1:03:11<43:51,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Smith-Stanley.jpg

 35%|███▍      | 3105/8920 [1:03:12<37:32,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Jenkinson.jpg

 35%|███▍      | 3106/8920 [1:03:13<1:10:39,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Pelham.jpg

 35%|███▍      | 3107/8920 [1:03:14<1:10:13,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Lloyd_George.jpg

 35%|███▍      | 3108/8920 [1:03:15<1:26:30,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Petty.jpg

 35%|███▍      | 3109/8920 [1:03:15<1:07:13,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Callaghan.jpg

 35%|███▍      | 3110/8920 [1:03:16<52:59,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanley_Baldwin.jpg

 35%|███▍      | 3111/8920 [1:03:20<2:58:11,  1.84s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Grenville.jpg

 35%|███▍      | 3112/8920 [1:03:21<2:14:04,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Canning.jpg

 35%|███▍      | 3113/8920 [1:03:21<1:40:50,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Hamilton-Gordon.jpg

 35%|███▍      | 3114/8920 [1:03:22<1:27:12,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alec_Douglas-Home.jpg

 35%|███▍      | 3115/8920 [1:03:22<1:11:05,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Watson-Wentworth.jpg

 35%|███▍      | 3116/8920 [1:03:23<1:06:47,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harold_Wilson.jpg

 35%|███▍      | 3117/8920 [1:03:24<1:39:19,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bonar_Law.jpg

 35%|███▍      | 3118/8920 [1:03:25<1:33:41,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Heath.jpg

 35%|███▍      | 3119/8920 [1:03:26<1:23:48,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Pelham-Holles.jpg

 35%|███▍      | 3120/8920 [1:03:27<1:34:44,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Gladstone.jpg

 35%|███▍      | 3121/8920 [1:03:27<1:13:39,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liz_Truss.jpg

 35%|███▌      | 3122/8920 [1:03:28<1:00:13,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Pitt_The_Elder.jpg

 35%|███▌      | 3123/8920 [1:03:28<51:39,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Peel.jpg

 35%|███▌      | 3124/8920 [1:03:28<44:26,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Pitt_The_Younger.jpg

 35%|███▌      | 3125/8920 [1:03:28<39:12,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benjamin_Disraeli.jpg

 35%|███▌      | 3126/8920 [1:03:29<35:13,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Brown.jpg

 35%|███▌      | 3127/8920 [1:03:29<44:11,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harold_Macmillan.jpg

 35%|███▌      | 3128/8920 [1:03:30<37:22,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clement_Attlee.jpg

 35%|███▌      | 3129/8920 [1:03:30<32:45,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Grenville.jpg

 35%|███▌      | 3130/8920 [1:03:30<29:53,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_John_Temple.jpg

 35%|███▌      | 3131/8920 [1:03:31<37:45,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rishi_Sunak.jpg

 35%|███▌      | 3132/8920 [1:03:32<54:50,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ramsay_Macdonald.jpg

 35%|███▌      | 3133/8920 [1:03:32<46:41,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Eden.jpg

 35%|███▌      | 3134/8920 [1:03:33<56:55,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Cameron.jpg

 35%|███▌      | 3135/8920 [1:03:33<54:07,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theresa_May.jpg

 35%|███▌      | 3136/8920 [1:03:34<44:57,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Walpole.jpg

 35%|███▌      | 3137/8920 [1:03:34<38:34,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spencer_Perceval.jpg

 35%|███▌      | 3138/8920 [1:03:36<1:18:23,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Major.jpg

 35%|███▌      | 3139/8920 [1:03:36<1:02:01,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/H._H._Asquith.jpg

 35%|███▌      | 3140/8920 [1:03:36<50:05,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Johnson.jpg

 35%|███▌      | 3141/8920 [1:03:36<43:03,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Blair.jpg

 35%|███▌      | 3142/8920 [1:03:37<39:14,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Gascoyne-Cecil.jpg

 35%|███▌      | 3143/8920 [1:03:37<34:54,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Addington.jpg

 35%|███▌      | 3144/8920 [1:03:37<33:10,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Grey.jpg

 35%|███▌      | 3145/8920 [1:03:37<31:30,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keir_Starmer.jpg

 35%|███▌      | 3146/8920 [1:03:38<40:22,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Cavendish-Bentinck.jpg

 35%|███▌      | 3147/8920 [1:03:38<36:26,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Wellesley.jpg

 35%|███▌      | 3148/8920 [1:03:39<32:10,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margaret_Thatcher.jpg

 35%|███▌      | 3149/8920 [1:03:39<41:24,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neville_Chamberlain.jpg

 35%|███▌      | 3150/8920 [1:03:40<47:54,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Balfour.jpg

 35%|███▌      | 3151/8920 [1:03:41<53:28,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Winston_Churchill.jpg

 35%|███▌      | 3152/8920 [1:03:41<54:29,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/W._O._Bentley.jpg

 35%|███▌      | 3153/8920 [1:03:43<1:26:51,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Chapman.jpg

 35%|███▌      | 3154/8920 [1:03:44<1:23:35,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lionel_Martin.jpg

 35%|███▌      | 3155/8920 [1:03:44<1:04:57,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Lyons.jpg

 35%|███▌      | 3156/8920 [1:03:44<53:51,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Chevrolet.jpg

 35%|███▌      | 3157/8920 [1:03:45<47:01,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soichiro_Honda.jpg

 35%|███▌      | 3158/8920 [1:03:46<1:04:45,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alec_Issigonis.jpg

 35%|███▌      | 3159/8920 [1:03:46<1:02:38,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ettore_Bugatti.jpg

 35%|███▌      | 3160/8920 [1:03:47<52:26,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ferruccio_Lamborghini.jpg

 35%|███▌      | 3161/8920 [1:03:47<46:17,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Armand_Peugeot.jpg

 35%|███▌      | 3162/8920 [1:03:49<1:19:49,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Édouard_Michelin.jpg

 35%|███▌      | 3163/8920 [1:03:49<1:03:20,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akio_Toyoda.jpg

 35%|███▌      | 3164/8920 [1:03:49<59:35,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ferdinand_Porsche.jpg

 35%|███▌      | 3165/8920 [1:03:50<1:11:40,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolaus_Otto.jpg

 35%|███▌      | 3166/8920 [1:03:53<2:00:50,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harlow_Curtice.jpg

 36%|███▌      | 3167/8920 [1:03:53<1:31:23,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Ferrari.jpg

 36%|███▌      | 3168/8920 [1:03:54<1:21:53,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Royce.jpg

 36%|███▌      | 3169/8920 [1:03:54<1:08:17,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Benz.jpg

 36%|███▌      | 3170/8920 [1:03:54<56:27,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Rolls.jpg

 36%|███▌      | 3171/8920 [1:03:55<52:26,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elon_Musk.jpg

 36%|███▌      | 3172/8920 [1:03:56<1:24:41,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Ford.jpg

 36%|███▌      | 3173/8920 [1:03:57<1:07:31,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gottlieb_Daimler.jpg

 36%|███▌      | 3174/8920 [1:03:59<1:38:21,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/August_Horch.jpg

 36%|███▌      | 3175/8920 [1:03:59<1:29:35,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Diesel.jpg

 36%|███▌      | 3176/8920 [1:04:01<1:40:54,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Chrysler.jpg

 36%|███▌      | 3177/8920 [1:04:03<2:09:20,  1.35s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_Michelin.jpg

 36%|███▌      | 3178/8920 [1:04:03<1:48:26,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Deakin.jpg

 36%|███▌      | 3179/8920 [1:04:03<1:22:00,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Curtin.jpg

 36%|███▌      | 3180/8920 [1:04:04<1:12:04,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Hawke.jpg

 36%|███▌      | 3181/8920 [1:04:05<1:07:42,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Fraser.jpg

 36%|███▌      | 3182/8920 [1:04:05<56:30,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Fisher.jpg

 36%|███▌      | 3183/8920 [1:04:05<45:55,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edmund_Barton.jpg

 36%|███▌      | 3184/8920 [1:04:05<38:44,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Albanese.jpg

 36%|███▌      | 3185/8920 [1:04:07<1:06:36,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Keating.jpg

 36%|███▌      | 3186/8920 [1:04:07<1:02:43,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Menzies.jpg

 36%|███▌      | 3187/8920 [1:04:08<55:05,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Howard.jpg

 36%|███▌      | 3188/8920 [1:04:08<59:41,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Morrison.jpg

 36%|███▌      | 3189/8920 [1:04:10<1:16:49,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Sessions.jpg

 36%|███▌      | 3190/8920 [1:04:10<1:02:38,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edmund_Randolph.jpg

 36%|███▌      | 3191/8920 [1:04:11<1:17:55,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Holder.jpg

 36%|███▌      | 3192/8920 [1:04:12<1:23:38,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Merrick_Garland.jpg

 36%|███▌      | 3193/8920 [1:04:12<1:06:43,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loretta_Lynch.jpg

 36%|███▌      | 3194/8920 [1:04:13<54:00,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_F._Kennedy.jpg

 36%|███▌      | 3195/8920 [1:04:13<46:04,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valery_Kubasov.jpg

 36%|███▌      | 3196/8920 [1:04:13<40:05,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronald_Mcnair.jpg

 36%|███▌      | 3197/8920 [1:04:14<36:12,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Astronaut_Michael_Collins.jpg

 36%|███▌      | 3198/8920 [1:04:14<33:08,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Garneau.jpg

 36%|███▌      | 3199/8920 [1:04:14<39:06,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Glenn.jpg

 36%|███▌      | 3200/8920 [1:04:15<44:21,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Hadfield.jpg

 36%|███▌      | 3201/8920 [1:04:15<40:44,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Lovell.jpg

 36%|███▌      | 3202/8920 [1:04:16<35:14,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Borman.jpg

 36%|███▌      | 3203/8920 [1:04:16<42:07,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Shepard.jpg

 36%|███▌      | 3204/8920 [1:04:16<35:55,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buzz_Aldrin.jpg

 36%|███▌      | 3205/8920 [1:04:17<33:47,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mae_Jemison.jpg

 36%|███▌      | 3206/8920 [1:04:17<31:14,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Armstrong.jpg

 36%|███▌      | 3207/8920 [1:04:17<30:02,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Kelly.jpg

 36%|███▌      | 3208/8920 [1:04:18<28:24,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Leonov.jpg

 36%|███▌      | 3209/8920 [1:04:18<26:06,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_A._Walker.jpg

 36%|███▌      | 3210/8920 [1:04:18<26:30,  3.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Gagarin.jpg

 36%|███▌      | 3211/8920 [1:04:19<44:44,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Carpenter.jpg

 36%|███▌      | 3212/8920 [1:04:21<1:23:50,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Ride.jpg

 36%|███▌      | 3213/8920 [1:04:21<1:05:40,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Tereshkova.jpg

 36%|███▌      | 3214/8920 [1:04:21<56:18,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mehmet_Ali_Ağca.jpg

 36%|███▌      | 3215/8920 [1:04:22<57:11,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gavrilo_Princip.jpg

 36%|███▌      | 3216/8920 [1:04:22<50:18,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Earl_Ray.jpg

 36%|███▌      | 3217/8920 [1:04:23<51:12,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sirhan_Sirhan.jpg

 36%|███▌      | 3218/8920 [1:04:24<59:12,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Harvey_Oswald.jpg

 36%|███▌      | 3219/8920 [1:04:24<57:21,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_J._Guiteau.jpg

 36%|███▌      | 3220/8920 [1:04:25<1:06:30,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Bellingham.jpg

 36%|███▌      | 3221/8920 [1:04:27<1:23:03,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Wilkes_Booth.jpg

 36%|███▌      | 3222/8920 [1:04:27<1:16:30,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_S._Burroughs.jpg

 36%|███▌      | 3223/8920 [1:04:27<1:02:49,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akira_Toriyama.jpg

 36%|███▌      | 3224/8920 [1:04:28<53:13,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tarsila_Do_Amaral.jpg

 36%|███▌      | 3225/8920 [1:04:29<1:01:30,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Wesley_Dow.jpg

 36%|███▌      | 3226/8920 [1:04:29<56:04,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Hockney.jpg

 36%|███▌      | 3227/8920 [1:04:30<59:31,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ai_Weiwei.jpg

 36%|███▌      | 3228/8920 [1:04:30<49:13,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andy_Warhol.jpg

 36%|███▌      | 3229/8920 [1:04:30<40:44,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Enwonwu.jpg

 36%|███▌      | 3230/8920 [1:04:31<35:34,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Max.jpg

 36%|███▌      | 3231/8920 [1:04:32<1:02:00,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stan_Lee.jpg

 36%|███▌      | 3232/8920 [1:04:32<49:49,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Botero.jpg

 36%|███▌      | 3233/8920 [1:04:34<1:27:32,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Blake.jpg

 36%|███▋      | 3234/8920 [1:04:34<1:07:57,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Repin.jpg

 36%|███▋      | 3235/8920 [1:04:35<1:12:45,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoko_Ono.jpg

 36%|███▋      | 3236/8920 [1:04:35<58:01,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Kirby.jpg

 36%|███▋      | 3237/8920 [1:04:36<47:06,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Haring.jpg

 36%|███▋      | 3238/8920 [1:04:36<49:01,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Polanyi.jpg

 36%|███▋      | 3239/8920 [1:04:36<43:50,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Virchow.jpg

 36%|███▋      | 3240/8920 [1:04:37<40:35,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davidson_Black.jpg

 36%|███▋      | 3241/8920 [1:04:37<44:28,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raymond_Dart.jpg

 36%|███▋      | 3242/8920 [1:04:38<39:28,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margaret_Mead.jpg

 36%|███▋      | 3243/8920 [1:04:38<35:50,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Leakey.jpg

 36%|███▋      | 3244/8920 [1:04:39<41:41,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Goodall.jpg

 36%|███▋      | 3245/8920 [1:04:39<36:29,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Schoolcraft.jpg

 36%|███▋      | 3246/8920 [1:04:39<35:14,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Leakey.jpg

 36%|███▋      | 3247/8920 [1:04:40<1:00:59,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Jellicoe.jpg

 36%|███▋      | 3248/8920 [1:04:41<1:01:18,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Dönitz.jpg

 36%|███▋      | 3249/8920 [1:04:42<1:05:20,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Farragut.jpg

 36%|███▋      | 3250/8920 [1:04:42<51:57,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gaspard_De_Coligny.jpg

 36%|███▋      | 3251/8920 [1:04:43<1:02:17,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Comte_De_Grasse.jpg

 36%|███▋      | 3252/8920 [1:04:43<52:15,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Afonso_De_Albuquerque.jpg

 36%|███▋      | 3253/8920 [1:04:44<43:52,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reinhard_Scheer.jpg

 36%|███▋      | 3254/8920 [1:04:44<49:32,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Piet_Heyn.jpg

 36%|███▋      | 3255/8920 [1:04:45<43:21,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grace_Hopper.jpg

 37%|███▋      | 3256/8920 [1:04:46<1:09:41,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chester_Nimitz.jpg

 37%|███▋      | 3257/8920 [1:04:47<1:25:54,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Bligh.jpg

 37%|███▋      | 3258/8920 [1:04:47<1:06:07,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lord_Mountbatten.jpg

 37%|███▋      | 3259/8920 [1:04:48<1:05:17,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_B._Cushing.jpg

 37%|███▋      | 3260/8920 [1:04:49<1:08:21,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Dewey.jpg

 37%|███▋      | 3261/8920 [1:04:50<1:21:38,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Beatty.jpg

 37%|███▋      | 3262/8920 [1:04:51<1:21:48,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maarten_Tromp.jpg

 37%|███▋      | 3263/8920 [1:04:51<1:05:12,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samuel_Hood.jpg

 37%|███▋      | 3264/8920 [1:04:52<53:07,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isoroku_Yamamoto.jpg

 37%|███▋      | 3265/8920 [1:04:52<45:41,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Horatio_Nelson.jpg

 37%|███▋      | 3266/8920 [1:04:53<1:05:48,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francis_Drake.jpg

 37%|███▋      | 3267/8920 [1:04:53<54:51,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Morphy.jpg

 37%|███▋      | 3268/8920 [1:04:54<45:17,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Botvinnik.jpg

 37%|███▋      | 3269/8920 [1:04:54<41:25,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magnus_Carlsen.jpg

 37%|███▋      | 3270/8920 [1:04:55<51:25,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Raúl_Capablanca.jpg

 37%|███▋      | 3271/8920 [1:04:55<43:09,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Karpov.jpg

 37%|███▋      | 3272/8920 [1:04:55<44:20,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Fischer.jpg

 37%|███▋      | 3273/8920 [1:04:56<44:45,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Kasparov.jpg

 37%|███▋      | 3274/8920 [1:04:57<1:09:10,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cixi.jpg

 37%|███▋      | 3275/8920 [1:04:58<55:42,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mao_Zedong.jpg

 37%|███▋      | 3276/8920 [1:04:59<1:18:49,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hu_Yaobang.jpg

 37%|███▋      | 3277/8920 [1:05:00<1:13:23,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavlo_Lazarenko.jpg

 37%|███▋      | 3278/8920 [1:05:00<59:23,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyudmila_Pavlichenko.jpg

 37%|███▋      | 3279/8920 [1:05:01<1:08:09,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stepan_Bandera.jpg

 37%|███▋      | 3280/8920 [1:05:01<55:28,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Kurylenko.jpg

 37%|███▋      | 3281/8920 [1:05:01<44:59,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milla_Jovovich.jpg

 37%|███▋      | 3282/8920 [1:05:02<52:41,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Volodymyr_Zelensky.jpg

 37%|███▋      | 3283/8920 [1:05:03<56:57,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larisa_Latynina.jpg

 37%|███▋      | 3284/8920 [1:05:04<1:00:15,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wladimir_Klitschko.jpg

 37%|███▋      | 3285/8920 [1:05:04<48:01,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petro_Poroshenko.jpg

 37%|███▋      | 3286/8920 [1:05:04<41:37,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Yanukovych.jpg

 37%|███▋      | 3287/8920 [1:05:05<52:39,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonid_Brezhnev.jpg

 37%|███▋      | 3288/8920 [1:05:06<55:48,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Golda_Meir.jpg

 37%|███▋      | 3289/8920 [1:05:06<47:36,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitali_Klitschko.jpg

 37%|███▋      | 3290/8920 [1:05:07<1:00:52,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Yushchenko.jpg

 37%|███▋      | 3291/8920 [1:05:08<1:03:27,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Trotsky.jpg

 37%|███▋      | 3292/8920 [1:05:09<1:13:46,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hu_Jintao.jpg

 37%|███▋      | 3293/8920 [1:05:09<57:58,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiang_Zemin.jpg

 37%|███▋      | 3294/8920 [1:05:09<48:51,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhao_Ziyang.jpg

 37%|███▋      | 3295/8920 [1:05:09<42:45,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deng_Xiaoping.jpg

 37%|███▋      | 3296/8920 [1:05:10<38:22,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Kai-Shek.jpg

 37%|███▋      | 3297/8920 [1:05:10<32:56,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hua_Guofeng.jpg

 37%|███▋      | 3298/8920 [1:05:10<31:15,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xi_Jinping.jpg

 37%|███▋      | 3299/8920 [1:05:11<29:39,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adolf_Hitler.jpg

 37%|███▋      | 3300/8920 [1:05:11<40:24,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Paul.jpg

 37%|███▋      | 3301/8920 [1:05:11<35:12,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bessie_Coleman.jpg

 37%|███▋      | 3302/8920 [1:05:12<32:01,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haile_Selassie.jpg

 37%|███▋      | 3303/8920 [1:05:12<29:37,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mao_Zedong.jpg

 37%|███▋      | 3304/8920 [1:05:12<29:01,  3.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Campbell.jpg

 37%|███▋      | 3305/8920 [1:05:13<39:21,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benito_Mussolini.jpg

 37%|███▋      | 3306/8920 [1:05:14<49:08,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonio_Gramsci.jpg

 37%|███▋      | 3307/8920 [1:05:14<45:22,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queen_Elizabeth.jpg

 37%|███▋      | 3308/8920 [1:05:14<42:42,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Wills_Douglas.jpg

 37%|███▋      | 3309/8920 [1:05:15<38:02,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elsa_Schiaparelli.jpg

 37%|███▋      | 3310/8920 [1:05:15<42:58,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelly_Sachs.jpg

 37%|███▋      | 3311/8920 [1:05:16<40:23,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fanny_Brice.jpg

 37%|███▋      | 3312/8920 [1:05:16<38:40,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_P._Kennedy.jpg

 37%|███▋      | 3313/8920 [1:05:16<35:32,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colonel_Sanders.jpg

 37%|███▋      | 3314/8920 [1:05:17<30:45,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Eden.jpg

 37%|███▋      | 3315/8920 [1:05:17<38:25,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._R._R._Tolkien.jpg

 37%|███▋      | 3316/8920 [1:05:17<33:13,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Perón.jpg

 37%|███▋      | 3317/8920 [1:05:18<41:58,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dorothy_Parker.jpg

 37%|███▋      | 3318/8920 [1:05:19<42:14,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Logie_Baird.jpg

 37%|███▋      | 3319/8920 [1:05:19<39:41,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Massey.jpg

 37%|███▋      | 3320/8920 [1:05:19<36:23,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bucky_Harris.jpg

 37%|███▋      | 3321/8920 [1:05:19<32:20,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mae_West.jpg

 37%|███▋      | 3322/8920 [1:05:20<29:09,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Faulkner.jpg

 37%|███▋      | 3323/8920 [1:05:20<27:00,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lester_B._Pearson.jpg

 37%|███▋      | 3324/8920 [1:05:21<36:08,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rogers_Hornsby.jpg

 37%|███▋      | 3325/8920 [1:05:21<31:38,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/D._H._Lawrence.jpg

 37%|███▋      | 3326/8920 [1:05:21<28:23,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ty_Cobb.jpg

 37%|███▋      | 3327/8920 [1:05:23<1:15:58,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolph_Valentino.jpg

 37%|███▋      | 3328/8920 [1:05:24<1:21:51,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hans_Luther.jpg

 37%|███▋      | 3329/8920 [1:05:25<1:16:42,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imre_Nagy.jpg

 37%|███▋      | 3330/8920 [1:05:26<1:27:05,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Merian_C._Cooper.jpg

 37%|███▋      | 3331/8920 [1:05:27<1:16:46,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Borotra.jpg

 37%|███▋      | 3332/8920 [1:05:28<1:29:36,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Terry.jpg

 37%|███▋      | 3333/8920 [1:05:29<1:46:25,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathaniel_Niles.jpg

 37%|███▋      | 3334/8920 [1:05:30<1:45:10,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/C.V._Raman.jpg

 37%|███▋      | 3335/8920 [1:05:32<2:09:14,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Rose.jpg

 37%|███▋      | 3336/8920 [1:05:34<2:20:57,  1.51s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hoagy_Carmichael.jpg

 37%|███▋      | 3337/8920 [1:05:35<2:02:26,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dorothy_Day.jpg

 37%|███▋      | 3338/8920 [1:05:36<1:49:55,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarrie_Grimmett.jpg

 37%|███▋      | 3339/8920 [1:05:38<2:04:53,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grover_Cleveland_Alexander.jpg

 37%|███▋      | 3340/8920 [1:05:40<2:19:26,  1.50s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gracie_Allen.jpg

 37%|███▋      | 3341/8920 [1:05:41<2:23:33,  1.54s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ford_Frick.jpg

 37%|███▋      | 3342/8920 [1:05:44<2:53:25,  1.87s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oscar_Hammerstein_Ii.jpg

 37%|███▋      | 3343/8920 [1:05:45<2:40:28,  1.73s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bert_Lahr.jpg

 37%|███▋      | 3344/8920 [1:05:46<2:15:41,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rupert_Brooke.jpg

 38%|███▊      | 3345/8920 [1:05:47<1:58:22,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herbert_Marcuse.jpg

 38%|███▊      | 3346/8920 [1:05:51<3:16:30,  2.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frankie_Frisch.jpg

 38%|███▊      | 3347/8920 [1:05:52<2:35:50,  1.68s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarence_Kummer.jpg

 38%|███▊      | 3348/8920 [1:05:52<1:57:00,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Lukas.jpg

 38%|███▊      | 3349/8920 [1:05:56<3:10:52,  2.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Knott.jpg

 38%|███▊      | 3350/8920 [1:05:57<2:32:15,  1.64s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._Paul_Getty.jpg

 38%|███▊      | 3351/8920 [1:05:57<1:56:40,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_Breton.jpg

 38%|███▊      | 3352/8920 [1:05:58<2:02:55,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maximilian_Kolbe.jpg

 38%|███▊      | 3353/8920 [1:06:00<2:16:26,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jock_Hutchison.jpg

 38%|███▊      | 3354/8920 [1:06:01<2:03:31,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leo_Diegel.jpg

 38%|███▊      | 3355/8920 [1:06:02<1:35:26,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_George_Barker.jpg

 38%|███▊      | 3356/8920 [1:06:02<1:17:17,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buster_Keaton.jpg

 38%|███▊      | 3357/8920 [1:06:02<1:00:56,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Allen_Dulles.jpg

 38%|███▊      | 3358/8920 [1:06:03<57:30,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludwig_Erhard.jpg

 38%|███▊      | 3359/8920 [1:06:06<2:02:56,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oswald_Mosley.jpg

 38%|███▊      | 3360/8920 [1:06:06<1:33:56,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hudson_Fysh.jpg

 38%|███▊      | 3361/8920 [1:06:06<1:15:57,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Connelly.jpg

 38%|███▊      | 3362/8920 [1:06:08<1:28:40,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/W._O._Bentley.jpg

 38%|███▊      | 3363/8920 [1:06:08<1:10:47,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Wolfe.jpg

 38%|███▊      | 3364/8920 [1:06:08<1:00:49,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reinhold_Niebuhr.jpg

 38%|███▊      | 3365/8920 [1:06:09<53:05,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Howard_Hanson.jpg

 38%|███▊      | 3366/8920 [1:06:10<1:21:44,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sammy_Davis_Sr..jpg

 38%|███▊      | 3367/8920 [1:06:11<1:05:09,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Horkheimer.jpg

 38%|███▊      | 3368/8920 [1:06:11<1:00:55,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonio_Segni.jpg

 38%|███▊      | 3369/8920 [1:06:13<1:24:50,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Miller.jpg

 38%|███▊      | 3370/8920 [1:06:13<1:18:18,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergei_Prokofiev.jpg

 38%|███▊      | 3371/8920 [1:06:14<1:11:53,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Laval.jpg

 38%|███▊      | 3372/8920 [1:06:14<58:16,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilder_Penfield.jpg

 38%|███▊      | 3373/8920 [1:06:16<1:17:13,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooks_Atkinson.jpg

 38%|███▊      | 3374/8920 [1:06:17<1:30:18,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hazel_Hotchkiss_Wightman.jpg

 38%|███▊      | 3375/8920 [1:06:18<1:43:11,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Earl_Sande.jpg

 38%|███▊      | 3376/8920 [1:06:19<1:36:18,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fredric_March.jpg

 38%|███▊      | 3377/8920 [1:06:21<1:47:07,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Barnes.jpg

 38%|███▊      | 3378/8920 [1:06:21<1:22:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sidney_Holland.jpg

 38%|███▊      | 3379/8920 [1:06:21<1:15:28,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erich_Maria_Remarque.jpg

 38%|███▊      | 3380/8920 [1:06:23<1:25:35,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Crerar.jpg

 38%|███▊      | 3381/8920 [1:06:24<1:23:42,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fletcher_Henderson.jpg

 38%|███▊      | 3382/8920 [1:06:24<1:07:49,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kazimierz_Fajans.jpg

 38%|███▊      | 3383/8920 [1:06:25<1:25:14,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Piston.jpg

 38%|███▊      | 3384/8920 [1:06:26<1:09:42,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elmer_Rice.jpg

 38%|███▊      | 3385/8920 [1:06:27<1:14:17,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shemp_Howard.jpg

 38%|███▊      | 3386/8920 [1:06:27<1:05:46,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gertrude_Lawrence.jpg

 38%|███▊      | 3387/8920 [1:06:28<1:14:43,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Robeson.jpg

 38%|███▊      | 3388/8920 [1:06:29<1:30:40,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerald_Patterson.jpg

 38%|███▊      | 3389/8920 [1:06:30<1:12:47,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Heidegger.jpg

 38%|███▊      | 3390/8920 [1:06:30<57:56,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Weiss.jpg

 38%|███▊      | 3391/8920 [1:06:31<1:18:26,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rajendra_Prasad.jpg

 38%|███▊      | 3392/8920 [1:06:32<1:01:25,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rube_Marquard.jpg

 38%|███▊      | 3393/8920 [1:06:32<52:37,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Diefenbaker.jpg

 38%|███▊      | 3394/8920 [1:06:32<49:29,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Curtin.jpg

 38%|███▊      | 3395/8920 [1:06:33<42:26,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Warner_Baxter.jpg

 38%|███▊      | 3396/8920 [1:06:33<37:56,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Halas.jpg

 38%|███▊      | 3397/8920 [1:06:34<44:44,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Ponsford.jpg

 38%|███▊      | 3398/8920 [1:06:34<49:39,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/R._Norris_Williams.jpg

 38%|███▊      | 3399/8920 [1:06:35<51:21,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/François_Faber.jpg

 38%|███▊      | 3400/8920 [1:06:36<1:08:58,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edvard_Beneš.jpg

 38%|███▊      | 3401/8920 [1:06:38<1:37:39,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Palmiro_Togliatti.jpg

 38%|███▊      | 3402/8920 [1:06:39<1:39:23,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Muni.jpg

 38%|███▊      | 3403/8920 [1:06:39<1:17:11,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludwig_Wittgenstein.jpg

 38%|███▊      | 3404/8920 [1:06:40<1:22:41,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfonso_Xiii.jpg

 38%|███▊      | 3405/8920 [1:06:41<1:06:32,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Wilding.jpg

 38%|███▊      | 3406/8920 [1:06:41<1:04:11,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/D._S._Senanayake.jpg

 38%|███▊      | 3407/8920 [1:06:42<1:15:56,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pieter_Menten.jpg

 38%|███▊      | 3408/8920 [1:06:43<59:33,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Piet_Moeskops.jpg

 38%|███▊      | 3409/8920 [1:06:44<1:26:27,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Malone.jpg

 38%|███▊      | 3410/8920 [1:06:45<1:23:38,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helen_Hayes.jpg

 38%|███▊      | 3411/8920 [1:06:45<1:07:37,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wallace_Beery.jpg

 38%|███▊      | 3412/8920 [1:06:46<1:06:26,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Mittelholzer.jpg

 38%|███▊      | 3413/8920 [1:06:47<1:00:35,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Booth.jpg

 38%|███▊      | 3414/8920 [1:06:47<49:02,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Honegger.jpg

 38%|███▊      | 3415/8920 [1:06:48<1:11:24,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Bottomley.jpg

 38%|███▊      | 3416/8920 [1:06:48<55:57,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Molla_Mallory.jpg

 38%|███▊      | 3417/8920 [1:06:50<1:23:45,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jozef_Tiso.jpg

 38%|███▊      | 3418/8920 [1:06:52<2:02:05,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronald_Colman.jpg

 38%|███▊      | 3419/8920 [1:06:53<1:51:50,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Pessoa.jpg

 38%|███▊      | 3420/8920 [1:06:54<1:24:46,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Polanyi.jpg

 38%|███▊      | 3421/8920 [1:06:54<1:07:22,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Ryan.jpg

 38%|███▊      | 3422/8920 [1:06:56<1:38:31,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Ormandy.jpg

 38%|███▊      | 3423/8920 [1:06:56<1:16:03,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerome_Kern.jpg

 38%|███▊      | 3424/8920 [1:06:56<1:00:16,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriela_Mistral.jpg

 38%|███▊      | 3425/8920 [1:06:58<1:19:19,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/B.R._Ambedkar.jpg

 38%|███▊      | 3426/8920 [1:06:59<1:42:00,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hans_Frank.jpg

 38%|███▊      | 3427/8920 [1:07:00<1:28:30,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emil_Jannings.jpg

 38%|███▊      | 3428/8920 [1:07:01<1:43:02,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxwell_Anderson.jpg

 38%|███▊      | 3429/8920 [1:07:02<1:35:48,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cy_Denneny.jpg

 38%|███▊      | 3430/8920 [1:07:05<2:11:47,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Cukor.jpg

 38%|███▊      | 3431/8920 [1:07:05<1:51:03,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Copland.jpg

 38%|███▊      | 3432/8920 [1:07:07<1:53:07,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karel_Čapek.jpg

 38%|███▊      | 3433/8920 [1:07:07<1:24:53,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Cagney.jpg

 38%|███▊      | 3434/8920 [1:07:07<1:06:33,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Armour.jpg

 39%|███▊      | 3435/8920 [1:07:07<56:32,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Hainsworth.jpg

 39%|███▊      | 3436/8920 [1:07:08<1:00:15,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Cocteau.jpg

 39%|███▊      | 3437/8920 [1:07:11<1:48:10,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chico_Marx.jpg

 39%|███▊      | 3438/8920 [1:07:11<1:21:57,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Benny.jpg

 39%|███▊      | 3439/8920 [1:07:13<1:47:14,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erle_Stanley_Gardner.jpg

 39%|███▊      | 3440/8920 [1:07:13<1:23:11,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Howard_Florey.jpg

 39%|███▊      | 3441/8920 [1:07:14<1:30:53,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spencer_Tracy.jpg

 39%|███▊      | 3442/8920 [1:07:15<1:31:54,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irene_Dunne.jpg

 39%|███▊      | 3443/8920 [1:07:16<1:14:30,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Draža_Mihailović.jpg

 39%|███▊      | 3444/8920 [1:07:17<1:35:09,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Mccarthy.jpg

 39%|███▊      | 3446/8920 [1:07:18<56:26,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Tilden.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_B._Mayer.jpg

 39%|███▊      | 3447/8920 [1:07:18<48:47,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Jolson.jpg

 39%|███▊      | 3448/8920 [1:07:20<1:32:41,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curly_Lambeau.jpg

 39%|███▊      | 3449/8920 [1:07:21<1:21:59,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joyce_Kilmer.jpg

 39%|███▊      | 3450/8920 [1:07:21<1:16:37,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cole_Porter.jpg

 39%|███▊      | 3451/8920 [1:07:22<1:10:23,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Raúl_Capablanca.jpg

 39%|███▊      | 3452/8920 [1:07:22<57:21,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Ziegler.jpg

 39%|███▊      | 3453/8920 [1:07:23<1:08:32,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Haley.jpg

 39%|███▊      | 3454/8920 [1:07:24<57:48,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Bormann.jpg

 39%|███▊      | 3455/8920 [1:07:24<47:55,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Fraser.jpg

 39%|███▊      | 3456/8920 [1:07:24<40:23,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Allen.jpg

 39%|███▉      | 3457/8920 [1:07:27<1:33:34,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Friedrich_Paulus.jpg

 39%|███▉      | 3458/8920 [1:07:28<1:40:07,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rafael_Trujillo.jpg

 39%|███▉      | 3459/8920 [1:07:29<1:27:04,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abe_Attell.jpg

 39%|███▉      | 3460/8920 [1:07:29<1:23:05,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarence_Demar.jpg

 39%|███▉      | 3461/8920 [1:07:30<1:20:25,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Johnson.jpg

 39%|███▉      | 3462/8920 [1:07:31<1:10:38,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Dönitz.jpg

 39%|███▉      | 3463/8920 [1:07:32<1:23:34,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darius_Milhaud.jpg

 39%|███▉      | 3464/8920 [1:07:33<1:38:11,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wiley_Post.jpg

 39%|███▉      | 3465/8920 [1:07:34<1:29:52,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bud_Abbott.jpg

 39%|███▉      | 3466/8920 [1:07:35<1:19:01,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georges_Vezina.jpg

 39%|███▉      | 3467/8920 [1:07:35<1:03:29,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miles_Dempsey.jpg

 39%|███▉      | 3468/8920 [1:07:35<50:07,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tris_Speaker.jpg

 39%|███▉      | 3469/8920 [1:07:36<43:07,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tarsila_Do_Amaral.jpg

 39%|███▉      | 3470/8920 [1:07:36<40:44,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Dos_Passos.jpg

 39%|███▉      | 3471/8920 [1:07:38<1:33:33,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Hindemith.jpg

 39%|███▉      | 3472/8920 [1:07:39<1:13:36,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manuel_Roxas.jpg

 39%|███▉      | 3473/8920 [1:07:39<1:09:18,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_P._Laurel.jpg

 39%|███▉      | 3474/8920 [1:07:40<1:09:26,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Mclaglen.jpg

 39%|███▉      | 3475/8920 [1:07:41<1:09:28,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gloria_Swanson.jpg

 39%|███▉      | 3476/8920 [1:07:42<1:14:58,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmie_Rodgers.jpg

 39%|███▉      | 3477/8920 [1:07:42<58:04,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/António_De_Oliveira_Salazar.jpg

 39%|███▉      | 3478/8920 [1:07:42<46:53,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Humphrey_Bogart.jpg

 39%|███▉      | 3479/8920 [1:07:42<38:42,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_O'Neill.jpg

 39%|███▉      | 3480/8920 [1:07:43<33:27,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noel_Wien.jpg

 39%|███▉      | 3481/8920 [1:07:53<4:58:20,  3.29s/it]

❌ Failed to download https://www.onthisday.com/images/people/walter-hagen.jpg: _ssl.c:983: The handshake operation timed out

 39%|███▉      | 3482/8920 [1:08:20<15:58:11, 10.57s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Legs_Diamond.jpg

 39%|███▉      | 3483/8920 [1:08:21<11:28:09,  7.59s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Laughton.jpg

 39%|███▉      | 3484/8920 [1:08:21<8:09:28,  5.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Kesselring.jpg

 39%|███▉      | 3485/8920 [1:08:21<5:48:49,  3.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florence_Price.jpg

 39%|███▉      | 3486/8920 [1:08:22<4:12:25,  2.79s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Ulbricht.jpg

 39%|███▉      | 3487/8920 [1:08:22<3:03:06,  2.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Costello.jpg

 39%|███▉      | 3488/8920 [1:08:24<2:54:53,  1.93s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Groucho_Marx.jpg

 39%|███▉      | 3489/8920 [1:08:24<2:12:37,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thornton_Wilder.jpg

 39%|███▉      | 3490/8920 [1:08:24<1:39:31,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clas_Thunberg.jpg

 39%|███▉      | 3491/8920 [1:08:27<2:09:13,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Archibald_Macleish.jpg

 39%|███▉      | 3492/8920 [1:08:27<1:40:19,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rube_Goldberg.jpg

 39%|███▉      | 3493/8920 [1:08:29<2:03:08,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Norbert_Wiener.jpg

 39%|███▉      | 3494/8920 [1:08:31<2:22:43,  1.58s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hattie_Mcdaniel.jpg

 39%|███▉      | 3495/8920 [1:08:32<1:58:55,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Carlton_Gilbert.jpg

 39%|███▉      | 3496/8920 [1:08:32<1:39:50,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ante_Pavelić.jpg

 39%|███▉      | 3497/8920 [1:08:33<1:19:02,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Eagan.jpg

 39%|███▉      | 3498/8920 [1:08:33<1:17:14,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moe_Howard.jpg

 39%|███▉      | 3499/8920 [1:08:35<1:30:02,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heinrich_Himmler.jpg

 39%|███▉      | 3500/8920 [1:08:35<1:17:03,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Sessions.jpg

 39%|███▉      | 3501/8920 [1:08:36<1:02:51,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ira_Gershwin.jpg

 39%|███▉      | 3502/8920 [1:08:37<1:09:14,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Nabokov.jpg

 39%|███▉      | 3503/8920 [1:08:37<1:06:49,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maurice_Mcloughlin.jpg

 39%|███▉      | 3504/8920 [1:08:38<57:35,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Zworykin.jpg

 39%|███▉      | 3505/8920 [1:08:40<1:47:37,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katherine_Mansfield.jpg

 39%|███▉      | 3506/8920 [1:08:41<1:35:38,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agnes_Moorehead.jpg

 39%|███▉      | 3507/8920 [1:08:41<1:14:08,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elpidio_Quirino.jpg

 39%|███▉      | 3508/8920 [1:08:41<58:08,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noël_Coward.jpg

 39%|███▉      | 3509/8920 [1:08:42<1:00:02,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Goebbels.jpg

 39%|███▉      | 3510/8920 [1:08:43<1:00:31,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dion_Fortune.jpg

 39%|███▉      | 3511/8920 [1:08:43<58:39,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duke_Ellington.jpg

 39%|███▉      | 3512/8920 [1:08:44<51:39,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Basil_Rathbone.jpg

 39%|███▉      | 3513/8920 [1:08:44<43:00,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prasanta_Chandra_Mahalanobis.jpg

 39%|███▉      | 3514/8920 [1:08:44<35:56,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Vi.jpg

 39%|███▉      | 3515/8920 [1:08:45<47:17,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Dempsey.jpg

 39%|███▉      | 3516/8920 [1:08:46<57:04,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Lippmann.jpg

 39%|███▉      | 3517/8920 [1:08:46<45:47,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raymond_Dart.jpg

 39%|███▉      | 3518/8920 [1:08:47<1:07:31,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Calder.jpg

 39%|███▉      | 3519/8920 [1:08:48<54:21,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ragnar_Granit.jpg

 39%|███▉      | 3520/8920 [1:08:48<52:35,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Karloff.jpg

 39%|███▉      | 3521/8920 [1:08:49<44:46,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxwell_Perkins.jpg

 39%|███▉      | 3522/8920 [1:08:49<39:30,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elijah_Muhammad.jpg

 39%|███▉      | 3523/8920 [1:08:49<34:30,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Watson-Watt.jpg

 40%|███▉      | 3524/8920 [1:08:49<30:35,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Édouard_Daladier.jpg

 40%|███▉      | 3525/8920 [1:08:50<37:54,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Chadwick.jpg

 40%|███▉      | 3526/8920 [1:08:50<32:57,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miguel_Ángel_Asturias.jpg

 40%|███▉      | 3527/8920 [1:08:50<30:07,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trygve_Lie.jpg

 40%|███▉      | 3528/8920 [1:08:51<29:21,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hermann_Goering.jpg

 40%|███▉      | 3529/8920 [1:08:51<27:39,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Patch.jpg

 40%|███▉      | 3530/8920 [1:08:52<39:07,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margaret_Mitchell.jpg

 40%|███▉      | 3531/8920 [1:08:52<45:31,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Casey_Stengel.jpg

 40%|███▉      | 3532/8920 [1:08:54<1:00:40,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Jodl.jpg

 40%|███▉      | 3533/8920 [1:08:55<1:23:43,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frédéric_Joliot-Curie.jpg

 40%|███▉      | 3534/8920 [1:08:56<1:27:43,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Fleming.jpg

 40%|███▉      | 3535/8920 [1:08:57<1:32:54,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilfred_Owen.jpg

 40%|███▉      | 3536/8920 [1:08:58<1:27:08,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lead_Belly.jpg

 40%|███▉      | 3537/8920 [1:08:58<1:08:11,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hack_Wilson.jpg

 40%|███▉      | 3538/8920 [1:08:59<55:43,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Menzies.jpg

 40%|███▉      | 3539/8920 [1:08:59<55:12,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davidson_Black.jpg

 40%|███▉      | 3540/8920 [1:09:00<46:15,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adlai_Stevenson_Ii.jpg

 40%|███▉      | 3541/8920 [1:09:00<42:03,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jomo_Kenyatta.jpg

 40%|███▉      | 3542/8920 [1:09:00<44:44,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudolf_Hess.jpg

 40%|███▉      | 3543/8920 [1:09:03<1:27:08,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgy_Zhukov.jpg

 40%|███▉      | 3544/8920 [1:09:03<1:08:12,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Bishop.jpg

 40%|███▉      | 3545/8920 [1:09:03<54:53,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gavrilo_Princip.jpg

 40%|███▉      | 3546/8920 [1:09:03<44:14,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Collins.jpg

 40%|███▉      | 3547/8920 [1:09:04<39:49,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paavo_Nurmi.jpg

 40%|███▉      | 3548/8920 [1:09:04<44:10,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lavrentiy_Beria.jpg

 40%|███▉      | 3549/8920 [1:09:05<39:27,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernest_Hemingway.jpg

 40%|███▉      | 3550/8920 [1:09:05<35:44,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Lloyd.jpg

 40%|███▉      | 3551/8920 [1:09:06<43:53,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wallis_Simpson.jpg

 40%|███▉      | 3552/8920 [1:09:06<38:05,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernard_Montgomery.jpg

 40%|███▉      | 3553/8920 [1:09:07<49:41,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._Edgar_Hoover.jpg

 40%|███▉      | 3554/8920 [1:09:07<53:59,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Gabor.jpg

 40%|███▉      | 3555/8920 [1:09:08<47:53,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eleanor_Roosevelt.jpg

 40%|███▉      | 3556/8920 [1:09:08<41:38,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Pickford.jpg

 40%|███▉      | 3557/8920 [1:09:09<46:07,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/F._Scott_Fitzgerald.jpg

 40%|███▉      | 3558/8920 [1:09:09<41:12,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ezra_Pound.jpg

 40%|███▉      | 3559/8920 [1:09:09<35:19,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harold_Macmillan.jpg

 40%|███▉      | 3560/8920 [1:09:10<30:50,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T._S._Eliot.jpg

 40%|███▉      | 3561/8920 [1:09:10<38:54,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stan_Laurel.jpg

 40%|███▉      | 3562/8920 [1:09:10<34:14,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Gershwin.jpg

 40%|███▉      | 3563/8920 [1:09:11<29:59,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_E._Byrd.jpg

 40%|███▉      | 3564/8920 [1:09:13<1:13:48,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clement_Attlee.jpg

 40%|███▉      | 3565/8920 [1:09:13<1:09:30,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frederick_Terman.jpg

 40%|███▉      | 3566/8920 [1:09:14<55:08,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diego_Rivera.jpg

 40%|███▉      | 3567/8920 [1:09:14<45:29,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coco_The_Clown.jpg

 40%|████      | 3568/8920 [1:09:14<39:37,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Astaire.jpg

 40%|████      | 3569/8920 [1:09:15<47:24,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Vygotsky.jpg

 40%|████      | 3570/8920 [1:09:15<41:15,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Iii.jpg

 40%|████      | 3571/8920 [1:09:16<42:29,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fatima_Jinnah.jpg

 40%|████      | 3572/8920 [1:09:16<46:40,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Douglas_Fairbanks.jpg

 40%|████      | 3573/8920 [1:09:17<39:18,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erwin_Rommel.jpg

 40%|████      | 3574/8920 [1:09:17<33:24,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harlow_Curtice.jpg

 40%|████      | 3575/8920 [1:09:17<28:54,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorenz_Hart.jpg

 40%|████      | 3576/8920 [1:09:18<52:39,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pearl_S._Buck.jpg

 40%|████      | 3577/8920 [1:09:18<42:47,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorge_Luis_Borges.jpg

 40%|████      | 3578/8920 [1:09:19<37:40,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franz_Kafka.jpg

 40%|████      | 3579/8920 [1:09:19<33:53,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Bullard.jpg

 40%|████      | 3580/8920 [1:09:20<38:52,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vidkun_Quisling.jpg

 40%|████      | 3581/8920 [1:09:20<34:28,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niels_Bohr.jpg

 40%|████      | 3582/8920 [1:09:20<31:44,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/E._B._White.jpg

 40%|████      | 3583/8920 [1:09:21<35:58,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/C._S._Lewis.jpg

 40%|████      | 3584/8920 [1:09:21<31:11,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Gardel.jpg

 40%|████      | 3585/8920 [1:09:22<39:43,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agatha_Christie.jpg

 40%|████      | 3586/8920 [1:09:22<38:48,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_"Machine_Gun"_Kelly.jpg

 40%|████      | 3587/8920 [1:09:22<35:32,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bertolt_Brecht.jpg

 40%|████      | 3588/8920 [1:09:23<42:03,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcel_Duchamp.jpg

 40%|████      | 3589/8920 [1:09:24<1:02:21,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyrus_Eaton.jpg

 40%|████      | 3590/8920 [1:09:24<53:21,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcus_Garvey.jpg

 40%|████      | 3591/8920 [1:09:25<1:01:53,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Best.jpg

 40%|████      | 3592/8920 [1:09:26<51:24,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bess_Truman.jpg

 40%|████      | 3593/8920 [1:09:28<1:34:44,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inez_Milholland.jpg

 40%|████      | 3594/8920 [1:09:28<1:14:58,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will_Durant.jpg

 40%|████      | 3595/8920 [1:09:29<1:08:18,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Earl_Warren.jpg

 40%|████      | 3596/8920 [1:09:30<1:06:59,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Belmondo.jpg

 40%|████      | 3597/8920 [1:09:30<53:33,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coco_Chanel.jpg

 40%|████      | 3598/8920 [1:09:30<47:12,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aldous_Huxley.jpg

 40%|████      | 3599/8920 [1:09:30<39:28,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfred_Hitchcock.jpg

 40%|████      | 3600/8920 [1:09:32<1:00:32,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irving_Berlin.jpg

 40%|████      | 3601/8920 [1:09:32<49:27,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_S._Patton.jpg

 40%|████      | 3602/8920 [1:09:32<40:22,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Durante.jpg

 40%|████      | 3603/8920 [1:09:33<46:34,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edwin_Hubble.jpg

 40%|████      | 3604/8920 [1:09:34<1:04:04,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/P._L._Travers.jpg

 40%|████      | 3605/8920 [1:09:35<59:19,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Collins.jpg

 40%|████      | 3606/8920 [1:09:36<1:07:54,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frederick_Banting.jpg

 40%|████      | 3607/8920 [1:09:36<53:32,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhou_Enlai.jpg

 40%|████      | 3608/8920 [1:09:37<1:16:04,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_De_Gaulle.jpg

 40%|████      | 3609/8920 [1:09:37<59:49,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Doolittle.jpg

 40%|████      | 3610/8920 [1:09:38<48:53,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dwight_D._Eisenhower.jpg

 40%|████      | 3611/8920 [1:09:38<40:50,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiang_Kai-Shek.jpg

 40%|████      | 3612/8920 [1:09:38<34:36,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Ferrari.jpg

 41%|████      | 3613/8920 [1:09:39<42:56,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Ford.jpg

 41%|████      | 3614/8920 [1:09:39<45:23,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huey_Long.jpg

 41%|████      | 3615/8920 [1:09:40<38:50,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarence_Birdseye.jpg

 41%|████      | 3616/8920 [1:09:40<32:54,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Chaplin.jpg

 41%|████      | 3617/8920 [1:09:44<1:56:44,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Khrushchev.jpg

 41%|████      | 3618/8920 [1:09:44<1:39:42,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Ferguson.jpg

 41%|████      | 3619/8920 [1:09:46<1:54:33,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hideki_Tojo.jpg

 41%|████      | 3620/8920 [1:09:47<1:39:09,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Golda_Meir.jpg

 41%|████      | 3621/8920 [1:09:47<1:17:15,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josip_Broz_Tito.jpg

 41%|████      | 3622/8920 [1:09:47<59:56,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Capone.jpg

 41%|████      | 3623/8920 [1:09:47<48:14,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Newman.jpg

 41%|████      | 3624/8920 [1:09:48<41:51,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chester_Nimitz.jpg

 41%|████      | 3625/8920 [1:09:48<44:36,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vijaya_Lakshmi_Pandit.jpg

 41%|████      | 3626/8920 [1:09:49<53:53,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oliver_Hardy.jpg

 41%|████      | 3627/8920 [1:09:50<1:00:53,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francisco_Franco.jpg

 41%|████      | 3628/8920 [1:09:50<53:40,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_T._Scopes.jpg

 41%|████      | 3629/8920 [1:09:51<59:21,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Maynard_Keynes.jpg

 41%|████      | 3630/8920 [1:09:51<48:04,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Percy_Lavon_Julian.jpg

 41%|████      | 3631/8920 [1:09:52<39:58,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lord_Mountbatten.jpg

 41%|████      | 3632/8920 [1:09:52<34:56,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Thorpe.jpg

 41%|████      | 3633/8920 [1:09:54<1:07:55,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Durant.jpg

 41%|████      | 3634/8920 [1:09:54<54:47,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joachim_Von_Ribbentrop.jpg

 41%|████      | 3635/8920 [1:09:55<1:14:30,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antoine_De_Saint-Exupéry.jpg

 41%|████      | 3636/8920 [1:09:55<58:33,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arnold_J._Toynbee.jpg

 41%|████      | 3637/8920 [1:09:56<47:07,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Norman_Bethune.jpg

 41%|████      | 3638/8920 [1:09:58<1:19:59,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Capra.jpg

 41%|████      | 3639/8920 [1:09:58<1:04:00,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marian_Anderson.jpg

 41%|████      | 3640/8920 [1:09:58<51:22,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leslie_Groves.jpg

 41%|████      | 3641/8920 [1:09:58<43:32,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Fitzgerald_Kennedy.jpg

 41%|████      | 3642/8920 [1:09:59<55:34,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ina_Boyle.jpg

 41%|████      | 3643/8920 [1:10:00<45:12,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ho_Chi_Minh.jpg

 41%|████      | 3644/8920 [1:10:00<38:39,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Viii.jpg

 41%|████      | 3645/8920 [1:10:00<33:57,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Archibald_Mcindoe.jpg

 41%|████      | 3646/8920 [1:10:01<50:51,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Buchalter.jpg

 41%|████      | 3647/8920 [1:10:01<44:56,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_"Lucky"_Luciano.jpg

 41%|████      | 3648/8920 [1:10:02<38:13,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enid_Blyton.jpg

 41%|████      | 3649/8920 [1:10:02<32:46,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Mallory.jpg

 41%|████      | 3650/8920 [1:10:02<32:41,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T._E._Lawrence.jpg

 41%|████      | 3651/8920 [1:10:03<43:31,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Pasternak.jpg

 41%|████      | 3652/8920 [1:10:03<36:06,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cecilia_Payne-Gaposchkin.jpg

 41%|████      | 3653/8920 [1:10:04<33:14,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jawaharlal_Nehru.jpg

 41%|████      | 3654/8920 [1:10:04<30:27,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dodie_Smith.jpg

 41%|████      | 3655/8920 [1:10:04<27:28,  3.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suzanne_Lenglen.jpg

 41%|████      | 3656/8920 [1:10:05<40:46,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Red_Baron.jpg

 41%|████      | 3657/8920 [1:10:06<55:37,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vyacheslav_Molotov.jpg

 41%|████      | 3658/8920 [1:10:06<44:51,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Bradley.jpg

 41%|████      | 3659/8920 [1:10:06<37:44,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erwin_Schrödinger.jpg

 41%|████      | 3660/8920 [1:10:07<34:13,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irène_Joliot-Curie.jpg

 41%|████      | 3661/8920 [1:10:07<29:19,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Vi.jpg

 41%|████      | 3662/8920 [1:10:08<38:01,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgia_O'Keeffe.jpg

 41%|████      | 3663/8920 [1:10:08<41:07,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Foster_Dulles.jpg

 41%|████      | 3664/8920 [1:10:08<37:35,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Fokker.jpg

 41%|████      | 3665/8920 [1:10:09<40:39,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amelia_Earhart.jpg

 41%|████      | 3666/8920 [1:10:09<39:04,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isoroku_Yamamoto.jpg

 41%|████      | 3668/8920 [1:10:11<50:41,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgios_Papanicolaou.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leó_Szilárd.jpg

 41%|████      | 3669/8920 [1:10:11<41:25,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bugs_Moran.jpg

 41%|████      | 3670/8920 [1:10:13<1:04:30,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soong_Mei-Ling.jpg

 41%|████      | 3671/8920 [1:10:13<1:02:55,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Mayakovsky.jpg

 41%|████      | 3672/8920 [1:10:14<56:20,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Sikorsky.jpg

 41%|████      | 3673/8920 [1:10:14<45:59,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Babe_Ruth.jpg

 41%|████      | 3674/8920 [1:10:14<37:58,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Truman.jpg

 41%|████      | 3675/8920 [1:10:15<34:17,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Like_Nastya.jpg

 41%|████      | 3676/8920 [1:10:15<32:04,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_George.jpg

 41%|████      | 3677/8920 [1:10:15<30:36,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gwen_Stefani.jpg

 41%|████      | 3678/8920 [1:10:15<29:56,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ajay_Devgan.jpg

 41%|████      | 3679/8920 [1:10:17<1:04:04,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robbie_Williams.jpg

 41%|████▏     | 3680/8920 [1:10:17<53:02,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Courier.jpg

 41%|████▏     | 3681/8920 [1:10:18<52:16,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tedros_Adhanom_Ghebreyesus.jpg

 41%|████▏     | 3682/8920 [1:10:18<43:24,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will.I.Am.jpg

 41%|████▏     | 3683/8920 [1:10:19<36:19,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billie_Joe_Armstrong.jpg

 41%|████▏     | 3684/8920 [1:10:19<43:29,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kylie_Minogue.jpg

 41%|████▏     | 3685/8920 [1:10:20<38:36,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dr._Dre.jpg

 41%|████▏     | 3686/8920 [1:10:20<36:50,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shakira.jpg

 41%|████▏     | 3687/8920 [1:10:20<33:44,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_Weisz.jpg

 41%|████▏     | 3688/8920 [1:10:20<30:36,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicole_Kidman.jpg

 41%|████▏     | 3689/8920 [1:10:21<28:32,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Slash.jpg

 41%|████▏     | 3690/8920 [1:10:22<41:33,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Chappelle.jpg

 41%|████▏     | 3691/8920 [1:10:22<38:07,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Venus_Williams.jpg

 41%|████▏     | 3692/8920 [1:10:23<1:07:08,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mackenzie_Scott.jpg

 41%|████▏     | 3693/8920 [1:10:24<54:13,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petro_Poroshenko.jpg

 41%|████▏     | 3694/8920 [1:10:24<46:34,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jewel_Kilcher.jpg

 41%|████▏     | 3695/8920 [1:10:25<52:48,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Chastain.jpg

 41%|████▏     | 3696/8920 [1:10:26<1:09:26,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ralf_Schumacher.jpg

 41%|████▏     | 3697/8920 [1:10:27<1:13:19,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Carlos.jpg

 41%|████▏     | 3698/8920 [1:10:28<1:26:23,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julie_Bowen.jpg

 41%|████▏     | 3699/8920 [1:10:29<1:19:10,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sanath_Jayasuriya.jpg

 41%|████▏     | 3700/8920 [1:10:31<1:34:06,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_O'Toole.jpg

 41%|████▏     | 3701/8920 [1:10:34<2:22:10,  1.63s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Riddick_Bowe.jpg

 42%|████▏     | 3702/8920 [1:10:34<2:03:28,  1.42s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tina_Fey.jpg

 42%|████▏     | 3703/8920 [1:10:35<1:45:09,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amélie_Mauresmo.jpg

 42%|████▏     | 3704/8920 [1:10:36<1:36:45,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abiy_Ahmed.jpg

 42%|████▏     | 3705/8920 [1:10:36<1:15:11,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Camporese.jpg

 42%|████▏     | 3706/8920 [1:10:38<1:26:31,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Orlando_Bloom.jpg

 42%|████▏     | 3707/8920 [1:10:39<1:34:49,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Khaled.jpg

 42%|████▏     | 3708/8920 [1:10:40<1:38:22,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Mccarthy.jpg

 42%|████▏     | 3709/8920 [1:10:40<1:15:57,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laura_Dern.jpg

 42%|████▏     | 3710/8920 [1:10:41<1:01:35,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Legend.jpg

 42%|████▏     | 3711/8920 [1:10:41<49:21,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aishwarya_Rai.jpg

 42%|████▏     | 3712/8920 [1:10:41<43:28,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chadwick_Boseman.jpg

 42%|████▏     | 3713/8920 [1:10:42<48:19,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Guetta.jpg

 42%|████▏     | 3714/8920 [1:10:43<52:43,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmx.jpg

 42%|████▏     | 3715/8920 [1:10:44<57:15,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shonda_Rhimes.jpg

 42%|████▏     | 3716/8920 [1:10:47<2:15:58,  1.57s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenneth_Mitchell.jpg

 42%|████▏     | 3717/8920 [1:10:47<1:42:25,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arantxa_Sánchez_Vicario.jpg

 42%|████▏     | 3718/8920 [1:10:49<1:45:23,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Gosling.jpg

 42%|████▏     | 3719/8920 [1:10:50<1:45:57,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luke_Perry.jpg

 42%|████▏     | 3720/8920 [1:10:52<2:00:49,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cillian_Murphy.jpg

 42%|████▏     | 3721/8920 [1:10:54<2:09:55,  1.50s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miranda_Hart.jpg

 42%|████▏     | 3722/8920 [1:10:55<2:04:09,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Scott.jpg

 42%|████▏     | 3723/8920 [1:10:55<1:32:38,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brandon_Sanderson.jpg

 42%|████▏     | 3724/8920 [1:10:55<1:10:59,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Carney.jpg

 42%|████▏     | 3725/8920 [1:10:56<1:03:05,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Stiller.jpg

 42%|████▏     | 3726/8920 [1:10:56<50:00,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rahul_Dravid.jpg

 42%|████▏     | 3727/8920 [1:10:56<41:17,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashens.jpg

 42%|████▏     | 3728/8920 [1:10:57<36:26,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Metzen.jpg

 42%|████▏     | 3729/8920 [1:10:57<40:16,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Michael_Mcdonagh.jpg

 42%|████▏     | 3730/8920 [1:10:57<34:44,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terrell_Owens.jpg

 42%|████▏     | 3731/8920 [1:10:58<30:45,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bradley_Cooper.jpg

 42%|████▏     | 3732/8920 [1:10:58<29:03,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Dorsey.jpg

 42%|████▏     | 3733/8920 [1:10:58<27:19,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronnie_O'Sullivan.jpg

 42%|████▏     | 3734/8920 [1:10:58<25:02,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcus_Luttrell.jpg

 42%|████▏     | 3735/8920 [1:10:59<38:10,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_O'Driscoll.jpg

 42%|████▏     | 3736/8920 [1:11:00<34:13,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Stanford.jpg

 42%|████▏     | 3737/8920 [1:11:00<40:41,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Huber.jpg

 42%|████▏     | 3738/8920 [1:11:00<35:14,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anke_Huber.jpg

 42%|████▏     | 3739/8920 [1:11:01<44:10,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marat_Safin.jpg

 42%|████▏     | 3740/8920 [1:11:01<37:09,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rick_Astley.jpg

 42%|████▏     | 3741/8920 [1:11:02<31:24,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Holmes.jpg

 42%|████▏     | 3742/8920 [1:11:02<28:59,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/January_Jones.jpg

 42%|████▏     | 3743/8920 [1:11:02<28:07,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Renner.jpg

 42%|████▏     | 3744/8920 [1:11:03<28:58,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Moss.jpg

 42%|████▏     | 3745/8920 [1:11:03<35:46,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lei_Jun.jpg

 42%|████▏     | 3746/8920 [1:11:04<58:00,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerard_Butler.jpg

 42%|████▏     | 3747/8920 [1:11:05<58:44,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Toms.jpg

 42%|████▏     | 3748/8920 [1:11:05<46:24,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Zahn.jpg

 42%|████▏     | 3749/8920 [1:11:06<48:20,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xavi.jpg

 42%|████▏     | 3750/8920 [1:11:07<53:39,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Ruffalo.jpg

 42%|████▏     | 3751/8920 [1:11:07<44:16,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Moorer.jpg

 42%|████▏     | 3752/8920 [1:11:07<37:09,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drew_Brees.jpg

 42%|████▏     | 3753/8920 [1:11:08<40:50,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Strahan.jpg

 42%|████▏     | 3754/8920 [1:11:08<34:51,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Muir.jpg

 42%|████▏     | 3755/8920 [1:11:08<30:45,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricky_Ponting.jpg

 42%|████▏     | 3756/8920 [1:11:09<27:51,  3.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calvin_Borel.jpg

 42%|████▏     | 3757/8920 [1:11:09<34:50,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Nash.jpg

 42%|████▏     | 3758/8920 [1:11:09<30:29,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Ortiz.jpg

 42%|████▏     | 3759/8920 [1:11:10<41:40,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedro_Sánchez.jpg

 42%|████▏     | 3760/8920 [1:11:11<43:35,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hristo_Stoichkov.jpg

 42%|████▏     | 3761/8920 [1:11:11<36:45,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Phillips.jpg

 42%|████▏     | 3762/8920 [1:11:11<34:05,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samantha_Bee.jpg

 42%|████▏     | 3763/8920 [1:11:12<29:40,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Silverman.jpg

 42%|████▏     | 3764/8920 [1:11:12<36:03,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kid_Rock.jpg

 42%|████▏     | 3765/8920 [1:11:13<37:33,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isla_Fisher.jpg

 42%|████▏     | 3766/8920 [1:11:13<40:23,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Day.jpg

 42%|████▏     | 3767/8920 [1:11:13<34:14,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stéphane_Charbonnier.jpg

 42%|████▏     | 3768/8920 [1:11:14<30:41,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glenn_Mcgrath.jpg

 42%|████▏     | 3769/8920 [1:11:14<27:18,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Game_[Jayceon_Taylor].jpg

 42%|████▏     | 3770/8920 [1:11:15<1:01:12,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Bateman.jpg

 42%|████▏     | 3771/8920 [1:11:16<1:03:53,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Weiland.jpg

 42%|████▏     | 3772/8920 [1:11:17<51:07,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Symonds.jpg

 42%|████▏     | 3773/8920 [1:11:17<43:17,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Faris.jpg

 42%|████▏     | 3774/8920 [1:11:17<36:40,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurent-Désiré_Kabila.jpg

 42%|████▏     | 3775/8920 [1:11:18<44:56,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Favreau.jpg

 42%|████▏     | 3776/8920 [1:11:18<39:23,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Ainslie.jpg

 42%|████▏     | 3777/8920 [1:11:20<1:03:04,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ja_Rule.jpg

 42%|████▏     | 3778/8920 [1:11:20<1:06:31,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Houser.jpg

 42%|████▏     | 3779/8920 [1:11:21<1:02:06,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Big_Show.jpg

 42%|████▏     | 3780/8920 [1:11:21<48:58,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Rockwell.jpg

 42%|████▏     | 3781/8920 [1:11:21<40:02,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Colman.jpg

 42%|████▏     | 3782/8920 [1:11:22<34:03,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Duval.jpg

 42%|████▏     | 3783/8920 [1:11:22<29:39,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiësto.jpg

 42%|████▏     | 3784/8920 [1:11:23<37:19,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junichi_Masuda.jpg

 42%|████▏     | 3785/8920 [1:11:23<42:36,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Foxx.jpg

 42%|████▏     | 3786/8920 [1:11:24<37:53,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maggie_Gyllenhaal.jpg

 42%|████▏     | 3787/8920 [1:11:24<42:21,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Wojcicki.jpg

 42%|████▏     | 3788/8920 [1:11:25<1:02:50,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_García.jpg

 42%|████▏     | 3789/8920 [1:11:26<1:08:52,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Hammond.jpg

 42%|████▏     | 3790/8920 [1:11:28<1:28:59,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Travis_Barker.jpg

 42%|████▎     | 3791/8920 [1:11:29<1:23:36,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kiefer_Sutherland.jpg

 43%|████▎     | 3792/8920 [1:11:31<1:55:55,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jude_Law.jpg

 43%|████▎     | 3793/8920 [1:11:32<1:51:15,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christina_Aguilera.jpg

 43%|████▎     | 3794/8920 [1:11:34<1:51:43,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Paulson.jpg

 43%|████▎     | 3795/8920 [1:11:34<1:29:02,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brendan_Fraser.jpg

 43%|████▎     | 3796/8920 [1:11:36<1:53:30,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Ellis.jpg

 43%|████▎     | 3797/8920 [1:11:38<2:06:26,  1.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sinead_O'Connor.jpg

 43%|████▎     | 3798/8920 [1:11:38<1:45:44,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sammy_Sosa.jpg

 43%|████▎     | 3799/8920 [1:11:39<1:22:18,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Cruz.jpg

 43%|████▎     | 3800/8920 [1:11:39<1:08:26,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Kurylenko.jpg

 43%|████▎     | 3801/8920 [1:11:41<1:21:59,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Morrison.jpg

 43%|████▎     | 3802/8920 [1:11:41<1:15:58,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Griffey_Jr..jpg

 43%|████▎     | 3803/8920 [1:11:42<1:00:19,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Romero.jpg

 43%|████▎     | 3804/8920 [1:11:42<1:00:26,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/R._Kelly.jpg

 43%|████▎     | 3805/8920 [1:11:43<1:04:17,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Flint.jpg

 43%|████▎     | 3806/8920 [1:11:43<53:09,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ichiro_Suzuki.jpg

 43%|████▎     | 3807/8920 [1:11:44<43:26,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Matthews.jpg

 43%|████▎     | 3808/8920 [1:11:44<37:32,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Pierce.jpg

 43%|████▎     | 3809/8920 [1:11:45<40:26,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karrie_Webb.jpg

 43%|████▎     | 3810/8920 [1:11:45<51:26,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Huber.jpg

 43%|████▎     | 3811/8920 [1:11:46<58:51,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Bale.jpg

 43%|████▎     | 3812/8920 [1:11:48<1:27:43,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jana_Novotna.jpg

 43%|████▎     | 3813/8920 [1:11:49<1:10:38,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Puff_Daddy.jpg

 43%|████▎     | 3814/8920 [1:11:49<1:10:31,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Owen_Wilson.jpg

 43%|████▎     | 3815/8920 [1:11:50<55:10,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Schwimmer.jpg

 43%|████▎     | 3816/8920 [1:11:51<1:14:11,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonah_Lomu.jpg

 43%|████▎     | 3817/8920 [1:11:52<1:24:59,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosamund_Pike.jpg

 43%|████▎     | 3818/8920 [1:11:53<1:14:47,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Connelly.jpg

 43%|████▎     | 3819/8920 [1:11:53<59:32,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zooey_Deschanel.jpg

 43%|████▎     | 3820/8920 [1:11:53<47:24,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Holly_Madison.jpg

 43%|████▎     | 3821/8920 [1:11:54<39:29,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_Mcadams.jpg

 43%|████▎     | 3822/8920 [1:11:54<34:06,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mel_C.jpg

 43%|████▎     | 3823/8920 [1:11:56<1:06:03,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Secretariat.jpg

 43%|████▎     | 3824/8920 [1:11:57<1:16:14,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Floyd.jpg

 43%|████▎     | 3826/8920 [1:11:57<47:34,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kurt_Angle.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brad_Paisley.jpg

 43%|████▎     | 3827/8920 [1:11:58<1:00:15,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Blake.jpg

 43%|████▎     | 3828/8920 [1:12:01<1:44:53,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefan_Edberg.jpg

 43%|████▎     | 3829/8920 [1:12:01<1:25:33,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shane_Warne.jpg

 43%|████▎     | 3830/8920 [1:12:02<1:32:03,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jake_Gyllenhaal.jpg

 43%|████▎     | 3831/8920 [1:12:03<1:19:34,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Heche.jpg

 43%|████▎     | 3832/8920 [1:12:04<1:28:17,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Brandis.jpg

 43%|████▎     | 3833/8920 [1:12:06<1:34:41,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heather_Mills.jpg

 43%|████▎     | 3834/8920 [1:12:07<1:52:32,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Lopes.jpg

 43%|████▎     | 3835/8920 [1:12:08<1:38:40,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Marie.jpg

 43%|████▎     | 3836/8920 [1:12:09<1:25:00,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Pujols.jpg

 43%|████▎     | 3837/8920 [1:12:11<1:47:04,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Duhamel.jpg

 43%|████▎     | 3838/8920 [1:12:11<1:21:12,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Grohl.jpg

 43%|████▎     | 3839/8920 [1:12:11<1:04:50,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Becker.jpg

 43%|████▎     | 3840/8920 [1:12:13<1:27:55,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/François_Pienaar.jpg

 43%|████▎     | 3841/8920 [1:12:15<1:56:36,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shah_Rukh_Khan.jpg

 43%|████▎     | 3842/8920 [1:12:16<1:46:23,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heath_Ledger.jpg

 43%|████▎     | 3843/8920 [1:12:17<1:29:50,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Urban.jpg

 43%|████▎     | 3844/8920 [1:12:18<1:34:14,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanessa_Lachey.jpg

 43%|████▎     | 3845/8920 [1:12:19<1:27:58,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Wheldon.jpg

 43%|████▎     | 3846/8920 [1:12:20<1:21:38,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Trudeau.jpg

 43%|████▎     | 3847/8920 [1:12:20<1:18:36,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Druckmann.jpg

 43%|████▎     | 3848/8920 [1:12:22<1:34:44,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salman_Khan.jpg

 43%|████▎     | 3849/8920 [1:12:23<1:37:19,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petteri_Orpo.jpg

 43%|████▎     | 3850/8920 [1:12:24<1:28:17,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seth_Meyers.jpg

 43%|████▎     | 3851/8920 [1:12:24<1:09:38,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dido.jpg

 43%|████▎     | 3852/8920 [1:12:25<1:08:07,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay-Z.jpg

 43%|████▎     | 3853/8920 [1:12:27<1:39:38,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Rafferty.jpg

 43%|████▎     | 3854/8920 [1:12:28<1:25:11,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Felipe_Vi.jpg

 43%|████▎     | 3855/8920 [1:12:29<1:34:35,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shawn_Michaels.jpg

 43%|████▎     | 3856/8920 [1:12:29<1:13:32,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monica_Seles.jpg

 43%|████▎     | 3857/8920 [1:12:31<1:23:51,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tyra_Banks.jpg

 43%|████▎     | 3858/8920 [1:12:31<1:08:44,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Houser.jpg

 43%|████▎     | 3859/8920 [1:12:31<54:35,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milla_Jovovich.jpg

 43%|████▎     | 3860/8920 [1:12:33<1:08:53,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Kimmel.jpg

 43%|████▎     | 3861/8920 [1:12:34<1:30:17,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lin-Manuel_Miranda.jpg

 43%|████▎     | 3862/8920 [1:12:35<1:10:06,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Sweeney.jpg

 43%|████▎     | 3863/8920 [1:12:35<1:04:44,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedro_Martínez.jpg

 43%|████▎     | 3864/8920 [1:12:36<1:09:19,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cuba_Gooding_Jr..jpg

 43%|████▎     | 3865/8920 [1:12:37<1:02:25,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashton_Kutcher.jpg

 43%|████▎     | 3866/8920 [1:12:37<1:04:06,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthew_Mcconaughey.jpg

 43%|████▎     | 3867/8920 [1:12:39<1:34:18,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chen_Kun.jpg

 43%|████▎     | 3868/8920 [1:12:40<1:22:05,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Philip_Seymour_Hoffman.jpg

 43%|████▎     | 3869/8920 [1:12:40<1:07:19,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seth_Macfarlane.jpg

 43%|████▎     | 3870/8920 [1:12:42<1:15:28,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricky_Martin.jpg

 43%|████▎     | 3871/8920 [1:12:42<1:08:07,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenni_Rivera.jpg

 43%|████▎     | 3872/8920 [1:12:42<55:39,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joaquin_Phoenix.jpg

 43%|████▎     | 3873/8920 [1:12:43<56:02,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katherine_Heigl.jpg

 43%|████▎     | 3874/8920 [1:12:43<46:54,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Nicole_Smith.jpg

 43%|████▎     | 3875/8920 [1:12:45<1:09:35,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Bonet.jpg

 43%|████▎     | 3876/8920 [1:12:46<1:05:15,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Schumacher.jpg

 43%|████▎     | 3877/8920 [1:12:46<59:24,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Beamer.jpg

 43%|████▎     | 3878/8920 [1:12:48<1:16:39,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaromír_Jágr.jpg

 43%|████▎     | 3879/8920 [1:12:49<1:28:57,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelly.jpg

 43%|████▎     | 3880/8920 [1:12:50<1:34:34,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Lafontaine.jpg

 44%|████▎     | 3881/8920 [1:12:51<1:28:07,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matteo_Salvini.jpg

 44%|████▎     | 3882/8920 [1:12:52<1:20:40,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Ramsay.jpg

 44%|████▎     | 3883/8920 [1:12:52<1:12:13,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Markus_Persson.jpg

 44%|████▎     | 3884/8920 [1:12:53<1:06:58,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christy_Turlington.jpg

 44%|████▎     | 3885/8920 [1:12:53<54:00,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikki_Haley.jpg

 44%|████▎     | 3886/8920 [1:12:54<57:32,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Perez_Hilton.jpg

 44%|████▎     | 3887/8920 [1:12:55<49:35,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Menounos.jpg

 44%|████▎     | 3888/8920 [1:12:55<46:14,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Seacrest.jpg

 44%|████▎     | 3889/8920 [1:12:57<1:24:11,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelly_Furtado.jpg

 44%|████▎     | 3890/8920 [1:12:57<1:08:19,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Psy.jpg

 44%|████▎     | 3891/8920 [1:12:58<1:10:01,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Snoop_Dogg.jpg

 44%|████▎     | 3892/8920 [1:12:59<1:05:56,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonardo_Dicaprio.jpg

 44%|████▎     | 3893/8920 [1:13:01<1:30:02,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daddy_Yankee.jpg

 44%|████▎     | 3894/8920 [1:13:02<1:39:13,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Ofili.jpg

 44%|████▎     | 3895/8920 [1:13:03<1:24:56,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ll_Cool_J.jpg

 44%|████▎     | 3896/8920 [1:13:04<1:32:24,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liz_Truss.jpg

 44%|████▎     | 3897/8920 [1:13:05<1:23:58,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mellody_Hobson.jpg

 44%|████▎     | 3898/8920 [1:13:05<1:04:47,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Banks.jpg

 44%|████▎     | 3899/8920 [1:13:06<1:00:20,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephenie_Meyer.jpg

 44%|████▎     | 3900/8920 [1:13:06<49:32,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rebel_Wilson.jpg

 44%|████▎     | 3901/8920 [1:13:07<1:00:42,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiger_Woods.jpg

 44%|████▎     | 3902/8920 [1:13:07<49:38,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Claire_Danes.jpg

 44%|████▍     | 3903/8920 [1:13:08<50:16,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emmanuel_Macron.jpg

 44%|████▍     | 3904/8920 [1:13:08<41:59,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Bunton.jpg

 44%|████▍     | 3905/8920 [1:13:09<49:45,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cedric_Pioline.jpg

 44%|████▍     | 3906/8920 [1:13:10<1:06:46,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristi_Yamaguchi.jpg

 44%|████▍     | 3907/8920 [1:13:11<1:04:17,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentino_Rossi.jpg

 44%|████▍     | 3908/8920 [1:13:14<1:51:16,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Lopez.jpg

 44%|████▍     | 3909/8920 [1:13:15<1:52:15,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonny_Wilkinson.jpg

 44%|████▍     | 3910/8920 [1:13:15<1:27:17,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Randy_Orton.jpg

 44%|████▍     | 3911/8920 [1:13:16<1:21:42,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Rhode.jpg

 44%|████▍     | 3912/8920 [1:13:19<2:02:39,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Regina_King.jpg

 44%|████▍     | 3913/8920 [1:13:19<1:35:04,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Jeong.jpg

 44%|████▍     | 3914/8920 [1:13:19<1:13:08,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brendan_Greene.jpg

 44%|████▍     | 3915/8920 [1:13:20<58:40,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthew_Perry.jpg

 44%|████▍     | 3916/8920 [1:13:21<1:07:59,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Chang.jpg

 44%|████▍     | 3917/8920 [1:13:21<53:49,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Justice.jpg

 44%|████▍     | 3918/8920 [1:13:21<43:17,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Mcdonagh.jpg

 44%|████▍     | 3919/8920 [1:13:22<59:24,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernie_Els.jpg

 44%|████▍     | 3920/8920 [1:13:23<1:04:51,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Dimarco.jpg

 44%|████▍     | 3921/8920 [1:13:25<1:36:21,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doug_Mcmillon.jpg

 44%|████▍     | 3922/8920 [1:13:26<1:34:16,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oscar_Isaac.jpg

 44%|████▍     | 3923/8920 [1:13:28<1:39:10,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Blaine.jpg

 44%|████▍     | 3924/8920 [1:13:28<1:22:15,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kurt_Browning.jpg

 44%|████▍     | 3925/8920 [1:13:29<1:14:11,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Triple_H.jpg

 44%|████▍     | 3926/8920 [1:13:31<1:32:37,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yulia_Navalnaya.jpg

 44%|████▍     | 3927/8920 [1:13:32<1:30:32,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Javier_Bardem.jpg

 44%|████▍     | 3928/8920 [1:13:32<1:17:33,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Hart.jpg

 44%|████▍     | 3929/8920 [1:13:33<1:08:15,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jensen_Ackles.jpg

 44%|████▍     | 3930/8920 [1:13:33<55:46,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Winona_Ryder.jpg

 44%|████▍     | 3931/8920 [1:13:35<1:18:07,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Koji_Igarashi.jpg

 44%|████▍     | 3932/8920 [1:13:35<1:01:41,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moises_Alou.jpg

 44%|████▍     | 3933/8920 [1:13:36<1:02:00,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vijay.jpg

 44%|████▍     | 3934/8920 [1:13:36<50:46,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Selma_Blair.jpg

 44%|████▍     | 3935/8920 [1:13:37<1:00:57,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Rodriguez.jpg

 44%|████▍     | 3936/8920 [1:13:37<53:50,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tonya_Harding.jpg

 44%|████▍     | 3937/8920 [1:13:38<52:11,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavel_Bure.jpg

 44%|████▍     | 3938/8920 [1:13:39<53:12,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lindsay_Davenport.jpg

 44%|████▍     | 3939/8920 [1:13:39<50:25,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juicy_J.jpg

 44%|████▍     | 3940/8920 [1:13:40<1:04:07,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Rutte.jpg

 44%|████▍     | 3941/8920 [1:13:41<58:44,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brandon_Boyd.jpg

 44%|████▍     | 3942/8920 [1:13:44<1:51:31,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahershala_Ali.jpg

 44%|████▍     | 3943/8920 [1:13:45<1:37:14,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrice_Désilets.jpg

 44%|████▍     | 3944/8920 [1:13:45<1:26:46,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarence_Seedorf.jpg

 44%|████▍     | 3945/8920 [1:13:47<1:40:23,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brett_Kavanaugh.jpg

 44%|████▍     | 3946/8920 [1:13:48<1:28:22,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tucker_Carlson.jpg

 44%|████▍     | 3947/8920 [1:13:48<1:21:09,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brock_Lesnar.jpg

 44%|████▍     | 3948/8920 [1:13:50<1:45:54,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lou_Bega.jpg

 44%|████▍     | 3949/8920 [1:13:53<2:17:43,  1.66s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demis_Hassabis.jpg

 44%|████▍     | 3950/8920 [1:13:54<2:09:27,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yahya_Jammeh.jpg

 44%|████▍     | 3951/8920 [1:13:55<1:36:18,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alyson_Hannigan.jpg

 44%|████▍     | 3952/8920 [1:13:56<1:39:50,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manny_Pacquiao.jpg

 44%|████▍     | 3953/8920 [1:13:56<1:15:42,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Daly.jpg

 44%|████▍     | 3954/8920 [1:13:57<1:17:41,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexis_Tsipras.jpg

 44%|████▍     | 3955/8920 [1:13:58<1:16:21,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Randy_Moss.jpg

 44%|████▍     | 3956/8920 [1:13:59<1:14:39,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Longoria.jpg

 44%|████▍     | 3957/8920 [1:14:01<1:50:15,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvis_Stojko.jpg

 44%|████▍     | 3958/8920 [1:14:01<1:24:07,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Mendelsohn.jpg

 44%|████▍     | 3959/8920 [1:14:02<1:12:24,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miroslav_Klose.jpg

 44%|████▍     | 3960/8920 [1:14:02<58:25,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Gayle.jpg

 44%|████▍     | 3961/8920 [1:14:05<1:52:06,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Patrick_Harris.jpg

 44%|████▍     | 3962/8920 [1:14:07<2:09:14,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Cryer.jpg

 44%|████▍     | 3963/8920 [1:14:07<1:35:40,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Pratt.jpg

 44%|████▍     | 3964/8920 [1:14:08<1:19:11,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thierry_Henry.jpg

 44%|████▍     | 3965/8920 [1:14:09<1:25:52,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Thornton.jpg

 44%|████▍     | 3966/8920 [1:14:09<1:06:38,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deion_Sanders.jpg

 44%|████▍     | 3967/8920 [1:14:11<1:23:28,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cliff_Bleszinski.jpg

 44%|████▍     | 3968/8920 [1:14:12<1:20:56,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Roberts.jpg

 44%|████▍     | 3969/8920 [1:14:13<1:22:19,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Lynn_Rajskub.jpg

 45%|████▍     | 3970/8920 [1:14:13<1:05:58,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reese_Witherspoon.jpg

 45%|████▍     | 3971/8920 [1:14:15<1:31:05,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Cannavale.jpg

 45%|████▍     | 3972/8920 [1:14:15<1:14:01,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Volodymyr_Zelensky.jpg

 45%|████▍     | 3973/8920 [1:14:16<1:01:12,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennie_Garth.jpg

 45%|████▍     | 3974/8920 [1:14:17<1:12:29,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandra_Oh.jpg

 45%|████▍     | 3975/8920 [1:14:18<1:07:15,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Roy.jpg

 45%|████▍     | 3976/8920 [1:14:19<1:16:34,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Hudson.jpg

 45%|████▍     | 3977/8920 [1:14:19<1:03:14,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alyssa_Milano.jpg

 45%|████▍     | 3978/8920 [1:14:20<1:12:05,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Rudd.jpg

 45%|████▍     | 3979/8920 [1:14:22<1:23:20,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Capriati.jpg

 45%|████▍     | 3980/8920 [1:14:22<1:04:38,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julianna_Margulies.jpg

 45%|████▍     | 3981/8920 [1:14:23<1:17:59,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keri_Russell.jpg

 45%|████▍     | 3982/8920 [1:14:25<1:35:11,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Lemieux.jpg

 45%|████▍     | 3983/8920 [1:14:26<1:28:10,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adrien_Brody.jpg

 45%|████▍     | 3984/8920 [1:14:27<1:40:46,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Koumas.jpg

 45%|████▍     | 3985/8920 [1:14:28<1:16:34,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Rock.jpg

 45%|████▍     | 3986/8920 [1:14:29<1:17:53,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abu_Bakr_Al-Baghdadi.jpg

 45%|████▍     | 3987/8920 [1:14:29<1:02:33,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Norah_Jones.jpg

 45%|████▍     | 3988/8920 [1:14:29<52:15,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kobe_Bryant.jpg

 45%|████▍     | 3989/8920 [1:14:30<47:21,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Dell.jpg

 45%|████▍     | 3990/8920 [1:14:30<50:00,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keiji_Inafune.jpg

 45%|████▍     | 3991/8920 [1:14:31<42:15,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christina_Applegate.jpg

 45%|████▍     | 3992/8920 [1:14:31<34:37,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_J._Blige.jpg

 45%|████▍     | 3993/8920 [1:14:33<1:05:56,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Gant.jpg

 45%|████▍     | 3994/8920 [1:14:33<55:27,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Duncan.jpg

 45%|████▍     | 3995/8920 [1:14:34<57:41,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Webb.jpg

 45%|████▍     | 3996/8920 [1:14:35<1:07:54,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Feldman.jpg

 45%|████▍     | 3997/8920 [1:14:36<1:12:50,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sterling_K._Brown.jpg

 45%|████▍     | 3998/8920 [1:14:37<1:08:27,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Turgeon.jpg

 45%|████▍     | 3999/8920 [1:14:37<55:24,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Furyk.jpg

 45%|████▍     | 4000/8920 [1:14:37<45:13,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liv_Tyler.jpg

 45%|████▍     | 4001/8920 [1:14:38<47:09,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cam_Neely.jpg

 45%|████▍     | 4002/8920 [1:14:39<1:09:01,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Goran_Ivanišević.jpg

 45%|████▍     | 4003/8920 [1:14:40<1:18:33,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amanda_Peet.jpg

 45%|████▍     | 4004/8920 [1:14:41<1:00:19,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Martin.jpg

 45%|████▍     | 4005/8920 [1:14:41<47:43,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melissa_Joan_Hart.jpg

 45%|████▍     | 4006/8920 [1:14:43<1:14:08,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kal_Penn.jpg

 45%|████▍     | 4007/8920 [1:14:43<1:11:31,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vaughan_Gething.jpg

 45%|████▍     | 4008/8920 [1:14:45<1:19:03,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iva_Majoli.jpg

 45%|████▍     | 4009/8920 [1:14:45<1:00:58,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willem-Alexander.jpg

 45%|████▍     | 4010/8920 [1:14:46<1:09:13,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Aldean.jpg

 45%|████▍     | 4011/8920 [1:14:46<55:21,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricki_Lake.jpg

 45%|████▍     | 4012/8920 [1:14:46<44:41,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noah_Wyle.jpg

 45%|████▍     | 4013/8920 [1:14:47<38:40,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luis_Miguel.jpg

 45%|████▌     | 4014/8920 [1:14:48<56:42,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Cash.jpg

 45%|████▌     | 4015/8920 [1:14:48<48:08,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marlee_Matlin.jpg

 45%|████▌     | 4016/8920 [1:14:49<1:03:30,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Robbins.jpg

 45%|████▌     | 4017/8920 [1:14:50<57:34,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Ng.jpg

 45%|████▌     | 4018/8920 [1:14:50<50:55,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uta_Pippig.jpg

 45%|████▌     | 4019/8920 [1:14:51<45:57,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Glavine.jpg

 45%|████▌     | 4020/8920 [1:14:52<48:08,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ramin_Djawadi.jpg

 45%|████▌     | 4021/8920 [1:14:52<46:29,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kanye_West.jpg

 45%|████▌     | 4022/8920 [1:14:55<1:35:46,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Jansen.jpg

 45%|████▌     | 4023/8920 [1:14:55<1:14:09,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanilla_Ice.jpg

 45%|████▌     | 4024/8920 [1:14:55<59:14,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heidi_Klum.jpg

 45%|████▌     | 4025/8920 [1:14:56<54:35,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Macdonald.jpg

 45%|████▌     | 4026/8920 [1:14:56<45:36,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacinda_Ardern.jpg

 45%|████▌     | 4027/8920 [1:14:56<39:15,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_Maddow.jpg

 45%|████▌     | 4028/8920 [1:14:57<34:55,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samantha_Power.jpg

 45%|████▌     | 4029/8920 [1:14:58<56:38,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hilary_Swank.jpg

 45%|████▌     | 4030/8920 [1:14:59<1:02:46,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_C._Reilly.jpg

 45%|████▌     | 4031/8920 [1:14:59<50:06,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Tennant.jpg

 45%|████▌     | 4032/8920 [1:14:59<42:36,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peyton_Manning.jpg

 45%|████▌     | 4033/8920 [1:15:00<34:50,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/River_Phoenix.jpg

 45%|████▌     | 4034/8920 [1:15:01<53:10,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kent_Desormeaux.jpg

 45%|████▌     | 4035/8920 [1:15:01<51:47,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Biondi.jpg

 45%|████▌     | 4036/8920 [1:15:02<56:15,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aamir_Khan.jpg

 45%|████▌     | 4037/8920 [1:15:03<46:41,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Idris_Elba.jpg

 45%|████▌     | 4038/8920 [1:15:05<1:29:52,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Hamm.jpg

 45%|████▌     | 4039/8920 [1:15:05<1:10:30,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Lewis.jpg

 45%|████▌     | 4040/8920 [1:15:06<56:37,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Statham.jpg

 45%|████▌     | 4041/8920 [1:15:06<45:15,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trent_Reznor.jpg

 45%|████▌     | 4042/8920 [1:15:06<46:25,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shinji_Mikami.jpg

 45%|████▌     | 4043/8920 [1:15:08<1:04:18,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Maddux.jpg

 45%|████▌     | 4044/8920 [1:15:08<58:05,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alicia_Silverstone.jpg

 45%|████▌     | 4045/8920 [1:15:10<1:13:03,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danai_Gurira.jpg

 45%|████▌     | 4046/8920 [1:15:10<1:11:45,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catriona_Matthew.jpg

 45%|████▌     | 4047/8920 [1:15:11<58:12,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diane_Kruger.jpg

 45%|████▌     | 4048/8920 [1:15:11<54:52,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Slater.jpg

 45%|████▌     | 4049/8920 [1:15:12<55:14,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Munn.jpg

 45%|████▌     | 4050/8920 [1:15:13<1:12:01,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Worthington.jpg

 45%|████▌     | 4051/8920 [1:15:14<1:07:53,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Pegg.jpg

 45%|████▌     | 4052/8920 [1:15:14<55:59,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Bay.jpg

 45%|████▌     | 4053/8920 [1:15:15<53:09,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Sakic.jpg

 45%|████▌     | 4054/8920 [1:15:15<43:16,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristen_Bell.jpg

 45%|████▌     | 4055/8920 [1:15:17<1:02:42,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conchita_Martínez.jpg

 45%|████▌     | 4056/8920 [1:15:18<1:22:33,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Jones.jpg

 45%|████▌     | 4057/8920 [1:15:19<1:17:57,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Lindros.jpg

 45%|████▌     | 4058/8920 [1:15:20<1:07:43,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Brodeur.jpg

 46%|████▌     | 4059/8920 [1:15:20<53:55,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Lyonne.jpg

 46%|████▌     | 4060/8920 [1:15:20<43:11,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Carlos_Ferrero.jpg

 46%|████▌     | 4061/8920 [1:15:21<44:39,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brett_Favre.jpg

 46%|████▌     | 4062/8920 [1:15:21<40:40,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rishi_Sunak.jpg

 46%|████▌     | 4063/8920 [1:15:22<54:48,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Jaeger.jpg

 46%|████▌     | 4064/8920 [1:15:22<44:23,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/50_Cent.jpg

 46%|████▌     | 4065/8920 [1:15:23<47:44,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Brolin.jpg

 46%|████▌     | 4066/8920 [1:15:23<42:11,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeezy.jpg

 46%|████▌     | 4067/8920 [1:15:25<1:01:41,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Thrun.jpg

 46%|████▌     | 4068/8920 [1:15:25<49:56,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Björk.jpg

 46%|████▌     | 4069/8920 [1:15:27<1:22:49,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Foley.jpg

 46%|████▌     | 4070/8920 [1:15:28<1:12:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerard_Way.jpg

 46%|████▌     | 4071/8920 [1:15:28<1:07:30,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Gordon.jpg

 46%|████▌     | 4072/8920 [1:15:31<1:52:43,  1.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laverne_Cox.jpg

 46%|████▌     | 4073/8920 [1:15:32<1:35:22,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Yzerman.jpg

 46%|████▌     | 4074/8920 [1:15:33<1:29:53,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Fiennes.jpg

 46%|████▌     | 4075/8920 [1:15:33<1:09:56,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Price.jpg

 46%|████▌     | 4076/8920 [1:15:34<1:09:11,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eminem.jpg

 46%|████▌     | 4077/8920 [1:15:35<1:10:44,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Too_Short.jpg

 46%|████▌     | 4078/8920 [1:15:36<1:24:30,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Russell_Brand.jpg

 46%|████▌     | 4079/8920 [1:15:36<1:05:38,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sundar_Pichai.jpg

 46%|████▌     | 4080/8920 [1:15:37<1:01:29,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Michelle_Gellar.jpg

 46%|████▌     | 4081/8920 [1:15:38<59:03,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vin_Diesel.jpg

 46%|████▌     | 4082/8920 [1:15:39<1:13:10,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wasim_Akram.jpg

 46%|████▌     | 4083/8920 [1:15:40<1:10:11,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shannen_Doherty.jpg

 46%|████▌     | 4084/8920 [1:15:40<1:03:30,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Rodriguez.jpg

 46%|████▌     | 4085/8920 [1:15:42<1:26:19,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Ayoade.jpg

 46%|████▌     | 4086/8920 [1:15:42<1:09:08,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benedict_Cumberbatch.jpg

 46%|████▌     | 4087/8920 [1:15:44<1:27:24,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Andrés.jpg

 46%|████▌     | 4088/8920 [1:15:45<1:22:33,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rob_Thomas.jpg

 46%|████▌     | 4089/8920 [1:15:46<1:17:08,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Cohen.jpg

 46%|████▌     | 4090/8920 [1:15:46<1:11:51,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Astin.jpg

 46%|████▌     | 4091/8920 [1:15:49<1:40:25,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jodhi_May.jpg

 46%|████▌     | 4092/8920 [1:15:49<1:30:11,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Robinson.jpg

 46%|████▌     | 4093/8920 [1:15:50<1:08:45,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cynthia_Nixon.jpg

 46%|████▌     | 4094/8920 [1:15:50<58:14,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucy_Lawless.jpg

 46%|████▌     | 4095/8920 [1:15:50<48:02,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rodney_King.jpg

 46%|████▌     | 4096/8920 [1:15:52<1:01:26,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nancy_Kerrigan.jpg

 46%|████▌     | 4097/8920 [1:15:52<1:06:08,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Hu.jpg

 46%|████▌     | 4098/8920 [1:15:53<56:51,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Morrison.jpg

 46%|████▌     | 4099/8920 [1:15:54<54:54,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Mendes.jpg

 46%|████▌     | 4100/8920 [1:15:54<59:43,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zach_Braff.jpg

 46%|████▌     | 4101/8920 [1:15:55<1:00:14,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Medvedev.jpg

 46%|████▌     | 4102/8920 [1:15:57<1:34:52,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellen_Pompeo.jpg

 46%|████▌     | 4103/8920 [1:15:58<1:12:59,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helena_Bonham_Carter.jpg

 46%|████▌     | 4104/8920 [1:15:58<1:06:06,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cory_Barlog.jpg

 46%|████▌     | 4105/8920 [1:15:59<53:09,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cindy_Crawford.jpg

 46%|████▌     | 4106/8920 [1:15:59<45:17,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Onrait.jpg

 46%|████▌     | 4107/8920 [1:16:00<53:20,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Williams.jpg

 46%|████▌     | 4108/8920 [1:16:02<1:25:21,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Lopez.jpg

 46%|████▌     | 4109/8920 [1:16:02<1:14:30,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Savage.jpg

 46%|████▌     | 4110/8920 [1:16:03<1:06:56,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Connolly.jpg

 46%|████▌     | 4111/8920 [1:16:03<53:24,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Eldredge.jpg

 46%|████▌     | 4112/8920 [1:16:04<45:33,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tupac_Shakur.jpg

 46%|████▌     | 4113/8920 [1:16:04<37:37,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Shearer.jpg

 46%|████▌     | 4114/8920 [1:16:05<42:48,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Lawrence.jpg

 46%|████▌     | 4115/8920 [1:16:05<49:15,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marion_Jones.jpg

 46%|████▌     | 4116/8920 [1:16:06<49:40,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Davies.jpg

 46%|████▌     | 4117/8920 [1:16:07<51:53,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Burr.jpg

 46%|████▌     | 4118/8920 [1:16:07<41:43,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ice_Cube.jpg

 46%|████▌     | 4119/8920 [1:16:07<38:40,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wladimir_Klitschko.jpg

 46%|████▌     | 4120/8920 [1:16:08<33:10,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tobey_Maguire.jpg

 46%|████▌     | 4121/8920 [1:16:08<30:35,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Undertaker.jpg

 46%|████▌     | 4122/8920 [1:16:08<34:52,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Sisto.jpg

 46%|████▌     | 4123/8920 [1:16:09<30:17,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patricia_Arquette.jpg

 46%|████▌     | 4124/8920 [1:16:09<27:05,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uma_Thurman.jpg

 46%|████▌     | 4125/8920 [1:16:09<27:26,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Momoa.jpg

 46%|████▋     | 4126/8920 [1:16:10<45:32,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Krumholtz.jpg

 46%|████▋     | 4127/8920 [1:16:11<46:23,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Van_Der_Beek.jpg

 46%|████▋     | 4128/8920 [1:16:11<38:47,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gisele_Bündchen.jpg

 46%|████▋     | 4129/8920 [1:16:13<57:07,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Lara.jpg

 46%|████▋     | 4130/8920 [1:16:15<1:30:38,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Jennings.jpg

 46%|████▋     | 4131/8920 [1:16:15<1:09:20,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Missy_Elliott.jpg

 46%|████▋     | 4132/8920 [1:16:16<1:03:44,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hidetaka_Miyazaki.jpg

 46%|████▋     | 4133/8920 [1:16:16<59:18,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Fillion.jpg

 46%|████▋     | 4134/8920 [1:16:16<50:25,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shaggy.jpg

 46%|████▋     | 4135/8920 [1:16:17<41:59,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tricia_Helfer.jpg

 46%|████▋     | 4136/8920 [1:16:17<36:46,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Didier_Drogba.jpg

 46%|████▋     | 4137/8920 [1:16:18<40:44,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Mraz.jpg

 46%|████▋     | 4138/8920 [1:16:18<47:20,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akon.jpg

 46%|████▋     | 4139/8920 [1:16:19<52:19,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brandy_Norwood.jpg

 46%|████▋     | 4140/8920 [1:16:20<1:04:39,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Joe_Fernández.jpg

 46%|████▋     | 4141/8920 [1:16:23<1:49:56,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriela_Sabatini.jpg

 46%|████▋     | 4142/8920 [1:16:24<1:27:33,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuji_Naka.jpg

 46%|████▋     | 4143/8920 [1:16:24<1:07:42,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Nolan.jpg

 46%|████▋     | 4144/8920 [1:16:24<55:06,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Jones.jpg

 46%|████▋     | 4145/8920 [1:16:24<43:45,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Walker.jpg

 46%|████▋     | 4146/8920 [1:16:25<54:56,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Eckhart.jpg

 46%|████▋     | 4147/8920 [1:16:27<1:09:54,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Stapleton.jpg

 47%|████▋     | 4148/8920 [1:16:27<55:24,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ioan_Gruffudd.jpg

 47%|████▋     | 4149/8920 [1:16:28<1:02:50,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Mendes.jpg

 47%|████▋     | 4150/8920 [1:16:30<1:27:51,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Renée_Zellweger.jpg

 47%|████▋     | 4151/8920 [1:16:31<1:19:59,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Floyd_Mayweather_Jr..jpg

 47%|████▋     | 4152/8920 [1:16:32<1:37:17,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Hawk.jpg

 47%|████▋     | 4153/8920 [1:16:33<1:31:30,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Parsons.jpg

 47%|████▋     | 4154/8920 [1:16:34<1:11:51,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Halle_Berry.jpg

 47%|████▋     | 4155/8920 [1:16:34<1:07:13,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Derek_Jeter.jpg

 47%|████▋     | 4156/8920 [1:16:35<54:24,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gucci_Mane.jpg

 47%|████▋     | 4157/8920 [1:16:35<43:29,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chai_Jing.jpg

 47%|████▋     | 4158/8920 [1:16:35<43:17,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Brady.jpg

 47%|████▋     | 4159/8920 [1:16:36<35:49,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gwyneth_Paltrow.jpg

 47%|████▋     | 4160/8920 [1:16:36<42:38,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luke_Bryan.jpg

 47%|████▋     | 4161/8920 [1:16:37<50:01,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Mcavoy.jpg

 47%|████▋     | 4162/8920 [1:16:38<56:58,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedro_Pascal.jpg

 47%|████▋     | 4163/8920 [1:16:39<58:08,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexis_Denisof.jpg

 47%|████▋     | 4164/8920 [1:16:40<58:59,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Andre.jpg

 47%|████▋     | 4165/8920 [1:16:40<47:37,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annika_Sörenstam.jpg

 47%|████▋     | 4166/8920 [1:16:41<55:51,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Brin.jpg

 47%|████▋     | 4167/8920 [1:16:43<1:24:24,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_O'Donnell.jpg

 47%|████▋     | 4168/8920 [1:16:44<1:16:01,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Page.jpg

 47%|████▋     | 4169/8920 [1:16:44<1:01:28,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Simpson.jpg

 47%|████▋     | 4170/8920 [1:16:45<1:01:27,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marine_Le_Pen.jpg

 47%|████▋     | 4171/8920 [1:16:45<50:50,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Penélope_Cruz.jpg

 47%|████▋     | 4172/8920 [1:16:46<52:36,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louise_Woodward.jpg

 47%|████▋     | 4173/8920 [1:16:47<1:16:29,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Fisher.jpg

 47%|████▋     | 4174/8920 [1:16:49<1:30:00,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Casey_Affleck.jpg

 47%|████▋     | 4175/8920 [1:16:52<2:03:44,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wes_Bentley.jpg

 47%|████▋     | 4176/8920 [1:16:52<1:42:25,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zinedine_Zidane.jpg

 47%|████▋     | 4177/8920 [1:16:53<1:36:04,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Tucker.jpg

 47%|████▋     | 4178/8920 [1:16:54<1:35:26,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jill_Soloway.jpg

 47%|████▋     | 4179/8920 [1:16:55<1:28:10,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sacha_Baron_Cohen.jpg

 47%|████▋     | 4180/8920 [1:16:57<1:36:51,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enrique_Peña_Nieto.jpg

 47%|████▋     | 4181/8920 [1:16:58<1:40:34,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blake_Shelton.jpg

 47%|████▋     | 4182/8920 [1:16:59<1:26:11,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Johns.jpg

 47%|████▋     | 4183/8920 [1:17:00<1:15:42,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Craig.jpg

 47%|████▋     | 4184/8920 [1:17:00<59:49,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pamela_Anderson.jpg

 47%|████▋     | 4185/8920 [1:17:00<47:14,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Kipkoech_Cheruiyot.jpg

 47%|████▋     | 4186/8920 [1:17:01<56:52,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Todd_Howard.jpg

 47%|████▋     | 4187/8920 [1:17:01<46:56,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofía_Vergara.jpg

 47%|████▋     | 4188/8920 [1:17:02<38:32,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiffany_Darwish.jpg

 47%|████▋     | 4189/8920 [1:17:03<57:14,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Farrell.jpg

 47%|████▋     | 4190/8920 [1:17:03<44:53,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terrence_Howard.jpg

 47%|████▋     | 4191/8920 [1:17:04<45:46,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronan_Keating.jpg

 47%|████▋     | 4192/8920 [1:17:04<49:06,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julian_Assange.jpg

 47%|████▋     | 4193/8920 [1:17:05<39:46,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Cameron.jpg

 47%|████▋     | 4194/8920 [1:17:06<50:23,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Muster.jpg

 47%|████▋     | 4195/8920 [1:17:06<42:01,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Cannon.jpg

 47%|████▋     | 4196/8920 [1:17:06<44:08,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queen_Latifah.jpg

 47%|████▋     | 4197/8920 [1:17:07<36:55,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melanie_Brown.jpg

 47%|████▋     | 4198/8920 [1:17:07<34:11,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vince_Vaughn.jpg

 47%|████▋     | 4199/8920 [1:17:07<30:19,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bashar_Al-Assad.jpg

 47%|████▋     | 4200/8920 [1:17:08<41:54,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_George.jpg

 47%|████▋     | 4201/8920 [1:17:09<50:08,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Freeman.jpg

 47%|████▋     | 4202/8920 [1:17:09<41:57,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Dujardin.jpg

 47%|████▋     | 4203/8920 [1:17:10<34:40,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Love_Hewitt.jpg

 47%|████▋     | 4204/8920 [1:17:13<1:32:10,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oliver_Riedel.jpg

 47%|████▋     | 4205/8920 [1:17:13<1:19:20,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Adams.jpg

 47%|████▋     | 4206/8920 [1:17:13<1:01:54,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melissa_Mccarthy.jpg

 47%|████▋     | 4207/8920 [1:17:14<56:49,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Notorious_B.I.G..jpg

 47%|████▋     | 4208/8920 [1:17:15<1:09:35,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Winslet.jpg

 47%|████▋     | 4209/8920 [1:17:16<1:06:32,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Dinklage.jpg

 47%|████▋     | 4210/8920 [1:17:16<51:59,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shaquille_O'Neal.jpg

 47%|████▋     | 4211/8920 [1:17:17<43:27,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Affleck.jpg

 47%|████▋     | 4212/8920 [1:17:18<1:08:32,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zoe_Saldaña.jpg

 47%|████▋     | 4213/8920 [1:17:19<1:07:16,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Mcgowan.jpg

 47%|████▋     | 4214/8920 [1:17:19<52:23,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Mcgraw.jpg

 47%|████▋     | 4215/8920 [1:17:20<1:05:51,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toni_Braxton.jpg

 47%|████▋     | 4216/8920 [1:17:22<1:14:11,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Theroux.jpg

 47%|████▋     | 4217/8920 [1:17:23<1:13:18,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugh_Jackman.jpg

 47%|████▋     | 4218/8920 [1:17:24<1:23:08,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Mickelson.jpg

 47%|████▋     | 4219/8920 [1:17:25<1:12:53,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Corden.jpg

 47%|████▋     | 4220/8920 [1:17:26<1:15:00,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steffi_Graf.jpg

 47%|████▋     | 4221/8920 [1:17:27<1:35:23,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheryl_Sandberg.jpg

 47%|████▋     | 4222/8920 [1:17:28<1:21:09,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Leblanc.jpg

 47%|████▋     | 4223/8920 [1:17:28<1:02:26,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Dirnt.jpg

 47%|████▋     | 4224/8920 [1:17:29<1:03:09,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Idina_Menzel.jpg

 47%|████▋     | 4225/8920 [1:17:29<50:33,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kurt_Cobain.jpg

 47%|████▋     | 4226/8920 [1:17:30<53:07,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geri_Horner.jpg

 47%|████▋     | 4227/8920 [1:17:31<50:08,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drew_Barrymore.jpg

 47%|████▋     | 4228/8920 [1:17:31<46:38,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Audra_Mcdonald.jpg

 47%|████▋     | 4229/8920 [1:17:31<38:19,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Damon.jpg

 47%|████▋     | 4230/8920 [1:17:32<33:43,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Wahlberg.jpg

 47%|████▋     | 4231/8920 [1:17:32<38:11,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/N._K._Jemisin.jpg

 47%|████▋     | 4232/8920 [1:17:33<32:31,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marion_Cotillard.jpg

 47%|████▋     | 4233/8920 [1:17:33<29:25,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scottie_Pippen.jpg

 47%|████▋     | 4234/8920 [1:17:35<1:15:20,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taika_Waititi.jpg

 47%|████▋     | 4235/8920 [1:17:36<1:08:25,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Maines.jpg

 47%|████▋     | 4236/8920 [1:17:37<1:19:45,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martina_Hingis.jpg

 48%|████▊     | 4237/8920 [1:17:37<1:01:13,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Poehler.jpg

 48%|████▊     | 4238/8920 [1:17:38<59:27,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronaldinho.jpg

 48%|████▊     | 4239/8920 [1:17:38<47:25,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will_Ferrell.jpg

 48%|████▊     | 4240/8920 [1:17:40<1:02:14,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Paul.jpg

 48%|████▊     | 4241/8920 [1:17:40<51:07,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seattle_Slew.jpg

 48%|████▊     | 4242/8920 [1:17:40<42:41,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marilyn_Manson.jpg

 48%|████▊     | 4243/8920 [1:17:41<46:16,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linus_Torvalds.jpg

 48%|████▊     | 4244/8920 [1:17:41<37:46,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Norton.jpg

 48%|████▊     | 4245/8920 [1:17:43<1:05:23,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Sampras.jpg

 48%|████▊     | 4246/8920 [1:17:44<1:04:54,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cate_Blanchett.jpg

 48%|████▊     | 4247/8920 [1:17:44<50:53,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Ronson.jpg

 48%|████▊     | 4248/8920 [1:17:45<58:54,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Hurley.jpg

 48%|████▊     | 4249/8920 [1:17:45<47:52,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elon_Musk.jpg

 48%|████▊     | 4250/8920 [1:17:45<38:35,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Satya_Nadella.jpg

 48%|████▊     | 4251/8920 [1:17:47<1:03:04,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ewan_Mcgregor.jpg

 48%|████▊     | 4252/8920 [1:17:47<51:13,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Fallon.jpg

 48%|████▊     | 4253/8920 [1:17:48<41:49,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Marie_Presley.jpg

 48%|████▊     | 4254/8920 [1:17:48<36:26,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salma_Hayek.jpg

 48%|████▊     | 4255/8920 [1:17:48<30:47,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlize_Theron.jpg

 48%|████▊     | 4256/8920 [1:17:48<27:43,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/P!Nk.jpg

 48%|████▊     | 4257/8920 [1:17:49<24:45,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitali_Klitschko.jpg

 48%|████▊     | 4258/8920 [1:17:49<24:15,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sachin_Tendulkar.jpg

 48%|████▊     | 4259/8920 [1:17:50<35:02,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thalía.jpg

 48%|████▊     | 4260/8920 [1:17:50<30:26,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Claudia_Schiffer.jpg

 48%|████▊     | 4261/8920 [1:17:50<34:32,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_Zeta-Jones.jpg

 48%|████▊     | 4262/8920 [1:17:51<30:41,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alison_Krauss.jpg

 48%|████▊     | 4263/8920 [1:17:51<27:35,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timothy_Mcveigh.jpg

 48%|████▊     | 4264/8920 [1:17:52<48:21,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Galecki.jpg

 48%|████▊     | 4265/8920 [1:17:52<39:04,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faith_Hill.jpg

 48%|████▊     | 4266/8920 [1:17:53<47:56,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._J._Abrams.jpg

 48%|████▊     | 4267/8920 [1:17:54<55:25,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tammy_Duckworth.jpg

 48%|████▊     | 4268/8920 [1:17:56<1:18:05,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Carmack.jpg

 48%|████▊     | 4269/8920 [1:17:57<1:16:06,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Tyson.jpg

 48%|████▊     | 4270/8920 [1:17:57<1:00:01,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooke_Shields.jpg

 48%|████▊     | 4271/8920 [1:17:57<47:30,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dwayne_Johnson.jpg

 48%|████▊     | 4272/8920 [1:18:00<1:25:09,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fergie.jpg

 48%|████▊     | 4273/8920 [1:18:00<1:04:40,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lance_Armstrong.jpg

 48%|████▊     | 4274/8920 [1:18:02<1:25:31,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Lopez.jpg

 48%|████▊     | 4275/8920 [1:18:02<1:13:33,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lennox_Lewis.jpg

 48%|████▊     | 4276/8920 [1:18:04<1:22:39,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Garner.jpg

 48%|████▊     | 4277/8920 [1:18:04<1:12:58,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jada_Pinkett_Smith.jpg

 48%|████▊     | 4278/8920 [1:18:05<1:04:12,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macaulay_Culkin.jpg

 48%|████▊     | 4279/8920 [1:18:05<1:02:00,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Sandler.jpg

 48%|████▊     | 4280/8920 [1:18:06<49:49,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sadiq_Khan.jpg

 48%|████▊     | 4281/8920 [1:18:06<40:09,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cameron_Diaz.jpg

 48%|████▊     | 4282/8920 [1:18:06<34:54,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noel_Gallagher.jpg

 48%|████▊     | 4283/8920 [1:18:07<29:42,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enrique_Iglesias.jpg

 48%|████▊     | 4284/8920 [1:18:07<26:07,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Cena.jpg

 48%|████▊     | 4285/8920 [1:18:07<23:40,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Connick_Jr.jpg

 48%|████▊     | 4286/8920 [1:18:07<23:09,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Rogan.jpg

 48%|████▊     | 4287/8920 [1:18:08<22:48,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celine_Dion.jpg

 48%|████▊     | 4288/8920 [1:18:09<46:32,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naomi_Campbell.jpg

 48%|████▊     | 4289/8920 [1:18:09<38:04,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Bublé.jpg

 48%|████▊     | 4290/8920 [1:18:10<40:05,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will_Smith.jpg

 48%|████▊     | 4291/8920 [1:18:11<47:47,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Jessica_Parker.jpg

 48%|████▊     | 4292/8920 [1:18:11<41:46,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martina_Mcbride.jpg

 48%|████▊     | 4293/8920 [1:18:11<34:33,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chimamanda_Ngozi_Adichie.jpg

 48%|████▊     | 4294/8920 [1:18:12<39:16,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Martin.jpg

 48%|████▊     | 4295/8920 [1:18:13<54:45,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andre_Agassi.jpg

 48%|████▊     | 4296/8920 [1:18:14<53:42,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carmen_Electra.jpg

 48%|████▊     | 4297/8920 [1:18:14<42:37,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelina_Jolie.jpg

 48%|████▊     | 4298/8920 [1:18:15<53:42,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Anthony.jpg

 48%|████▊     | 4299/8920 [1:18:15<44:54,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Beckham.jpg

 48%|████▊     | 4300/8920 [1:18:16<38:54,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Aniston.jpg

 48%|████▊     | 4301/8920 [1:18:16<34:54,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reid_Hoffman.jpg

 48%|████▊     | 4302/8920 [1:18:16<31:24,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Oliver.jpg

 48%|████▊     | 4303/8920 [1:18:16<27:22,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Downey_Jr.jpg

 48%|████▊     | 4304/8920 [1:18:18<58:18,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pharrell_Williams.jpg

 48%|████▊     | 4305/8920 [1:18:19<1:09:54,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._K._Rowling.jpg

 48%|████▊     | 4306/8920 [1:18:20<1:14:10,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janet_Jackson.jpg

 48%|████▊     | 4307/8920 [1:18:21<58:39,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronaldo.jpg

 48%|████▊     | 4308/8920 [1:18:23<1:31:02,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Beckham.jpg

 48%|████▊     | 4309/8920 [1:18:24<1:24:24,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christina_Ricci.jpg

 48%|████▊     | 4310/8920 [1:18:24<1:04:43,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Sheen.jpg

 48%|████▊     | 4311/8920 [1:18:25<57:58,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariah_Carey.jpg

 48%|████▊     | 4312/8920 [1:18:25<47:27,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lauryn_Hill.jpg

 48%|████▊     | 4313/8920 [1:18:25<38:50,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emmitt_Smith.jpg

 48%|████▊     | 4314/8920 [1:18:25<35:19,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thom_Yorke.jpg

 48%|████▊     | 4315/8920 [1:18:26<39:02,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shania_Twain.jpg

 48%|████▊     | 4316/8920 [1:18:26<33:05,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolores_O’Riordan.jpg

 48%|████▊     | 4317/8920 [1:18:27<28:37,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marco_Rubio.jpg

 48%|████▊     | 4318/8920 [1:18:28<47:59,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wayne_Brady.jpg

 48%|████▊     | 4319/8920 [1:18:29<56:14,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rashida_Jones.jpg

 48%|████▊     | 4320/8920 [1:18:29<53:10,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Corgan.jpg

 48%|████▊     | 4321/8920 [1:18:30<43:32,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Landry.jpg

 48%|████▊     | 4322/8920 [1:18:30<37:17,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Desantis.jpg

 48%|████▊     | 4323/8920 [1:18:30<31:14,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monica_Lewinsky.jpg

 48%|████▊     | 4324/8920 [1:18:30<27:04,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melania_Trump.jpg

 48%|████▊     | 4325/8920 [1:18:31<24:02,  3.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alanis_Morissette.jpg

 48%|████▊     | 4326/8920 [1:18:32<52:15,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Dan.jpg

 49%|████▊     | 4327/8920 [1:18:32<43:42,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Navalny.jpg

 49%|████▊     | 4328/8920 [1:18:33<36:06,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Wright.jpg

 49%|████▊     | 4329/8920 [1:18:33<30:56,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abby_Wambach.jpg

 49%|████▊     | 4330/8920 [1:18:34<50:20,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neve_Campbell.jpg

 49%|████▊     | 4331/8920 [1:18:35<52:20,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Clapton.jpg

 49%|████▊     | 4332/8920 [1:18:35<42:56,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marvin_Gaye.jpg

 49%|████▊     | 4333/8920 [1:18:37<1:00:08,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Slobodan_Milošević.jpg

 49%|████▊     | 4334/8920 [1:18:37<59:14,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rupert_Murdoch.jpg

 49%|████▊     | 4335/8920 [1:18:38<46:45,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikhail_Gorbachev.jpg

 49%|████▊     | 4336/8920 [1:18:38<38:42,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Watson.jpg

 49%|████▊     | 4337/8920 [1:18:39<55:58,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jayne_Mansfield.jpg

 49%|████▊     | 4338/8920 [1:18:40<55:24,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Gehry.jpg

 49%|████▊     | 4339/8920 [1:18:40<45:33,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Tereshkova.jpg

 49%|████▊     | 4340/8920 [1:18:40<39:04,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glenn_Hall.jpg

 49%|████▊     | 4341/8920 [1:18:42<54:46,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Van_Morrison.jpg

 49%|████▊     | 4342/8920 [1:18:42<45:36,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Micky_Dolenz.jpg

 49%|████▊     | 4343/8920 [1:18:43<46:17,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabel_Allende.jpg

 49%|████▊     | 4344/8920 [1:18:43<49:26,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Glitter.jpg

 49%|████▊     | 4345/8920 [1:18:44<43:05,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_E._Ambrose.jpg

 49%|████▊     | 4346/8920 [1:18:44<37:16,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Martin.jpg

 49%|████▊     | 4347/8920 [1:18:44<31:23,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Goodall.jpg

 49%|████▊     | 4348/8920 [1:18:44<28:42,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Stiglitz.jpg

 49%|████▉     | 4349/8920 [1:18:45<26:47,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Rose.jpg

 49%|████▉     | 4350/8920 [1:18:46<41:42,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Chamberlain.jpg

 49%|████▉     | 4351/8920 [1:18:47<1:05:26,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neale_Fraser.jpg

 49%|████▉     | 4352/8920 [1:18:50<1:55:59,  1.52s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Mckee.jpg

 49%|████▉     | 4353/8920 [1:18:51<1:32:31,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rajiv_Gandhi.jpg

 49%|████▉     | 4354/8920 [1:18:52<1:29:27,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mitch_Mcconnell.jpg

 49%|████▉     | 4355/8920 [1:18:54<1:49:51,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dudley_Herschbach.jpg

 49%|████▉     | 4356/8920 [1:18:55<1:35:23,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doris_Kearns_Goodwin.jpg

 49%|████▉     | 4357/8920 [1:18:56<1:28:47,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tuesday_Weld.jpg

 49%|████▉     | 4358/8920 [1:18:57<1:17:20,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Jones.jpg

 49%|████▉     | 4359/8920 [1:18:57<59:53,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellen_Johnson_Sirleaf.jpg

 49%|████▉     | 4360/8920 [1:18:58<1:10:00,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_M._Daley.jpg

 49%|████▉     | 4361/8920 [1:18:58<54:10,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Cousy.jpg

 49%|████▉     | 4362/8920 [1:18:59<50:30,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tina_Turner.jpg

 49%|████▉     | 4363/8920 [1:19:00<57:16,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Esposito.jpg

 49%|████▉     | 4364/8920 [1:19:00<54:51,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_John.jpg

 49%|████▉     | 4365/8920 [1:19:03<1:36:19,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evel_Knievel.jpg

 49%|████▉     | 4366/8920 [1:19:04<1:24:29,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Berry_Gordy.jpg

 49%|████▉     | 4367/8920 [1:19:04<1:11:20,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pele.jpg

 49%|████▉     | 4368/8920 [1:19:05<1:16:13,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Mortimer.jpg

 49%|████▉     | 4369/8920 [1:19:06<59:31,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akihito.jpg

 49%|████▉     | 4370/8920 [1:19:07<1:11:20,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Rice.jpg

 49%|████▉     | 4371/8920 [1:19:08<1:05:29,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Hopfield.jpg

 49%|████▉     | 4372/8920 [1:19:10<1:47:01,  1.41s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Carlton.jpg

 49%|████▉     | 4373/8920 [1:19:11<1:31:55,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Mccartney.jpg

 49%|████▉     | 4374/8920 [1:19:11<1:11:46,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Fonda.jpg

 49%|████▉     | 4375/8920 [1:19:12<1:06:47,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Ayckbourn.jpg

 49%|████▉     | 4376/8920 [1:19:13<1:07:45,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Cassidy.jpg

 49%|████▉     | 4377/8920 [1:19:14<1:03:02,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khun_Sa.jpg

 49%|████▉     | 4378/8920 [1:19:15<1:07:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Brown.jpg

 49%|████▉     | 4379/8920 [1:19:15<53:48,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Suzuki.jpg

 49%|████▉     | 4380/8920 [1:19:16<49:57,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Al-Bashir.jpg

 49%|████▉     | 4381/8920 [1:19:17<58:13,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ridley_Scott.jpg

 49%|████▉     | 4382/8920 [1:19:17<50:18,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nate_Thurmond.jpg

 49%|████▉     | 4383/8920 [1:19:18<57:03,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ennio_Morricone.jpg

 49%|████▉     | 4384/8920 [1:19:19<1:08:53,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernardo_Bertolucci.jpg

 49%|████▉     | 4385/8920 [1:19:21<1:34:02,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pervez_Musharraf.jpg

 49%|████▉     | 4386/8920 [1:19:23<1:45:06,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Cleary.jpg

 49%|████▉     | 4387/8920 [1:19:23<1:19:03,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Bancroft.jpg

 49%|████▉     | 4388/8920 [1:19:24<1:00:21,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mickey_Wright.jpg

 49%|████▉     | 4389/8920 [1:19:25<1:25:37,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheldon_Adelson.jpg

 49%|████▉     | 4390/8920 [1:19:26<1:14:06,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Seaver.jpg

 49%|████▉     | 4391/8920 [1:19:27<1:15:03,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gnassingbé_Eyadéma.jpg

 49%|████▉     | 4392/8920 [1:19:28<1:09:32,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Miller.jpg

 49%|████▉     | 4393/8920 [1:19:28<54:48,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Leone.jpg

 49%|████▉     | 4394/8920 [1:19:30<1:11:46,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dawn_Wells.jpg

 49%|████▉     | 4395/8920 [1:19:31<1:11:40,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harmon_Killebrew.jpg

 49%|████▉     | 4396/8920 [1:19:31<1:11:37,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Mason.jpg

 49%|████▉     | 4397/8920 [1:19:32<56:57,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Judith_Sheindlin.jpg

 49%|████▉     | 4398/8920 [1:19:32<50:31,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Hill.jpg

 49%|████▉     | 4399/8920 [1:19:34<1:06:37,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuck_Noll.jpg

 49%|████▉     | 4400/8920 [1:19:35<1:07:27,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Burt_Bacharach.jpg

 49%|████▉     | 4401/8920 [1:19:35<1:00:36,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Ebb.jpg

 49%|████▉     | 4402/8920 [1:19:35<48:08,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Lucas.jpg

 49%|████▉     | 4403/8920 [1:19:36<39:58,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Moore.jpg

 49%|████▉     | 4404/8920 [1:19:37<46:33,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilma_Rudolph.jpg

 49%|████▉     | 4406/8920 [1:19:37<31:00,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_West.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacques_Plante.jpg

 49%|████▉     | 4407/8920 [1:19:37<29:50,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betty_Shabazz.jpg

 49%|████▉     | 4408/8920 [1:19:38<27:47,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Morgan.jpg

 49%|████▉     | 4409/8920 [1:19:38<33:49,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cale_Yarborough.jpg

 49%|████▉     | 4410/8920 [1:19:38<28:56,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Rumelhart.jpg

 49%|████▉     | 4411/8920 [1:19:39<26:45,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stan_Mikita.jpg

 49%|████▉     | 4412/8920 [1:19:40<37:04,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuck_Mckinley.jpg

 49%|████▉     | 4413/8920 [1:19:41<56:29,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A._Bartlett_Giamatti.jpg

 49%|████▉     | 4414/8920 [1:19:41<45:27,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curtis_Mayfield.jpg

 49%|████▉     | 4415/8920 [1:19:41<36:44,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cy_Coleman.jpg

 50%|████▉     | 4416/8920 [1:19:42<43:00,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ornette_Coleman.jpg

 50%|████▉     | 4417/8920 [1:19:42<34:54,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luiz_Inácio_Lula_Da_Silva.jpg

 50%|████▉     | 4418/8920 [1:19:44<1:05:46,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Olmedo.jpg

 50%|████▉     | 4419/8920 [1:19:45<1:10:14,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerd_Müller.jpg

 50%|████▉     | 4420/8920 [1:19:46<1:03:12,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Everly.jpg

 50%|████▉     | 4421/8920 [1:19:46<50:33,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grace_Bumbry.jpg

 50%|████▉     | 4422/8920 [1:19:48<1:19:26,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ursula_K._Le_Guin.jpg

 50%|████▉     | 4423/8920 [1:19:49<1:09:20,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mia_Farrow.jpg

 50%|████▉     | 4424/8920 [1:19:49<1:00:07,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Hill.jpg

 50%|████▉     | 4425/8920 [1:19:50<47:14,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Simpson.jpg

 50%|████▉     | 4426/8920 [1:19:51<1:00:09,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Geffen.jpg

 50%|████▉     | 4427/8920 [1:19:52<1:02:47,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Turley.jpg

 50%|████▉     | 4428/8920 [1:19:53<1:04:35,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Sutherland.jpg

 50%|████▉     | 4429/8920 [1:19:53<58:12,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Geesink.jpg

 50%|████▉     | 4430/8920 [1:19:53<46:09,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hubert_Dreyfus.jpg

 50%|████▉     | 4431/8920 [1:19:54<49:52,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Brisco.jpg

 50%|████▉     | 4432/8920 [1:19:55<56:33,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Reid.jpg

 50%|████▉     | 4433/8920 [1:19:55<45:33,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Dolby.jpg

 50%|████▉     | 4434/8920 [1:19:56<45:00,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Michaels.jpg

 50%|████▉     | 4435/8920 [1:19:57<46:42,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elgin_Baylor.jpg

 50%|████▉     | 4436/8920 [1:19:58<58:59,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Snyder.jpg

 50%|████▉     | 4437/8920 [1:19:59<1:12:03,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harold_Bloom.jpg

 50%|████▉     | 4438/8920 [1:20:01<1:23:08,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Etta_James.jpg

 50%|████▉     | 4439/8920 [1:20:01<1:14:39,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doug_Sahm.jpg

 50%|████▉     | 4440/8920 [1:20:02<58:22,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuan_T._Lee.jpg

 50%|████▉     | 4441/8920 [1:20:02<55:12,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Gutfreund.jpg

 50%|████▉     | 4442/8920 [1:20:03<43:55,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rolf_Harris.jpg

 50%|████▉     | 4443/8920 [1:20:04<57:01,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wes_Craven.jpg

 50%|████▉     | 4444/8920 [1:20:04<47:58,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vivienne_Westwood.jpg

 50%|████▉     | 4445/8920 [1:20:05<59:52,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Meads.jpg

 50%|████▉     | 4446/8920 [1:20:07<1:19:37,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Von_Sydow.jpg

 50%|████▉     | 4447/8920 [1:20:08<1:12:59,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Spence.jpg

 50%|████▉     | 4448/8920 [1:20:08<1:06:03,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Cherry.jpg

 50%|████▉     | 4449/8920 [1:20:09<52:33,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sparky_Anderson.jpg

 50%|████▉     | 4450/8920 [1:20:10<58:56,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Guccione.jpg

 50%|████▉     | 4451/8920 [1:20:10<54:55,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dr._John.jpg

 50%|████▉     | 4452/8920 [1:20:11<43:16,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Polanyi.jpg

 50%|████▉     | 4453/8920 [1:20:11<41:00,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Chapman.jpg

 50%|████▉     | 4454/8920 [1:20:11<35:18,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Finney.jpg

 50%|████▉     | 4455/8920 [1:20:12<37:34,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Johnson.jpg

 50%|████▉     | 4456/8920 [1:20:13<43:23,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Turner.jpg

 50%|████▉     | 4457/8920 [1:20:13<37:13,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Craig_Breedlove.jpg

 50%|████▉     | 4458/8920 [1:20:15<1:05:26,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Welch.jpg

 50%|████▉     | 4459/8920 [1:20:15<1:02:28,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Mcqueen.jpg

 50%|█████     | 4460/8920 [1:20:16<51:42,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sani_Abacha.jpg

 50%|█████     | 4461/8920 [1:20:17<58:36,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Dukakis.jpg

 50%|█████     | 4462/8920 [1:20:17<53:16,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carol_Mann.jpg

 50%|█████     | 4463/8920 [1:20:18<49:08,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chi-Chi_Rodríguez.jpg

 50%|█████     | 4464/8920 [1:20:19<49:21,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chandra_Bahadur_Dangi.jpg

 50%|█████     | 4465/8920 [1:20:19<39:07,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stirling_Moss.jpg

 50%|█████     | 4466/8920 [1:20:19<34:39,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ollie_Matson.jpg

 50%|█████     | 4467/8920 [1:20:19<30:20,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clive_Granger.jpg

 50%|█████     | 4468/8920 [1:20:20<26:19,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Carle.jpg

 50%|█████     | 4469/8920 [1:20:20<30:04,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Norman_Schwarzkopf.jpg

 50%|█████     | 4470/8920 [1:20:20<26:53,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Ortega.jpg

 50%|█████     | 4471/8920 [1:20:21<26:00,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T._Boone_Pickens.jpg

 50%|█████     | 4472/8920 [1:20:21<25:37,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Cannon.jpg

 50%|█████     | 4473/8920 [1:20:23<55:58,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Arizin.jpg

 50%|█████     | 4474/8920 [1:20:24<58:05,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kris_Kristofferson.jpg

 50%|█████     | 4475/8920 [1:20:24<56:35,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Oerter.jpg

 50%|█████     | 4476/8920 [1:20:25<55:31,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Seale.jpg

 50%|█████     | 4477/8920 [1:20:26<52:30,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Chretien.jpg

 50%|█████     | 4478/8920 [1:20:26<42:06,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roone_Arledge.jpg

 50%|█████     | 4479/8920 [1:20:26<34:53,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margaret_Atwood.jpg

 50%|█████     | 4480/8920 [1:20:27<40:55,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Mills.jpg

 50%|█████     | 4481/8920 [1:20:27<34:35,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ralph_Boston.jpg

 50%|█████     | 4482/8920 [1:20:28<50:05,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Unser.jpg

 50%|█████     | 4483/8920 [1:20:30<1:12:31,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yao_Wenyuan.jpg

 50%|█████     | 4484/8920 [1:20:31<1:04:34,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Kopit.jpg

 50%|█████     | 4485/8920 [1:20:32<1:08:52,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lenny_Wilkens.jpg

 50%|█████     | 4486/8920 [1:20:33<1:10:52,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernie_Davis.jpg

 50%|█████     | 4487/8920 [1:20:33<55:06,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruno_Sammartino.jpg

 50%|█████     | 4488/8920 [1:20:35<1:20:44,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Clark.jpg

 50%|█████     | 4489/8920 [1:20:35<1:03:39,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fran_Tarkenton.jpg

 50%|█████     | 4490/8920 [1:20:37<1:21:40,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Mcfarlane.jpg

 50%|█████     | 4491/8920 [1:20:37<1:03:12,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacques_Anquetil.jpg

 50%|█████     | 4492/8920 [1:20:38<1:04:12,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Brookshier.jpg

 50%|█████     | 4493/8920 [1:20:39<58:30,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Lieberman.jpg

 50%|█████     | 4494/8920 [1:20:39<45:44,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Shrimpton.jpg

 50%|█████     | 4495/8920 [1:20:40<49:22,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Rosenblatt.jpg

 50%|█████     | 4496/8920 [1:20:41<1:03:30,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Stolle.jpg

 50%|█████     | 4497/8920 [1:20:42<59:00,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Rather.jpg

 50%|█████     | 4498/8920 [1:20:42<58:07,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvin_Hayes.jpg

 50%|█████     | 4499/8920 [1:20:43<49:53,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maury_Wills.jpg

 50%|█████     | 4500/8920 [1:20:43<41:47,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ingemar_Johansson.jpg

 50%|█████     | 4501/8920 [1:20:44<52:56,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Walsh.jpg

 50%|█████     | 4502/8920 [1:20:45<50:35,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Henry_Lawrence.jpg

 50%|█████     | 4503/8920 [1:20:45<40:17,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henri_Richard.jpg

 50%|█████     | 4504/8920 [1:20:46<42:30,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_O'Toole.jpg

 51%|█████     | 4505/8920 [1:20:47<58:09,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Wilson.jpg

 51%|█████     | 4506/8920 [1:20:48<54:10,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_F._Engle.jpg

 51%|█████     | 4507/8920 [1:20:49<1:01:29,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean-Luc_Godard.jpg

 51%|█████     | 4508/8920 [1:20:49<50:12,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Davis.jpg

 51%|█████     | 4509/8920 [1:20:50<56:19,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Teri_Garr.jpg

 51%|█████     | 4510/8920 [1:20:51<57:25,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Suárez_Gómez.jpg

 51%|█████     | 4511/8920 [1:20:51<45:16,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emile_Griffith.jpg

 51%|█████     | 4512/8920 [1:20:51<36:28,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amartya_Sen.jpg

 51%|█████     | 4513/8920 [1:20:51<30:31,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/August_Wilson.jpg

 51%|█████     | 4514/8920 [1:20:52<36:32,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Hull.jpg

 51%|█████     | 4515/8920 [1:20:52<32:23,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Nilsson.jpg

 51%|█████     | 4516/8920 [1:20:55<1:20:33,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorne_Michaels.jpg

 51%|█████     | 4517/8920 [1:20:55<1:01:47,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Shula.jpg

 51%|█████     | 4518/8920 [1:20:57<1:11:08,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glenda_Jackson.jpg

 51%|█████     | 4519/8920 [1:20:57<1:01:36,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Albee.jpg

 51%|█████     | 4520/8920 [1:20:58<1:10:05,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jalal_Talabani.jpg

 51%|█████     | 4521/8920 [1:21:01<1:48:53,  1.49s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilma_Mankiller.jpg

 51%|█████     | 4522/8920 [1:21:03<1:52:14,  1.53s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashley_Cooper.jpg

 51%|█████     | 4523/8920 [1:21:03<1:24:30,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Marichal.jpg

 51%|█████     | 4524/8920 [1:21:03<1:10:05,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Nitschke.jpg

 51%|█████     | 4525/8920 [1:21:04<1:02:29,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chet_Baker.jpg

 51%|█████     | 4526/8920 [1:21:04<49:43,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calvin_Klein.jpg

 51%|█████     | 4527/8920 [1:21:06<1:01:17,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Boyle.jpg

 51%|█████     | 4528/8920 [1:21:06<55:23,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darlene_Hard.jpg

 51%|█████     | 4529/8920 [1:21:07<49:02,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Perkins.jpg

 51%|█████     | 4530/8920 [1:21:07<40:08,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Caan.jpg

 51%|█████     | 4531/8920 [1:21:08<59:52,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Earl_Anthony.jpg

 51%|█████     | 4532/8920 [1:21:10<1:14:41,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Tarkovsky.jpg

 51%|█████     | 4533/8920 [1:21:10<1:05:51,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willis_Reed.jpg

 51%|█████     | 4534/8920 [1:21:12<1:14:31,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Lange.jpg

 51%|█████     | 4535/8920 [1:21:12<1:05:14,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Page.jpg

 51%|█████     | 4536/8920 [1:21:13<51:44,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Spector.jpg

 51%|█████     | 4537/8920 [1:21:13<51:28,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Unser.jpg

 51%|█████     | 4538/8920 [1:21:15<1:02:58,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolph_Schayes.jpg

 51%|█████     | 4539/8920 [1:21:15<1:00:54,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lou_Brock.jpg

 51%|█████     | 4540/8920 [1:21:16<1:03:56,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gale_Sayers.jpg

 51%|█████     | 4541/8920 [1:21:17<54:54,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Trevino.jpg

 51%|█████     | 4542/8920 [1:21:17<45:56,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manmohan_Singh.jpg

 51%|█████     | 4543/8920 [1:21:18<54:29,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Allen_Toussaint.jpg

 51%|█████     | 4544/8920 [1:21:18<44:13,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cormac_Mccarthy.jpg

 51%|█████     | 4545/8920 [1:21:20<1:11:03,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marsha_P._Johnson.jpg

 51%|█████     | 4546/8920 [1:21:21<1:13:14,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franz_Beckenbauer.jpg

 51%|█████     | 4547/8920 [1:21:23<1:27:07,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Cowdrey.jpg

 51%|█████     | 4548/8920 [1:21:24<1:17:11,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonny_Ramadhin.jpg

 51%|█████     | 4549/8920 [1:21:25<1:16:53,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/F._Murray_Abraham.jpg

 51%|█████     | 4550/8920 [1:21:25<1:00:56,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Ilitch.jpg

 51%|█████     | 4551/8920 [1:21:27<1:19:10,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gaylord_Perry.jpg

 51%|█████     | 4552/8920 [1:21:27<1:01:07,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Plácido_Domingo.jpg

 51%|█████     | 4553/8920 [1:21:28<1:15:04,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernie_Madoff.jpg

 51%|█████     | 4554/8920 [1:21:30<1:28:19,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alberto_Fujimori.jpg

 51%|█████     | 4555/8920 [1:21:31<1:15:04,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacques_Brel.jpg

 51%|█████     | 4556/8920 [1:21:31<58:42,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean-Paul_Belmondo.jpg

 51%|█████     | 4557/8920 [1:21:31<46:47,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isaac_Hayes.jpg

 51%|█████     | 4558/8920 [1:21:31<37:28,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raymond_Kopa.jpg

 51%|█████     | 4559/8920 [1:21:32<32:49,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Winkler.jpg

 51%|█████     | 4560/8920 [1:21:32<35:37,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hobart_"Hobie"_Alter.jpg

 51%|█████     | 4561/8920 [1:21:33<36:05,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Hagman.jpg

 51%|█████     | 4562/8920 [1:21:34<42:19,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terry_Sawchuk.jpg

 51%|█████     | 4563/8920 [1:21:34<39:52,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Bogdanovich.jpg

 51%|█████     | 4564/8920 [1:21:34<35:18,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Arbour.jpg

 51%|█████     | 4565/8920 [1:21:35<29:50,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Voight.jpg

 51%|█████     | 4566/8920 [1:21:36<48:01,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hu_Jintao.jpg

 51%|█████     | 4567/8920 [1:21:36<38:13,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Koch.jpg

 51%|█████     | 4568/8920 [1:21:37<49:56,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Stevens.jpg

 51%|█████     | 4569/8920 [1:21:37<40:26,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richie_Benaud.jpg

 51%|█████     | 4570/8920 [1:21:38<33:04,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Sloan.jpg

 51%|█████     | 4571/8920 [1:21:38<37:14,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Casper.jpg

 51%|█████▏    | 4572/8920 [1:21:39<32:16,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Epstein.jpg

 51%|█████▏    | 4573/8920 [1:21:39<36:29,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dick_Button.jpg

 51%|█████▏    | 4574/8920 [1:21:41<55:35,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ángel_Cordero_Jr..jpg

 51%|█████▏    | 4575/8920 [1:21:41<51:50,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Kevorkian.jpg

 51%|█████▏    | 4576/8920 [1:21:43<1:21:07,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Herman.jpg

 51%|█████▏    | 4577/8920 [1:21:45<1:43:31,  1.43s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofia_Muratova.jpg

 51%|█████▏    | 4578/8920 [1:21:46<1:18:15,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Ann_Howes.jpg

 51%|█████▏    | 4579/8920 [1:21:46<1:01:27,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seamus_Heaney.jpg

 51%|█████▏    | 4580/8920 [1:21:47<59:42,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christine_Mcvie.jpg

 51%|█████▏    | 4581/8920 [1:21:47<47:04,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Turner.jpg

 51%|█████▏    | 4582/8920 [1:21:48<56:15,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Drysdale.jpg

 51%|█████▏    | 4583/8920 [1:21:48<46:55,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_A._Steitz.jpg

 51%|█████▏    | 4584/8920 [1:21:51<1:20:46,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Kingsley.jpg

 51%|█████▏    | 4585/8920 [1:21:52<1:21:01,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Benchley.jpg

 51%|█████▏    | 4586/8920 [1:21:52<1:01:45,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Hawke.jpg

 51%|█████▏    | 4587/8920 [1:21:53<1:09:07,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Norton.jpg

 51%|█████▏    | 4588/8920 [1:21:54<1:02:27,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Holtzman.jpg

 51%|█████▏    | 4589/8920 [1:21:54<56:16,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Jennings.jpg

 51%|█████▏    | 4590/8920 [1:21:55<58:00,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Earl_Weaver.jpg

 51%|█████▏    | 4591/8920 [1:21:56<57:27,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Pearson.jpg

 51%|█████▏    | 4592/8920 [1:21:56<46:03,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Stockton.jpg

 51%|█████▏    | 4593/8920 [1:21:57<54:28,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Kaline.jpg

 52%|█████▏    | 4594/8920 [1:21:58<44:47,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Clemente.jpg

 52%|█████▏    | 4595/8920 [1:21:58<36:13,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Graham_Hill.jpg

 52%|█████▏    | 4596/8920 [1:21:59<43:13,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Krzysztof_Penderecki.jpg

 52%|█████▏    | 4597/8920 [1:21:59<35:57,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Bakker.jpg

 52%|█████▏    | 4598/8920 [1:21:59<31:49,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vaughn_Meader.jpg

 52%|█████▏    | 4599/8920 [1:22:00<38:48,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lew_Hoad.jpg

 52%|█████▏    | 4600/8920 [1:22:02<1:00:12,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Sagan.jpg

 52%|█████▏    | 4601/8920 [1:22:03<1:04:15,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Maris.jpg

 52%|█████▏    | 4602/8920 [1:22:03<52:29,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Pettit.jpg

 52%|█████▏    | 4603/8920 [1:22:05<1:15:50,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Jones.jpg

 52%|█████▏    | 4604/8920 [1:22:05<1:04:45,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdelaziz_Bouteflika.jpg

 52%|█████▏    | 4605/8920 [1:22:06<1:00:59,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wang_Hongwen.jpg

 52%|█████▏    | 4606/8920 [1:22:06<48:44,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dietrich_Mateschitz.jpg

 52%|█████▏    | 4607/8920 [1:22:07<47:51,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Stargell.jpg

 52%|█████▏    | 4608/8920 [1:22:07<39:52,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helmut_Kohl.jpg

 52%|█████▏    | 4609/8920 [1:22:08<47:03,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Havlicek.jpg

 52%|█████▏    | 4610/8920 [1:22:08<39:19,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Allison.jpg

 52%|█████▏    | 4611/8920 [1:22:10<52:00,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anita_Ekberg.jpg

 52%|█████▏    | 4612/8920 [1:22:11<56:57,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernie_Ecclestone.jpg

 52%|█████▏    | 4613/8920 [1:22:11<47:43,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilson_Pickett.jpg

 52%|█████▏    | 4614/8920 [1:22:11<40:41,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Waylon_Jennings.jpg

 52%|█████▏    | 4615/8920 [1:22:12<34:33,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marty_Schottenheimer.jpg

 52%|█████▏    | 4616/8920 [1:22:12<29:14,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luis_Suárez_Miramontes.jpg

 52%|█████▏    | 4617/8920 [1:22:13<51:19,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rocky_Colavito.jpg

 52%|█████▏    | 4618/8920 [1:22:13<40:54,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Merle_Haggard.jpg

 52%|█████▏    | 4619/8920 [1:22:14<42:55,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Ventura.jpg

 52%|█████▏    | 4620/8920 [1:22:14<36:58,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roy_Orbison.jpg

 52%|█████▏    | 4621/8920 [1:22:15<32:16,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessye_Norman.jpg

 52%|█████▏    | 4622/8920 [1:22:15<27:49,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Steinbrenner.jpg

 52%|█████▏    | 4623/8920 [1:22:16<44:55,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gilberto_Rodríguez_Orejuela.jpg

 52%|█████▏    | 4624/8920 [1:22:18<1:07:38,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Lester.jpg

 52%|█████▏    | 4625/8920 [1:22:18<52:28,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Best.jpg

 52%|█████▏    | 4626/8920 [1:22:18<42:03,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ziaur_Rahman.jpg

 52%|█████▏    | 4627/8920 [1:22:20<56:47,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Garner.jpg

 52%|█████▏    | 4628/8920 [1:22:21<1:11:09,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rip_Taylor.jpg

 52%|█████▏    | 4629/8920 [1:22:23<1:26:03,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roy_Emerson.jpg

 52%|█████▏    | 4630/8920 [1:22:23<1:14:18,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Kennedy.jpg

 52%|█████▏    | 4631/8920 [1:22:24<1:14:14,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davy_Jones.jpg

 52%|█████▏    | 4632/8920 [1:22:25<59:00,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raquel_Welch.jpg

 52%|█████▏    | 4633/8920 [1:22:25<46:02,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hanif_Mohammad.jpg

 52%|█████▏    | 4634/8920 [1:22:25<36:52,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellen_Burstyn.jpg

 52%|█████▏    | 4635/8920 [1:22:25<31:07,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curt_Flood.jpg

 52%|█████▏    | 4636/8920 [1:22:26<27:49,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Shoemaker.jpg

 52%|█████▏    | 4637/8920 [1:22:26<25:05,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Debusschere.jpg

 52%|█████▏    | 4638/8920 [1:22:27<33:21,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Denver.jpg

 52%|█████▏    | 4639/8920 [1:22:27<37:20,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricky_Nelson.jpg

 52%|█████▏    | 4640/8920 [1:22:28<32:06,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Feigenbaum.jpg

 52%|█████▏    | 4641/8920 [1:22:28<30:55,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spalding_Gray.jpg

 52%|█████▏    | 4642/8920 [1:22:29<34:54,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Delillo.jpg

 52%|█████▏    | 4643/8920 [1:22:30<55:05,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harold_Pinter.jpg

 52%|█████▏    | 4644/8920 [1:22:31<58:16,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_King.jpg

 52%|█████▏    | 4645/8920 [1:22:32<51:52,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gene_Wilder.jpg

 52%|█████▏    | 4646/8920 [1:22:32<42:19,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Cooke.jpg

 52%|█████▏    | 4647/8920 [1:22:32<42:45,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elston_Howard.jpg

 52%|█████▏    | 4648/8920 [1:22:33<45:33,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patsy_Cline.jpg

 52%|█████▏    | 4649/8920 [1:22:34<38:33,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaclyn_Smith.jpg

 52%|█████▏    | 4650/8920 [1:22:34<38:57,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Pesci.jpg

 52%|█████▏    | 4651/8920 [1:22:35<40:20,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carolyn_Jones.jpg

 52%|█████▏    | 4652/8920 [1:22:36<58:56,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Mccovey.jpg

 52%|█████▏    | 4653/8920 [1:22:36<47:06,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Robinson.jpg

 52%|█████▏    | 4654/8920 [1:22:37<38:54,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Rosewall.jpg

 52%|█████▏    | 4655/8920 [1:22:37<34:30,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Burt_Reynolds.jpg

 52%|█████▏    | 4656/8920 [1:22:37<29:20,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Montgomery.jpg

 52%|█████▏    | 4657/8920 [1:22:37<25:31,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cass_Elliot.jpg

 52%|█████▏    | 4658/8920 [1:22:38<38:44,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nora_Ephron.jpg

 52%|█████▏    | 4659/8920 [1:22:39<33:29,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Bunning.jpg

 52%|█████▏    | 4660/8920 [1:22:40<40:25,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ross_Perot.jpg

 52%|█████▏    | 4661/8920 [1:22:40<34:58,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Pepitone.jpg

 52%|█████▏    | 4663/8920 [1:22:41<35:15,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Earl_Lloyd.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fela_Kuti.jpg

 52%|█████▏    | 4664/8920 [1:22:41<31:49,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gene_Littler.jpg

 52%|█████▏    | 4665/8920 [1:22:42<36:34,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betsy_Rawls.jpg

 52%|█████▏    | 4666/8920 [1:22:42<31:55,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Sabol.jpg

 52%|█████▏    | 4667/8920 [1:22:44<50:25,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandy_Koufax.jpg

 52%|█████▏    | 4668/8920 [1:22:45<1:04:41,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Wayne_Gacy.jpg

 52%|█████▏    | 4669/8920 [1:22:45<52:39,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Hopper.jpg

 52%|█████▏    | 4670/8920 [1:22:46<42:56,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_A._Romero.jpg

 52%|█████▏    | 4671/8920 [1:22:46<36:11,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean_Béliveau.jpg

 52%|█████▏    | 4672/8920 [1:22:46<30:28,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Player.jpg

 52%|█████▏    | 4673/8920 [1:22:47<47:39,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Flynt.jpg

 52%|█████▏    | 4674/8920 [1:22:48<47:10,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Summerall.jpg

 52%|█████▏    | 4675/8920 [1:22:49<1:01:04,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loretta_Lynn.jpg

 52%|█████▏    | 4676/8920 [1:22:50<1:02:50,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Nichols.jpg

 52%|█████▏    | 4677/8920 [1:22:51<49:38,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Unitas.jpg

 52%|█████▏    | 4678/8920 [1:22:51<39:33,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Whitey_Ford.jpg

 52%|█████▏    | 4679/8920 [1:22:51<33:40,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Springer.jpg

 52%|█████▏    | 4680/8920 [1:22:51<28:51,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Withers.jpg

 52%|█████▏    | 4681/8920 [1:22:52<25:21,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariel_Sharon.jpg

 52%|█████▏    | 4682/8920 [1:22:52<23:30,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kofi_Annan.jpg

 52%|█████▎    | 4683/8920 [1:22:52<21:14,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Sutton.jpg

 53%|█████▎    | 4684/8920 [1:22:52<22:39,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Kaczynski.jpg

 53%|█████▎    | 4685/8920 [1:22:53<21:34,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conway_Twitty.jpg

 53%|█████▎    | 4686/8920 [1:22:53<26:42,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruth_Bader_Ginsburg.jpg

 53%|█████▎    | 4687/8920 [1:22:54<23:22,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Lightfoot.jpg

 53%|█████▎    | 4688/8920 [1:22:54<29:28,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Mujica.jpg

 53%|█████▎    | 4689/8920 [1:22:54<27:14,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muhammadu_Buhari.jpg

 53%|█████▎    | 4690/8920 [1:22:55<32:52,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Martin.jpg

 53%|█████▎    | 4691/8920 [1:22:55<28:36,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Beck.jpg

 53%|█████▎    | 4692/8920 [1:22:57<58:50,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Bixby.jpg

 53%|█████▎    | 4693/8920 [1:22:58<56:54,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hayao_Miyazaki.jpg

 53%|█████▎    | 4694/8920 [1:22:59<51:48,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Frost.jpg

 53%|█████▎    | 4695/8920 [1:23:00<1:06:55,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mel_Stottlemyre.jpg

 53%|█████▎    | 4696/8920 [1:23:01<58:33,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Hawking.jpg

 53%|█████▎    | 4697/8920 [1:23:02<1:06:58,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Duvall.jpg

 53%|█████▎    | 4698/8920 [1:23:03<1:03:14,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Trabert.jpg

 53%|█████▎    | 4699/8920 [1:23:04<1:16:38,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernie_Banks.jpg

 53%|█████▎    | 4700/8920 [1:23:05<1:13:06,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Marshall.jpg

 53%|█████▎    | 4701/8920 [1:23:06<1:10:42,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Bouton.jpg

 53%|█████▎    | 4702/8920 [1:23:07<1:14:13,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Strouse.jpg

 53%|█████▎    | 4703/8920 [1:23:08<1:05:56,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Parkinson.jpg

 53%|█████▎    | 4704/8920 [1:23:08<53:23,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Koch.jpg

 53%|█████▎    | 4705/8920 [1:23:09<56:00,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Alda.jpg

 53%|█████▎    | 4706/8920 [1:23:09<44:56,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Kerry.jpg

 53%|█████▎    | 4707/8920 [1:23:11<1:09:21,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ferguson_Jenkins.jpg

 53%|█████▎    | 4708/8920 [1:23:12<1:16:13,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louise_Fletcher.jpg

 53%|█████▎    | 4709/8920 [1:23:13<1:06:06,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rod_Taylor.jpg

 53%|█████▎    | 4710/8920 [1:23:13<56:49,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imre_Kertész.jpg

 53%|█████▎    | 4711/8920 [1:23:14<44:56,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Perkins.jpg

 53%|█████▎    | 4712/8920 [1:23:14<46:46,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Diamond.jpg

 53%|█████▎    | 4713/8920 [1:23:15<38:21,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Bueno.jpg

 53%|█████▎    | 4714/8920 [1:23:16<49:17,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glen_Campbell.jpg

 53%|█████▎    | 4715/8920 [1:23:17<56:23,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samuel_C._C._Ting.jpg

 53%|█████▎    | 4716/8920 [1:23:18<58:27,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Mays.jpg

 53%|█████▎    | 4717/8920 [1:23:19<1:08:23,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Thomson.jpg

 53%|█████▎    | 4718/8920 [1:23:20<1:10:04,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Safire.jpg

 53%|█████▎    | 4719/8920 [1:23:20<54:47,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maureen_Connolly.jpg

 53%|█████▎    | 4720/8920 [1:23:21<43:51,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Sondheim.jpg

 53%|█████▎    | 4721/8920 [1:23:21<34:56,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Philippe_De_Broca.jpg

 53%|█████▎    | 4722/8920 [1:23:22<47:36,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Cocker.jpg

 53%|█████▎    | 4723/8920 [1:23:22<38:20,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathy_Whitworth.jpg

 53%|█████▎    | 4724/8920 [1:23:24<56:07,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Plummer.jpg

 53%|█████▎    | 4725/8920 [1:23:25<1:05:02,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kurt_Nielsen.jpg

 53%|█████▎    | 4726/8920 [1:23:25<51:49,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Davis.jpg

 53%|█████▎    | 4727/8920 [1:23:26<1:02:28,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooks_Robinson.jpg

 53%|█████▎    | 4728/8920 [1:23:28<1:10:52,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abebe_Bikila.jpg

 53%|█████▎    | 4729/8920 [1:23:28<55:17,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lynn_Redgrave.jpg

 53%|█████▎    | 4730/8920 [1:23:29<56:00,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Hughes.jpg

 53%|█████▎    | 4731/8920 [1:23:29<46:19,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buddy_Holly.jpg

 53%|█████▎    | 4732/8920 [1:23:30<55:21,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emmett_Till.jpg

 53%|█████▎    | 4733/8920 [1:23:32<1:06:49,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Niekro.jpg

 53%|█████▎    | 4734/8920 [1:23:32<52:50,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donna_Caponi.jpg

 53%|█████▎    | 4735/8920 [1:23:33<51:42,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Harris.jpg

 53%|█████▎    | 4736/8920 [1:23:34<57:30,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonard_Nimoy.jpg

 53%|█████▎    | 4737/8920 [1:23:34<45:24,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dick_Clark.jpg

 53%|█████▎    | 4738/8920 [1:23:35<59:14,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maggie_Smith.jpg

 53%|█████▎    | 4739/8920 [1:23:36<50:29,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Belzer.jpg

 53%|█████▎    | 4740/8920 [1:23:37<1:11:15,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Gotti.jpg

 53%|█████▎    | 4741/8920 [1:23:38<1:11:15,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Temple.jpg

 53%|█████▎    | 4742/8920 [1:23:39<54:52,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tammy_Wynette.jpg

 53%|█████▎    | 4743/8920 [1:23:39<43:21,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Slim.jpg

 53%|█████▎    | 4744/8920 [1:23:39<37:42,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hank_Aaron.jpg

 53%|█████▎    | 4745/8920 [1:23:39<30:54,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arnold_Palmer.jpg

 53%|█████▎    | 4746/8920 [1:23:40<35:40,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dick_Cheney.jpg

 53%|█████▎    | 4747/8920 [1:23:41<53:19,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Corazon_Aquino.jpg

 53%|█████▎    | 4748/8920 [1:23:43<1:15:14,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vidal_Sassoon.jpg

 53%|█████▎    | 4749/8920 [1:23:43<57:18,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Frazier.jpg

 53%|█████▎    | 4750/8920 [1:23:44<46:35,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Sheridan.jpg

 53%|█████▎    | 4751/8920 [1:23:45<1:07:41,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Kuklinski.jpg

 53%|█████▎    | 4752/8920 [1:23:46<52:19,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Brown.jpg

 53%|█████▎    | 4753/8920 [1:23:47<56:20,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Hopkins.jpg

 53%|█████▎    | 4754/8920 [1:23:47<52:06,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Devito.jpg

 53%|█████▎    | 4755/8920 [1:23:47<41:28,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sydney_Pollack.jpg

 53%|█████▎    | 4756/8920 [1:23:48<34:47,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Astronaut_Michael_Collins.jpg

 53%|█████▎    | 4757/8920 [1:23:48<30:06,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_King.jpg

 53%|█████▎    | 4758/8920 [1:23:48<26:31,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonny_Liston.jpg

 53%|█████▎    | 4759/8920 [1:23:49<39:12,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maya_Angelou.jpg

 53%|█████▎    | 4760/8920 [1:23:50<43:23,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonard_Cohen.jpg

 53%|█████▎    | 4762/8920 [1:23:51<34:57,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dionne_Warwick.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Lee_Lewis.jpg

 53%|█████▎    | 4763/8920 [1:23:52<52:23,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Wagner.jpg

 53%|█████▎    | 4764/8920 [1:23:52<41:10,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salman_Bin_Abdulaziz_Al_Saud.jpg

 53%|█████▎    | 4765/8920 [1:23:54<56:41,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Pryor.jpg

 53%|█████▎    | 4766/8920 [1:23:54<44:55,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billie_Jean_King.jpg

 53%|█████▎    | 4767/8920 [1:23:55<43:28,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mobutu_Sese_Seko.jpg

 53%|█████▎    | 4768/8920 [1:23:55<37:05,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faye_Dunaway.jpg

 53%|█████▎    | 4769/8920 [1:23:55<30:54,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Crichton.jpg

 53%|█████▎    | 4770/8920 [1:23:55<26:44,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Robinson.jpg

 53%|█████▎    | 4771/8920 [1:23:56<23:46,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacques_Chirac.jpg

 53%|█████▎    | 4772/8920 [1:23:57<41:54,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Casey_Kasem.jpg

 54%|█████▎    | 4773/8920 [1:23:58<45:13,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Gibbs.jpg

 54%|█████▎    | 4774/8920 [1:23:58<36:16,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Dean.jpg

 54%|█████▎    | 4775/8920 [1:23:58<30:44,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grace_Kelly.jpg

 54%|█████▎    | 4776/8920 [1:23:59<42:38,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Landon.jpg

 54%|█████▎    | 4777/8920 [1:23:59<35:02,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bo_Diddley.jpg

 54%|█████▎    | 4778/8920 [1:24:00<31:05,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Young.jpg

 54%|█████▎    | 4779/8920 [1:24:00<31:41,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Zappa.jpg

 54%|█████▎    | 4780/8920 [1:24:03<1:17:32,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Richards.jpg

 54%|█████▎    | 4781/8920 [1:24:06<1:49:25,  1.59s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Winnie_Mandela.jpg

 54%|█████▎    | 4782/8920 [1:24:06<1:23:10,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_White.jpg

 54%|█████▎    | 4783/8920 [1:24:06<1:04:30,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Charles.jpg

 54%|█████▎    | 4784/8920 [1:24:07<57:23,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Trebek.jpg

 54%|█████▎    | 4785/8920 [1:24:08<1:05:59,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alain_Delon.jpg

 54%|█████▎    | 4786/8920 [1:24:09<1:03:59,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Goldie_Hawn.jpg

 54%|█████▎    | 4787/8920 [1:24:11<1:20:43,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mickey_Mantle.jpg

 54%|█████▎    | 4788/8920 [1:24:11<1:01:22,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hafez_Al-Assad.jpg

 54%|█████▎    | 4789/8920 [1:24:11<47:58,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jong-Il.jpg

 54%|█████▎    | 4790/8920 [1:24:11<38:16,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hissène_Habré.jpg

 54%|█████▎    | 4791/8920 [1:24:12<43:58,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Estridge.jpg

 54%|█████▎    | 4792/8920 [1:24:13<49:42,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefanie_Powers.jpg

 54%|█████▎    | 4793/8920 [1:24:14<45:00,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Evans.jpg

 54%|█████▎    | 4794/8920 [1:24:14<39:22,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Lloyd.jpg

 54%|█████▍    | 4795/8920 [1:24:15<40:05,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francis_Gary_Powers.jpg

 54%|█████▍    | 4796/8920 [1:24:15<34:14,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Lee.jpg

 54%|█████▍    | 4797/8920 [1:24:15<29:15,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joan_Rivers.jpg

 54%|█████▍    | 4798/8920 [1:24:15<25:06,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Lucas.jpg

 54%|█████▍    | 4799/8920 [1:24:16<23:35,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Manson.jpg

 54%|█████▍    | 4800/8920 [1:24:16<22:12,  3.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Douglas_Hofstadter.jpg

 54%|█████▍    | 4801/8920 [1:24:16<20:40,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Keating.jpg

 54%|█████▍    | 4802/8920 [1:24:17<25:51,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Travers.jpg

 54%|█████▍    | 4803/8920 [1:24:17<29:53,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_C._Bogle.jpg

 54%|█████▍    | 4804/8920 [1:24:17<25:18,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Icahn.jpg

 54%|█████▍    | 4805/8920 [1:24:18<23:04,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Floyd_Patterson.jpg

 54%|█████▍    | 4806/8920 [1:24:18<28:18,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberta_Flack.jpg

 54%|█████▍    | 4807/8920 [1:24:20<57:39,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Denver.jpg

 54%|█████▍    | 4808/8920 [1:24:20<45:12,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Fauci.jpg

 54%|█████▍    | 4809/8920 [1:24:21<38:02,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Woody_Allen.jpg

 54%|█████▍    | 4810/8920 [1:24:23<1:16:26,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Scorsese.jpg

 54%|█████▍    | 4811/8920 [1:24:25<1:31:20,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nancy_Richey.jpg

 54%|█████▍    | 4812/8920 [1:24:27<1:35:33,  1.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nursultan_Nazarbayev.jpg

 54%|█████▍    | 4813/8920 [1:24:27<1:12:18,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Simone.jpg

 54%|█████▍    | 4814/8920 [1:24:27<55:25,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Little_Richard.jpg

 54%|█████▍    | 4815/8920 [1:24:27<43:33,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bette_Midler.jpg

 54%|█████▍    | 4816/8920 [1:24:28<39:07,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Newhart.jpg

 54%|█████▍    | 4817/8920 [1:24:28<32:03,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Connery.jpg

 54%|█████▍    | 4818/8920 [1:24:28<32:26,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roald_Hoffmann.jpg

 54%|█████▍    | 4819/8920 [1:24:29<31:43,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Munsch.jpg

 54%|█████▍    | 4820/8920 [1:24:29<32:01,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Lefkowitz.jpg

 54%|█████▍    | 4821/8920 [1:24:30<27:20,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Mccain.jpg

 54%|█████▍    | 4822/8920 [1:24:30<38:49,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Lithgow.jpg

 54%|█████▍    | 4823/8920 [1:24:31<41:44,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walt_Frazier.jpg

 54%|█████▍    | 4824/8920 [1:24:31<34:59,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Astin.jpg

 54%|█████▍    | 4825/8920 [1:24:32<29:44,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raúl_Castro.jpg

 54%|█████▍    | 4826/8920 [1:24:33<47:02,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Akerlof.jpg

 54%|█████▍    | 4827/8920 [1:24:34<56:40,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenny_Rogers.jpg

 54%|█████▍    | 4828/8920 [1:24:36<1:07:23,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Collins.jpg

 54%|█████▍    | 4829/8920 [1:24:36<52:50,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Davis.jpg

 54%|█████▍    | 4830/8920 [1:24:36<42:55,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bert_Campaneris.jpg

 54%|█████▍    | 4831/8920 [1:24:36<36:10,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Goulet.jpg

 54%|█████▍    | 4832/8920 [1:24:37<31:12,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roch_Carrier.jpg

 54%|█████▍    | 4833/8920 [1:24:37<36:09,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sonny_Bono.jpg

 54%|█████▍    | 4834/8920 [1:24:38<29:44,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Bannister.jpg

 54%|█████▍    | 4835/8920 [1:24:38<36:12,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sepp_Blatter.jpg

 54%|█████▍    | 4836/8920 [1:24:39<35:22,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Torre.jpg

 54%|█████▍    | 4837/8920 [1:24:40<42:05,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Quincy_Jones_Jr.jpg

 54%|█████▍    | 4838/8920 [1:24:40<34:03,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Sutherland.jpg

 54%|█████▍    | 4839/8920 [1:24:41<35:56,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Ashe.jpg

 54%|█████▍    | 4840/8920 [1:24:41<39:47,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Garcia.jpg

 54%|█████▍    | 4841/8920 [1:24:42<33:23,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Knox-Johnston.jpg

 54%|█████▍    | 4842/8920 [1:24:42<31:44,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ibrahim_Babangida.jpg

 54%|█████▍    | 4843/8920 [1:24:44<1:00:29,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ethel_Kennedy.jpg

 54%|█████▍    | 4844/8920 [1:24:44<48:06,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Cunningham.jpg

 54%|█████▍    | 4845/8920 [1:24:44<39:39,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rudy_Giuliani.jpg

 54%|█████▍    | 4846/8920 [1:24:45<40:04,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denny_Mclain.jpg

 54%|█████▍    | 4847/8920 [1:24:46<47:25,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ralph_Nader.jpg

 54%|█████▍    | 4848/8920 [1:24:47<48:05,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helen_Mirren.jpg

 54%|█████▍    | 4849/8920 [1:24:47<39:19,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Charles.jpg

 54%|█████▍    | 4850/8920 [1:24:47<38:20,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Howard.jpg

 54%|█████▍    | 4851/8920 [1:24:48<31:43,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tenley_Albright.jpg

 54%|█████▍    | 4852/8920 [1:24:50<1:03:20,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carole_King.jpg

 54%|█████▍    | 4853/8920 [1:24:51<1:09:19,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Namath.jpg

 54%|█████▍    | 4854/8920 [1:24:51<53:29,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacob_Zuma.jpg

 54%|█████▍    | 4855/8920 [1:24:53<1:04:49,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oscar_Robertson.jpg

 54%|█████▍    | 4856/8920 [1:24:53<50:24,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Václav_Havel.jpg

 54%|█████▍    | 4857/8920 [1:24:53<40:07,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Judi_Dench.jpg

 54%|█████▍    | 4858/8920 [1:24:53<33:08,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Hockney.jpg

 54%|█████▍    | 4859/8920 [1:24:54<31:11,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/F._W._De_Klerk.jpg

 54%|█████▍    | 4860/8920 [1:24:54<27:10,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Tyler_Moore.jpg

 54%|█████▍    | 4861/8920 [1:24:56<51:57,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Russell.jpg

 55%|█████▍    | 4862/8920 [1:24:56<40:55,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aretha_Franklin.jpg

 55%|█████▍    | 4863/8920 [1:24:56<41:45,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joni_Mitchell.jpg

 55%|█████▍    | 4864/8920 [1:24:57<33:56,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Roche.jpg

 55%|█████▍    | 4865/8920 [1:24:57<28:35,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_La_Russa.jpg

 55%|█████▍    | 4866/8920 [1:24:57<30:59,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Ferguson.jpg

 55%|█████▍    | 4867/8920 [1:24:59<43:19,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_Levinson.jpg

 55%|█████▍    | 4868/8920 [1:24:59<37:30,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordie_Howe.jpg

 55%|█████▍    | 4869/8920 [1:24:59<32:00,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toni_Morrison.jpg

 55%|█████▍    | 4870/8920 [1:24:59<28:07,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vigdís_Finnbogadóttir.jpg

 55%|█████▍    | 4871/8920 [1:25:00<27:08,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerhard_Schröder.jpg

 55%|█████▍    | 4872/8920 [1:25:00<24:22,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andy_Warhol.jpg

 55%|█████▍    | 4873/8920 [1:25:01<42:16,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Carlos_I.jpg

 55%|█████▍    | 4874/8920 [1:25:02<34:23,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Silvio_Berlusconi.jpg

 55%|█████▍    | 4875/8920 [1:25:02<37:26,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Estrada.jpg

 55%|█████▍    | 4876/8920 [1:25:03<33:10,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Kraft.jpg

 55%|█████▍    | 4877/8920 [1:25:03<28:41,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roy_Demeo.jpg

 55%|█████▍    | 4878/8920 [1:25:03<29:32,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Selleck.jpg

 55%|█████▍    | 4879/8920 [1:25:05<54:40,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Warren_Beatty.jpg

 55%|█████▍    | 4880/8920 [1:25:05<44:05,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Bassey.jpg

 55%|█████▍    | 4881/8920 [1:25:06<44:46,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Cosby.jpg

 55%|█████▍    | 4882/8920 [1:25:06<35:45,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julie_Christie.jpg

 55%|█████▍    | 4883/8920 [1:25:08<1:06:59,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Radovan_Karadžić.jpg

 55%|█████▍    | 4884/8920 [1:25:09<59:19,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ban_Ki-Moon.jpg

 55%|█████▍    | 4885/8920 [1:25:09<46:57,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Ditka.jpg

 55%|█████▍    | 4886/8920 [1:25:09<38:31,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Stewart.jpg

 55%|█████▍    | 4887/8920 [1:25:10<39:28,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rita_Moreno.jpg

 55%|█████▍    | 4888/8920 [1:25:11<37:49,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Kershaw.jpg

 55%|█████▍    | 4889/8920 [1:25:11<40:04,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Mahovlich.jpg

 55%|█████▍    | 4890/8920 [1:25:12<40:24,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rod_Laver.jpg

 55%|█████▍    | 4891/8920 [1:25:12<32:50,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Whitey_Bulger.jpg

 55%|█████▍    | 4892/8920 [1:25:14<1:06:21,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hale_Irwin.jpg

 55%|█████▍    | 4893/8920 [1:25:15<59:58,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Stewart.jpg

 55%|█████▍    | 4894/8920 [1:25:15<47:48,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Ueberroth.jpg

 55%|█████▍    | 4895/8920 [1:25:16<49:59,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Desmond_Tutu.jpg

 55%|█████▍    | 4896/8920 [1:25:16<40:53,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joan_Baez.jpg

 55%|█████▍    | 4897/8920 [1:25:17<35:44,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Nicklaus.jpg

 55%|█████▍    | 4898/8920 [1:25:17<30:02,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hosni_Mubarak.jpg

 55%|█████▍    | 4899/8920 [1:25:17<25:39,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Kay.jpg

 55%|█████▍    | 4900/8920 [1:25:18<28:55,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Judd_Hirsch.jpg

 55%|█████▍    | 4901/8920 [1:25:20<1:00:21,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geraldine_Ferraro.jpg

 55%|█████▍    | 4902/8920 [1:25:20<48:58,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Jones.jpg

 55%|█████▍    | 4903/8920 [1:25:20<39:17,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Gambon.jpg

 55%|█████▍    | 4904/8920 [1:25:21<33:12,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Wood.jpg

 55%|█████▍    | 4905/8920 [1:25:21<29:05,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loretta_Swit.jpg

 55%|█████▌    | 4906/8920 [1:25:22<46:21,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maurice_Sendak.jpg

 55%|█████▌    | 4907/8920 [1:25:23<43:49,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandra_Haynie.jpg

 55%|█████▌    | 4908/8920 [1:25:23<36:43,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Bevel.jpg

 55%|█████▌    | 4909/8920 [1:25:23<29:55,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Max.jpg

 55%|█████▌    | 4910/8920 [1:25:23<25:57,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddy_Merckx.jpg

 55%|█████▌    | 4911/8920 [1:25:25<44:43,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Bloomberg.jpg

 55%|█████▌    | 4912/8920 [1:25:25<35:51,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ratko_Mladić.jpg

 55%|█████▌    | 4913/8920 [1:25:26<40:14,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Walters.jpg

 55%|█████▌    | 4914/8920 [1:25:27<46:12,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shakuntala_Devi.jpg

 55%|█████▌    | 4915/8920 [1:25:27<38:44,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Stoppard.jpg

 55%|█████▌    | 4916/8920 [1:25:27<32:49,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Floyd.jpg

 55%|█████▌    | 4917/8920 [1:25:28<32:07,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herb_Alpert.jpg

 55%|█████▌    | 4918/8920 [1:25:28<35:23,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Petty.jpg

 55%|█████▌    | 4919/8920 [1:25:29<31:12,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Brown.jpg

 55%|█████▌    | 4920/8920 [1:25:30<40:39,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Searle.jpg

 55%|█████▌    | 4921/8920 [1:25:30<33:08,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Walken.jpg

 55%|█████▌    | 4922/8920 [1:25:30<27:47,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nino_Benvenuti.jpg

 55%|█████▌    | 4923/8920 [1:25:32<59:05,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ira_Levin.jpg

 55%|█████▌    | 4924/8920 [1:25:33<1:00:17,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Earl_Jones.jpg

 55%|█████▌    | 4925/8920 [1:25:34<51:23,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacqueline_Kennedy_Onassis.jpg

 55%|█████▌    | 4926/8920 [1:25:34<48:37,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Sheen.jpg

 55%|█████▌    | 4927/8920 [1:25:36<1:02:22,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Davies.jpg

 55%|█████▌    | 4928/8920 [1:25:38<1:30:57,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Crampton.jpg

 55%|█████▌    | 4929/8920 [1:25:39<1:18:43,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Virginia_Wade.jpg

 55%|█████▌    | 4930/8920 [1:25:40<1:19:33,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margaret_Smith_Court.jpg

 55%|█████▌    | 4931/8920 [1:25:41<1:09:31,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carol_Burnett.jpg

 55%|█████▌    | 4932/8920 [1:25:42<1:19:31,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Mcdowell.jpg

 55%|█████▌    | 4933/8920 [1:25:43<1:04:14,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Borman.jpg

 55%|█████▌    | 4934/8920 [1:25:44<1:06:12,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Miller.jpg

 55%|█████▌    | 4935/8920 [1:25:44<52:19,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garfield_Sobers.jpg

 55%|█████▌    | 4936/8920 [1:25:45<1:02:08,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geraldo_Rivera.jpg

 55%|█████▌    | 4937/8920 [1:25:45<48:01,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Johnson.jpg

 55%|█████▌    | 4938/8920 [1:25:46<44:19,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Parcells.jpg

 55%|█████▌    | 4939/8920 [1:25:46<35:34,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larisa_Latynina.jpg

 55%|█████▌    | 4940/8920 [1:25:47<39:46,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Eden.jpg

 55%|█████▌    | 4941/8920 [1:25:48<48:11,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wole_Soyinka.jpg

 55%|█████▌    | 4942/8920 [1:25:50<1:21:30,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oliver_North.jpg

 55%|█████▌    | 4943/8920 [1:25:51<1:02:04,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Hunt.jpg

 55%|█████▌    | 4944/8920 [1:25:51<47:53,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chuck_Norris.jpg

 55%|█████▌    | 4945/8920 [1:25:53<1:11:55,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gloria_Steinem.jpg

 55%|█████▌    | 4946/8920 [1:25:53<1:03:29,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ritchie_Blackmore.jpg

 55%|█████▌    | 4947/8920 [1:25:54<51:23,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Yeltsin.jpg

 55%|█████▌    | 4948/8920 [1:25:54<42:24,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduard_Shevardnadze.jpg

 55%|█████▌    | 4949/8920 [1:25:56<1:14:53,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Newcombe.jpg

 55%|█████▌    | 4950/8920 [1:25:59<1:35:30,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aldrich_Ames.jpg

 56%|█████▌    | 4951/8920 [1:25:59<1:11:35,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lance_Gibbs.jpg

 56%|█████▌    | 4952/8920 [1:25:59<1:00:38,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Dee_Williams.jpg

 56%|█████▌    | 4953/8920 [1:26:00<47:49,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rodrigo_Duterte.jpg

 56%|█████▌    | 4954/8920 [1:26:00<39:04,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Popovich.jpg

 56%|█████▌    | 4955/8920 [1:26:02<1:14:20,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Maiorca.jpg

 56%|█████▌    | 4956/8920 [1:26:03<57:17,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Rice.jpg

 56%|█████▌    | 4957/8920 [1:26:03<44:22,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Nash.jpg

 56%|█████▌    | 4958/8920 [1:26:03<36:37,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Earl_Ray.jpg

 56%|█████▌    | 4959/8920 [1:26:04<35:29,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Carlos.jpg

 56%|█████▌    | 4960/8920 [1:26:04<35:11,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Croce.jpg

 56%|█████▌    | 4961/8920 [1:26:04<30:25,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masanori_Murakami.jpg

 56%|█████▌    | 4962/8920 [1:26:06<1:00:05,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Otis_Redding.jpg

 56%|█████▌    | 4963/8920 [1:26:08<1:08:22,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Warren_Buffett.jpg

 56%|█████▌    | 4964/8920 [1:26:08<53:19,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Lewis.jpg

 56%|█████▌    | 4965/8920 [1:26:09<1:07:15,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Jones.jpg

 56%|█████▌    | 4966/8920 [1:26:10<59:01,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimi_Hendrix.jpg

 56%|█████▌    | 4967/8920 [1:26:11<53:45,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Crumb.jpg

 56%|█████▌    | 4968/8920 [1:26:11<51:59,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Graves.jpg

 56%|█████▌    | 4969/8920 [1:26:12<41:31,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/June_Carter_Cash.jpg

 56%|█████▌    | 4970/8920 [1:26:12<33:37,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Kahneman.jpg

 56%|█████▌    | 4971/8920 [1:26:13<36:31,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Martin.jpg

 56%|█████▌    | 4972/8920 [1:26:13<30:32,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saddam_Hussein.jpg

 56%|█████▌    | 4973/8920 [1:26:13<27:27,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Mondale.jpg

 56%|█████▌    | 4974/8920 [1:26:15<51:08,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Dreesen.jpg

 56%|█████▌    | 4975/8920 [1:26:15<40:17,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Anka.jpg

 56%|█████▌    | 4976/8920 [1:26:15<32:42,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Luther_King_Jr..jpg

 56%|█████▌    | 4977/8920 [1:26:16<38:27,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Lee.jpg

 56%|█████▌    | 4978/8920 [1:26:18<1:00:19,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ard_Schenk.jpg

 56%|█████▌    | 4979/8920 [1:26:19<1:15:47,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Evans.jpg

 56%|█████▌    | 4980/8920 [1:26:21<1:31:20,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Debbie_Harry.jpg

 56%|█████▌    | 4981/8920 [1:26:23<1:31:07,  1.39s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dawn_Fraser.jpg

 56%|█████▌    | 4982/8920 [1:26:23<1:15:50,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A._J._Foyt.jpg

 56%|█████▌    | 4983/8920 [1:26:24<1:04:31,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imelda_Marcos.jpg

 56%|█████▌    | 4984/8920 [1:26:25<1:07:16,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Wilson.jpg

 56%|█████▌    | 4985/8920 [1:26:26<1:04:57,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joel_Grey.jpg

 56%|█████▌    | 4986/8920 [1:26:26<52:08,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Palmer.jpg

 56%|█████▌    | 4987/8920 [1:26:27<42:11,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ann_Haydon-Jones.jpg

 56%|█████▌    | 4988/8920 [1:26:27<44:17,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rod_Stewart.jpg

 56%|█████▌    | 4989/8920 [1:26:28<43:05,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michel_Temer.jpg

 56%|█████▌    | 4990/8920 [1:26:29<42:12,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Carner.jpg

 56%|█████▌    | 4991/8920 [1:26:29<34:25,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ralph_Lauren.jpg

 56%|█████▌    | 4992/8920 [1:26:29<29:50,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amitabh_Bachchan.jpg

 56%|█████▌    | 4993/8920 [1:26:31<1:04:36,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ada_E._Yonath.jpg

 56%|█████▌    | 4994/8920 [1:26:33<1:18:00,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vera_Miles.jpg

 56%|█████▌    | 4995/8920 [1:26:33<1:01:04,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_De_Niro.jpg

 56%|█████▌    | 4996/8920 [1:26:35<1:17:55,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Biden.jpg

 56%|█████▌    | 4997/8920 [1:26:35<59:45,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harvey_Milk.jpg

 56%|█████▌    | 4998/8920 [1:26:36<48:01,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Bradley.jpg

 56%|█████▌    | 4999/8920 [1:26:37<57:09,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Clark.jpg

 56%|█████▌    | 5000/8920 [1:26:37<51:00,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francis_Ford_Coppola.jpg

 56%|█████▌    | 5001/8920 [1:26:38<41:36,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noam_Chomsky.jpg

 56%|█████▌    | 5002/8920 [1:26:39<45:19,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elliott_Gould.jpg

 56%|█████▌    | 5003/8920 [1:26:39<45:42,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_B._Gurdon.jpg

 56%|█████▌    | 5004/8920 [1:26:40<36:23,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harrison_Ford.jpg

 56%|█████▌    | 5005/8920 [1:26:40<31:39,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Packwood.jpg

 56%|█████▌    | 5006/8920 [1:26:40<27:02,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Harvey_Oswald.jpg

 56%|█████▌    | 5007/8920 [1:26:40<23:26,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liz_Claiborne.jpg

 56%|█████▌    | 5008/8920 [1:26:41<30:41,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Rogers.jpg

 56%|█████▌    | 5009/8920 [1:26:41<26:06,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rod_Carew.jpg

 56%|█████▌    | 5010/8920 [1:26:43<57:32,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roman_Polanski.jpg

 56%|█████▌    | 5011/8920 [1:26:44<45:55,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Fischer.jpg

 56%|█████▌    | 5012/8920 [1:26:44<43:30,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Ellison.jpg

 56%|█████▌    | 5013/8920 [1:26:44<35:23,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emmerson_Mnangagwa.jpg

 56%|█████▌    | 5014/8920 [1:26:45<30:24,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anni-Frid_Lyngstad.jpg

 56%|█████▌    | 5015/8920 [1:26:46<37:36,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Townshend.jpg

 56%|█████▌    | 5016/8920 [1:26:47<57:23,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorge_Paulo_Lemann.jpg

 56%|█████▌    | 5017/8920 [1:26:48<52:04,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Grove.jpg

 56%|█████▋    | 5018/8920 [1:26:48<49:26,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Yastrzemski.jpg

 56%|█████▋    | 5019/8920 [1:26:49<51:50,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Newt_Gingrich.jpg

 56%|█████▋    | 5020/8920 [1:26:50<42:48,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Jay_Gould.jpg

 56%|█████▋    | 5021/8920 [1:26:50<36:55,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herbie_Hancock.jpg

 56%|█████▋    | 5022/8920 [1:26:50<32:53,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Major.jpg

 56%|█████▋    | 5023/8920 [1:26:51<28:54,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Morrison.jpg

 56%|█████▋    | 5024/8920 [1:26:51<34:13,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Mulroney.jpg

 56%|█████▋    | 5025/8920 [1:26:52<37:06,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/R._L._Stine.jpg

 56%|█████▋    | 5026/8920 [1:26:52<30:55,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Little_Eva.jpg

 56%|█████▋    | 5027/8920 [1:26:53<27:04,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Schwab.jpg

 56%|█████▋    | 5028/8920 [1:26:53<23:11,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Powell.jpg

 56%|█████▋    | 5029/8920 [1:26:54<30:30,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Redford.jpg

 56%|█████▋    | 5030/8920 [1:26:54<33:17,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dustin_Hoffman.jpg

 56%|█████▋    | 5031/8920 [1:26:55<32:15,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buzz_Aldrin.jpg

 56%|█████▋    | 5032/8920 [1:26:55<33:51,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Maclaine.jpg

 56%|█████▋    | 5033/8920 [1:26:55<27:56,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesse_Jackson.jpg

 56%|█████▋    | 5034/8920 [1:26:56<24:38,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manuel_Noriega.jpg

 56%|█████▋    | 5035/8920 [1:26:56<21:31,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Woodward.jpg

 56%|█████▋    | 5036/8920 [1:26:56<19:29,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janis_Joplin.jpg

 56%|█████▋    | 5037/8920 [1:26:56<19:30,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aung_San_Suu_Kyi.jpg

 56%|█████▋    | 5038/8920 [1:26:58<41:07,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muhammad_Yunus.jpg

 56%|█████▋    | 5039/8920 [1:26:58<34:07,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Che_Guevara.jpg

 57%|█████▋    | 5040/8920 [1:26:59<41:44,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andreas_Baader.jpg

 57%|█████▋    | 5041/8920 [1:27:00<39:44,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Shatner.jpg

 57%|█████▋    | 5042/8920 [1:27:01<54:27,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Simon.jpg

 57%|█████▋    | 5043/8920 [1:27:01<46:12,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amancio_Ortega.jpg

 57%|█████▋    | 5044/8920 [1:27:03<1:01:06,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dudley_Moore.jpg

 57%|█████▋    | 5045/8920 [1:27:04<1:10:36,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giorgio_Armani.jpg

 57%|█████▋    | 5046/8920 [1:27:05<55:21,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Hosseini_Khamenei.jpg

 57%|█████▋    | 5047/8920 [1:27:05<43:45,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ernő_Rubik.jpg

 57%|█████▋    | 5048/8920 [1:27:05<35:18,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Li_Ka-Shing.jpg

 57%|█████▋    | 5049/8920 [1:27:09<1:34:17,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Fogerty.jpg

 57%|█████▋    | 5050/8920 [1:27:09<1:20:53,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Walker.jpg

 57%|█████▋    | 5051/8920 [1:27:10<1:13:25,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Kennedy.jpg

 57%|█████▋    | 5052/8920 [1:27:12<1:20:00,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Douglas.jpg

 57%|█████▋    | 5053/8920 [1:27:12<1:08:52,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Cash.jpg

 57%|█████▋    | 5054/8920 [1:27:13<58:16,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Armstrong.jpg

 57%|█████▋    | 5055/8920 [1:27:13<45:10,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Botero.jpg

 57%|█████▋    | 5056/8920 [1:27:14<46:04,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brigitte_Bardot.jpg

 57%|█████▋    | 5057/8920 [1:27:14<38:52,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elie_Wiesel.jpg

 57%|█████▋    | 5058/8920 [1:27:16<51:40,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gladys_Knight.jpg

 57%|█████▋    | 5059/8920 [1:27:16<40:32,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Osamu_Tezuka.jpg

 57%|█████▋    | 5060/8920 [1:27:16<33:23,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Lennon.jpg

 57%|█████▋    | 5061/8920 [1:27:17<39:25,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_Manilow.jpg

 57%|█████▋    | 5062/8920 [1:27:18<48:52,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Caine.jpg

 57%|█████▋    | 5063/8920 [1:27:19<44:27,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martha_Stewart.jpg

 57%|█████▋    | 5064/8920 [1:27:19<37:11,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sirhan_Sirhan.jpg

 57%|█████▋    | 5065/8920 [1:27:19<30:15,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muhammad_Ali.jpg

 57%|█████▋    | 5066/8920 [1:27:19<25:49,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernie_Sanders.jpg

 57%|█████▋    | 5067/8920 [1:27:20<39:10,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandra_Day_O'Connor.jpg

 57%|█████▋    | 5068/8920 [1:27:21<33:58,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Meredith.jpg

 57%|█████▋    | 5069/8920 [1:27:21<29:29,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joan_Collins.jpg

 57%|█████▋    | 5070/8920 [1:27:22<33:03,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fats_Domino.jpg

 57%|█████▋    | 5071/8920 [1:27:22<27:43,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tenzin_Gyatso.jpg

 57%|█████▋    | 5072/8920 [1:27:22<24:36,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolas_Hayek.jpg

 57%|█████▋    | 5073/8920 [1:27:23<29:04,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Daltrey.jpg

 57%|█████▋    | 5074/8920 [1:27:23<25:04,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Mckellen.jpg

 57%|█████▋    | 5075/8920 [1:27:23<22:50,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mick_Jagger.jpg

 57%|█████▋    | 5076/8920 [1:27:24<22:33,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Frank.jpg

 57%|█████▋    | 5077/8920 [1:27:24<21:12,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Jackson.jpg

 57%|█████▋    | 5078/8920 [1:27:26<57:06,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahmoud_Abbas.jpg

 57%|█████▋    | 5079/8920 [1:27:27<53:37,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Judea_Pearl.jpg

 57%|█████▋    | 5080/8920 [1:27:27<42:04,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Williams.jpg

 57%|█████▋    | 5081/8920 [1:27:28<41:33,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Ross.jpg

 57%|█████▋    | 5082/8920 [1:27:28<34:28,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Taylor.jpg

 57%|█████▋    | 5083/8920 [1:27:28<29:37,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Macgraw.jpg

 57%|█████▋    | 5084/8920 [1:27:31<1:04:44,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Lucas.jpg

 57%|█████▋    | 5085/8920 [1:27:31<58:45,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Madden.jpg

 57%|█████▋    | 5086/8920 [1:27:32<45:52,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Jessy_Raphael.jpg

 57%|█████▋    | 5087/8920 [1:27:34<1:16:54,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexei_Leonov.jpg

 57%|█████▋    | 5088/8920 [1:27:35<1:12:19,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margrethe_Ii.jpg

 57%|█████▋    | 5089/8920 [1:27:35<55:20,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chinua_Achebe.jpg

 57%|█████▋    | 5090/8920 [1:27:35<43:02,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nancy_Pelosi.jpg

 57%|█████▋    | 5091/8920 [1:27:36<42:30,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Loren.jpg

 57%|█████▋    | 5092/8920 [1:27:36<35:19,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanley_Kubrick.jpg

 57%|█████▋    | 5093/8920 [1:27:38<53:58,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Pacino.jpg

 57%|█████▋    | 5094/8920 [1:27:38<49:02,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sharon_Tate.jpg

 57%|█████▋    | 5095/8920 [1:27:39<39:10,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Nicholson.jpg

 57%|█████▋    | 5096/8920 [1:27:39<38:32,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvis_Presley.jpg

 57%|█████▋    | 5097/8920 [1:27:40<33:30,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joan_A._Steitz.jpg

 57%|█████▋    | 5098/8920 [1:27:40<28:42,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Björn_Ulvaeus.jpg

 57%|█████▋    | 5099/8920 [1:27:40<24:31,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morgan_Freeman.jpg

 57%|█████▋    | 5100/8920 [1:27:40<22:16,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Soros.jpg

 57%|█████▋    | 5101/8920 [1:27:42<40:31,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Dylan.jpg

 57%|█████▋    | 5102/8920 [1:27:42<40:07,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Bernstein.jpg

 57%|█████▋    | 5103/8920 [1:27:43<34:18,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Farrakhan.jpg

 57%|█████▋    | 5104/8920 [1:27:43<28:29,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Peter_Blatty.jpg

 57%|█████▋    | 5105/8920 [1:27:44<36:50,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Quant.jpg

 57%|█████▋    | 5106/8920 [1:27:45<50:21,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Waters.jpg

 57%|█████▋    | 5107/8920 [1:27:45<41:20,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pattie_Boyd.jpg

 57%|█████▋    | 5108/8920 [1:27:46<33:07,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hunter_S._Thompson.jpg

 57%|█████▋    | 5109/8920 [1:27:46<27:43,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juvénal_Habyarimana.jpg

 57%|█████▋    | 5110/8920 [1:27:46<24:07,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Smokey_Robinson.jpg

 57%|█████▋    | 5111/8920 [1:27:46<22:56,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scotty_Bowman.jpg

 57%|█████▋    | 5112/8920 [1:27:47<19:56,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Mccartney.jpg

 57%|█████▋    | 5113/8920 [1:27:47<18:29,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pope_Francis.jpg

 57%|█████▋    | 5114/8920 [1:27:47<22:45,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Andretti.jpg

 57%|█████▋    | 5115/8920 [1:27:48<20:44,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Priscilla_Presley.jpg

 57%|█████▋    | 5116/8920 [1:27:48<18:56,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Brokaw.jpg

 57%|█████▋    | 5117/8920 [1:27:49<38:43,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuri_Gagarin.jpg

 57%|█████▋    | 5118/8920 [1:27:49<33:14,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Harrison.jpg

 57%|█████▋    | 5119/8920 [1:27:50<36:49,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Gallo.jpg

 57%|█████▋    | 5120/8920 [1:27:51<46:08,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Sontag.jpg

 57%|█████▋    | 5121/8920 [1:27:52<45:52,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Takei.jpg

 57%|█████▋    | 5122/8920 [1:27:52<37:47,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Fogerty.jpg

 57%|█████▋    | 5123/8920 [1:27:53<31:27,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommie_Smith.jpg

 57%|█████▋    | 5124/8920 [1:27:53<28:15,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ringo_Starr.jpg

 57%|█████▋    | 5125/8920 [1:27:54<33:13,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jocelyn_Bell_Burnell.jpg

 57%|█████▋    | 5126/8920 [1:27:54<28:45,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lech_Wałęsa.jpg

 57%|█████▋    | 5127/8920 [1:27:54<25:32,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joanne_Woodward.jpg

 57%|█████▋    | 5128/8920 [1:27:54<21:41,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Audrey_Hepburn.jpg

 57%|█████▊    | 5129/8920 [1:27:55<19:30,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Hargreaves.jpg

 58%|█████▊    | 5130/8920 [1:27:55<19:24,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clint_Eastwood.jpg

 58%|█████▊    | 5131/8920 [1:27:55<23:45,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nolan_Bushnell.jpg

 58%|█████▊    | 5132/8920 [1:27:56<21:16,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betty_Cuthbert.jpg

 58%|█████▊    | 5133/8920 [1:27:56<19:02,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Hanssen.jpg

 58%|█████▊    | 5134/8920 [1:27:56<18:33,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Griselda_Blanco.jpg

 58%|█████▊    | 5135/8920 [1:27:56<17:49,  3.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoko_Ono.jpg

 58%|█████▊    | 5136/8920 [1:27:57<17:01,  3.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gene_Hackman.jpg

 58%|█████▊    | 5137/8920 [1:27:57<17:04,  3.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huey_P._Newton.jpg

 58%|█████▊    | 5138/8920 [1:27:59<43:08,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbra_Streisand.jpg

 58%|█████▊    | 5139/8920 [1:27:59<34:25,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Vargas_Llosa.jpg

 58%|█████▊    | 5140/8920 [1:27:59<28:32,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Palin.jpg

 58%|█████▊    | 5141/8920 [1:27:59<24:42,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wangari_Maathai.jpg

 58%|█████▊    | 5142/8920 [1:28:00<23:27,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Nelson.jpg

 58%|█████▊    | 5143/8920 [1:28:00<21:33,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Horton.jpg

 58%|█████▊    | 5144/8920 [1:28:00<26:06,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Watts.jpg

 58%|█████▊    | 5145/8920 [1:28:01<24:33,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julie_Andrews.jpg

 58%|█████▊    | 5146/8920 [1:28:02<43:35,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvia_Plath.jpg

 58%|█████▊    | 5147/8920 [1:28:02<35:02,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Marley.jpg

 58%|█████▊    | 5148/8920 [1:28:03<28:54,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmie_Lee_Jackson.jpg

 58%|█████▊    | 5149/8920 [1:28:03<30:30,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chubby_Checker.jpg

 58%|█████▊    | 5150/8920 [1:28:04<26:55,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thabo_Mbeki.jpg

 58%|█████▊    | 5151/8920 [1:28:06<1:00:00,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herb_Brooks.jpg

 58%|█████▊    | 5152/8920 [1:28:06<46:39,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chico_Mendes.jpg

 58%|█████▊    | 5153/8920 [1:28:06<38:19,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilt_Chamberlain.jpg

 58%|█████▊    | 5154/8920 [1:28:07<36:19,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yasser_Arafat.jpg

 58%|█████▊    | 5155/8920 [1:28:08<50:45,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luciano_Pavarotti.jpg

 58%|█████▊    | 5156/8920 [1:28:09<54:50,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Henson.jpg

 58%|█████▊    | 5157/8920 [1:28:09<43:56,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rick_Barry.jpg

 58%|█████▊    | 5158/8920 [1:28:11<55:57,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muammar_Gaddafi.jpg

 58%|█████▊    | 5159/8920 [1:28:11<43:20,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madeleine_Albright.jpg

 58%|█████▊    | 5160/8920 [1:28:11<36:58,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amanda_Gorman.jpg

 58%|█████▊    | 5161/8920 [1:28:12<36:41,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greta_Thunberg.jpg

 58%|█████▊    | 5162/8920 [1:28:12<31:19,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Millie_Bobby_Brown.jpg

 58%|█████▊    | 5163/8920 [1:28:13<28:58,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Lillis.jpg

 58%|█████▊    | 5164/8920 [1:28:13<32:06,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maisie_Williams.jpg

 58%|█████▊    | 5165/8920 [1:28:13<26:55,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peyton_Elizabeth_Lee.jpg

 58%|█████▊    | 5166/8920 [1:28:15<39:23,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaden_Smith.jpg

 58%|█████▊    | 5167/8920 [1:28:16<46:49,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lando_Norris.jpg

 58%|█████▊    | 5168/8920 [1:28:16<38:19,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roddy_Ricch.jpg

 58%|█████▊    | 5169/8920 [1:28:16<30:53,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lonzo_Ball.jpg

 58%|█████▊    | 5170/8920 [1:28:17<31:30,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cody_Simpson.jpg

 58%|█████▊    | 5171/8920 [1:28:17<37:04,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willow_Smith.jpg

 58%|█████▊    | 5172/8920 [1:28:18<44:54,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brock_Purdy.jpg

 58%|█████▊    | 5173/8920 [1:28:19<49:01,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jake_Paul.jpg

 58%|█████▊    | 5174/8920 [1:28:20<39:55,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conan_Gray.jpg

 58%|█████▊    | 5175/8920 [1:28:22<1:13:57,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kiernan_Shipka.jpg

 58%|█████▊    | 5176/8920 [1:28:23<1:03:17,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_Wang.jpg

 58%|█████▊    | 5177/8920 [1:28:23<49:28,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zara_Larsson.jpg

 58%|█████▊    | 5178/8920 [1:28:23<39:04,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcus_Rashford.jpg

 58%|█████▊    | 5179/8920 [1:28:24<39:55,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billie_Eilish.jpg

 58%|█████▊    | 5180/8920 [1:28:25<51:17,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Baby_Ariel.jpg

 58%|█████▊    | 5181/8920 [1:28:26<47:42,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nba_Youngboy.jpg

 58%|█████▊    | 5182/8920 [1:28:26<37:43,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Mosey.jpg

 58%|█████▊    | 5183/8920 [1:28:26<32:07,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Finn_Wolfhard.jpg

 58%|█████▊    | 5184/8920 [1:28:27<26:32,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juice_Wrld.jpg

 58%|█████▊    | 5185/8920 [1:28:28<44:38,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabel_May.jpg

 58%|█████▊    | 5186/8920 [1:28:28<35:33,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liza_Soberano.jpg

 58%|█████▊    | 5187/8920 [1:28:28<29:29,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rowan_Blanchard.jpg

 58%|█████▊    | 5188/8920 [1:28:29<24:48,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chappell_Roan.jpg

 58%|█████▊    | 5189/8920 [1:28:29<22:58,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xxxtentacion.jpg

 58%|█████▊    | 5190/8920 [1:28:29<20:53,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angourie_Rice.jpg

 58%|█████▊    | 5191/8920 [1:28:29<18:57,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chloë_Grace_Moretz.jpg

 58%|█████▊    | 5192/8920 [1:28:30<18:24,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adut_Akech.jpg

 58%|█████▊    | 5193/8920 [1:28:30<22:21,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Hogg.jpg

 58%|█████▊    | 5194/8920 [1:28:31<31:26,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kylian_Mbappé.jpg

 58%|█████▊    | 5195/8920 [1:28:32<47:30,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naomi_Osaka.jpg

 58%|█████▊    | 5196/8920 [1:28:33<38:19,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Alcaraz.jpg

 58%|█████▊    | 5197/8920 [1:28:33<31:41,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margo_Hayes.jpg

 58%|█████▊    | 5198/8920 [1:28:34<41:02,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caitlin_Clark.jpg

 58%|█████▊    | 5199/8920 [1:28:34<36:04,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Grossman.jpg

 58%|█████▊    | 5200/8920 [1:28:35<30:17,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lamar_Jackson.jpg

 58%|█████▊    | 5201/8920 [1:28:35<26:24,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooke_Raboutou.jpg

 58%|█████▊    | 5202/8920 [1:28:35<25:00,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Pump.jpg

 58%|█████▊    | 5203/8920 [1:28:36<34:40,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kylie_Jenner.jpg

 58%|█████▊    | 5204/8920 [1:28:37<31:13,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Ledecky.jpg

 58%|█████▊    | 5205/8920 [1:28:38<40:11,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janja_Garnbret.jpg

 58%|█████▊    | 5206/8920 [1:28:40<1:10:00,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jalen_Hurts.jpg

 58%|█████▊    | 5207/8920 [1:28:40<53:58,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elle_Fanning.jpg

 58%|█████▊    | 5208/8920 [1:28:40<41:43,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chloe_Kim.jpg

 58%|█████▊    | 5209/8920 [1:28:42<1:08:30,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Zverev.jpg

 58%|█████▊    | 5210/8920 [1:28:43<55:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lily-Rose_Depp.jpg

 58%|█████▊    | 5211/8920 [1:28:43<44:20,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Harlow.jpg

 58%|█████▊    | 5212/8920 [1:28:43<36:58,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rashid_Khan.jpg

 58%|█████▊    | 5213/8920 [1:28:44<38:54,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luka_Dončić.jpg

 58%|█████▊    | 5214/8920 [1:28:46<1:00:41,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lewis_Koumas.jpg

 58%|█████▊    | 5215/8920 [1:28:46<48:11,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lalisa.jpg

 58%|█████▊    | 5216/8920 [1:28:48<1:01:24,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bella_Thorne.jpg

 58%|█████▊    | 5217/8920 [1:28:48<47:09,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khalid_[Donnel_Robinson].jpg

 58%|█████▊    | 5218/8920 [1:28:48<37:29,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jungkook.jpg

 59%|█████▊    | 5219/8920 [1:28:49<31:25,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Nas_X.jpg

 59%|█████▊    | 5220/8920 [1:28:49<35:08,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Rodrigo.jpg

 59%|█████▊    | 5221/8920 [1:28:50<30:22,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ai_Mori.jpg

 59%|█████▊    | 5222/8920 [1:28:50<36:34,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lydia_Ko.jpg

 59%|█████▊    | 5223/8920 [1:28:51<38:21,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenna_Ortega.jpg

 59%|█████▊    | 5224/8920 [1:28:51<32:01,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shawn_Mendes.jpg

 59%|█████▊    | 5225/8920 [1:28:52<26:43,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacob_Sartorius.jpg

 59%|█████▊    | 5226/8920 [1:28:52<24:34,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malala_Yousafzai.jpg

 59%|█████▊    | 5227/8920 [1:28:52<21:33,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camila_Cabello.jpg

 59%|█████▊    | 5228/8920 [1:28:53<25:38,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simone_Biles.jpg

 59%|█████▊    | 5229/8920 [1:28:53<26:01,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charli_D'Amelio.jpg

 59%|█████▊    | 5230/8920 [1:28:53<22:31,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Verstappen.jpg

 59%|█████▊    | 5231/8920 [1:28:56<58:40,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mrbeast.jpg

 59%|█████▊    | 5232/8920 [1:28:56<45:40,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khaby_Lame.jpg

 59%|█████▊    | 5233/8920 [1:28:58<1:03:07,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maddie_Ziegler.jpg

 59%|█████▊    | 5234/8920 [1:28:59<1:16:15,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erling_Haaland.jpg

 59%|█████▊    | 5235/8920 [1:29:00<57:42,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Lee.jpg

 59%|█████▊    | 5236/8920 [1:29:01<1:11:35,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Trump.jpg

 59%|█████▊    | 5237/8920 [1:29:02<54:15,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cat_Stevens.jpg

 59%|█████▊    | 5238/8920 [1:29:03<1:08:42,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayrton_Senna.jpg

 59%|█████▊    | 5239/8920 [1:29:03<52:53,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xi_Jinping.jpg

 59%|█████▊    | 5240/8920 [1:29:04<41:11,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Haring.jpg

 59%|█████▉    | 5241/8920 [1:29:04<33:50,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mr._T.jpg

 59%|█████▉    | 5242/8920 [1:29:04<30:45,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paula_Abdul.jpg

 59%|█████▉    | 5243/8920 [1:29:05<25:43,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lionel_Richie.jpg

 59%|█████▉    | 5244/8920 [1:29:06<38:06,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sigourney_Weaver.jpg

 59%|█████▉    | 5245/8920 [1:29:06<32:20,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Leibovitz.jpg

 59%|█████▉    | 5246/8920 [1:29:06<27:00,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Jackson.jpg

 59%|█████▉    | 5247/8920 [1:29:07<32:27,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Murray.jpg

 59%|█████▉    | 5248/8920 [1:29:08<34:00,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricky_Gervais.jpg

 59%|█████▉    | 5249/8920 [1:29:08<31:55,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rowan_Atkinson.jpg

 59%|█████▉    | 5250/8920 [1:29:09<34:54,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alec_Baldwin.jpg

 59%|█████▉    | 5251/8920 [1:29:09<36:56,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Norman.jpg

 59%|█████▉    | 5252/8920 [1:29:10<31:32,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/O.J._Simpson.jpg

 59%|█████▉    | 5253/8920 [1:29:10<25:53,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Green.jpg

 59%|█████▉    | 5254/8920 [1:29:11<29:52,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Cattrall.jpg

 59%|█████▉    | 5255/8920 [1:29:11<27:06,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Šťastný.jpg

 59%|█████▉    | 5256/8920 [1:29:12<43:39,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Pecci.jpg

 59%|█████▉    | 5257/8920 [1:29:12<34:35,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glenn_Close.jpg

 59%|█████▉    | 5258/8920 [1:29:13<28:23,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Hamilton.jpg

 59%|█████▉    | 5259/8920 [1:29:13<23:48,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wilfred_Benítez.jpg

 59%|█████▉    | 5260/8920 [1:29:13<20:35,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Malone.jpg

 59%|█████▉    | 5261/8920 [1:29:14<31:58,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Santana.jpg

 59%|█████▉    | 5262/8920 [1:29:14<28:18,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Newton-John.jpg

 59%|█████▉    | 5263/8920 [1:29:15<24:39,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arlo_Guthrie.jpg

 59%|█████▉    | 5264/8920 [1:29:15<28:07,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosanne_Cash.jpg

 59%|█████▉    | 5265/8920 [1:29:16<33:52,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahmad_Shah_Massoud.jpg

 59%|█████▉    | 5266/8920 [1:29:17<43:12,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arsenio_Hall.jpg

 59%|█████▉    | 5267/8920 [1:29:18<40:30,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrej_Babiš.jpg

 59%|█████▉    | 5268/8920 [1:29:19<44:14,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Campion.jpg

 59%|█████▉    | 5269/8920 [1:29:19<35:33,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Elway.jpg

 59%|█████▉    | 5270/8920 [1:29:19<37:06,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Heiden.jpg

 59%|█████▉    | 5271/8920 [1:29:20<32:17,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Linklater.jpg

 59%|█████▉    | 5272/8920 [1:29:21<52:48,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Sinise.jpg

 59%|█████▉    | 5273/8920 [1:29:22<41:57,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Iii.jpg

 59%|█████▉    | 5274/8920 [1:29:22<33:54,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clint_Black.jpg

 59%|█████▉    | 5275/8920 [1:29:24<53:08,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dale_Jarrett.jpg

 59%|█████▉    | 5276/8920 [1:29:24<43:20,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hillary_Clinton.jpg

 59%|█████▉    | 5277/8920 [1:29:25<42:04,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willie_Randolph.jpg

 59%|█████▉    | 5278/8920 [1:29:25<44:55,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olaf_Scholz.jpg

 59%|█████▉    | 5279/8920 [1:29:26<35:36,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Kutaragi.jpg

 59%|█████▉    | 5280/8920 [1:29:26<28:55,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Farley.jpg

 59%|█████▉    | 5281/8920 [1:29:27<41:17,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Temuera_Morrison.jpg

 59%|█████▉    | 5282/8920 [1:29:27<33:04,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shane_Gould.jpg

 59%|█████▉    | 5283/8920 [1:29:28<28:59,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Gibb.jpg

 59%|█████▉    | 5284/8920 [1:29:29<39:21,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Crystal_Gayle.jpg

 59%|█████▉    | 5285/8920 [1:29:29<37:31,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rickey_Henderson.jpg

 59%|█████▉    | 5286/8920 [1:29:30<37:11,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Price.jpg

 59%|█████▉    | 5287/8920 [1:29:30<36:33,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florence_Griffith_Joyner.jpg

 59%|█████▉    | 5288/8920 [1:29:31<31:26,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Lee_Curtis.jpg

 59%|█████▉    | 5289/8920 [1:29:31<26:07,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ina_Garten.jpg

 59%|█████▉    | 5290/8920 [1:29:31<23:28,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ralph_Fiennes.jpg

 59%|█████▉    | 5291/8920 [1:29:32<28:30,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Weathers.jpg

 59%|█████▉    | 5292/8920 [1:29:32<24:06,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Cone.jpg

 59%|█████▉    | 5293/8920 [1:29:33<27:11,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Jarvis.jpg

 59%|█████▉    | 5294/8920 [1:29:37<1:29:46,  1.49s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peggy_Lipton.jpg

 59%|█████▉    | 5295/8920 [1:29:37<1:18:24,  1.30s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Higdon.jpg

 59%|█████▉    | 5296/8920 [1:29:39<1:17:55,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Warburton.jpg

 59%|█████▉    | 5297/8920 [1:29:39<58:55,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Elkington.jpg

 59%|█████▉    | 5298/8920 [1:29:40<54:53,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Bolton.jpg

 59%|█████▉    | 5299/8920 [1:29:41<55:06,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Octavia_E._Butler.jpg

 59%|█████▉    | 5300/8920 [1:29:41<50:18,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Friedrich_Merz.jpg

 59%|█████▉    | 5301/8920 [1:29:42<46:36,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Blair.jpg

 59%|█████▉    | 5302/8920 [1:29:45<1:25:10,  1.41s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Stamos.jpg

 59%|█████▉    | 5303/8920 [1:29:46<1:27:55,  1.46s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antony_Blinken.jpg

 59%|█████▉    | 5304/8920 [1:29:47<1:06:37,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_May.jpg

 59%|█████▉    | 5305/8920 [1:29:48<1:03:58,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rob_Reiner.jpg

 59%|█████▉    | 5306/8920 [1:29:49<1:11:40,  1.19s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moses_Malone.jpg

 59%|█████▉    | 5307/8920 [1:29:50<1:05:58,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hans_Moravec.jpg

 60%|█████▉    | 5308/8920 [1:29:51<57:12,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryan_Stevenson.jpg

 60%|█████▉    | 5309/8920 [1:29:51<43:56,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuji_Horii.jpg

 60%|█████▉    | 5310/8920 [1:29:52<43:37,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roddy_Piper.jpg

 60%|█████▉    | 5311/8920 [1:29:52<36:41,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdul_Qadir.jpg

 60%|█████▉    | 5312/8920 [1:29:52<29:45,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/P._J._O'Rourke.jpg

 60%|█████▉    | 5313/8920 [1:29:53<41:51,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Benigni.jpg

 60%|█████▉    | 5314/8920 [1:29:54<33:40,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Payton.jpg

 60%|█████▉    | 5315/8920 [1:29:54<27:48,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wolfgang_Güllich.jpg

 60%|█████▉    | 5316/8920 [1:29:54<31:41,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uri_Geller.jpg

 60%|█████▉    | 5317/8920 [1:29:55<26:04,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anita_Baker.jpg

 60%|█████▉    | 5318/8920 [1:29:55<29:44,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Daniels.jpg

 60%|█████▉    | 5319/8920 [1:29:56<34:21,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diane_Von_Furstenberg.jpg

 60%|█████▉    | 5320/8920 [1:29:57<40:36,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pavlo_Lazarenko.jpg

 60%|█████▉    | 5321/8920 [1:29:58<52:49,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caitlyn_Jenner.jpg

 60%|█████▉    | 5322/8920 [1:29:59<49:48,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matti_Nykänen.jpg

 60%|█████▉    | 5323/8920 [1:30:00<53:48,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Kite.jpg

 60%|█████▉    | 5324/8920 [1:30:02<1:09:53,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geoffrey_Hinton.jpg

 60%|█████▉    | 5325/8920 [1:30:02<59:57,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Howard_Johnson.jpg

 60%|█████▉    | 5326/8920 [1:30:03<51:11,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Comey.jpg

 60%|█████▉    | 5327/8920 [1:30:05<1:07:07,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Anderson.jpg

 60%|█████▉    | 5328/8920 [1:30:05<53:22,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Randy_Savage.jpg

 60%|█████▉    | 5329/8920 [1:30:06<59:20,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfonso_Cuarón.jpg

 60%|█████▉    | 5330/8920 [1:30:08<1:17:24,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Jae-In.jpg

 60%|█████▉    | 5331/8920 [1:30:09<1:05:11,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katey_Sagal.jpg

 60%|█████▉    | 5332/8920 [1:30:09<50:52,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rajinikanth.jpg

 60%|█████▉    | 5333/8920 [1:30:13<1:50:18,  1.85s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curtis_Strange.jpg

 60%|█████▉    | 5334/8920 [1:30:14<1:22:10,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hassan_Rouhani.jpg

 60%|█████▉    | 5335/8920 [1:30:14<1:10:41,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Gartner.jpg

 60%|█████▉    | 5336/8920 [1:30:16<1:12:09,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Campese.jpg

 60%|█████▉    | 5337/8920 [1:30:16<54:30,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Boitano.jpg

 60%|█████▉    | 5338/8920 [1:30:20<1:59:05,  1.99s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nancy_Lopez.jpg

 60%|█████▉    | 5339/8920 [1:30:21<1:27:59,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Quisenberry.jpg

 60%|█████▉    | 5340/8920 [1:30:22<1:27:51,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Li_Keqiang.jpg

 60%|█████▉    | 5341/8920 [1:30:22<1:06:03,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Turnbull.jpg

 60%|█████▉    | 5342/8920 [1:30:23<51:08,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Sessions.jpg

 60%|█████▉    | 5343/8920 [1:30:23<41:48,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lawrence_Taylor.jpg

 60%|█████▉    | 5344/8920 [1:30:24<43:05,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ozzie_Smith.jpg

 60%|█████▉    | 5345/8920 [1:30:24<35:40,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imad_Mughniyeh.jpg

 60%|█████▉    | 5346/8920 [1:30:24<29:54,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastián_Piñera.jpg

 60%|█████▉    | 5347/8920 [1:30:25<26:31,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Bernanke.jpg

 60%|█████▉    | 5348/8920 [1:30:25<22:33,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doug_Flutie.jpg

 60%|█████▉    | 5349/8920 [1:30:27<56:03,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernard_Hinault.jpg

 60%|█████▉    | 5350/8920 [1:30:27<44:08,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Taylor.jpg

 60%|█████▉    | 5351/8920 [1:30:28<34:57,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabe_Newell.jpg

 60%|██████    | 5352/8920 [1:30:28<28:40,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Lee_Howard.jpg

 60%|██████    | 5353/8920 [1:30:29<41:59,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arnoldo_Aleman.jpg

 60%|██████    | 5354/8920 [1:30:30<51:26,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Hughes.jpg

 60%|██████    | 5355/8920 [1:30:31<40:00,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gregg_Allman.jpg

 60%|██████    | 5356/8920 [1:30:31<31:48,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wes_Unseld.jpg

 60%|██████    | 5357/8920 [1:30:32<45:46,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Cook.jpg

 60%|██████    | 5358/8920 [1:30:33<46:37,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nawaz_Sharif.jpg

 60%|██████    | 5359/8920 [1:30:35<1:00:39,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uhuru_Kenyatta.jpg

 60%|██████    | 5360/8920 [1:30:38<1:38:18,  1.66s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haruki_Murakami.jpg

 60%|██████    | 5361/8920 [1:30:38<1:13:13,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Courtney_Walsh.jpg

 60%|██████    | 5362/8920 [1:30:38<56:30,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vida_Blue.jpg

 60%|██████    | 5363/8920 [1:30:39<1:01:42,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Leguizamo.jpg

 60%|██████    | 5364/8920 [1:30:40<1:01:26,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorenzo_Lamas.jpg

 60%|██████    | 5365/8920 [1:30:41<48:17,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gilbert_Gottfried.jpg

 60%|██████    | 5366/8920 [1:30:42<49:39,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rand_Paul.jpg

 60%|██████    | 5367/8920 [1:30:42<39:01,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathryn_Bigelow.jpg

 60%|██████    | 5368/8920 [1:30:42<32:23,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryne_Sandberg.jpg

 60%|██████    | 5369/8920 [1:30:43<33:19,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alfre_Woodard.jpg

 60%|██████    | 5370/8920 [1:30:44<41:11,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Liotta.jpg

 60%|██████    | 5371/8920 [1:30:44<33:04,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patty_Sheehan.jpg

 60%|██████    | 5372/8920 [1:30:45<45:16,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hassan_Nasrallah.jpg

 60%|██████    | 5373/8920 [1:30:46<36:30,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Carter.jpg

 60%|██████    | 5374/8920 [1:30:49<1:18:48,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Flynn.jpg

 60%|██████    | 5375/8920 [1:30:49<1:01:25,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tōru_Iwatani.jpg

 60%|██████    | 5376/8920 [1:30:49<48:06,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Kinison.jpg

 60%|██████    | 5377/8920 [1:30:49<38:36,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stanley_Tucci.jpg

 60%|██████    | 5378/8920 [1:30:50<44:46,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Messier.jpg

 60%|██████    | 5379/8920 [1:30:51<36:18,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ang_Lee.jpg

 60%|██████    | 5380/8920 [1:30:51<29:40,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Felicity_Huffman.jpg

 60%|██████    | 5381/8920 [1:30:51<25:36,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Cowens.jpg

 60%|██████    | 5382/8920 [1:30:52<23:08,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Murcer.jpg

 60%|██████    | 5383/8920 [1:30:52<20:28,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Carpenter.jpg

 60%|██████    | 5384/8920 [1:30:53<34:33,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Maravich.jpg

 60%|██████    | 5385/8920 [1:30:54<44:06,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohamed_Morsi.jpg

 60%|██████    | 5386/8920 [1:30:55<41:44,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leon_Spinks.jpg

 60%|██████    | 5387/8920 [1:30:56<47:23,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Romano.jpg

 60%|██████    | 5388/8920 [1:30:56<37:13,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ismail_Haniyeh.jpg

 60%|██████    | 5389/8920 [1:30:56<32:42,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gilbert_Perreault.jpg

 60%|██████    | 5390/8920 [1:30:58<1:00:55,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dino_Ciccarelli.jpg

 60%|██████    | 5391/8920 [1:30:59<47:57,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Kagame.jpg

 60%|██████    | 5392/8920 [1:31:00<46:14,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liu_Xiaobo.jpg

 60%|██████    | 5393/8920 [1:31:00<43:10,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Carreras.jpg

 60%|██████    | 5394/8920 [1:31:00<34:15,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Reitman.jpg

 60%|██████    | 5395/8920 [1:31:01<43:53,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hironobu_Sakaguchi.jpg

 60%|██████    | 5396/8920 [1:31:02<41:54,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annie_Lennox.jpg

 61%|██████    | 5397/8920 [1:31:03<36:26,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirby_Puckett.jpg

 61%|██████    | 5398/8920 [1:31:04<55:23,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luther_Vandross.jpg

 61%|██████    | 5399/8920 [1:31:05<43:45,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Basinger.jpg

 61%|██████    | 5400/8920 [1:31:05<35:18,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Bourque.jpg

 61%|██████    | 5401/8920 [1:31:07<56:29,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Howard_Stern.jpg

 61%|██████    | 5402/8920 [1:31:07<43:43,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terry_Fox.jpg

 61%|██████    | 5403/8920 [1:31:08<47:07,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evo_Morales.jpg

 61%|██████    | 5404/8920 [1:31:09<48:51,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akira_Toriyama.jpg

 61%|██████    | 5405/8920 [1:31:09<39:09,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Cuomo.jpg

 61%|██████    | 5406/8920 [1:31:09<31:48,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Val_Kilmer.jpg

 61%|██████    | 5407/8920 [1:31:10<33:53,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Bossy.jpg

 61%|██████    | 5408/8920 [1:31:10<27:41,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wendy_Wasserstein.jpg

 61%|██████    | 5409/8920 [1:31:11<41:38,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niki_Lauda.jpg

 61%|██████    | 5410/8920 [1:31:12<38:53,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Greig.jpg

 61%|██████    | 5411/8920 [1:31:14<1:07:08,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Corey_Pavin.jpg

 61%|██████    | 5412/8920 [1:31:15<59:06,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitas_Gerulaitis.jpg

 61%|██████    | 5413/8920 [1:31:15<45:17,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathy_Griffin.jpg

 61%|██████    | 5414/8920 [1:31:16<42:07,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Alexander.jpg

 61%|██████    | 5415/8920 [1:31:17<49:08,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Mcguinness.jpg

 61%|██████    | 5416/8920 [1:31:18<52:29,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Flay.jpg

 61%|██████    | 5417/8920 [1:31:19<49:12,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Crenshaw.jpg

 61%|██████    | 5418/8920 [1:31:19<39:12,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Lai.jpg

 61%|██████    | 5419/8920 [1:31:19<32:10,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rush_Limbaugh.jpg

 61%|██████    | 5420/8920 [1:31:20<39:55,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paula_Yates.jpg

 61%|██████    | 5421/8920 [1:31:20<34:19,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabrielle_Carteris.jpg

 61%|██████    | 5422/8920 [1:31:21<33:46,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Kline.jpg

 61%|██████    | 5423/8920 [1:31:22<36:07,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Eruzione.jpg

 61%|██████    | 5424/8920 [1:31:23<44:03,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Reubens.jpg

 61%|██████    | 5425/8920 [1:31:23<36:38,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Bench.jpg

 61%|██████    | 5426/8920 [1:31:24<41:46,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahmoud_Ahmadinejad.jpg

 61%|██████    | 5427/8920 [1:31:24<33:14,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvester_James_Jr..jpg

 61%|██████    | 5428/8920 [1:31:25<28:44,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Haney.jpg

 61%|██████    | 5429/8920 [1:31:25<32:31,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoon_Suk-Yeol.jpg

 61%|██████    | 5430/8920 [1:31:26<33:30,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Lane.jpg

 61%|██████    | 5431/8920 [1:31:26<28:47,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mandy_Patinkin.jpg

 61%|██████    | 5432/8920 [1:31:27<25:01,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rita_Wilson.jpg

 61%|██████    | 5433/8920 [1:31:27<21:34,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Lynch.jpg

 61%|██████    | 5434/8920 [1:31:27<19:10,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julianne_Moore.jpg

 61%|██████    | 5435/8920 [1:31:29<43:15,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Lucci.jpg

 61%|██████    | 5436/8920 [1:31:30<52:48,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dale_Earnhardt.jpg

 61%|██████    | 5437/8920 [1:31:32<1:11:26,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Lydon.jpg

 61%|██████    | 5438/8920 [1:31:32<54:33,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dilma_Rousseff.jpg

 61%|██████    | 5439/8920 [1:31:33<54:26,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Ramone.jpg

 61%|██████    | 5440/8920 [1:31:34<51:09,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sissy_Spacek.jpg

 61%|██████    | 5441/8920 [1:31:40<2:15:32,  2.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zina_Garrison.jpg

 61%|██████    | 5442/8920 [1:31:41<1:57:41,  2.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grete_Waitz.jpg

 61%|██████    | 5443/8920 [1:31:42<1:32:28,  1.60s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Reeve.jpg

 61%|██████    | 5444/8920 [1:31:43<1:23:23,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Pullman.jpg

 61%|██████    | 5445/8920 [1:31:45<1:44:39,  1.81s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Sajak.jpg

 61%|██████    | 5446/8920 [1:31:46<1:25:14,  1.47s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Buffett.jpg

 61%|██████    | 5447/8920 [1:31:46<1:03:50,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darrell_Waltrip.jpg

 61%|██████    | 5448/8920 [1:31:48<1:13:44,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Mamet.jpg

 61%|██████    | 5449/8920 [1:31:50<1:35:13,  1.65s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikki_Sixx.jpg

 61%|██████    | 5450/8920 [1:31:51<1:20:49,  1.40s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyril_Ramaphosa.jpg

 61%|██████    | 5451/8920 [1:31:52<1:02:11,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvia_Hanika.jpg

 61%|██████    | 5452/8920 [1:31:52<48:40,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emerson_Fittipaldi.jpg

 61%|██████    | 5453/8920 [1:31:54<1:05:51,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stan_Smith.jpg

 61%|██████    | 5454/8920 [1:31:54<51:41,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johan_Cruyff.jpg

 61%|██████    | 5455/8920 [1:31:54<40:13,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyle_Lovett.jpg

 61%|██████    | 5456/8920 [1:31:56<52:08,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Syd_Barrett.jpg

 61%|██████    | 5457/8920 [1:31:57<54:17,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_Hurt.jpg

 61%|██████    | 5458/8920 [1:31:58<59:34,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Mandrell.jpg

 61%|██████    | 5459/8920 [1:31:58<52:00,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Baszucki.jpg

 61%|██████    | 5460/8920 [1:31:59<48:10,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bo_Jackson.jpg

 61%|██████    | 5461/8920 [1:32:00<53:32,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Gwynn.jpg

 61%|██████    | 5462/8920 [1:32:01<41:25,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Hillenburg.jpg

 61%|██████    | 5463/8920 [1:32:01<34:46,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Righetti.jpg

 61%|██████▏   | 5464/8920 [1:32:02<35:43,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seve_Ballesteros.jpg

 61%|██████▏   | 5465/8920 [1:32:02<36:49,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Austin.jpg

 61%|██████▏   | 5466/8920 [1:32:02<29:51,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronald_Mcnair.jpg

 61%|██████▏   | 5467/8920 [1:32:03<25:46,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Forsch.jpg

 61%|██████▏   | 5468/8920 [1:32:03<22:54,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Garvey.jpg

 61%|██████▏   | 5469/8920 [1:32:03<21:04,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Botham.jpg

 61%|██████▏   | 5470/8920 [1:32:04<19:24,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Rodgers.jpg

 61%|██████▏   | 5471/8920 [1:32:04<24:31,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Swayze.jpg

 61%|██████▏   | 5472/8920 [1:32:04<21:10,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Belushi.jpg

 61%|██████▏   | 5473/8920 [1:32:05<18:31,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Petty.jpg

 61%|██████▏   | 5474/8920 [1:32:05<17:32,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Kingman.jpg

 61%|██████▏   | 5475/8920 [1:32:06<22:58,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduardo_Romero.jpg

 61%|██████▏   | 5476/8920 [1:32:06<19:59,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean-Claude_Duvalier.jpg

 61%|██████▏   | 5477/8920 [1:32:08<56:42,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malcolm_Mclaren.jpg

 61%|██████▏   | 5478/8920 [1:32:09<55:27,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Becker.jpg

 61%|██████▏   | 5479/8920 [1:32:10<1:00:03,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Paul_Jones.jpg

 61%|██████▏   | 5480/8920 [1:32:11<55:46,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Hutchence.jpg

 61%|██████▏   | 5481/8920 [1:32:12<54:18,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shelley_Duvall.jpg

 61%|██████▏   | 5482/8920 [1:32:13<48:35,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Will_Wright.jpg

 61%|██████▏   | 5483/8920 [1:32:13<44:49,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calista_Flockhart.jpg

 61%|██████▏   | 5484/8920 [1:32:14<45:09,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chanda_Kochhar.jpg

 61%|██████▏   | 5485/8920 [1:32:28<4:27:16,  4.67s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Pryce.jpg

 62%|██████▏   | 5486/8920 [1:32:29<3:19:19,  3.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donna_Summer.jpg

 62%|██████▏   | 5487/8920 [1:32:29<2:25:34,  2.54s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reza_Pahlavi.jpg

 62%|██████▏   | 5488/8920 [1:32:30<2:01:18,  2.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Smith.jpg

 62%|██████▏   | 5489/8920 [1:32:31<1:48:29,  1.90s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marco_Van_Basten.jpg

 62%|██████▏   | 5490/8920 [1:32:32<1:30:45,  1.59s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoshihide_Suga.jpg

 62%|██████▏   | 5491/8920 [1:32:33<1:18:03,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Rickman.jpg

 62%|██████▏   | 5492/8920 [1:32:33<59:34,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kapil_Dev.jpg

 62%|██████▏   | 5493/8920 [1:32:35<1:07:07,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Preston.jpg

 62%|██████▏   | 5494/8920 [1:32:37<1:14:46,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dwight_Gooden.jpg

 62%|██████▏   | 5495/8920 [1:32:42<2:27:40,  2.59s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Wintour.jpg

 62%|██████▏   | 5496/8920 [1:32:44<2:07:29,  2.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miguel_Ángel_Félix_Gallardo.jpg

 62%|██████▏   | 5497/8920 [1:32:45<1:57:16,  2.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Malkovich.jpg

 62%|██████▏   | 5498/8920 [1:32:45<1:26:33,  1.52s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadia_Comăneci.jpg

 62%|██████▏   | 5499/8920 [1:32:46<1:10:59,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trevor_Berbick.jpg

 62%|██████▏   | 5500/8920 [1:32:46<54:35,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hakeem_Olajuwon.jpg

 62%|██████▏   | 5501/8920 [1:32:47<52:30,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ming-Na_Wen.jpg

 62%|██████▏   | 5502/8920 [1:32:49<1:06:27,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Bonds.jpg

 62%|██████▏   | 5503/8920 [1:32:50<1:12:46,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Condoleezza_Rice.jpg

 62%|██████▏   | 5504/8920 [1:32:51<55:56,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Boon.jpg

 62%|██████▏   | 5505/8920 [1:32:51<43:47,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Crowe.jpg

 62%|██████▏   | 5506/8920 [1:32:51<34:32,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Allison_Janney.jpg

 62%|██████▏   | 5507/8920 [1:32:52<30:26,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reggie_White.jpg

 62%|██████▏   | 5508/8920 [1:32:54<1:00:05,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Sutcliffe.jpg

 62%|██████▏   | 5509/8920 [1:32:55<1:08:12,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Van_Halen.jpg

 62%|██████▏   | 5510/8920 [1:32:56<1:01:40,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Fink.jpg

 62%|██████▏   | 5511/8920 [1:32:57<51:02,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Saget.jpg

 62%|██████▏   | 5512/8920 [1:32:58<59:15,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_O'Meara.jpg

 62%|██████▏   | 5513/8920 [1:32:59<1:03:16,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Gandolfini.jpg

 62%|██████▏   | 5514/8920 [1:33:00<53:32,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tilda_Swinton.jpg

 62%|██████▏   | 5515/8920 [1:33:01<1:03:58,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cathy_Moriarty.jpg

 62%|██████▏   | 5516/8920 [1:33:02<48:48,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fuzzy_Zoeller.jpg

 62%|██████▏   | 5517/8920 [1:33:02<44:01,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Waits.jpg

 62%|██████▏   | 5518/8920 [1:33:03<35:59,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Axl_Rose.jpg

 62%|██████▏   | 5519/8920 [1:33:03<30:28,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dick_Wolf.jpg

 62%|██████▏   | 5520/8920 [1:33:04<38:51,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toby_Keith.jpg

 62%|██████▏   | 5521/8920 [1:33:05<37:34,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Geddes.jpg

 62%|██████▏   | 5522/8920 [1:33:05<30:10,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stevie_Ray_Vaughan.jpg

 62%|██████▏   | 5523/8920 [1:33:05<25:18,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rodney_Brooks.jpg

 62%|██████▏   | 5524/8920 [1:33:06<27:01,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sid_Vicious.jpg

 62%|██████▏   | 5525/8920 [1:33:06<27:37,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christine_Lagarde.jpg

 62%|██████▏   | 5526/8920 [1:33:06<24:38,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Blake.jpg

 62%|██████▏   | 5527/8920 [1:33:07<21:08,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Jackson.jpg

 62%|██████▏   | 5528/8920 [1:33:07<24:36,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Cole.jpg

 62%|██████▏   | 5529/8920 [1:33:08<30:13,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolas_Sarkozy.jpg

 62%|██████▏   | 5530/8920 [1:33:08<26:39,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laffit_Pincay_Jr..jpg

 62%|██████▏   | 5531/8920 [1:33:09<29:53,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_The_Giant.jpg

 62%|██████▏   | 5532/8920 [1:33:10<30:20,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nolan_Ryan.jpg

 62%|██████▏   | 5533/8920 [1:33:10<26:28,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenneth_Branagh.jpg

 62%|██████▏   | 5534/8920 [1:33:10<27:52,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Weird_Al_Yankovic.jpg

 62%|██████▏   | 5535/8920 [1:33:12<41:08,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hamid_Karzai.jpg

 62%|██████▏   | 5536/8920 [1:33:12<38:21,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Glenn_Frey.jpg

 62%|██████▏   | 5537/8920 [1:33:13<47:41,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Payne_Stewart.jpg

 62%|██████▏   | 5538/8920 [1:33:14<42:05,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wayne_Gretzky.jpg

 62%|██████▏   | 5539/8920 [1:33:14<34:37,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugene_Levy.jpg

 62%|██████▏   | 5540/8920 [1:33:15<41:28,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tracy_Austin.jpg

 62%|██████▏   | 5541/8920 [1:33:16<34:21,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Russert.jpg

 62%|██████▏   | 5542/8920 [1:33:16<34:13,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Holder.jpg

 62%|██████▏   | 5543/8920 [1:33:18<51:05,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patty_Duke.jpg

 62%|██████▏   | 5544/8920 [1:33:19<1:03:06,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marisa_Tomei.jpg

 62%|██████▏   | 5545/8920 [1:33:20<52:33,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Fagen.jpg

 62%|██████▏   | 5546/8920 [1:33:22<1:03:46,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Givens.jpg

 62%|██████▏   | 5547/8920 [1:33:22<49:14,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Bridges.jpg

 62%|██████▏   | 5548/8920 [1:33:22<38:03,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Steinman.jpg

 62%|██████▏   | 5549/8920 [1:33:22<30:33,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Houser.jpg

 62%|██████▏   | 5550/8920 [1:33:24<44:56,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Hartman.jpg

 62%|██████▏   | 5551/8920 [1:33:25<48:16,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rupaul.jpg

 62%|██████▏   | 5552/8920 [1:33:25<37:27,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ozzy_Osbourne.jpg

 62%|██████▏   | 5553/8920 [1:33:25<31:12,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Goldblum.jpg

 62%|██████▏   | 5554/8920 [1:33:25<26:07,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bret_Saberhagen.jpg

 62%|██████▏   | 5555/8920 [1:33:26<22:58,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrés_Manuel_López_Obrador.jpg

 62%|██████▏   | 5556/8920 [1:33:28<46:45,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samuel_L._Jackson.jpg

 62%|██████▏   | 5557/8920 [1:33:28<37:29,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Ho.jpg

 62%|██████▏   | 5558/8920 [1:33:29<53:21,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Spitz.jpg

 62%|██████▏   | 5559/8920 [1:33:30<50:08,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariska_Hargitay.jpg

 62%|██████▏   | 5560/8920 [1:33:31<42:33,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robbie_Coltrane.jpg

 62%|██████▏   | 5561/8920 [1:33:32<46:28,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Richardson.jpg

 62%|██████▏   | 5562/8920 [1:33:33<52:19,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denis_Potvin.jpg

 62%|██████▏   | 5563/8920 [1:33:34<58:03,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Holmes.jpg

 62%|██████▏   | 5564/8920 [1:33:36<1:14:16,  1.33s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Bruno.jpg

 62%|██████▏   | 5565/8920 [1:33:37<1:04:26,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Glover.jpg

 62%|██████▏   | 5566/8920 [1:33:37<50:17,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Field.jpg

 62%|██████▏   | 5567/8920 [1:33:38<43:08,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Walton.jpg

 62%|██████▏   | 5568/8920 [1:33:38<33:43,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kris_Jenner.jpg

 62%|██████▏   | 5569/8920 [1:33:38<29:04,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demi_Moore.jpg

 62%|██████▏   | 5570/8920 [1:33:39<31:04,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Hsien_Loong.jpg

 62%|██████▏   | 5571/8920 [1:33:39<26:22,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yahya_Sinwar.jpg

 62%|██████▏   | 5572/8920 [1:33:39<23:00,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Obama.jpg

 62%|██████▏   | 5573/8920 [1:33:40<20:31,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Vedder.jpg

 62%|██████▏   | 5574/8920 [1:33:40<18:14,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brad_Pitt.jpg

 62%|██████▎   | 5575/8920 [1:33:41<25:16,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Starr.jpg

 63%|██████▎   | 5576/8920 [1:33:41<22:35,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Louganis.jpg

 63%|██████▎   | 5577/8920 [1:33:42<33:18,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benny_Andersson.jpg

 63%|██████▎   | 5578/8920 [1:33:42<28:24,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Evert.jpg

 63%|██████▎   | 5579/8920 [1:33:44<51:20,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Lewis.jpg

 63%|██████▎   | 5580/8920 [1:33:45<46:14,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Milken.jpg

 63%|██████▎   | 5581/8920 [1:33:46<45:45,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Hines.jpg

 63%|██████▎   | 5582/8920 [1:33:47<50:15,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yannick_Noah.jpg

 63%|██████▎   | 5583/8920 [1:33:47<39:32,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Coffey.jpg

 63%|██████▎   | 5584/8920 [1:33:48<41:53,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeffrey_Dahmer.jpg

 63%|██████▎   | 5585/8920 [1:33:50<1:02:35,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Allen.jpg

 63%|██████▎   | 5586/8920 [1:33:50<48:14,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meg_Ryan.jpg

 63%|██████▎   | 5587/8920 [1:33:51<44:03,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Albanese.jpg

 63%|██████▎   | 5588/8920 [1:33:51<43:23,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Dreyfuss.jpg

 63%|██████▎   | 5589/8920 [1:33:52<37:16,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coolio.jpg

 63%|██████▎   | 5590/8920 [1:33:53<47:32,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Alcott.jpg

 63%|██████▎   | 5591/8920 [1:33:53<38:24,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mehmet_Ali_Ağca.jpg

 63%|██████▎   | 5592/8920 [1:33:55<1:00:58,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Russell_Coutts.jpg

 63%|██████▎   | 5593/8920 [1:33:56<59:39,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brigitte_Macron.jpg

 63%|██████▎   | 5594/8920 [1:33:58<1:07:15,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guy_Lafleur.jpg

 63%|██████▎   | 5595/8920 [1:33:59<55:38,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Rogers_Nelson.jpg

 63%|██████▎   | 5596/8920 [1:33:59<44:28,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Garneau.jpg

 63%|██████▎   | 5597/8920 [1:34:00<48:46,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Maclean.jpg

 63%|██████▎   | 5598/8920 [1:34:01<51:46,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_Spielberg.jpg

 63%|██████▎   | 5599/8920 [1:34:02<57:19,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davis_Love_Iii.jpg

 63%|██████▎   | 5600/8920 [1:34:03<45:14,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolas_Cage.jpg

 63%|██████▎   | 5601/8920 [1:34:04<49:36,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clyde_Drexler.jpg

 63%|██████▎   | 5602/8920 [1:34:04<39:26,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mel_Gibson.jpg

 63%|██████▎   | 5603/8920 [1:34:04<32:12,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_Soderbergh.jpg

 63%|██████▎   | 5604/8920 [1:34:06<48:29,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Manuel_Santos.jpg

 63%|██████▎   | 5605/8920 [1:34:06<43:03,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Michael.jpg

 63%|██████▎   | 5606/8920 [1:34:07<49:44,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evander_Holyfield.jpg

 63%|██████▎   | 5607/8920 [1:34:08<40:25,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Denzel_Washington.jpg

 63%|██████▎   | 5608/8920 [1:34:08<38:24,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Whoopi_Goldberg.jpg

 63%|██████▎   | 5609/8920 [1:34:09<33:10,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hulk_Hogan.jpg

 63%|██████▎   | 5610/8920 [1:34:12<1:13:43,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Perlman.jpg

 63%|██████▎   | 5611/8920 [1:34:12<55:31,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellen_Degeneres.jpg

 63%|██████▎   | 5612/8920 [1:34:13<1:00:15,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frank_Bainimarama.jpg

 63%|██████▎   | 5613/8920 [1:34:14<45:49,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dorothy_Hamill.jpg

 63%|██████▎   | 5614/8920 [1:34:15<47:55,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wayne_Grady.jpg

 63%|██████▎   | 5615/8920 [1:34:16<1:04:01,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Cerny.jpg

 63%|██████▎   | 5616/8920 [1:34:18<1:09:19,  1.26s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_James.jpg

 63%|██████▎   | 5617/8920 [1:34:19<59:27,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Weaver.jpg

 63%|██████▎   | 5618/8920 [1:34:20<1:01:55,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julius_Erving.jpg

 63%|██████▎   | 5619/8920 [1:34:21<1:01:03,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Sirtis.jpg

 63%|██████▎   | 5620/8920 [1:34:23<1:19:53,  1.45s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Cox.jpg

 63%|██████▎   | 5621/8920 [1:34:23<59:43,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Merrick_Garland.jpg

 63%|██████▎   | 5622/8920 [1:34:24<53:53,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hideo_Kojima.jpg

 63%|██████▎   | 5623/8920 [1:34:25<54:43,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rex_Tillerson.jpg

 63%|██████▎   | 5624/8920 [1:34:26<51:51,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Irwin.jpg

 63%|██████▎   | 5625/8920 [1:34:26<40:16,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Harper.jpg

 63%|██████▎   | 5626/8920 [1:34:27<33:52,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martina_Navratilova.jpg

 63%|██████▎   | 5627/8920 [1:34:27<28:09,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loretta_Lynch.jpg

 63%|██████▎   | 5628/8920 [1:34:27<23:49,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Campbell.jpg

 63%|██████▎   | 5629/8920 [1:34:28<33:45,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelson_Piquet.jpg

 63%|██████▎   | 5630/8920 [1:34:29<34:31,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jodie_Foster.jpg

 63%|██████▎   | 5631/8920 [1:34:30<45:15,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christa_Johnson.jpg

 63%|██████▎   | 5632/8920 [1:34:30<35:30,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeffrey_Hawkins.jpg

 63%|██████▎   | 5633/8920 [1:34:31<31:48,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nils_Lofgren.jpg

 63%|██████▎   | 5634/8920 [1:34:31<35:19,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brad_Garrett.jpg

 63%|██████▎   | 5635/8920 [1:34:33<46:29,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Carrey.jpg

 63%|██████▎   | 5636/8920 [1:34:33<43:15,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Nagin.jpg

 63%|██████▎   | 5637/8920 [1:34:34<34:45,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcel_Dionne.jpg

 63%|██████▎   | 5638/8920 [1:34:34<28:47,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sherri_Turner.jpg

 63%|██████▎   | 5639/8920 [1:34:34<27:15,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Gervin.jpg

 63%|██████▎   | 5640/8920 [1:34:37<54:14,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shelley_Long.jpg

 63%|██████▎   | 5641/8920 [1:34:38<58:06,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haider_Al-Abadi.jpg

 63%|██████▎   | 5642/8920 [1:34:40<1:14:15,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henri_Leconte.jpg

 63%|██████▎   | 5643/8920 [1:34:41<1:02:45,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meg_Mallon.jpg

 63%|██████▎   | 5644/8920 [1:34:41<49:04,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benjamin_Netanyahu.jpg

 63%|██████▎   | 5645/8920 [1:34:43<1:02:50,  1.15s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Jenkins.jpg

 63%|██████▎   | 5646/8920 [1:34:44<1:01:23,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vijay_Singh.jpg

 63%|██████▎   | 5647/8920 [1:34:44<54:46,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Edward.jpg

 63%|██████▎   | 5648/8920 [1:34:46<57:39,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laura_Davies.jpg

 63%|██████▎   | 5649/8920 [1:34:48<1:18:19,  1.44s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Deakins.jpg

 63%|██████▎   | 5650/8920 [1:34:49<1:15:24,  1.38s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Nye.jpg

 63%|██████▎   | 5651/8920 [1:34:50<1:10:20,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/François-Henri_Pinault.jpg

 63%|██████▎   | 5652/8920 [1:34:50<53:20,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mima_Jausovec.jpg

 63%|██████▎   | 5653/8920 [1:34:52<57:27,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Fernandes.jpg

 63%|██████▎   | 5654/8920 [1:34:52<50:13,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roseanne_Barr.jpg

 63%|██████▎   | 5655/8920 [1:34:53<47:29,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Funk.jpg

 63%|██████▎   | 5656/8920 [1:34:54<54:57,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Hextall.jpg

 63%|██████▎   | 5657/8920 [1:34:56<1:05:25,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garth_Brooks.jpg

 63%|██████▎   | 5658/8920 [1:34:57<53:27,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Warren.jpg

 63%|██████▎   | 5659/8920 [1:34:58<59:45,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunil_Gavaskar.jpg

 63%|██████▎   | 5660/8920 [1:34:58<46:59,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Yauch.jpg

 63%|██████▎   | 5661/8920 [1:34:59<53:34,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Orbán.jpg

 63%|██████▎   | 5662/8920 [1:35:00<41:19,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamal_Khashoggi.jpg

 63%|██████▎   | 5663/8920 [1:35:01<44:27,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolay_Zimyatov.jpg

 63%|██████▎   | 5664/8920 [1:35:02<56:44,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikael_Pernfors.jpg

 64%|██████▎   | 5665/8920 [1:35:03<45:01,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michel_Platini.jpg

 64%|██████▎   | 5666/8920 [1:35:06<1:27:20,  1.61s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirin_Ebadi.jpg

 64%|██████▎   | 5667/8920 [1:35:07<1:12:53,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilie_Năstase.jpg

 64%|██████▎   | 5668/8920 [1:35:07<55:01,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Shanahan.jpg

 64%|██████▎   | 5669/8920 [1:35:07<42:13,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mo_Yan.jpg

 64%|██████▎   | 5670/8920 [1:35:08<36:24,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Graham_Norton.jpg

 64%|██████▎   | 5671/8920 [1:35:09<52:03,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eiji_Aonuma.jpg

 64%|██████▎   | 5672/8920 [1:35:10<53:25,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolly_Parton.jpg

 64%|██████▎   | 5673/8920 [1:35:11<41:53,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tracy_Chapman.jpg

 64%|██████▎   | 5674/8920 [1:35:11<38:36,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Xvi_Gustaf.jpg

 64%|██████▎   | 5675/8920 [1:35:12<37:14,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Worthy.jpg

 64%|██████▎   | 5676/8920 [1:35:12<36:20,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Morris.jpg

 64%|██████▎   | 5677/8920 [1:35:13<30:16,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Stewart.jpg

 64%|██████▎   | 5678/8920 [1:35:14<46:16,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helen_Hunt.jpg

 64%|██████▎   | 5679/8920 [1:35:15<42:59,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guillermo_Vilas.jpg

 64%|██████▎   | 5680/8920 [1:35:15<34:05,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Valenzuela.jpg

 64%|██████▎   | 5681/8920 [1:35:15<27:53,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ed_Harris.jpg

 64%|██████▎   | 5682/8920 [1:35:16<25:04,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akio_Toyoda.jpg

 64%|██████▎   | 5683/8920 [1:35:16<22:01,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dale_Murphy.jpg

 64%|██████▎   | 5684/8920 [1:35:17<38:53,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Costner.jpg

 64%|██████▎   | 5685/8920 [1:35:19<48:28,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ice-T.jpg

 64%|██████▎   | 5686/8920 [1:35:20<50:54,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Short.jpg

 64%|██████▍   | 5687/8920 [1:35:20<44:50,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolás_Maduro.jpg

 64%|██████▍   | 5688/8920 [1:35:21<46:54,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun_Fat_Chow.jpg

 64%|██████▍   | 5689/8920 [1:35:22<42:51,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miloslav_Mečíř.jpg

 64%|██████▍   | 5690/8920 [1:35:23<44:06,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helen_Clark.jpg

 64%|██████▍   | 5691/8920 [1:35:23<34:44,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betsy_King.jpg

 64%|██████▍   | 5692/8920 [1:35:24<39:33,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Babcock.jpg

 64%|██████▍   | 5693/8920 [1:35:25<34:41,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ai_Weiwei.jpg

 64%|██████▍   | 5694/8920 [1:35:25<27:59,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shinzō_Abe.jpg

 64%|██████▍   | 5695/8920 [1:35:25<23:24,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geoffrey_Rush.jpg

 64%|██████▍   | 5696/8920 [1:35:25<20:34,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cal_Ripken_Jr.jpg

 64%|██████▍   | 5697/8920 [1:35:26<29:22,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoshua_Bengio.jpg

 64%|██████▍   | 5698/8920 [1:35:27<30:28,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imran_Khan.jpg

 64%|██████▍   | 5699/8920 [1:35:28<34:40,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Graham_Gooch.jpg

 64%|██████▍   | 5700/8920 [1:35:28<29:34,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carrie_Fisher.jpg

 64%|██████▍   | 5701/8920 [1:35:28<24:12,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edie_Falco.jpg

 64%|██████▍   | 5702/8920 [1:35:28<20:52,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Key.jpg

 64%|██████▍   | 5703/8920 [1:35:29<22:13,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Hadfield.jpg

 64%|██████▍   | 5704/8920 [1:35:29<19:18,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Molyneux.jpg

 64%|██████▍   | 5705/8920 [1:35:30<29:49,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melanie_Griffith.jpg

 64%|██████▍   | 5706/8920 [1:35:30<24:57,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mukesh_Ambani.jpg

 64%|██████▍   | 5707/8920 [1:35:31<25:25,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_O'Neill.jpg

 64%|██████▍   | 5708/8920 [1:35:31<27:44,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Carter.jpg

 64%|██████▍   | 5709/8920 [1:35:34<56:14,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dianne_Wiest.jpg

 64%|██████▍   | 5710/8920 [1:35:34<43:32,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diane_Keaton.jpg

 64%|██████▍   | 5711/8920 [1:35:35<53:35,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosanna_Arquette.jpg

 64%|██████▍   | 5712/8920 [1:35:36<41:05,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Parish.jpg

 64%|██████▍   | 5713/8920 [1:35:37<50:33,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Galloway.jpg

 64%|██████▍   | 5714/8920 [1:35:38<56:08,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Lillee.jpg

 64%|██████▍   | 5715/8920 [1:35:41<1:22:34,  1.55s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Woods.jpg

 64%|██████▍   | 5716/8920 [1:35:41<1:02:34,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sridevi_Kapoor.jpg

 64%|██████▍   | 5717/8920 [1:35:42<50:37,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oprah_Winfrey.jpg

 64%|██████▍   | 5718/8920 [1:35:43<54:07,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Lehman.jpg

 64%|██████▍   | 5719/8920 [1:35:43<42:00,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Meyer.jpg

 64%|██████▍   | 5720/8920 [1:35:44<34:23,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Brown.jpg

 64%|██████▍   | 5721/8920 [1:35:44<39:30,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grant_Fuhr.jpg

 64%|██████▍   | 5722/8920 [1:35:45<31:12,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Neeson.jpg

 64%|██████▍   | 5723/8920 [1:35:45<27:40,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peggy_Fleming.jpg

 64%|██████▍   | 5724/8920 [1:35:47<44:20,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Meloni.jpg

 64%|██████▍   | 5725/8920 [1:35:47<34:43,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Stockton.jpg

 64%|██████▍   | 5726/8920 [1:35:48<34:31,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brendan_Gleeson.jpg

 64%|██████▍   | 5727/8920 [1:35:49<51:27,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marilu_Henner.jpg

 64%|██████▍   | 5728/8920 [1:35:50<41:07,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Hernandez.jpg

 64%|██████▍   | 5729/8920 [1:35:50<32:24,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryan_Adams.jpg

 64%|██████▍   | 5730/8920 [1:35:51<45:04,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sitiveni_Rabuka.jpg

 64%|██████▍   | 5731/8920 [1:35:52<48:12,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valerie_Bertinelli.jpg

 64%|██████▍   | 5732/8920 [1:35:53<38:35,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Hearns.jpg

 64%|██████▍   | 5733/8920 [1:35:53<31:57,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naruhito.jpg

 64%|██████▍   | 5734/8920 [1:35:53<27:34,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Little.jpg

 64%|██████▍   | 5735/8920 [1:35:53<22:49,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Spacey.jpg

 64%|██████▍   | 5736/8920 [1:35:55<39:59,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Faldo.jpg

 64%|██████▍   | 5737/8920 [1:35:55<33:33,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Boyle.jpg

 64%|██████▍   | 5738/8920 [1:35:57<49:36,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zaheer_Abbas.jpg

 64%|██████▍   | 5739/8920 [1:35:58<46:33,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Farrah_Fawcett.jpg

 64%|██████▍   | 5740/8920 [1:36:00<1:03:42,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Carlyle.jpg

 64%|██████▍   | 5741/8920 [1:36:00<56:39,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janet_Yellen.jpg

 64%|██████▍   | 5742/8920 [1:36:01<50:27,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maurice_Gibb.jpg

 64%|██████▍   | 5743/8920 [1:36:02<56:45,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Penn.jpg

 64%|██████▍   | 5744/8920 [1:36:03<43:49,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Bowie.jpg

 64%|██████▍   | 5745/8920 [1:36:03<35:42,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryan_Trottier.jpg

 64%|██████▍   | 5746/8920 [1:36:03<29:30,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Oldman.jpg

 64%|██████▍   | 5747/8920 [1:36:03<24:26,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Lehder.jpg

 64%|██████▍   | 5748/8920 [1:36:04<21:40,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Allan_Border.jpg

 64%|██████▍   | 5749/8920 [1:36:04<19:27,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Day.jpg

 64%|██████▍   | 5750/8920 [1:36:04<17:01,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ursula_Von_Der_Leyen.jpg

 64%|██████▍   | 5751/8920 [1:36:05<16:42,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Murray.jpg

 64%|██████▍   | 5752/8920 [1:36:05<16:27,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pat_Bradley.jpg

 64%|██████▍   | 5753/8920 [1:36:05<15:49,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nigel_Mansell.jpg

 65%|██████▍   | 5754/8920 [1:36:06<24:24,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Dryden.jpg

 65%|██████▍   | 5755/8920 [1:36:06<22:01,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Montgomerie.jpg

 65%|██████▍   | 5756/8920 [1:36:07<28:49,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brett_Hull.jpg

 65%|██████▍   | 5757/8920 [1:36:08<40:34,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Cooper.jpg

 65%|██████▍   | 5758/8920 [1:36:09<33:41,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_Nelson.jpg

 65%|██████▍   | 5759/8920 [1:36:09<34:56,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Curtly_Ambrose.jpg

 65%|██████▍   | 5760/8920 [1:36:10<36:44,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gloria_Macapagal-Arroyo.jpg

 65%|██████▍   | 5761/8920 [1:36:11<30:41,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Strait.jpg

 65%|██████▍   | 5762/8920 [1:36:11<25:14,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Canseco.jpg

 65%|██████▍   | 5763/8920 [1:36:11<22:28,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Sugar.jpg

 65%|██████▍   | 5764/8920 [1:36:11<19:34,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosa_Mota.jpg

 65%|██████▍   | 5765/8920 [1:36:12<19:13,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Boyle.jpg

 65%|██████▍   | 5766/8920 [1:36:14<46:31,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Douglas_Lenat.jpg

 65%|██████▍   | 5767/8920 [1:36:14<41:39,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Najib_Razak.jpg

 65%|██████▍   | 5768/8920 [1:36:15<45:15,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lloyd_Blankfein.jpg

 65%|██████▍   | 5769/8920 [1:36:16<36:00,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andre_Dawson.jpg

 65%|██████▍   | 5770/8920 [1:36:17<41:51,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvester_Stallone.jpg

 65%|██████▍   | 5771/8920 [1:36:17<40:57,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yevgeny_Prigozhin.jpg

 65%|██████▍   | 5772/8920 [1:36:20<1:16:13,  1.45s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Burton.jpg

 65%|██████▍   | 5773/8920 [1:36:21<56:54,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Menken.jpg

 65%|██████▍   | 5774/8920 [1:36:21<44:26,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirk_Hammett.jpg

 65%|██████▍   | 5775/8920 [1:36:22<49:48,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miguel_Induráin.jpg

 65%|██████▍   | 5776/8920 [1:36:23<51:13,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Young.jpg

 65%|██████▍   | 5777/8920 [1:36:24<46:35,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Lemond.jpg

 65%|██████▍   | 5778/8920 [1:36:24<37:56,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeb_Bush.jpg

 65%|██████▍   | 5779/8920 [1:36:25<30:58,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Martínez.jpg

 65%|██████▍   | 5780/8920 [1:36:25<31:08,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Craig_Ferguson.jpg

 65%|██████▍   | 5781/8920 [1:36:26<28:11,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Molitor.jpg

 65%|██████▍   | 5782/8920 [1:36:27<35:07,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donovan.jpg

 65%|██████▍   | 5783/8920 [1:36:28<51:42,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shigeru_Miyamoto.jpg

 65%|██████▍   | 5784/8920 [1:36:29<42:09,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Carell.jpg

 65%|██████▍   | 5785/8920 [1:36:31<1:00:35,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Hadlee.jpg

 65%|██████▍   | 5786/8920 [1:36:31<47:08,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyndi_Lauper.jpg

 65%|██████▍   | 5787/8920 [1:36:31<36:30,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Raines.jpg

 65%|██████▍   | 5788/8920 [1:36:31<29:35,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Durán.jpg

 65%|██████▍   | 5789/8920 [1:36:32<24:45,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cecil_Fielder.jpg

 65%|██████▍   | 5790/8920 [1:36:33<40:22,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charo.jpg

 65%|██████▍   | 5791/8920 [1:36:34<39:45,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergey_Lavrov.jpg

 65%|██████▍   | 5792/8920 [1:36:34<33:45,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joss_Whedon.jpg

 65%|██████▍   | 5793/8920 [1:36:35<39:40,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Venkatraman_Ramakrishnan.jpg

 65%|██████▍   | 5794/8920 [1:36:36<45:17,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dmitry_Muratov.jpg

 65%|██████▍   | 5795/8920 [1:36:38<56:25,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean-Claude_Van_Damme.jpg

 65%|██████▍   | 5796/8920 [1:36:39<56:24,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Crystal.jpg

 65%|██████▍   | 5797/8920 [1:36:39<43:50,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jair_Bolsonaro.jpg

 65%|██████▌   | 5798/8920 [1:36:41<54:12,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suze_Orman.jpg

 65%|██████▌   | 5799/8920 [1:36:42<50:46,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Cowher.jpg

 65%|██████▌   | 5800/8920 [1:36:42<44:23,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wanda_Sykes.jpg

 65%|██████▌   | 5801/8920 [1:36:43<36:25,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darryl_Sittler.jpg

 65%|██████▌   | 5802/8920 [1:36:44<51:20,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ron_Guidry.jpg

 65%|██████▌   | 5803/8920 [1:36:45<45:35,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosemary_Casals.jpg

 65%|██████▌   | 5804/8920 [1:36:45<37:44,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Dempsey.jpg

 65%|██████▌   | 5805/8920 [1:36:46<39:32,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ric_Flair.jpg

 65%|██████▌   | 5806/8920 [1:36:46<32:33,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Coe.jpg

 65%|██████▌   | 5807/8920 [1:36:47<39:36,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Silver.jpg

 65%|██████▌   | 5808/8920 [1:36:49<49:56,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laura_Harring.jpg

 65%|██████▌   | 5809/8920 [1:36:50<55:57,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/François_Hollande.jpg

 65%|██████▌   | 5810/8920 [1:36:51<43:10,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Ewing.jpg

 65%|██████▌   | 5811/8920 [1:36:51<40:54,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alberto_Salazar.jpg

 65%|██████▌   | 5812/8920 [1:36:53<49:10,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anatoly_Karpov.jpg

 65%|██████▌   | 5813/8920 [1:36:53<38:39,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Moon.jpg

 65%|██████▌   | 5814/8920 [1:36:53<37:34,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabella_Rossellini.jpg

 65%|██████▌   | 5815/8920 [1:36:55<45:57,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivan_Lendl.jpg

 65%|██████▌   | 5816/8920 [1:36:55<42:24,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Burnett.jpg

 65%|██████▌   | 5817/8920 [1:36:56<38:52,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Clemens.jpg

 65%|██████▌   | 5818/8920 [1:36:56<30:56,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salman_Rushdie.jpg

 65%|██████▌   | 5819/8920 [1:36:56<25:02,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Jackson.jpg

 65%|██████▌   | 5820/8920 [1:36:57<30:33,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kamala_Harris.jpg

 65%|██████▌   | 5821/8920 [1:36:58<29:37,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wynonna_Judd.jpg

 65%|██████▌   | 5822/8920 [1:36:58<25:13,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Gower.jpg

 65%|██████▌   | 5823/8920 [1:36:58<23:01,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Björn_Borg.jpg

 65%|██████▌   | 5824/8920 [1:36:59<25:47,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viv_Richards.jpg

 65%|██████▌   | 5825/8920 [1:36:59<23:29,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Curtin.jpg

 65%|██████▌   | 5826/8920 [1:37:01<40:58,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bonnie_Blair.jpg

 65%|██████▌   | 5827/8920 [1:37:03<51:44,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Goodell.jpg

 65%|██████▌   | 5828/8920 [1:37:03<40:58,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Barkley.jpg

 65%|██████▌   | 5829/8920 [1:37:03<38:11,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Simonyi.jpg

 65%|██████▌   | 5830/8920 [1:37:04<37:46,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annette_Bening.jpg

 65%|██████▌   | 5831/8920 [1:37:04<30:47,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Joyner-Kersee.jpg

 65%|██████▌   | 5832/8920 [1:37:06<45:41,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Bachelet.jpg

 65%|██████▌   | 5833/8920 [1:37:06<37:16,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janeane_Garofalo.jpg

 65%|██████▌   | 5834/8920 [1:37:07<35:00,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosie_O'Donnell.jpg

 65%|██████▌   | 5835/8920 [1:37:07<32:22,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kurt_Russell.jpg

 65%|██████▌   | 5836/8920 [1:37:08<26:44,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Fry.jpg

 65%|██████▌   | 5837/8920 [1:37:08<22:16,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Smith.jpg

 65%|██████▌   | 5838/8920 [1:37:08<21:15,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carl_Lewis.jpg

 65%|██████▌   | 5839/8920 [1:37:10<37:54,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meryl_Streep.jpg

 65%|██████▌   | 5840/8920 [1:37:10<34:13,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Lukashenko.jpg

 65%|██████▌   | 5841/8920 [1:37:11<28:00,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rick_Hansen.jpg

 65%|██████▌   | 5842/8920 [1:37:11<29:01,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rick_James.jpg

 66%|██████▌   | 5843/8920 [1:37:11<23:42,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marla_Maples.jpg

 66%|██████▌   | 5844/8920 [1:37:12<20:49,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Thompson.jpg

 66%|██████▌   | 5845/8920 [1:37:12<19:04,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yann_Lecun.jpg

 66%|██████▌   | 5846/8920 [1:37:13<36:16,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hank_Azaria.jpg

 66%|██████▌   | 5847/8920 [1:37:15<43:56,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beth_Daniel.jpg

 66%|██████▌   | 5848/8920 [1:37:17<59:51,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isiah_Thomas.jpg

 66%|██████▌   | 5849/8920 [1:37:17<45:25,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yvonne_Van_Gennip.jpg

 66%|██████▌   | 5850/8920 [1:37:18<43:06,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patty_Hearst.jpg

 66%|██████▌   | 5851/8920 [1:37:18<34:55,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelsey_Grammer.jpg

 66%|██████▌   | 5852/8920 [1:37:19<38:00,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathy_Bates.jpg

 66%|██████▌   | 5853/8920 [1:37:20<41:30,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clarence_Thomas.jpg

 66%|██████▌   | 5854/8920 [1:37:21<49:14,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alain_Prost.jpg

 66%|██████▌   | 5855/8920 [1:37:21<37:56,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Williams.jpg

 66%|██████▌   | 5856/8920 [1:37:23<55:48,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Forest_Whitaker.jpg

 66%|██████▌   | 5857/8920 [1:37:23<42:21,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gianni_Versace.jpg

 66%|██████▌   | 5858/8920 [1:37:24<33:52,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stevie_Nicks.jpg

 66%|██████▌   | 5859/8920 [1:37:26<55:05,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Courteney_Cox.jpg

 66%|██████▌   | 5860/8920 [1:37:26<42:43,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frances_Mcdormand.jpg

 66%|██████▌   | 5861/8920 [1:37:26<33:53,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Rodman.jpg

 66%|██████▌   | 5862/8920 [1:37:27<37:11,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Dice_Clay.jpg

 66%|██████▌   | 5863/8920 [1:37:29<52:39,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giuseppe_Conte.jpg

 66%|██████▌   | 5864/8920 [1:37:29<42:34,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Elliott.jpg

 66%|██████▌   | 5865/8920 [1:37:30<34:19,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Secada.jpg

 66%|██████▌   | 5866/8920 [1:37:31<44:00,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonio_Banderas.jpg

 66%|██████▌   | 5867/8920 [1:37:31<40:05,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_Bonds.jpg

 66%|██████▌   | 5868/8920 [1:37:32<32:24,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Philippe_Of_Belgium.jpg

 66%|██████▌   | 5869/8920 [1:37:32<26:09,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernhard_Langer.jpg

 66%|██████▌   | 5870/8920 [1:37:33<31:54,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Holly_Hunter.jpg

 66%|██████▌   | 5871/8920 [1:37:34<44:33,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Patterson.jpg

 66%|██████▌   | 5872/8920 [1:37:35<35:49,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_Seagal.jpg

 66%|██████▌   | 5873/8920 [1:37:36<43:32,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wesley_Snipes.jpg

 66%|██████▌   | 5874/8920 [1:37:36<34:24,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Christie.jpg

 66%|██████▌   | 5875/8920 [1:37:37<31:04,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dennis_Quaid.jpg

 66%|██████▌   | 5876/8920 [1:37:38<40:21,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Brown.jpg

 66%|██████▌   | 5877/8920 [1:37:38<31:37,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Bob_Thornton.jpg

 66%|██████▌   | 5878/8920 [1:37:39<30:51,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_James_Olmos.jpg

 66%|██████▌   | 5879/8920 [1:37:39<25:48,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Marino.jpg

 66%|██████▌   | 5880/8920 [1:37:40<42:11,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Draghi.jpg

 66%|██████▌   | 5881/8920 [1:37:41<42:40,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeffrey_Immelt.jpg

 66%|██████▌   | 5882/8920 [1:37:43<50:30,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robyn_Erbesfield-Raboutou.jpg

 66%|██████▌   | 5883/8920 [1:37:43<45:19,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Cameron.jpg

 66%|██████▌   | 5884/8920 [1:37:44<39:29,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Mechner.jpg

 66%|██████▌   | 5885/8920 [1:37:45<48:54,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashraf_Ghani.jpg

 66%|██████▌   | 5886/8920 [1:37:45<38:04,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melissa_Etheridge.jpg

 66%|██████▌   | 5887/8920 [1:37:46<30:07,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Fincher.jpg

 66%|██████▌   | 5888/8920 [1:37:46<24:23,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Gross.jpg

 66%|██████▌   | 5889/8920 [1:37:46<21:02,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pablo_Escobar.jpg

 66%|██████▌   | 5890/8920 [1:37:48<39:56,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Lange.jpg

 66%|██████▌   | 5891/8920 [1:37:48<32:24,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Judge.jpg

 66%|██████▌   | 5892/8920 [1:37:48<27:29,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Brennan.jpg

 66%|██████▌   | 5893/8920 [1:37:50<34:46,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernard_Arnault.jpg

 66%|██████▌   | 5894/8920 [1:37:50<34:24,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Chappell.jpg

 66%|██████▌   | 5895/8920 [1:37:51<41:08,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Schmidt.jpg

 66%|██████▌   | 5896/8920 [1:37:52<32:17,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Mattingly.jpg

 66%|██████▌   | 5897/8920 [1:37:52<25:54,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Mcgwire.jpg

 66%|██████▌   | 5898/8920 [1:37:54<45:08,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arianna_Huffington.jpg

 66%|██████▌   | 5899/8920 [1:37:54<35:01,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Satoru_Iwata.jpg

 66%|██████▌   | 5900/8920 [1:37:54<28:04,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Rice.jpg

 66%|██████▌   | 5901/8920 [1:37:57<1:02:29,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Frakes.jpg

 66%|██████▌   | 5902/8920 [1:37:58<58:32,  1.16s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Merkel.jpg

 66%|██████▌   | 5903/8920 [1:37:58<45:43,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eric_Dickerson.jpg

 66%|██████▌   | 5904/8920 [1:37:59<41:27,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danny_Elfman.jpg

 66%|██████▌   | 5905/8920 [1:37:59<32:24,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Thewlis.jpg

 66%|██████▌   | 5906/8920 [1:38:00<33:11,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Jackson.jpg

 66%|██████▌   | 5907/8920 [1:38:01<39:36,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugh_Laurie.jpg

 66%|██████▌   | 5908/8920 [1:38:01<35:57,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Edwards.jpg

 66%|██████▌   | 5909/8920 [1:38:02<36:12,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huey_Lewis.jpg

 66%|██████▋   | 5910/8920 [1:38:02<29:47,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Flatley.jpg

 66%|██████▋   | 5911/8920 [1:38:03<37:58,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/António_Guterres.jpg

 66%|██████▋   | 5912/8920 [1:38:04<30:03,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlene_Carter.jpg

 66%|██████▋   | 5913/8920 [1:38:05<36:44,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hank_Williams_Jr.jpg

 66%|██████▋   | 5914/8920 [1:38:06<40:23,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Allen_Litchfield.jpg

 66%|██████▋   | 5915/8920 [1:38:07<39:45,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angus_Young.jpg

 66%|██████▋   | 5916/8920 [1:38:07<31:18,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary-Louise_Parker.jpg

 66%|██████▋   | 5917/8920 [1:38:08<42:33,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Lee_Jones.jpg

 66%|██████▋   | 5918/8920 [1:38:09<44:53,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sugar_Ray_Leonard.jpg

 66%|██████▋   | 5919/8920 [1:38:09<35:59,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oliver_Stone.jpg

 66%|██████▋   | 5920/8920 [1:38:11<49:01,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Woody_Harrelson.jpg

 66%|██████▋   | 5921/8920 [1:38:12<41:59,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Goodman.jpg

 66%|██████▋   | 5922/8920 [1:38:12<40:20,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Ballmer.jpg

 66%|██████▋   | 5923/8920 [1:38:13<37:24,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugo_Chávez.jpg

 66%|██████▋   | 5924/8920 [1:38:14<39:02,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurence_Fishburne.jpg

 66%|██████▋   | 5925/8920 [1:38:15<42:41,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Howe.jpg

 66%|██████▋   | 5926/8920 [1:38:15<33:22,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reggie_Jackson.jpg

 66%|██████▋   | 5927/8920 [1:38:16<33:35,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Connors.jpg

 66%|██████▋   | 5928/8920 [1:38:17<42:41,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Moore.jpg

 66%|██████▋   | 5929/8920 [1:38:17<33:34,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Yanukovych.jpg

 66%|██████▋   | 5930/8920 [1:38:18<38:53,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harvey_Weinstein.jpg

 66%|██████▋   | 5931/8920 [1:38:19<41:00,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boy_George.jpg

 67%|██████▋   | 5932/8920 [1:38:20<43:03,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Orr.jpg

 67%|██████▋   | 5933/8920 [1:38:21<49:25,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carles_Puigdemont.jpg

 67%|██████▋   | 5934/8920 [1:38:22<40:03,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emmylou_Harris.jpg

 67%|██████▋   | 5935/8920 [1:38:22<37:52,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Grisham.jpg

 67%|██████▋   | 5936/8920 [1:38:24<44:12,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roscoe_Tanner.jpg

 67%|██████▋   | 5937/8920 [1:38:25<46:49,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joko_Widodo.jpg

 67%|██████▋   | 5938/8920 [1:38:25<38:15,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geddy_Lee.jpg

 67%|██████▋   | 5939/8920 [1:38:25<30:09,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Flavor_Flav.jpg

 67%|██████▋   | 5940/8920 [1:38:27<42:15,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mats_Wilander.jpg

 67%|██████▋   | 5941/8920 [1:38:27<33:55,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Robbins.jpg

 67%|██████▋   | 5942/8920 [1:38:28<35:52,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_Tyler.jpg

 67%|██████▋   | 5943/8920 [1:38:28<29:32,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theresa_May.jpg

 67%|██████▋   | 5944/8920 [1:38:29<39:57,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Leno.jpg

 67%|██████▋   | 5945/8920 [1:38:30<43:47,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guillermo_Del_Toro.jpg

 67%|██████▋   | 5946/8920 [1:38:31<34:52,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Watson.jpg

 67%|██████▋   | 5947/8920 [1:38:31<33:00,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Orel_Hershiser.jpg

 67%|██████▋   | 5948/8920 [1:38:32<26:47,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freddie_Mercury.jpg

 67%|██████▋   | 5949/8920 [1:38:32<30:01,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Irons.jpg

 67%|██████▋   | 5950/8920 [1:38:33<35:08,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Gabriel.jpg

 67%|██████▋   | 5951/8920 [1:38:34<28:22,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anjelica_Huston.jpg

 67%|██████▋   | 5952/8920 [1:38:34<24:30,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthew_Broderick.jpg

 67%|██████▋   | 5953/8920 [1:38:36<49:50,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jane_Lynch.jpg

 67%|██████▋   | 5954/8920 [1:38:37<45:24,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_James.jpg

 67%|██████▋   | 5955/8920 [1:38:38<51:29,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Warren_Spector.jpg

 67%|██████▋   | 5956/8920 [1:38:38<40:49,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Sarandon.jpg

 67%|██████▋   | 5957/8920 [1:38:39<44:24,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernadette_Peters.jpg

 67%|██████▋   | 5958/8920 [1:38:40<41:01,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janusz_Kamiński.jpg

 67%|██████▋   | 5959/8920 [1:38:41<37:34,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pope_Leo_Xiv.jpg

 67%|██████▋   | 5960/8920 [1:38:42<39:26,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Brett.jpg

 67%|██████▋   | 5961/8920 [1:38:44<55:27,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hana_Mandlikova.jpg

 67%|██████▋   | 5962/8920 [1:38:44<42:58,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richie_Sambora.jpg

 67%|██████▋   | 5963/8920 [1:38:45<52:57,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Day-Lewis.jpg

 67%|██████▋   | 5964/8920 [1:38:46<44:45,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juliane_Koepcke.jpg

 67%|██████▋   | 5965/8920 [1:38:47<53:18,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evonne_Goolagong_Cawley.jpg

 67%|██████▋   | 5966/8920 [1:38:48<48:51,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryan_Cranston.jpg

 67%|██████▋   | 5967/8920 [1:38:49<52:48,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fran_Drescher.jpg

 67%|██████▋   | 5968/8920 [1:38:50<40:43,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Bonham.jpg

 67%|██████▋   | 5969/8920 [1:38:50<32:29,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackson_Browne.jpg

 67%|██████▋   | 5970/8920 [1:38:50<27:02,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sandra_Bullock.jpg

 67%|██████▋   | 5971/8920 [1:38:51<32:38,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_Brightman.jpg

 67%|██████▋   | 5972/8920 [1:38:51<26:08,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Cave.jpg

 67%|██████▋   | 5973/8920 [1:38:53<38:21,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanessa_Williams.jpg

 67%|██████▋   | 5974/8920 [1:38:54<52:01,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_King.jpg

 67%|██████▋   | 5975/8920 [1:38:55<39:52,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reba_Mcentire.jpg

 67%|██████▋   | 5976/8920 [1:38:55<38:26,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Pence.jpg

 67%|██████▋   | 5977/8920 [1:38:56<34:24,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Louis-Dreyfus.jpg

 67%|██████▋   | 5978/8920 [1:38:57<46:34,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Hitchens.jpg

 67%|██████▋   | 5979/8920 [1:38:58<35:55,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Depp.jpg

 67%|██████▋   | 5980/8920 [1:38:58<28:28,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Kudrow.jpg

 67%|██████▋   | 5981/8920 [1:38:59<36:33,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meat_Loaf.jpg

 67%|██████▋   | 5982/8920 [1:39:01<54:21,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larry_David.jpg

 67%|██████▋   | 5983/8920 [1:39:01<42:22,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Alexis.jpg

 67%|██████▋   | 5984/8920 [1:39:02<34:05,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Isaak.jpg

 67%|██████▋   | 5985/8920 [1:39:02<27:58,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Chan.jpg

 67%|██████▋   | 5986/8920 [1:39:02<23:34,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gary_Larson.jpg

 67%|██████▋   | 5987/8920 [1:39:04<37:52,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maureen_Mccormick.jpg

 67%|██████▋   | 5988/8920 [1:39:04<29:48,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Penn_Jillette.jpg

 67%|██████▋   | 5989/8920 [1:39:05<34:01,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Geun-Hye.jpg

 67%|██████▋   | 5990/8920 [1:39:05<28:08,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Neill.jpg

 67%|██████▋   | 5991/8920 [1:39:06<28:41,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fatboy_Slim.jpg

 67%|██████▋   | 5992/8920 [1:39:07<35:56,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danielle_Steel.jpg

 67%|██████▋   | 5993/8920 [1:39:07<33:57,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elvis_Costello.jpg

 67%|██████▋   | 5994/8920 [1:39:08<37:32,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Taylor.jpg

 67%|██████▋   | 5995/8920 [1:39:09<40:28,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melinda_Gates.jpg

 67%|██████▋   | 5996/8920 [1:39:10<32:55,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Mcgraw.jpg

 67%|██████▋   | 5997/8920 [1:39:10<33:24,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Cruise.jpg

 67%|██████▋   | 5998/8920 [1:39:12<41:40,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magic_Johnson.jpg

 67%|██████▋   | 5999/8920 [1:39:12<38:31,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Myers.jpg

 67%|██████▋   | 6000/8920 [1:39:13<41:40,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Russell_Crowe.jpg

 67%|██████▋   | 6001/8920 [1:39:14<40:36,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Gere.jpg

 67%|██████▋   | 6002/8920 [1:39:15<47:52,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Biehn.jpg

 67%|██████▋   | 6003/8920 [1:39:16<37:30,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Mcenroe.jpg

 67%|██████▋   | 6004/8920 [1:39:17<45:48,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Mancini.jpg

 67%|██████▋   | 6005/8920 [1:39:17<35:41,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Aykroyd.jpg

 67%|██████▋   | 6006/8920 [1:39:18<44:25,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Gilmour.jpg

 67%|██████▋   | 6007/8920 [1:39:19<34:26,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Bezos.jpg

 67%|██████▋   | 6008/8920 [1:39:19<27:38,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Travolta.jpg

 67%|██████▋   | 6009/8920 [1:39:19<23:18,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Youssou_N'Dour.jpg

 67%|██████▋   | 6010/8920 [1:39:20<27:25,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Spencer.jpg

 67%|██████▋   | 6011/8920 [1:39:21<40:14,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Recep_Tayyip_Erdoğan.jpg

 67%|██████▋   | 6012/8920 [1:39:23<48:47,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Hasselhoff.jpg

 67%|██████▋   | 6013/8920 [1:39:23<41:12,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Hanks.jpg

 67%|██████▋   | 6014/8920 [1:39:25<50:49,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Whitney_Houston.jpg

 67%|██████▋   | 6015/8920 [1:39:25<39:13,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Courtney_Love.jpg

 67%|██████▋   | 6016/8920 [1:39:26<36:24,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Walz.jpg

 67%|██████▋   | 6017/8920 [1:39:27<44:04,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Stewart.jpg

 67%|██████▋   | 6018/8920 [1:39:28<38:13,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Johnson.jpg

 67%|██████▋   | 6019/8920 [1:39:28<30:34,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lenny_Kravitz.jpg

 67%|██████▋   | 6020/8920 [1:39:28<24:36,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Branson.jpg

 68%|██████▊   | 6021/8920 [1:39:28<20:44,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trisha_Yearwood.jpg

 68%|██████▊   | 6022/8920 [1:39:29<26:01,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seal.jpg

 68%|██████▊   | 6023/8920 [1:39:29<22:53,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheikh_Hasina.jpg

 68%|██████▊   | 6024/8920 [1:39:30<22:41,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Ray_Cyrus.jpg

 68%|██████▊   | 6025/8920 [1:39:32<47:03,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Pfeiffer.jpg

 68%|██████▊   | 6026/8920 [1:39:33<42:48,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ted_Bundy.jpg

 68%|██████▊   | 6027/8920 [1:39:33<38:45,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_J._Fox.jpg

 68%|██████▊   | 6028/8920 [1:39:34<35:02,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mitt_Romney.jpg

 68%|██████▊   | 6029/8920 [1:39:35<34:56,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elisabeth_Shue.jpg

 68%|██████▊   | 6030/8920 [1:39:36<43:56,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Yeoh.jpg

 68%|██████▊   | 6031/8920 [1:39:37<40:50,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iggy_Pop.jpg

 68%|██████▊   | 6032/8920 [1:39:38<51:43,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Randy_Travis.jpg

 68%|██████▊   | 6033/8920 [1:39:39<44:16,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Gates.jpg

 68%|██████▊   | 6034/8920 [1:39:39<36:29,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Blair.jpg

 68%|██████▊   | 6035/8920 [1:39:39<29:38,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ingrid_Kristiansen.jpg

 68%|██████▊   | 6036/8920 [1:39:41<37:32,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathleen_Kennedy.jpg

 68%|██████▊   | 6037/8920 [1:39:41<36:34,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diego_Maradona.jpg

 68%|██████▊   | 6038/8920 [1:39:42<32:30,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Montana.jpg

 68%|██████▊   | 6039/8920 [1:39:43<33:58,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Letterman.jpg

 68%|██████▊   | 6040/8920 [1:39:43<27:39,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathy_Hochul.jpg

 68%|██████▊   | 6041/8920 [1:39:43<25:46,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugh_Grant.jpg

 68%|██████▊   | 6042/8920 [1:39:45<37:26,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Homer_Simpson.jpg

 68%|██████▊   | 6043/8920 [1:39:46<48:25,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierce_Brosnan.jpg

 68%|██████▊   | 6044/8920 [1:39:48<58:09,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Teller.jpg

 68%|██████▊   | 6045/8920 [1:39:48<49:30,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Dean.jpg

 68%|██████▊   | 6046/8920 [1:39:50<53:56,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madonna.jpg

 68%|██████▊   | 6047/8920 [1:39:50<43:11,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camilla_Parker_Bowles.jpg

 68%|██████▊   | 6048/8920 [1:39:53<1:05:03,  1.36s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerry_Adams.jpg

 68%|██████▊   | 6049/8920 [1:39:53<49:59,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drew_Carey.jpg

 68%|██████▊   | 6050/8920 [1:39:54<43:45,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Hamilton.jpg

 68%|██████▊   | 6051/8920 [1:39:55<49:57,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheryl_Crow.jpg

 68%|██████▊   | 6052/8920 [1:39:55<38:59,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conan_O'Brien.jpg

 68%|██████▊   | 6053/8920 [1:39:55<32:00,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Jones.jpg

 68%|██████▊   | 6054/8920 [1:39:58<52:21,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spike_Lee.jpg

 68%|██████▊   | 6055/8920 [1:39:59<52:42,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Colbert.jpg

 68%|██████▊   | 6056/8920 [1:40:00<51:34,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rigoberta_Menchú.jpg

 68%|██████▊   | 6057/8920 [1:40:01<53:45,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Lee_Roth.jpg

 68%|██████▊   | 6058/8920 [1:40:01<44:32,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mick_Fleetwood.jpg

 68%|██████▊   | 6059/8920 [1:40:02<38:08,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Clooney.jpg

 68%|██████▊   | 6060/8920 [1:40:04<56:05,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fumio_Kishida.jpg

 68%|██████▊   | 6061/8920 [1:40:05<46:59,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Mellencamp.jpg

 68%|██████▊   | 6062/8920 [1:40:05<41:48,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andy_Gibb.jpg

 68%|██████▊   | 6063/8920 [1:40:05<33:07,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Idriss_Déby.jpg

 68%|██████▊   | 6064/8920 [1:40:06<26:21,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chesley_Sullenberger.jpg

 68%|██████▊   | 6065/8920 [1:40:08<45:01,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_May.jpg

 68%|██████▊   | 6066/8920 [1:40:08<43:13,  1.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agnetha_Fältskog.jpg

 68%|██████▊   | 6067/8920 [1:40:09<33:52,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scott_Kelly.jpg

 68%|██████▊   | 6068/8920 [1:40:10<46:04,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Morello.jpg

 68%|██████▊   | 6069/8920 [1:40:10<35:26,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_W._Bush.jpg

 68%|██████▊   | 6070/8920 [1:40:11<29:15,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Clayton.jpg

 68%|██████▊   | 6071/8920 [1:40:11<24:28,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Garry_Kasparov.jpg

 68%|██████▊   | 6072/8920 [1:40:11<21:22,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Thorogood.jpg

 68%|██████▊   | 6073/8920 [1:40:13<32:24,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shinya_Yamanaka.jpg

 68%|██████▊   | 6074/8920 [1:40:13<30:24,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Copperfield.jpg

 68%|██████▊   | 6075/8920 [1:40:14<33:02,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_O'Hara.jpg

 68%|██████▊   | 6076/8920 [1:40:16<48:57,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darryl_Strawberry.jpg

 68%|██████▊   | 6077/8920 [1:40:16<38:16,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Hamill.jpg

 68%|██████▊   | 6078/8920 [1:40:16<30:58,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerry_Seinfeld.jpg

 68%|██████▊   | 6079/8920 [1:40:18<45:44,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_H._Macy.jpg

 68%|██████▊   | 6080/8920 [1:40:19<49:48,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Berners-Lee.jpg

 68%|██████▊   | 6081/8920 [1:40:19<38:30,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Keaton.jpg

 68%|██████▊   | 6082/8920 [1:40:20<41:09,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Gore.jpg

 68%|██████▊   | 6083/8920 [1:40:22<48:00,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Twiggy.jpg

 68%|██████▊   | 6084/8920 [1:40:22<37:28,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gloria_Estefan.jpg

 68%|██████▊   | 6085/8920 [1:40:22<29:35,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benazir_Bhutto.jpg

 68%|██████▊   | 6086/8920 [1:40:23<24:12,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maureen_Mcgovern.jpg

 68%|██████▊   | 6087/8920 [1:40:23<20:11,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Cowell.jpg

 68%|██████▊   | 6088/8920 [1:40:23<19:45,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jayne_Torvill.jpg

 68%|██████▊   | 6089/8920 [1:40:24<24:24,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tim_Allen.jpg

 68%|██████▊   | 6090/8920 [1:40:25<26:21,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Willis.jpg

 68%|██████▊   | 6091/8920 [1:40:25<27:51,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Firth.jpg

 68%|██████▊   | 6092/8920 [1:40:26<33:47,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Murphy.jpg

 68%|██████▊   | 6093/8920 [1:40:27<30:42,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terry_Pratchett.jpg

 68%|██████▊   | 6094/8920 [1:40:27<26:24,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keir_Starmer.jpg

 68%|██████▊   | 6095/8920 [1:40:27<21:41,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keanu_Reeves.jpg

 68%|██████▊   | 6096/8920 [1:40:28<21:38,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Bach.jpg

 68%|██████▊   | 6097/8920 [1:40:28<19:34,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chrissie_Hynde.jpg

 68%|██████▊   | 6098/8920 [1:40:28<16:51,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sharon_Stone.jpg

 68%|██████▊   | 6099/8920 [1:40:29<17:24,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Lloyd_Webber.jpg

 68%|██████▊   | 6100/8920 [1:40:29<15:53,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Peterson.jpg

 68%|██████▊   | 6101/8920 [1:40:30<29:38,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_Gibb.jpg

 68%|██████▊   | 6102/8920 [1:40:31<29:38,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vince_Gill.jpg

 68%|██████▊   | 6103/8920 [1:40:31<24:06,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Jordan.jpg

 68%|██████▊   | 6104/8920 [1:40:31<20:33,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bono.jpg

 68%|██████▊   | 6105/8920 [1:40:32<21:57,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chaka_Khan.jpg

 68%|██████▊   | 6106/8920 [1:40:33<23:34,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Bon_Jovi.jpg

 68%|██████▊   | 6107/8920 [1:40:33<24:15,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sting.jpg

 68%|██████▊   | 6108/8920 [1:40:34<33:52,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ken_Follett.jpg

 68%|██████▊   | 6109/8920 [1:40:35<28:03,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Wozniak.jpg

 68%|██████▊   | 6110/8920 [1:40:36<37:22,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Agre.jpg

 69%|██████▊   | 6111/8920 [1:40:36<30:14,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billy_Joel.jpg

 69%|██████▊   | 6112/8920 [1:40:36<24:16,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Putin.jpg

 69%|██████▊   | 6113/8920 [1:40:37<20:53,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Plant.jpg

 69%|██████▊   | 6114/8920 [1:40:38<31:46,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Quentin_Tarantino.jpg

 69%|██████▊   | 6115/8920 [1:40:38<26:03,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Douglas_Adams.jpg

 69%|██████▊   | 6116/8920 [1:40:38<22:02,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stevie_Wonder.jpg

 69%|██████▊   | 6117/8920 [1:40:39<22:48,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Korbut.jpg

 69%|██████▊   | 6118/8920 [1:40:41<39:11,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Belichick.jpg

 69%|██████▊   | 6119/8920 [1:40:41<32:10,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Osama_Bin_Laden.jpg

 69%|██████▊   | 6120/8920 [1:40:41<25:34,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Krugman.jpg

 69%|██████▊   | 6121/8920 [1:40:41<20:46,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Ma.jpg

 69%|██████▊   | 6122/8920 [1:40:42<18:05,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kareem_Abdul-Jabbar.jpg

 69%|██████▊   | 6123/8920 [1:40:42<22:29,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Hetfield.jpg

 69%|██████▊   | 6124/8920 [1:40:43<19:46,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linda_Ronstadt.jpg

 69%|██████▊   | 6125/8920 [1:40:43<18:01,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Yushchenko.jpg

 69%|██████▊   | 6126/8920 [1:40:43<17:11,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arnold_Schwarzenegger.jpg

 69%|██████▊   | 6127/8920 [1:40:44<15:05,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joaquín_"El_Chapo"_Guzmán.jpg

 69%|██████▊   | 6128/8920 [1:40:44<19:48,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Kobilka.jpg

 69%|██████▊   | 6129/8920 [1:40:44<17:48,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Bocelli.jpg

 69%|██████▊   | 6130/8920 [1:40:45<15:44,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Dimon.jpg

 69%|██████▊   | 6131/8920 [1:40:45<15:44,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phil_Collins.jpg

 69%|██████▊   | 6132/8920 [1:40:46<18:29,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elle_Macpherson.jpg

 69%|██████▉   | 6133/8920 [1:40:46<17:10,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jet_Li.jpg

 69%|██████▉   | 6134/8920 [1:40:46<15:44,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Springsteen.jpg

 69%|██████▉   | 6135/8920 [1:40:46<14:39,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Jobs.jpg

 69%|██████▉   | 6136/8920 [1:40:47<13:21,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liza_Minnelli.jpg

 69%|██████▉   | 6137/8920 [1:40:48<24:23,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Narendra_Modi.jpg

 69%|██████▉   | 6138/8920 [1:40:48<25:40,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sid_Meier.jpg

 69%|██████▉   | 6139/8920 [1:40:49<21:44,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Ride.jpg

 69%|██████▉   | 6140/8920 [1:40:49<18:09,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobby_Sands.jpg

 69%|██████▉   | 6141/8920 [1:40:49<16:21,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elton_John.jpg

 69%|██████▉   | 6142/8920 [1:40:49<15:33,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enya.jpg

 69%|██████▉   | 6143/8920 [1:40:51<29:02,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Clarkson.jpg

 69%|██████▉   | 6144/8920 [1:40:51<25:27,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joy_Harjo.jpg

 69%|██████▉   | 6145/8920 [1:40:52<26:38,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Newsted.jpg

 69%|██████▉   | 6146/8920 [1:40:52<26:11,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Clinton.jpg

 69%|██████▉   | 6147/8920 [1:40:53<27:23,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barack_Obama.jpg

 69%|██████▉   | 6148/8920 [1:40:53<24:08,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Farndon.jpg

 69%|██████▉   | 6149/8920 [1:40:54<20:48,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Unser_Jr..jpg

 69%|██████▉   | 6150/8920 [1:40:54<17:52,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cher.jpg

 69%|██████▉   | 6151/8920 [1:40:54<21:12,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Groening.jpg

 69%|██████▉   | 6152/8920 [1:40:55<18:40,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ray_Kurzweil.jpg

 69%|██████▉   | 6153/8920 [1:40:55<16:40,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carole_Bayer_Sager.jpg

 69%|██████▉   | 6154/8920 [1:40:55<15:47,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Winfield.jpg

 69%|██████▉   | 6155/8920 [1:40:56<14:44,  3.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fred_Couples.jpg

 69%|██████▉   | 6156/8920 [1:40:56<21:28,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Sharpton.jpg

 69%|██████▉   | 6157/8920 [1:40:57<18:54,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tessa_Thompson.jpg

 69%|██████▉   | 6158/8920 [1:40:58<37:05,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexis_Ohanian.jpg

 69%|██████▉   | 6159/8920 [1:40:59<35:00,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessandra_Ambrosio.jpg

 69%|██████▉   | 6160/8920 [1:40:59<28:29,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thora_Birch.jpg

 69%|██████▉   | 6161/8920 [1:41:01<37:59,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mike_Krieger.jpg

 69%|██████▉   | 6162/8920 [1:41:02<44:18,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lady_Gaga.jpg

 69%|██████▉   | 6163/8920 [1:41:02<35:33,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cardi_B.jpg

 69%|██████▉   | 6164/8920 [1:41:02<28:06,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kacey_Musgraves.jpg

 69%|██████▉   | 6165/8920 [1:41:04<37:56,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Breanna_Stewart.jpg

 69%|██████▉   | 6166/8920 [1:41:04<35:21,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Megan_Rapinoe.jpg

 69%|██████▉   | 6167/8920 [1:41:07<53:57,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Mulaney.jpg

 69%|██████▉   | 6168/8920 [1:41:07<48:01,  1.05s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Mccoll.jpg

 69%|██████▉   | 6169/8920 [1:41:08<37:17,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Durk.jpg

 69%|██████▉   | 6170/8920 [1:41:08<34:54,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lily_James.jpg

 69%|██████▉   | 6171/8920 [1:41:08<28:12,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Petra_Kvitová.jpg

 69%|██████▉   | 6172/8920 [1:41:10<36:51,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohammed_Bin_Salman.jpg

 69%|██████▉   | 6173/8920 [1:41:10<28:58,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anita_Sarkeesian.jpg

 69%|██████▉   | 6174/8920 [1:41:11<36:45,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cobie_Smulders.jpg

 69%|██████▉   | 6175/8920 [1:41:11<30:14,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hayden_Christensen.jpg

 69%|██████▉   | 6176/8920 [1:41:12<24:47,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Stone.jpg

 69%|██████▉   | 6177/8920 [1:41:13<33:05,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Gad.jpg

 69%|██████▉   | 6178/8920 [1:41:13<26:48,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emily_Blunt.jpg

 69%|██████▉   | 6179/8920 [1:41:14<27:45,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sadio_Mane.jpg

 69%|██████▉   | 6180/8920 [1:41:15<30:10,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Wilde.jpg

 69%|██████▉   | 6181/8920 [1:41:15<25:59,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Wang.jpg

 69%|██████▉   | 6182/8920 [1:41:16<37:41,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yalitza_Aparicio.jpg

 69%|██████▉   | 6183/8920 [1:41:18<44:36,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emilia_Clarke.jpg

 69%|██████▉   | 6184/8920 [1:41:18<35:53,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Dyer.jpg

 69%|██████▉   | 6185/8920 [1:41:18<28:21,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tyler_Joseph.jpg

 69%|██████▉   | 6186/8920 [1:41:19<32:48,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Poppy_[Moriah_Rose_Pereira].jpg

 69%|██████▉   | 6187/8920 [1:41:19<26:14,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lleyton_Hewitt.jpg

 69%|██████▉   | 6188/8920 [1:41:20<22:06,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diogo_Jota.jpg

 69%|██████▉   | 6189/8920 [1:41:20<19:53,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikola_Jokić.jpg

 69%|██████▉   | 6190/8920 [1:41:22<46:49,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hozier.jpg

 69%|██████▉   | 6191/8920 [1:41:23<36:52,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shailene_Woodley.jpg

 69%|██████▉   | 6192/8920 [1:41:23<35:28,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Essien.jpg

 69%|██████▉   | 6193/8920 [1:41:24<27:59,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Cox.jpg

 69%|██████▉   | 6194/8920 [1:41:24<28:11,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ellie_Goulding.jpg

 69%|██████▉   | 6195/8920 [1:41:25<27:11,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tori_Kelly.jpg

 69%|██████▉   | 6196/8920 [1:41:25<22:53,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evan_Peters.jpg

 69%|██████▉   | 6197/8920 [1:41:26<26:59,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicholas_Hoult.jpg

 69%|██████▉   | 6198/8920 [1:41:26<22:50,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paulo_Dybala.jpg

 69%|██████▉   | 6199/8920 [1:41:26<18:54,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Krysten_Ritter.jpg

 70%|██████▉   | 6200/8920 [1:41:27<16:16,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guy_Sebastian.jpg

 70%|██████▉   | 6201/8920 [1:41:27<15:14,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Eve.jpg

 70%|██████▉   | 6202/8920 [1:41:28<20:36,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Cassidy.jpg

 70%|██████▉   | 6203/8920 [1:41:28<17:19,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pete_Davidson.jpg

 70%|██████▉   | 6204/8920 [1:41:29<23:46,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Vardy.jpg

 70%|██████▉   | 6205/8920 [1:41:30<31:13,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Candice_Swanepoel.jpg

 70%|██████▉   | 6206/8920 [1:41:30<26:32,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Sagan.jpg

 70%|██████▉   | 6207/8920 [1:41:32<36:21,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Ramos.jpg

 70%|██████▉   | 6208/8920 [1:41:32<28:32,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dwyane_Wade.jpg

 70%|██████▉   | 6209/8920 [1:41:32<24:39,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lindsey_Vonn.jpg

 70%|██████▉   | 6210/8920 [1:41:33<31:27,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shelly-Ann_Fraser-Pryce.jpg

 70%|██████▉   | 6211/8920 [1:41:34<31:42,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jojo_[Joanna_Levesque].jpg

 70%|██████▉   | 6212/8920 [1:41:34<25:28,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jodie_Sweetin.jpg

 70%|██████▉   | 6213/8920 [1:41:35<35:19,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luis_Suárez.jpg

 70%|██████▉   | 6214/8920 [1:41:36<28:45,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Redmayne.jpg

 70%|██████▉   | 6215/8920 [1:41:36<26:25,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dababy.jpg

 70%|██████▉   | 6216/8920 [1:41:37<26:10,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Peaty.jpg

 70%|██████▉   | 6217/8920 [1:41:37<26:37,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bob_Morley.jpg

 70%|██████▉   | 6218/8920 [1:41:39<35:54,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Future_[Nayvadius_Wilburn].jpg

 70%|██████▉   | 6219/8920 [1:41:39<35:28,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexis_Sánchez.jpg

 70%|██████▉   | 6220/8920 [1:41:40<39:21,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adrienne_Bailon.jpg

 70%|██████▉   | 6221/8920 [1:41:41<31:50,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanessa_Hudgens.jpg

 70%|██████▉   | 6222/8920 [1:41:41<26:09,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabby_Douglas.jpg

 70%|██████▉   | 6223/8920 [1:41:41<21:15,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelique_Kerber.jpg

 70%|██████▉   | 6224/8920 [1:41:42<22:39,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicola_Peltz.jpg

 70%|██████▉   | 6225/8920 [1:41:44<38:13,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ana_Ivanović.jpg

 70%|██████▉   | 6226/8920 [1:41:44<30:10,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Lee.jpg

 70%|██████▉   | 6227/8920 [1:41:44<23:57,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jared_Kushner.jpg

 70%|██████▉   | 6228/8920 [1:41:45<32:39,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Derrick_Henry.jpg

 70%|██████▉   | 6229/8920 [1:41:45<26:51,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karen_Gillan.jpg

 70%|██████▉   | 6230/8920 [1:41:46<27:30,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hayley_Williams.jpg

 70%|██████▉   | 6231/8920 [1:41:47<30:24,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Medina.jpg

 70%|██████▉   | 6232/8920 [1:41:48<36:40,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Quinn.jpg

 70%|██████▉   | 6233/8920 [1:41:48<29:55,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yani_Tseng.jpg

 70%|██████▉   | 6234/8920 [1:41:49<27:31,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Michaels.jpg

 70%|██████▉   | 6235/8920 [1:41:50<40:01,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Labrinth_[Timothy_Lee_Mckenzie].jpg

 70%|██████▉   | 6236/8920 [1:41:51<35:49,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Rodgers.jpg

 70%|██████▉   | 6237/8920 [1:41:53<45:08,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Kane.jpg

 70%|██████▉   | 6238/8920 [1:41:53<35:05,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivanka_Trump.jpg

 70%|██████▉   | 6239/8920 [1:41:53<32:07,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dove_Cameron.jpg

 70%|██████▉   | 6240/8920 [1:41:54<26:18,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xander_Schauffele.jpg

 70%|██████▉   | 6241/8920 [1:41:54<21:51,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raven-Symoné.jpg

 70%|██████▉   | 6242/8920 [1:41:55<34:27,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jade_Thirlwall.jpg

 70%|██████▉   | 6243/8920 [1:41:56<28:18,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magnus_Carlsen.jpg

 70%|███████   | 6244/8920 [1:41:56<25:46,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Systrom.jpg

 70%|███████   | 6245/8920 [1:41:56<21:05,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuzuru_Hanyu.jpg

 70%|███████   | 6246/8920 [1:41:57<18:10,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Burrow.jpg

 70%|███████   | 6247/8920 [1:41:57<17:08,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Oosthuizen.jpg

 70%|███████   | 6248/8920 [1:41:57<19:07,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Klay_Thompson.jpg

 70%|███████   | 6249/8920 [1:41:58<17:06,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Swann_Arlaud.jpg

 70%|███████   | 6250/8920 [1:41:59<29:07,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cynthia_Erivo.jpg

 70%|███████   | 6251/8920 [1:42:01<49:59,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hailee_Steinfeld.jpg

 70%|███████   | 6252/8920 [1:42:02<38:49,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kane_Brown.jpg

 70%|███████   | 6253/8920 [1:42:02<30:09,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carly_Rae_Jepsen.jpg

 70%|███████   | 6254/8920 [1:42:02<24:53,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesse_Lingard.jpg

 70%|███████   | 6255/8920 [1:42:03<25:41,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hope_Hicks.jpg

 70%|███████   | 6256/8920 [1:42:03<21:18,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Hathaway.jpg

 70%|███████   | 6257/8920 [1:42:03<19:28,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alison_Brie.jpg

 70%|███████   | 6258/8920 [1:42:04<17:19,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rita_Ora.jpg

 70%|███████   | 6259/8920 [1:42:05<33:50,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miranda_Lambert.jpg

 70%|███████   | 6260/8920 [1:42:06<31:44,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonah_Hill.jpg

 70%|███████   | 6261/8920 [1:42:07<42:43,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Heaton.jpg

 70%|███████   | 6262/8920 [1:42:08<39:17,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_B._Jordan.jpg

 70%|███████   | 6263/8920 [1:42:08<30:46,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bethany_Hamilton.jpg

 70%|███████   | 6264/8920 [1:42:09<25:17,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janelle_Monáe.jpg

 70%|███████   | 6265/8920 [1:42:09<27:35,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sultan_Kösen.jpg

 70%|███████   | 6266/8920 [1:42:15<1:38:28,  2.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mia_Wasikowska.jpg

 70%|███████   | 6267/8920 [1:42:16<1:13:39,  1.67s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sza.jpg

 70%|███████   | 6268/8920 [1:42:17<1:15:36,  1.71s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timothée_Chalamet.jpg

 70%|███████   | 6269/8920 [1:42:19<1:08:52,  1.56s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Smith.jpg

 70%|███████   | 6270/8920 [1:42:20<1:06:06,  1.50s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Burling.jpg

 70%|███████   | 6271/8920 [1:42:21<56:01,  1.27s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Driver.jpg

 70%|███████   | 6272/8920 [1:42:21<43:35,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Baby.jpg

 70%|███████   | 6273/8920 [1:42:23<52:05,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Ondra.jpg

 70%|███████   | 6274/8920 [1:42:23<40:27,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doja_Cat.jpg

 70%|███████   | 6275/8920 [1:42:25<54:02,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Hiddleston.jpg

 70%|███████   | 6276/8920 [1:42:26<54:19,  1.23s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Pierce_Bush.jpg

 70%|███████   | 6277/8920 [1:42:26<41:19,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthew_Stafford.jpg

 70%|███████   | 6278/8920 [1:42:27<37:18,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raheem_Sterling.jpg

 70%|███████   | 6279/8920 [1:42:27<29:13,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jon_Batiste.jpg

 70%|███████   | 6280/8920 [1:42:29<39:06,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cameron_Bright.jpg

 70%|███████   | 6281/8920 [1:42:29<30:26,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kendall_Jenner.jpg

 70%|███████   | 6282/8920 [1:42:30<31:04,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zoë_Kravitz.jpg

 70%|███████   | 6283/8920 [1:42:30<31:44,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bryson_Tiller.jpg

 70%|███████   | 6284/8920 [1:42:31<28:39,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calvin_Harris.jpg

 70%|███████   | 6285/8920 [1:42:32<38:55,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karim_Benzema.jpg

 70%|███████   | 6286/8920 [1:42:33<34:51,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jyoti_Amge.jpg

 70%|███████   | 6287/8920 [1:42:34<31:58,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davido.jpg

 70%|███████   | 6288/8920 [1:42:34<26:59,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amanda_Seyfried.jpg

 71%|███████   | 6289/8920 [1:42:35<31:52,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronnie_Radke.jpg

 71%|███████   | 6290/8920 [1:42:36<43:50,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Foles.jpg

 71%|███████   | 6291/8920 [1:42:39<1:06:26,  1.52s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mckayla_Maroney.jpg

 71%|███████   | 6292/8920 [1:42:39<50:00,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefanie_Scott.jpg

 71%|███████   | 6293/8920 [1:42:40<39:19,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Holmes.jpg

 71%|███████   | 6294/8920 [1:42:40<31:07,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Avicii.jpg

 71%|███████   | 6295/8920 [1:42:41<35:39,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorena_Ochoa.jpg

 71%|███████   | 6296/8920 [1:42:42<41:28,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cory_Monteith.jpg

 71%|███████   | 6297/8920 [1:42:43<32:41,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florence_Pugh.jpg

 71%|███████   | 6299/8920 [1:42:43<24:18,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Britney_Spears.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Seok-Jin.jpg

 71%|███████   | 6300/8920 [1:42:44<19:58,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chrissy_Teigen.jpg

 71%|███████   | 6301/8920 [1:42:45<29:13,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Puth.jpg

 71%|███████   | 6302/8920 [1:42:45<23:47,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giannis_Antetokounmpo.jpg

 71%|███████   | 6303/8920 [1:42:46<22:58,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Poonam_Pandey.jpg

 71%|███████   | 6304/8920 [1:42:47<32:08,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Tomlinson.jpg

 71%|███████   | 6305/8920 [1:42:47<26:11,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/A_Boogie_Wit_Da_Hoodie.jpg

 71%|███████   | 6306/8920 [1:42:48<33:54,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eli_Manning.jpg

 71%|███████   | 6307/8920 [1:42:49<27:48,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorde.jpg

 71%|███████   | 6308/8920 [1:42:50<37:16,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Gatlin.jpg

 71%|███████   | 6309/8920 [1:42:50<29:47,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Tae-Hyung.jpg

 71%|███████   | 6310/8920 [1:42:52<48:02,  1.10s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theo_James.jpg

 71%|███████   | 6311/8920 [1:42:53<42:47,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drake.jpg

 71%|███████   | 6312/8920 [1:42:54<38:15,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eliud_Kipchoge.jpg

 71%|███████   | 6313/8920 [1:42:55<40:33,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ciara.jpg

 71%|███████   | 6314/8920 [1:42:55<31:49,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicki_Minaj.jpg

 71%|███████   | 6315/8920 [1:42:56<31:36,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zayn_Malik.jpg

 71%|███████   | 6316/8920 [1:42:57<36:38,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Roberts.jpg

 71%|███████   | 6317/8920 [1:42:59<49:37,  1.14s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Styles.jpg

 71%|███████   | 6318/8920 [1:43:00<46:03,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolly_The_Sheep.jpg

 71%|███████   | 6319/8920 [1:43:01<47:07,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaley_Cuoco.jpg

 71%|███████   | 6320/8920 [1:43:01<36:14,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Sherman.jpg

 71%|███████   | 6321/8920 [1:43:02<33:19,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pewdiepie.jpg

 71%|███████   | 6322/8920 [1:43:02<26:13,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Russell_Wilson.jpg

 71%|███████   | 6323/8920 [1:43:02<22:10,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alicia_Keys.jpg

 71%|███████   | 6324/8920 [1:43:03<24:20,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Travis_Kelce.jpg

 71%|███████   | 6325/8920 [1:43:03<24:59,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Ramos.jpg

 71%|███████   | 6326/8920 [1:43:05<35:15,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stacy_Lewis.jpg

 71%|███████   | 6327/8920 [1:43:05<30:07,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shohei_Ohtani.jpg

 71%|███████   | 6328/8920 [1:43:06<37:42,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J._J._Watt.jpg

 71%|███████   | 6329/8920 [1:43:08<47:47,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inbee_Park.jpg

 71%|███████   | 6330/8920 [1:43:08<37:48,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timnit_Gebru.jpg

 71%|███████   | 6331/8920 [1:43:09<29:24,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Schumer.jpg

 71%|███████   | 6332/8920 [1:43:09<24:23,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Kirk.jpg

 71%|███████   | 6333/8920 [1:43:10<25:12,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Roethlisberger.jpg

 71%|███████   | 6334/8920 [1:43:10<24:54,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Guaidó.jpg

 71%|███████   | 6335/8920 [1:43:11<28:00,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Pogba.jpg

 71%|███████   | 6336/8920 [1:43:12<32:40,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taran_Killam.jpg

 71%|███████   | 6337/8920 [1:43:13<37:57,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohamed_Salah.jpg

 71%|███████   | 6338/8920 [1:43:14<35:08,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justine_Henin.jpg

 71%|███████   | 6339/8920 [1:43:15<41:21,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Kaepernick.jpg

 71%|███████   | 6340/8920 [1:43:15<32:00,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Stöhr.jpg

 71%|███████   | 6341/8920 [1:43:16<25:52,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Holasoygerman.jpg

 71%|███████   | 6342/8920 [1:43:17<31:14,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Thomas.jpg

 71%|███████   | 6343/8920 [1:43:17<24:51,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kesha.jpg

 71%|███████   | 6344/8920 [1:43:17<20:13,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/G-Eazy.jpg

 71%|███████   | 6345/8920 [1:43:17<18:02,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooks_Koepka.jpg

 71%|███████   | 6346/8920 [1:43:18<20:51,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scarlett_Johansson.jpg

 71%|███████   | 6347/8920 [1:43:19<27:55,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wayne_Rooney.jpg

 71%|███████   | 6348/8920 [1:43:20<28:31,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miley_Cyrus.jpg

 71%|███████   | 6349/8920 [1:43:21<35:12,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bonnie_Wright.jpg

 71%|███████   | 6350/8920 [1:43:21<27:39,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Timberlake.jpg

 71%|███████   | 6351/8920 [1:43:22<27:21,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chloé_Zhao.jpg

 71%|███████   | 6352/8920 [1:43:22<21:54,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Selena_Gomez.jpg

 71%|███████   | 6353/8920 [1:43:24<33:54,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Clijsters.jpg

 71%|███████   | 6354/8920 [1:43:25<38:18,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Lynn_Spears.jpg

 71%|███████   | 6355/8920 [1:43:25<33:04,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Judge.jpg

 71%|███████▏  | 6356/8920 [1:43:26<31:41,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Claire_Foy.jpg

 71%|███████▏  | 6357/8920 [1:43:27<31:59,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elaine_Thompson-Herah.jpg

 71%|███████▏  | 6358/8920 [1:43:30<1:05:42,  1.54s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacob_Blake.jpg

 71%|███████▏  | 6359/8920 [1:43:31<55:47,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Cera.jpg

 71%|███████▏  | 6360/8920 [1:43:31<42:43,  1.00s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Leslie.jpg

 71%|███████▏  | 6361/8920 [1:43:34<1:03:15,  1.48s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brendon_Mccullum.jpg

 71%|███████▏  | 6362/8920 [1:43:34<47:38,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saoirse_Ronan.jpg

 71%|███████▏  | 6363/8920 [1:43:34<36:49,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesy_Nelson.jpg

 71%|███████▏  | 6364/8920 [1:43:34<28:54,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Canelo_Álvarez.jpg

 71%|███████▏  | 6365/8920 [1:43:35<27:14,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katy_Perry.jpg

 71%|███████▏  | 6366/8920 [1:43:36<37:40,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brittany_Snow.jpg

 71%|███████▏  | 6367/8920 [1:43:37<29:41,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Hemsworth.jpg

 71%|███████▏  | 6368/8920 [1:43:37<27:40,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristiano_Ronaldo.jpg

 71%|███████▏  | 6369/8920 [1:43:38<30:42,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Ortega.jpg

 71%|███████▏  | 6370/8920 [1:43:39<30:36,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Constance_Wu.jpg

 71%|███████▏  | 6371/8920 [1:43:41<46:02,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dev_Patel.jpg

 71%|███████▏  | 6372/8920 [1:43:41<35:06,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duffy.jpg

 71%|███████▏  | 6373/8920 [1:43:42<43:17,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rory_Mcilroy.jpg

 71%|███████▏  | 6374/8920 [1:43:45<56:45,  1.34s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Boyega.jpg

 71%|███████▏  | 6375/8920 [1:43:45<43:49,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trevor_Noah.jpg

 71%|███████▏  | 6376/8920 [1:43:47<52:58,  1.25s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_Brosnahan.jpg

 71%|███████▏  | 6377/8920 [1:43:47<40:55,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scottie_Scheffler.jpg

 72%|███████▏  | 6378/8920 [1:43:48<39:43,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Olsen.jpg

 72%|███████▏  | 6379/8920 [1:43:48<31:18,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Weeknd.jpg

 72%|███████▏  | 6380/8920 [1:43:48<24:44,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elijah_Wood.jpg

 72%|███████▏  | 6381/8920 [1:43:49<25:54,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Lochte.jpg

 72%|███████▏  | 6382/8920 [1:43:51<45:27,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lebron_James.jpg

 72%|███████▏  | 6383/8920 [1:43:51<35:17,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Isner.jpg

 72%|███████▏  | 6384/8920 [1:43:52<27:35,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kit_Harington.jpg

 72%|███████▏  | 6385/8920 [1:43:52<22:51,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manuel_Neuer.jpg

 72%|███████▏  | 6386/8920 [1:43:54<39:47,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Mckeon.jpg

 72%|███████▏  | 6387/8920 [1:43:54<31:34,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aziz_Ansari.jpg

 72%|███████▏  | 6388/8920 [1:43:55<40:00,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Sharma.jpg

 72%|███████▏  | 6389/8920 [1:43:56<37:27,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Virat_Kohli.jpg

 72%|███████▏  | 6390/8920 [1:43:59<57:53,  1.37s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bethany_Joy_Lenz.jpg

 72%|███████▏  | 6391/8920 [1:44:00<50:57,  1.21s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_Sprouse.jpg

 72%|███████▏  | 6392/8920 [1:44:00<44:57,  1.07s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Young.jpg

 72%|███████▏  | 6393/8920 [1:44:01<37:27,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Young_M.A.jpg

 72%|███████▏  | 6394/8920 [1:44:01<30:34,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Peirsol.jpg

 72%|███████▏  | 6395/8920 [1:44:02<31:20,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurent_Duvernay-Tardif.jpg

 72%|███████▏  | 6396/8920 [1:44:03<29:52,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joseph_Mazzello.jpg

 72%|███████▏  | 6397/8920 [1:44:03<25:38,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Taurasi.jpg

 72%|███████▏  | 6398/8920 [1:44:04<31:51,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marshawn_Lynch.jpg

 72%|███████▏  | 6399/8920 [1:44:04<26:05,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Holland.jpg

 72%|███████▏  | 6400/8920 [1:44:05<21:44,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Swift.jpg

 72%|███████▏  | 6401/8920 [1:44:05<21:26,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Puccio.jpg

 72%|███████▏  | 6402/8920 [1:44:05<19:04,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ava_Max.jpg

 72%|███████▏  | 6403/8920 [1:44:06<17:01,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suzann_Pettersen.jpg

 72%|███████▏  | 6404/8920 [1:44:06<19:00,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyrie_Irving.jpg

 72%|███████▏  | 6405/8920 [1:44:07<16:47,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rupert_Grint.jpg

 72%|███████▏  | 6406/8920 [1:44:07<23:43,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Hutcherson.jpg

 72%|███████▏  | 6407/8920 [1:44:09<34:27,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/El_Rubius.jpg

 72%|███████▏  | 6408/8920 [1:44:09<29:03,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenenisa_Bekele.jpg

 72%|███████▏  | 6409/8920 [1:44:10<24:01,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Wie.jpg

 72%|███████▏  | 6410/8920 [1:44:10<20:22,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ms_Dhoni.jpg

 72%|███████▏  | 6411/8920 [1:44:12<35:40,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conor_Mcgregor.jpg

 72%|███████▏  | 6412/8920 [1:44:12<34:57,  1.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chance_The_Rapper.jpg

 72%|███████▏  | 6413/8920 [1:44:14<46:29,  1.11s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Cavill.jpg

 72%|███████▏  | 6414/8920 [1:44:15<46:43,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Lee.jpg

 72%|███████▏  | 6415/8920 [1:44:16<46:45,  1.12s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evan_Rachel_Wood.jpg

 72%|███████▏  | 6416/8920 [1:44:18<54:36,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gunna.jpg

 72%|███████▏  | 6417/8920 [1:44:19<54:45,  1.31s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/N'Golo_Kante.jpg

 72%|███████▏  | 6418/8920 [1:44:20<41:39,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucy_Hale.jpg

 72%|███████▏  | 6419/8920 [1:44:20<32:39,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lena_Dunham.jpg

 72%|███████▏  | 6420/8920 [1:44:20<25:44,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joel_Embiid.jpg

 72%|███████▏  | 6421/8920 [1:44:21<27:02,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Morgan.jpg

 72%|███████▏  | 6422/8920 [1:44:22<31:26,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyle_Busch.jpg

 72%|███████▏  | 6423/8920 [1:44:23<29:43,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calum_Scott.jpg

 72%|███████▏  | 6424/8920 [1:44:24<36:51,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Kournikova.jpg

 72%|███████▏  | 6425/8920 [1:44:24<29:54,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniil_Medvedev.jpg

 72%|███████▏  | 6426/8920 [1:44:25<28:49,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brittany_Lincicome.jpg

 72%|███████▏  | 6427/8920 [1:44:26<29:15,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bad_Bunny.jpg

 72%|███████▏  | 6428/8920 [1:44:27<41:48,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Li_Na.jpg

 72%|███████▏  | 6429/8920 [1:44:28<42:56,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Franco.jpg

 72%|███████▏  | 6430/8920 [1:44:30<46:56,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Tavares.jpg

 72%|███████▏  | 6431/8920 [1:44:31<42:45,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edward_Snowden.jpg

 72%|███████▏  | 6432/8920 [1:44:31<33:24,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Altuve.jpg

 72%|███████▏  | 6433/8920 [1:44:31<26:00,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phoebe_Waller-Bridge.jpg

 72%|███████▏  | 6434/8920 [1:44:31<21:15,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elisabeth_Moss.jpg

 72%|███████▏  | 6435/8920 [1:44:32<17:56,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shia_Labeouf.jpg

 72%|███████▏  | 6436/8920 [1:44:32<15:53,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessia_Cara.jpg

 72%|███████▏  | 6437/8920 [1:44:33<23:19,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Kurz.jpg

 72%|███████▏  | 6438/8920 [1:44:35<48:57,  1.18s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emile_Hirsch.jpg

 72%|███████▏  | 6439/8920 [1:44:37<51:13,  1.24s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Casey_Neistat.jpg

 72%|███████▏  | 6440/8920 [1:44:38<53:20,  1.29s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Logan.jpg

 72%|███████▏  | 6441/8920 [1:44:38<41:05,  1.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Sharapova.jpg

 72%|███████▏  | 6442/8920 [1:44:39<36:01,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Stump.jpg

 72%|███████▏  | 6443/8920 [1:44:40<41:47,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Léa_Seydoux.jpg

 72%|███████▏  | 6444/8920 [1:44:41<32:10,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Stiles.jpg

 72%|███████▏  | 6445/8920 [1:44:41<25:48,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robbie_Amell.jpg

 72%|███████▏  | 6446/8920 [1:44:42<28:57,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paris_Hilton.jpg

 72%|███████▏  | 6447/8920 [1:44:43<41:03,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cole_Sprouse.jpg

 72%|███████▏  | 6448/8920 [1:44:44<35:30,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Allen.jpg

 72%|███████▏  | 6449/8920 [1:44:44<28:14,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emily_Osment.jpg

 72%|███████▏  | 6450/8920 [1:44:45<33:41,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaimie_Alexander.jpg

 72%|███████▏  | 6451/8920 [1:44:46<31:48,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jd_Vance.jpg

 72%|███████▏  | 6452/8920 [1:44:46<24:46,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carol_E._Reiley.jpg

 72%|███████▏  | 6453/8920 [1:44:47<20:02,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xie_Na.jpg

 72%|███████▏  | 6454/8920 [1:44:47<22:55,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessie_J.jpg

 72%|███████▏  | 6455/8920 [1:44:47<19:13,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Degarmo.jpg

 72%|███████▏  | 6456/8920 [1:44:48<16:49,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Megan_Thee_Stallion.jpg

 72%|███████▏  | 6457/8920 [1:44:49<22:57,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gareth_Bale.jpg

 72%|███████▏  | 6458/8920 [1:44:49<18:54,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Stokes.jpg

 72%|███████▏  | 6459/8920 [1:44:50<23:59,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soulja_Boy.jpg

 72%|███████▏  | 6460/8920 [1:44:50<25:33,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dakota_Fanning.jpg

 72%|███████▏  | 6461/8920 [1:44:52<39:50,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benny_Blanco.jpg

 72%|███████▏  | 6462/8920 [1:44:53<31:05,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_William.jpg

 72%|███████▏  | 6463/8920 [1:44:53<24:37,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joshua_Wong.jpg

 72%|███████▏  | 6464/8920 [1:44:53<20:01,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Reynolds.jpg

 72%|███████▏  | 6465/8920 [1:44:53<16:59,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jamie_Dornan.jpg

 72%|███████▏  | 6466/8920 [1:44:55<28:00,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Müller.jpg

 72%|███████▎  | 6467/8920 [1:44:55<22:20,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rob_Gronkowski.jpg

 73%|███████▎  | 6468/8920 [1:44:56<30:08,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Davis.jpg

 73%|███████▎  | 6469/8920 [1:44:56<24:39,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bobi_Wine.jpg

 73%|███████▎  | 6470/8920 [1:44:57<21:21,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adriana_Lima.jpg

 73%|███████▎  | 6471/8920 [1:44:58<26:08,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Post_Malone.jpg

 73%|███████▎  | 6472/8920 [1:45:00<47:54,  1.17s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rami_Malek.jpg

 73%|███████▎  | 6473/8920 [1:45:01<49:45,  1.22s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lindsay_Lohan.jpg

 73%|███████▎  | 6474/8920 [1:45:02<39:20,  1.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gugu_Mbatha-Raw.jpg

 73%|███████▎  | 6475/8920 [1:45:02<33:30,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bebe_Rexha.jpg

 73%|███████▎  | 6476/8920 [1:45:03<36:37,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Azarenka.jpg

 73%|███████▎  | 6477/8920 [1:45:05<44:08,  1.08s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandre_Bilodeau.jpg

 73%|███████▎  | 6478/8920 [1:45:05<35:01,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Brown.jpg

 73%|███████▎  | 6479/8920 [1:45:05<28:44,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Spieth.jpg

 73%|███████▎  | 6480/8920 [1:45:06<23:42,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greta_Gerwig.jpg

 73%|███████▎  | 6481/8920 [1:45:06<19:59,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne-Marie.jpg

 73%|███████▎  | 6482/8920 [1:45:07<24:28,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antoine_Griezmann.jpg

 73%|███████▎  | 6483/8920 [1:45:07<19:49,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fan_Bingbing.jpg

 73%|███████▎  | 6484/8920 [1:45:09<34:01,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elliot_Page.jpg

 73%|███████▎  | 6485/8920 [1:45:09<26:29,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leona_Lewis.jpg

 73%|███████▎  | 6486/8920 [1:45:10<26:31,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khloé_Kardashian.jpg

 73%|███████▎  | 6487/8920 [1:45:10<22:10,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary-Kate_Olsen.jpg

 73%|███████▎  | 6488/8920 [1:45:10<18:18,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haley_Joel_Osment.jpg

 73%|███████▎  | 6489/8920 [1:45:10<15:40,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Carter.jpg

 73%|███████▎  | 6490/8920 [1:45:11<14:21,  2.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morgan_Wallen.jpg

 73%|███████▎  | 6491/8920 [1:45:12<22:00,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andy_Roddick.jpg

 73%|███████▎  | 6492/8920 [1:45:12<18:48,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Kitsch.jpg

 73%|███████▎  | 6493/8920 [1:45:12<16:47,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freddie_Highmore.jpg

 73%|███████▎  | 6494/8920 [1:45:12<14:55,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gedhun_Choekyi_Nyima.jpg

 73%|███████▎  | 6495/8920 [1:45:13<13:26,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaká.jpg

 73%|███████▎  | 6496/8920 [1:45:13<18:24,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caroline_Wozniacki.jpg

 73%|███████▎  | 6497/8920 [1:45:14<16:33,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Chesky.jpg

 73%|███████▎  | 6498/8920 [1:45:15<20:55,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tyson_Fury.jpg

 73%|███████▎  | 6499/8920 [1:45:15<17:54,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demarcus_Cousins.jpg

 73%|███████▎  | 6500/8920 [1:45:15<15:14,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Mciver.jpg

 73%|███████▎  | 6501/8920 [1:45:16<26:12,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Alba.jpg

 73%|███████▎  | 6502/8920 [1:45:18<34:01,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keira_Knightley.jpg

 73%|███████▎  | 6503/8920 [1:45:18<32:52,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Megan_Fox.jpg

 73%|███████▎  | 6504/8920 [1:45:19<28:56,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Craig_David.jpg

 73%|███████▎  | 6505/8920 [1:45:20<29:56,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Madden.jpg

 73%|███████▎  | 6506/8920 [1:45:20<24:37,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_Heard.jpg

 73%|███████▎  | 6507/8920 [1:45:21<36:03,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Palmer_Luckey.jpg

 73%|███████▎  | 6508/8920 [1:45:22<28:37,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashley_Olsen.jpg

 73%|███████▎  | 6509/8920 [1:45:22<22:50,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lana_Del_Rey.jpg

 73%|███████▎  | 6510/8920 [1:45:22<19:30,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jodie_Comer.jpg

 73%|███████▎  | 6511/8920 [1:45:23<24:36,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Mara.jpg

 73%|███████▎  | 6512/8920 [1:45:24<21:45,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anya_Taylor-Joy.jpg

 73%|███████▎  | 6513/8920 [1:45:24<18:35,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Kane.jpg

 73%|███████▎  | 6514/8920 [1:45:24<16:02,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Groban.jpg

 73%|███████▎  | 6515/8920 [1:45:25<18:52,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Evans.jpg

 73%|███████▎  | 6516/8920 [1:45:25<19:15,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leelee_Sobieski.jpg

 73%|███████▎  | 6517/8920 [1:45:27<29:16,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_J._Adams.jpg

 73%|███████▎  | 6518/8920 [1:45:28<35:38,  1.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Van_Gerwen.jpg

 73%|███████▎  | 6519/8920 [1:45:29<41:08,  1.03s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duhan_Van_Der_Merwe.jpg

 73%|███████▎  | 6520/8920 [1:45:29<32:23,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Logan_Paul.jpg

 73%|███████▎  | 6521/8920 [1:45:31<42:34,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Felicity_Jones.jpg

 73%|███████▎  | 6522/8920 [1:45:31<32:34,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hope_Solo.jpg

 73%|███████▎  | 6523/8920 [1:45:32<25:34,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaya_Scodelario.jpg

 73%|███████▎  | 6524/8920 [1:45:32<20:49,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miranda_Cosgrove.jpg

 73%|███████▎  | 6525/8920 [1:45:32<18:01,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lily_Allen.jpg

 73%|███████▎  | 6526/8920 [1:45:33<27:52,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Alonso.jpg

 73%|███████▎  | 6527/8920 [1:45:34<28:12,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Stan.jpg

 73%|███████▎  | 6528/8920 [1:45:34<22:34,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zara_Phillips.jpg

 73%|███████▎  | 6529/8920 [1:45:35<28:31,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Pattinson.jpg

 73%|███████▎  | 6530/8920 [1:45:37<41:22,  1.04s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Draymond_Green.jpg

 73%|███████▎  | 6531/8920 [1:45:37<31:53,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Wayne.jpg

 73%|███████▎  | 6532/8920 [1:45:39<35:15,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Middleton.jpg

 73%|███████▎  | 6533/8920 [1:45:39<28:07,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seth_Rogen.jpg

 73%|███████▎  | 6534/8920 [1:45:39<23:17,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hasan_Minhaj.jpg

 73%|███████▎  | 6535/8920 [1:45:40<30:24,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margot_Robbie.jpg

 73%|███████▎  | 6536/8920 [1:45:42<37:21,  1.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Garfield.jpg

 73%|███████▎  | 6537/8920 [1:45:42<28:46,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Lawrence.jpg

 73%|███████▎  | 6538/8920 [1:45:43<29:31,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carrie_Underwood.jpg

 73%|███████▎  | 6539/8920 [1:45:43<23:39,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kendrick_Lamar.jpg

 73%|███████▎  | 6540/8920 [1:45:43<22:42,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lauren_Cohan.jpg

 73%|███████▎  | 6541/8920 [1:45:44<21:07,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mo_Farah.jpg

 73%|███████▎  | 6542/8920 [1:45:44<18:35,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dominic_Thiem.jpg

 73%|███████▎  | 6543/8920 [1:45:44<15:40,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Froome.jpg

 73%|███████▎  | 6544/8920 [1:45:45<15:12,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christina_Perri.jpg

 73%|███████▎  | 6545/8920 [1:45:45<17:57,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neymar.jpg

 73%|███████▎  | 6546/8920 [1:45:46<16:04,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luka_Modrić.jpg

 73%|███████▎  | 6547/8920 [1:45:46<14:04,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lewis_Hamilton.jpg

 73%|███████▎  | 6548/8920 [1:45:48<36:42,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Vettel.jpg

 73%|███████▎  | 6549/8920 [1:45:48<28:11,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashley_Tisdale.jpg

 73%|███████▎  | 6550/8920 [1:45:49<23:55,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agnieszka_Radwańska.jpg

 73%|███████▎  | 6551/8920 [1:45:49<23:59,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_O'Brien.jpg

 73%|███████▎  | 6552/8920 [1:45:50<20:35,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dakota_Johnson.jpg

 73%|███████▎  | 6553/8920 [1:45:50<17:39,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kirsten_Dunst.jpg

 73%|███████▎  | 6554/8920 [1:45:51<18:20,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Martín_Del_Potro.jpg

 73%|███████▎  | 6555/8920 [1:45:51<16:05,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shaun_White.jpg

 73%|███████▎  | 6556/8920 [1:45:51<16:43,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Portman.jpg

 74%|███████▎  | 6557/8920 [1:45:52<18:02,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Durant.jpg

 74%|███████▎  | 6558/8920 [1:45:52<20:21,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mandy_Moore.jpg

 74%|███████▎  | 6559/8920 [1:45:53<17:11,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Hemsworth.jpg

 74%|███████▎  | 6560/8920 [1:45:53<19:04,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zendaya.jpg

 74%|███████▎  | 6561/8920 [1:45:54<27:30,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lea_Michele.jpg

 74%|███████▎  | 6562/8920 [1:45:55<26:30,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimin.jpg

 74%|███████▎  | 6563/8920 [1:45:55<21:52,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Radcliffe.jpg

 74%|███████▎  | 6564/8920 [1:45:56<27:40,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Priyanka_Chopra.jpg

 74%|███████▎  | 6565/8920 [1:45:57<22:19,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melanie_Martinez.jpg

 74%|███████▎  | 6566/8920 [1:45:57<24:47,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Biel.jpg

 74%|███████▎  | 6567/8920 [1:45:58<24:06,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joss_Stone.jpg

 74%|███████▎  | 6568/8920 [1:45:58<20:10,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Ovechkin.jpg

 74%|███████▎  | 6569/8920 [1:45:59<20:28,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macklemore.jpg

 74%|███████▎  | 6570/8920 [1:45:59<17:19,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rafael_Nadal.jpg

 74%|███████▎  | 6571/8920 [1:45:59<14:48,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Misty_Copeland.jpg

 74%|███████▎  | 6572/8920 [1:46:01<25:45,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nick_Jonas.jpg

 74%|███████▎  | 6573/8920 [1:46:01<20:41,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Glover.jpg

 74%|███████▎  | 6574/8920 [1:46:01<17:35,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephen_Curry.jpg

 74%|███████▎  | 6575/8920 [1:46:02<16:57,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lizzo.jpg

 74%|███████▎  | 6576/8920 [1:46:02<21:02,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruno_Mars.jpg

 74%|███████▎  | 6577/8920 [1:46:03<17:33,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T-Pain.jpg

 74%|███████▎  | 6578/8920 [1:46:03<15:20,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daisy_Ridley.jpg

 74%|███████▍  | 6579/8920 [1:46:03<15:48,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hilary_Duff.jpg

 74%|███████▍  | 6580/8920 [1:46:04<14:26,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kelly_Clarkson.jpg

 74%|███████▍  | 6581/8920 [1:46:04<14:35,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adele.jpg

 74%|███████▍  | 6582/8920 [1:46:04<13:39,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sviatlana_Tsikhanouskaya.jpg

 74%|███████▍  | 6583/8920 [1:46:05<13:07,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Breonna_Taylor.jpg

 74%|███████▍  | 6584/8920 [1:46:05<11:51,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demi_Lovato.jpg

 74%|███████▍  | 6585/8920 [1:46:07<29:23,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Holly_Valance.jpg

 74%|███████▍  | 6586/8920 [1:46:07<24:18,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leann_Rimes.jpg

 74%|███████▍  | 6587/8920 [1:46:07<19:44,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andy_Murray.jpg

 74%|███████▍  | 6588/8920 [1:46:07<17:01,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Usain_Bolt.jpg

 74%|███████▍  | 6589/8920 [1:46:08<21:23,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miranda_Kerr.jpg

 74%|███████▍  | 6590/8920 [1:46:08<18:08,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Harry.jpg

 74%|███████▍  | 6591/8920 [1:46:09<18:26,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jong-Un.jpg

 74%|███████▍  | 6592/8920 [1:46:09<16:58,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristen_Stewart.jpg

 74%|███████▍  | 6593/8920 [1:46:10<15:23,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Phelps.jpg

 74%|███████▍  | 6594/8920 [1:46:11<22:42,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brie_Larson.jpg

 74%|███████▍  | 6595/8920 [1:46:12<30:35,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Bieber.jpg

 74%|███████▍  | 6596/8920 [1:46:12<24:27,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Avril_Lavigne.jpg

 74%|███████▍  | 6597/8920 [1:46:12<19:47,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariana_Grande.jpg

 74%|███████▍  | 6598/8920 [1:46:13<16:56,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billie_Piper.jpg

 74%|███████▍  | 6599/8920 [1:46:13<15:53,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Novak_Đoković.jpg

 74%|███████▍  | 6600/8920 [1:46:14<21:31,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandria_Ocasio-Cortez.jpg

 74%|███████▍  | 6601/8920 [1:46:15<30:02,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennifer_Hudson.jpg

 74%|███████▍  | 6602/8920 [1:46:16<24:18,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gal_Gadot.jpg

 74%|███████▍  | 6603/8920 [1:46:16<19:44,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karolína_Kurková.jpg

 74%|███████▍  | 6604/8920 [1:46:16<16:32,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Mahomes.jpg

 74%|███████▍  | 6605/8920 [1:46:17<25:27,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Watson.jpg

 74%|███████▍  | 6606/8920 [1:46:18<21:30,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Winehouse.jpg

 74%|███████▍  | 6607/8920 [1:46:18<18:25,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ed_Sheeran.jpg

 74%|███████▍  | 6608/8920 [1:46:19<29:42,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Zuckerberg.jpg

 74%|███████▍  | 6609/8920 [1:46:21<37:53,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lionel_Messi.jpg

 74%|███████▍  | 6610/8920 [1:46:21<33:19,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Serena_Williams.jpg

 74%|███████▍  | 6611/8920 [1:46:22<29:28,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caroline_Shaw.jpg

 74%|███████▍  | 6612/8920 [1:46:22<23:14,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beyoncé.jpg

 74%|███████▍  | 6613/8920 [1:46:22<18:39,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rihanna.jpg

 74%|███████▍  | 6614/8920 [1:46:23<16:12,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dua_Lipa.jpg

 74%|███████▍  | 6615/8920 [1:46:23<15:44,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meghan_Markle.jpg

 74%|███████▍  | 6616/8920 [1:46:23<14:11,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roger_Federer.jpg

 74%|███████▍  | 6618/8920 [1:46:24<15:12,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Carlos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jude_Bellingham.jpg

 74%|███████▍  | 6619/8920 [1:46:24<12:35,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nba_Youngboy.jpg

 74%|███████▍  | 6620/8920 [1:46:25<14:56,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashley_Jensen.jpg

 74%|███████▍  | 6622/8920 [1:46:25<10:58,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_O'Dowd.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejandro_Nones.jpg

 74%|███████▍  | 6623/8920 [1:46:25<10:08,  3.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suela.Ez.jpg

 74%|███████▍  | 6624/8920 [1:46:26<09:57,  3.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentijn_Dijkman.jpg

 74%|███████▍  | 6625/8920 [1:46:28<36:35,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aquamarin.jpg

 74%|███████▍  | 6626/8920 [1:46:29<28:26,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Verena_Michelitsch.jpg

 74%|███████▍  | 6627/8920 [1:46:29<25:17,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tina_Neumann.jpg

 74%|███████▍  | 6628/8920 [1:46:30<23:53,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Walter_Hahn.jpg

 74%|███████▍  | 6630/8920 [1:46:30<19:20,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanessa_Zinner.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romy_Schneider_(1938-1982).jpg

 74%|███████▍  | 6632/8920 [1:46:31<16:02,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrejs_Mihelsons.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michigun_(1996-2021).jpg

 74%|███████▍  | 6633/8920 [1:46:31<13:32,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lingualizer.jpg

 74%|███████▍  | 6634/8920 [1:46:33<23:37,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadine_Leopold.jpg

 74%|███████▍  | 6635/8920 [1:46:33<21:36,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Marie_Schiffner.jpg

 74%|███████▍  | 6636/8920 [1:46:34<21:08,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Little_Sky.jpg

 74%|███████▍  | 6637/8920 [1:46:34<17:11,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natascha_Kampusch.jpg

 74%|███████▍  | 6639/8920 [1:46:34<13:55,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fabio_Wibmer.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Evita.jpg

 74%|███████▍  | 6640/8920 [1:46:35<11:32,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miep_Gies_(1909-2010).jpg

 74%|███████▍  | 6641/8920 [1:46:35<12:22,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conchita_Wurst.jpg

 74%|███████▍  | 6643/8920 [1:46:36<12:18,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rene_Wurz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erand_Arifi.jpg

 74%|███████▍  | 6644/8920 [1:46:36<13:52,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lydia_Campanelli.jpg

 74%|███████▍  | 6645/8920 [1:46:37<14:29,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wersow.jpg

 75%|███████▍  | 6647/8920 [1:46:38<21:18,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florian_Macek.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Stadler.jpg

 75%|███████▍  | 6648/8920 [1:46:39<21:08,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toby_Woess.jpg

 75%|███████▍  | 6649/8920 [1:46:39<17:05,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Alaba.jpg

 75%|███████▍  | 6650/8920 [1:46:39<17:09,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paula_Wolf.jpg

 75%|███████▍  | 6651/8920 [1:46:40<17:47,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Felix_Baumgartner_(1969-2025).jpg

 75%|███████▍  | 6653/8920 [1:46:41<16:46,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doina_Barbaneagra.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elisabeth_Fritzl.jpg

 75%|███████▍  | 6654/8920 [1:46:42<22:39,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johannes_Bartl.jpg

 75%|███████▍  | 6655/8920 [1:46:42<18:09,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niki_Lauda_(1949-2019).jpg

 75%|███████▍  | 6656/8920 [1:46:42<16:30,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hedy_Lamarr_(1914-2000).jpg

 75%|███████▍  | 6657/8920 [1:46:43<13:50,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franz_Ferdinand_(1863-1914).jpg

 75%|███████▍  | 6659/8920 [1:46:43<13:56,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tynna.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christoph_Waltz.jpg

 75%|███████▍  | 6661/8920 [1:46:44<14:30,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boris_Kodjoe.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Growingannanas.jpg

 75%|███████▍  | 6663/8920 [1:46:45<13:17,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toto_Wolff.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Radal.jpg

 75%|███████▍  | 6664/8920 [1:46:46<16:20,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johannes_Pietsch.jpg

 75%|███████▍  | 6666/8920 [1:46:46<14:30,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faze_Blaze.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manuel_Enrique.jpg

 75%|███████▍  | 6667/8920 [1:46:47<12:11,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wolfgang_Amadeus_Mozart_(1756-1791).jpg

 75%|███████▍  | 6668/8920 [1:46:47<10:55,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marie_Antoinette_(1755-1793).jpg

 75%|███████▍  | 6670/8920 [1:46:47<09:15,  4.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Candy_Ken.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arnold_Schwarzenegger.jpg

 75%|███████▍  | 6671/8920 [1:46:49<24:04,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Briggitte_Bozzo.jpg

 75%|███████▍  | 6672/8920 [1:46:49<19:32,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ani_Cat.jpg

 75%|███████▍  | 6673/8920 [1:46:49<16:02,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Santiago_Armando.jpg

 75%|███████▍  | 6674/8920 [1:46:50<16:51,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenny_Devil.jpg

 75%|███████▍  | 6675/8920 [1:46:50<17:33,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barbara_Ramirez.jpg

 75%|███████▍  | 6676/8920 [1:46:51<18:00,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natasha_Domínguez.jpg

 75%|███████▍  | 6677/8920 [1:46:51<15:07,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Le_Jac.jpg

 75%|███████▍  | 6679/8920 [1:46:52<18:51,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabrina_Seara.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariale_Marrero.jpg

 75%|███████▍  | 6680/8920 [1:46:53<20:13,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Cuadros_Salek.jpg

 75%|███████▍  | 6682/8920 [1:46:54<15:48,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gaby_Espino.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patricia_Velásquez.jpg

 75%|███████▍  | 6684/8920 [1:46:54<11:02,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marjorie_De_Sousa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omaya_Zein.jpg

 75%|███████▍  | 6685/8920 [1:46:54<09:57,  3.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Estrada.jpg

 75%|███████▍  | 6686/8920 [1:46:55<10:34,  3.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rafael_De_La_Fuente.jpg

 75%|███████▍  | 6688/8920 [1:46:55<11:56,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Santiago_Cabrera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Briella.jpg

 75%|███████▍  | 6689/8920 [1:46:56<10:40,  3.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Villarroel_Gamero.jpg

 75%|███████▌  | 6690/8920 [1:46:56<10:28,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicolás_Maduro.jpg

 75%|███████▌  | 6692/8920 [1:46:56<08:45,  4.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nando.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evaluna_Montaner.jpg

 75%|███████▌  | 6693/8920 [1:46:57<11:19,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/María_Gabriela_De_Faría.jpg

 75%|███████▌  | 6694/8920 [1:46:57<10:26,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Rossell.jpg

 75%|███████▌  | 6695/8920 [1:46:58<15:27,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabella_Ladera.jpg

 75%|███████▌  | 6696/8920 [1:46:58<13:04,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cinthya_Carmona.jpg

 75%|███████▌  | 6697/8920 [1:46:58<11:25,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicole_García.jpg

 75%|███████▌  | 6698/8920 [1:46:59<20:28,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kimberly_Dos_Ramos.jpg

 75%|███████▌  | 6699/8920 [1:46:59<16:36,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesús_Montero_(1989-2025).jpg

 75%|███████▌  | 6700/8920 [1:47:00<16:56,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronald_Acuna_Jr..jpg

 75%|███████▌  | 6701/8920 [1:47:00<18:17,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniela_Nieves.jpg

 75%|███████▌  | 6703/8920 [1:47:01<12:19,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shadow.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/María_Gracia_Sosa.jpg

 75%|███████▌  | 6705/8920 [1:47:01<09:44,  3.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Altuve.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karen_Hauer.jpg

 75%|███████▌  | 6706/8920 [1:47:01<09:09,  4.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Édgar_Ramírez.jpg

 75%|███████▌  | 6707/8920 [1:47:02<12:58,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leyla_Star.jpg

 75%|███████▌  | 6709/8920 [1:47:02<09:52,  3.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arca.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Futcrunch.jpg

 75%|███████▌  | 6710/8920 [1:47:03<09:03,  4.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Schor.jpg

 75%|███████▌  | 6712/8920 [1:47:04<12:59,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yolo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Panda_Aventurero.jpg

 75%|███████▌  | 6713/8920 [1:47:04<11:22,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lilimar.jpg

 75%|███████▌  | 6714/8920 [1:47:04<14:46,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mariana_Ávila.jpg

 75%|███████▌  | 6715/8920 [1:47:05<17:22,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Rudberg.jpg

 75%|███████▌  | 6716/8920 [1:47:06<17:37,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kimberly_Kim.jpg

 75%|███████▌  | 6717/8920 [1:47:06<18:42,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lele_Pons.jpg

 75%|███████▌  | 6718/8920 [1:47:06<15:37,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fiona_Shaw.jpg

 75%|███████▌  | 6719/8920 [1:47:07<17:16,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Call_Me_Kevin.jpg

 75%|███████▌  | 6721/8920 [1:47:08<15:48,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_D._Higgins.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sheamus.jpg

 75%|███████▌  | 6722/8920 [1:47:09<24:31,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicola_Coughlan.jpg

 75%|███████▌  | 6723/8920 [1:47:09<19:43,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Domhnall_Gleeson.jpg

 75%|███████▌  | 6724/8920 [1:47:10<16:22,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lilah_Marie.jpg

 75%|███████▌  | 6725/8920 [1:47:10<19:57,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hercules_Mulligan_(1740-1825).jpg

 75%|███████▌  | 6726/8920 [1:47:11<17:30,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Godfrey.jpg

 75%|███████▌  | 6727/8920 [1:47:11<17:44,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrew_Scott.jpg

 75%|███████▌  | 6728/8920 [1:47:11<14:38,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Harris_(1930-2002).jpg

 75%|███████▌  | 6729/8920 [1:47:12<12:35,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Kelly.jpg

 75%|███████▌  | 6730/8920 [1:47:12<11:28,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Neill.jpg

 75%|███████▌  | 6732/8920 [1:47:13<12:43,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grandad_Frank.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Simpson.jpg

 75%|███████▌  | 6733/8920 [1:47:13<11:19,  3.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_O'Donoghue.jpg

 75%|███████▌  | 6734/8920 [1:47:14<18:12,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Terroriser.jpg

 76%|███████▌  | 6736/8920 [1:47:14<12:15,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Gambon_(1940-2023).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bono.jpg

 76%|███████▌  | 6737/8920 [1:47:15<22:27,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xiaoleung.jpg

 76%|███████▌  | 6738/8920 [1:47:16<18:09,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maura_Higgins.jpg

 76%|███████▌  | 6739/8920 [1:47:17<25:56,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Mcgrath.jpg

 76%|███████▌  | 6740/8920 [1:47:17<20:40,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elijah_Hewson.jpg

 76%|███████▌  | 6741/8920 [1:47:17<16:49,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aoife_O'Farrell.jpg

 76%|███████▌  | 6743/8920 [1:47:18<12:00,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Sheehan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justaminx.jpg

 76%|███████▌  | 6744/8920 [1:47:19<21:54,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierce_Brosnan.jpg

 76%|███████▌  | 6745/8920 [1:47:20<28:44,  1.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Little_Kelly.jpg

 76%|███████▌  | 6746/8920 [1:47:21<25:12,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Colin_Farrell.jpg

 76%|███████▌  | 6747/8920 [1:47:21<20:02,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daithi_De_Nogla.jpg

 76%|███████▌  | 6749/8920 [1:47:21<14:11,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_Adeyinka.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Mescal.jpg

 76%|███████▌  | 6750/8920 [1:47:22<16:50,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Evanna_Lynch.jpg

 76%|███████▌  | 6751/8920 [1:47:23<25:58,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Molly_Mccann_(Actress).jpg

 76%|███████▌  | 6752/8920 [1:47:24<29:32,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Finn_Bálor.jpg

 76%|███████▌  | 6754/8920 [1:47:25<18:40,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amybeth_Mcnulty.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hozier.jpg

 76%|███████▌  | 6755/8920 [1:47:25<15:23,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Barry_Keoghan.jpg

 76%|███████▌  | 6756/8920 [1:47:25<13:52,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Becky_Lynch.jpg

 76%|███████▌  | 6757/8920 [1:47:26<12:22,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cillian_Murphy.jpg

 76%|███████▌  | 6758/8920 [1:47:26<14:06,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conor_Mcgregor.jpg

 76%|███████▌  | 6759/8920 [1:47:26<12:41,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edie_Saccone-Joly.jpg

 76%|███████▌  | 6760/8920 [1:47:27<11:08,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alisha_Weir.jpg

 76%|███████▌  | 6761/8920 [1:47:27<14:24,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Saccone-Joly.jpg

 76%|███████▌  | 6762/8920 [1:47:27<12:28,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacksepticeye.jpg

 76%|███████▌  | 6764/8920 [1:47:28<10:04,  3.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emilia_Saccone-Joly.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niall_Horan.jpg

 76%|███████▌  | 6765/8920 [1:47:28<09:21,  3.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Cosmo.jpg

 76%|███████▌  | 6766/8920 [1:47:29<13:41,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christina_Smith_(1809-1893).jpg

 76%|███████▌  | 6767/8920 [1:47:30<27:10,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Hannah.jpg

 76%|███████▌  | 6768/8920 [1:47:31<21:55,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Mullan.jpg

 76%|███████▌  | 6769/8920 [1:47:31<22:21,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Valentine.jpg

 76%|███████▌  | 6770/8920 [1:47:32<26:38,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dougray_Scott.jpg

 76%|███████▌  | 6771/8920 [1:47:33<23:44,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyn-Z.jpg

 76%|███████▌  | 6772/8920 [1:47:34<27:16,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angus_Young.jpg

 76%|███████▌  | 6773/8920 [1:47:34<21:15,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Biggerstaff.jpg

 76%|███████▌  | 6774/8920 [1:47:34<18:46,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylorxhx.jpg

 76%|███████▌  | 6775/8920 [1:47:36<27:15,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Ferguson.jpg

 76%|███████▌  | 6776/8920 [1:47:37<32:53,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Susan_Boyle.jpg

 76%|███████▌  | 6778/8920 [1:47:38<21:58,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shirley_Henderson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sword4000.jpg

 76%|███████▌  | 6779/8920 [1:47:38<18:11,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Craig_Ferguson.jpg

 76%|███████▌  | 6781/8920 [1:47:38<12:11,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bald_Martin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophie_Xeon_(1986-2021).jpg

 76%|███████▌  | 6782/8920 [1:47:40<22:32,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Evans.jpg

 76%|███████▌  | 6783/8920 [1:47:40<18:00,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Thomas.jpg

 76%|███████▌  | 6784/8920 [1:47:40<15:28,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ross_King.jpg

 76%|███████▌  | 6786/8920 [1:47:41<11:23,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drew_Mcintyre.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katie_Leung.jpg

 76%|███████▌  | 6787/8920 [1:47:42<20:46,  1.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Carlyle.jpg

 76%|███████▌  | 6788/8920 [1:47:42<17:35,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_Cox.jpg

 76%|███████▌  | 6789/8920 [1:47:42<15:37,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Margaret_(1930-2002).jpg

 76%|███████▌  | 6790/8920 [1:47:43<16:34,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Connor_Ball.jpg

 76%|███████▌  | 6791/8920 [1:47:43<14:27,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Cumming.jpg

 76%|███████▌  | 6792/8920 [1:47:43<12:28,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Connery_(1930-2020).jpg

 76%|███████▌  | 6793/8920 [1:47:44<11:38,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Queen_Of_Scots_(1542-1587).jpg

 76%|███████▌  | 6794/8920 [1:47:44<15:03,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Icycaress.jpg

 76%|███████▌  | 6795/8920 [1:47:45<23:30,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Capaldi.jpg

 76%|███████▌  | 6796/8920 [1:47:47<32:51,  1.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Mckidd.jpg

 76%|███████▌  | 6797/8920 [1:47:47<25:08,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Itsjustnicholas.jpg

 76%|███████▌  | 6798/8920 [1:47:48<29:15,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Madden.jpg

 76%|███████▌  | 6799/8920 [1:47:49<26:33,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Paul_Jones_(1747-1792).jpg

 76%|███████▌  | 6800/8920 [1:47:49<21:55,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robbie_Coltrane_(1950-2022).jpg

 76%|███████▌  | 6801/8920 [1:47:50<21:14,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Mcavoy.jpg

 76%|███████▋  | 6802/8920 [1:47:51<22:58,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ewan_Mcgregor.jpg

 76%|███████▋  | 6803/8920 [1:47:51<25:50,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karen_Gillan.jpg

 76%|███████▋  | 6804/8920 [1:47:53<29:59,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gerard_Butler.jpg

 76%|███████▋  | 6805/8920 [1:47:54<34:23,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dangthatsalongname.jpg

 76%|███████▋  | 6806/8920 [1:47:55<37:19,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Calvin_Harris.jpg

 76%|███████▋  | 6807/8920 [1:47:55<28:39,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Tennant.jpg

 76%|███████▋  | 6808/8920 [1:47:56<29:48,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Doherty.jpg

 76%|███████▋  | 6809/8920 [1:47:57<27:37,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jasmine_Chiswell.jpg

 76%|███████▋  | 6811/8920 [1:47:58<19:57,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lewis_Capaldi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gordon_Ramsay.jpg

 76%|███████▋  | 6812/8920 [1:47:58<16:28,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steak.jpg

 76%|███████▋  | 6814/8920 [1:47:59<14:17,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brent_Rivera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Reynolds.jpg

 76%|███████▋  | 6816/8920 [1:47:59<10:06,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cardi_B.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diezel_Ortiz.jpg

 76%|███████▋  | 6818/8920 [1:47:59<08:24,  4.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcusonthelow.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jojo_Siwa.jpg

 76%|███████▋  | 6819/8920 [1:48:00<08:06,  4.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/2Xrakai.jpg

 76%|███████▋  | 6821/8920 [1:48:00<10:07,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kylie_Jenner.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cesar_Mendoza.jpg

 76%|███████▋  | 6822/8920 [1:48:01<09:14,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caylus.jpg

 76%|███████▋  | 6823/8920 [1:48:01<08:59,  3.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jules_Leblanc.jpg

 77%|███████▋  | 6824/8920 [1:48:02<19:00,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenna_Ortega.jpg

 77%|███████▋  | 6825/8920 [1:48:03<18:45,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Addison_Rae.jpg

 77%|███████▋  | 6827/8920 [1:48:03<12:54,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rebecca_Zamolo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lexi_Rivera.jpg

 77%|███████▋  | 6828/8920 [1:48:03<11:45,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paultooreall.jpg

 77%|███████▋  | 6829/8920 [1:48:04<14:37,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiji_Wonder.jpg

 77%|███████▋  | 6830/8920 [1:48:04<12:54,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Jackson_(1958-2009).jpg

 77%|███████▋  | 6831/8920 [1:48:05<21:28,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooke_Monk.jpg

 77%|███████▋  | 6832/8920 [1:48:06<20:12,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donald_Trump.jpg

 77%|███████▋  | 6833/8920 [1:48:06<18:47,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Rodrigo.jpg

 77%|███████▋  | 6835/8920 [1:48:07<12:32,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Preslee_Grace_Nelson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlie_Kirk_(1993-2025).jpg

 77%|███████▋  | 6837/8920 [1:48:07<09:00,  3.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lei_Lei.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kai_Cenat.jpg

 77%|███████▋  | 6838/8920 [1:48:07<08:32,  4.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ishowspeed.jpg

 77%|███████▋  | 6839/8920 [1:48:07<08:32,  4.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabrina_Carpenter.jpg

 77%|███████▋  | 6840/8920 [1:48:08<10:31,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Billie_Eilish.jpg

 77%|███████▋  | 6841/8920 [1:48:09<16:14,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harper_Zilmer.jpg

 77%|███████▋  | 6842/8920 [1:48:09<17:42,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paislee_Jaine_Nelson.jpg

 77%|███████▋  | 6844/8920 [1:48:11<22:23,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mrbeast.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariana_Grande.jpg

 77%|███████▋  | 6845/8920 [1:48:11<18:09,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charli_D'Amelio.jpg

 77%|███████▋  | 6847/8920 [1:48:12<12:09,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Piper_Rockelle.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackson_Harvey.jpg

 77%|███████▋  | 6848/8920 [1:48:12<10:16,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooks_Harvey.jpg

 77%|███████▋  | 6850/8920 [1:48:13<09:35,  3.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nidal_Wonder.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Preslee_Faith.jpg

 77%|███████▋  | 6851/8920 [1:48:14<21:20,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Txunamy.jpg

 77%|███████▋  | 6852/8920 [1:48:14<17:25,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylor_Swift.jpg

 77%|███████▋  | 6853/8920 [1:48:14<14:29,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Embreigh_Courtlyn.jpg

 77%|███████▋  | 6854/8920 [1:48:15<13:02,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaido_Lee_Roberts.jpg

 77%|███████▋  | 6856/8920 [1:48:15<09:53,  3.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malachi_Barton.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Matter.jpg

 77%|███████▋  | 6857/8920 [1:48:15<08:58,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zuza_Beine_(2011-2025).jpg

 77%|███████▋  | 6858/8920 [1:48:16<12:37,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salish_Matter.jpg

 77%|███████▋  | 6859/8920 [1:48:16<12:22,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chunkz.jpg

 77%|███████▋  | 6861/8920 [1:48:17<09:48,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Charlotte_Of_Wales.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arthur_Frederick.jpg

 77%|███████▋  | 6863/8920 [1:48:17<07:43,  4.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Russell.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lewis_Hamilton.jpg

 77%|███████▋  | 6864/8920 [1:48:17<07:30,  4.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niko_Omilana.jpg

 77%|███████▋  | 6865/8920 [1:48:17<07:27,  4.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jakeydavies.jpg

 77%|███████▋  | 6866/8920 [1:48:18<11:29,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiana_Wilson.jpg

 77%|███████▋  | 6867/8920 [1:48:19<21:19,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/21_Savage.jpg

 77%|███████▋  | 6869/8920 [1:48:20<17:28,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ldshadowlady.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Italianbach.jpg

 77%|███████▋  | 6871/8920 [1:48:21<11:45,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/King_Charles_Iii.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Howell.jpg

 77%|███████▋  | 6873/8920 [1:48:21<09:12,  3.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Pattinson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angryginge13.jpg

 77%|███████▋  | 6875/8920 [1:48:21<07:58,  4.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Speed_Mcqueen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yungblud.jpg

 77%|███████▋  | 6876/8920 [1:48:22<07:38,  4.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgenotfound.jpg

 77%|███████▋  | 6878/8920 [1:48:22<07:32,  4.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Clarke.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morgz.jpg

 77%|███████▋  | 6879/8920 [1:48:22<07:20,  4.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lando_Norris.jpg

 77%|███████▋  | 6880/8920 [1:48:24<17:57,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Partridge.jpg

 77%|███████▋  | 6881/8920 [1:48:25<25:27,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charli_Xcx.jpg

 77%|███████▋  | 6883/8920 [1:48:25<16:05,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommyinnit.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Diana_(1961-1997).jpg

 77%|███████▋  | 6884/8920 [1:48:25<13:20,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Central_Cee.jpg

 77%|███████▋  | 6885/8920 [1:48:26<11:48,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Tomlinson.jpg

 77%|███████▋  | 6887/8920 [1:48:26<11:48,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dantdm.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Grace_Brownlee.jpg

 77%|███████▋  | 6889/8920 [1:48:27<11:01,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chrismd.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Felton.jpg

 77%|███████▋  | 6890/8920 [1:48:27<09:44,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Radcliffe.jpg

 77%|███████▋  | 6891/8920 [1:48:29<19:00,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Cowell.jpg

 77%|███████▋  | 6892/8920 [1:48:30<29:51,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adele.jpg

 77%|███████▋  | 6893/8920 [1:48:30<22:59,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dua_Lipa.jpg

 77%|███████▋  | 6894/8920 [1:48:31<18:47,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ozzy_Osbourne_(1948-2025).jpg

 77%|███████▋  | 6895/8920 [1:48:31<15:40,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rowan_Atkinson.jpg

 77%|███████▋  | 6896/8920 [1:48:31<15:01,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zayn_Malik.jpg

 77%|███████▋  | 6897/8920 [1:48:33<23:38,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Owen_Cooper.jpg

 77%|███████▋  | 6898/8920 [1:48:33<20:00,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ed_Sheeran.jpg

 77%|███████▋  | 6899/8920 [1:48:34<20:30,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ksi.jpg

 77%|███████▋  | 6900/8920 [1:48:34<16:35,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Ii_(1926-2022).jpg

 77%|███████▋  | 6902/8920 [1:48:34<13:25,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Styles.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Payne_(1993-2024).jpg

 77%|███████▋  | 6903/8920 [1:48:35<12:37,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sssniperwolf.jpg

 77%|███████▋  | 6904/8920 [1:48:35<11:32,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Holland.jpg

 77%|███████▋  | 6906/8920 [1:48:35<09:02,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freya_Skye.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mavie_Da_Silva_Santos.jpg

 77%|███████▋  | 6907/8920 [1:48:36<08:57,  3.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morena_Baccarin.jpg

 77%|███████▋  | 6908/8920 [1:48:36<11:09,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Contieri.jpg

 77%|███████▋  | 6910/8920 [1:48:37<12:55,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Araujo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruna_Marquezine.jpg

 77%|███████▋  | 6911/8920 [1:48:37<11:17,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liz_Macedo.jpg

 77%|███████▋  | 6912/8920 [1:48:38<13:04,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xuxa.jpg

 78%|███████▊  | 6913/8920 [1:48:39<14:49,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luara_Fonseca.jpg

 78%|███████▊  | 6914/8920 [1:48:39<15:39,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martijn_Bk.jpg

 78%|███████▊  | 6916/8920 [1:48:40<11:45,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faze_Temperrr.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Mapeli.jpg

 78%|███████▊  | 6917/8920 [1:48:40<10:38,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larissa_Manoela.jpg

 78%|███████▊  | 6918/8920 [1:48:40<14:24,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giana_Mello.jpg

 78%|███████▊  | 6920/8920 [1:48:41<10:14,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giovanna_Ramos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Bortoleto.jpg

 78%|███████▊  | 6922/8920 [1:48:41<08:05,  4.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brenda_Esperança.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hulk.jpg

 78%|███████▊  | 6923/8920 [1:48:42<11:51,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erik_Porto.jpg

 78%|███████▊  | 6924/8920 [1:48:42<10:43,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coracy_Arantes_(1942-2025).jpg

 78%|███████▊  | 6926/8920 [1:48:43<10:22,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Pereira.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bak.jpg

 78%|███████▊  | 6927/8920 [1:48:45<30:01,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariane_Torres.jpg

 78%|███████▊  | 6928/8920 [1:48:45<23:14,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayrton_Senna_(1960-1994).jpg

 78%|███████▊  | 6929/8920 [1:48:45<18:31,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaká.jpg

 78%|███████▊  | 6930/8920 [1:48:46<18:00,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joana_Ceddia.jpg

 78%|███████▊  | 6931/8920 [1:48:47<23:12,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saiko.jpg

 78%|███████▊  | 6932/8920 [1:48:48<20:47,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raphinha.jpg

 78%|███████▊  | 6934/8920 [1:48:48<13:36,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomas_Kuc.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitoria_Bueno.jpg

 78%|███████▊  | 6935/8920 [1:48:49<22:27,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anitta.jpg

 78%|███████▊  | 6936/8920 [1:48:50<20:35,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Oliveira.jpg

 78%|███████▊  | 6938/8920 [1:48:51<16:09,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Igor_Ten.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessandra_Ambrósio.jpg

 78%|███████▊  | 6939/8920 [1:48:51<15:38,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mychaelade.jpg

 78%|███████▊  | 6940/8920 [1:48:51<12:57,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vinícius_Júnior.jpg

 78%|███████▊  | 6942/8920 [1:48:52<11:48,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nottrebeca.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Francisco_Lachowski.jpg

 78%|███████▊  | 6943/8920 [1:48:52<09:52,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronaldinho.jpg

 78%|███████▊  | 6945/8920 [1:48:52<08:15,  3.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gisele_Bündchen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriela_Moura.jpg

 78%|███████▊  | 6946/8920 [1:48:53<08:21,  3.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pelé_(1940-2022).jpg

 78%|███████▊  | 6947/8920 [1:48:53<12:26,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benji_Krol.jpg

 78%|███████▊  | 6949/8920 [1:48:54<12:06,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camilla_Araujo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zach_Clayton.jpg

 78%|███████▊  | 6950/8920 [1:48:54<10:33,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neymar.jpg

 78%|███████▊  | 6951/8920 [1:48:55<09:41,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adriana_Lima.jpg

 78%|███████▊  | 6952/8920 [1:48:55<14:13,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tota_Mc.jpg

 78%|███████▊  | 6953/8920 [1:48:56<12:21,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hackypixelz.jpg

 78%|███████▊  | 6954/8920 [1:48:56<14:48,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shira_Haas.jpg

 78%|███████▊  | 6956/8920 [1:48:57<13:30,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Parham_Rownaghi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greg_Davies.jpg

 78%|███████▊  | 6958/8920 [1:48:57<09:37,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thảo_Linhh.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Signe_Hansen.jpg

 78%|███████▊  | 6960/8920 [1:48:58<09:56,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathan_Vandergunst.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pilou_Asbaek.jpg

 78%|███████▊  | 6961/8920 [1:48:58<08:53,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elias_Hole.jpg

 78%|███████▊  | 6963/8920 [1:48:59<08:53,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolaj_Lie_Kaas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laila_Hasanovic.jpg

 78%|███████▊  | 6964/8920 [1:49:00<19:21,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mika_Valentin_Lin_Schultz.jpg

 78%|███████▊  | 6965/8920 [1:49:00<15:42,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queen_Margrethe_Ii.jpg

 78%|███████▊  | 6966/8920 [1:49:01<13:00,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hans_Christian_Andersen_(1805-1875).jpg

 78%|███████▊  | 6967/8920 [1:49:01<13:47,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Bodnia.jpg

 78%|███████▊  | 6968/8920 [1:49:01<11:46,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Count_Felix_Of_Monpezat.jpg

 78%|███████▊  | 6969/8920 [1:49:02<13:37,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morten_Lund.jpg

 78%|███████▊  | 6970/8920 [1:49:03<21:50,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rasmus_Højlund.jpg

 78%|███████▊  | 6972/8920 [1:49:04<15:16,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Jensen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariyan_Akaltun.jpg

 78%|███████▊  | 6973/8920 [1:49:05<22:38,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emilie_Ullerup.jpg

 78%|███████▊  | 6974/8920 [1:49:05<20:26,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Josephine.jpg

 78%|███████▊  | 6975/8920 [1:49:06<16:47,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Crown_Prince_Christian.jpg

 78%|███████▊  | 6977/8920 [1:49:07<20:04,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mø.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Levi_Skyum.jpg

 78%|███████▊  | 6979/8920 [1:49:08<13:10,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thea_Kornum.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Vincent.jpg

 78%|███████▊  | 6981/8920 [1:49:09<12:47,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Holtti.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magma.jpg

 78%|███████▊  | 6983/8920 [1:49:09<09:26,  3.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josefine_Simone.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josephine_Skriver.jpg

 78%|███████▊  | 6985/8920 [1:49:09<07:52,  4.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amalie_Star.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niki_Topgaard.jpg

 78%|███████▊  | 6986/8920 [1:49:10<07:33,  4.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alma_Kopenhagen.jpg

 78%|███████▊  | 6988/8920 [1:49:10<06:54,  4.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rasmus_Søndergaard.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikolaj_Coster-Waldau.jpg

 78%|███████▊  | 6989/8920 [1:49:11<10:02,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ulrich_Thomsen.jpg

 78%|███████▊  | 6990/8920 [1:49:11<12:08,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lukas_Forchhammer.jpg

 78%|███████▊  | 6991/8920 [1:49:11<11:00,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Husum.jpg

 78%|███████▊  | 6992/8920 [1:49:12<09:43,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Münster.jpg

 78%|███████▊  | 6993/8920 [1:49:13<19:15,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bille_August.jpg

 78%|███████▊  | 6994/8920 [1:49:13<15:39,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Connie_Nielsen.jpg

 78%|███████▊  | 6996/8920 [1:49:14<10:57,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Helena_Christensen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oscar_Rosenstroem.jpg

 78%|███████▊  | 6997/8920 [1:49:14<09:38,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabell_Afro.jpg

 78%|███████▊  | 6998/8920 [1:49:14<08:45,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Agdal.jpg

 78%|███████▊  | 7000/8920 [1:49:14<07:33,  4.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giancarlo_Esposito.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lars_Ulrich.jpg

 78%|███████▊  | 7001/8920 [1:49:15<09:57,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naja_Munster.jpg

 79%|███████▊  | 7003/8920 [1:49:15<09:17,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jasmin_Lind.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mira_Daisy.jpg

 79%|███████▊  | 7004/8920 [1:49:16<08:03,  3.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mads_Mikkelsen.jpg

 79%|███████▊  | 7005/8920 [1:49:16<11:54,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Crainer.jpg

 79%|███████▊  | 7006/8920 [1:49:16<10:16,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deepika_Padukone.jpg

 79%|███████▊  | 7007/8920 [1:49:17<13:17,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Ghost.jpg

 79%|███████▊  | 7009/8920 [1:49:18<10:01,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rapunzel_Asmr.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jérémy_Doku.jpg

 79%|███████▊  | 7010/8920 [1:49:18<11:42,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thibaut_Courtois.jpg

 79%|███████▊  | 7011/8920 [1:49:18<10:18,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masha_Bwi.jpg

 79%|███████▊  | 7013/8920 [1:49:19<10:46,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Elisabeth.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Rodriguez.jpg

 79%|███████▊  | 7014/8920 [1:49:19<09:15,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pommelien_Thijs.jpg

 79%|███████▊  | 7015/8920 [1:49:20<13:12,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cubehead.jpg

 79%|███████▊  | 7016/8920 [1:49:20<11:11,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stien_Edlund.jpg

 79%|███████▊  | 7017/8920 [1:49:21<13:31,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oussifooty.jpg

 79%|███████▊  | 7019/8920 [1:49:22<16:50,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gardianhasani.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vexx.jpg

 79%|███████▊  | 7020/8920 [1:49:23<22:56,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angele_Van_Laeken.jpg

 79%|███████▊  | 7022/8920 [1:49:24<16:51,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steffi_Mercie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonas_Bloquet.jpg

 79%|███████▊  | 7023/8920 [1:49:25<21:12,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Daniel.jpg

 79%|███████▊  | 7024/8920 [1:49:26<20:06,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Like_Mike.jpg

 79%|███████▉  | 7025/8920 [1:49:26<16:41,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hanne_Verbruggen.jpg

 79%|███████▉  | 7027/8920 [1:49:27<13:56,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hadise.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jul_Goossens.jpg

 79%|███████▉  | 7028/8920 [1:49:27<14:03,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Parker.jpg

 79%|███████▉  | 7029/8920 [1:49:28<15:27,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dystinct.jpg

 79%|███████▉  | 7031/8920 [1:49:28<10:31,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michiel_Callebaut.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Degryse.jpg

 79%|███████▉  | 7032/8920 [1:49:28<09:08,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthias_Schoenaerts.jpg

 79%|███████▉  | 7033/8920 [1:49:29<08:18,  3.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenza_Boutrif.jpg

 79%|███████▉  | 7035/8920 [1:49:29<07:11,  4.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romelu_Lukaku.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Senne_Jackson.jpg

 79%|███████▉  | 7036/8920 [1:49:29<07:11,  4.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ella_Kasumovic.jpg

 79%|███████▉  | 7037/8920 [1:49:30<10:24,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stromae.jpg

 79%|███████▉  | 7038/8920 [1:49:30<09:47,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Rouyre.jpg

 79%|███████▉  | 7039/8920 [1:49:30<08:52,  3.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jean-Claude_Van_Damme.jpg

 79%|███████▉  | 7040/8920 [1:49:30<08:11,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eden_Hazard.jpg

 79%|███████▉  | 7042/8920 [1:49:31<07:18,  4.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Galecki.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gotye.jpg

 79%|███████▉  | 7043/8920 [1:49:31<09:46,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_De_Bruyne.jpg

 79%|███████▉  | 7044/8920 [1:49:32<08:54,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stella_Maxwell.jpg

 79%|███████▉  | 7045/8920 [1:49:32<08:11,  3.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thewizardliz.jpg

 79%|███████▉  | 7046/8920 [1:49:32<09:25,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marius_De_Saeger.jpg

 79%|███████▉  | 7047/8920 [1:49:33<10:01,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nella_Rose.jpg

 79%|███████▉  | 7049/8920 [1:49:33<09:50,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nanou_Philips.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lou_Goossens.jpg

 79%|███████▉  | 7050/8920 [1:49:34<12:52,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Audrey_Hepburn_(1929-1993).jpg

 79%|███████▉  | 7052/8920 [1:49:35<12:18,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celine_Dept.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Dragun.jpg

 79%|███████▉  | 7053/8920 [1:49:35<14:02,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Verstappen.jpg

 79%|███████▉  | 7054/8920 [1:49:37<21:20,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kanishiima.jpg

 79%|███████▉  | 7055/8920 [1:49:37<20:46,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Nguyen.jpg

 79%|███████▉  | 7056/8920 [1:49:38<21:11,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hana_Dinh.jpg

 79%|███████▉  | 7057/8920 [1:49:38<16:51,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nino'S_Home.jpg

 79%|███████▉  | 7058/8920 [1:49:38<13:43,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vinh_Quang_Giang.jpg

 79%|███████▉  | 7060/8920 [1:49:39<09:34,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jake_Tran.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thgquoc.jpg

 79%|███████▉  | 7061/8920 [1:49:39<09:30,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eudrip.jpg

 79%|███████▉  | 7063/8920 [1:49:41<17:02,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oanh.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hanbin.jpg

 79%|███████▉  | 7064/8920 [1:49:41<16:54,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Onlyc.jpg

 79%|███████▉  | 7066/8920 [1:49:42<11:43,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thien_Lam.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bùi_Thảo_Ly.jpg

 79%|███████▉  | 7067/8920 [1:49:44<29:18,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/My_Nguyen.jpg

 79%|███████▉  | 7068/8920 [1:49:44<22:43,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oanh_Moon_Nguyen.jpg

 79%|███████▉  | 7069/8920 [1:49:46<27:03,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rhyder.jpg

 79%|███████▉  | 7070/8920 [1:49:46<23:17,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chanieme.jpg

 79%|███████▉  | 7071/8920 [1:49:46<18:46,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jenny_Huynh.jpg

 79%|███████▉  | 7072/8920 [1:49:46<15:02,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bich_Phuong.jpg

 79%|███████▉  | 7073/8920 [1:49:47<16:52,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Binbin9495.jpg

 79%|███████▉  | 7074/8920 [1:49:48<16:51,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viet_Tran.jpg

 79%|███████▉  | 7075/8920 [1:49:48<17:19,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anh_Do.jpg

 79%|███████▉  | 7076/8920 [1:49:48<13:58,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Van_Martarello.jpg

 79%|███████▉  | 7078/8920 [1:49:49<11:53,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ho_Chi_Minh_(1890-1969).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jade_Cloud.jpg

 79%|███████▉  | 7079/8920 [1:49:49<10:55,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Đỗ_Duy_Nam.jpg

 79%|███████▉  | 7080/8920 [1:49:51<18:38,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Son_Tung_M-Tp.jpg

 79%|███████▉  | 7081/8920 [1:49:51<14:57,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Ly.jpg

 79%|███████▉  | 7083/8920 [1:49:52<12:27,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thuy_Trang_(1973-2001).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Byoru.jpg

 79%|███████▉  | 7085/8920 [1:49:52<12:20,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julie_Baochi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thien.jpg

 79%|███████▉  | 7086/8920 [1:49:53<10:17,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Lequang.jpg

 79%|███████▉  | 7088/8920 [1:49:53<08:06,  3.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Plastique_Tiara.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uyen_Ninh.jpg

 79%|███████▉  | 7089/8920 [1:49:53<07:41,  3.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huyen_Tran.jpg

 79%|███████▉  | 7090/8920 [1:49:54<11:38,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alissa_Nguyen.jpg

 80%|███████▉  | 7092/8920 [1:49:54<08:35,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Dang.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ke_Huy_Quan.jpg

 80%|███████▉  | 7093/8920 [1:49:56<17:01,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viettrap.jpg

 80%|███████▉  | 7094/8920 [1:49:56<18:09,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sanymaa.jpg

 80%|███████▉  | 7096/8920 [1:49:58<18:04,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lovely_Mimi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lana_Condor.jpg

 80%|███████▉  | 7097/8920 [1:49:59<27:45,  1.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loann_Kaji.jpg

 80%|███████▉  | 7098/8920 [1:50:00<29:27,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suni_Ha_Linh.jpg

 80%|███████▉  | 7099/8920 [1:50:01<27:13,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clara_Dao.jpg

 80%|███████▉  | 7100/8920 [1:50:02<29:35,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Giggs.jpg

 80%|███████▉  | 7101/8920 [1:50:02<22:37,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vy_Qwaint.jpg

 80%|███████▉  | 7103/8920 [1:50:05<29:17,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iwan_Rheon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hana_Martin.jpg

 80%|███████▉  | 7105/8920 [1:50:06<18:59,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Davies.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bonnie_Tyler.jpg

 80%|███████▉  | 7106/8920 [1:50:06<15:01,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matt_Ryan.jpg

 80%|███████▉  | 7107/8920 [1:50:06<12:49,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Vii_(1457-1509).jpg

 80%|███████▉  | 7108/8920 [1:50:08<20:28,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reuben_De_Maid.jpg

 80%|███████▉  | 7109/8920 [1:50:08<19:15,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elliot_Giles.jpg

 80%|███████▉  | 7110/8920 [1:50:11<36:06,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clickfortaz.jpg

 80%|███████▉  | 7111/8920 [1:50:11<27:12,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rob_Brydon.jpg

 80%|███████▉  | 7112/8920 [1:50:11<21:01,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruth_Jones.jpg

 80%|███████▉  | 7114/8920 [1:50:12<13:40,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Regan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dheanasaur.jpg

 80%|███████▉  | 7115/8920 [1:50:12<17:41,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Corys_World.jpg

 80%|███████▉  | 7116/8920 [1:50:13<16:51,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Matthew_Rhys.jpg

 80%|███████▉  | 7117/8920 [1:50:13<14:12,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ioan_Gruffudd.jpg

 80%|███████▉  | 7119/8920 [1:50:14<11:56,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Pryce.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chloe_May.jpg

 80%|███████▉  | 7120/8920 [1:50:14<10:29,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dawn_French.jpg

 80%|███████▉  | 7121/8920 [1:50:15<11:45,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Watkins.jpg

 80%|███████▉  | 7123/8920 [1:50:15<08:32,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timothy_Dalton.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlotte_Church.jpg

 80%|███████▉  | 7125/8920 [1:50:15<07:09,  4.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willow_Gait.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Dowden.jpg

 80%|███████▉  | 7126/8920 [1:50:16<07:25,  4.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cdawgva.jpg

 80%|███████▉  | 7128/8920 [1:50:17<09:56,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elan_Gwen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cam_Holmes.jpg

 80%|███████▉  | 7129/8920 [1:50:17<12:15,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anthony_Hopkins.jpg

 80%|███████▉  | 7130/8920 [1:50:17<10:31,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luke_Evans.jpg

 80%|███████▉  | 7131/8920 [1:50:18<09:24,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarah_New.jpg

 80%|███████▉  | 7132/8920 [1:50:18<10:46,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Sheen.jpg

 80%|███████▉  | 7133/8920 [1:50:19<15:19,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gareth_Bale.jpg

 80%|███████▉  | 7135/8920 [1:50:19<10:47,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ben_Phillips.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rhia_Official.jpg

 80%|████████  | 7136/8920 [1:50:20<09:00,  3.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Jones.jpg

 80%|████████  | 7137/8920 [1:50:20<08:08,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hope_Brett.jpg

 80%|████████  | 7138/8920 [1:50:20<11:09,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Ellis.jpg

 80%|████████  | 7139/8920 [1:50:21<10:24,  2.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aimsey.jpg

 80%|████████  | 7140/8920 [1:50:21<11:58,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bambinobecky.jpg

 80%|████████  | 7141/8920 [1:50:22<13:51,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leondre_Devries.jpg

 80%|████████  | 7142/8920 [1:50:22<14:31,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amber_Davies.jpg

 80%|████████  | 7143/8920 [1:50:23<12:44,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roald_Dahl_(1916-1990).jpg

 80%|████████  | 7144/8920 [1:50:23<13:22,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina.jpg

 80%|████████  | 7145/8920 [1:50:24<19:17,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Bale.jpg

 80%|████████  | 7146/8920 [1:50:25<15:19,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_Zeta-Jones.jpg

 80%|████████  | 7147/8920 [1:50:26<21:34,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liana_Jade_Brooker.jpg

 80%|████████  | 7148/8920 [1:50:26<20:03,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahlagha_Jaberi.jpg

 80%|████████  | 7149/8920 [1:50:27<17:41,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Nooshin.jpg

 80%|████████  | 7150/8920 [1:50:27<15:37,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masoud_Barzani.jpg

 80%|████████  | 7151/8920 [1:50:28<16:19,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hadi_Choopan.jpg

 80%|████████  | 7153/8920 [1:50:29<17:47,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arshia__Bk.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ebi.jpg

 80%|████████  | 7155/8920 [1:50:30<14:48,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayatollah_Khomeini_(1902-1989).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alishmas.jpg

 80%|████████  | 7156/8920 [1:50:31<14:59,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Homa_Mohammadi.jpg

 80%|████████  | 7157/8920 [1:50:31<14:31,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cassandra_Clare.jpg

 80%|████████  | 7159/8920 [1:50:32<10:37,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Googoosh.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tooji.jpg

 80%|████████  | 7161/8920 [1:50:32<07:40,  3.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arash_Labaf.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mo_Saffari.jpg

 80%|████████  | 7162/8920 [1:50:32<09:34,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Itzarya.jpg

 80%|████████  | 7163/8920 [1:50:33<09:56,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Negin_Ghalavand.jpg

 80%|████████  | 7164/8920 [1:50:33<08:46,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elika_Abdolrazzaghi.jpg

 80%|████████  | 7165/8920 [1:50:33<09:21,  3.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sally_Orlando.jpg

 80%|████████  | 7166/8920 [1:50:35<22:38,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sam_Asghari.jpg

 80%|████████  | 7167/8920 [1:50:35<18:02,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arat_Hosseini.jpg

 80%|████████  | 7168/8920 [1:50:36<19:21,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pey_95.jpg

 80%|████████  | 7170/8920 [1:50:37<12:30,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iron_Sheik_(1942-2023).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Younan_Nowzaradan.jpg

 80%|████████  | 7171/8920 [1:50:38<20:16,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mia_Plays.jpg

 80%|████████  | 7172/8920 [1:50:39<24:26,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sahar_Tabar.jpg

 80%|████████  | 7173/8920 [1:50:40<22:03,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alin_Sumarwata.jpg

 80%|████████  | 7174/8920 [1:50:40<19:54,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arian_Moayed.jpg

 80%|████████  | 7176/8920 [1:50:41<12:44,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Patrick_Bet-David.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shaun_Toub.jpg

 80%|████████  | 7177/8920 [1:50:41<11:14,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omid_Abtahi.jpg

 80%|████████  | 7178/8920 [1:50:41<09:40,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Khamenei.jpg

 80%|████████  | 7179/8920 [1:50:42<13:09,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dominic_Rains.jpg

 80%|████████  | 7180/8920 [1:50:42<13:50,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shohreh_Aghdashloo.jpg

 81%|████████  | 7181/8920 [1:50:43<11:38,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sevdaliza.jpg

 81%|████████  | 7182/8920 [1:50:43<11:46,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nina_Gray.jpg

 81%|████████  | 7183/8920 [1:50:44<18:40,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Golshifteh_Farahani.jpg

 81%|████████  | 7184/8920 [1:50:44<15:06,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tala_Ashe.jpg

 81%|████████  | 7186/8920 [1:50:45<10:16,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sijal.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Navid_Negahban.jpg

 81%|████████  | 7188/8920 [1:50:46<10:28,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nazanin_Boniadi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mir-Hossein_Mousavi.jpg

 81%|████████  | 7189/8920 [1:50:46<09:08,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boz_Mofid.jpg

 81%|████████  | 7190/8920 [1:50:46<08:46,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elay.jpg

 81%|████████  | 7192/8920 [1:50:48<13:28,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nasim_Pedrad.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mehdi_Sadaghdar.jpg

 81%|████████  | 7193/8920 [1:50:48<11:30,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mandana_Mani.jpg

 81%|████████  | 7194/8920 [1:50:50<26:47,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mehran_Rowshan.jpg

 81%|████████  | 7195/8920 [1:50:51<29:03,  1.01s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amit_Gofman_Levy.jpg

 81%|████████  | 7196/8920 [1:50:52<23:14,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Abu-Sbeih.jpg

 81%|████████  | 7197/8920 [1:50:52<18:05,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inbar_Lavi.jpg

 81%|████████  | 7199/8920 [1:50:53<14:53,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noga_Erez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuval_Biton.jpg

 81%|████████  | 7200/8920 [1:50:53<12:01,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lili_Hayes.jpg

 81%|████████  | 7202/8920 [1:50:54<11:48,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neta_Alchimister.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tomer_Lawton.jpg

 81%|████████  | 7204/8920 [1:50:55<13:33,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gal_Gold.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Ortega.jpg

 81%|████████  | 7205/8920 [1:50:55<10:58,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deni_Avdija.jpg

 81%|████████  | 7206/8920 [1:50:55<09:31,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haley_Israelov.jpg

 81%|████████  | 7207/8920 [1:50:57<16:14,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Idan_Telem.jpg

 81%|████████  | 7208/8920 [1:50:57<16:37,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/X.Lian.jpg

 81%|████████  | 7209/8920 [1:50:57<13:29,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moses_Hacmon.jpg

 81%|████████  | 7210/8920 [1:50:58<13:05,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liel_Eli.jpg

 81%|████████  | 7211/8920 [1:50:58<11:07,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gali_Golan.jpg

 81%|████████  | 7212/8920 [1:50:59<15:19,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oded_Fehr.jpg

 81%|████████  | 7213/8920 [1:51:00<16:49,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iddo_Goldberg.jpg

 81%|████████  | 7214/8920 [1:51:00<14:54,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayelet_Zurer.jpg

 81%|████████  | 7215/8920 [1:51:01<23:16,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bar_Refaeli.jpg

 81%|████████  | 7216/8920 [1:51:04<36:16,  1.28s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rucka_Rucka_Ali.jpg

 81%|████████  | 7217/8920 [1:51:04<27:31,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eviatar_Ozeri.jpg

 81%|████████  | 7218/8920 [1:51:04<21:19,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronen_Rubinstein.jpg

 81%|████████  | 7219/8920 [1:51:05<16:55,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adam_Rose.jpg

 81%|████████  | 7221/8920 [1:51:05<11:19,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alona_Tal.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eden_Golan.jpg

 81%|████████  | 7222/8920 [1:51:05<10:38,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omer_Fedi.jpg

 81%|████████  | 7223/8920 [1:51:07<17:41,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hilitoledano.jpg

 81%|████████  | 7224/8920 [1:51:07<17:17,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dandan.jpg

 81%|████████  | 7226/8920 [1:51:08<11:26,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yael_Shelbia.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuval_Raphael.jpg

 81%|████████  | 7227/8920 [1:51:08<09:31,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brian_George.jpg

 81%|████████  | 7228/8920 [1:51:08<08:32,  3.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Roiz.jpg

 81%|████████  | 7229/8920 [1:51:09<12:00,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Gantus.jpg

 81%|████████  | 7231/8920 [1:51:09<09:01,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Odeya_Rush.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Netta_Barzilai.jpg

 81%|████████  | 7232/8920 [1:51:09<08:14,  3.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hila_Klein.jpg

 81%|████████  | 7233/8920 [1:51:10<07:33,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asmr_Glow.jpg

 81%|████████  | 7235/8920 [1:51:10<08:48,  3.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shai_Lighter.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Living_Tombstone.jpg

 81%|████████  | 7236/8920 [1:51:12<18:41,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gene_Simmons.jpg

 81%|████████  | 7237/8920 [1:51:12<18:48,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nas_Daily.jpg

 81%|████████  | 7238/8920 [1:51:13<16:36,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noa_Kirel.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benjamin_Netanyahu.jpg

 81%|████████  | 7240/8920 [1:51:13<11:00,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gal_Gadot.jpg

 81%|████████  | 7241/8920 [1:51:14<11:56,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalie_Portman.jpg

 81%|████████  | 7243/8920 [1:51:14<09:39,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sin_Boy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katerinaop.jpg

 81%|████████  | 7244/8920 [1:51:15<08:55,  3.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Ekou.jpg

 81%|████████  | 7246/8920 [1:51:15<07:17,  3.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arianna_Huffington.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mg.jpg

 81%|████████▏ | 7248/8920 [1:51:15<06:19,  4.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Famous_Toli.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Venetia_Kamara.jpg

 81%|████████▏ | 7249/8920 [1:51:16<07:34,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Achilles_Pretty_Boy_Karma.jpg

 81%|████████▏ | 7251/8920 [1:51:16<06:21,  4.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mylifeasmaria99.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sakis_Karpas.jpg

 81%|████████▏ | 7252/8920 [1:51:16<05:51,  4.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Athena_Georgiadi.jpg

 81%|████████▏ | 7253/8920 [1:51:17<07:58,  3.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Lamprou.jpg

 81%|████████▏ | 7254/8920 [1:51:17<10:10,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christos_Dimtsis.jpg

 81%|████████▏ | 7255/8920 [1:51:18<08:48,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Konstantinos_Argiros.jpg

 81%|████████▏ | 7256/8920 [1:51:18<07:54,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariadni_Star.jpg

 81%|████████▏ | 7258/8920 [1:51:18<06:47,  4.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Liva.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thanasis_Antetokounmpo.jpg

 81%|████████▏ | 7259/8920 [1:51:18<06:06,  4.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyle_Hamilton.jpg

 81%|████████▏ | 7261/8920 [1:51:19<08:04,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giannis_Theotokas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trannos.jpg

 81%|████████▏ | 7262/8920 [1:51:19<07:08,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marianna_Grfld.jpg

 81%|████████▏ | 7264/8920 [1:51:20<06:04,  4.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Persad.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vasia_Golfinopoulou.jpg

 81%|████████▏ | 7265/8920 [1:51:21<14:14,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dat_Lilly.jpg

 81%|████████▏ | 7266/8920 [1:51:21<11:46,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Savagiou.jpg

 81%|████████▏ | 7268/8920 [1:51:22<10:53,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dimitris_Tsede.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mrantoun.jpg

 81%|████████▏ | 7269/8920 [1:51:22<09:22,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Artemi_Star.jpg

 82%|████████▏ | 7270/8920 [1:51:23<15:50,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyriakos_Mitsotakis.jpg

 82%|████████▏ | 7271/8920 [1:51:24<15:22,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giorgos_Manolopoulos.jpg

 82%|████████▏ | 7272/8920 [1:51:25<23:34,  1.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milo_Yiannopoulos.jpg

 82%|████████▏ | 7273/8920 [1:51:27<26:39,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sakis_Rouvas.jpg

 82%|████████▏ | 7275/8920 [1:51:27<15:37,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Panagiotis_Eftaxias.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marina_Satti.jpg

 82%|████████▏ | 7276/8920 [1:51:27<12:25,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jadnarra.jpg

 82%|████████▏ | 7277/8920 [1:51:27<10:35,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Klavdia.jpg

 82%|████████▏ | 7278/8920 [1:51:28<10:06,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastazia_Dupee.jpg

 82%|████████▏ | 7279/8920 [1:51:29<15:35,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eponimos_Alkoolikos.jpg

 82%|████████▏ | 7280/8920 [1:51:30<21:13,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofia_Skalkosova.jpg

 82%|████████▏ | 7281/8920 [1:51:30<16:41,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Snik.jpg

 82%|████████▏ | 7283/8920 [1:51:31<12:46,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mustafa_Kemal_Ataturk_(1881-1938).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Panos_Argianidis.jpg

 82%|████████▏ | 7284/8920 [1:51:31<10:30,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yanni.jpg

 82%|████████▏ | 7285/8920 [1:51:31<09:00,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celaine.jpg

 82%|████████▏ | 7286/8920 [1:51:32<12:53,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Lee.jpg

 82%|████████▏ | 7288/8920 [1:51:33<09:17,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giannis_Antetokounmpo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Philip_(1921-2021).jpg

 82%|████████▏ | 7289/8920 [1:51:33<07:52,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrei_Terbea.jpg

 82%|████████▏ | 7291/8920 [1:51:33<06:47,  4.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aeon_Air.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Madalena_Aragão.jpg

 82%|████████▏ | 7292/8920 [1:51:33<06:05,  4.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Everythingapplepro.jpg

 82%|████████▏ | 7293/8920 [1:51:34<06:35,  4.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shady_Srour.jpg

 82%|████████▏ | 7294/8920 [1:51:36<23:42,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luay.jpg

 82%|████████▏ | 7295/8920 [1:51:37<26:31,  1.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maaz_Safder.jpg

 82%|████████▏ | 7296/8920 [1:51:38<20:59,  1.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dollie.jpg

 82%|████████▏ | 7297/8920 [1:51:38<17:17,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sidwaj.jpg

 82%|████████▏ | 7298/8920 [1:51:38<16:11,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayesha_Omar.jpg

 82%|████████▏ | 7300/8920 [1:51:39<10:49,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fawad_Khan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danish_Taimoor.jpg

 82%|████████▏ | 7301/8920 [1:51:39<08:55,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maryam_Nawaz_Sharif.jpg

 82%|████████▏ | 7303/8920 [1:51:39<07:22,  3.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iqra_Aziz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fahad_Mustafa.jpg

 82%|████████▏ | 7304/8920 [1:51:40<06:45,  3.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Summaya_Rizwan.jpg

 82%|████████▏ | 7306/8920 [1:51:41<13:10,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jannat_Mirza.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laiba_Zaid.jpg

 82%|████████▏ | 7308/8920 [1:51:42<08:57,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunny_Jafry.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samar_Jafri.jpg

 82%|████████▏ | 7309/8920 [1:51:42<12:20,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Art_Malik.jpg

 82%|████████▏ | 7311/8920 [1:51:44<14:31,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Atif_Aslam.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rabeeca_Khan.jpg

 82%|████████▏ | 7312/8920 [1:51:44<11:34,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imransavage.jpg

 82%|████████▏ | 7314/8920 [1:51:45<09:01,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayeza_Khan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asad_Ali.jpg

 82%|████████▏ | 7316/8920 [1:51:47<20:31,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sajal_Ali.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dananeer_Mobeen.jpg

 82%|████████▏ | 7317/8920 [1:51:48<16:03,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahad_Raza_Mir.jpg

 82%|████████▏ | 7318/8920 [1:51:48<16:09,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdullah_Tauqeer.jpg

 82%|████████▏ | 7319/8920 [1:51:49<16:41,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samra_Mirr.jpg

 82%|████████▏ | 7320/8920 [1:51:50<22:28,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nawaz_Sharif.jpg

 82%|████████▏ | 7321/8920 [1:51:51<20:14,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muhammad_Ali_Jinnah_(1876-1948).jpg

 82%|████████▏ | 7322/8920 [1:51:51<16:47,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ducky_Bhai.jpg

 82%|████████▏ | 7323/8920 [1:51:51<13:37,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guru_Nanak_(1469-1539).jpg

 82%|████████▏ | 7324/8920 [1:51:52<11:15,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Froggy.jpg

 82%|████████▏ | 7326/8920 [1:51:52<08:11,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahira_Khan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maaz_Theamaazing.jpg

 82%|████████▏ | 7328/8920 [1:51:52<06:24,  4.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Abdaal.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shahveer_Jafry.jpg

 82%|████████▏ | 7330/8920 [1:51:53<05:36,  4.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aina_Asif.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hania_Aamir.jpg

 82%|████████▏ | 7332/8920 [1:51:53<05:00,  5.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Babar_Azam.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zainab_Faisal.jpg

 82%|████████▏ | 7333/8920 [1:51:54<12:55,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hira_Faisal.jpg

 82%|████████▏ | 7334/8920 [1:51:55<12:57,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iqra_Kanwal.jpg

 82%|████████▏ | 7335/8920 [1:51:55<12:00,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iman_Vellani.jpg

 82%|████████▏ | 7336/8920 [1:51:55<10:04,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rabia_Faisal.jpg

 82%|████████▏ | 7338/8920 [1:51:56<07:47,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kumail_Nanjiani.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fatima_Faisal.jpg

 82%|████████▏ | 7339/8920 [1:51:56<10:04,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdur_Rafay.jpg

 82%|████████▏ | 7340/8920 [1:51:58<16:46,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imran_Khan.jpg

 82%|████████▏ | 7342/8920 [1:51:58<10:58,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Super_Sumayah.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malala_Yousafzai.jpg

 82%|████████▏ | 7343/8920 [1:51:58<09:17,  2.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugo_García.jpg

 82%|████████▏ | 7344/8920 [1:51:59<10:46,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luanna_Pérez-Garreaud.jpg

 82%|████████▏ | 7346/8920 [1:52:00<13:20,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejandro_Pino.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Macarena_Argote.jpg

 82%|████████▏ | 7347/8920 [1:52:01<18:29,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thedaarick28.jpg

 82%|████████▏ | 7348/8920 [1:52:02<17:54,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricardo_Zupe.jpg

 82%|████████▏ | 7349/8920 [1:52:02<14:08,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Immortal_Technique.jpg

 82%|████████▏ | 7350/8920 [1:52:03<13:07,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laura_Bozzo.jpg

 82%|████████▏ | 7351/8920 [1:52:03<10:46,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristorata.jpg

 82%|████████▏ | 7352/8920 [1:52:04<16:50,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejandro_Aramburú.jpg

 82%|████████▏ | 7354/8920 [1:52:04<10:47,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Espinoza.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/G18.jpg

 82%|████████▏ | 7355/8920 [1:52:05<16:48,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adriana_Campos_Salazar.jpg

 82%|████████▏ | 7357/8920 [1:52:06<12:26,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Turbo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dina_Boluarte.jpg

 82%|████████▎ | 7359/8920 [1:52:07<08:48,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queen_Pee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duxorethey.jpg

 83%|████████▎ | 7361/8920 [1:52:07<09:34,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anny_Asmr.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paolo_Guerrero.jpg

 83%|████████▎ | 7362/8920 [1:52:09<16:22,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yahaira_Plasencia.jpg

 83%|████████▎ | 7363/8920 [1:52:09<15:34,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Flavia_Laos.jpg

 83%|████████▎ | 7364/8920 [1:52:10<20:12,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Hart.jpg

 83%|████████▎ | 7365/8920 [1:52:11<15:44,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jose_Mufarech.jpg

 83%|████████▎ | 7366/8920 [1:52:12<22:19,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milenka_Nolasco.jpg

 83%|████████▎ | 7367/8920 [1:52:13<22:31,  1.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/_Nenavil_.jpg

 83%|████████▎ | 7368/8920 [1:52:13<18:07,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luciana_Fuster.jpg

 83%|████████▎ | 7369/8920 [1:52:14<16:05,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josi.jpg

 83%|████████▎ | 7370/8920 [1:52:14<14:35,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Whatdafaqshow.jpg

 83%|████████▎ | 7372/8920 [1:52:15<11:41,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moises_Green.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Capitan_Gato.jpg

 83%|████████▎ | 7374/8920 [1:52:15<08:10,  3.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zullyy_Cs.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angela_Rose.jpg

 83%|████████▎ | 7375/8920 [1:52:16<10:04,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alecchi.jpg

 83%|████████▎ | 7377/8920 [1:52:17<09:26,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruben_Tuesta.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mía_Mont.jpg

 83%|████████▎ | 7378/8920 [1:52:17<10:44,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Paz.jpg

 83%|████████▎ | 7379/8920 [1:52:18<11:38,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Flavia_Cucalon.jpg

 83%|████████▎ | 7380/8920 [1:52:18<09:52,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Ramos.jpg

 83%|████████▎ | 7381/8920 [1:52:18<08:50,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriela_Flores_Villar.jpg

 83%|████████▎ | 7382/8920 [1:52:19<12:02,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexia_Barnechea.jpg

 83%|████████▎ | 7384/8920 [1:52:19<08:43,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Ian_Cusick.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mía_Owens.jpg

 83%|████████▎ | 7385/8920 [1:52:20<11:04,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicovald.jpg

 83%|████████▎ | 7386/8920 [1:52:21<12:25,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathalie_Kelley.jpg

 83%|████████▎ | 7388/8920 [1:52:21<09:12,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zombyfie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tula_Rodríguez.jpg

 83%|████████▎ | 7389/8920 [1:52:23<17:49,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lina_Medina.jpg

 83%|████████▎ | 7390/8920 [1:52:23<17:34,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Iskander.jpg

 83%|████████▎ | 7392/8920 [1:52:24<13:06,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenzy_Madbouly.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wegz.jpg

 83%|████████▎ | 7393/8920 [1:52:25<13:16,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dina_Khalil.jpg

 83%|████████▎ | 7394/8920 [1:52:25<10:49,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samer_Al-Madany.jpg

 83%|████████▎ | 7396/8920 [1:52:25<08:23,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohammed_Hijab.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dodi_Fayed_(1955-1997).jpg

 83%|████████▎ | 7397/8920 [1:52:26<13:18,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ramez_Galal.jpg

 83%|████████▎ | 7398/8920 [1:52:27<11:05,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fares_Sokar.jpg

 83%|████████▎ | 7399/8920 [1:52:27<12:01,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jessica_Hosam_Eldin.jpg

 83%|████████▎ | 7400/8920 [1:52:28<12:57,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadia_Ahmed.jpg

 83%|████████▎ | 7401/8920 [1:52:28<10:44,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donia_Samir_Ghanem.jpg

 83%|████████▎ | 7403/8920 [1:52:28<07:56,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hamza_Diab.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danisha_Carter.jpg

 83%|████████▎ | 7404/8920 [1:52:29<09:42,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amira_Adeeb.jpg

 83%|████████▎ | 7406/8920 [1:52:29<07:57,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amr_Waked.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Farah_Roushdy.jpg

 83%|████████▎ | 7407/8920 [1:52:31<14:50,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lina-Sophia_Ben_Hamman.jpg

 83%|████████▎ | 7408/8920 [1:52:31<13:29,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jana_Diab.jpg

 83%|████████▎ | 7409/8920 [1:52:32<13:55,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayten_Radwan.jpg

 83%|████████▎ | 7411/8920 [1:52:32<09:40,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jana_El-Alfy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Black_Charcoal.jpg

 83%|████████▎ | 7412/8920 [1:52:32<08:31,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Abdel_Fattah_El-Sisi.jpg

 83%|████████▎ | 7413/8920 [1:52:33<12:07,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faroukiie.jpg

 83%|████████▎ | 7415/8920 [1:52:34<11:58,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dina_Tokio.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohamed_Light.jpg

 83%|████████▎ | 7416/8920 [1:52:35<12:18,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Agamy.jpg

 83%|████████▎ | 7417/8920 [1:52:36<18:58,  1.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Omar_Khaled_Mohamed_Marmoush.jpg

 83%|████████▎ | 7419/8920 [1:52:37<12:06,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahmed_Mekky.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lunarolexler.jpg

 83%|████████▎ | 7420/8920 [1:52:37<09:40,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Haidar_Macher.jpg

 83%|████████▎ | 7421/8920 [1:52:38<15:23,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamer_Hosny.jpg

 83%|████████▎ | 7422/8920 [1:52:39<15:21,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amir_Eid.jpg

 83%|████████▎ | 7423/8920 [1:52:39<15:16,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sherine.jpg

 83%|████████▎ | 7425/8920 [1:52:40<10:22,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andreas_Eskander.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yasser_Arafat_(1929-2004).jpg

 83%|████████▎ | 7426/8920 [1:52:40<11:24,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohamed_Ramadan.jpg

 83%|████████▎ | 7428/8920 [1:52:41<08:06,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayten_Amer.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varli_Singh.jpg

 83%|████████▎ | 7429/8920 [1:52:41<06:59,  3.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adhamyy.jpg

 83%|████████▎ | 7431/8920 [1:52:41<06:41,  3.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amr_Diab.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mena_Massoud.jpg

 83%|████████▎ | 7433/8920 [1:52:42<05:44,  4.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Larx.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anok_Yai.jpg

 83%|████████▎ | 7434/8920 [1:52:42<05:27,  4.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yxl_Salah.jpg

 83%|████████▎ | 7435/8920 [1:52:43<12:54,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohamed_Salah.jpg

 83%|████████▎ | 7436/8920 [1:52:44<18:31,  1.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaido.jpg

 83%|████████▎ | 7438/8920 [1:52:45<11:46,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Solomia_Lukyanets.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mary_Senn.jpg

 83%|████████▎ | 7439/8920 [1:52:45<12:02,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taras_Maksimuk.jpg

 83%|████████▎ | 7441/8920 [1:52:46<08:34,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruslana_Popach.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Nita.jpg

 83%|████████▎ | 7442/8920 [1:52:46<07:12,  3.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarita_Barvina.jpg

 83%|████████▎ | 7444/8920 [1:52:47<09:20,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivanna_Sakhno.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yep4Andy.jpg

 83%|████████▎ | 7445/8920 [1:52:47<07:45,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ilya_Ilyuk.jpg

 83%|████████▎ | 7447/8920 [1:52:48<06:25,  3.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Pavlinov.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Slavik.jpg

 84%|████████▎ | 7449/8920 [1:52:48<05:31,  4.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maryna_Molchanova.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miss_Katy.jpg

 84%|████████▎ | 7450/8920 [1:52:48<05:20,  4.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olga_Kurylenko.jpg

 84%|████████▎ | 7451/8920 [1:52:49<08:07,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iryna_Zhuravska.jpg

 84%|████████▎ | 7453/8920 [1:52:50<10:39,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yannalinnaa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deny_Havrikov.jpg

 84%|████████▎ | 7455/8920 [1:52:51<09:35,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Crazy_Russian_Hacker.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oleksandr_Kostyliev.jpg

 84%|████████▎ | 7456/8920 [1:52:51<08:09,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Vlad.jpg

 84%|████████▎ | 7457/8920 [1:52:51<09:40,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Candy.Superstar.jpg

 84%|████████▎ | 7458/8920 [1:52:52<08:15,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marinetta_27.jpg

 84%|████████▎ | 7460/8920 [1:52:52<06:48,  3.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Snejana_Onopka.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadiya_Bychkova.jpg

 84%|████████▎ | 7462/8920 [1:52:53<05:46,  4.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Nass.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Notyourbaeboy.jpg

 84%|████████▎ | 7463/8920 [1:52:53<05:37,  4.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alec_Utgoff.jpg

 84%|████████▎ | 7464/8920 [1:52:53<05:34,  4.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milla_Jovovich.jpg

 84%|████████▎ | 7465/8920 [1:52:54<08:54,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Football_Tv.jpg

 84%|████████▎ | 7466/8920 [1:52:54<07:52,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maksim_Chmerkovskiy.jpg

 84%|████████▎ | 7467/8920 [1:52:55<10:13,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pasha_Pai.jpg

 84%|████████▎ | 7468/8920 [1:52:56<19:32,  1.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iryna_Zarutska_(2002-2025).jpg

 84%|████████▎ | 7469/8920 [1:52:57<21:07,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daryna_Popach.jpg

 84%|████████▎ | 7470/8920 [1:52:58<16:59,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Klymenko.jpg

 84%|████████▍ | 7471/8920 [1:52:58<13:21,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Volodymyr_Zelenskyy.jpg

 84%|████████▍ | 7472/8920 [1:52:59<21:25,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Kuzmin.jpg

 84%|████████▍ | 7474/8920 [1:53:00<14:29,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karolina_Protsenko.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lady_Diana.jpg

 84%|████████▍ | 7475/8920 [1:53:00<11:31,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kids_Roma_Show.jpg

 84%|████████▍ | 7476/8920 [1:53:01<13:05,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Malygon.jpg

 84%|████████▍ | 7478/8920 [1:53:03<18:23,  1.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spizee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elizabeth_Lisi.jpg

 84%|████████▍ | 7479/8920 [1:53:04<16:23,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mila_Kunis.jpg

 84%|████████▍ | 7481/8920 [1:53:04<10:34,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Chmerkovskiy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kids_Diana_Show.jpg

 84%|████████▍ | 7483/8920 [1:53:06<12:41,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikocado_Avocado.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nevaaadaa.jpg

 84%|████████▍ | 7485/8920 [1:53:07<14:34,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduarda_Silva.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lixian.jpg

 84%|████████▍ | 7487/8920 [1:53:08<09:32,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rúben_Neves.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luisinha_Barosa_Oliveira.jpg

 84%|████████▍ | 7489/8920 [1:53:09<12:12,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rute_Cardaso.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniela_Melchior.jpg

 84%|████████▍ | 7490/8920 [1:53:10<12:47,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diogo_Dalot.jpg

 84%|████████▍ | 7491/8920 [1:53:10<14:22,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Windoh.jpg

 84%|████████▍ | 7492/8920 [1:53:11<13:09,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nga.jpg

 84%|████████▍ | 7493/8920 [1:53:11<13:23,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisbokate.jpg

 84%|████████▍ | 7494/8920 [1:53:12<13:47,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricardinho.jpg

 84%|████████▍ | 7496/8920 [1:53:13<10:05,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junior_Pereira.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giullia_Calapez.jpg

 84%|████████▍ | 7498/8920 [1:53:13<07:12,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luís_Figo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bernardo_Silva.jpg

 84%|████████▍ | 7499/8920 [1:53:13<06:36,  3.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miguel_Veloso.jpg

 84%|████████▍ | 7501/8920 [1:53:14<05:37,  4.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oceana_Basílio.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/D4Rkframe.jpg

 84%|████████▍ | 7502/8920 [1:53:14<05:19,  4.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniela_Rodrigues.jpg

 84%|████████▍ | 7503/8920 [1:53:14<06:28,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ana_Lisa_Kohler.jpg

 84%|████████▍ | 7505/8920 [1:53:15<05:41,  4.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joaquim_De_Almeida.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aa9Skillz.jpg

 84%|████████▍ | 7507/8920 [1:53:15<05:01,  4.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rúben_Amorim.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/VíTor_Ferreira.jpg

 84%|████████▍ | 7508/8920 [1:53:16<12:49,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_Silva_(2000-2025).jpg

 84%|████████▍ | 7509/8920 [1:53:17<10:37,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ferdinand_Magellan_(1480-1521).jpg

 84%|████████▍ | 7511/8920 [1:53:17<08:40,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wuant.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rúben_Dias.jpg

 84%|████████▍ | 7513/8920 [1:53:19<11:16,  2.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/João_Neves.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rafael_Leão.jpg

 84%|████████▍ | 7515/8920 [1:53:19<07:32,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nuno_Mendes.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jota_Filipe.jpg

 84%|████████▍ | 7516/8920 [1:53:19<06:30,  3.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alba_Baptista.jpg

 84%|████████▍ | 7518/8920 [1:53:21<10:35,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Mourinho.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Ferreira.jpg

 84%|████████▍ | 7520/8920 [1:53:21<07:09,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raphael_Gomes.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romell_Henry.jpg

 84%|████████▍ | 7521/8920 [1:53:22<14:28,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedro_Santos.jpg

 84%|████████▍ | 7523/8920 [1:53:23<09:27,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sara_Sampaio.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kika_Cerqueira_Gomes.jpg

 84%|████████▍ | 7524/8920 [1:53:23<08:01,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/André_Silva.jpg

 84%|████████▍ | 7525/8920 [1:53:24<14:11,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruno_Fernandes.jpg

 84%|████████▍ | 7527/8920 [1:53:24<09:14,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dinis_Pereira.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margarida_Corceiro.jpg

 84%|████████▍ | 7528/8920 [1:53:25<09:11,  2.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/João_Félix.jpg

 84%|████████▍ | 7529/8920 [1:53:26<10:48,  2.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diogo_Jota_(1996-2025).jpg

 84%|████████▍ | 7530/8920 [1:53:26<10:23,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristiano_Ronaldo.jpg

 84%|████████▍ | 7531/8920 [1:53:26<10:50,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henrik_Holm.jpg

 84%|████████▍ | 7532/8920 [1:53:27<09:00,  2.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kitti_Milkgore.jpg

 84%|████████▍ | 7534/8920 [1:53:27<08:15,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tarjei_Sandvik_Moe.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lillepekka.jpg

 84%|████████▍ | 7535/8920 [1:53:28<07:08,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erna_Solberg.jpg

 84%|████████▍ | 7536/8920 [1:53:28<09:38,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Morten_Harket.jpg

 84%|████████▍ | 7537/8920 [1:53:29<15:14,  1.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sigrid_Raabe.jpg

 85%|████████▍ | 7539/8920 [1:53:30<11:42,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sondre_Rodriguez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mina_Jacobsen.jpg

 85%|████████▍ | 7540/8920 [1:53:32<16:50,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frida_Aasen.jpg

 85%|████████▍ | 7541/8920 [1:53:32<14:06,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josefine_Pettersen.jpg

 85%|████████▍ | 7542/8920 [1:53:32<12:35,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tale_Torjussen.jpg

 85%|████████▍ | 7543/8920 [1:53:32<10:14,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leah_Behn.jpg

 85%|████████▍ | 7544/8920 [1:53:34<15:34,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Sogaard.jpg

 85%|████████▍ | 7545/8920 [1:53:34<12:20,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aksel_Hennie.jpg

 85%|████████▍ | 7547/8920 [1:53:34<08:21,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophie_Elise_Isachsen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristofer_Hivju.jpg

 85%|████████▍ | 7548/8920 [1:53:35<09:27,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lido.jpg

 85%|████████▍ | 7550/8920 [1:53:35<06:46,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varg_Vikernes.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tord_Larsson.jpg

 85%|████████▍ | 7552/8920 [1:53:36<05:25,  4.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabelle_Eriksen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erika_Lundmoen.jpg

 85%|████████▍ | 7553/8920 [1:53:36<05:18,  4.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonas_Gahr_Støre.jpg

 85%|████████▍ | 7554/8920 [1:53:36<05:40,  4.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelina_Jordan.jpg

 85%|████████▍ | 7555/8920 [1:53:37<06:55,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camilla_Lorentzen.jpg

 85%|████████▍ | 7557/8920 [1:53:38<10:27,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rd_Benji.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Sotberg.jpg

 85%|████████▍ | 7559/8920 [1:53:38<07:33,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Herman_Tommeraas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorn_Lande.jpg

 85%|████████▍ | 7561/8920 [1:53:39<05:59,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Ødegaard.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Astrid_Smeplass.jpg

 85%|████████▍ | 7562/8920 [1:53:39<05:39,  3.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Ellingsen.jpg

 85%|████████▍ | 7564/8920 [1:53:39<04:55,  4.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Havanna_Winter.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alisha_Boe.jpg

 85%|████████▍ | 7565/8920 [1:53:40<04:48,  4.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brede_Bremnes.jpg

 85%|████████▍ | 7566/8920 [1:53:41<13:31,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Gunnarsen.jpg

 85%|████████▍ | 7568/8920 [1:53:41<08:57,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Magnus_Carlsen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martinus_Gunnarsen.jpg

 85%|████████▍ | 7570/8920 [1:53:43<11:30,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcus_Gunnarsen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aurora_Aksnes.jpg

 85%|████████▍ | 7571/8920 [1:53:43<09:21,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amara_Chehade.jpg

 85%|████████▍ | 7573/8920 [1:53:45<11:33,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Girl_In_Red.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danimilkman.jpg

 85%|████████▍ | 7574/8920 [1:53:45<09:24,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mrsavage.jpg

 85%|████████▍ | 7575/8920 [1:53:46<14:36,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tsutsumi_Hoang.jpg

 85%|████████▍ | 7577/8920 [1:53:47<11:24,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyle_Alessandro.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iamsanna.jpg

 85%|████████▍ | 7578/8920 [1:53:47<09:17,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anastasia_Soare.jpg

 85%|████████▍ | 7579/8920 [1:53:47<09:31,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sashley.jpg

 85%|████████▍ | 7580/8920 [1:53:48<09:40,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kate_Linn.jpg

 85%|████████▍ | 7581/8920 [1:53:48<10:01,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danu_Vlogs.jpg

 85%|████████▌ | 7583/8920 [1:53:50<12:07,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Snikuletz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bela_Lugosi_(1882-1956).jpg

 85%|████████▌ | 7585/8920 [1:53:50<08:08,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zappy_Tv.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Nbn.jpg

 85%|████████▌ | 7586/8920 [1:53:51<09:27,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Otilia.jpg

 85%|████████▌ | 7587/8920 [1:53:51<08:11,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Lara.jpg

 85%|████████▌ | 7589/8920 [1:53:52<08:39,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isilent.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gami_Os.jpg

 85%|████████▌ | 7590/8920 [1:53:52<07:06,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dorian_Popa.jpg

 85%|████████▌ | 7592/8920 [1:53:52<05:46,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theo_Zeciu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gheorghe_Hagi.jpg

 85%|████████▌ | 7594/8920 [1:53:53<04:47,  4.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Stan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tzancă_Uraganu.jpg

 85%|████████▌ | 7595/8920 [1:53:53<04:48,  4.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ihatepink.jpg

 85%|████████▌ | 7596/8920 [1:53:54<07:05,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elie_Wiesel_(1928-2016).jpg

 85%|████████▌ | 7597/8920 [1:53:54<06:30,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Codrin_Bradea.jpg

 85%|████████▌ | 7599/8920 [1:53:55<06:52,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aimee_Tea_Reads.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cocofelix.jpg

 85%|████████▌ | 7600/8920 [1:53:55<06:24,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vlad_Munteanu.jpg

 85%|████████▌ | 7601/8920 [1:53:55<06:04,  3.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vlad_The_Impaler_(1431-1476).jpg

 85%|████████▌ | 7603/8920 [1:53:55<05:17,  4.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Smiley.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adian_Boboc.jpg

 85%|████████▌ | 7604/8920 [1:53:57<11:36,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadina_Ioana.jpg

 85%|████████▌ | 7605/8920 [1:53:58<15:56,  1.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxinfinite.jpg

 85%|████████▌ | 7607/8920 [1:53:58<10:03,  2.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tan_Feelz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xslayder.jpg

 85%|████████▌ | 7608/8920 [1:53:59<14:55,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladteevee.jpg

 85%|████████▌ | 7609/8920 [1:54:00<12:03,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romulus_Stoicescu.jpg

 85%|████████▌ | 7610/8920 [1:54:00<11:24,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nusuntian.jpg

 85%|████████▌ | 7611/8920 [1:54:01<11:30,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Inna.jpg

 85%|████████▌ | 7612/8920 [1:54:01<09:26,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadia_Comaneci.jpg

 85%|████████▌ | 7613/8920 [1:54:01<09:29,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nazanin_Kavari.jpg

 85%|████████▌ | 7615/8920 [1:54:02<08:42,  2.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iraphahell.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Selly.jpg

 85%|████████▌ | 7617/8920 [1:54:03<06:18,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andra_Gogan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Smaranda_Stirbu.jpg

 85%|████████▌ | 7619/8920 [1:54:03<05:04,  4.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bibi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aurelia_Dobre.jpg

 85%|████████▌ | 7620/8920 [1:54:03<07:15,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Condurache.jpg

 85%|████████▌ | 7621/8920 [1:54:04<08:12,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faze_H1Ghsky1.jpg

 85%|████████▌ | 7622/8920 [1:54:04<08:06,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Payleey.jpg

 85%|████████▌ | 7623/8920 [1:54:05<07:06,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Andreea.jpg

 85%|████████▌ | 7624/8920 [1:54:05<06:31,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastian_Stan.jpg

 85%|████████▌ | 7625/8920 [1:54:05<08:09,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Darileidy_Concepcion.jpg

 85%|████████▌ | 7626/8920 [1:54:06<09:02,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Temuera_Morrison.jpg

 86%|████████▌ | 7628/8920 [1:54:07<11:08,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zetassj.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bankii.jpg

 86%|████████▌ | 7629/8920 [1:54:08<11:36,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shaydee.jpg

 86%|████████▌ | 7631/8920 [1:54:08<07:47,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noor_Neelofa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luhan.jpg

 86%|████████▌ | 7633/8920 [1:54:09<05:59,  3.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kris_Wu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhang_Miaoyi.jpg

 86%|████████▌ | 7635/8920 [1:54:11<15:29,  1.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kibo_Lee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoyo_The_Witch.jpg

 86%|████████▌ | 7637/8920 [1:54:12<09:34,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leah_Lewis.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wong_Yuk-Hei.jpg

 86%|████████▌ | 7638/8920 [1:54:12<08:17,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sherry_Cola.jpg

 86%|████████▌ | 7639/8920 [1:54:12<07:43,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The8.jpg

 86%|████████▌ | 7640/8920 [1:54:13<09:02,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhou_Yiran.jpg

 86%|████████▌ | 7642/8920 [1:54:14<08:35,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donnie_Yen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sun_Ning.jpg

 86%|████████▌ | 7643/8920 [1:54:14<07:07,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhao_Lusi.jpg

 86%|████████▌ | 7645/8920 [1:54:15<07:14,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ming-Na_Wen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lulu_Chu.jpg

 86%|████████▌ | 7646/8920 [1:54:15<06:18,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_Wang.jpg

 86%|████████▌ | 7647/8920 [1:54:15<05:53,  3.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shuang_Hu.jpg

 86%|████████▌ | 7649/8920 [1:54:16<09:28,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jet_Li.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kin_Ryan.jpg

 86%|████████▌ | 7650/8920 [1:54:18<14:18,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruby_Siu.jpg

 86%|████████▌ | 7651/8920 [1:54:19<17:42,  1.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wumuti.jpg

 86%|████████▌ | 7652/8920 [1:54:20<20:34,  1.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Sui.jpg

 86%|████████▌ | 7654/8920 [1:54:21<12:07,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simu_Liu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ms_Shi.jpg

 86%|████████▌ | 7655/8920 [1:54:21<09:42,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yao_Ming.jpg

 86%|████████▌ | 7656/8920 [1:54:22<11:18,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Lin.jpg

 86%|████████▌ | 7658/8920 [1:54:23<11:49,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mao_Zedong_(1893-1976).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jade_Weber.jpg

 86%|████████▌ | 7660/8920 [1:54:23<07:42,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dndmolly.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Towa_Bird.jpg

 86%|████████▌ | 7661/8920 [1:54:23<06:52,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celine_Tam.jpg

 86%|████████▌ | 7662/8920 [1:54:24<09:33,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jack_Ma.jpg

 86%|████████▌ | 7664/8920 [1:54:25<06:54,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Xi_Jinping.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ningning.jpg

 86%|████████▌ | 7666/8920 [1:54:25<05:20,  3.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Katrina_Kaif.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joy_Mei.jpg

 86%|████████▌ | 7668/8920 [1:54:25<04:25,  4.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuqi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_He.jpg

 86%|████████▌ | 7669/8920 [1:54:26<04:47,  4.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karissa_Eats.jpg

 86%|████████▌ | 7671/8920 [1:54:26<04:21,  4.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carrie_Ou_Yeung.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tingting_Asmr.jpg

 86%|████████▌ | 7673/8920 [1:54:27<06:49,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhao_Yufan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackson_Wang.jpg

 86%|████████▌ | 7674/8920 [1:54:28<11:33,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Stokes.jpg

 86%|████████▌ | 7676/8920 [1:54:29<07:52,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Stokes.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wengie.jpg

 86%|████████▌ | 7678/8920 [1:54:29<05:38,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jackie_Chan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samara_Boulter.jpg

 86%|████████▌ | 7680/8920 [1:54:29<04:47,  4.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Erissa_Puteri.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Binx.jpg

 86%|████████▌ | 7681/8920 [1:54:29<04:32,  4.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zizan_Razak.jpg

 86%|████████▌ | 7682/8920 [1:54:30<06:53,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/C_Kumaresan.jpg

 86%|████████▌ | 7684/8920 [1:54:30<05:22,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celine_Lam.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edwin_Chuah.jpg

 86%|████████▌ | 7685/8920 [1:54:31<05:04,  4.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faye_Ng.jpg

 86%|████████▌ | 7686/8920 [1:54:31<04:51,  4.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sylvia_Chan.jpg

 86%|████████▌ | 7687/8920 [1:54:31<04:59,  4.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Geniev12.jpg

 86%|████████▌ | 7689/8920 [1:54:33<08:53,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zi_Xuen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alieff_Irfan.jpg

 86%|████████▌ | 7690/8920 [1:54:34<13:49,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manpreet_Toor.jpg

 86%|████████▌ | 7691/8920 [1:54:34<12:36,  1.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yana_Azlee.jpg

 86%|████████▌ | 7692/8920 [1:54:34<10:04,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Uriah_See_Khai.jpg

 86%|████████▋ | 7694/8920 [1:54:35<06:46,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aqil_Zulkiflee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Wan.jpg

 86%|████████▋ | 7696/8920 [1:54:35<05:08,  3.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Addy_Lee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anwar_Ibrahim.jpg

 86%|████████▋ | 7698/8920 [1:54:36<05:47,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimmy_Choo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Putra_Abdullah.jpg

 86%|████████▋ | 7699/8920 [1:54:36<05:08,  3.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aisyah_Nur.jpg

 86%|████████▋ | 7701/8920 [1:54:37<08:39,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elyana.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chaelanl.jpg

 86%|████████▋ | 7702/8920 [1:54:38<09:36,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahathir_Mohamad.jpg

 86%|████████▋ | 7704/8920 [1:54:39<08:12,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michael_Gough_(1916-2011).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simon_Russell_Beale.jpg

 86%|████████▋ | 7705/8920 [1:54:40<13:05,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Siti_Nurhaliza.jpg

 86%|████████▋ | 7706/8920 [1:54:40<10:34,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cado.jpg

 86%|████████▋ | 7707/8920 [1:54:41<11:05,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Chong_Wei.jpg

 86%|████████▋ | 7709/8920 [1:54:42<11:42,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronny_Chieng.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Puteri_Rania.jpg

 86%|████████▋ | 7711/8920 [1:54:44<12:25,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faline_San.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Henry_Golding.jpg

 86%|████████▋ | 7712/8920 [1:54:46<21:58,  1.09s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelle_Yeoh.jpg

 86%|████████▋ | 7713/8920 [1:54:46<17:00,  1.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marilyn_Monru.jpg

 86%|████████▋ | 7714/8920 [1:54:46<13:28,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aekims.jpg

 86%|████████▋ | 7715/8920 [1:54:47<12:03,  1.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miraie.jpg

 87%|████████▋ | 7716/8920 [1:54:47<09:58,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyanna_Kea.jpg

 87%|████████▋ | 7717/8920 [1:54:48<14:43,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chelsea_Sik.jpg

 87%|████████▋ | 7719/8920 [1:54:49<09:13,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robin_Lim.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ms_Qiwiie.jpg

 87%|████████▋ | 7720/8920 [1:54:49<07:24,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guy_Sebastian.jpg

 87%|████████▋ | 7721/8920 [1:54:49<06:41,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuna.jpg

 87%|████████▋ | 7723/8920 [1:54:50<05:22,  3.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nigel_Ng.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cherry_Pop_Productions.jpg

 87%|████████▋ | 7724/8920 [1:54:50<07:09,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Siow_Wei.jpg

 87%|████████▋ | 7725/8920 [1:54:51<08:04,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keara_Cornella.jpg

 87%|████████▋ | 7726/8920 [1:54:51<08:43,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Scru_Face_Jean.jpg

 87%|████████▋ | 7728/8920 [1:54:53<13:47,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jide_Olatunji.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cleotrapa_West.jpg

 87%|████████▋ | 7729/8920 [1:54:54<12:54,  1.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mc_Shem.jpg

 87%|████████▋ | 7730/8920 [1:54:54<10:23,  1.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Omogbehin.jpg

 87%|████████▋ | 7732/8920 [1:54:55<07:29,  2.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rynenzo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asake.jpg

 87%|████████▋ | 7733/8920 [1:54:55<06:21,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peller.jpg

 87%|████████▋ | 7734/8920 [1:54:55<05:44,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Muhammadu_Buhari_(1942-2025).jpg

 87%|████████▋ | 7735/8920 [1:54:55<05:25,  3.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bismarck_Ebiweh.jpg

 87%|████████▋ | 7736/8920 [1:54:56<10:09,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hakeem_Kae-Kazim.jpg

 87%|████████▋ | 7737/8920 [1:54:57<09:50,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wisdom_Kaye.jpg

 87%|████████▋ | 7739/8920 [1:54:57<06:52,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wendy_Osefo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dayo_Okeniyi.jpg

 87%|████████▋ | 7740/8920 [1:54:58<05:51,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toks_Olagundoye.jpg

 87%|████████▋ | 7741/8920 [1:54:58<07:30,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chukwuka_Ekweani.jpg

 87%|████████▋ | 7742/8920 [1:54:59<08:19,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thebigsol.jpg

 87%|████████▋ | 7743/8920 [1:54:59<08:36,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/King_Chris.jpg

 87%|████████▋ | 7744/8920 [1:55:00<08:42,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Collins_O.jpg

 87%|████████▋ | 7745/8920 [1:55:00<08:12,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ebube_Obi.jpg

 87%|████████▋ | 7746/8920 [1:55:00<07:00,  2.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Regina_Daniels.jpg

 87%|████████▋ | 7747/8920 [1:55:01<07:58,  2.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sojaboy.jpg

 87%|████████▋ | 7748/8920 [1:55:02<11:30,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wunmi_Mosaku.jpg

 87%|████████▋ | 7750/8920 [1:55:02<07:31,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay-Jay_Okocha.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Young_Jonn.jpg

 87%|████████▋ | 7752/8920 [1:55:02<05:46,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ami_Mcclure.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Baba.jpg

 87%|████████▋ | 7753/8920 [1:55:03<05:20,  3.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yvonne_Orji.jpg

 87%|████████▋ | 7754/8920 [1:55:03<05:06,  3.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Purple_Speedy.jpg

 87%|████████▋ | 7755/8920 [1:55:08<30:52,  1.59s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Osimhen.jpg

 87%|████████▋ | 7756/8920 [1:55:08<25:36,  1.32s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugo_Weaving.jpg

 87%|████████▋ | 7758/8920 [1:55:10<19:44,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hakeem_Olajuwon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Israel_Adesanya.jpg

 87%|████████▋ | 7759/8920 [1:55:10<15:41,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Macaulley.jpg

 87%|████████▋ | 7761/8920 [1:55:11<10:51,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aunty_Success.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiwa_Savage.jpg

 87%|████████▋ | 7762/8920 [1:55:11<08:34,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Angel.jpg

 87%|████████▋ | 7764/8920 [1:55:12<06:12,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil'_O.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wizkid.jpg

 87%|████████▋ | 7765/8920 [1:55:13<11:22,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tems.jpg

 87%|████████▋ | 7766/8920 [1:55:13<09:19,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sade.jpg

 87%|████████▋ | 7767/8920 [1:55:14<13:26,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Burna_Boy.jpg

 87%|████████▋ | 7769/8920 [1:55:15<08:24,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emanuella_Samuel.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samspedy_Entertainment.jpg

 87%|████████▋ | 7770/8920 [1:55:15<09:32,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lumi.jpg

 87%|████████▋ | 7772/8920 [1:55:16<06:26,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rema.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kado_Art.jpg

 87%|████████▋ | 7773/8920 [1:55:16<05:30,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nattawat_Jirochtikul.jpg

 87%|████████▋ | 7774/8920 [1:55:17<08:24,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naiyarat_Thanawaigoses.jpg

 87%|████████▋ | 7775/8920 [1:55:17<07:04,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Porntawan_Klompua.jpg

 87%|████████▋ | 7776/8920 [1:55:18<11:59,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thaiboy_Digital.jpg

 87%|████████▋ | 7778/8920 [1:55:19<08:56,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Win_Metawin_Opas-Iamkajorn.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tony_Jaa.jpg

 87%|████████▋ | 7780/8920 [1:55:19<06:14,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pugun_Wisad.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sirada_Angkapanomprai.jpg

 87%|████████▋ | 7781/8920 [1:55:20<11:18,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Engfa_Waraha.jpg

 87%|████████▋ | 7783/8920 [1:55:21<07:24,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cait_Knight.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noon_Huck.jpg

 87%|████████▋ | 7785/8920 [1:55:21<06:09,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Janiphoria.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Becky_Armstrong.jpg

 87%|████████▋ | 7786/8920 [1:55:22<05:23,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thanawat_Rattanakitpaisan.jpg

 87%|████████▋ | 7787/8920 [1:55:22<05:36,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natachai_Boonprasert.jpg

 87%|████████▋ | 7789/8920 [1:55:23<06:08,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chawarin_Perdpiriyawong.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tontawan_Tantivejakul.jpg

 87%|████████▋ | 7790/8920 [1:55:24<11:12,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sarocha_Chankimha.jpg

 87%|████████▋ | 7792/8920 [1:55:24<07:26,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zak_Srakaew.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nattapong_Kaewsomnuek.jpg

 87%|████████▋ | 7793/8920 [1:55:24<06:13,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chicha_Amatayakul.jpg

 87%|████████▋ | 7794/8920 [1:55:25<05:36,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sorn.jpg

 87%|████████▋ | 7795/8920 [1:55:26<10:50,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aimee_Jai_Hall.jpg

 87%|████████▋ | 7796/8920 [1:55:26<08:43,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minnie.jpg

 87%|████████▋ | 7797/8920 [1:55:26<08:19,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vachirawit_Chivaaree.jpg

 87%|████████▋ | 7798/8920 [1:55:28<12:52,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prince_Vatani.jpg

 87%|████████▋ | 7800/8920 [1:55:28<09:31,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeff_Satur.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Archen_Aydin.jpg

 87%|████████▋ | 7801/8920 [1:55:29<07:51,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pruk_Panich.jpg

 87%|████████▋ | 7803/8920 [1:55:30<07:15,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Third_Lapat.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marquise_Aura.jpg

 88%|████████▊ | 7805/8920 [1:55:30<06:32,  2.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ammika_Harris.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chai_Hansen.jpg

 88%|████████▊ | 7806/8920 [1:55:31<06:26,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Myra_Molloy.jpg

 88%|████████▊ | 7807/8920 [1:55:31<05:37,  3.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hong_Chau.jpg

 88%|████████▊ | 7808/8920 [1:55:32<10:39,  1.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/1St.jpg

 88%|████████▊ | 7810/8920 [1:55:33<08:47,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Notamberroblox.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ten.jpg

 88%|████████▊ | 7811/8920 [1:55:33<07:01,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sas-Asmr.jpg

 88%|████████▊ | 7812/8920 [1:55:33<07:35,  2.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pornsak.jpg

 88%|████████▊ | 7813/8920 [1:55:34<06:25,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bambam.jpg

 88%|████████▊ | 7814/8920 [1:55:34<05:40,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pharita.jpg

 88%|████████▊ | 7816/8920 [1:55:34<05:33,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoo_Jieun.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiquita.jpg

 88%|████████▊ | 7818/8920 [1:55:35<04:40,  3.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jmancurly.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa.jpg

 88%|████████▊ | 7819/8920 [1:55:35<04:09,  4.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/N10Zinx.jpg

 88%|████████▊ | 7821/8920 [1:55:35<03:43,  4.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taylin_Chandler.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Thompson.jpg

 88%|████████▊ | 7822/8920 [1:55:36<03:32,  5.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steven_Adams.jpg

 88%|████████▊ | 7823/8920 [1:55:36<03:47,  4.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacinda_Ardern.jpg

 88%|████████▊ | 7825/8920 [1:55:36<03:47,  4.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manu_Bennett.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buddy_Pohato.jpg

 88%|████████▊ | 7827/8920 [1:55:37<03:36,  5.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucy_Lawless.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Park.jpg

 88%|████████▊ | 7829/8920 [1:55:37<03:18,  5.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolan_Dark.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benny_Osborne.jpg

 88%|████████▊ | 7830/8920 [1:55:37<03:13,  5.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lankmandan.jpg

 88%|████████▊ | 7831/8920 [1:55:38<05:51,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faith_Ward.jpg

 88%|████████▊ | 7833/8920 [1:55:39<08:26,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jemaine_Clement.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jay_Ryan.jpg

 88%|████████▊ | 7835/8920 [1:55:40<05:53,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_House.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marton_Csokas.jpg

 88%|████████▊ | 7836/8920 [1:55:41<10:46,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caleb_Cameron_Lee.jpg

 88%|████████▊ | 7838/8920 [1:55:42<08:21,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thomasin_Mckenzie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julian_Dennison.jpg

 88%|████████▊ | 7839/8920 [1:55:42<06:43,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cheree_Crowley.jpg

 88%|████████▊ | 7840/8920 [1:55:42<07:40,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Henderson.jpg

 88%|████████▊ | 7842/8920 [1:55:43<05:28,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rhys_Darby.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taika_Waititi.jpg

 88%|████████▊ | 7844/8920 [1:55:43<05:20,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amie_Donald.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Mcgregor.jpg

 88%|████████▊ | 7846/8920 [1:55:44<04:05,  4.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mccreamy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peta_Murgatroyd.jpg

 88%|████████▊ | 7847/8920 [1:55:44<06:09,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melanie_Lynskey.jpg

 88%|████████▊ | 7848/8920 [1:55:45<05:42,  3.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Mciver.jpg

 88%|████████▊ | 7849/8920 [1:55:45<05:23,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karl_Urban.jpg

 88%|████████▊ | 7851/8920 [1:55:46<05:43,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Russell_Crowe.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antony_Starr.jpg

 88%|████████▊ | 7852/8920 [1:55:46<05:13,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Lawson.jpg

 88%|████████▊ | 7854/8920 [1:55:46<04:24,  4.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lance_Savali.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fitz.jpg

 88%|████████▊ | 7856/8920 [1:55:48<07:30,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jordan_Riki.jpg

 88%|████████▊ | 7858/8920 [1:55:48<05:21,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Dallas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richie_Mccaw.jpg

 88%|████████▊ | 7860/8920 [1:55:48<04:29,  3.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cracky4.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Austin_Taylor.jpg

 88%|████████▊ | 7861/8920 [1:55:49<04:12,  4.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keith_Urban.jpg

 88%|████████▊ | 7863/8920 [1:55:49<05:05,  3.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chillz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorde.jpg

 88%|████████▊ | 7865/8920 [1:55:50<03:59,  4.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kj_Apa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosé_Park.jpg

 88%|████████▊ | 7867/8920 [1:55:50<03:28,  5.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jandel.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pailita.jpg

 88%|████████▊ | 7868/8920 [1:55:50<03:19,  5.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Standly.jpg

 88%|████████▊ | 7869/8920 [1:55:50<03:51,  4.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arturo_Vidal.jpg

 88%|████████▊ | 7870/8920 [1:55:51<07:04,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Degoboom.jpg

 88%|████████▊ | 7871/8920 [1:55:52<08:57,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martín_Rompeltien.jpg

 88%|████████▊ | 7873/8920 [1:55:52<06:23,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pia_Miller.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ignacio_Orellana.jpg

 88%|████████▊ | 7874/8920 [1:55:53<05:20,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Boric.jpg

 88%|████████▊ | 7875/8920 [1:55:53<04:59,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Flavia_Martin.jpg

 88%|████████▊ | 7876/8920 [1:55:53<04:33,  3.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Araya.jpg

 88%|████████▊ | 7877/8920 [1:55:53<04:16,  4.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_White.jpg

 88%|████████▊ | 7878/8920 [1:55:54<08:47,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kidd_Voodoo.jpg

 88%|████████▊ | 7879/8920 [1:55:56<12:21,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Don_Francisco.jpg

 88%|████████▊ | 7880/8920 [1:55:56<09:42,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mattplays.jpg

 88%|████████▊ | 7881/8920 [1:55:56<08:32,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trinidad_Riveros.jpg

 88%|████████▊ | 7882/8920 [1:55:56<07:11,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beno_Espinosa.jpg

 88%|████████▊ | 7883/8920 [1:55:58<13:17,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Acursito.jpg

 88%|████████▊ | 7885/8920 [1:55:59<11:53,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jere_Klein.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofía_Silva.jpg

 88%|████████▊ | 7886/8920 [1:56:00<09:21,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cristián_De_La_Fuente.jpg

 88%|████████▊ | 7887/8920 [1:56:00<07:34,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isidora_Vives.jpg

 88%|████████▊ | 7888/8920 [1:56:01<14:02,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonor_Varela.jpg

 88%|████████▊ | 7889/8920 [1:56:02<10:52,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorenza_Izzo.jpg

 88%|████████▊ | 7890/8920 [1:56:02<08:44,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Millaray.jpg

 88%|████████▊ | 7892/8920 [1:56:02<06:12,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tomiii_11_(2009-2021).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Renata_Jara.jpg

 88%|████████▊ | 7894/8920 [1:56:03<04:34,  3.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camila_Cabello.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cote_De_Pablo.jpg

 89%|████████▊ | 7896/8920 [1:56:04<07:26,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexis_Sánchez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mon_Laferte.jpg

 89%|████████▊ | 7898/8920 [1:56:05<08:57,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorge_López.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tati_Fernández.jpg

 89%|████████▊ | 7899/8920 [1:56:07<12:17,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Valenzuela.jpg

 89%|████████▊ | 7900/8920 [1:56:07<10:46,  1.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jocx17.jpg

 89%|████████▊ | 7902/8920 [1:56:08<07:40,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ignacia_Antonia.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Papa_Bee.jpg

 89%|████████▊ | 7904/8920 [1:56:08<05:25,  3.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Floyymenor.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paloma_Mami.jpg

 89%|████████▊ | 7906/8920 [1:56:08<04:16,  3.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Vaquer.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Germán_Garmendia.jpg

 89%|████████▊ | 7908/8920 [1:56:09<03:31,  4.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bramty_Juliette.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cris_Mj.jpg

 89%|████████▊ | 7909/8920 [1:56:10<06:11,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Snooki.jpg

 89%|████████▊ | 7911/8920 [1:56:11<08:20,  2.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernanda_Villalobos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mario_Selman.jpg

 89%|████████▊ | 7912/8920 [1:56:12<09:15,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/León_Allendes.jpg

 89%|████████▊ | 7913/8920 [1:56:12<08:51,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedro_Pascal.jpg

 89%|████████▊ | 7914/8920 [1:56:12<07:21,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Luis_Guerra.jpg

 89%|████████▊ | 7916/8920 [1:56:13<05:15,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/La_Materialista.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amelia_Vega.jpg

 89%|████████▉ | 7917/8920 [1:56:14<08:07,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jey_One.jpg

 89%|████████▉ | 7918/8920 [1:56:14<08:48,  1.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sammy_Sosa.jpg

 89%|████████▉ | 7919/8920 [1:56:15<08:52,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emily_Tosta.jpg

 89%|████████▉ | 7920/8920 [1:56:15<09:25,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Ramírez.jpg

 89%|████████▉ | 7921/8920 [1:56:16<10:09,  1.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rubby_Perez_(1956-2025).jpg

 89%|████████▉ | 7922/8920 [1:56:17<12:57,  1.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zuany_Tatiana.jpg

 89%|████████▉ | 7923/8920 [1:56:19<18:49,  1.13s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jandel_Gustave.jpg

 89%|████████▉ | 7924/8920 [1:56:20<15:48,  1.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariis_Muñoz.jpg

 89%|████████▉ | 7925/8920 [1:56:20<13:33,  1.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jhonny_Peralta.jpg

 89%|████████▉ | 7927/8920 [1:56:21<08:08,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Huan62.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeremy_Peña.jpg

 89%|████████▉ | 7929/8920 [1:56:21<05:21,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tokischa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorge_Lendeborg_Jr..jpg

 89%|████████▉ | 7930/8920 [1:56:21<04:32,  3.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hasly.jpg

 89%|████████▉ | 7932/8920 [1:56:22<04:17,  3.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eduardo_Núñez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lil_Naay.jpg

 89%|████████▉ | 7934/8920 [1:56:22<03:26,  4.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Al_Horford.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jose_Ramon.jpg

 89%|████████▉ | 7936/8920 [1:56:22<03:29,  4.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rdjavi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jan_Luis_Castellanos.jpg

 89%|████████▉ | 7937/8920 [1:56:23<03:35,  4.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/José_Bautista.jpg

 89%|████████▉ | 7938/8920 [1:56:23<04:06,  3.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sr_Jimenez.jpg

 89%|████████▉ | 7940/8920 [1:56:24<04:55,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dania_Ramírez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Martinez.jpg

 89%|████████▉ | 7941/8920 [1:56:25<09:14,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jelijah_Diaz.jpg

 89%|████████▉ | 7943/8920 [1:56:26<07:29,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Pujols.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elly_Antonio_De_La_Cruz.jpg

 89%|████████▉ | 7945/8920 [1:56:26<05:10,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Teoscar_Hernández.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Santiago_Matías.jpg

 89%|████████▉ | 7946/8920 [1:56:26<04:40,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dascha_Polanco.jpg

 89%|████████▉ | 7947/8920 [1:56:28<09:22,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donpollo.jpg

 89%|████████▉ | 7949/8920 [1:56:29<09:00,  1.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samantha_Sepúlveda.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pioladitingancia.jpg

 89%|████████▉ | 7950/8920 [1:56:29<09:10,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Ortíz.jpg

 89%|████████▉ | 7951/8920 [1:56:30<09:21,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julio_Rodriguez.jpg

 89%|████████▉ | 7953/8920 [1:56:30<06:10,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Tatís_Jr..jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aimee_Carrero.jpg

 89%|████████▉ | 7955/8920 [1:56:31<05:37,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Soto.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yailin_La_Más_Viral.jpg

 89%|████████▉ | 7956/8920 [1:56:31<04:45,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angioly_Tejeda.jpg

 89%|████████▉ | 7957/8920 [1:56:32<04:40,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/El_Alfa_El_Jefe.jpg

 89%|████████▉ | 7958/8920 [1:56:33<09:04,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tokyo_Toni.jpg

 89%|████████▉ | 7959/8920 [1:56:33<08:37,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natti_Natasha.jpg

 89%|████████▉ | 7961/8920 [1:56:34<07:14,  2.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dashie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dave_Matthews.jpg

 89%|████████▉ | 7963/8920 [1:56:36<09:28,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Harry_Warner_(1881-1958).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Viktor_Einar_Gyökeres.jpg

 89%|████████▉ | 7965/8920 [1:56:36<06:45,  2.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arie_Luyendyk_Jr..jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maya_Başol.jpg

 89%|████████▉ | 7967/8920 [1:56:37<04:44,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nathalie_Paris.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minicuteclub.jpg

 89%|████████▉ | 7968/8920 [1:56:37<04:05,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miki_Matsubara_(1959-2004).jpg

 89%|████████▉ | 7969/8920 [1:56:37<05:25,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ikue_Otani.jpg

 89%|████████▉ | 7971/8920 [1:56:39<07:30,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nico_Blox.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sagawa.jpg

 89%|████████▉ | 7972/8920 [1:56:39<06:03,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fujii_Kaze.jpg

 89%|████████▉ | 7973/8920 [1:56:39<05:25,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_T_Jones.jpg

 89%|████████▉ | 7974/8920 [1:56:40<06:44,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naomi_Osaka.jpg

 89%|████████▉ | 7975/8920 [1:56:41<10:19,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kairi_Sane.jpg

 89%|████████▉ | 7977/8920 [1:56:42<07:23,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dori_Sakurada.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kazuha.jpg

 89%|████████▉ | 7978/8920 [1:56:52<52:50,  3.37s/it]

❌ Failed to download https://www.famousbirthdays.com/thumbnails/enami-asa-medium.jpg: The read operation timed out

 89%|████████▉ | 7979/8920 [1:56:56<57:09,  3.64s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kane_Tanaka_(1903-2022).jpg

 89%|████████▉ | 7981/8920 [1:56:57<30:47,  1.97s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kawai_Ruka.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elena_Shinohara.jpg

 89%|████████▉ | 7983/8920 [1:56:57<16:34,  1.06s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junko_Furuta_(1971-1989).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miya_Cech.jpg

 90%|████████▉ | 7985/8920 [1:56:58<11:02,  1.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoko_Ono.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sakura_Miyawaki.jpg

 90%|████████▉ | 7987/8920 [1:56:59<07:04,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thee_Blackbadger.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asuka.jpg

 90%|████████▉ | 7988/8920 [1:56:59<05:41,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ado.jpg

 90%|████████▉ | 7990/8920 [1:56:59<04:42,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Minatozaki_Sana.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruka.jpg

 90%|████████▉ | 7991/8920 [1:56:59<04:06,  3.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marco_Portugal.jpg

 90%|████████▉ | 7992/8920 [1:57:00<07:11,  2.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bayashi.jpg

 90%|████████▉ | 7993/8920 [1:57:01<08:12,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yuki_Tsunoda.jpg

 90%|████████▉ | 7994/8920 [1:57:02<12:07,  1.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nijiro_Murakami.jpg

 90%|████████▉ | 7995/8920 [1:57:03<09:31,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iroha.jpg

 90%|████████▉ | 7996/8920 [1:57:03<07:43,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saki_Fujita.jpg

 90%|████████▉ | 7997/8920 [1:57:03<07:46,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monako0515.jpg

 90%|████████▉ | 7998/8920 [1:57:04<06:24,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mia_Sayoko.jpg

 90%|████████▉ | 8000/8920 [1:57:04<05:56,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junya1Gou.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moka.jpg

 90%|████████▉ | 8001/8920 [1:57:05<05:04,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Momo.jpg

 90%|████████▉ | 8002/8920 [1:57:05<05:52,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kento_Yamazaki.jpg

 90%|████████▉ | 8004/8920 [1:57:05<04:25,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iyo_Sky.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guma_Art.jpg

 90%|████████▉ | 8005/8920 [1:57:06<03:57,  3.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kiyomi.jpg

 90%|████████▉ | 8007/8920 [1:57:06<03:28,  4.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Boggs.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shohei_Ohtani.jpg

 90%|████████▉ | 8009/8920 [1:57:07<04:41,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mitski.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shakhed.jpg

 90%|████████▉ | 8010/8920 [1:57:08<07:43,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zach_Bryan.jpg

 90%|████████▉ | 8012/8920 [1:57:09<08:30,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sky_Brown.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joji.jpg

 90%|████████▉ | 8013/8920 [1:57:09<06:53,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ni-Ki.jpg

 90%|████████▉ | 8014/8920 [1:57:10<05:44,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Skyyjade.jpg

 90%|████████▉ | 8015/8920 [1:57:10<07:35,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Torres.jpg

 90%|████████▉ | 8016/8920 [1:57:11<08:11,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luis_Díaz.jpg

 90%|████████▉ | 8017/8920 [1:57:12<08:54,  1.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julie_Sofia.jpg

 90%|████████▉ | 8019/8920 [1:57:12<05:53,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Camilo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carmen_Villalobos.jpg

 90%|████████▉ | 8020/8920 [1:57:12<04:58,  3.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Valdes.jpg

 90%|████████▉ | 8021/8920 [1:57:13<04:25,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ami_Rodríguez.jpg

 90%|████████▉ | 8022/8920 [1:57:13<04:01,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_García.jpg

 90%|████████▉ | 8024/8920 [1:57:13<03:25,  4.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anddy_.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Richard_Ríos.jpg

 90%|████████▉ | 8026/8920 [1:57:15<06:12,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Salas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Ortiz.jpg

 90%|████████▉ | 8027/8920 [1:57:15<05:21,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catalina_Sandino_Moreno.jpg

 90%|█████████ | 8028/8920 [1:57:16<10:54,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marlon_Villamil.jpg

 90%|█████████ | 8029/8920 [1:57:17<10:22,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeancarlo_León.jpg

 90%|█████████ | 8030/8920 [1:57:18<10:40,  1.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blessd.jpg

 90%|█████████ | 8032/8920 [1:57:19<09:53,  1.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_López.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/John_Leguizamo.jpg

 90%|█████████ | 8033/8920 [1:57:19<07:54,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ana_Maria_Jones.jpg

 90%|█████████ | 8035/8920 [1:57:20<05:23,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Roy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lulu99.jpg

 90%|█████████ | 8037/8920 [1:57:21<04:44,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manuel_Turizo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Feria.jpg

 90%|█████████ | 8038/8920 [1:57:21<04:03,  3.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beéle.jpg

 90%|█████████ | 8040/8920 [1:57:22<06:09,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Westcol.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastián_Villalobos.jpg

 90%|█████████ | 8042/8920 [1:57:22<04:15,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Estrella_Aventurera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastián_Yatra.jpg

 90%|█████████ | 8044/8920 [1:57:23<05:16,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isabella_Gómez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alinity_Divine.jpg

 90%|█████████ | 8046/8920 [1:57:26<10:13,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Feid.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luna_Bloom.jpg

 90%|█████████ | 8047/8920 [1:57:26<08:03,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/James_Rodríguez.jpg

 90%|█████████ | 8048/8920 [1:57:26<06:51,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeraldin_Ocampo.jpg

 90%|█████████ | 8049/8920 [1:57:26<05:51,  2.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Canas.jpg

 90%|█████████ | 8051/8920 [1:57:27<04:12,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dascha_Grinwis.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miguel_Morales.jpg

 90%|█████████ | 8053/8920 [1:57:27<03:44,  3.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Celeste_Aventurera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lukas_Urkijo.jpg

 90%|█████████ | 8054/8920 [1:57:27<03:20,  4.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J_Balvin.jpg

 90%|█████████ | 8055/8920 [1:57:29<07:38,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maluma.jpg

 90%|█████████ | 8056/8920 [1:57:29<06:16,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yung_Filly.jpg

 90%|█████████ | 8057/8920 [1:57:29<05:29,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karol_G.jpg

 90%|█████████ | 8058/8920 [1:57:30<06:37,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sofía_Vergara.jpg

 90%|█████████ | 8059/8920 [1:57:31<09:44,  1.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Espada.jpg

 90%|█████████ | 8060/8920 [1:57:31<07:46,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ferran_Espada.jpg

 90%|█████████ | 8061/8920 [1:57:31<06:22,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shakira.jpg

 90%|█████████ | 8063/8920 [1:57:32<04:27,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kivanc_Tatlitug.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ozge_Yagiz.jpg

 90%|█████████ | 8064/8920 [1:57:33<09:48,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toprak_Bocuk.jpg

 90%|█████████ | 8066/8920 [1:57:34<07:40,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alperen_Şengün.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ramazan_Giriş.jpg

 90%|█████████ | 8067/8920 [1:57:35<08:04,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nitlenka.jpg

 90%|█████████ | 8068/8920 [1:57:35<06:41,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruhi_Çenet.jpg

 90%|█████████ | 8069/8920 [1:57:36<09:55,  1.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rumeysa_Gelgi.jpg

 90%|█████████ | 8070/8920 [1:57:38<13:16,  1.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Engin_Altan_Duzyatan.jpg

 90%|█████████ | 8072/8920 [1:57:38<07:53,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kingani.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zeliha_Akpinar.jpg

 91%|█████████ | 8073/8920 [1:57:38<06:18,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Su_Burcu_Yazgi_Coskun.jpg

 91%|█████████ | 8075/8920 [1:57:39<05:25,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tcheky_Karyo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neslihan_Atagül.jpg

 91%|█████████ | 8077/8920 [1:57:40<04:05,  3.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mert_Ramazan_Demir.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aleyna_Tilki.jpg

 91%|█████████ | 8078/8920 [1:57:41<06:53,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zaro_Aga_(1774-1934).jpg

 91%|█████████ | 8079/8920 [1:57:41<06:00,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cznburak.jpg

 91%|█████████ | 8080/8920 [1:57:41<05:22,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Numan_Acar.jpg

 91%|█████████ | 8082/8920 [1:57:41<03:58,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ibrahim_Tatlises.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ecrin_Su_Coban.jpg

 91%|█████████ | 8083/8920 [1:57:42<03:30,  3.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leya_Kirsan.jpg

 91%|█████████ | 8085/8920 [1:57:43<06:11,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Efewissie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Boran_Kuzum.jpg

 91%|█████████ | 8087/8920 [1:57:43<04:14,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demet_Ozdemir.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nil_Sani.jpg

 91%|█████████ | 8088/8920 [1:57:45<07:28,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Esra_Bilgic.jpg

 91%|█████████ | 8090/8920 [1:57:45<05:00,  2.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Can_Yaman.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cagatay_Ulusoy.jpg

 91%|█████████ | 8091/8920 [1:57:45<04:27,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Orkun_Isitmak.jpg

 91%|█████████ | 8092/8920 [1:57:45<04:03,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Afra_Saracoglu.jpg

 91%|█████████ | 8093/8920 [1:57:46<05:09,  2.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nusret_Gokce.jpg

 91%|█████████ | 8095/8920 [1:57:46<03:52,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yasin_Cengiz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Burak_Ozcivit.jpg

 91%|█████████ | 8096/8920 [1:57:47<05:07,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Özge_Törer.jpg

 91%|█████████ | 8097/8920 [1:57:47<05:03,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ülkü_Hilal_Çiftçi.jpg

 91%|█████████ | 8099/8920 [1:57:49<06:59,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Recep_Tayyip_Erdogan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kerem_Bursin.jpg

 91%|█████████ | 8101/8920 [1:57:49<04:46,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Masteroogwgay.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enes_Batur.jpg

 91%|█████████ | 8102/8920 [1:57:49<04:15,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ali_Dawah.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sultan_Kosen.jpg

 91%|█████████ | 8104/8920 [1:57:50<03:19,  4.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ozkan_Balkas.jpg

 91%|█████████ | 8105/8920 [1:57:50<03:43,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hailey_Sani.jpg

 91%|█████████ | 8107/8920 [1:57:51<03:52,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saint_Nicholas_(270-343).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hande_ErçEl.jpg

 91%|█████████ | 8108/8920 [1:57:51<03:27,  3.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arda_Güler.jpg

 91%|█████████ | 8109/8920 [1:57:51<03:17,  4.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willem-Alexander_Of_The_Netherlands.jpg

 91%|█████████ | 8110/8920 [1:57:52<04:34,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Summer_De_Snoo.jpg

 91%|█████████ | 8111/8920 [1:57:52<04:12,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michiel_Huisman.jpg

 91%|█████████ | 8113/8920 [1:57:52<03:39,  3.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jade_Anna_Van_Vliet.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Imaan_Hammam.jpg

 91%|█████████ | 8114/8920 [1:57:53<03:15,  4.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duncan_Laurence.jpg

 91%|█████████ | 8116/8920 [1:57:53<04:04,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Esmee_Joanna.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jan_Pol.jpg

 91%|█████████ | 8118/8920 [1:57:54<03:58,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Famke_Janssen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roxy_Dekker.jpg

 91%|█████████ | 8120/8920 [1:57:54<03:13,  4.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johan_Cruyff_(1947-2016).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yolanda_Hadid.jpg

 91%|█████████ | 8121/8920 [1:57:55<03:16,  4.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rae_Lil_Black.jpg

 91%|█████████ | 8123/8920 [1:57:55<03:06,  4.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Meisjedjamila.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ariana_Elahi.jpg

 91%|█████████ | 8124/8920 [1:57:55<03:13,  4.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malakai_Black.jpg

 91%|█████████ | 8126/8920 [1:57:56<04:04,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dutchtuber.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Kok.jpg

 91%|█████████ | 8127/8920 [1:57:57<03:57,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Buur.jpg

 91%|█████████ | 8128/8920 [1:57:57<03:41,  3.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Silly_On_Roblox.jpg

 91%|█████████ | 8129/8920 [1:57:57<04:42,  2.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sidney_Dunk.jpg

 91%|█████████ | 8131/8920 [1:57:58<04:25,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddie_Van_Halen_(1955-2020).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Virgil_Van_Dijk.jpg

 91%|█████████ | 8133/8920 [1:57:58<03:16,  4.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stan_Browney.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sean_Sotaridona.jpg

 91%|█████████ | 8135/8920 [1:57:59<02:55,  4.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blaza_Plays.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dieuwertje_Blok_(1957-2025).jpg

 91%|█████████ | 8136/8920 [1:57:59<04:28,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Knol.jpg

 91%|█████████ | 8137/8920 [1:58:00<04:16,  3.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooks.jpg

 91%|█████████ | 8139/8920 [1:58:01<06:02,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fundy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Willem_Van_Hanegem.jpg

 91%|█████████▏| 8141/8920 [1:58:02<04:59,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romee_Strijd.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joost_Klein.jpg

 91%|█████████▏| 8143/8920 [1:58:02<03:48,  3.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pangi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hanni_Hanna.jpg

 91%|█████████▏| 8144/8920 [1:58:02<03:20,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Doutzen_Kroes.jpg

 91%|█████████▏| 8146/8920 [1:58:03<02:50,  4.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Van_Gogh_(1853-1890).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yasmin_Wijnaldum.jpg

 91%|█████████▏| 8147/8920 [1:58:03<02:51,  4.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Twan_Kuyper.jpg

 91%|█████████▏| 8148/8920 [1:58:03<03:35,  3.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Garrix.jpg

 91%|█████████▏| 8150/8920 [1:58:04<03:58,  3.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kwebbelkop.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikkie_De_Jager.jpg

 91%|█████████▏| 8152/8920 [1:58:04<03:03,  4.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Clownpierce.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jelly.jpg

 91%|█████████▏| 8153/8920 [1:58:05<02:52,  4.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cindy_Kimberly.jpg

 91%|█████████▏| 8154/8920 [1:58:05<04:48,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aj_Shabeel.jpg

 91%|█████████▏| 8155/8920 [1:58:06<04:10,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sharky.jpg

 91%|█████████▏| 8156/8920 [1:58:06<03:47,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Theoz.jpg

 91%|█████████▏| 8157/8920 [1:58:06<03:25,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Martin.jpg

 91%|█████████▏| 8159/8920 [1:58:07<05:19,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peter_Stormare.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stellan_Skarsgård.jpg

 91%|█████████▏| 8161/8920 [1:58:08<03:38,  3.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ann_Margret.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ecco2K.jpg

 92%|█████████▏| 8163/8920 [1:58:08<02:55,  4.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alicia_Vikander.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Faze_Teeqo.jpg

 92%|█████████▏| 8164/8920 [1:58:08<02:48,  4.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jalal_Amara.jpg

 92%|█████████▏| 8166/8920 [1:58:10<06:33,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reddoons.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hedvig_Sjödin.jpg

 92%|█████████▏| 8168/8920 [1:58:12<08:06,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/William_LöFstedt.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Thomassen.jpg

 92%|█████████▏| 8170/8920 [1:58:13<06:04,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iza_Cryssanthander.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucas_Bergvall.jpg

 92%|█████████▏| 8171/8920 [1:58:15<12:26,  1.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lexie_Levin.jpg

 92%|█████████▏| 8173/8920 [1:58:15<08:00,  1.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dolph_Lundgren.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joel_Kinnaman.jpg

 92%|█████████▏| 8174/8920 [1:58:17<11:11,  1.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anomaly.jpg

 92%|█████████▏| 8176/8920 [1:58:18<07:31,  1.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tobias_Forge.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bianca_Ingrosso.jpg

 92%|█████████▏| 8177/8920 [1:58:18<05:55,  2.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loreen.jpg

 92%|█████████▏| 8179/8920 [1:58:18<04:44,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benny_Andersson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elsa_Hosk.jpg

 92%|█████████▏| 8181/8920 [1:58:19<03:39,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Isak.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Malin_Akerman.jpg

 92%|█████████▏| 8182/8920 [1:58:20<08:06,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexander_Skarsgård.jpg

 92%|█████████▏| 8184/8920 [1:58:21<05:16,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pushpek_Sidhu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tove_Lo.jpg

 92%|█████████▏| 8185/8920 [1:58:21<04:21,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Topala.jpg

 92%|█████████▏| 8186/8920 [1:58:21<04:08,  2.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asta_Bush.jpg

 92%|█████████▏| 8187/8920 [1:58:22<04:24,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rebecca_Ferguson.jpg

 92%|█████████▏| 8189/8920 [1:58:22<03:37,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yung_Lean.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bladee.jpg

 92%|█████████▏| 8191/8920 [1:58:24<05:37,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Edvin_Ryding.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lowe_Asmr.jpg

 92%|█████████▏| 8193/8920 [1:58:24<04:38,  2.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nymn.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roomie.jpg

 92%|█████████▏| 8195/8920 [1:58:25<03:29,  3.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Notch.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zlatan_Ibrahimovic.jpg

 92%|█████████▏| 8197/8920 [1:58:25<02:44,  4.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Skarsgård.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Avicii_(1989-2018).jpg

 92%|█████████▏| 8199/8920 [1:58:26<03:12,  3.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Max_Magnus_Norman.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greta_Thunberg.jpg

 92%|█████████▏| 8201/8920 [1:58:26<02:39,  4.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zara_Larsson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marlon_Lundgren_Garcia.jpg

 92%|█████████▏| 8203/8920 [1:58:26<02:27,  4.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pewdiepie.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frederic_Chopin_(1810-1849).jpg

 92%|█████████▏| 8205/8920 [1:58:27<02:18,  5.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Śmigielska.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrzej_Duda.jpg

 92%|█████████▏| 8207/8920 [1:58:27<02:16,  5.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justyna_Steczkowska.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Blanka_Stajkow.jpg

 92%|█████████▏| 8209/8920 [1:58:29<04:45,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcin_Patrzalek.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roksana_Wegiel.jpg

 92%|█████████▏| 8211/8920 [1:58:29<04:18,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zuzia_Kaszuba.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Queen_K.jpg

 92%|█████████▏| 8212/8920 [1:58:31<09:04,  1.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Lewandowska.jpg

 92%|█████████▏| 8214/8920 [1:58:31<05:33,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Maria_Sieklucka.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Klaudia_Antos.jpg

 92%|█████████▏| 8215/8920 [1:58:32<04:38,  2.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hubert_Twinsstyle.jpg

 92%|█████████▏| 8216/8920 [1:58:32<05:21,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Skyen.jpg

 92%|█████████▏| 8217/8920 [1:58:32<04:31,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wojan.jpg

 92%|█████████▏| 8219/8920 [1:58:33<03:18,  3.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_D._Novak.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tommy_Craze.jpg

 92%|█████████▏| 8220/8920 [1:58:34<05:08,  2.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Speed_Gang.jpg

 92%|█████████▏| 8221/8920 [1:58:34<04:26,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Badgirl_From_Falista.jpg

 92%|█████████▏| 8222/8920 [1:58:34<03:49,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Damian_Chrobak.jpg

 92%|█████████▏| 8224/8920 [1:58:35<03:34,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kacper_Glodek.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iga_Świątek.jpg

 92%|█████████▏| 8225/8920 [1:58:35<03:08,  3.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sara_James.jpg

 92%|█████████▏| 8226/8920 [1:58:35<04:00,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heatzze.jpg

 92%|█████████▏| 8228/8920 [1:58:36<03:10,  3.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Keralis.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arcadius_Kul_(1975-2023).jpg

 92%|█████████▏| 8230/8920 [1:58:36<02:41,  4.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_The_Great_(1729-1796).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zuzanna_Szadkowski.jpg

 92%|█████████▏| 8231/8920 [1:58:36<02:28,  4.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Senpirates.jpg

 92%|█████████▏| 8233/8920 [1:58:37<03:20,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roxxsaurus.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Friz.jpg

 92%|█████████▏| 8234/8920 [1:58:37<02:55,  3.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dagmara_Dominczyk.jpg

 92%|█████████▏| 8235/8920 [1:58:38<02:51,  4.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jerzyk_Smielecki.jpg

 92%|█████████▏| 8236/8920 [1:58:38<02:41,  4.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Freddy_Kurzawa.jpg

 92%|█████████▏| 8238/8920 [1:58:40<05:37,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ewa_Zawada.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeleniewska.jpg

 92%|█████████▏| 8240/8920 [1:58:40<03:42,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Gawin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pope_John_Paul_Ii_(1920-2005).jpg

 92%|█████████▏| 8242/8920 [1:58:40<03:00,  3.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alina_Rose.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maja_Ciesielska.jpg

 92%|█████████▏| 8243/8920 [1:58:40<02:38,  4.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kets4Eki.jpg

 92%|█████████▏| 8245/8920 [1:58:41<02:52,  3.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Oakley.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marie_Curie_(1867-1934).jpg

 92%|█████████▏| 8247/8920 [1:58:43<05:41,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Lewandowski.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jowita_Pryzystal.jpg

 92%|█████████▏| 8249/8920 [1:58:43<04:22,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikki_Pindor.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zuzanna_Borucka.jpg

 92%|█████████▎| 8251/8920 [1:58:44<03:10,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dena_Kaplan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nthaabseng.jpg

 93%|█████████▎| 8253/8920 [1:58:44<02:37,  4.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chané_Grobler.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Byron_Langley.jpg

 93%|█████████▎| 8254/8920 [1:58:44<02:23,  4.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Nash.jpg

 93%|█████████▎| 8256/8920 [1:58:45<02:19,  4.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nasty_C.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Pieters.jpg

 93%|█████████▎| 8258/8920 [1:58:45<02:13,  4.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Domnikov.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jonathan_Clark.jpg

 93%|█████████▎| 8260/8920 [1:58:46<02:20,  4.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sketchy_Bongo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alice_Krige.jpg

 93%|█████████▎| 8262/8920 [1:58:46<02:13,  4.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dezz_Lee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Adhir_Kalyan.jpg

 93%|█████████▎| 8263/8920 [1:58:47<05:34,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aka_(1988-2023).jpg

 93%|█████████▎| 8265/8920 [1:58:48<04:40,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zayaanfour.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Sachiko.jpg

 93%|█████████▎| 8267/8920 [1:58:48<03:11,  3.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cyril_Ramaphosa.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duduzile_Mnisi.jpg

 93%|█████████▎| 8268/8920 [1:58:49<02:52,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Timeless_Tim.jpg

 93%|█████████▎| 8269/8920 [1:58:49<02:48,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noel_Deyzel.jpg

 93%|█████████▎| 8271/8920 [1:58:49<03:09,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oti_Mabuse.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ash_Sewlal.jpg

 93%|█████████▎| 8273/8920 [1:58:50<02:45,  3.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tammin_Sursok.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rendog.jpg

 93%|█████████▎| 8275/8920 [1:58:50<02:16,  4.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thea_Booysen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khanya_Hlubi.jpg

 93%|█████████▎| 8277/8920 [1:58:51<02:10,  4.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cariba_Heine.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ayabonga_Ndhlovu.jpg

 93%|█████████▎| 8279/8920 [1:58:51<02:02,  5.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trevor_Noah.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chloe_Williams.jpg

 93%|█████████▎| 8280/8920 [1:58:51<01:58,  5.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shiv_Sewlal.jpg

 93%|█████████▎| 8282/8920 [1:58:52<02:02,  5.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Motsi_Mabuse.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefan_Benz.jpg

 93%|█████████▎| 8284/8920 [1:58:52<02:19,  4.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charlize_Theron.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thandow.jpg

 93%|█████████▎| 8286/8920 [1:58:53<02:12,  4.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Lombard.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Pieterse.jpg

 93%|█████████▎| 8288/8920 [1:58:53<01:59,  5.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nelson_Mandela_(1918-2013).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriella_Lewitton.jpg

 93%|█████████▎| 8289/8920 [1:58:54<03:31,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Belle_Delphine.jpg

 93%|█████████▎| 8290/8920 [1:58:54<03:14,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sammy_Ndabaga.jpg

 93%|█████████▎| 8291/8920 [1:58:54<02:54,  3.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Troye_Sivan.jpg

 93%|█████████▎| 8293/8920 [1:58:54<02:25,  4.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tyla.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Candice_Swanepoel.jpg

 93%|█████████▎| 8295/8920 [1:58:55<02:15,  4.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jezelle_Catherine.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nara_Smith.jpg

 93%|█████████▎| 8297/8920 [1:58:56<02:51,  3.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elon_Musk.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nikita_Kusuma.jpg

 93%|█████████▎| 8298/8920 [1:58:57<05:12,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luisana_Lopilato.jpg

 93%|█████████▎| 8299/8920 [1:58:57<04:16,  2.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wonhee.jpg

 93%|█████████▎| 8301/8920 [1:58:57<03:02,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kooleen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Bocelli.jpg

 93%|█████████▎| 8302/8920 [1:58:57<02:46,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dagi_Bee.jpg

 93%|█████████▎| 8304/8920 [1:58:58<03:07,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Miller.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Paul.jpg

 93%|█████████▎| 8306/8920 [1:58:59<03:09,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Petras.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tonanreal.jpg

 93%|█████████▎| 8307/8920 [1:58:59<03:08,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arón_Piper.jpg

 93%|█████████▎| 8309/8920 [1:59:00<02:55,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gamerbrother.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noah_Rodriguez.jpg

 93%|█████████▎| 8311/8920 [1:59:00<02:36,  3.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jawed_Karim.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/.Loveme078.jpg

 93%|█████████▎| 8313/8920 [1:59:01<02:54,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bradley_Rittmann.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ailaughatmyownjokes.jpg

 93%|█████████▎| 8314/8920 [1:59:04<12:04,  1.20s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Damien_Haas.jpg

 93%|█████████▎| 8316/8920 [1:59:05<06:52,  1.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Serdar_Bogatekin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nadine_Breaty.jpg

 93%|█████████▎| 8318/8920 [1:59:05<04:46,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lala_Lalaleluu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nils_Kuesel.jpg

 93%|█████████▎| 8319/8920 [1:59:06<05:23,  1.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marianamski.jpg

 93%|█████████▎| 8320/8920 [1:59:06<04:25,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tamera_Mowry.jpg

 93%|█████████▎| 8321/8920 [1:59:06<04:24,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alanna_Lisia_Herbert.jpg

 93%|█████████▎| 8322/8920 [1:59:07<05:10,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wiktoria_Gabor.jpg

 93%|█████████▎| 8323/8920 [1:59:08<05:28,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenan_Yıldız.jpg

 93%|█████████▎| 8325/8920 [1:59:08<04:16,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacob_Rott.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junus.jpg

 93%|█████████▎| 8326/8920 [1:59:09<03:31,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/George_Frideric_Handel_(1685-1759).jpg

 93%|█████████▎| 8328/8920 [1:59:09<02:43,  3.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Martin_Lawrence.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jasmin_Arndt.jpg

 93%|█████████▎| 8330/8920 [1:59:10<03:13,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ludwig_Van_Beethoven_(1770-1827).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jadan.jpg

 93%|█████████▎| 8332/8920 [1:59:11<03:12,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruce_Willis.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kamo.jpg

 93%|█████████▎| 8333/8920 [1:59:11<02:47,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nihachu.jpg

 93%|█████████▎| 8334/8920 [1:59:11<03:13,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rain_Spencer.jpg

 93%|█████████▎| 8336/8920 [1:59:12<02:29,  3.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bill_Kaulitz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lisa_Mantler.jpg

 93%|█████████▎| 8338/8920 [1:59:14<05:15,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lena_Mantler.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tia_Mowry.jpg

 93%|█████████▎| 8340/8920 [1:59:14<03:48,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alinaa.Brss.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Berkibooiii.jpg

 94%|█████████▎| 8342/8920 [1:59:15<04:46,  2.02it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J_Cole.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heidi_Klum.jpg

 94%|█████████▎| 8343/8920 [1:59:16<05:00,  1.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anne_Frank_(1929-1945).jpg

 94%|█████████▎| 8345/8920 [1:59:17<04:07,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Asaliraniii.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Este_Fanija.jpg

 94%|█████████▎| 8347/8920 [1:59:17<02:52,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tom_Kaulitz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Albert_Einstein_(1879-1955).jpg

 94%|█████████▎| 8348/8920 [1:59:18<03:34,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samrosauvage.jpg

 94%|█████████▎| 8350/8920 [1:59:18<02:40,  3.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiara_Calisto.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zahide.jpg

 94%|█████████▎| 8352/8920 [1:59:19<04:09,  2.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michelangelo_(1475-1564).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deva_Cassel.jpg

 94%|█████████▎| 8354/8920 [1:59:20<02:55,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benny_Moschini.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gianluigi_Buffon.jpg

 94%|█████████▎| 8355/8920 [1:59:21<04:34,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benito_Mussolini_(1883-1945).jpg

 94%|█████████▎| 8357/8920 [1:59:21<03:12,  2.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Galileo_Galilei_(1564-1642).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lela_Sohna.jpg

 94%|█████████▎| 8358/8920 [1:59:21<02:43,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fabiola_Baglieri.jpg

 94%|█████████▎| 8359/8920 [1:59:21<02:28,  3.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rose_Mcgowan.jpg

 94%|█████████▎| 8361/8920 [1:59:22<02:05,  4.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guccio_Gucci_(1881-1953).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Loren.jpg

 94%|█████████▎| 8362/8920 [1:59:23<04:56,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessandra_Mele.jpg

 94%|█████████▍| 8363/8920 [1:59:24<04:57,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emiliano_Santoro.jpg

 94%|█████████▍| 8364/8920 [1:59:25<06:52,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florence_Nightingale_(1820-1910).jpg

 94%|█████████▍| 8365/8920 [1:59:25<06:31,  1.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samuel_Tarini.jpg

 94%|█████████▍| 8366/8920 [1:59:26<05:11,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo_Ferrari_(1898-1988).jpg

 94%|█████████▍| 8367/8920 [1:59:26<05:22,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucia_Ferrato.jpg

 94%|█████████▍| 8369/8920 [1:59:27<03:33,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joel_Mchale.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alessio_Scalzotto.jpg

 94%|█████████▍| 8371/8920 [1:59:27<03:03,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Riccardo_Marcuzzo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marco_Polo_(1254-1324).jpg

 94%|█████████▍| 8373/8920 [1:59:28<02:15,  4.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chiara_Ferragni.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Donatella_Versace.jpg

 94%|█████████▍| 8374/8920 [1:59:28<02:00,  4.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanilla_Syndrome.jpg

 94%|█████████▍| 8376/8920 [1:59:28<01:57,  4.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victoria_De_Angelis.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vito_Coppola.jpg

 94%|█████████▍| 8378/8920 [1:59:29<02:22,  3.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Davie504.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jannik_Sinner.jpg

 94%|█████████▍| 8380/8920 [1:59:29<01:57,  4.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maxggs.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Giorgio_Armani_(1934-2025).jpg

 94%|█████████▍| 8381/8920 [1:59:31<05:14,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amy_Adams.jpg

 94%|█████████▍| 8382/8920 [1:59:32<07:09,  1.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julia_Fox.jpg

 94%|█████████▍| 8383/8920 [1:59:32<06:11,  1.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Arru.jpg

 94%|█████████▍| 8384/8920 [1:59:33<05:14,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gio_Scotti.jpg

 94%|█████████▍| 8386/8920 [1:59:34<05:43,  1.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marzia_Kjellberg.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Monica_Bellucci.jpg

 94%|█████████▍| 8388/8920 [1:59:36<05:28,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samuele_Carrino.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Michele_Morrone.jpg

 94%|█████████▍| 8389/8920 [1:59:36<04:18,  2.06it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bruno_Tonioli.jpg

 94%|█████████▍| 8391/8920 [1:59:37<03:19,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christopher_Columbus_(1451-1506).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lorenzo_Zurzolo.jpg

 94%|█████████▍| 8392/8920 [1:59:37<02:51,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Damiano_David.jpg

 94%|█████████▍| 8394/8920 [1:59:38<03:52,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Samara_Tramontana.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Kimi_Antonelli.jpg

 94%|█████████▍| 8395/8920 [1:59:38<03:09,  2.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dylan_Sprouse.jpg

 94%|█████████▍| 8396/8920 [1:59:38<02:44,  3.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leonardo_Da_Vinci_(1452-1519).jpg

 94%|█████████▍| 8397/8920 [1:59:39<02:27,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cole_Sprouse.jpg

 94%|█████████▍| 8399/8920 [1:59:40<03:56,  2.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khamzat_Chimaev.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anton_Yelchin_(1989-2016).jpg

 94%|█████████▍| 8401/8920 [1:59:40<02:52,  3.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vlada_Roslyakova.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mark_Chirkin.jpg

 94%|█████████▍| 8402/8920 [1:59:41<02:26,  3.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sophia_Diamond.jpg

 94%|█████████▍| 8404/8920 [1:59:41<02:13,  3.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vitaly_Zdorovetskiy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danilis_Boom.jpg

 94%|█████████▍| 8405/8920 [1:59:41<01:58,  4.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daria_K.jpg

 94%|█████████▍| 8406/8920 [1:59:42<01:54,  4.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_Kozyreva.jpg

 94%|█████████▍| 8408/8920 [1:59:42<01:45,  4.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arta_Game.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milana_Khametova.jpg

 94%|█████████▍| 8410/8920 [1:59:43<02:26,  3.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Islam_Makhachev.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hasbulla_Magomedov.jpg

 94%|█████████▍| 8412/8920 [1:59:43<01:54,  4.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Betsy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Odnovol.jpg

 94%|█████████▍| 8414/8920 [1:59:44<01:58,  4.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Radion.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kolunya___.jpg

 94%|█████████▍| 8416/8920 [1:59:44<01:44,  4.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Zak.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Taisiya_Chirkina.jpg

 94%|█████████▍| 8417/8920 [1:59:45<04:13,  1.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Elfie.jpg

 94%|█████████▍| 8419/8920 [1:59:46<03:29,  2.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greta_Onieogou.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maria_Yankovskaya.jpg

 94%|█████████▍| 8421/8920 [1:59:46<02:32,  3.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iman_Gadzhi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Classify.jpg

 94%|█████████▍| 8422/8920 [1:59:46<02:17,  3.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sweetfox.jpg

 94%|█████████▍| 8423/8920 [1:59:47<03:02,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sasha_Farber.jpg

 94%|█████████▍| 8425/8920 [1:59:47<02:16,  3.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kvadra.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dasha_Taran.jpg

 94%|█████████▍| 8427/8920 [1:59:48<01:51,  4.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nastya_Tropicelle_(2002-2020).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valeria_Tanashevich.jpg

 94%|█████████▍| 8429/8920 [1:59:48<01:37,  5.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Ignatova.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zedd.jpg

 95%|█████████▍| 8431/8920 [1:59:49<01:32,  5.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Khabib_Nurmagomedov.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diana_Belitskaya.jpg

 95%|█████████▍| 8433/8920 [1:59:49<01:28,  5.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dafuq!?Boom!.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Irina_Shayk.jpg

 95%|█████████▍| 8434/8920 [1:59:49<01:31,  5.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pasha_Pashkov.jpg

 95%|█████████▍| 8436/8920 [1:59:49<01:35,  5.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kristina_Pimenova.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zhong.jpg

 95%|█████████▍| 8437/8920 [1:59:50<01:35,  5.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bridger_Nelson.jpg

 95%|█████████▍| 8438/8920 [1:59:50<01:37,  4.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yana_Chirkina.jpg

 95%|█████████▍| 8439/8920 [1:59:50<02:16,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gleb_Savchenko.jpg

 95%|█████████▍| 8440/8920 [1:59:51<02:54,  2.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liza_Anokhina.jpg

 95%|█████████▍| 8441/8920 [1:59:51<03:25,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dr_Mike.jpg

 95%|█████████▍| 8443/8920 [1:59:52<03:18,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Journee_Nelson.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vladimir_Putin.jpg

 95%|█████████▍| 8444/8920 [1:59:53<02:45,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Like_Nastya.jpg

 95%|█████████▍| 8445/8920 [1:59:53<03:20,  2.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paula_Valbuena.jpg

 95%|█████████▍| 8447/8920 [1:59:54<02:38,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorgina_Kei.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dan_Markham.jpg

 95%|█████████▍| 8448/8920 [1:59:54<02:19,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bongbong_Marcos.jpg

 95%|█████████▍| 8450/8920 [1:59:55<02:31,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chrystiane_Jowy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashley_Garcia.jpg

 95%|█████████▍| 8451/8920 [1:59:55<02:38,  2.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elle_Mills.jpg

 95%|█████████▍| 8452/8920 [1:59:56<03:12,  2.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Neil_Dy.jpg

 95%|█████████▍| 8454/8920 [1:59:56<02:20,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ivana_Alawi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Toni_Fowler.jpg

 95%|█████████▍| 8456/8920 [1:59:58<04:16,  1.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dae_Darlin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charles_Law.jpg

 95%|█████████▍| 8457/8920 [1:59:58<03:28,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Domics.jpg

 95%|█████████▍| 8458/8920 [1:59:58<02:56,  2.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zairayzabelleee.jpg

 95%|█████████▍| 8460/8920 [2:00:00<03:46,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_So.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yaelokre.jpg

 95%|█████████▍| 8461/8920 [2:00:00<03:04,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pinkleaf.jpg

 95%|█████████▍| 8463/8920 [2:00:01<02:46,  2.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Daniel_Padilla.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natalia_Guerrero.jpg

 95%|█████████▍| 8464/8920 [2:00:01<03:09,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jepitot.jpg

 95%|█████████▍| 8465/8920 [2:00:02<04:58,  1.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simply_Misha.jpg

 95%|█████████▍| 8466/8920 [2:00:03<04:01,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vice_Ganda.jpg

 95%|█████████▍| 8468/8920 [2:00:03<03:16,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Regie_Macalino.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manny_Jacinto.jpg

 95%|█████████▍| 8469/8920 [2:00:04<03:37,  2.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kathryn_Bernardo.jpg

 95%|█████████▍| 8470/8920 [2:00:04<03:06,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Innah_Bee.jpg

 95%|█████████▍| 8472/8920 [2:00:05<03:01,  2.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ranz_Kyle.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andrea_Brillantes.jpg

 95%|█████████▌| 8474/8920 [2:00:06<02:43,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coco_Martin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Little_Big_Toys.jpg

 95%|█████████▌| 8476/8920 [2:00:06<02:06,  3.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manny_Pacquiao.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princess_Mae.jpg

 95%|█████████▌| 8477/8920 [2:00:06<01:55,  3.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melvin_Achanzar.jpg

 95%|█████████▌| 8479/8920 [2:00:07<01:39,  4.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Loren.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andres_Muhlach.jpg

 95%|█████████▌| 8480/8920 [2:00:08<02:49,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rabin_Angeles.jpg

 95%|█████████▌| 8481/8920 [2:00:09<04:10,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rachel_In_Wonderland.jpg

 95%|█████████▌| 8483/8920 [2:00:09<02:44,  2.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashtine_Olviga.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niana_Guerrero.jpg

 95%|█████████▌| 8484/8920 [2:00:09<02:21,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kaycee_In_Wonderland.jpg

 95%|█████████▌| 8485/8920 [2:00:10<03:06,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lourd_Asprec.jpg

 95%|█████████▌| 8487/8920 [2:00:10<02:12,  3.28it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aaron_Burriss.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Guava_Juice.jpg

 95%|█████████▌| 8488/8920 [2:00:10<01:54,  3.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bretman_Rock.jpg

 95%|█████████▌| 8490/8920 [2:00:11<01:58,  3.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Beabadoobee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zarathebanana.jpg

 95%|█████████▌| 8492/8920 [2:00:11<01:37,  4.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bella_Poarch.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jiny_Maeng.jpg

 95%|█████████▌| 8493/8920 [2:00:12<01:29,  4.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iu.jpg

 95%|█████████▌| 8495/8920 [2:00:12<01:27,  4.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yun-Jin_Huh.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahyeon.jpg

 95%|█████████▌| 8497/8920 [2:00:12<01:20,  5.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Soo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sung_Hoon.jpg

 95%|█████████▌| 8499/8920 [2:00:13<01:13,  5.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jake_Sim.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeonjun.jpg

 95%|█████████▌| 8501/8920 [2:00:13<01:15,  5.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cha_Eun-Woo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Simji.jpg

 95%|█████████▌| 8503/8920 [2:00:13<01:15,  5.52it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Park_Ji-Hoon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J.Y._Park.jpg

 95%|█████████▌| 8504/8920 [2:00:14<01:17,  5.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rei_Ami.jpg

 95%|█████████▌| 8505/8920 [2:00:16<05:07,  1.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/G_Dragon.jpg

 95%|█████████▌| 8507/8920 [2:00:16<03:45,  1.83it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Jin-Woo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nayeon.jpg

 95%|█████████▌| 8508/8920 [2:00:17<03:30,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunoo.jpg

 95%|█████████▌| 8510/8920 [2:00:20<07:00,  1.02s/it]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Byung-Hun.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yim_Si-Wan.jpg

 95%|█████████▌| 8512/8920 [2:00:21<04:03,  1.67it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Moon_Bin_(1998-2023).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Won-Young_Jang.jpg

 95%|█████████▌| 8514/8920 [2:00:22<03:38,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jungwon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sulli_(1994-2019).jpg

 95%|█████████▌| 8516/8920 [2:00:23<03:12,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sung-Hoon_Park.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jin.jpg

 95%|█████████▌| 8518/8920 [2:00:23<02:06,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roh_Jaewon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Jung-Jae.jpg

 96%|█████████▌| 8520/8920 [2:00:25<03:44,  1.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Eun-Jae.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Han_Jisung.jpg

 96%|█████████▌| 8521/8920 [2:00:25<02:56,  2.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/J-Hope.jpg

 96%|█████████▌| 8522/8920 [2:00:27<04:52,  1.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Suga.jpg

 96%|█████████▌| 8523/8920 [2:00:28<05:50,  1.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jo_Yuri.jpg

 96%|█████████▌| 8525/8920 [2:00:28<03:31,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/T.O.P.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rm.jpg

 96%|█████████▌| 8526/8920 [2:00:29<03:36,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heeseung.jpg

 96%|█████████▌| 8527/8920 [2:00:29<03:39,  1.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Changbin.jpg

 96%|█████████▌| 8528/8920 [2:00:31<04:54,  1.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hyunjin.jpg

 96%|█████████▌| 8529/8920 [2:00:31<03:49,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/I.N.jpg

 96%|█████████▌| 8531/8920 [2:00:31<02:27,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Seungmin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jennie_Kim.jpg

 96%|█████████▌| 8533/8920 [2:00:32<01:43,  3.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Taehyung.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jimin.jpg

 96%|█████████▌| 8535/8920 [2:00:32<01:21,  4.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lee_Know.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jisoo.jpg

 96%|█████████▌| 8536/8920 [2:00:34<04:26,  1.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jungkook.jpg

 96%|█████████▌| 8538/8920 [2:00:34<03:11,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bang_Chan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoonchae_Jeong.jpg

 96%|█████████▌| 8540/8920 [2:00:35<02:21,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benjamín_Rojas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_Pablo_Di_Pace.jpg

 96%|█████████▌| 8542/8920 [2:00:36<02:07,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lyna_Vallejos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lali_Espósito.jpg

 96%|█████████▌| 8543/8920 [2:00:36<01:47,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/María_Becerra.jpg

 96%|█████████▌| 8544/8920 [2:00:37<03:32,  1.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mernuel.jpg

 96%|█████████▌| 8545/8920 [2:00:37<03:19,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Augusto_Giménez.jpg

 96%|█████████▌| 8546/8920 [2:00:38<02:46,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/K1Ng.jpg

 96%|█████████▌| 8548/8920 [2:00:38<01:56,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cazzu.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sebastián_Rulli.jpg

 96%|█████████▌| 8549/8920 [2:00:38<01:40,  3.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Julián_Álvarez.jpg

 96%|█████████▌| 8551/8920 [2:00:40<02:44,  2.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greberte.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/El_Purre.jpg

 96%|█████████▌| 8553/8920 [2:00:40<01:56,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ian_Lucas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejo_Igoa.jpg

 96%|█████████▌| 8555/8920 [2:00:41<01:54,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Agüero.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentina_Zenere.jpg

 96%|█████████▌| 8556/8920 [2:00:41<02:47,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ángel_Di_María.jpg

 96%|█████████▌| 8558/8920 [2:00:42<01:56,  3.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rodrigo_Carrera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Trueno.jpg

 96%|█████████▌| 8559/8920 [2:00:42<01:42,  3.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Micah_Palace.jpg

 96%|█████████▌| 8560/8920 [2:00:43<02:04,  2.90it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robleisiutu.jpg

 96%|█████████▌| 8562/8920 [2:00:43<02:07,  2.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonela_Roccuzzo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Duki.jpg

 96%|█████████▌| 8563/8920 [2:00:44<01:46,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mikaela_Lafuente.jpg

 96%|█████████▌| 8564/8920 [2:00:44<01:54,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Franco_Alejandro_Colapinto.jpg

 96%|█████████▌| 8565/8920 [2:00:44<01:44,  3.39it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pili_Pascual.jpg

 96%|█████████▌| 8566/8920 [2:00:44<01:35,  3.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Olivia_Hussey_(1951-2024).jpg

 96%|█████████▌| 8567/8920 [2:00:45<01:27,  4.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valentin_Lopez.jpg

 96%|█████████▌| 8568/8920 [2:00:45<01:23,  4.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aylen_Park.jpg

 96%|█████████▌| 8569/8920 [2:00:45<01:57,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paulo_Dybala.jpg

 96%|█████████▌| 8571/8920 [2:00:46<01:28,  3.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ángel_Gastón_Díaz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vector.jpg

 96%|█████████▌| 8572/8920 [2:00:46<01:21,  4.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emilia_Mernes.jpg

 96%|█████████▌| 8573/8920 [2:00:46<01:18,  4.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spreen.jpg

 96%|█████████▌| 8575/8920 [2:00:46<01:09,  4.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Maru_Lee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Milo_J.jpg

 96%|█████████▌| 8577/8920 [2:00:47<01:06,  5.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Beatriz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fede_Dorcaz_(1996-2025).jpg

 96%|█████████▌| 8579/8920 [2:00:47<01:07,  5.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/María_Sol_Mendoza.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diego_Maradona_(1960-2020).jpg

 96%|█████████▌| 8580/8920 [2:00:47<01:03,  5.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tini.jpg

 96%|█████████▌| 8581/8920 [2:00:49<02:50,  1.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yamal.jpg

 96%|█████████▌| 8582/8920 [2:00:49<02:19,  2.41it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pope_Francis_(1936-2025).jpg

 96%|█████████▌| 8583/8920 [2:00:49<02:33,  2.19it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicki_Nicole.jpg

 96%|█████████▌| 8585/8920 [2:00:50<01:47,  3.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Georgina_Rodríguez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lionel_Messi.jpg

 96%|█████████▋| 8587/8920 [2:00:50<01:21,  4.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jess_No_Limit.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yoshi_Sudarso.jpg

 96%|█████████▋| 8589/8920 [2:00:51<01:14,  4.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurensia_Ineke.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yama_Carlos.jpg

 96%|█████████▋| 8591/8920 [2:00:51<01:05,  5.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dochi_Sadega.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iko_Uwais.jpg

 96%|█████████▋| 8593/8920 [2:00:51<01:02,  5.27it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fattah_Syach.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kitsunee.jpg

 96%|█████████▋| 8594/8920 [2:00:51<01:01,  5.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ardell_Aryana.jpg

 96%|█████████▋| 8596/8920 [2:00:52<01:05,  4.92it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naura.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sachi_Tenripada.jpg

 96%|█████████▋| 8597/8920 [2:00:52<01:03,  5.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Raffi_Ahmad.jpg

 96%|█████████▋| 8598/8920 [2:00:53<01:39,  3.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Riana_Antoinette.jpg

 96%|█████████▋| 8599/8920 [2:00:54<02:45,  1.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Wanda_Hamidah.jpg

 96%|█████████▋| 8600/8920 [2:00:54<02:19,  2.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kim_Thai.jpg

 96%|█████████▋| 8601/8920 [2:00:55<03:34,  1.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ridersuru.jpg

 96%|█████████▋| 8602/8920 [2:00:55<02:50,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agnez_Mo.jpg

 96%|█████████▋| 8603/8920 [2:00:56<02:52,  1.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alsa_Aqilah.jpg

 96%|█████████▋| 8604/8920 [2:00:56<02:22,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Windah_Basudara.jpg

 96%|█████████▋| 8605/8920 [2:00:57<02:34,  2.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niki_Zefanya.jpg

 96%|█████████▋| 8606/8920 [2:00:57<02:20,  2.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Florie.jpg

 96%|█████████▋| 8607/8920 [2:00:57<02:00,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shion.jpg

 97%|█████████▋| 8608/8920 [2:00:58<01:54,  2.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Danilla_Riyadi.jpg

 97%|█████████▋| 8609/8920 [2:00:59<03:14,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tenxi.jpg

 97%|█████████▋| 8610/8920 [2:00:59<02:38,  1.96it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ria_Ricis.jpg

 97%|█████████▋| 8611/8920 [2:01:00<02:43,  1.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shania_Yan.jpg

 97%|█████████▋| 8612/8920 [2:01:00<02:18,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stephanie_Poetri.jpg

 97%|█████████▋| 8613/8920 [2:01:00<02:23,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joe_Taslim.jpg

 97%|█████████▋| 8614/8920 [2:01:01<02:32,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Leonardo.jpg

 97%|█████████▋| 8615/8920 [2:01:01<02:11,  2.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miawaug.jpg

 97%|█████████▋| 8617/8920 [2:01:02<01:35,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mbah_Gotho_(1870-2017).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nurhayati.jpg

 97%|█████████▋| 8618/8920 [2:01:03<02:55,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joko_Widodo.jpg

 97%|█████████▋| 8620/8920 [2:01:03<01:55,  2.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bulgogifartsalot.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prabowo_Subianto.jpg

 97%|█████████▋| 8622/8920 [2:01:04<01:22,  3.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Santos_Prayoza.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zahra_Faiha.jpg

 97%|█████████▋| 8623/8920 [2:01:04<01:29,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Sin.jpg

 97%|█████████▋| 8625/8920 [2:01:05<01:35,  3.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Valerie_Mahaffey_(1953-2025).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jazmine_Tan.jpg

 97%|█████████▋| 8626/8920 [2:01:05<01:22,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stefano_Malachi.jpg

 97%|█████████▋| 8628/8920 [2:01:07<02:37,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jaden_Bahtera.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Attamimi_Halilintar.jpg

 97%|█████████▋| 8629/8920 [2:01:07<02:05,  2.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jason_Susanto.jpg

 97%|█████████▋| 8630/8920 [2:01:07<02:04,  2.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rich_Brian.jpg

 97%|█████████▋| 8632/8920 [2:01:08<01:30,  3.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Baby_Glow.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reza_Oktovian.jpg

 97%|█████████▋| 8633/8920 [2:01:08<01:46,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kevin_Langue.jpg

 97%|█████████▋| 8635/8920 [2:01:09<01:49,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Esile.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Márquez.jpg

 97%|█████████▋| 8637/8920 [2:01:10<01:17,  3.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kyrie_Irving.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Natanael_Cano.jpg

 97%|█████████▋| 8638/8920 [2:01:10<01:10,  4.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mythpat.jpg

 97%|█████████▋| 8639/8920 [2:01:11<02:29,  1.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Laurdiy.jpg

 97%|█████████▋| 8641/8920 [2:01:11<01:40,  2.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Greyson_Pumple.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Melissa_O'Neil.jpg

 97%|█████████▋| 8643/8920 [2:01:12<01:11,  3.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Stromedy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mackenzie_Turner.jpg

 97%|█████████▋| 8645/8920 [2:01:12<00:58,  4.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Gosling.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Azzyland.jpg

 97%|█████████▋| 8646/8920 [2:01:12<00:59,  4.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thatmartinkid.jpg

 97%|█████████▋| 8647/8920 [2:01:13<01:22,  3.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gloom.jpg

 97%|█████████▋| 8649/8920 [2:01:13<01:23,  3.26it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriela_Bee.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Spencer_Barbosa.jpg

 97%|█████████▋| 8651/8920 [2:01:14<01:14,  3.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bbno$.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jim_Carrey.jpg

 97%|█████████▋| 8653/8920 [2:01:14<01:03,  4.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kio_Cyr.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Baszucki.jpg

 97%|█████████▋| 8654/8920 [2:01:16<02:49,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cassiesbooktok.jpg

 97%|█████████▋| 8655/8920 [2:01:17<03:35,  1.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kris_Collins.jpg

 97%|█████████▋| 8656/8920 [2:01:17<02:48,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Auntie_Charli.jpg

 97%|█████████▋| 8658/8920 [2:01:18<02:08,  2.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Agent_00.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Avril_Lavigne.jpg

 97%|█████████▋| 8659/8920 [2:01:18<01:41,  2.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cynthia_Parker.jpg

 97%|█████████▋| 8661/8920 [2:01:19<01:17,  3.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mangopull.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anas_Marwah.jpg

 97%|█████████▋| 8663/8920 [2:01:19<01:03,  4.08it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kreative_Kyle.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lilly_Singh.jpg

 97%|█████████▋| 8664/8920 [2:01:19<00:56,  4.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Itsfunneh.jpg

 97%|█████████▋| 8665/8920 [2:01:20<02:11,  1.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mila_Marwah.jpg

 97%|█████████▋| 8666/8920 [2:01:22<03:38,  1.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_Paiz.jpg

 97%|█████████▋| 8668/8920 [2:01:23<02:16,  1.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Benoftheweek.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ryan_Reynolds.jpg

 97%|█████████▋| 8669/8920 [2:01:23<01:48,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Johnny_Orlando.jpg

 97%|█████████▋| 8670/8920 [2:01:23<01:58,  2.11it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cali_Rush.jpg

 97%|█████████▋| 8671/8920 [2:01:24<01:41,  2.46it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vanilbean.jpg

 97%|█████████▋| 8672/8920 [2:01:25<02:41,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_Kurzawa.jpg

 97%|█████████▋| 8673/8920 [2:01:25<02:12,  1.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Weeknd.jpg

 97%|█████████▋| 8674/8920 [2:01:25<01:47,  2.30it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Josh_Richards.jpg

 97%|█████████▋| 8676/8920 [2:01:26<01:15,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Finn_Wolfhard.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ronaldomg.jpg

 97%|█████████▋| 8677/8920 [2:01:26<01:06,  3.64it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kane_Bailey.jpg

 97%|█████████▋| 8679/8920 [2:01:27<01:12,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anna_Mcnulty.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shawn_Mendes.jpg

 97%|█████████▋| 8680/8920 [2:01:27<01:29,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Noah_Risling.jpg

 97%|█████████▋| 8681/8920 [2:01:28<02:27,  1.62it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tate_Mcrae.jpg

 97%|█████████▋| 8683/8920 [2:01:29<01:33,  2.54it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Drake.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sunday_Kalogeras.jpg

 97%|█████████▋| 8685/8920 [2:01:29<01:07,  3.50it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Demitra_Mia_Kalogeras.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eliana_Kalogeras.jpg

 97%|█████████▋| 8686/8920 [2:01:29<00:58,  4.01it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Justin_Bieber.jpg

 97%|█████████▋| 8688/8920 [2:01:30<01:03,  3.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ananya_Panday.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Saif_Ali_Khan.jpg

 97%|█████████▋| 8690/8920 [2:01:30<00:52,  4.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Siddhant_Srinandan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ahaan_Panday.jpg

 97%|█████████▋| 8691/8920 [2:01:30<00:50,  4.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kiara_Advani.jpg

 97%|█████████▋| 8692/8920 [2:01:31<00:49,  4.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tiger_Shroff.jpg

 97%|█████████▋| 8693/8920 [2:01:32<01:35,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rajinikanth.jpg

 97%|█████████▋| 8695/8920 [2:01:32<01:07,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ujjwal_Chaurasia.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Great_Khali.jpg

 98%|█████████▊| 8697/8920 [2:01:33<01:17,  2.87it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bhushan_Kumar.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shraddha_Kapoor.jpg

 98%|█████████▊| 8698/8920 [2:01:33<01:06,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ms_Dhoni.jpg

 98%|█████████▊| 8700/8920 [2:01:34<01:41,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Varun_Dhawan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ajey_Nagar.jpg

 98%|█████████▊| 8701/8920 [2:01:35<01:20,  2.71it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aamir_Khan.jpg

 98%|█████████▊| 8703/8920 [2:01:36<01:46,  2.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kajol.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ranbir_Kapoor.jpg

 98%|█████████▊| 8705/8920 [2:01:36<01:14,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Akshay_Kumar.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vijay_Chandrasekhar.jpg

 98%|█████████▊| 8706/8920 [2:01:37<01:12,  2.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karan_Aujla.jpg

 98%|█████████▊| 8708/8920 [2:01:37<00:56,  3.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mohanlal.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sidhu_Moose_Wala_(1993-2022).jpg

 98%|█████████▊| 8709/8920 [2:01:38<01:13,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Primz.jpg

 98%|█████████▊| 8710/8920 [2:01:38<01:04,  3.25it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Realrosa.jpg

 98%|█████████▊| 8711/8920 [2:01:39<02:01,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niki_Mahajan.jpg

 98%|█████████▊| 8713/8920 [2:01:40<02:03,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Amitabh_Bachchan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rajvir_Jawanda_(1990-2025).jpg

 98%|█████████▊| 8714/8920 [2:01:41<01:59,  1.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kareena_Kapoor.jpg

 98%|█████████▊| 8715/8920 [2:01:41<01:36,  2.13it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Arasha_Lalani.jpg

 98%|█████████▊| 8717/8920 [2:01:42<01:08,  2.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ashswag.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Narendra_Modi.jpg

 98%|█████████▊| 8718/8920 [2:01:42<01:00,  3.36it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aishwarya_Rai_Bachchan.jpg

 98%|█████████▊| 8719/8920 [2:01:42<01:14,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aayu_Kalra.jpg

 98%|█████████▊| 8721/8920 [2:01:43<01:09,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hrithik_Roshan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Triggered_Insaan.jpg

 98%|█████████▊| 8722/8920 [2:01:43<00:59,  3.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diljit_Dosanjh.jpg

 98%|█████████▊| 8724/8920 [2:01:44<00:52,  3.74it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pihu_Kalra.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mahatma_Gandhi_(1869-1948).jpg

 98%|█████████▊| 8726/8920 [2:01:44<00:43,  4.47it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alia_Bhatt.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Krutika_Themermaidscale.jpg

 98%|█████████▊| 8728/8920 [2:01:45<00:46,  4.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kk_(1968-2022).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jyoti_Amge.jpg

 98%|█████████▊| 8730/8920 [2:01:45<00:43,  4.33it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salman_Khan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Virat_Kohli.jpg

 98%|█████████▊| 8731/8920 [2:01:46<00:58,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Priyanka_Chopra.jpg

 98%|█████████▊| 8733/8920 [2:01:46<01:02,  2.98it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Shah_Rukh_Khan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dhar_Mann.jpg

 98%|█████████▊| 8735/8920 [2:01:47<00:45,  4.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lupita_Nyong'O.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iñaki_Godoy.jpg

 98%|█████████▊| 8736/8920 [2:01:47<00:40,  4.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sexy_Star.jpg

 98%|█████████▊| 8737/8920 [2:01:48<01:21,  2.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eiza_González.jpg

 98%|█████████▊| 8739/8920 [2:01:48<00:57,  3.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karla_Bustillos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ana_Emilia.jpg

 98%|█████████▊| 8741/8920 [2:01:49<00:46,  3.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miku.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diosdado_Juarez.jpg

 98%|█████████▊| 8742/8920 [2:01:49<00:40,  4.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yeri_Mua.jpg

 98%|█████████▊| 8744/8920 [2:01:49<00:44,  3.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernanda_Duran.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dafnne_Jm.jpg

 98%|█████████▊| 8746/8920 [2:01:50<00:37,  4.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eugenio_Derbez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lara_Campos.jpg

 98%|█████████▊| 8747/8920 [2:01:50<00:36,  4.77it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soyjessi.jpg

 98%|█████████▊| 8748/8920 [2:01:51<00:53,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marcos_Villalobos.jpg

 98%|█████████▊| 8750/8920 [2:01:51<00:42,  4.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexa_Rivera_Villegas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jesús_Ortiz-Paz.jpg

 98%|█████████▊| 8751/8920 [2:01:52<00:58,  2.91it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kenia_Os.jpg

 98%|█████████▊| 8752/8920 [2:01:52<00:51,  3.24it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Domelipa.jpg

 98%|█████████▊| 8753/8920 [2:01:52<00:48,  3.45it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cesar_Pantoja.jpg

 98%|█████████▊| 8755/8920 [2:01:53<01:15,  2.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marisela_Cantú.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juan_De_Dios_Pantoja.jpg

 98%|█████████▊| 8757/8920 [2:01:55<01:17,  2.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karol_Sevilla.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anahi_Rios.jpg

 98%|█████████▊| 8759/8920 [2:01:55<00:50,  3.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gia_Lover.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Linette_Rodriguez.jpg

 98%|█████████▊| 8761/8920 [2:01:55<00:40,  3.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Niño_Gucci.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lumi_Athena.jpg

 98%|█████████▊| 8762/8920 [2:01:55<00:38,  4.15it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Frida_Kahlo_(1907-1954).jpg

 98%|█████████▊| 8763/8920 [2:01:56<01:07,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Christian_Nodal.jpg

 98%|█████████▊| 8764/8920 [2:01:57<01:00,  2.58it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Soy_Pau.jpg

 98%|█████████▊| 8766/8920 [2:01:57<00:57,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elasticdroid.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Roberto_Laija.jpg

 98%|█████████▊| 8767/8920 [2:01:58<00:47,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alan_Arrieta.jpg

 98%|█████████▊| 8769/8920 [2:01:58<00:48,  3.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carol_Castro.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Salma_Hayek.jpg

 98%|█████████▊| 8770/8920 [2:02:00<01:26,  1.73it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Saint_Mleux.jpg

 98%|█████████▊| 8771/8920 [2:02:00<01:10,  2.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Junior_H.jpg

 98%|█████████▊| 8773/8920 [2:02:00<00:47,  3.09it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabrina_Quesada.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Canelo_Álvarez.jpg

 98%|█████████▊| 8774/8920 [2:02:00<00:45,  3.23it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Juanpa_Zurita.jpg

 98%|█████████▊| 8775/8920 [2:02:02<01:22,  1.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eddievr.jpg

 98%|█████████▊| 8777/8920 [2:02:03<01:24,  1.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kimberly_Loaiza.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Juarez.jpg

 98%|█████████▊| 8778/8920 [2:02:03<01:05,  2.16it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Elsarca.jpg

 98%|█████████▊| 8780/8920 [2:02:04<00:46,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Peso_Pluma.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Quackity.jpg

 98%|█████████▊| 8782/8920 [2:02:04<00:53,  2.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Phoebe_Tonkin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Caleb_Finn.jpg

 98%|█████████▊| 8783/8920 [2:02:05<00:45,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alexandra_Marasigan.jpg

 98%|█████████▊| 8784/8920 [2:02:05<00:57,  2.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hannah_Bahng.jpg

 98%|█████████▊| 8786/8920 [2:02:06<00:44,  3.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ruby_Rose.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Reece_Walsh.jpg

 99%|█████████▊| 8788/8920 [2:02:06<00:34,  3.80it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Liam_Hemsworth.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Conrad_Fisher.jpg

 99%|█████████▊| 8789/8920 [2:02:07<00:52,  2.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mia_Van_Haarlem.jpg

 99%|█████████▊| 8791/8920 [2:02:07<00:40,  3.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Luke_Hemmings.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Oscar_Piastri.jpg

 99%|█████████▊| 8792/8920 [2:02:08<00:34,  3.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diesel_La_Torraca.jpg

 99%|█████████▊| 8794/8920 [2:02:08<00:35,  3.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Steve_Irwin_(1962-2006).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Llxllie.jpg

 99%|█████████▊| 8796/8920 [2:02:09<00:28,  4.42it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bindi_Irwin.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bridey_Drake.jpg

 99%|█████████▊| 8798/8920 [2:02:09<00:25,  4.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Latisha_Clark.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Grace_Mulgrew.jpg

 99%|█████████▊| 8800/8920 [2:02:10<00:35,  3.38it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Indiana_Massara.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cadel__06.jpg

 99%|█████████▊| 8801/8920 [2:02:10<00:39,  3.03it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Hugh_Jackman.jpg

 99%|█████████▊| 8803/8920 [2:02:11<00:30,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Vincent_Nguy.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iggy_Azalea.jpg

 99%|█████████▊| 8804/8920 [2:02:11<00:39,  2.93it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Disco_Norris.jpg

 99%|█████████▊| 8806/8920 [2:02:12<00:30,  3.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lazarbeam.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Charm_Norris.jpg

 99%|█████████▊| 8807/8920 [2:02:12<00:32,  3.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Heath_Ledger_(1979-2008).jpg

 99%|█████████▊| 8808/8920 [2:02:12<00:29,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Margot_Robbie.jpg

 99%|█████████▉| 8810/8920 [2:02:13<00:32,  3.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sia.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jacob_Elordi.jpg

 99%|█████████▉| 8812/8920 [2:02:14<00:35,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Chris_Hemsworth.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/The_Kid_Laroi.jpg

 99%|█████████▉| 8813/8920 [2:02:14<00:30,  3.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leah_Halton.jpg

 99%|█████████▉| 8815/8920 [2:02:14<00:24,  4.32it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelo_Marasigan.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alaska_Violet.jpg

 99%|█████████▉| 8816/8920 [2:02:14<00:23,  4.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rhea_Ripley.jpg

 99%|█████████▉| 8817/8920 [2:02:15<00:34,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kat_Zoe_Clark.jpg

 99%|█████████▉| 8819/8920 [2:02:15<00:26,  3.78it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Miss_Charli.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Owen1Dk.jpg

 99%|█████████▉| 8820/8920 [2:02:16<00:23,  4.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Felix_Yongbok_Lee.jpg

 99%|█████████▉| 8821/8920 [2:02:17<01:04,  1.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Brooke_Norris.jpg

 99%|█████████▉| 8823/8920 [2:02:18<00:41,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sockie_Norris.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sabre_Norris.jpg

 99%|█████████▉| 8824/8920 [2:02:18<00:33,  2.88it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Robert_Irwin.jpg

 99%|█████████▉| 8825/8920 [2:02:18<00:35,  2.66it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Naz_Norris.jpg

 99%|█████████▉| 8826/8920 [2:02:18<00:31,  3.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Biggy_Norris.jpg

 99%|█████████▉| 8828/8920 [2:02:19<00:23,  3.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Deja_Clark.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ibai_Llanos.jpg

 99%|█████████▉| 8829/8920 [2:02:20<00:38,  2.37it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Princesa_Leonor.jpg

 99%|█████████▉| 8830/8920 [2:02:20<00:33,  2.69it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ester_Expósito.jpg

 99%|█████████▉| 8832/8920 [2:02:20<00:24,  3.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rafael_Nadal.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Apolo_Ribera.jpg

 99%|█████████▉| 8833/8920 [2:02:22<00:54,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lola_Lolita.jpg

 99%|█████████▉| 8834/8920 [2:02:22<00:44,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pau_Cubarsí_Paredes.jpg

 99%|█████████▉| 8835/8920 [2:02:23<01:00,  1.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Mateo_Messi.jpg

 99%|█████████▉| 8836/8920 [2:02:24<01:13,  1.14it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dafne_Keen.jpg

 99%|█████████▉| 8837/8920 [2:02:25<00:56,  1.48it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Alcaraz.jpg

 99%|█████████▉| 8838/8920 [2:02:25<00:51,  1.60it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bb_Trickz.jpg

 99%|█████████▉| 8839/8920 [2:02:26<00:50,  1.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pablo_Picasso_(1881-1973).jpg

 99%|█████████▉| 8841/8920 [2:02:26<00:31,  2.49it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Padilla.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alejandro_Garnacho.jpg

 99%|█████████▉| 8843/8920 [2:02:27<00:25,  3.05it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rubius.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sergio_Ramos.jpg

 99%|█████████▉| 8844/8920 [2:02:27<00:21,  3.59it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Yera_Fontes.jpg

 99%|█████████▉| 8846/8920 [2:02:27<00:16,  4.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Penélope_Cruz.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gara.jpg

 99%|█████████▉| 8848/8920 [2:02:28<00:13,  5.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karina_&_Marina.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marc_Bosch.jpg

 99%|█████████▉| 8850/8920 [2:02:28<00:12,  5.44it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Catherine_Of_Aragon_(1485-1536).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Señor_Zeta.jpg

 99%|█████████▉| 8851/8920 [2:02:28<00:13,  5.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Manu_Ríos.jpg

 99%|█████████▉| 8852/8920 [2:02:29<00:34,  1.95it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enrique_Iglesias.jpg

 99%|█████████▉| 8854/8920 [2:02:31<00:42,  1.57it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andreina_Santos.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Aria_Kurzawa.jpg

 99%|█████████▉| 8855/8920 [2:02:31<00:32,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Fernando_Alonso.jpg

 99%|█████████▉| 8856/8920 [2:02:32<00:26,  2.40it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Annersite.jpg

 99%|█████████▉| 8858/8920 [2:02:32<00:22,  2.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Antonio_Banderas.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pedri.jpg

 99%|█████████▉| 8859/8920 [2:02:32<00:20,  2.99it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jorge_Garay.jpg

 99%|█████████▉| 8861/8920 [2:02:33<00:15,  3.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Rosalía.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carmen_Sánchez.jpg

 99%|█████████▉| 8863/8920 [2:02:33<00:13,  4.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Cruz_Beckham.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Carlos_Sainz_Jr..jpg

 99%|█████████▉| 8865/8920 [2:02:34<00:10,  5.04it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gavi.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Tatiana_Kaer.jpg

 99%|█████████▉| 8866/8920 [2:02:34<00:11,  4.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Iván_Martínez.jpg

 99%|█████████▉| 8868/8920 [2:02:35<00:15,  3.35it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emilio_Martínez.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Héctor_Fort.jpg

 99%|█████████▉| 8869/8920 [2:02:35<00:19,  2.63it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marta_Díaz.jpg

 99%|█████████▉| 8870/8920 [2:02:36<00:31,  1.61it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thiago_Messi.jpg

 99%|█████████▉| 8871/8920 [2:02:37<00:24,  1.97it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Gabriel_Guevara.jpg

 99%|█████████▉| 8872/8920 [2:02:37<00:24,  2.00it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Nicole_Wallace.jpg

 99%|█████████▉| 8873/8920 [2:02:38<00:28,  1.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lamine_Yamal.jpg

 99%|█████████▉| 8875/8920 [2:02:38<00:17,  2.55it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Millie_Bobby_Brown.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Anyme023.jpg

100%|█████████▉| 8877/8920 [2:02:39<00:12,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Esteban_Ocon.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Thierry_Henry.jpg

100%|█████████▉| 8878/8920 [2:02:39<00:10,  3.85it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Prime.jpg

100%|█████████▉| 8880/8920 [2:02:40<00:11,  3.51it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Angelique_Boyer.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Loli_Bahia.jpg

100%|█████████▉| 8881/8920 [2:02:40<00:10,  3.84it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Leny_Dpt.jpg

100%|█████████▉| 8883/8920 [2:02:40<00:08,  4.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Eva_Green.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Louis_Vuitton_(1821-1892).jpg

100%|█████████▉| 8884/8920 [2:02:40<00:07,  4.81it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Désiré_Doué.jpg

100%|█████████▉| 8885/8920 [2:02:41<00:08,  4.12it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Zinedine_Zidane.jpg

100%|█████████▉| 8886/8920 [2:02:41<00:10,  3.31it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Squeezie.jpg

100%|█████████▉| 8887/8920 [2:02:42<00:12,  2.68it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Indila.jpg

100%|█████████▉| 8889/8920 [2:02:42<00:08,  3.65it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Enzo.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bakary_Sako.jpg

100%|█████████▉| 8891/8920 [2:02:42<00:06,  4.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kido.Aep.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Sinetmatteo.jpg

100%|█████████▉| 8892/8920 [2:02:43<00:05,  4.79it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Gasly.jpg

100%|█████████▉| 8894/8920 [2:02:43<00:06,  3.94it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ousmane_Dembele.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Karim_Benzema.jpg

100%|█████████▉| 8896/8920 [2:02:44<00:05,  4.53it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lucas_Coly_(1997-2024).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Codyurbex.jpg

100%|█████████▉| 8897/8920 [2:02:44<00:04,  4.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Ricardo_Juliano.jpg

100%|█████████▉| 8898/8920 [2:02:44<00:04,  4.70it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Andre_The_Giant_(1946-1993).jpg

100%|█████████▉| 8899/8920 [2:02:44<00:04,  4.76it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Dj_Snake.jpg

100%|█████████▉| 8900/8920 [2:02:45<00:06,  3.17it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Victor_Wembanyama.jpg

100%|█████████▉| 8901/8920 [2:02:45<00:06,  3.10it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Paul_Pogba.jpg

100%|█████████▉| 8903/8920 [2:02:46<00:07,  2.34it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Coco_Chanel_(1883-1971).jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/David_Guetta.jpg

100%|█████████▉| 8904/8920 [2:02:46<00:05,  2.86it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Isack_Hadjar.jpg

100%|█████████▉| 8906/8920 [2:02:47<00:04,  3.07it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/0Zuottag.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marie_Stella.jpg

100%|█████████▉| 8907/8920 [2:02:47<00:03,  3.43it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Joan_Of_Arc_(1412-1431).jpg

100%|█████████▉| 8908/8920 [2:02:49<00:06,  1.75it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Napoleon_Bonaparte_(1769-1821).jpg

100%|█████████▉| 8909/8920 [2:02:49<00:06,  1.82it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Marquis_De_Lafayette_(1757-1834).jpg

100%|█████████▉| 8910/8920 [2:02:49<00:04,  2.22it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Alex_Lange.jpg

100%|█████████▉| 8912/8920 [2:02:50<00:02,  3.20it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Romy_Mars.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Jeanne_Calment_(1875-1997).jpg

100%|█████████▉| 8914/8920 [2:02:50<00:01,  4.18it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Bachbuquen.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Pierre_Boo.jpg

100%|█████████▉| 8915/8920 [2:02:51<00:01,  2.89it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Diamant_Blazi.jpg

100%|█████████▉| 8916/8920 [2:02:51<00:01,  3.29it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lea_Elui_Ginet.jpg

100%|█████████▉| 8918/8920 [2:02:51<00:00,  3.56it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lily-Rose_Depp.jpg
✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Kylian_Mbappé.jpg

100%|█████████▉| 8919/8920 [2:02:52<00:00,  2.72it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Lev_Cameron.jpg

100%|██████████| 8920/8920 [2:02:53<00:00,  1.21it/s]

✅ Downloaded: /home/octoopt/workspace/projects/personal/data_enrichment/data/images/20252210_mrgdprf/Emma_Watson.jpg

In [42]:
write_json(
    data=usable_profiles, 
    file_path='../data/20252210_mrgdprf_aftr.json', 
)

✓ Written JSON to: ../data/20252210_mrgdprf_aftr.json

True